-- 0024_class_catalog.sql — the class catalog: session kinds, grade bands, and
-- recurring weekly series. Additive and idempotent. Run after 0023.
--
-- WHAT THIS ENCODES
-- The club's storefront sells a weekly schedule — "Algebra I Clinic · Tuesday
-- 5:00 PM" — not one-off rooms a tutor happens to host. A series row is the
-- template; an hourly cron materializes concrete group_session rows a couple
-- of weeks ahead. Three kinds of room exist:
--
--   clinic         — Subject Clinic: focused topic, 4–6 students, $18 retail /
--                    member pricing $14/$12/$10. Keeps min-fill economics.
--   homework_hall  — supervised academic work session (students work
--                    independently, tutor rotates through a help queue; NOT
--                    private-tutoring-for-several). $12 retail; membership
--                    visits (4/8/12 per month) settle it; runs for whoever
--                    shows up: min_seats 1, NO min-fill sweep. Capacity 8 per
--                    tutor — do not overload tutors to improve margin.
--   community_free — the weekly FREE Community Homework Hall ($0, up to ~30
--                    students). A permanent community product, not a trial.
--                    Also exempt from min-fill.
--
-- MIN-FILL EXEMPTION, STRUCTURALLY: resolve_group_fill (0020) only sweeps rooms
-- where cutoff_at IS NOT NULL. Hall and free rooms are created with
-- cutoff_at NULL, so they are exempt without touching the RPC.

-- ── The series template ───────────────────────────────────────────────────────
create table if not exists group_session_series (
  id uuid primary key default uuid_generate_v4(),
  -- Nullable: an admin can lay out the weekly grid before staffing it. The
  -- materializer SKIPS series with no tutor — a room nobody teaches must never
  -- become bookable.
  tutor_id uuid references tutors(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,

  title text not null,                          -- "Algebra I Clinic"
  subject text not null,                        -- Math / English / Science / Social Studies / Homework
  topic text,
  description text,
  kind text not null default 'clinic'
    check (kind in ('clinic','homework_hall','community_free')),
  grade_band text check (grade_band in ('7-8','9-12','college','all')),

  -- Weekly recurrence: one weekday, a LOCAL wall-clock time, and an IANA zone.
  -- Each instance resolves its own UTC offset, so "Tuesday 5 PM Eastern" stays
  -- 5 PM across DST transitions.
  weekday int not null check (weekday between 0 and 6),   -- 0 = Sunday
  local_start_time time not null,
  duration_minutes int not null default 60 check (duration_minutes between 30 and 120),
  timezone text not null default 'America/New_York',

  capacity int not null default 6 check (capacity between 1 and 30),
  min_seats int not null default 1 check (min_seats >= 1),
  seat_price_cents int not null default 1800 check (seat_price_cents between 0 and 10000),

  active boolean not null default true,
  starts_on date not null default current_date,
  ends_on date,

  created_at timestamptz not null default now(),
  check (min_seats <= capacity)
);
alter table group_session_series enable row level security;
drop policy if exists "admin series" on group_session_series;
create policy "admin series" on group_session_series for all using (is_admin());
-- Public schedule browsing goes through a service-role route that sanitizes
-- fields; no direct client access. (0019 defaults are closed; restated anyway.)
revoke select, insert, update, delete on group_session_series from anon, authenticated;
create index if not exists group_session_series_active_idx
  on group_session_series (active, weekday) where active;

-- ── Instances learn their kind, grade band, and origin ───────────────────────
alter table group_session
  add column if not exists kind text not null default 'clinic'
    check (kind in ('clinic','homework_hall','community_free')),
  add column if not exists grade_band text
    check (grade_band in ('7-8','9-12','college','all')),
  add column if not exists series_id uuid references group_session_series(id) on delete set null,
  -- Display metadata only; scheduled_start stays the source of truth.
  add column if not exists timezone text;

-- One instance per series per start — the materializer's idempotency backstop.
create unique index if not exists group_session_series_start_uniq
  on group_session (series_id, scheduled_start) where series_id is not null;

-- ── Relax the drop-in-era bounds ─────────────────────────────────────────────
-- 0017 assumed 2–6 paid students. The club needs $0 community seats, a $12
-- Homework Hall, and free-hall rooms up to ~30 students. Constraint names are
-- the Postgres autogenerated ones from 0017's inline checks.
alter table group_session drop constraint if exists group_session_capacity_check;
alter table group_session add constraint group_session_capacity_check
  check (capacity between 1 and 30);
alter table group_session drop constraint if exists group_session_seat_price_cents_check;
alter table group_session add constraint group_session_seat_price_cents_check
  check (seat_price_cents between 0 and 10000);
