// Generates THIRD_PARTY_NOTICES.md from the installed dependency tree
// (audit LIC-004): every installed package with name, version, and license
// identifier, plus verbatim license texts for direct runtime dependencies.
// Run:  node scripts/generate-notices.mjs   (from web/)

import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const nm = path.join(root, 'node_modules');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json')));

function licenseOf(dir) {
  try {
    const p = JSON.parse(fs.readFileSync(path.join(dir, 'package.json')));
    let id = typeof p.license === 'string' ? p.license : p.license?.type || null;
    if (!id && Array.isArray(p.licenses)) id = p.licenses.map((l) => l.type).join(' OR ');
    // Some packages (e.g. khroma) omit the field but ship a license file.
    if (!id) {
      for (const f of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license', 'license.md']) {
        if (fs.existsSync(path.join(dir, f))) {
          const head = fs.readFileSync(path.join(dir, f), 'utf8').slice(0, 200);
          if (/MIT License/i.test(head)) { id = 'MIT (from LICENSE file)'; break; }
          id = 'SEE LICENSE FILE'; break;
        }
      }
    }
    return { name: p.name, version: p.version, license: id || 'UNKNOWN' };
  } catch { return null; }
}

function licenseTextOf(dir) {
  for (const f of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENSE-MIT', 'license', 'license.md']) {
    const fp = path.join(dir, f);
    if (fs.existsSync(fp)) return fs.readFileSync(fp, 'utf8').trim();
  }
  return null;
}

// Walk every installed package (flat npm tree + scoped dirs + one nested level)
const all = new Map();
function scan(base) {
  if (!fs.existsSync(base)) return;
  for (const d of fs.readdirSync(base)) {
    if (d.startsWith('.')) continue;
    const dir = path.join(base, d);
    if (d.startsWith('@')) { scan(dir); continue; }
    const info = licenseOf(dir);
    if (info) all.set(`${info.name}@${info.version}`, info);
    const nested = path.join(dir, 'node_modules');
    if (fs.existsSync(nested)) scan(nested);
  }
}
scan(nm);

const rows = [...all.values()].sort((a, b) => a.name.localeCompare(b.name));
const counts = {};
for (const r of rows) counts[r.license] = (counts[r.license] || 0) + 1;

let out = `# Third-Party Notices — Kaizen (web)

Kaizen includes open-source components under the licenses below. Kaizen's own
code is proprietary (see /LICENSE at the repository root). This file is
generated by \`scripts/generate-notices.mjs\`; regenerate after dependency
changes.

Where a component is dual-licensed (e.g. jszip "MIT OR GPL-3.0-or-later"),
Kaizen elects the **MIT** license. The prebuilt libvips binaries
(\`@img/sharp-libvips-*\`, LGPL-3.0-or-later) are used unmodified, server-side
only, as a replaceable shared library — they are never shipped to browsers.
Generated: ${new Date().toISOString().slice(0, 10)}.

## License summary (${rows.length} installed packages)

| License | Packages |
|---|---|
${Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([l, c]) => `| ${l} | ${c} |`).join('\n')}

## Direct dependencies — full license texts

`;

const direct = [...Object.keys(pkg.dependencies || {}), ...Object.keys(pkg.devDependencies || {})];
for (const name of direct) {
  const dir = path.join(nm, name);
  const info = licenseOf(dir);
  if (!info) continue;
  out += `### ${info.name}@${info.version} — ${info.license}\n\n`;
  const text = licenseTextOf(dir);
  out += text ? '```\n' + text + '\n```\n\n' : '_No license file shipped in package; see the project repository._\n\n';
}

out += `## All installed packages\n\n| Package | Version | License |\n|---|---|---|\n`;
for (const r of rows) out += `| ${r.name} | ${r.version} | ${r.license} |\n`;

fs.writeFileSync(path.join(root, 'THIRD_PARTY_NOTICES.md'), out);
console.log(`Wrote THIRD_PARTY_NOTICES.md — ${rows.length} packages, ${direct.length} direct with full texts`);
