/* lesson-caller-vote-route.test.mjs — the U1 server half over REAL HTTP.
 * Run: node --test lesson/tests/lesson-caller-vote-route.test.mjs
 *
 * ADDITIVE. No existing test is edited, re-baselined or weakened.
 *
 * A real node:http server on an ephemeral port, with its library pointed at a
 * per-test scratch directory. LOCAL_RUNTIME evidence for the route contract:
 * `GET /api/lesson-library/<recordId>?voterToken=<32hex>` reports the CALLER'S OWN
 * standing vote. Not a provider call, not a browser, not proof any lesson was
 * generated by a model — every lesson body here comes from a fake AI subprocess.
 *
 * The owner's real library under .local-data/lesson-library is never opened; the
 * guard at the bottom asserts that rather than assuming it.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { request } from 'node:http';
import { createHash } from 'node:crypto';
import { createServer } from '../server.mjs';

const scratch = () => mkdtempSync(join(tmpdir(), 'lesson-callervote-'));

// Same guard the existing archive tests use: prove the live library was untouched.
const LIVE_LIBRARY = join(import.meta.dirname, '..', '.local-data', 'lesson-library');
const liveList = () => { try { return readdirSync(LIVE_LIBRARY).sort().join(','); } catch { return ''; } };
const liveBefore = liveList();
test.after(() => assert.equal(liveList(), liveBefore,
  `tests must not write to the owner's real library at ${LIVE_LIBRARY}`));

const LESSON = {
  version: 2, id: 'cv1', title: 'Halves', goal: 'understand halves', subject: 'fractions',
  age: 9, locale: 'en', intro: 'Lets split things in two.',
  steps: [1, 2, 3].map((n) => ({
    id: `s${n}`, prompt: `Shade half of shape ${n}`, explanation: `Half means two equal parts (${n}).`,
    hint: 'Count the parts.', kind: 'numeric', answer: '1/2',
    visual: { kind: 'fraction', parts: 2, filled: 1, caption: `shape ${n}` },
  })),
  path: { reinforce: { goal: 'more halves', reason: 'needs practice' },
    advance: { goal: 'quarters', reason: 'ready' } },
};
const REQ = { goal: 'understand halves', age: 9, locale: 'en', adultTest: true };

/** A fake AI as a real subprocess. Nothing here is a model call. */
const fakeAI = () => 'node|-e|' + [
  "let b='';process.stdin.on('data',c=>b+=c).on('end',()=>{process.stdout.write(JSON.stringify({",
  'ok:true,text:JSON.stringify(' + JSON.stringify(LESSON) + '),',
  "provenance:{provider:'anthropic',model:'claude-opus-5',model_wire:'claude-opus-5-20260101',model_wire_proved:true,live:true}}))})",
].join('');

async function withServer(fn) {
  const dir = scratch();
  const server = createServer({ aiCmd: fakeAI(), libraryDir: dir });
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const port = server.address().port;
  const call = (path, { method = 'GET', body, headers = {} } = {}) => new Promise((resolve, reject) => {
    const payload = body === undefined ? null : JSON.stringify(body);
    const req = request({ host: '127.0.0.1', port, path, method,
      headers: { host: `127.0.0.1:${port}`, origin: `http://127.0.0.1:${port}`,
        ...(payload === null ? {} : { 'content-type': 'application/json',
          'content-length': Buffer.byteLength(payload) }), ...headers } }, (res) => {
      let raw = '';
      res.setEncoding('utf8');
      res.on('data', (c) => { raw += c; });
      res.on('end', () => resolve({ status: res.statusCode, json: () => JSON.parse(raw), text: () => raw }));
    });
    req.on('error', reject);
    if (payload !== null) req.write(payload);
    req.end();
  });
  try { await fn(call, dir); } finally {
    server.close(); await new Promise((r) => server.once('close', r));
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Generate one lesson and return its recordId. */
async function generate(call) {
  const res = await call('/api/lesson', { method: 'POST', body: REQ });
  assert.equal(res.status, 200, res.text().slice(0, 300));
  const recordId = res.json().library?.recordId;
  assert.match(String(recordId), /^[0-9a-f]{64}$/, 'the generation must report a recordId');
  return recordId;
}
const TOKEN_A = '1'.repeat(32);
const TOKEN_B = '2'.repeat(32);

test('the library GET reports the caller\u2019s own vote for their token', async () => {
  await withServer(async (call) => {
    const recordId = await generate(call);
    // Before voting: the key is present (the token was valid) but the value is null.
    const cold = await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_A}`);
    assert.equal(cold.status, 200);
    assert.equal(cold.json().callerVote, null, 'no vote yet must be null, not a direction');

    const up = await call('/api/lesson-rating', { method: 'POST',
      body: { adultTest: true, recordId, vote: 'up', voterToken: TOKEN_A } });
    assert.equal(up.status, 200, up.text().slice(0, 300));

    const mine = await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_A}`);
    assert.equal(mine.json().callerVote, 'up', 'the caller must get their OWN direction back');
    assert.equal(mine.json().feedback.thumbsUp, 1, 'the counts must still be reported');

    // A different voter's token must not inherit the first voter's direction.
    const other = await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_B}`);
    assert.equal(other.json().callerVote, null, 'one voter\u2019s direction leaked to another token');
    assert.equal(other.json().feedback.thumbsUp, 1, 'the public tally is still visible');
  });
});

test('change and removal move the reported direction with them', async () => {
  await withServer(async (call) => {
    const recordId = await generate(call);
    const vote = (v, token = TOKEN_A) => call('/api/lesson-rating', { method: 'POST',
      body: { adultTest: true, recordId, vote: v, voterToken: token } });
    const mine = async () => (await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_A}`)).json();

    await vote('up');
    assert.equal((await mine()).callerVote, 'up');
    await vote('up');                                   // idempotent repeat
    assert.equal((await mine()).callerVote, 'up');
    assert.equal((await mine()).feedback.thumbsUp, 1, 'a repeat must not double-count');
    await vote('down');                                 // change
    let got = await mine();
    assert.equal(got.callerVote, 'down');
    assert.equal(got.feedback.thumbsUp, 0);
    assert.equal(got.feedback.thumbsDown, 1);
    await vote(null);                                   // remove
    got = await mine();
    assert.equal(got.callerVote, null, 'a removed vote must report no direction');
    assert.equal(got.feedback.total, 0);
  });
});

test('no token, or a malformed one, yields no callerVote key at all', async () => {
  await withServer(async (call) => {
    const recordId = await generate(call);
    await call('/api/lesson-rating', { method: 'POST',
      body: { adultTest: true, recordId, vote: 'up', voterToken: TOKEN_A } });
    // Absent must mean UNKNOWN, never a defaulted or guessed direction: a legacy
    // token stored before this route existed must not be read as a vote.
    for (const q of ['', '?voterToken=', '?voterToken=nope', `?voterToken=${'A'.repeat(32)}`,
      `?voterToken=${'1'.repeat(31)}`, '?voterToken=../../etc/passwd']) {
      const res = await call(`/api/lesson-library/${recordId}${q}`);
      assert.equal(res.status, 200, `${q} -> ${res.status}`);
      const body = res.json();
      assert.ok(!('callerVote' in body), `${q} produced a callerVote: ${JSON.stringify(body.callerVote)}`);
      assert.equal(body.feedback.thumbsUp, 1, `${q} lost the counts`);
    }
  });
});

test('the reply never exposes a voter hash and never lists the library', async () => {
  await withServer(async (call, dir) => {
    const recordId = await generate(call);
    await call('/api/lesson-rating', { method: 'POST',
      body: { adultTest: true, recordId, vote: 'down', voterToken: TOKEN_A } });
    const raw = (await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_A}`)).text();
    assert.deepEqual(Object.keys(JSON.parse(raw)).sort(),
      ['callerVote', 'feedback', 'metadata', 'recordId'], 'the reply shape must not grow');
    assert.ok(!raw.includes(TOKEN_A), 'the raw token must not be echoed');
    // The VOTER HASH specifically: it is sha256(recordId \0 token), the one 64-hex
    // value that would let a reader correlate this caller across the stored file.
    // The metadata legitimately carries its own content/prompt hashes, so a blanket
    // "one 64-hex value" rule would be a false alarm rather than a leak check.
    const voterHash = createHash('sha256').update(`${recordId}\u0000${TOKEN_A}`).digest('hex');
    assert.ok(!raw.includes(voterHash), 'the voter hash must never be exposed');
    const fb = JSON.parse(readFileSync(join(dir, `${recordId}.fb`), 'utf8'));
    assert.ok(Object.keys(fb.votes).includes(voterHash), 'the hash really is the stored key');
    for (const who of Object.keys(fb.votes)) {
      assert.ok(!raw.includes(who), `a stored voter hash leaked: ${who}`);
    }
    // Still no enumeration route.
    for (const p of ['/api/lesson-library/', '/api/lesson-library', '/api/lesson-library/list']) {
      assert.equal((await call(p)).status, 404, `${p} must not enumerate`);
    }
  });
});

test('an unknown or malformed recordId is a 404 even with a valid token', async () => {
  await withServer(async (call) => {
    await generate(call);
    for (const id of ['c'.repeat(64), 'short', '..%2f..%2fetc%2fpasswd', 'A'.repeat(64)]) {
      const res = await call(`/api/lesson-library/${id}?voterToken=${TOKEN_A}`);
      assert.equal(res.status, 404, `${id} -> ${res.status}`);
      assert.ok(!res.text().includes('callerVote'));
    }
  });
});

test('corrupt feedback is a typed failure, not "you never voted"', async () => {
  await withServer(async (call, dir) => {
    const recordId = await generate(call);
    await call('/api/lesson-rating', { method: 'POST',
      body: { adultTest: true, recordId, vote: 'up', voterToken: TOKEN_A } });
    const fb = join(dir, `${recordId}.fb`);
    writeFileSync(fb, '{"v":1,"votes":{"not-a-hash":"up"}}');
    const broken = readFileSync(fb);
    const res = await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_A}`);
    assert.notEqual(res.status, 200, 'corrupt feedback must not answer 200 with a fabricated null');
    assert.ok(!res.text().includes('"callerVote":null'), 'a lost vote must not read as "never voted"');
    assert.deepEqual(readFileSync(fb), broken, 'the corrupt bytes must be left for inspection');
  });
});

test('a cross-origin request is still refused on this route', async () => {
  await withServer(async (call) => {
    const recordId = await generate(call);
    const res = await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_A}`,
      { headers: { origin: 'http://evil.example' } });
    assert.equal(res.status, 403, 'the same-origin check must still apply');
  });
});

test('reading a caller vote never mutates the archived record', async () => {
  await withServer(async (call, dir) => {
    const recordId = await generate(call);
    await call('/api/lesson-rating', { method: 'POST',
      body: { adultTest: true, recordId, vote: 'up', voterToken: TOKEN_A } });
    const before = readdirSync(dir).sort()
      .map((f) => `${f}:${readFileSync(join(dir, f)).length}`).join('|');
    for (let i = 0; i < 3; i++) await call(`/api/lesson-library/${recordId}?voterToken=${TOKEN_A}`);
    const after = readdirSync(dir).sort()
      .map((f) => `${f}:${readFileSync(join(dir, f)).length}`).join('|');
    assert.equal(after, before, 'a read changed the library on disk');
    // And the version is still served under the same digest.
    assert.equal((await call(`/api/lesson-library/${recordId}`)).json().recordId, recordId);
  });
});
