/* library-ui.test.mjs — lesson-library / cache-hit disclosure in the UI.
 * Run: node --test lesson/tests/library-ui.test.mjs
 *
 * SYNTHETIC: every server payload here is authored in this file. Nothing is a
 * live provider call, a live server response or a real archive read. These
 * tests prove only what the UI *says* about a payload, never that a lesson was
 * really cached or really saved.
 *
 * The decisions under test are pure and exported, so no DOM is needed:
 *   libraryActKey(out)      which activity-log line a /api/lesson reply earns
 *   provenanceLines(prov)   which footer sentences a provenance object earns
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const realCore = resolve(here, '..', 'core.mjs');
const stubCore = resolve(here, 'ui-fixtures', 'core-stub.mjs');
if (!existsSync(realCore)) {
  registerHooks({
    resolve(spec, ctx, next) {
      if (spec === './core.mjs') return { url: pathToFileURL(stubCore).href, shortCircuit: true };
      return next(spec, ctx);
    },
  });
}
const app = await import('../app.mjs');
const { libraryActKey, provenanceLines, t, STRINGS } = app;

// ── synthetic replies, shaped exactly like the server's two documented cases ──
const FRESH_SAVED = {
  provenance: { provider: 'anthropic', model: 'claude-opus-5', live: true,
    model_wire: 'claude-opus-5-20260101', model_wire_proved: true },
  library: { saved: true, cached: false, id: 'abc0123456789def' },
};
const CACHE_HIT = {
  provenance: { provider: 'anthropic', model: 'claude-opus-5', live: false, cached: true,
    model_wire: 'claude-opus-5-20260101', model_wire_proved: true,
    generated_at: '2026-10-03T19:26:21.000Z' },
  library: { saved: false, cached: true, id: 'abc0123456789def' },
};
const keys = (prov) => provenanceLines(prov).map((l) => l.key);

// ── activity log ────────────────────────────────────────────────────────────
test('a fresh saved lesson says it was saved; a cache hit says no new AI call', () => {
  assert.equal(libraryActKey(FRESH_SAVED), 'actSaved');
  assert.equal(libraryActKey(CACHE_HIT), 'actCached');
  // cached wins even if the library block were ever to disagree
  assert.equal(libraryActKey({ ...CACHE_HIT, library: { saved: true, cached: true, id: 'x' } }), 'actCached');
});

test('a save the server did not confirm is never reported as saved', () => {
  for (const library of [{ saved: false, cached: false, id: 'x' }, { cached: false, id: 'x' },
    { saved: 'yes', cached: false, id: 'x' }]) {
    assert.equal(libraryActKey({ provenance: FRESH_SAVED.provenance, library }), 'actSaveFailed',
      `library=${JSON.stringify(library)} must not claim saved`);
  }
  // A reply with no library block at all (older server) claims nothing either way.
  assert.equal(libraryActKey({ provenance: FRESH_SAVED.provenance }), null);
  assert.equal(libraryActKey(null), null);
});

// ── footer ──────────────────────────────────────────────────────────────────
test('a cache hit discloses reuse and never claims a fresh generation', () => {
  const ks = keys(CACHE_HIT.provenance);
  assert.ok(ks.includes('sourceCached'), 'cache hit must disclose it came from the library');
  assert.ok(!ks.includes('sourceFresh'), 'a cache hit must not be labelled freshly generated');
  // the original identity still shows, as the identity of the ORIGINAL call
  assert.ok(ks.includes('sourceNote'));
  assert.equal(provenanceLines(CACHE_HIT.provenance).find((l) => l.key === 'sourceCached').vars.at,
    '2026-10-03', 'date only: no invented precision, no raw ISO noise');
});

test('a fresh lesson gets no cache sentence', () => {
  assert.deepEqual(keys(FRESH_SAVED.provenance), ['sourceNote']);
});

test('an unproved model is not credited as the proven author', () => {
  const unproved = { ...FRESH_SAVED.provenance, model_wire: null, model_wire_proved: false };
  const ks = keys(unproved);
  assert.ok(ks.includes('sourceUnproved'), 'unproved wire model needs the hedged sentence');
  assert.ok(!ks.includes('sourceNote'), 'unproved must not use the flat "generated by" claim');
  // a payload that never mentions proof (fixtures, older server) keeps the plain line
  assert.deepEqual(keys({ provider: 'local-stub', model: 'synthetic-fixture' }), ['sourceNote']);
});

test('footer sentences never render null, undefined or an empty claim', () => {
  for (const prov of [null, {}, { model: 'm' }, { provider: 'p' },
    { provider: 'p', model: 'm', cached: true }]) {
    for (const locale of ['en', 'es']) {
      for (const { key, vars } of provenanceLines(prov)) {
        const s = t(locale, key, vars);
        assert.ok(s && s.trim().length > 0, `${locale}.${key} empty`);
        assert.ok(!/null|undefined|\{\w+\}/.test(s), `${locale}.${key} leaked a placeholder: ${s}`);
      }
    }
  }
});

// ── both locales, really translated ─────────────────────────────────────────
test('every new disclosure string is authored in EN and ES', () => {
  const added = ['sourceCached', 'sourceUnproved', 'actSaved', 'actSaveFailed', 'actCached', 'disclose6'];
  for (const k of added) {
    for (const locale of ['en', 'es']) {
      assert.ok(String(STRINGS[locale][k] ?? '').trim().length > 0, `${locale}.${k} missing`);
    }
    assert.notEqual(STRINGS.es[k], STRINGS.en[k], `es.${k} is untranslated English`);
  }
  assert.match(t('en', 'actCached'), /saved lesson library/i);
  assert.match(t('en', 'actSaved'), /lesson library/i);
  assert.match(t('es', 'actCached'), /biblioteca/i);
  // the hedge must actually hedge, in both locales
  assert.match(t('en', 'sourceUnproved', { model: 'm', provider: 'p' }), /not confirmed/i);
  assert.match(t('es', 'sourceUnproved', { model: 'm', provider: 'p' }), /no se confirm/i);
});

test('the library privacy notice is accurate about what it does and does not protect', () => {
  for (const locale of ['en', 'es']) {
    const s = String(STRINGS[locale].disclose6);
    // It must NOT promise anonymity: the free-text goal can carry anything.
    assert.ok(!/anonym|an\u00f3nim/i.test(s), `${locale}.disclose6 must not promise anonymity`);
    assert.ok(!/never|nunca/i.test(s) || /name|nombre/i.test(s),
      `${locale}.disclose6 may only scope a "never" to the profile name`);
  }
  assert.match(STRINGS.en.disclose6, /reuse/i);
  assert.match(STRINGS.en.disclose6, /name/i);
  assert.match(STRINGS.es.disclose6, /nombre/i);
});

// ── wiring + the rules the whole file already lives under ───────────────────
test('the footer and the activity log actually use these helpers, via textContent', () => {
  const src = readFileSync(resolve(here, '..', 'app.mjs'), 'utf8');
  assert.match(src, /provenanceLines\(S\.provenance\)/, 'viewFoot must drive off the helper');
  assert.match(src, /libraryActKey\(out\)/, 'generate must log off the helper');
  assert.match(src, /disclose6/, 'the privacy notice must be rendered, not just authored');
  for (const banned of ['innerHTML', 'outerHTML', 'insertAdjacentHTML', 'document.write']) {
    assert.ok(!src.includes(banned), `app.mjs grew an HTML sink: ${banned}`);
  }
  assert.ok(!/getUserMedia|MediaDevices|navigator\.media/.test(src), 'app.mjs touches camera/mic');
});
