import type { Resource } from "./index";

// Real, free sources, checked to load on 2026-10-07. We link to them; nothing is copied.
// Skill fits are exact ids or prefixes ending in "."; "grade:N" fits every skill of that grade.

const PHET = "University of Colorado Boulder (PhET)";
const phet = (slug: string, title: string, fits: string[], grades: Resource["grades"], subject: Resource["subject"], en: string, es: string): Resource => ({
  id: `phet-${slug}`,
  title,
  source: PHET,
  url: `https://phet.colorado.edu/en/simulations/${slug}`,
  urlEs: `https://phet.colorado.edu/es/simulations/${slug}`,
  kind: "simulation",
  subject,
  grades,
  languages: ["en", "es"],
  fits,
  about: { en, es },
});

const khanGrade = (g: "K" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8", path: string): Resource => ({
  id: `khan-math-${g}`,
  title: g === "K" ? "Kindergarten math" : `Grade ${g} math`,
  source: "Khan Academy",
  url: `https://www.khanacademy.org/math/${path}`,
  urlEs: "https://es.khanacademy.org/math",
  kind: "video",
  subject: "math",
  grades: [g, g],
  languages: ["en", "es"],
  fits: [`grade:${g}`],
  about: { en: "Short videos and practice for every grade-level topic. Free; an account saves progress.", es: "Videos cortos y práctica para cada tema del grado. Gratis; una cuenta guarda el progreso." },
});

export const RESOURCES: Resource[] = [
  // Math — video lessons by grade
  khanGrade("K", "cc-kindergarten-math"),
  khanGrade("1", "cc-1st-grade-math"),
  khanGrade("2", "cc-2nd-grade-math"),
  khanGrade("3", "cc-third-grade-math"),
  khanGrade("4", "cc-fourth-grade-math"),
  khanGrade("5", "cc-fifth-grade-math"),
  khanGrade("6", "cc-sixth-grade-math"),
  khanGrade("7", "cc-seventh-grade-math"),
  khanGrade("8", "cc-eighth-grade-math"),
  {
    id: "khan-algebra",
    title: "Algebra 1",
    source: "Khan Academy",
    url: "https://www.khanacademy.org/math/algebra",
    urlEs: "https://es.khanacademy.org/math",
    kind: "video",
    subject: "math",
    grades: ["8", "adult"],
    languages: ["en", "es"],
    fits: ["grade:9", "m.eq.", "m.poly.", "m.factor.tri", "m.quad.solve", "m.systems", "m.line.equation", "m.func.eval", "m.ineq."],
    about: { en: "A full Algebra 1 course: videos, practice and unit tests.", es: "Un curso completo de Álgebra 1: videos, práctica y pruebas por unidad." },
  },
  // Math — simulations
  phet("make-a-ten", "Make a Ten", ["m.make.10", "m.add.20", "m.add.10"], ["K", "2"], "math", "Build sums by making ten first, with movable counters.", "Forma sumas completando diez, con fichas que se mueven."),
  phet("arithmetic", "Arithmetic", ["m.mult.facts", "m.mult.easy", "m.div.facts", "m.add.20"], ["2", "5"], "math", "A game for multiplication, division and factor facts.", "Un juego de multiplicación, división y factores."),
  phet("area-model-multiplication", "Area Model Multiplication", ["m.mult.multi", "m.mult.groups", "m.poly.mult"], ["3", "9"], "math", "See multiplication as the area of a rectangle, from facts to algebra.", "Mira la multiplicación como el área de un rectángulo, de las tablas al álgebra."),
  phet("fractions-intro", "Fractions: Intro", ["m.frac.unit", "m.frac.numberline", "m.frac.mixed"], ["2", "5"], "math", "Build fractions with pies, bars and number lines.", "Construye fracciones con pasteles, barras y rectas numéricas."),
  phet("fractions-equality", "Fractions: Equality", ["m.frac.equiv", "m.frac.compare"], ["3", "6"], "math", "Find equal fractions and compare them by building them.", "Encuentra fracciones iguales y compáralas construyéndolas."),
  phet("build-a-fraction", "Build a Fraction", ["m.frac.equiv", "m.frac.mixed", "m.frac.addlike"], ["3", "6"], "math", "Puzzle levels that build fractions and mixed numbers.", "Niveles de rompecabezas para formar fracciones y números mixtos."),
  phet("number-line-integers", "Number Line: Integers", ["m.int.numberline", "m.int.addsub", "m.compare.100"], ["5", "7"], "math", "Place and compare positive and negative numbers.", "Ubica y compara números positivos y negativos."),
  phet("area-builder", "Area Builder", ["m.area.rect", "m.area.poly"], ["3", "6"], "math", "Build shapes and find their area and perimeter.", "Construye figuras y encuentra su área y perímetro."),
  phet("equality-explorer", "Equality Explorer", ["m.missing.addend", "m.eq.onestep", "m.eq.twostep", "m.eq.multistep"], ["2", "9"], "math", "A balance scale that shows what keeps an equation true.", "Una balanza que muestra qué mantiene verdadera una ecuación."),
  phet("function-builder", "Function Builder", ["m.func.eval", "m.expr.eval", "m.linear.table"], ["6", "9"], "math", "Send inputs through function machines and find the rule.", "Pasa entradas por máquinas de funciones y descubre la regla."),
  phet("graphing-lines", "Graphing Lines", ["m.slope", "m.line.equation"], ["8", "9"], "math", "Move points and lines to see slope and equations change.", "Mueve puntos y rectas para ver cómo cambian la pendiente y la ecuación."),
  phet("graphing-slope-intercept", "Graphing Slope-Intercept", ["m.line.equation", "m.linear.table", "m.slope"], ["8", "9"], "math", "Explore y = mx + b by changing m and b.", "Explora y = mx + b cambiando m y b."),
  {
    id: "mlc-apps",
    title: "Math Learning Center apps",
    source: "The Math Learning Center",
    url: "https://www.mathlearningcenter.org/apps",
    kind: "tool",
    subject: "math",
    grades: ["K", "5"],
    languages: ["en", "es"],
    fits: ["m.count.", "m.place.tens", "m.add.", "m.sub.", "m.frac.unit", "m.frac.equiv", "m.time.clock", "m.mult.groups"],
    about: { en: "Free virtual manipulatives: number frames, base-ten pieces, fraction bars, clocks.", es: "Materiales manipulativos virtuales gratis: marcos numéricos, bloques de base diez, barras de fracciones, relojes." },
  },
  {
    id: "nrich",
    title: "NRICH problems and games",
    source: "University of Cambridge (NRICH)",
    url: "https://nrich.maths.org/",
    kind: "practice",
    subject: "math",
    grades: ["K", "9"],
    languages: ["en"],
    fits: ["problem solving", "puzzles", "challenge", "games"],
    about: { en: "Rich problems and games for thinking mathematically, sorted by age.", es: "Problemas y juegos para pensar matemáticamente, ordenados por edad (en inglés)." },
  },
  {
    id: "openstax-prealgebra",
    title: "Prealgebra 2e (free textbook)",
    source: "OpenStax, Rice University",
    url: "https://openstax.org/details/books/prealgebra-2e",
    kind: "book",
    subject: "math",
    grades: ["6", "adult"],
    languages: ["en"],
    fits: ["m.int.addsub", "m.int.multdiv", "m.frac.div", "m.dec.mult", "m.ratio.equiv", "m.ratio.unit", "m.percent", "m.expr.eval", "m.expr.simplify", "m.eq.onestep", "m.eq.twostep", "m.order.ops", "m.gcf.lcm"],
    about: { en: "A complete, free textbook with worked examples and answers to odd problems.", es: "Un libro de texto completo y gratis con ejemplos resueltos (en inglés)." },
  },
  {
    id: "openstax-algebra",
    title: "Elementary Algebra 2e (free textbook)",
    source: "OpenStax, Rice University",
    url: "https://openstax.org/details/books/elementary-algebra-2e",
    kind: "book",
    subject: "math",
    grades: ["8", "adult"],
    languages: ["en"],
    fits: ["m.eq.multistep", "m.systems", "m.poly.addsub", "m.poly.mult", "m.factor.tri", "m.quad.solve", "m.slope", "m.line.equation", "m.ineq.multistep", "m.exp.rules", "m.sci.notation", "m.sqrt"],
    about: { en: "Free algebra textbook: linear equations, graphs, systems, polynomials, factoring.", es: "Libro de álgebra gratis: ecuaciones, gráficas, sistemas, polinomios, factorización (en inglés)." },
  },
  {
    id: "desmos",
    title: "Desmos graphing calculator",
    source: "Desmos",
    url: "https://www.desmos.com/calculator",
    kind: "tool",
    subject: "math",
    grades: ["6", "adult"],
    languages: ["en", "es"],
    fits: ["m.slope", "m.line.equation", "m.linear.table", "m.func.eval", "m.quad.solve", "m.systems", "graph"],
    about: { en: "Graph any equation and move sliders to see what each number does.", es: "Grafica cualquier ecuación y mueve deslizadores para ver qué hace cada número." },
  },
  {
    id: "geogebra",
    title: "GeoGebra",
    source: "GeoGebra",
    url: "https://www.geogebra.org/",
    kind: "tool",
    subject: "math",
    grades: ["5", "adult"],
    languages: ["en", "es"],
    fits: ["m.area.poly", "m.circle", "m.pythag", "m.volume", "geometry", "shapes"],
    about: { en: "Geometry and graphing tools, plus ready-made activities.", es: "Herramientas de geometría y gráficas, con actividades listas." },
  },
  {
    id: "illustrative-math",
    title: "Illustrative Mathematics family materials",
    source: "Illustrative Mathematics",
    url: "https://illustrativemathematics.org/",
    kind: "text",
    subject: "math",
    grades: ["K", "9"],
    languages: ["en"],
    fits: ["curriculum", "homework", "school math"],
    about: { en: "The problem-based K–12 curriculum many schools use, with notes for families.", es: "El plan de estudios de matemáticas K–12 que usan muchas escuelas, con notas para familias (en inglés)." },
  },
  // English — reading and read-alouds
  {
    id: "storyline",
    title: "Storyline Online",
    source: "SAG-AFTRA Foundation",
    url: "https://storylineonline.net/",
    kind: "video",
    subject: "english",
    grades: ["K", "4"],
    languages: ["en"],
    fits: ["e.rhyme", "e.sight.words", "e.letter.sounds", "e.cvc.words", "read aloud", "stories", "books"],
    about: { en: "Actors read picture books aloud, with the pages on screen.", es: "Actores leen en voz alta libros ilustrados, con las páginas en pantalla (en inglés)." },
  },
  {
    id: "unite-literacy",
    title: "Unite for Literacy picture books",
    source: "Unite for Literacy",
    url: "https://www.uniteforliteracy.com/",
    kind: "book",
    subject: "english",
    grades: ["K", "3"],
    languages: ["en", "es"],
    fits: ["e.sight.words", "e.cvc.words", "e.letter.sounds", "e.plurals", "read aloud", "books", "stories", "reading"],
    about: { en: "Free picture books with narration in English, Spanish and many other languages.", es: "Libros ilustrados gratis narrados en español, inglés y muchos otros idiomas." },
  },
  {
    id: "starfall",
    title: "Starfall ABCs and reading",
    source: "Starfall Education Foundation",
    url: "https://www.starfall.com/",
    kind: "practice",
    subject: "english",
    grades: ["K", "2"],
    languages: ["en"],
    fits: ["e.letter.sounds", "e.cvc.words", "e.sight.words", "e.rhyme", "phonics"],
    about: { en: "Phonics games and early readers. Many activities are free; some need a membership.", es: "Juegos de fonética y lecturas iniciales. Muchas actividades son gratis (en inglés)." },
    note: { en: "Some parts need a paid membership.", es: "Algunas partes requieren membresía." },
  },
  {
    id: "gutenberg-children",
    title: "Children's literature",
    source: "Project Gutenberg",
    url: "https://www.gutenberg.org/ebooks/bookshelf/20",
    kind: "library",
    subject: "english",
    grades: ["3", "adult"],
    languages: ["en"],
    fits: ["books", "novels", "classics", "reading", "e.main.idea", "e.figurative"],
    about: { en: "Classic children's books in the public domain, free to read online or download.", es: "Libros infantiles clásicos de dominio público, gratis para leer o descargar." },
  },
  {
    id: "gutenberg-picture",
    title: "Picture books",
    source: "Project Gutenberg",
    url: "https://www.gutenberg.org/ebooks/bookshelf/22",
    kind: "library",
    subject: "english",
    grades: ["K", "3"],
    languages: ["en"],
    fits: ["picture books", "books", "read aloud"],
    about: { en: "Old picture books in the public domain, free.", es: "Libros ilustrados antiguos de dominio público, gratis (en inglés)." },
  },
  {
    id: "lit2go",
    title: "Lit2Go audiobooks",
    source: "University of South Florida",
    url: "https://etc.usf.edu/lit2go/",
    kind: "library",
    subject: "english",
    grades: ["3", "adult"],
    languages: ["en"],
    fits: ["audiobooks", "poems", "stories", "e.main.idea", "e.context.clues", "e.rhetorical.devices"],
    about: { en: "Free audiobooks of stories and poems, with the text to read along.", es: "Audiolibros gratis de cuentos y poemas, con el texto para seguir (en inglés)." },
  },
  {
    id: "readworks",
    title: "ReadWorks passages",
    source: "ReadWorks",
    url: "https://www.readworks.org/",
    kind: "text",
    subject: "english",
    grades: ["K", "9"],
    languages: ["en", "es"],
    fits: ["e.main.idea", "e.fact.opinion", "e.context.clues", "reading comprehension", "passages"],
    about: { en: "Short nonfiction and fiction passages with questions, many with audio. Free account.", es: "Lecturas cortas con preguntas, muchas con audio. Cuenta gratis." },
    note: { en: "Needs a free account.", es: "Requiere una cuenta gratis." },
  },
  {
    id: "commonlit",
    title: "CommonLit texts",
    source: "CommonLit",
    url: "https://www.commonlit.org/",
    kind: "text",
    subject: "english",
    grades: ["3", "adult"],
    languages: ["en", "es"],
    fits: ["e.claim.evidence", "e.appeals", "e.main.idea", "e.thesis", "e.rhetorical.devices", "reading", "argument"],
    about: { en: "Free reading passages for grades 3–12 with discussion questions. Free account.", es: "Lecturas gratis para grados 3–12 con preguntas. Cuenta gratis." },
    note: { en: "Needs a free account.", es: "Requiere una cuenta gratis." },
  },
  {
    id: "khan-ela",
    title: "Reading and vocabulary",
    source: "Khan Academy",
    url: "https://www.khanacademy.org/ela",
    kind: "practice",
    subject: "english",
    grades: ["2", "9"],
    languages: ["en"],
    fits: ["e.context.clues", "e.main.idea", "e.synonyms", "e.prefixes", "reading", "vocabulary"],
    about: { en: "Reading passages and vocabulary practice by grade.", es: "Lecturas y práctica de vocabulario por grado (en inglés)." },
  },
  {
    id: "owl-grammar",
    title: "Grammar guides",
    source: "Purdue Online Writing Lab",
    url: "https://owl.purdue.edu/owl/general_writing/grammar/index.html",
    kind: "text",
    subject: "english",
    grades: ["6", "adult"],
    languages: ["en"],
    fits: ["e.pronouns", "e.active.passive", "e.sentence.types", "e.commas", "e.subject.verb", "e.concision", "grammar"],
    about: { en: "Clear explanations of grammar, punctuation and sentence style.", es: "Explicaciones claras de gramática y puntuación (en inglés)." },
  },
  {
    id: "owl-fallacies",
    title: "Logical fallacies",
    source: "Purdue Online Writing Lab",
    url: "https://owl.purdue.edu/owl/general_writing/academic_writing/logic_in_argumentative_writing/fallacies.html",
    kind: "text",
    subject: "english",
    grades: ["7", "adult"],
    languages: ["en"],
    fits: ["e.fallacies", "fallacies", "logic", "debate"],
    about: { en: "Common fallacies with short examples of each.", es: "Falacias comunes con ejemplos cortos (en inglés)." },
  },
  {
    id: "owl-rhetoric",
    title: "The rhetorical situation",
    source: "Purdue Online Writing Lab",
    url: "https://owl.purdue.edu/owl/general_writing/academic_writing/rhetorical_situation/index.html",
    kind: "text",
    subject: "english",
    grades: ["7", "adult"],
    languages: ["en"],
    fits: ["e.appeals", "e.rhetorical.devices", "rhetoric", "persuasion", "audience"],
    about: { en: "Purpose, audience and appeals: how persuasion works.", es: "Propósito, público y llamados: cómo funciona la persuasión (en inglés)." },
  },
  {
    id: "owl-arguments",
    title: "Building an argument",
    source: "Purdue Online Writing Lab",
    url: "https://owl.purdue.edu/owl/general_writing/academic_writing/establishing_arguments/index.html",
    kind: "text",
    subject: "english",
    grades: ["6", "adult"],
    languages: ["en"],
    fits: ["e.thesis", "e.claim.evidence", "e.transitions", "argument", "essay"],
    about: { en: "How to make a claim, support it and answer the other side.", es: "Cómo hacer una afirmación, apoyarla y responder al otro lado (en inglés)." },
  },
  {
    id: "open-library",
    title: "Open Library",
    source: "Internet Archive",
    url: "https://openlibrary.org/",
    kind: "library",
    subject: "english",
    grades: ["K", "adult"],
    languages: ["en", "es"],
    fits: ["books", "borrow", "library", "reading"],
    about: { en: "Borrow digital copies of millions of books for free.", es: "Pide prestadas copias digitales de millones de libros, gratis." },
    note: { en: "Borrowing needs a free account.", es: "Pedir prestado requiere una cuenta gratis." },
  },
  {
    id: "libby",
    title: "Libby (your public library)",
    source: "OverDrive",
    url: "https://libbyapp.com/",
    kind: "library",
    subject: "english",
    grades: ["K", "adult"],
    languages: ["en", "es"],
    fits: ["books", "audiobooks", "library", "reading"],
    about: { en: "E-books and audiobooks free with your public library card.", es: "Libros electrónicos y audiolibros gratis con tu tarjeta de la biblioteca pública." },
    note: { en: "Needs a public library card.", es: "Requiere tarjeta de la biblioteca pública." },
  },
  {
    id: "dpla",
    title: "Digital Public Library of America",
    source: "DPLA",
    url: "https://dp.la/",
    kind: "library",
    subject: "english",
    grades: ["6", "adult"],
    languages: ["en"],
    fits: ["primary sources", "history", "research", "e.claim.evidence"],
    about: { en: "Primary sources and collections from America's libraries and museums.", es: "Fuentes primarias de bibliotecas y museos de Estados Unidos (en inglés)." },
  },
  // Science
  phet("states-of-matter-basics", "States of Matter: Basics", ["s.states.matter", "s.chem.phys", "s.water.cycle"], ["2", "9"], "science", "Heat and cool atoms to see solids, liquids and gases.", "Calienta y enfría átomos para ver sólidos, líquidos y gases."),
  phet("density", "Density", ["s.density"], ["6", "9"], "science", "Change mass and volume and watch blocks float or sink.", "Cambia masa y volumen y mira bloques flotar o hundirse."),
  phet("forces-and-motion-basics", "Forces and Motion: Basics", ["s.push.pull", "s.forces", "s.newton", "s.newton.laws", "s.speed"], ["K", "9"], "science", "Push, pull and race: see how forces change motion.", "Empuja, jala y compite: mira cómo las fuerzas cambian el movimiento."),
  phet("friction", "Friction", ["s.forces", "s.energy.forms"], ["3", "9"], "science", "Rub surfaces together and watch heat build up.", "Frota superficies y mira cómo se produce calor."),
  phet("energy-skate-park-basics", "Energy Skate Park: Basics", ["s.energy.forms"], ["4", "9"], "science", "A skater on a ramp shows kinetic and potential energy.", "Un patinador en una rampa muestra energía cinética y potencial."),
  phet("circuit-construction-kit-dc", "Circuit Construction Kit", ["s.energy.forms"], ["4", "9"], "science", "Build circuits with batteries, bulbs and switches.", "Construye circuitos con pilas, focos e interruptores."),
  phet("build-an-atom", "Build an Atom", ["s.atoms", "s.formula.atoms"], ["7", "9"], "science", "Add protons, neutrons and electrons to make elements.", "Agrega protones, neutrones y electrones para formar elementos."),
  phet("balancing-chemical-equations", "Balancing Chemical Equations", ["s.formula.atoms", "s.chem.phys"], ["8", "adult"], "science", "Balance reactions by counting atoms on each side.", "Balancea reacciones contando los átomos de cada lado."),
  phet("ph-scale-basics", "pH Scale: Basics", ["s.ph"], ["7", "adult"], "science", "Test everyday liquids and see where they sit on the pH scale.", "Prueba líquidos de todos los días y mira su lugar en la escala de pH."),
  phet("gravity-and-orbits", "Gravity and Orbits", ["s.earth.sun.moon"], ["4", "9"], "science", "Move the Sun, Earth and Moon and see how orbits work.", "Mueve el Sol, la Tierra y la Luna y mira cómo funcionan las órbitas."),
  phet("natural-selection", "Natural Selection", ["s.genetics", "s.ecosystems"], ["7", "adult"], "science", "Watch traits spread in a bunny population over generations.", "Mira cómo se extienden rasgos en una población de conejos."),
  {
    id: "nasa-space-place",
    title: "NASA Space Place",
    source: "NASA",
    url: "https://spaceplace.nasa.gov/",
    urlEs: "https://spaceplace.nasa.gov/sp/",
    kind: "text",
    subject: "science",
    grades: ["K", "6"],
    languages: ["en", "es"],
    fits: ["s.earth.sun.moon", "s.weather", "space", "planets", "moon", "sun", "stars"],
    about: { en: "Space and Earth science for kids: explainers, games and crafts.", es: "Ciencia del espacio y la Tierra para niños: explicaciones, juegos y manualidades." },
  },
  {
    id: "nasa-moon-phases",
    title: "Moon phases",
    source: "NASA Science",
    url: "https://science.nasa.gov/moon/moon-phases/",
    kind: "text",
    subject: "science",
    grades: ["3", "adult"],
    languages: ["en"],
    fits: ["s.earth.sun.moon", "moon", "phases"],
    about: { en: "Why the Moon's shape seems to change, with pictures of each phase.", es: "Por qué parece cambiar la forma de la Luna, con imágenes de cada fase (en inglés)." },
  },
  {
    id: "nasa-kids-earth",
    title: "Earth for kids",
    source: "NASA Science",
    url: "https://science.nasa.gov/kids/earth/",
    kind: "text",
    subject: "science",
    grades: ["2", "8"],
    languages: ["en"],
    fits: ["s.weather", "s.water.cycle", "climate", "earth", "weather"],
    about: { en: "Earth's air, water and climate explained for young learners.", es: "El aire, el agua y el clima de la Tierra explicados para niños (en inglés)." },
  },
  {
    id: "usgs-water",
    title: "Water Science School",
    source: "U.S. Geological Survey",
    url: "https://www.usgs.gov/water-science-school",
    kind: "text",
    subject: "science",
    grades: ["4", "adult"],
    languages: ["en", "es"],
    fits: ["s.water.cycle", "water", "rivers", "groundwater"],
    about: { en: "The water cycle and water on Earth, with diagrams (some in Spanish).", es: "El ciclo del agua y el agua en la Tierra, con diagramas (algunos en español)." },
  },
  {
    id: "exploratorium-snacks",
    title: "Science Snacks",
    source: "Exploratorium",
    url: "https://www.exploratorium.edu/snacks",
    kind: "text",
    subject: "science",
    grades: ["3", "adult"],
    languages: ["en"],
    fits: ["s.variables", "s.forces", "s.energy.forms", "s.materials", "experiments", "hands-on"],
    about: { en: "Hands-on experiments with cheap, everyday materials.", es: "Experimentos prácticos con materiales baratos de la casa (en inglés)." },
  },
  {
    id: "khan-science",
    title: "Middle school science",
    source: "Khan Academy",
    url: "https://www.khanacademy.org/science",
    kind: "video",
    subject: "science",
    grades: ["6", "adult"],
    languages: ["en", "es"],
    fits: ["s.cells", "s.genetics", "s.atoms", "s.ecosystems", "s.plate.tectonics", "s.newton", "s.chem.phys", "biology", "physics", "chemistry"],
    about: { en: "Videos and practice in life, physical and earth science.", es: "Videos y práctica de ciencias de la vida, físicas y de la Tierra." },
  },
  {
    id: "openstax-biology",
    title: "Concepts of Biology (free textbook)",
    source: "OpenStax, Rice University",
    url: "https://openstax.org/details/books/concepts-biology",
    kind: "book",
    subject: "science",
    grades: ["8", "adult"],
    languages: ["en"],
    fits: ["s.cells", "s.genetics", "s.ecosystems", "biology"],
    about: { en: "A free introductory biology textbook: cells, genetics, ecology.", es: "Un libro de biología introductoria gratis: células, genética, ecología (en inglés)." },
  },
  {
    id: "ck12",
    title: "CK-12 science and math",
    source: "CK-12 Foundation",
    url: "https://www.ck12.org/",
    kind: "text",
    subject: "science",
    grades: ["3", "adult"],
    languages: ["en", "es"],
    fits: ["s.cells", "s.rocks", "s.plate.tectonics", "s.food.chains", "s.habitats", "s.life.cycles", "science"],
    about: { en: "Free readings, videos and practice for grades 3–12.", es: "Lecturas, videos y práctica gratis para grados 3 a 12." },
  },
  {
    id: "natgeo-kids",
    title: "National Geographic Kids",
    source: "National Geographic",
    url: "https://kids.nationalgeographic.com/",
    kind: "text",
    subject: "science",
    grades: ["K", "6"],
    languages: ["en"],
    fits: ["s.habitats", "s.living", "s.food.chains", "s.life.cycles", "animals", "dinosaurs", "nature"],
    about: { en: "Animal facts, photos and videos.", es: "Datos, fotos y videos de animales (en inglés)." },
    note: { en: "Has ads.", es: "Tiene anuncios." },
  },
  // Math K–9 deep links (+45): every url and urlEs fetched and checked to load the described page on 2026-10-07.
  // Math — kindergarten
  phet("number-play", "Number Play", ["m.count.10", "m.count.20", "m.next.number"], ["K", "1"], "math", "Count with objects, ten frames, numerals and number words up to 20, and hear each number said aloud.", "Cuenta con objetos, marcos de diez, cifras y palabras hasta 20, y escucha cada número en voz alta."),
  {
    id: "mlc-number-frames",
    title: "Number Frames",
    source: "The Math Learning Center",
    url: "https://apps.mathlearningcenter.org/number-frames/",
    kind: "tool",
    subject: "math",
    grades: ["K", "2"],
    languages: ["en"],
    fits: ["m.count.10", "m.count.20", "m.add.5", "m.sub.5", "m.make.10"],
    about: { en: "Fill five-, ten- and twenty-frames with counters to count, add and make ten.", es: "Llena marcos de cinco, diez y veinte con fichas para contar, sumar y formar diez (en inglés)." },
  },
  {
    id: "im-k-numbers-to-10",
    title: "Numbers 1–10 (kindergarten, family materials)",
    source: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/k5/families/kindergarten/unit-2/family-materials.html",
    kind: "text",
    subject: "math",
    grades: ["K", "K"],
    languages: ["en"],
    fits: ["m.count.10", "m.compare.10"],
    about: { en: "What kindergartners learn about counting and comparing groups up to 10, with an activity to try at home.", es: "Lo que aprenden en kínder sobre contar y comparar grupos hasta 10, con una actividad para la casa (en inglés)." },
  },
  {
    id: "oak-counting-to-10",
    title: "Counting, recognising and comparing numbers 0–10",
    source: "Oak National Academy",
    url: "https://www.thenational.academy/pupils/programmes/maths-primary-year-1/units/counting-recognising-and-comparing-numbers-0-10/lessons",
    kind: "video",
    subject: "math",
    grades: ["K", "1"],
    languages: ["en"],
    fits: ["m.count.10", "m.compare.10", "m.next.number"],
    about: { en: "Fifteen short video lessons with quizzes on counting, zero, ordering and one more or one less within 10.", es: "Quince videolecciones cortas con pruebas sobre contar, el cero, ordenar y uno más o uno menos hasta 10 (en inglés)." },
    note: { en: "UK lessons: Year 1 matches US kindergarten.", es: "Lecciones del Reino Unido: Year 1 equivale a kínder en EE. UU." },
  },
  // Math — grade 1
  {
    id: "mlc-number-rack",
    title: "Number Rack",
    source: "The Math Learning Center",
    url: "https://apps.mathlearningcenter.org/number-rack/",
    kind: "tool",
    subject: "math",
    grades: ["K", "2"],
    languages: ["en"],
    fits: ["m.make.10", "m.add.10", "m.sub.10", "m.add.20", "m.sub.20"],
    about: { en: "A bead rack in rows of ten for seeing numbers as fives and tens while adding and subtracting.", es: "Un ábaco de filas de diez cuentas para ver los números en cincos y dieces al sumar y restar (en inglés)." },
  },
  {
    id: "nrich-strike-it-out",
    title: "Strike It Out",
    source: "University of Cambridge (NRICH)",
    url: "https://nrich.maths.org/problems/strike-it-out",
    kind: "practice",
    subject: "math",
    grades: ["1", "3"],
    languages: ["en"],
    fits: ["m.add.20", "m.sub.20", "games"],
    about: { en: "A game for two on a 0–20 number line: cross out two numbers and circle their sum or difference.", es: "Un juego para dos en una recta del 0 al 20: tacha dos números y encierra su suma o su diferencia (en inglés)." },
  },
  {
    id: "mathsisfun-place-value",
    title: "Place value",
    source: "Math is Fun",
    url: "https://www.mathsisfun.com/place-value.html",
    urlEs: "https://www.disfrutalasmatematicas.com/valor-posicional.html",
    kind: "text",
    subject: "math",
    grades: ["1", "3"],
    languages: ["en", "es"],
    fits: ["m.place.tens", "m.compare.100", "m.addsub.1000"],
    about: { en: "Ones, tens and hundreds columns that show what each digit in a number is worth.", es: "Columnas de unidades, decenas y centenas que muestran cuánto vale cada dígito de un número." },
    note: { en: "Has ads.", es: "Tiene anuncios." },
  },
  {
    id: "im-g1-numbers-to-99",
    title: "Numbers to 99 (grade 1, family materials)",
    source: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/k5/families/grade-1/unit-4/family-materials.html",
    kind: "text",
    subject: "math",
    grades: ["1", "1"],
    languages: ["en"],
    fits: ["m.place.tens", "m.compare.100"],
    about: { en: "How first graders learn tens and ones for numbers to 99, with an activity to try at home.", es: "Cómo aprenden en primer grado las decenas y unidades hasta 99, con una actividad para la casa (en inglés)." },
  },
  // Math — grade 2
  {
    id: "mlc-number-pieces",
    title: "Number Pieces",
    source: "The Math Learning Center",
    url: "https://apps.mathlearningcenter.org/number-pieces/",
    kind: "tool",
    subject: "math",
    grades: ["1", "4"],
    languages: ["en"],
    fits: ["m.place.tens", "m.add.2digit", "m.sub.2digit", "m.addsub.1000"],
    about: { en: "Base-ten pieces for ones, tens and hundreds to build numbers and add or subtract by regrouping.", es: "Piezas de base diez para unidades, decenas y centenas: forma números y suma o resta reagrupando (en inglés)." },
  },
  {
    id: "oak-two-digit-add-sub",
    title: "Addition and subtraction of two 2-digit numbers",
    source: "Oak National Academy",
    url: "https://www.thenational.academy/pupils/programmes/maths-primary-year-2/units/addition-and-subtraction-of-two-2-digit-numbers/lessons",
    kind: "video",
    subject: "math",
    grades: ["1", "2"],
    languages: ["en"],
    fits: ["m.add.2digit", "m.sub.2digit", "m.missing.addend"],
    about: { en: "Fifteen video lessons with quizzes on adding and subtracting two-digit numbers, with and without crossing ten.", es: "Quince videolecciones con pruebas sobre sumar y restar números de dos dígitos, con y sin pasar la decena (en inglés)." },
    note: { en: "UK lessons: Year 2 matches US grade 1.", es: "Lecciones del Reino Unido: Year 2 equivale a primer grado en EE. UU." },
  },
  {
    id: "mathsisfun-skip-counting",
    title: "Skip counting",
    source: "Math is Fun",
    url: "https://www.mathsisfun.com/numbers/skip-counting.html",
    urlEs: "https://www.disfrutalasmatematicas.com/numeros/contar-saltos.html",
    kind: "practice",
    subject: "math",
    grades: ["1", "3"],
    languages: ["en", "es"],
    fits: ["m.skip.count", "m.mult.groups"],
    about: { en: "Count by 2s, 3s, 5s and 10s, then fill in the missing numbers to practise.", es: "Cuenta de 2 en 2, de 3 en 3, de 5 en 5 y de 10 en 10, y completa los números que faltan." },
    note: { en: "Has ads.", es: "Tiene anuncios." },
  },
  {
    id: "im-g2-add-sub-1000",
    title: "Adding and subtracting within 1,000 (grade 2, family materials)",
    source: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/k5/families/grade-2/unit-7/family-materials.html",
    kind: "text",
    subject: "math",
    grades: ["2", "2"],
    languages: ["en"],
    fits: ["m.addsub.1000", "m.add.2digit", "m.sub.2digit"],
    about: { en: "How second graders use place value to add and subtract within 1,000, with an activity to try at home.", es: "Cómo usan el valor posicional en segundo grado para sumar y restar hasta 1,000, con una actividad para la casa (en inglés)." },
  },
  {
    id: "nces-create-a-graph",
    title: "Create a Graph",
    source: "National Center for Education Statistics",
    url: "https://nces.ed.gov/nceskids/createagraph/",
    kind: "tool",
    subject: "math",
    grades: ["2", "8"],
    languages: ["en"],
    fits: ["graphs", "bar graph", "line graph", "pie chart", "data", "statistics"],
    about: { en: "Type in your own data and turn it into a bar, line, area, pie or XY graph.", es: "Escribe tus propios datos y conviértelos en una gráfica de barras, líneas, área, pastel o XY (en inglés)." },
  },
  // Math — grade 3
  {
    id: "mathsisfun-times-tables",
    title: "Learn your multiplication tables",
    source: "Math is Fun",
    url: "https://www.mathsisfun.com/tables.html",
    urlEs: "https://www.disfrutalasmatematicas.com/tablas-multiplicar.html",
    kind: "practice",
    subject: "math",
    grades: ["3", "4"],
    languages: ["en", "es"],
    fits: ["m.mult.facts", "m.mult.easy", "m.div.facts"],
    about: { en: "A times table to explore and print, with tips and a trainer for remembering the facts.", es: "Una tabla de multiplicar para explorar e imprimir, con consejos y un entrenador para memorizarla." },
    note: { en: "Has ads.", es: "Tiene anuncios." },
  },
  phet("area-model-introduction", "Area Model: Introduction", ["m.mult.groups", "m.mult.multi", "m.area.rect"], ["3", "4"], "math", "Build rectangles on a grid to see multiplication as area, then split them to multiply in parts.", "Forma rectángulos en una cuadrícula para ver la multiplicación como área y divídelos para multiplicar por partes."),
  {
    id: "nrich-multiplication-square-jigsaw",
    title: "Multiplication Square Jigsaw",
    source: "University of Cambridge (NRICH)",
    url: "https://nrich.maths.org/problems/multiplication-square-jigsaw",
    kind: "practice",
    subject: "math",
    grades: ["3", "4"],
    languages: ["en"],
    fits: ["m.mult.facts", "puzzles"],
    about: { en: "Put a 1-to-10 multiplication square back together from its jigsaw pieces, on screen or on paper.", es: "Arma de nuevo una tabla de multiplicar del 1 al 10 con sus piezas de rompecabezas, en pantalla o en papel (en inglés)." },
  },
  {
    id: "im-g3-fractions-as-numbers",
    title: "Fractions as numbers (grade 3, family materials)",
    source: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/k5/families/grade-3/unit-5/family-materials.html",
    kind: "text",
    subject: "math",
    grades: ["3", "3"],
    languages: ["en"],
    fits: ["m.frac.unit", "m.frac.numberline", "m.frac.equiv"],
    about: { en: "How third graders show fractions with diagrams and number lines, with an activity to try at home.", es: "Cómo representan las fracciones en tercer grado con diagramas y rectas numéricas, con una actividad para la casa (en inglés)." },
  },
  {
    id: "mlc-geoboard",
    title: "Geoboard",
    source: "The Math Learning Center",
    url: "https://apps.mathlearningcenter.org/geoboard/",
    kind: "tool",
    subject: "math",
    grades: ["2", "6"],
    languages: ["en"],
    fits: ["m.area.rect", "m.area.poly", "shapes", "perimeter", "geometry"],
    about: { en: "Stretch bands around pegs to make shapes and work out their perimeter and area.", es: "Estira ligas entre clavijas para formar figuras y calcular su perímetro y su área (en inglés)." },
  },
  // Math — grade 4
  phet("fractions-mixed-numbers", "Fractions: Mixed Numbers", ["m.frac.mixed", "m.frac.equiv", "m.frac.unit"], ["3", "5"], "math", "Build mixed numbers and improper fractions with cakes, bars and number lines, then match them in a game.", "Forma números mixtos y fracciones impropias con pasteles, barras y rectas numéricas, y emparéjalos en un juego."),
  {
    id: "im-g4-fraction-equivalence",
    title: "Fraction equivalence and comparison (grade 4, family materials)",
    source: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/k5/families/grade-4/unit-2/family-materials.html",
    kind: "text",
    subject: "math",
    grades: ["4", "4"],
    languages: ["en"],
    fits: ["m.frac.equiv", "m.frac.compare"],
    about: { en: "How fourth graders write equivalent fractions and compare and order fractions, with an activity to try at home.", es: "Cómo escriben fracciones equivalentes en cuarto grado y cómo comparan y ordenan fracciones, con una actividad para la casa (en inglés)." },
  },
  {
    id: "nrich-four-go",
    title: "Four Go",
    source: "University of Cambridge (NRICH)",
    url: "https://nrich.maths.org/problems/four-go",
    kind: "practice",
    subject: "math",
    grades: ["3", "5"],
    languages: ["en"],
    fits: ["m.mult.facts", "m.div.facts", "games"],
    about: { en: "A game for two: multiply or divide pairs of numbers and try to get four marks in a row on a 0–20 line.", es: "Un juego para dos: multiplica o divide parejas de números y busca cuatro marcas seguidas en una recta del 0 al 20 (en inglés)." },
  },
  {
    id: "oak-tenths",
    title: "Understand tenths as part of a whole",
    source: "Oak National Academy",
    url: "https://www.thenational.academy/pupils/programmes/maths-primary-year-5/units/understand-tenths-as-part-of-a-whole-represent-and-calculate-mentally/lessons",
    kind: "video",
    subject: "math",
    grades: ["4", "4"],
    languages: ["en"],
    fits: ["m.dec.tenths"],
    about: { en: "Five video lessons with quizzes on tenths as decimals: counting, writing and comparing them.", es: "Cinco videolecciones con pruebas sobre las décimas como decimales: contarlas, escribirlas y compararlas (en inglés)." },
    note: { en: "UK lessons: Year 5 matches US grade 4.", es: "Lecciones del Reino Unido: Year 5 equivale a cuarto grado en EE. UU." },
  },
  // Math — grade 5
  phet("area-model-decimals", "Area Model: Decimals", ["m.dec.mult", "m.mult.multi"], ["5", "6"], "math", "Split rectangles into smaller areas to find new ways to multiply decimals.", "Divide rectángulos en áreas más pequeñas para descubrir formas de multiplicar decimales."),
  {
    id: "mathsisfun-order-of-operations",
    title: "Order of operations (PEMDAS)",
    source: "Math is Fun",
    url: "https://www.mathsisfun.com/operation-order-pemdas.html",
    urlEs: "https://www.disfrutalasmatematicas.com/operaciones-orden-pemdas.html",
    kind: "text",
    subject: "math",
    grades: ["5", "7"],
    languages: ["en", "es"],
    fits: ["m.order.ops", "m.expr.eval"],
    about: { en: "The agreed order for parentheses, exponents, multiplying, dividing, adding and subtracting, with worked examples.", es: "El orden acordado para paréntesis, exponentes, multiplicación, división, suma y resta, con ejemplos resueltos." },
    note: { en: "Has ads.", es: "Tiene anuncios." },
  },
  {
    id: "im-g5-volume",
    title: "Finding volume (grade 5, family materials)",
    source: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/k5/families/grade-5/unit-1/family-materials.html",
    kind: "text",
    subject: "math",
    grades: ["5", "5"],
    languages: ["en"],
    fits: ["m.volume"],
    about: { en: "How fifth graders find the volume of boxes by counting unit cubes and by multiplying side lengths, with an activity to try at home.", es: "Cómo hallan en quinto grado el volumen de cajas contando cubos unitarios y multiplicando sus lados, con una actividad para la casa (en inglés)." },
  },
  {
    id: "openstax-unlike-fractions",
    title: "Add and subtract fractions with different denominators",
    source: "OpenStax, Rice University",
    url: "https://openstax.org/books/prealgebra-2e/pages/4-5-add-and-subtract-fractions-with-different-denominators",
    kind: "text",
    subject: "math",
    grades: ["5", "7"],
    languages: ["en"],
    fits: ["m.frac.addunlike", "m.gcf.lcm"],
    about: { en: "A free textbook section on finding a common denominator, with worked examples and practice.", es: "Una sección de libro de texto gratis sobre el denominador común, con ejemplos resueltos y práctica (en inglés)." },
  },
  {
    id: "polypad",
    title: "Polypad",
    source: "Amplify (Mathigon)",
    url: "https://polypad.amplify.com/p",
    urlEs: "https://polypad.amplify.com/es/p",
    kind: "tool",
    subject: "math",
    grades: ["2", "9"],
    languages: ["en", "es"],
    fits: ["m.place.tens", "m.frac.equiv", "m.frac.addunlike", "m.expr.simplify", "manipulatives", "shapes", "geometry"],
    about: { en: "A free canvas of virtual manipulatives: number tiles, fraction bars, algebra tiles, shapes and dice.", es: "Un lienzo gratis de materiales virtuales: fichas numéricas, barras de fracciones, fichas de álgebra, figuras y dados." },
    note: { en: "Saving work needs a free account; using it does not.", es: "Guardar el trabajo requiere una cuenta gratis; usarlo no." },
  },
  // Math — grade 6
  {
    id: "im-g6-ratios",
    title: "Introducing ratios (grade 6, family materials)",
    source: "Illustrative Mathematics",
    url: "https://im.kendallhunt.com/MS/families/1/2/index.html",
    urlEs: "https://im.kendallhunt.com/MS_ES/families/1/2/index.html",
    kind: "text",
    subject: "math",
    grades: ["6", "6"],
    languages: ["en", "es"],
    fits: ["m.ratio.equiv", "m.ratio.unit"],
    about: { en: "Ratios explained with diagrams, double number lines and tables, plus problems with worked solutions.", es: "Las razones explicadas con diagramas, rectas numéricas dobles y tablas, con problemas y sus soluciones." },
  },
  phet("mean-share-and-balance", "Mean: Share and Balance", ["mean", "average", "statistics", "data"], ["5", "7"], "math", "Level cups of water, share snacks fairly and balance a beam to see what the mean is.", "Nivela vasos de agua, reparte meriendas por igual y equilibra una barra para ver qué es la media."),
  {
    id: "openstax-integers",
    title: "Introduction to integers",
    source: "OpenStax, Rice University",
    url: "https://openstax.org/books/prealgebra-2e/pages/3-1-introduction-to-integers",
    kind: "text",
    subject: "math",
    grades: ["6", "7"],
    languages: ["en"],
    fits: ["m.int.numberline", "m.int.addsub"],
    about: { en: "A free textbook section on negative numbers, opposites and absolute value on the number line.", es: "Una sección de libro de texto gratis sobre números negativos, opuestos y valor absoluto en la recta numérica (en inglés)." },
  },
  {
    id: "oak-expressions-equations",
    title: "Expressions and equations",
    source: "Oak National Academy",
    url: "https://www.thenational.academy/pupils/programmes/maths-secondary-year-7/units/expressions-and-equations/lessons",
    kind: "video",
    subject: "math",
    grades: ["6", "7"],
    languages: ["en"],
    fits: ["m.expr.eval", "m.expr.simplify", "m.eq.onestep"],
    about: { en: "Seventeen video lessons with quizzes on algebra notation, substituting values and collecting like terms.", es: "Diecisiete videolecciones con pruebas sobre notación algebraica, sustituir valores y reducir términos semejantes (en inglés)." },
    note: { en: "UK lessons: Year 7 matches US grade 6.", es: "Lecciones del Reino Unido: Year 7 equivale a sexto grado en EE. UU." },
  },
];
