/**
 * The parent report (spec §5.9, R11) assembled from the tables the loop
 * writes: sessions and minutes this week, per-skill starting and current
 * estimates with status, misconceptions open and resolved, the next skill,
 * one tutor note per session with the learner's thumbs, and the attention
 * aggregates when a session recorded any (spec §5.10, aggregates only).
 *
 * Wording (docs/STRATEGY-INTEGRATION.md law 2 and D17): every estimate is
 * called an estimate, the word mastery is used only for `confirmed`, and
 * every generated sentence carries GENERATED_LABEL.
 */
import type { MasteryStatus, ParentReport, ParentReportSkill } from '@/lib/tutor/contracts';
import type { Queryable } from '@/lib/tutor/db';

import { masteryStatus, parseSessionSummary } from './rows';

export const GENERATED_LABEL =
  'Generated by the AI tutor from the session record; nothing here is a human rating.';

/** The D17 sentence the parent view shows beside the confirmed list. */
export const REPORT_MASTERY_NOTE =
  'The tutor never grades its own help as mastery: a skill is confirmed only by an unassisted check at least a day later.';

/** Tutor notes shown per report; the transcript reader has the full history. */
export const REPORT_NOTE_LIMIT = 10;

/** Monday 00:00 UTC of the week containing `now`. */
export function weekStartUtc(now: Date): Date {
  const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const sinceMonday = (start.getUTCDay() + 6) % 7;
  start.setUTCDate(start.getUTCDate() - sinceMonday);
  return start;
}

export interface SkillRow extends Record<string, unknown> {
  id: string;
  name: string;
  prereqs: unknown;
  ordinal: number | string;
}

const MASTERED_OR_CONFIRMED: ReadonlySet<MasteryStatus> = new Set(['mastered', 'confirmed']);

function prereqIds(value: unknown): string[] {
  let raw = value;
  if (typeof raw === 'string') {
    try {
      raw = JSON.parse(raw);
    } catch {
      return [];
    }
  }
  return Array.isArray(raw) ? raw.filter((item): item is string => typeof item === 'string') : [];
}

/**
 * The lowest-ordinal skill that is not mastered whose prerequisites are all
 * mastered or confirmed (spec §5.7); null when the graph is empty or nothing
 * is reachable.
 */
export function selectNextSkill(
  skills: readonly SkillRow[],
  statuses: ReadonlyMap<string, MasteryStatus>,
): { id: string; name: string } | null {
  const ordered = [...skills].sort(
    (a, b) => Number(a.ordinal) - Number(b.ordinal) || a.id.localeCompare(b.id),
  );
  const done = (id: string) => MASTERED_OR_CONFIRMED.has(statuses.get(id) ?? 'not_started');
  for (const skill of ordered) {
    if (done(skill.id)) continue;
    if (prereqIds(skill.prereqs).every(done)) return { id: skill.id, name: skill.name };
  }
  return null;
}

/** Status wording for the parent view: "mastery" only for `confirmed`, "estimate" elsewhere. */
export function masteryStatusLabel(status: MasteryStatus): string {
  switch (status) {
    case 'confirmed':
      return 'mastery confirmed';
    case 'mastered':
      return 'on track (estimate)';
    case 'in_progress':
      return 'in progress (estimate)';
    default:
      return 'not started';
  }
}

function percent(estimate: number): string {
  return `${Math.round(estimate * 100)}%`;
}

/**
 * The §5.9 reading for one skill, for example
 * "Fractions — starting 42%, now 78%; resolved: denominator magnitude; next: equivalent fractions."
 */
export function skillSentence(
  skill: ParentReportSkill,
  extras: { resolved?: readonly string[]; next?: string | null } = {},
): string {
  const parts = [
    skill.startingEstimate === null
      ? `${skill.name} — now ${percent(skill.currentEstimate)}`
      : `${skill.name} — starting ${percent(skill.startingEstimate)}, now ${percent(skill.currentEstimate)}`,
  ];
  if (extras.resolved && extras.resolved.length > 0) {
    parts.push(`resolved: ${extras.resolved.join(', ')}`);
  }
  if (extras.next) parts.push(`next: ${extras.next}`);
  return `${parts.join('; ')}.`;
}

interface WeekRow extends Record<string, unknown> {
  sessions: number | string;
  minutes: number | string;
}

interface ReportMasteryRow extends Record<string, unknown> {
  skill_id: string;
  name: string;
  starting_estimate: number | string | null;
  estimate: number | string;
  status: string;
}

interface MisconceptionTagRow extends Record<string, unknown> {
  tag: string;
  status: string;
}

interface NoteRow extends Record<string, unknown> {
  id: string;
  started_at: string | Date;
  summary: unknown;
  thumbs: string | null;
}

interface AttentionRow extends Record<string, unknown> {
  n: number | string;
  camera: boolean | null;
  attending: number | string | null;
  recoveries: number | string | null;
}

export async function buildParentReport(
  db: Queryable,
  accountId: string,
  learnerId: string,
  now = new Date(),
): Promise<ParentReport> {
  const weekStart = weekStartUtc(now);
  const [week, mastery, misconceptions, skills, notes, attention] = await Promise.all([
    db.query<WeekRow>(
      `SELECT count(*)::int AS sessions, COALESCE(sum(minutes), 0)::int AS minutes
       FROM sessions WHERE account_id = $1 AND learner_id = $2 AND started_at >= $3`,
      [accountId, learnerId, weekStart],
    ),
    db.query<ReportMasteryRow>(
      `SELECT m.skill_id, COALESCE(s.name, m.skill_id) AS name, m.starting_estimate, m.estimate, m.status
       FROM skill_mastery m LEFT JOIN skills s ON s.id = m.skill_id
       WHERE m.account_id = $1 AND m.learner_id = $2
       ORDER BY COALESCE(s.ordinal, 2147483647), m.skill_id`,
      [accountId, learnerId],
    ),
    db.query<MisconceptionTagRow>(
      `SELECT tag, status FROM misconceptions
       WHERE account_id = $1 AND learner_id = $2 ORDER BY first_seen_at, tag`,
      [accountId, learnerId],
    ),
    db.query<SkillRow>(`SELECT id, name, prereqs, ordinal FROM skills ORDER BY ordinal, id`),
    db.query<NoteRow>(
      `SELECT id, started_at, summary, thumbs FROM sessions
       WHERE account_id = $1 AND learner_id = $2 AND summary IS NOT NULL
       ORDER BY started_at DESC, id DESC LIMIT $3`,
      [accountId, learnerId, REPORT_NOTE_LIMIT],
    ),
    db.query<AttentionRow>(
      `SELECT count(*)::int AS n, bool_or(a.camera_enabled) AS camera,
              avg(a.attending_pct)::float AS attending, COALESCE(sum(a.recoveries), 0)::int AS recoveries
       FROM attention_stats a JOIN sessions s ON s.id = a.session_id
       WHERE a.account_id = $1 AND s.account_id = $1 AND s.learner_id = $2`,
      [accountId, learnerId],
    ),
  ]);

  const statuses = new Map<string, MasteryStatus>();
  const reportSkills: ParentReportSkill[] = mastery.rows.map((row) => {
    const status = masteryStatus(row.status);
    statuses.set(row.skill_id, status);
    return {
      skillId: row.skill_id,
      name: row.name,
      startingEstimate: row.starting_estimate == null ? null : Number(row.starting_estimate),
      currentEstimate: Number(row.estimate),
      status,
    };
  });

  const attentionRow = attention.rows[0];
  const attending = Number(attentionRow?.attending ?? 0);
  const hasAttention =
    Number(attentionRow?.n ?? 0) > 0 && (Boolean(attentionRow?.camera) || attending > 0);

  return {
    learnerId,
    weekStart: weekStart.toISOString(),
    sessions: Number(week.rows[0]?.sessions ?? 0),
    minutes: Number(week.rows[0]?.minutes ?? 0),
    skills: reportSkills,
    misconceptionsOpen: misconceptions.rows
      .filter((row) => row.status !== 'resolved')
      .map((row) => row.tag),
    misconceptionsResolved: misconceptions.rows
      .filter((row) => row.status === 'resolved')
      .map((row) => row.tag),
    nextSkill: selectNextSkill(skills.rows, statuses),
    sessionNotes: notes.rows.map((row) => ({
      sessionId: row.id,
      date:
        row.started_at instanceof Date
          ? row.started_at.toISOString()
          : new Date(row.started_at).toISOString(),
      note: parseSessionSummary(row.summary)?.tutorNote ?? '',
      thumbs: row.thumbs === 'up' || row.thumbs === 'down' ? row.thumbs : null,
    })),
    attention: hasAttention
      ? {
          attendingPct: Math.round(attending),
          recoveries: Number(attentionRow?.recoveries ?? 0),
        }
      : null,
  };
}
