import { how, Q, type Passage } from "./types";

// More band 1 poems, grade 2–3 text band (draft: written for KaizenEDU, not yet reviewed by a teacher).
// Free verse. The speakers differ on purpose: a father penguin, a child in a garden, someone drawing on
// a sidewalk, a cat at a window, an older sister.
export const BAND1_POEMS_2: Passage[] = [
  {
    id: "father-penguin",
    kind: "poem",
    band: 1,
    title: ["All Winter on the Ice", "Todo el invierno sobre el hielo"],
    en: [
      "The wind is sharp,\nthe night is long,\nand the sun has not come up for many days.\nStill I stand here on the ice.",
      "Before you went to find the sea,\nyou rolled our egg to me,\nand I lifted it onto my feet\nand tucked it under my warm fold of skin.",
      "I do not eat. I do not wander.\nI shuffle with the other fathers\ninto the crowded middle,\nthen out to the windy edge again.",
      "Some nights I hum to the egg,\na low song only it can hear,\nso the chick inside will know my voice\nthe day it pecks its way out.",
      "When you come back from the sea,\nfat with fish and smelling of salt,\nI will call, and you will call,\nand you will find us in the crowd.",
      "Then I will walk to the water at last,\nhungry and thin and glad,\nand you will hold our chick\nthe way I held the egg.",
    ],
    es: [
      "El viento corta,\nla noche es larga,\ny hace muchos días que no sale el sol.\nAun así, yo sigo de pie sobre el hielo.",
      "Antes de irte a buscar el mar,\nme pasaste rodando nuestro huevo,\ny yo lo subí a mis patas\ny lo tapé con mi pliegue de piel calientito.",
      "No como. No me alejo.\nMe muevo despacito con los otros papás\nhacia el centro apretado,\ny luego otra vez a la orilla, donde sopla el viento.",
      "Algunas noches le canturreo al huevo\nuna canción bajita que solo él oye,\npara que el polluelo conozca mi voz\nel día que rompa el cascarón.",
      "Cuando vuelvas del mar,\ngordita de tanto pescado y con olor a sal,\nyo llamaré, y tú llamarás,\ny nos encontrarás entre la multitud.",
      "Entonces por fin caminaré hasta el agua,\nflaco, con hambre y contento,\ny tú cargarás a nuestro polluelo\ncomo yo cargué el huevo.",
    ],
    qs: [
      Q("pov", ["Who is the speaker of this poem?", "¿Quién habla en este poema?"], ["A father penguin keeping an egg warm", "Un papá pingüino que le da calor a un huevo"], [["A mother penguin out at sea", "Una mamá pingüino que está en el mar", "wrong-character"], ["The chick inside the egg", "El polluelo que está dentro del huevo", "wrong-character"], ["A scientist watching penguins", "Una científica que observa pingüinos", "not-in-text"]], ["Find who has the egg on their feet.", "Busca quién tiene el huevo sobre las patas."], ["and I lifted it onto my feet", "y yo lo subí a mis patas"]),
      how(Q("pov", ["Who is “you” in this poem?", "¿Quién es el “tú” de este poema?"], ["The mother penguin, who went to the sea", "La mamá pingüino, que se fue al mar"], [["The chick that will hatch", "El polluelo que va a nacer", "wrong-character"], ["The other fathers in the huddle", "Los otros papás del grupo", "wrong-character"], ["The reader of the poem", "Quien lee el poema", "not-in-text"]], ["Read the second stanza. Who gave the egg to the speaker?", "Lee la segunda estrofa. ¿Quién le pasó el huevo a quien habla?"], ["Before you went to find the sea", "Antes de irte a buscar el mar"]), ["A speaker can talk to someone who is not there. Look for what “you” did and what “you” will do.", "Quien habla le puede hablar a alguien que no está. Busca lo que hizo ese “tú” y lo que va a hacer."]),
      Q("theme", ["What is the message of the poem?", "¿Cuál es el mensaje del poema?"], ["Parents may work hard and wait a long time to care for their young.", "Los padres pueden esforzarse y esperar mucho tiempo para cuidar a sus crías."], [["A penguin holds an egg all winter.", "Un pingüino sostiene un huevo todo el invierno.", "plot-summary"], ["It is better to live where it is warm.", "Es mejor vivir donde hace calor.", "unsupported-lesson"], ["Penguins like to sing.", "A los pingüinos les gusta cantar.", "too-narrow"]], ["Think about everything the speaker gives up for the egg.", "Piensa en todo lo que deja de hacer quien habla por el huevo."], ["I do not eat. I do not wander.", "No como. No me alejo."]),
      Q("words", ["In the poem, what does “fat with fish” mean?", "En el poema, ¿qué significa “gordita de tanto pescado”?"], ["Well fed after eating lots of fish", "Bien alimentada después de comer mucho pescado"], [["Shaped like a fish", "Con forma de pescado", "took-literally"], ["Carrying fish for the egg", "Cargando pescado para el huevo", "ignored-context"], ["Tired and very thin", "Cansada y muy flaca", "opposite-meaning"]], ["The mother has been at the sea, eating. How would she look when she comes back?", "La mamá estuvo en el mar comiendo. ¿Cómo se vería al volver?"], ["fat with fish and smelling of salt", "gordita de tanto pescado y con olor a sal"]),
      Q("details", ["What does the speaker do on some nights?", "¿Qué hace quien habla algunas noches?"], ["Sings a quiet song to the egg", "Le canta bajito al huevo"], [["Walks to the water to eat", "Camina hasta el agua a comer", "wrong-order"], ["Calls to find the mother", "Llama para encontrar a la mamá", "wrong-order"], ["Builds a nest of stones", "Hace un nido de piedras", "not-in-text"]], ["Find the stanza that begins “Some nights.”", "Busca la estrofa que empieza con “Algunas noches”."], ["Some nights I hum to the egg", "Algunas noches le canturreo al huevo"]),
    ],
  },
  {
    id: "morning-web",
    kind: "poem",
    band: 1,
    title: ["Morning Web", "La telaraña de la mañana"],
    en: [
      "This morning, between the fence and the tomato plants,\nI found a wheel made of silver thread.\nDew sat on every string\nlike tiny glass beads.",
      "I counted the spokes, one, two, three,\nand lost count at twenty.\nRound and round went the sticky road\nthat you walked in the dark.",
      "You were sitting in the middle,\nstill as a button,\nwaiting for breakfast to fly in.",
      "A fly buzzed close.\nThe whole web trembled,\nand you ran down a single thread\nfaster than I could blink.",
      "I wanted to touch it.\nI wanted to see if it would stretch.\nBut Mom says a web is a spider's house and kitchen,\nso I just looked.",
      "By lunchtime the dew was gone,\nand so was the web.\nTomorrow, I bet, you will build another one,\nand I will be here to watch.",
    ],
    es: [
      "Esta mañana, entre la cerca y las matas de tomate,\nencontré una rueda hecha de hilo plateado.\nEl rocío estaba en cada hilo\ncomo cuentas diminutas de vidrio.",
      "Conté los rayos, uno, dos, tres,\ny perdí la cuenta en veinte.\nDaba vueltas y vueltas el camino pegajoso\nque tú recorriste en la oscuridad.",
      "Estabas sentada en el centro,\nquieta como un botón,\nesperando que el desayuno llegara volando.",
      "Una mosca zumbó cerca.\nToda la telaraña tembló,\ny tú bajaste corriendo por un solo hilo\nmás rápido de lo que pude parpadear.",
      "Quería tocarla.\nQuería ver si se estiraba.\nPero mamá dice que la telaraña es la casa y la cocina de la araña,\nasí que solo la miré.",
      "Para la hora del almuerzo, el rocío ya no estaba,\nni la telaraña tampoco.\nApuesto a que mañana vas a tejer otra,\ny yo voy a estar aquí para verla.",
    ],
    qs: [
      how(Q("pov", ["Who is “you” in this poem?", "¿Quién es el “tú” de este poema?"], ["The spider that built the web", "La araña que tejió la telaraña"], [["Mom, who talks about the web", "La mamá, que habla de la telaraña", "wrong-character"], ["The fly that buzzed close", "La mosca que zumbó cerca", "wrong-character"], ["A friend helping in the garden", "Un amigo que ayuda en el huerto", "not-in-text"]], ["Read the third stanza. Who is sitting in the middle of the web?", "Lee la tercera estrofa. ¿Quién está sentada en el centro de la telaraña?"], ["You were sitting in the middle", "Estabas sentada en el centro"]), ["A speaker can talk to an animal. Look for what “you” does in the poem.", "Quien habla le puede hablar a un animal. Busca lo que hace ese “tú” en el poema."]),
      how(Q("pov", ["The speaker says the spider walked the “sticky road” in the dark. How can the speaker know this?", "Quien habla dice que la araña recorrió el “camino pegajoso” en la oscuridad. ¿Cómo lo puede saber?"], ["The web was already finished in the morning, so the speaker guesses it was built at night.", "La telaraña ya estaba terminada en la mañana, así que quien habla supone que se tejió de noche."], [["The speaker stayed up all night to watch.", "Quien habla pasó la noche en vela mirando.", "not-in-text"], ["Mom told the speaker about it.", "La mamá se lo contó.", "wrong-character"], ["The spider told the speaker.", "La araña se lo dijo.", "took-literally"]], ["Read the first stanza. When does the speaker find the web?", "Lee la primera estrofa. ¿Cuándo encuentra quien habla la telaraña?"], ["This morning, between the fence and the tomato plants", "Esta mañana, entre la cerca y las matas de tomate"]), ["A speaker can tell only what they see, plus what they guess. Think about what the speaker saw and when.", "Quien habla solo puede contar lo que ve y lo que supone. Piensa en lo que vio y cuándo."]),
      Q("theme", ["What is the message of the poem?", "¿Cuál es el mensaje del poema?"], ["Small things in nature are worth slowing down to watch.", "Vale la pena detenerse a mirar las cosas pequeñas de la naturaleza."], [["Someone finds a spider web in a garden.", "Alguien encuentra una telaraña en un huerto.", "plot-summary"], ["Spiders are scary, so stay away from them.", "Las arañas dan miedo, así que hay que alejarse de ellas.", "unsupported-lesson"], ["Dew dries up by lunchtime.", "El rocío se seca para la hora del almuerzo.", "too-narrow"]], ["Think about what the speaker does all morning and plans to do tomorrow.", "Piensa en lo que hace quien habla toda la mañana y en lo que piensa hacer mañana."], ["so I just looked", "así que solo la miré"]),
      Q("words", ["In the poem, what does “still as a button” mean?", "En el poema, ¿qué significa “quieta como un botón”?"], ["Not moving at all", "Sin moverse para nada"], [["Round and shiny like a button", "Redonda y brillante como un botón", "took-literally"], ["Moving very fast", "Moviéndose muy rápido", "opposite-meaning"], ["Hiding under a leaf", "Escondida bajo una hoja", "ignored-context"]], ["The spider is waiting. How does something look when it waits for a long time?", "La araña está esperando. ¿Cómo se ve algo que espera mucho tiempo?"], ["still as a button", "quieta como un botón"]),
      Q("details", ["What happened when the fly buzzed close?", "¿Qué pasó cuando la mosca zumbó cerca?"], ["The web shook, and the spider ran down a thread.", "La telaraña se sacudió y la araña bajó corriendo por un hilo."], [["The speaker wanted to touch the web.", "Quien habla quiso tocar la telaraña.", "wrong-order"], ["The dew dried up.", "El rocío se secó.", "wrong-order"], ["The fly broke the web.", "La mosca rompió la telaraña.", "not-in-text"]], ["Find the stanza about the fly.", "Busca la estrofa de la mosca."], ["The whole web trembled", "Toda la telaraña tembló"]),
    ],
  },
  {
    id: "sidewalk-chalk",
    kind: "poem",
    band: 1,
    title: ["Chalk City", "Ciudad de tiza"],
    en: [
      "On Saturday I drew a whole city\non the sidewalk in front of our building,\nblue rivers, green parks,\nand a yellow bus that went all the way to the corner.",
      "My neighbor, Mr. Chen, stepped around the bus\nso he would not smudge it.\nTwo little kids sat in my park\nand pretended to have a picnic.",
      "That night it rained.\nI listened from my window\nand knew what the rain was doing,\nwashing my rivers into the street.",
      "In the morning, the sidewalk was gray again,\nclean as a new page.\nOnly a smear of yellow\nwas left by the curb.",
      "I was sad for about a minute.\nThen I opened my box of chalk.\nA clean sidewalk, I decided,\nis just a place to start over.",
    ],
    es: [
      "El sábado dibujé una ciudad entera\nen la acera frente a nuestro edificio,\nríos azules, parques verdes\ny un autobús amarillo que llegaba hasta la esquina.",
      "Mi vecino, el señor Chen, le dio la vuelta al autobús\npara no borrarlo.\nDos niños pequeños se sentaron en mi parque\ny jugaron a que tenían un pícnic.",
      "Esa noche llovió.\nYo escuchaba desde mi ventana\ny sabía lo que estaba haciendo la lluvia:\nllevarse mis ríos a la calle.",
      "En la mañana, la acera estaba gris otra vez,\nlimpia como una página nueva.\nSolo quedaba una mancha amarilla\njunto al borde de la acera.",
      "Estuve triste como un minuto.\nLuego abrí mi caja de tizas.\nUna acera limpia, pensé,\nes solo un lugar para volver a empezar.",
    ],
    qs: [
      how(Q("pov", ["How does the speaker know what the rain is doing at night?", "¿Cómo sabe quien habla lo que hace la lluvia en la noche?"], ["The speaker hears the rain and pictures what it does to the drawing.", "Quien habla oye la lluvia y se imagina lo que le hace al dibujo."], [["The speaker is outside watching the drawing.", "Quien habla está afuera mirando el dibujo.", "opposite-of-text"], ["Mr. Chen tells the speaker.", "El señor Chen se lo cuenta.", "wrong-character"], ["The speaker sees it on the news.", "Quien habla lo ve en las noticias.", "not-in-text"]], ["Read the third stanza. Where is the speaker?", "Lee la tercera estrofa. ¿Dónde está quien habla?"], ["I listened from my window", "Yo escuchaba desde mi ventana"]), ["A speaker can tell only what they see and hear, plus what they imagine. Find where the speaker is when it rains.", "Quien habla solo puede contar lo que ve y oye, y lo que se imagina. Busca dónde está cuando llueve."]),
      Q("pov", ["Who is the speaker of this poem?", "¿Quién habla en este poema?"], ["Someone who drew a city on the sidewalk", "Alguien que dibujó una ciudad en la acera"], [["Mr. Chen, the neighbor", "El señor Chen, el vecino", "wrong-character"], ["One of the little kids at the picnic", "Uno de los niños pequeños del pícnic", "wrong-character"], ["The rain", "La lluvia", "wrong-character"]], ["Who says “I drew” in the first stanza?", "¿Quién dice “dibujé” en la primera estrofa?"], ["On Saturday I drew a whole city", "El sábado dibujé una ciudad entera"]),
      Q("theme", ["What is the theme of the poem?", "¿Cuál es el tema del poema?"], ["When something you made is lost, you can begin again.", "Cuando se pierde algo que hiciste, puedes empezar de nuevo."], [["Rain washes a chalk drawing away.", "La lluvia borra un dibujo de tiza.", "plot-summary"], ["Never draw outside.", "Nunca dibujes afuera.", "unsupported-lesson"], ["Buses are yellow.", "Los autobuses son amarillos.", "too-narrow"]], ["Read the last stanza. What does the speaker decide?", "Lee la última estrofa. ¿Qué decide quien habla?"], ["is just a place to start over", "es solo un lugar para volver a empezar"]),
      Q("words", ["In the poem, what does “clean as a new page” mean?", "En el poema, ¿qué significa “limpia como una página nueva”?"], ["With nothing drawn on it anymore", "Sin nada dibujado"], [["Made of paper", "Hecha de papel", "took-literally"], ["Covered with bright colors", "Llena de colores brillantes", "opposite-meaning"], ["Wet and slippery", "Mojada y resbalosa", "ignored-context"]], ["A new page in a notebook has nothing on it yet. What does the sidewalk look like?", "Una página nueva de un cuaderno todavía no tiene nada. ¿Cómo se ve la acera?"], ["clean as a new page", "limpia como una página nueva"]),
      Q("details", ["What did Mr. Chen do when he walked by the drawing?", "¿Qué hizo el señor Chen cuando pasó junto al dibujo?"], ["He walked around it to keep it safe.", "Caminó alrededor para no estropearlo."], [["He sat in the park and had a picnic.", "Se sentó en el parque e hizo un pícnic.", "wrong-character"], ["He helped draw the rivers.", "Ayudó a dibujar los ríos.", "not-in-text"], ["He washed the sidewalk.", "Lavó la acera.", "not-in-text"]], ["Read the second stanza.", "Lee la segunda estrofa."], ["stepped around the bus", "le dio la vuelta al autobús"]),
    ],
  },
  {
    id: "window-cat",
    kind: "poem",
    band: 1,
    title: ["My Window", "Mi ventana"],
    en: [
      "From my shelf by the window,\nI watch the whole world\nwith my tail wrapped around my paws.",
      "I see the mail carrier at ten,\nthe same blue bag, the same quick steps.\nI see the pigeons on the wire\nwho think I cannot reach them.\nThey are right, but I think about it.",
      "I see my girl come home at three,\nher backpack bumping like a drum.\nI pretend I was not waiting.\nI was waiting.",
      "I do not know what the mail carrier carries\nor where the pigeons go at night.\nI only know my window\nand the street below it\nand everything that passes by.",
      "When the street lamps glow,\nI leave my shelf and find a warm lap.\nThe world can wait\nuntil morning.",
    ],
    es: [
      "Desde mi repisa junto a la ventana,\nmiro el mundo entero\ncon la cola enroscada en las patas.",
      "Veo al cartero a las diez,\nla misma bolsa azul, los mismos pasos rápidos.\nVeo a las palomas en el cable,\nque creen que no puedo alcanzarlas.\nTienen razón, pero lo pienso.",
      "Veo a mi niña llegar a las tres,\ncon la mochila rebotando como un tambor.\nHago como si no la estuviera esperando.\nLa estaba esperando.",
      "No sé qué lleva el cartero en la bolsa\nni adónde van las palomas de noche.\nSolo conozco mi ventana,\nla calle de abajo\ny todo lo que pasa por ahí.",
      "Cuando se encienden los faroles,\nme bajo de la repisa y busco un regazo calientito.\nEl mundo puede esperar\nhasta mañana.",
    ],
    qs: [
      Q("pov", ["Who is the speaker of this poem?", "¿Quién habla en este poema?"], ["A cat that watches from a window", "Un gato que mira por la ventana"], [["The girl with the backpack", "La niña de la mochila", "wrong-character"], ["The mail carrier", "El cartero", "wrong-character"], ["A pigeon on the wire", "Una paloma del cable", "wrong-character"]], ["Read the first stanza. What does the speaker have that a person does not?", "Lee la primera estrofa. ¿Qué tiene quien habla que una persona no tiene?"], ["with my tail wrapped around my paws", "con la cola enroscada en las patas"]),
      how(Q("pov", ["What does the speaker say it cannot know?", "¿Qué dice quien habla que no puede saber?"], ["What is in the bag and where the birds sleep", "Qué hay en la bolsa y dónde duermen las aves"], [["What time the girl comes home", "A qué hora llega la niña", "opposite-of-text"], ["When the mail carrier comes by", "Cuándo pasa el cartero", "opposite-of-text"], ["Where to find a warm lap", "Dónde encontrar un regazo calientito", "opposite-of-text"]], ["Find the stanza that begins “I do not know.”", "Busca la estrofa que empieza con “No sé”."], ["I only know my window", "Solo conozco mi ventana"]), ["A speaker can tell only what they see and hear from where they are. Think about how much of the world a window shows.", "Quien habla solo puede contar lo que ve y oye desde donde está. Piensa en cuánto del mundo se ve por una ventana."]),
      Q("theme", ["What is the message of the poem?", "¿Cuál es el mensaje del poema?"], ["Even a small world can be full of things to notice.", "Hasta un mundo pequeño puede estar lleno de cosas que observar."], [["A cat sits at a window all day.", "Un gato se sienta en la ventana todo el día.", "plot-summary"], ["Cats should be allowed to go outside.", "A los gatos hay que dejarlos salir.", "unsupported-lesson"], ["Pigeons sit on wires.", "Las palomas se paran en los cables.", "too-narrow"]], ["Think about how much the speaker notices from one small shelf.", "Piensa en cuántas cosas nota quien habla desde una repisa pequeña."], ["I watch the whole world", "miro el mundo entero"]),
      Q("words", ["In the poem, what does “her backpack bumping like a drum” show?", "En el poema, ¿qué muestra “con la mochila rebotando como un tambor”?"], ["The backpack bounces as she walks.", "La mochila brinca mientras ella camina."], [["She is playing a drum.", "Está tocando un tambor.", "took-literally"], ["The backpack is empty.", "La mochila está vacía.", "not-in-text"], ["She is walking very slowly.", "Camina muy despacio.", "ignored-context"]], ["Think about what a heavy bag does when you walk fast.", "Piensa en lo que hace una mochila pesada cuando caminas rápido."], ["her backpack bumping like a drum", "con la mochila rebotando como un tambor"]),
      Q("details", ["What does the speaker do when the street lamps glow?", "¿Qué hace quien habla cuando se encienden los faroles?"], ["Leaves the window and finds a warm lap", "Se baja de la ventana y busca un regazo"], [["Watches the pigeons on the wire", "Mira a las palomas del cable", "wrong-order"], ["Waits for the mail carrier", "Espera al cartero", "wrong-order"], ["Goes outside to the street", "Sale a la calle", "not-in-text"]], ["Read the last stanza.", "Lee la última estrofa."], ["I leave my shelf and find a warm lap", "me bajo de la repisa y busco un regazo calientito"]),
    ],
  },
  {
    id: "sister-questions",
    kind: "poem",
    band: 1,
    title: ["My Sister's Questions", "Las preguntas de mi hermanita"],
    en: [
      "My little sister asks a question\nevery time I turn around.\n“Why is the sky blue?\nWhere does the wind live?\nDo fish ever sleep?”",
      "Some I can answer.\nFish do rest, I tell her,\nfloating still in the water\nlike leaves that forgot to fall.",
      "The sky is blue, I tell her,\nbecause the air spreads sunlight around,\nand blue gets spread the most.",
      "Some I cannot.\nWhere does the wind live?\nI look out at the swaying trees\nand say, “Everywhere, I think.”",
      "At bedtime she asks the biggest one.\n“Will you always be my sister?”\nThat one is easy.\nI do not even have to think.",
      "“Always,” I say, and turn off the light.\nIn the dark she whispers, “Why?”\nI smile, because I know\nshe will ask me again tomorrow.",
    ],
    es: [
      "Mi hermanita hace una pregunta\ncada vez que me doy la vuelta.\n“¿Por qué el cielo es azul?\n¿Dónde vive el viento?\n¿Los peces duermen?”",
      "Algunas las sé contestar.\nLos peces sí descansan, le digo,\nflotan quietos en el agua\ncomo hojas que se olvidaron de caer.",
      "El cielo es azul, le explico,\nporque el aire esparce la luz del sol\ny el azul es el que más se esparce.",
      "Otras no.\n¿Dónde vive el viento?\nMiro por la ventana los árboles que se mecen\ny le digo: “En todas partes, creo”.",
      "A la hora de dormir, hace la pregunta más grande.\n“¿Siempre vas a ser mi hermana?”\nEsa es fácil.\nNi siquiera tengo que pensarla.",
      "“Siempre”, le digo, y apago la luz.\nEn la oscuridad, susurra: “¿Por qué?”\nSonrío, porque sé\nque mañana me lo va a volver a preguntar.",
    ],
    qs: [
      Q("pov", ["Who is the speaker of this poem?", "¿Quién habla en este poema?"], ["An older sister who answers her little sister's questions", "Una hermana mayor que contesta las preguntas de su hermanita"], [["The little sister who asks the questions", "La hermanita que hace las preguntas", "dialogue-as-narrator"], ["The wind in the trees", "El viento de los árboles", "wrong-character"], ["A teacher at school", "Una maestra de la escuela", "not-in-text"]], ["Who says “I tell her” in the poem?", "¿Quién dice “le digo” en el poema?"], ["My little sister asks a question", "Mi hermanita hace una pregunta"]),
      how(Q("pov", ["Whose words are inside the quotation marks in the first stanza?", "¿De quién son las palabras que están entre comillas en la primera estrofa?"], ["The little sister's", "De la hermanita"], [["The speaker's", "De quien habla", "dialogue-as-narrator"], ["A teacher's", "De una maestra", "not-in-text"], ["Their mother's", "De su mamá", "not-in-text"]], ["Read the first two lines. Who asks a question every time?", "Lee los dos primeros versos. ¿Quién hace una pregunta cada vez?"], ["every time I turn around", "cada vez que me doy la vuelta"]), ["In a poem, words inside quotation marks are someone talking. The speaker may be telling what another person said.", "En un poema, las palabras entre comillas son alguien que habla. Quien habla puede estar contando lo que dijo otra persona."]),
      Q("theme", ["What is the message of the poem?", "¿Cuál es el mensaje del poema?"], ["You do not need every answer to show someone you love them.", "No necesitas tener todas las respuestas para mostrarle a alguien que lo quieres."], [["A girl asks her sister many questions.", "Una niña le hace muchas preguntas a su hermana.", "plot-summary"], ["Asking questions is rude.", "Hacer preguntas es de mala educación.", "unsupported-lesson"], ["Fish rest in the water.", "Los peces descansan en el agua.", "too-narrow"]], ["Compare a question the speaker cannot answer with the one that is easy.", "Compara una pregunta que quien habla no puede contestar con la que es fácil."], ["That one is easy.", "Esa es fácil."]),
      Q("words", ["In the poem, what does “like leaves that forgot to fall” describe?", "En el poema, ¿qué describe “como hojas que se olvidaron de caer”?"], ["Fish resting so still that they seem to hang in the water", "Peces tan quietos que parecen colgar en el agua"], [["Leaves floating down a river", "Hojas que flotan en un río", "took-literally"], ["Trees swaying in the wind", "Árboles que se mecen con el viento", "wrong-detail"], ["Fish swimming very fast", "Peces que nadan muy rápido", "opposite-meaning"]], ["Read the lines before it. What is floating in the water?", "Lee los versos de antes. ¿Qué flota en el agua?"], ["floating still in the water", "flotan quietos en el agua"]),
      Q("details", ["What does the speaker say when she cannot tell where the wind lives?", "¿Qué dice quien habla cuando no sabe dónde vive el viento?"], ["She guesses that it lives everywhere.", "Supone que vive en todas partes."], [["She says it lives in the trees.", "Dice que vive en los árboles.", "not-in-text"], ["She says the sky is blue.", "Dice que el cielo es azul.", "wrong-detail"], ["She says she will look it up tomorrow.", "Dice que mañana lo va a buscar.", "not-in-text"]], ["Find the stanza that begins “Some I cannot.”", "Busca la estrofa que empieza con “Otras no”."], ["I look out at the swaying trees", "Miro por la ventana los árboles que se mecen"]),
    ],
  },
];
