import { how, Q, type Passage } from "./types";

// More band 1 informational articles, grade 2–3 text band (draft: written for KaizenEDU, not yet reviewed
// by a teacher). Facts checked against standard references: emperor penguins (Antarctica, huddles, the
// father's two-month fast on the egg, up to about 45 in tall), spider silk and orb webs, fall leaf color
// (chlorophyll, carotenoids, new red pigments, the abscission layer), lightning and thunder (5 s a mile,
// 3 s a km, 30 minutes after the last thunder), teeth (20 baby, 32 adult, enamel), and snowflakes
// (six-sided crystals, Wilson Bentley's first photograph of one in 1885).
export const BAND1_INFO_2: Passage[] = [
  {
    id: "penguins",
    kind: "info",
    band: 1,
    title: ["How Emperor Penguins Stay Warm", "Cómo aguantan el frío los pingüinos emperador"],
    en: [
      "Emperor penguins live in Antarctica, the coldest place on Earth. In winter, the wind howls, and the air can be much colder than a freezer. Yet these birds stay warm.",
      "Built for the Cold",
      "An emperor penguin has a thick layer of fat under its skin. On top of the fat are layers of short feathers packed tightly together. The fat and feathers hold in the bird's body heat, like a warm coat.",
      "Staying Together",
      "On the coldest days, thousands of penguins crowd together in a big group called a huddle. The birds on the outside get the coldest wind. So the penguins slowly shuffle, and each one takes a turn in the warm middle.",
      "Keeping the Egg Warm",
      "After the mother lays an egg, she goes to the sea to eat. The father holds the egg on top of his feet and covers it with a warm fold of skin. For about two months, he stands in the cold and does not eat.",
      "Fast fact: An emperor penguin can be almost four feet tall. It is the biggest penguin in the world.",
    ],
    es: [
      "Los pingüinos emperador viven en la Antártida, el lugar más frío de la Tierra. En invierno, el viento sopla con fuerza, y el aire puede estar mucho más frío que un congelador. Aun así, estas aves no pasan frío.",
      "Hechos para el frío",
      "El pingüino emperador tiene una capa gruesa de grasa debajo de la piel. Encima de la grasa tiene capas de plumas cortas, muy apretadas unas con otras. La grasa y las plumas guardan el calor del cuerpo, como un abrigo.",
      "Todos juntos",
      "En los días más fríos, miles de pingüinos se amontonan en un grupo grande. Los que quedan por fuera reciben el viento más helado. Por eso los pingüinos se mueven poco a poco, y cada uno toma su turno en el centro, donde hace más calor.",
      "Un huevo siempre caliente",
      "Cuando la mamá pone un huevo, se va al mar a comer. El papá sostiene el huevo sobre sus patas y lo tapa con un pliegue de piel calientito. Durante unos dos meses, se queda de pie en el frío y no come.",
      "Dato curioso: Un pingüino emperador puede medir casi 120 centímetros. Es el pingüino más grande del mundo.",
    ],
    qs: [
      how(Q("features", ["Under which heading can you read about what a father penguin does?", "¿En qué subtítulo puedes leer lo que hace un papá pingüino?"], ["Keeping the Egg Warm", "Un huevo siempre caliente"], [["Staying Together", "Todos juntos", "wrong-section"], ["Built for the Cold", "Hechos para el frío", "wrong-section"], ["Fast fact", "Dato curioso", "wrong-feature"]], ["Think about which section is about one penguin family, not the whole group.", "Piensa en qué sección habla de una familia de pingüinos, no de todo el grupo."], ["The father holds the egg on top of his feet", "El papá sostiene el huevo sobre sus patas"]), ["Skim each section for the word “father.”", "Lee rápido cada sección y busca la palabra “papá”."]),
      how(Q("features", ["What does the “Fast fact” tell readers?", "¿Qué le dice al lector el “Dato curioso”?"], ["How big an emperor penguin can grow", "Qué tan grande puede llegar a ser un pingüino emperador"], [["How penguins take turns in the huddle", "Cómo se turnan los pingüinos en el grupo", "wrong-section"], ["What the hard words in the article mean", "Qué significan las palabras difíciles del artículo", "wrong-feature"], ["Which section to read first", "Qué sección hay que leer primero", "wrong-feature"]], ["Read the box at the end of the article. What is it about?", "Lee el recuadro del final del artículo. ¿De qué trata?"], ["An emperor penguin can be almost four feet tall.", "Un pingüino emperador puede medir casi 120 centímetros."]), ["A fact box adds one extra fact to an article. Read it and say what the fact is about.", "Un recuadro de datos le agrega un dato extra al artículo. Léelo y di de qué trata el dato."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Emperor penguins have several ways to stay warm in the cold.", "Los pingüinos emperador tienen varias formas de aguantar el frío."], [["Penguin fathers keep the egg on their feet.", "Los papás pingüinos tienen el huevo sobre las patas.", "one-paragraph-only"], ["Antarctica is the coldest place on Earth.", "La Antártida es el lugar más frío de la Tierra.", "too-narrow"], ["All birds can live in cold places.", "Todas las aves pueden vivir en lugares fríos.", "not-in-text"]], ["Read the first paragraph and the headings. What do all the sections explain?", "Lee el primer párrafo y los subtítulos. ¿Qué explican todas las secciones?"], ["Yet these birds stay warm.", "Aun así, estas aves no pasan frío."]),
      Q("mainidea", ["Which detail supports the idea that penguins help each other stay warm?", "¿Qué detalle apoya la idea de que los pingüinos se ayudan a no pasar frío?"], ["Each penguin gets a turn in the warm middle of the huddle.", "Cada pingüino tiene su turno en el centro calientito del grupo."], [["A penguin has a thick layer of fat.", "El pingüino tiene una capa gruesa de grasa.", "supports-other-point"], ["The mother goes to the sea to eat.", "La mamá se va al mar a comer.", "supports-other-point"], ["Penguins fly to warm places in winter.", "Los pingüinos vuelan a lugares cálidos en invierno.", "not-in-text"]], ["Find the section about the whole group of penguins.", "Busca la sección sobre todo el grupo de pingüinos."], ["each one takes a turn in the warm middle", "cada uno toma su turno en el centro, donde hace más calor"]),
      Q("sequence", ["What does the mother penguin do right after she lays the egg?", "¿Qué hace la mamá pingüino justo después de poner el huevo?"], ["She leaves to find food in the sea.", "Se va a buscar comida al mar."], [["She holds the egg on her feet.", "Sostiene el huevo sobre sus patas.", "wrong-character"], ["She crowds into the huddle.", "Se mete en el grupo de pingüinos.", "not-in-text"], ["She builds a nest of sticks.", "Hace un nido de palitos.", "not-in-text"]], ["Find the sentence that begins “After the mother lays an egg.”", "Busca la oración que empieza con “Cuando la mamá pone un huevo”."], ["After the mother lays an egg, she goes to the sea to eat.", "Cuando la mamá pone un huevo, se va al mar a comer."]),
    ],
  },
  {
    id: "spiders",
    kind: "info",
    band: 1,
    title: ["Spiders and Their Silk", "Las arañas y su seda"],
    en: [
      "Spiders are not insects. An insect has six legs, but a spider has eight. Most spiders also have eight eyes. All spiders can make silk, a strong thread that comes out of their bodies.",
      "Spinning a Web",
      "Many spiders use silk to build webs. A garden spider starts with a few long threads, like the spokes of a wheel. Then it walks around and around, adding a sticky spiral. It can finish the whole web in less than an hour.",
      "Catching Dinner",
      "When an insect flies into the web, it gets stuck. The spider feels the threads shake and hurries over. Many spiders wrap their catch in silk to save it for later.",
      "Not Every Spider Spins",
      "Some spiders never build webs. A jumping spider sneaks up on insects and leaps on them. A wolf spider runs after its food on the ground. These spiders still use silk, though, to make a safety line or to wrap their eggs.",
      "Did you know? Many garden spiders eat their old web and spin a new one every day.",
    ],
    es: [
      "Las arañas no son insectos. Un insecto tiene seis patas, pero una araña tiene ocho. Casi todas las arañas tienen también ocho ojos. Todas las arañas pueden hacer seda, un hilo resistente que sale de su cuerpo.",
      "Cómo se teje una telaraña",
      "Muchas arañas usan la seda para hacer telarañas. La araña de jardín empieza con unos hilos largos, como los rayos de una rueda. Después camina en círculos y va agregando una espiral pegajosa. Puede terminar toda la telaraña en menos de una hora.",
      "La hora de comer",
      "Cuando un insecto choca con la telaraña, se queda pegado. La araña siente que los hilos se mueven y se acerca rápido. Muchas arañas envuelven a su presa en seda para guardarla para después.",
      "No todas tejen telarañas",
      "Algunas arañas nunca hacen telarañas. La araña saltarina se acerca a los insectos sin hacer ruido y les salta encima. La araña lobo corre detrás de su comida por el suelo. Aun así, estas arañas usan la seda para colgarse de un hilo de seguridad o para envolver sus huevos.",
      "¿Sabías que…? Muchas arañas de jardín se comen su telaraña vieja y tejen una nueva cada día.",
    ],
    qs: [
      how(Q("features", ["Under which heading can you read about a spider that leaps on its food?", "¿En qué subtítulo puedes leer sobre una araña que le salta encima a su comida?"], ["Not Every Spider Spins", "No todas tejen telarañas"], [["Catching Dinner", "La hora de comer", "wrong-section"], ["Spinning a Web", "Cómo se teje una telaraña", "wrong-section"], ["Did you know?", "¿Sabías que…?", "wrong-feature"]], ["Think about how a leaping spider gets its food. Does it wait in a web?", "Piensa en cómo consigue su comida una araña que salta. ¿Espera en una telaraña?"], ["A jumping spider sneaks up on insects and leaps on them.", "La araña saltarina se acerca a los insectos sin hacer ruido y les salta encima."]), ["Skim each section for the words “leaps” and “jumping.”", "Lee rápido cada sección y busca las palabras “salta” y “saltarina”."]),
      how(Q("features", ["What does the “Did you know?” box add to the article?", "¿Qué le agrega al artículo el recuadro “¿Sabías que…?”?"], ["A surprising fact about what garden spiders do with old webs", "Un dato sorprendente sobre lo que hacen las arañas de jardín con sus telarañas viejas"], [["The steps for building a web", "Los pasos para hacer una telaraña", "wrong-section"], ["The meanings of hard words", "El significado de las palabras difíciles", "wrong-feature"], ["A list of spider names", "Una lista de nombres de arañas", "not-in-text"]], ["Read the box at the end. What does it tell you that is new?", "Lee el recuadro del final. ¿Qué te dice que es nuevo?"], ["Many garden spiders eat their old web and spin a new one every day.", "Muchas arañas de jardín se comen su telaraña vieja y tejen una nueva cada día."]), ["A box set apart from the article adds an extra fact. Read it and ask what it tells that the sections do not.", "Un recuadro aparte del artículo agrega un dato extra. Léelo y pregúntate qué dice que no digan las secciones."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Spiders make silk and use it in many ways.", "Las arañas hacen seda y la usan de muchas maneras."], [["A spider has eight legs and eight eyes.", "Una araña tiene ocho patas y ocho ojos.", "one-paragraph-only"], ["Garden spiders build webs shaped like wheels.", "Las arañas de jardín hacen telarañas con forma de rueda.", "too-narrow"], ["Spiders are the most dangerous animals.", "Las arañas son los animales más peligrosos.", "not-in-text"]], ["Look at what every section talks about.", "Fíjate en de qué habla cada sección."], ["All spiders can make silk, a strong thread that comes out of their bodies.", "Todas las arañas pueden hacer seda, un hilo resistente que sale de su cuerpo."]),
      Q("mainidea", ["What is the main idea of the section “Not Every Spider Spins”?", "¿Cuál es la idea principal de la sección “No todas tejen telarañas”?"], ["Some spiders hunt without webs but still use silk.", "Algunas arañas cazan sin telaraña, pero igual usan la seda."], [["Wolf spiders run on the ground.", "La araña lobo corre por el suelo.", "too-narrow"], ["All spiders build webs.", "Todas las arañas hacen telarañas.", "opposite-of-text"], ["Spiders wrap insects to eat later.", "Las arañas envuelven insectos para comérselos después.", "wrong-section"]], ["Read the first and the last sentences of that section.", "Lee la primera y la última oración de esa sección."], ["Some spiders never build webs.", "Algunas arañas nunca hacen telarañas."]),
      Q("details", ["How does a spider in its web know that an insect is caught?", "¿Cómo sabe una araña en su telaraña que atrapó un insecto?"], ["It feels the threads shake.", "Siente cómo tiemblan los hilos."], [["It wraps the insect in silk.", "Envuelve al insecto en seda.", "wrong-detail"], ["It sees the insect with all eight eyes.", "Ve al insecto con sus ocho ojos.", "not-in-text"], ["It hears the insect buzz.", "Oye el zumbido del insecto.", "not-in-text"]], ["Find the part about an insect flying into the web.", "Busca la parte en que un insecto choca con la telaraña."], ["The spider feels the threads shake and hurries over.", "La araña siente que los hilos se mueven y se acerca rápido."]),
    ],
  },
  {
    id: "leaves",
    kind: "info",
    band: 1,
    title: ["Why Leaves Change Color", "Por qué cambian de color las hojas"],
    en: [
      "In the fall, many trees trade their green leaves for red, orange, and yellow ones. Then the leaves drop to the ground. Why does this happen?",
      "A Green Helper",
      "All summer, a leaf makes food for its tree from sunlight, air, and water. To do this, it uses chlorophyll, a green material inside the leaf. There is so much chlorophyll that it covers up every other color.",
      "Colors Hiding Underneath",
      "In the fall, days get shorter and nights get cooler. The tree stops making chlorophyll, and the green slowly fades. Now the yellow and orange that were in the leaf all along can show. Some trees, like many maples, also make new red colors.",
      "Time to Let Go",
      "Before winter, a thin layer grows where each leaf joins its branch. It cuts the leaf off, and the wind carries it away. The tree rests through the cold months and grows new green leaves in the spring.",
      "Try it: Collect three leaves of different colors. Draw each one and write the name of the tree it came from.",
    ],
    es: [
      "En otoño, muchos árboles cambian sus hojas verdes por hojas rojas, anaranjadas y amarillas. Luego las hojas caen al suelo. ¿Por qué pasa esto?",
      "Una ayudante verde",
      "Todo el verano, la hoja fabrica alimento para su árbol con la luz del sol, el aire y el agua. Para hacerlo, usa clorofila, una sustancia verde que hay dentro de la hoja. Hay tanta clorofila que tapa todos los demás colores.",
      "Colores escondidos",
      "En otoño, los días se hacen más cortos y las noches más frescas. El árbol deja de fabricar clorofila, y el verde se va borrando poco a poco. Entonces se ven el amarillo y el anaranjado que siempre estuvieron en la hoja. Algunos árboles, como muchos arces, también fabrican colores rojos nuevos.",
      "Hora de soltarse",
      "Antes del invierno, crece una capa delgada en el lugar donde la hoja se une a la rama. Esa capa separa la hoja, y el viento se la lleva. El árbol descansa durante los meses fríos y en primavera le salen hojas verdes nuevas.",
      "Pruébalo: Junta tres hojas de distintos colores. Dibuja cada una y escribe el nombre del árbol de donde vino.",
    ],
    qs: [
      how(Q("features", ["Under which heading can you learn where the yellow and orange colors come from?", "¿En qué subtítulo puedes saber de dónde salen los colores amarillo y anaranjado?"], ["Colors Hiding Underneath", "Colores escondidos"], [["A Green Helper", "Una ayudante verde", "wrong-section"], ["Time to Let Go", "Hora de soltarse", "wrong-section"], ["Try it", "Pruébalo", "wrong-feature"]], ["Think about which section is about the fall colors, not about summer or winter.", "Piensa en qué sección habla de los colores del otoño, no del verano ni del invierno."], ["Now the yellow and orange that were in the leaf all along can show.", "Entonces se ven el amarillo y el anaranjado que siempre estuvieron en la hoja."]), ["Skim each section for the color words “yellow” and “orange.”", "Lee rápido cada sección y busca los colores “amarillo” y “anaranjado”."]),
      how(Q("features", ["Why does the article end with a “Try it” box?", "¿Para qué termina el artículo con un recuadro de “Pruébalo”?"], ["To give readers something to do with real leaves", "Para darle al lector algo que hacer con hojas de verdad"], [["To explain why leaves fall", "Para explicar por qué se caen las hojas", "wrong-section"], ["To list the meanings of hard words", "Para dar el significado de las palabras difíciles", "wrong-feature"], ["To tell the main idea of the article", "Para decir la idea principal del artículo", "wrong-feature"]], ["Read the box at the end and look at its verbs.", "Lee el recuadro del final y fíjate en sus verbos."], ["Collect three leaves of different colors.", "Junta tres hojas de distintos colores."]), ["A box that begins with “Try it” speaks straight to the reader. Think about what it asks you to do.", "Un recuadro que empieza con “Pruébalo” le habla directo al lector. Piensa en qué te pide hacer."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Changes in the fall make leaves lose their green and drop from the tree.", "Los cambios del otoño hacen que las hojas pierdan su verde y se caigan del árbol."], [["Leaves make food from sunlight.", "Las hojas fabrican alimento con la luz del sol.", "one-paragraph-only"], ["Maple trees make red colors.", "Los arces fabrican colores rojos.", "too-narrow"], ["Trees are the biggest plants on Earth.", "Los árboles son las plantas más grandes de la Tierra.", "not-in-text"]], ["Read the question at the end of the first paragraph. The whole article answers it.", "Lee la pregunta al final del primer párrafo. Todo el artículo la responde."], ["Why does this happen?", "¿Por qué pasa esto?"]),
      Q("mainidea", ["Which detail supports the idea that the fall colors were in the leaf all summer?", "¿Qué detalle apoya la idea de que los colores del otoño estaban en la hoja todo el verano?"], ["The green chlorophyll covers up every other color.", "La clorofila verde tapa todos los demás colores."], [["A thin layer cuts the leaf off.", "Una capa delgada separa la hoja.", "supports-other-point"], ["The tree grows new leaves in the spring.", "En primavera le salen hojas nuevas al árbol.", "supports-other-point"], ["Cold rain paints the leaves.", "La lluvia fría pinta las hojas.", "not-in-text"]], ["Find the section about summer, when the leaf is still green.", "Busca la sección sobre el verano, cuando la hoja todavía está verde."], ["There is so much chlorophyll that it covers up every other color.", "Hay tanta clorofila que tapa todos los demás colores."]),
      Q("sequence", ["What happens right after the tree stops making chlorophyll?", "¿Qué pasa justo después de que el árbol deja de fabricar clorofila?"], ["The green color slowly fades from the leaf.", "El color verde se va borrando de la hoja."], [["A thin layer cuts the leaf off.", "Una capa delgada separa la hoja.", "wrong-order"], ["The leaf makes food from sunlight.", "La hoja fabrica alimento con la luz del sol.", "wrong-order"], ["The leaf turns blue.", "La hoja se pone azul.", "not-in-text"]], ["Find the sentence about chlorophyll in the fall, and read it to the end.", "Busca la oración sobre la clorofila en otoño y léela hasta el final."], ["The tree stops making chlorophyll, and the green slowly fades.", "El árbol deja de fabricar clorofila, y el verde se va borrando poco a poco."]),
    ],
  },
  {
    id: "lightning",
    kind: "info",
    band: 1,
    title: ["Lightning and Thunder", "Rayos y truenos"],
    en: [
      "During a storm, you might see a bright flash and then hear a loud boom. The flash is lightning, and the boom is thunder. They happen at the same time, but they do not reach you at the same time.",
      "A Giant Spark",
      "Lightning is a giant spark of electricity. It jumps between a cloud and the ground, or from one part of a cloud to another. A bolt of lightning is hotter than the surface of the sun.",
      "Where the Boom Comes From",
      "Lightning heats the air around it in a split second. The hot air spreads out so fast that it makes a huge sound wave. That sound is thunder.",
      "Counting the Miles",
      "Light travels much faster than sound, so you see the flash first. To guess how far away the lightning is, count the seconds until you hear thunder. Every five seconds means about one mile.",
      "Stay safe: When thunder roars, go indoors. Stay inside until 30 minutes after the last thunder.",
    ],
    es: [
      "Durante una tormenta, puedes ver un destello brillante y luego oír un estruendo. El destello es el rayo, y el estruendo es el trueno. Pasan al mismo tiempo, pero no te llegan al mismo tiempo.",
      "Una chispa gigante",
      "Un rayo es una chispa gigante de electricidad. Salta entre una nube y el suelo, o de una parte de una nube a otra. Un rayo está más caliente que la superficie del Sol.",
      "De dónde sale el estruendo",
      "El rayo calienta el aire que lo rodea en un instante. El aire caliente se expande tan rápido que produce una enorme onda de sonido. Ese sonido es el trueno.",
      "Contar la distancia",
      "La luz viaja mucho más rápido que el sonido, por eso primero ves el destello. Para calcular qué tan lejos está el rayo, cuenta los segundos hasta que oigas el trueno. Cada tres segundos son más o menos un kilómetro.",
      "Para estar a salvo: Cuando ruge el trueno, entra a un lugar cerrado. Quédate adentro hasta 30 minutos después del último trueno.",
    ],
    qs: [
      how(Q("features", ["Under which heading can you learn how to tell how far away a storm is?", "¿En qué subtítulo puedes aprender a saber qué tan lejos está una tormenta?"], ["Counting the Miles", "Contar la distancia"], [["Where the Boom Comes From", "De dónde sale el estruendo", "wrong-section"], ["A Giant Spark", "Una chispa gigante", "wrong-section"], ["Stay safe", "Para estar a salvo", "wrong-feature"]], ["Think about what you would have to do to find out how far away something is.", "Piensa en qué tendrías que hacer para saber qué tan lejos está algo."], ["count the seconds until you hear thunder", "cuenta los segundos hasta que oigas el trueno"]), ["Skim each section for the word “seconds.”", "Lee rápido cada sección y busca la palabra “segundos”."]),
      how(Q("features", ["Why is the “Stay safe” box set apart from the rest of the article?", "¿Por qué el recuadro “Para estar a salvo” está aparte del resto del artículo?"], ["It gives readers a safety rule to follow.", "Le da al lector una regla para cuidarse."], [["It explains how thunder is made.", "Explica cómo se forma el trueno.", "wrong-section"], ["It tells what the hard words mean.", "Dice qué significan las palabras difíciles.", "wrong-feature"], ["It names the next section.", "Nombra la siguiente sección.", "wrong-feature"]], ["Read the box. Who is it talking to?", "Lee el recuadro. ¿A quién le habla?"], ["When thunder roars, go indoors.", "Cuando ruge el trueno, entra a un lugar cerrado."]), ["A box can speak straight to the reader. Look at what it tells you to do.", "Un recuadro le puede hablar directo al lector. Fíjate en lo que te pide hacer."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Lightning causes thunder, and the time between them tells how far away it is.", "El rayo produce el trueno, y el tiempo entre los dos dice qué tan lejos está."], [["Lightning is hotter than the sun.", "El rayo está más caliente que el Sol.", "too-narrow"], ["Thunder is a sound wave.", "El trueno es una onda de sonido.", "one-paragraph-only"], ["Storms happen only in the summer.", "Las tormentas solo pasan en verano.", "not-in-text"]], ["Read the first paragraph. What two things is the article about?", "Lee el primer párrafo. ¿De qué dos cosas trata el artículo?"], ["The flash is lightning, and the boom is thunder.", "El destello es el rayo, y el estruendo es el trueno."]),
      Q("mainidea", ["What is the main idea of the section “Where the Boom Comes From”?", "¿Cuál es la idea principal de la sección “De dónde sale el estruendo”?"], ["Thunder is the sound of air heated by lightning.", "El trueno es el sonido del aire que calienta el rayo."], [["Light travels faster than sound.", "La luz viaja más rápido que el sonido.", "wrong-section"], ["Lightning jumps between clouds.", "El rayo salta entre las nubes.", "wrong-section"], ["Thunder can break windows.", "El trueno puede romper ventanas.", "not-in-text"]], ["Read the last sentence of that section.", "Lee la última oración de esa sección."], ["That sound is thunder.", "Ese sonido es el trueno."]),
      Q("sequence", ["Why do you see lightning before you hear thunder?", "¿Por qué ves el rayo antes de oír el trueno?"], ["Light moves much faster than sound.", "La luz va mucho más rápido que el sonido."], [["The thunder happens later than the lightning.", "El trueno pasa después del rayo.", "opposite-of-text"], ["Lightning is hotter than the sun.", "El rayo está más caliente que el Sol.", "wrong-detail"], ["Sound travels only at night.", "El sonido solo viaja de noche.", "not-in-text"]], ["Find the cause word “so” in the last section.", "Busca la palabra de causa “por eso” en la última sección."], ["Light travels much faster than sound, so you see the flash first.", "La luz viaja mucho más rápido que el sonido, por eso primero ves el destello."]),
    ],
  },
  {
    id: "teeth",
    kind: "info",
    band: 1,
    title: ["Your Two Sets of Teeth", "Tus dos juegos de dientes"],
    en: [
      "Most people get two sets of teeth in their lives. The first set comes in when you are a baby. The second set has to last for the rest of your life.",
      "Baby Teeth",
      "Most children have 20 baby teeth by about age three. Around age six, these teeth start to get loose and fall out, one at a time. Each one is pushed out by a bigger tooth growing underneath.",
      "Grown-Up Teeth",
      "Most adults have 32 teeth. Sharp front teeth cut food. Pointed teeth next to them tear it. Wide, flat teeth in the back grind it into small pieces.",
      "Keeping Teeth Strong",
      "Each tooth is covered in enamel, the hardest material in the human body. But sugar left on teeth helps germs make acid, and acid can make holes called cavities. Brushing for two minutes, two times a day, helps keep enamel strong.",
      "Glossary",
      "enamel: the hard, white outer layer of a tooth.\nmolar: a wide, flat tooth at the back of the mouth.",
    ],
    es: [
      "Casi todas las personas tienen dos juegos de dientes en la vida. El primero sale cuando eres bebé. El segundo te tiene que durar el resto de la vida.",
      "Los dientes de leche",
      "Casi todos los niños tienen 20 dientes de leche más o menos a los tres años. Alrededor de los seis años, esos dientes empiezan a aflojarse y se caen uno por uno. A cada uno lo empuja un diente más grande que crece debajo.",
      "Los dientes permanentes",
      "Casi todos los adultos tienen 32 dientes. Los dientes de adelante, que tienen filo, cortan la comida. Los dientes puntiagudos que están a su lado la desgarran. Los dientes anchos y planos de atrás la muelen en pedacitos.",
      "Dientes fuertes",
      "Cada diente está cubierto de esmalte, el material más duro del cuerpo humano. Pero el azúcar que queda en los dientes ayuda a los microbios a producir ácido, y el ácido puede hacer agujeros llamados caries. Cepillarte dos minutos, dos veces al día, ayuda a mantener fuerte el esmalte.",
      "Glosario",
      "esmalte: la capa dura y blanca que cubre el diente.\nmuela: diente ancho y plano de la parte de atrás de la boca.",
    ],
    qs: [
      how(Q("features", ["Where in the article can you find what “molar” means?", "¿En qué parte del artículo puedes encontrar qué significa “muela”?"], ["In the glossary", "En el glosario"], [["In the section “Grown-Up Teeth”", "En la sección “Los dientes permanentes”", "wrong-section"], ["In the first paragraph", "En el primer párrafo", "wrong-section"], ["In the title", "En el título", "wrong-feature"]], ["The word “molar” is not in the sections. Look at the very end of the article.", "La palabra “muela” no está en las secciones. Mira el final del artículo."], ["molar: a wide, flat tooth at the back of the mouth.", "muela: diente ancho y plano de la parte de atrás de la boca."]), ["Hard words are sometimes explained in a list of their own. Look for the word followed by a colon.", "A veces las palabras difíciles se explican en una lista aparte. Busca la palabra seguida de dos puntos."]),
      how(Q("features", ["Under which heading can you learn what pushes a loose tooth out?", "¿En qué subtítulo puedes saber qué empuja un diente flojo para que se caiga?"], ["Baby Teeth", "Los dientes de leche"], [["Grown-Up Teeth", "Los dientes permanentes", "wrong-section"], ["Keeping Teeth Strong", "Dientes fuertes", "wrong-section"], ["Glossary", "Glosario", "wrong-feature"]], ["Think about which teeth get loose when a child is about six.", "Piensa en qué dientes se aflojan cuando un niño tiene unos seis años."], ["Each one is pushed out by a bigger tooth growing underneath.", "A cada uno lo empuja un diente más grande que crece debajo."]), ["Skim each section for the words “pushed out.”", "Lee rápido cada sección y busca la palabra “empuja”."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["People get two sets of teeth, and the second set needs care to last.", "Las personas tienen dos juegos de dientes, y el segundo necesita cuidados para durar."], [["Adults have 32 teeth.", "Los adultos tienen 32 dientes.", "too-narrow"], ["Brushing keeps enamel strong.", "Cepillarse mantiene fuerte el esmalte.", "one-paragraph-only"], ["Sugar is the worst food in the world.", "El azúcar es la peor comida del mundo.", "not-in-text"]], ["Read the first paragraph, then think about what the last section adds.", "Lee el primer párrafo y luego piensa en lo que agrega la última sección."], ["The second set has to last for the rest of your life.", "El segundo te tiene que durar el resto de la vida."]),
      Q("mainidea", ["Which detail supports the idea that different teeth have different jobs?", "¿Qué detalle apoya la idea de que cada tipo de diente tiene su trabajo?"], ["Front teeth cut food, and back teeth grind it.", "Los dientes de adelante cortan la comida y los de atrás la muelen."], [["Most children have 20 baby teeth.", "Casi todos los niños tienen 20 dientes de leche.", "supports-other-point"], ["Enamel is the hardest material in the body.", "El esmalte es el material más duro del cuerpo.", "supports-other-point"], ["Teeth grow faster in the summer.", "Los dientes crecen más rápido en verano.", "not-in-text"]], ["Find the section about grown-up teeth.", "Busca la sección sobre los dientes permanentes."], ["Sharp front teeth cut food.", "Los dientes de adelante, que tienen filo, cortan la comida."]),
      Q("details", ["What can make holes in teeth?", "¿Qué puede hacer agujeros en los dientes?"], ["Acid made by germs", "El ácido que producen los microbios"], [["Bigger teeth growing underneath", "Los dientes que crecen debajo", "wrong-detail"], ["Brushing too much", "Cepillarse demasiado", "not-in-text"], ["The enamel on each tooth", "El esmalte de cada diente", "opposite-of-text"]], ["Find the word “cavities” in the last section. What makes them?", "Busca la palabra “caries” en la última sección. ¿Qué las produce?"], ["acid can make holes called cavities", "el ácido puede hacer agujeros llamados caries"]),
    ],
  },
  {
    id: "snowflakes",
    kind: "info",
    band: 1,
    title: ["How a Snowflake Forms", "Cómo se forma un copo de nieve"],
    en: [
      "A snowflake starts high in a cloud, where the air is below freezing. It begins as a tiny speck of dust or pollen.",
      "From Water to Ice",
      "Water vapor, which is water in the form of a gas, floats in the cloud. When it touches the cold speck, it freezes onto it. The speck becomes a tiny ice crystal.",
      "Growing Six Arms",
      "Ice crystals almost always have six sides. As the crystal falls through the cloud, more water vapor freezes onto its corners. Slowly, six arms grow out from the center.",
      "No Two Alike",
      "Each snowflake takes its own path through the cloud. The air is a little warmer or wetter in some places than in others. That changes how the arms grow, so scientists think no two snowflakes are exactly alike.",
      "Fast fact: In 1885, a farmer named Wilson Bentley became the first person to take a photo of a single snowflake.",
    ],
    es: [
      "Un copo de nieve empieza muy alto en una nube, donde el aire está bajo cero. Al principio es una motita de polvo o de polen.",
      "Del agua al hielo",
      "En la nube flota vapor de agua, que es agua en forma de gas. Cuando toca la motita fría, se congela sobre ella. La motita se convierte en un cristal de hielo diminuto.",
      "Seis brazos",
      "Los cristales de hielo casi siempre tienen seis lados. Mientras el cristal cae por la nube, más vapor de agua se congela en sus esquinas. Poco a poco, le crecen seis brazos desde el centro.",
      "Ninguno es igual",
      "Cada copo de nieve sigue su propio camino por la nube. En algunas partes, el aire está un poco más tibio o más húmedo que en otras. Eso cambia la forma en que crecen los brazos, así que los científicos creen que no hay dos copos exactamente iguales.",
      "Dato curioso: En 1885, un granjero llamado Wilson Bentley fue la primera persona en tomarle una foto a un solo copo de nieve.",
    ],
    qs: [
      how(Q("features", ["Under which heading can you learn why snowflakes look different from each other?", "¿En qué subtítulo puedes saber por qué los copos de nieve se ven distintos entre sí?"], ["No Two Alike", "Ninguno es igual"], [["Growing Six Arms", "Seis brazos", "wrong-section"], ["From Water to Ice", "Del agua al hielo", "wrong-section"], ["Fast fact", "Dato curioso", "wrong-feature"]], ["Think about which section compares one snowflake with another.", "Piensa en qué sección compara un copo de nieve con otro."], ["Each snowflake takes its own path through the cloud.", "Cada copo de nieve sigue su propio camino por la nube."]), ["Skim each section for the word “path.”", "Lee rápido cada sección y busca la palabra “camino”."]),
      how(Q("features", ["What does the “Fast fact” add to the article?", "¿Qué le agrega al artículo el “Dato curioso”?"], ["A piece of history about the first snowflake photo", "Un dato de historia sobre la primera foto de un copo de nieve"], [["The steps a snowflake goes through", "Los pasos por los que pasa un copo de nieve", "wrong-section"], ["The meanings of hard words", "El significado de las palabras difíciles", "wrong-feature"], ["The reason snowflakes have six arms", "La razón por la que los copos tienen seis brazos", "wrong-section"]], ["Read the box at the end. Who is it about?", "Lee el recuadro del final. ¿De quién habla?"], ["a farmer named Wilson Bentley became the first person to take a photo of a single snowflake", "un granjero llamado Wilson Bentley fue la primera persona en tomarle una foto a un solo copo de nieve"]), ["A fact box adds something the sections do not cover. Ask what kind of fact this one is.", "Un recuadro de datos agrega algo que no está en las secciones. Pregúntate qué tipo de dato es este."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["A snowflake grows from a speck in a cold cloud into a six-armed crystal.", "Un copo de nieve crece en una nube fría, de una motita a un cristal de seis brazos."], [["Wilson Bentley took a photo of a snowflake.", "Wilson Bentley le tomó una foto a un copo de nieve.", "one-paragraph-only"], ["Water vapor is a gas.", "El vapor de agua es un gas.", "too-narrow"], ["Snow is the best kind of weather.", "La nieve es el mejor tipo de clima.", "not-in-text"]], ["Read the title and the headings in order.", "Lee el título y los subtítulos en orden."], ["A snowflake starts high in a cloud, where the air is below freezing.", "Un copo de nieve empieza muy alto en una nube, donde el aire está bajo cero."]),
      Q("mainidea", ["What is the main idea of the section “Growing Six Arms”?", "¿Cuál es la idea principal de la sección “Seis brazos”?"], ["As it falls, the crystal grows six arms.", "Al caer, el cristal va formando seis brazos."], [["Each snowflake takes its own path.", "Cada copo sigue su propio camino.", "wrong-section"], ["A snowflake starts as a speck of dust.", "Un copo empieza como una motita de polvo.", "wrong-section"], ["Snowflakes melt when they land.", "Los copos se derriten al caer al suelo.", "not-in-text"]], ["Read the whole section, then say in a few words what changes.", "Lee toda la sección y luego di en pocas palabras qué cambia."], ["Slowly, six arms grow out from the center.", "Poco a poco, le crecen seis brazos desde el centro."]),
      Q("sequence", ["What happens right after water vapor touches the cold speck?", "¿Qué pasa justo después de que el vapor de agua toca la motita fría?"], ["The vapor freezes onto the speck.", "El vapor se congela sobre la motita."], [["Six arms grow out from the center.", "Le crecen seis brazos desde el centro.", "wrong-order"], ["The snowflake melts into rain.", "El copo se derrite y se vuelve lluvia.", "not-in-text"], ["The speck floats out of the cloud.", "La motita sale flotando de la nube.", "not-in-text"]], ["Find the section about water turning into ice.", "Busca la sección sobre el agua que se vuelve hielo."], ["When it touches the cold speck, it freezes onto it.", "Cuando toca la motita fría, se congela sobre ella."]),
    ],
  },
];
