import { Q, type Passage } from "./types";

// Band 1 stories, grade 2–3 text band (draft: written for KaizenEDU, not yet reviewed by a teacher).
export const BAND1_STORIES: Passage[] = [
  {
    id: "kite",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Amara patched the hole herself.", "Amara tapó el agujero ella sola."],
    title: ["Amara's Kite", "La cometa de Amara"],
    en: [
      "Amara and her grandfather spent Saturday morning building a kite. They used two thin sticks, a sheet of red paper, and a long tail made of ribbon. Grandpa showed her how to tie the sticks in the shape of a cross.",
      "At the park, the wind was strong. Amara ran across the grass, and the kite rose higher and higher. Then a gust pulled it into a tree. When she got it down, the paper had a long tear.",
      "Amara's eyes filled with tears. “It's ruined,” she said. “We should just go home.”",
      "Grandpa sat down on a bench and opened his bag. He took out tape and a few sheets of paper. “A torn kite is not a ruined kite,” he said. “It is a kite that needs a patch.”",
      "Amara patched the hole herself. She even added a second ribbon to the tail so the kite would fly steadier. This time she stayed far from the trees. The red kite climbed until it was a tiny dot in the blue sky.",
    ],
    es: [
      "Amara y su abuelo pasaron la mañana del sábado haciendo una cometa. Usaron dos palitos delgados, una hoja de papel rojo y una cola larga hecha de listón. El abuelo le enseñó a amarrar los palitos en forma de cruz.",
      "En el parque soplaba un viento fuerte. Amara corrió por el pasto y la cometa subió cada vez más alto. De pronto, una ráfaga la lanzó contra un árbol. Cuando Amara logró bajarla, el papel tenía una rotura larga.",
      "A Amara se le llenaron los ojos de lágrimas. “Se arruinó”, dijo. “Mejor vámonos a casa”.",
      "El abuelo se sentó en una banca y abrió su bolsa. Sacó cinta adhesiva y unas hojas de papel. “Una cometa rota no es una cometa arruinada”, dijo. “Es una cometa que necesita un parche”.",
      "Amara tapó el agujero ella sola. Hasta le agregó otro listón a la cola para que la cometa volara más estable. Esta vez se alejó de los árboles. La cometa roja subió hasta parecer un puntito en el cielo azul.",
    ],
    qs: [
      Q("character", ["Which word best describes Grandpa?", "¿Qué palabra describe mejor al abuelo?"], ["Patient", "Paciente"], [["Impatient", "Impaciente", "opposite-trait"], ["Careless", "Descuidado", "trait-not-shown"], ["Bossy", "Mandón", "trait-not-shown"]], ["Look at what Grandpa says and does after the kite tears.", "Fíjate en lo que dice y hace el abuelo cuando se rompe la cometa."], ["“A torn kite is not a ruined kite,” he said.", "“Una cometa rota no es una cometa arruinada”, dijo."]),
      Q("theme", ["What lesson does the story teach?", "¿Qué lección enseña el cuento?"], ["When something goes wrong, you can fix it and try again.", "Cuando algo sale mal, puedes arreglarlo y volver a intentarlo."], [["Amara flies a kite with her grandfather at the park.", "Amara vuela una cometa con su abuelo en el parque.", "plot-summary"], ["Never fly a kite on a windy day.", "Nunca vueles una cometa en un día de viento.", "unsupported-lesson"], ["Red paper is best for making kites.", "El papel rojo es el mejor para hacer cometas.", "too-narrow"]], ["Amara wants to go home, but in the end she does not. What changes her mind?", "Amara quiere irse a casa, pero al final no se va. ¿Qué la hace cambiar de idea?"], ["“It is a kite that needs a patch.”", "“Es una cometa que necesita un parche”"]),
      Q("sequence", ["What happened right after the gust pulled the kite into a tree?", "¿Qué pasó justo después de que la ráfaga lanzó la cometa contra el árbol?"], ["Amara got the kite down and saw it was torn.", "Amara bajó la cometa y vio que estaba rota."], [["Grandpa tied the sticks in a cross.", "El abuelo amarró los palitos en cruz.", "wrong-order"], ["The kite became a tiny dot in the sky.", "La cometa se volvió un puntito en el cielo.", "wrong-order"], ["Amara bought a new kite.", "Amara compró una cometa nueva.", "not-in-text"]], ["Find the sentence about the tree, then read the one after it.", "Busca la oración sobre el árbol y lee la que sigue."], ["When she got it down, the paper had a long tear.", "Cuando Amara logró bajarla, el papel tenía una rotura larga."]),
      Q("details", ["What did Amara add to the kite, and why?", "¿Qué le agregó Amara a la cometa y para qué?"], ["Another ribbon, to help it fly more steadily", "Otro listón, para que volara más firme"], [["More tape, to make it stronger", "Más cinta, para hacerla más fuerte", "not-in-text"], ["A longer string, to fly it higher", "Un hilo más largo, para que subiera más", "not-in-text"], ["A second stick, to make it bigger", "Otro palito, para hacerla más grande", "not-in-text"]], ["Look at the end of the story, where Amara fixes the kite.", "Mira el final del cuento, cuando Amara arregla la cometa."], ["She even added a second ribbon to the tail so the kite would fly steadier.", "Hasta le agregó otro listón a la cola para que la cometa volara más estable."]),
      Q("words", ["In this story, what does “gust” mean?", "En este cuento, ¿qué significa “ráfaga”?"], ["A sudden, strong rush of wind", "Un golpe de viento fuerte y repentino"], [["A soft, warm breeze", "Una brisa suave y tibia", "opposite-meaning"], ["A tall tree branch", "Una rama alta de un árbol", "ignored-context"], ["A loud crowd of people", "Un grupo ruidoso de personas", "ignored-context"]], ["The gust pulled the kite into a tree. What can push a kite through the air?", "La ráfaga lanzó la cometa contra un árbol. ¿Qué puede mover una cometa por el aire?"], ["Then a gust pulled it into a tree.", "De pronto, una ráfaga la lanzó contra un árbol."]),
    ],
  },
  {
    id: "tamales",
    kind: "fiction",
    band: 1,
    pov: "first",
    povEv: ["This year, I wanted to help instead of just eating.", "Este año, yo quería ayudar en vez de solo comer."],
    title: ["Tamale Day", "Día de tamales"],
    en: [
      "Every December, my whole family makes tamales at my grandmother's house. This year, I wanted to help instead of just eating.",
      "Abuela gave me a job. I had to spread masa, a soft corn dough, on the corn husks. My first husk looked like a lumpy pancake. The masa was too thick, and it slid off the edge.",
      "“Thin, like butter on toast,” Abuela said. She showed me how to use the back of a spoon. I tried again, slowly this time. My second husk was better, and my tenth one was almost perfect.",
      "My cousin Rosa added the filling. My uncle folded each tamale and stood it up in the big pot. By the afternoon, we had made six dozen.",
      "That night, the kitchen smelled like corn and chile. When Abuela opened the pot, I found one lumpy tamale. I knew it was my first one. I ate it anyway, and it tasted great.",
    ],
    es: [
      "Cada diciembre, toda mi familia hace tamales en la casa de mi abuela. Este año, yo quería ayudar en vez de solo comer.",
      "La abuela me dio un trabajo. Tenía que untar masa, una pasta suave de maíz, sobre las hojas de maíz. Mi primera hoja parecía un panqueque lleno de bolitas. La masa estaba demasiado gruesa y se resbalaba por la orilla.",
      "“Delgadita, como mantequilla en el pan tostado”, dijo la abuela. Me enseñó a usar el revés de una cuchara. Lo intenté otra vez, despacio. Mi segunda hoja quedó mejor, y la décima quedó casi perfecta.",
      "Mi prima Rosa ponía el relleno. Mi tío doblaba cada tamal y lo acomodaba de pie en la olla grande. Para la tarde, ya habíamos hecho seis docenas.",
      "Esa noche, la cocina olía a maíz y a chile. Cuando la abuela abrió la olla, encontré un tamal todo chueco. Supe que era el primero que hice yo. Me lo comí de todos modos, y estaba riquísimo.",
    ],
    qs: [
      Q("character", ["Why does the narrator want to work in the kitchen this year?", "¿Por qué quien narra quiere trabajar en la cocina este año?"], ["To help make the tamales, not only eat them", "Para ayudar a hacer los tamales, no solo comérselos"], [["To win a cooking contest", "Para ganar un concurso de cocina", "wrong-motive"], ["Because Abuela is sick and cannot cook", "Porque la abuela está enferma y no puede cocinar", "not-in-text"], ["Because Rosa asks for help with her job", "Porque Rosa le pide ayuda con su trabajo", "wrong-character"]], ["The narrator gives the reason near the very beginning.", "Quien narra dice la razón casi al principio."], ["This year, I wanted to help instead of just eating.", "Este año, yo quería ayudar en vez de solo comer."]),
      Q("sequence", ["What did the narrator do right after Abuela showed how to use the back of a spoon?", "¿Qué hizo quien narra justo después de que la abuela le enseñó a usar el revés de la cuchara?"], ["Tried again, more slowly", "Lo intentó de nuevo, más despacio."], [["Spread masa that was too thick", "Untó masa demasiado gruesa.", "wrong-order"], ["Ate the lumpy tamale", "Se comió su tamal chueco.", "wrong-order"], ["Added the filling", "Puso el relleno.", "wrong-character"]], ["Find the sentence about the spoon, then read what comes next.", "Busca la oración de la cuchara y lee lo que sigue."], ["I tried again, slowly this time.", "Lo intenté otra vez, despacio."]),
      Q("words", ["What does “masa” mean in this story?", "¿Qué significa “masa” en este cuento?"], ["Dough made from corn", "Pasta de maíz"], [["A corn husk", "Una hoja de maíz", "wrong-detail"], ["A spicy filling", "Un relleno picante", "wrong-detail"], ["A large cooking pot", "Una olla grande", "ignored-context"]], ["The writer explains the word right after it, between commas.", "Quien escribe explica la palabra justo después, entre comas."], ["I had to spread masa, a soft corn dough, on the corn husks.", "Tenía que untar masa, una pasta suave de maíz, sobre las hojas de maíz."]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Practice helps you get better at something new.", "La práctica te ayuda a mejorar en algo nuevo."], [["A family makes six dozen tamales in December.", "Una familia hace seis docenas de tamales en diciembre.", "plot-summary"], ["It is better to cook alone.", "Es mejor cocinar solo.", "unsupported-lesson"], ["Masa should be spread thin.", "La masa se debe untar delgadita.", "too-narrow"]], ["Compare the narrator's first husk with the tenth one.", "Compara la primera hoja de quien narra con la décima."], ["My second husk was better, and my tenth one was almost perfect.", "Mi segunda hoja quedó mejor, y la décima quedó casi perfecta."]),
      Q("character", ["How does the narrator feel about the lumpy tamale at the end?", "¿Cómo se siente quien narra con su tamal chueco al final?"], ["Happy to eat it, even though it looks lumpy", "Con alegría de comérselo, aunque se vea chueco"], [["Ashamed enough to throw it away", "Con tanta vergüenza que lo tira", "opposite-of-text"], ["Angry at Abuela for keeping it", "Con enojo porque la abuela lo guardó", "not-in-text"], ["Tired of eating tamales", "Con cansancio de comer tamales", "not-in-text"]], ["Read the last two sentences. What does the narrator do with the tamale?", "Lee las dos últimas oraciones. ¿Qué hace con el tamal?"], ["I ate it anyway, and it tasted great.", "Me lo comí de todos modos, y estaba riquísimo."]),
    ],
  },
  {
    id: "library-card",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Kenji walked to the picture book shelf.", "Kenji fue al estante de libros ilustrados."],
    title: ["Kenji's First Library Card", "La primera tarjeta de Kenji"],
    en: [
      "Kenji signed his name on the line, and the librarian handed him a blue card. It was his very first library card. “You may borrow up to five books,” she said.",
      "Kenji knew exactly what he wanted: books about sharks. He found two right away. Then he stopped. His little sister, Yumi, was home with a cold. She had been sad all week because she could not go outside.",
      "Kenji walked to the picture book shelf. Yumi loved cats more than anything, so he found three books with cats on the covers. One cat wore boots, one cat played the drums, and one cat was lost in the snow.",
      "At home, Yumi was lying on the couch under a blanket. Kenji sat next to her and opened the book about the lost cat. He read in a squeaky voice for the cat and a deep voice for the snowplow driver. Yumi laughed so hard that she started coughing.",
      "“Read it again,” she said. Kenji smiled. His shark books could wait until tomorrow.",
    ],
    es: [
      "Kenji firmó en la línea y la bibliotecaria le dio una tarjeta azul. Era su primera tarjeta de la biblioteca. “Puedes llevarte hasta cinco libros”, le dijo.",
      "Kenji sabía exactamente qué quería: libros de tiburones. Encontró dos enseguida. Entonces se detuvo. Su hermanita, Yumi, estaba en casa con un resfriado. Había estado triste toda la semana porque no podía salir a jugar.",
      "Kenji fue al estante de libros ilustrados. A Yumi le encantaban los gatos más que nada, así que buscó tres libros con gatos en la portada. En uno, el gato usaba botas; en otro, tocaba la batería, y en el tercero, se perdía en la nieve.",
      "En casa, Yumi estaba acostada en el sofá bajo una cobija. Kenji se sentó a su lado y abrió el libro del gato perdido. Leyó con una voz chillona para el gato y una voz grave para el conductor de la quitanieves. Yumi se rio tanto que empezó a toser.",
      "“Léelo otra vez”, le pidió. Kenji sonrió. Sus libros de tiburones podían esperar hasta mañana.",
    ],
    qs: [
      Q("character", ["Which word best describes Kenji?", "¿Qué palabra describe mejor a Kenji?"], ["Thoughtful", "Considerado"], [["Selfish", "Egoísta", "opposite-trait"], ["Lazy", "Perezoso", "trait-not-shown"], ["Forgetful", "Olvidadizo", "trait-not-shown"]], ["Think about who Kenji picks books for.", "Piensa en para quién escoge libros Kenji."], ["Yumi loved cats more than anything, so he found three books with cats on the covers.", "A Yumi le encantaban los gatos más que nada, así que buscó tres libros con gatos en la portada."]),
      Q("character", ["Why does Kenji choose books about cats?", "¿Por qué Kenji escoge libros de gatos?"], ["His sister loves cats and is sick at home.", "A su hermana le encantan los gatos y está enferma en casa."], [["He likes cats more than sharks.", "Le gustan más los gatos que los tiburones.", "wrong-motive"], ["The librarian tells him to.", "La bibliotecaria se lo pide.", "not-in-text"], ["There are no shark books left.", "Ya no quedan libros de tiburones.", "opposite-of-text"]], ["Kenji stops looking for shark books. Who does he think of?", "Kenji deja de buscar libros de tiburones. ¿En quién piensa?"], ["His little sister, Yumi, was home with a cold.", "Su hermanita, Yumi, estaba en casa con un resfriado."]),
      Q("details", ["How many books may Kenji borrow?", "¿Cuántos libros puede llevarse Kenji?"], ["Five books at most", "Cinco libros como máximo"], [["Exactly two", "Exactamente dos", "wrong-detail"], ["Exactly three", "Exactamente tres", "wrong-detail"], ["As many as he wants", "Todos los que quiera", "not-in-text"]], ["Look at what the librarian tells Kenji.", "Fíjate en lo que le dice la bibliotecaria."], ["“You may borrow up to five books,” she said.", "“Puedes llevarte hasta cinco libros”, le dijo."]),
      Q("sequence", ["What does Kenji do right after he finds two shark books?", "¿Qué hace Kenji justo después de encontrar dos libros de tiburones?"], ["He stops and thinks about his sister.", "Se detiene y piensa en su hermana."], [["He signs his name for a card.", "Firma para recibir su tarjeta.", "wrong-order"], ["He reads to Yumi on the couch.", "Le lee a Yumi en el sofá.", "wrong-order"], ["He puts the shark books back on the shelf.", "Devuelve los libros de tiburones al estante.", "not-in-text"]], ["Find where Kenji finds the shark books. What is the very next thing he does?", "Busca dónde encuentra Kenji los libros de tiburones. ¿Qué hace justo después?"], ["Then he stopped.", "Entonces se detuvo."]),
      Q("theme", ["What lesson does the story show?", "¿Qué lección muestra el cuento?"], ["Doing something kind for someone can matter more than getting what you want first.", "Hacer algo amable por alguien puede importar más que tener primero lo que tú quieres."], [["Kenji gets his first library card.", "Kenji recibe su primera tarjeta de la biblioteca.", "plot-summary"], ["Books about sharks are boring.", "Los libros de tiburones son aburridos.", "unsupported-lesson"], ["Reading in a funny voice can make people cough.", "Leer con voz chistosa puede hacer toser a la gente.", "too-narrow"]], ["Read the last sentence. What does Kenji choose to put first?", "Lee la última oración. ¿Qué decide Kenji poner primero?"], ["His shark books could wait until tomorrow.", "Sus libros de tiburones podían esperar hasta mañana."]),
    ],
  },
  {
    id: "bean-diary",
    kind: "fiction",
    band: 1,
    pov: "first",
    povEv: ["I measured it with my ruler every morning.", "Lo medía con mi regla todas las mañanas."],
    title: ["My Bean Diary", "Mi diario del frijol"],
    en: [
      "On Monday, my teacher gave everyone a bean seed, a clear cup, and a paper towel. “Watch it closely, Priya,” she told me. I folded the wet towel inside the cup and slid my seed between the towel and the plastic. That way I could see it.",
      "On Wednesday, my seed looked fatter, and its skin was wrinkled. By Friday, the skin had split. A tiny white root poked out and curled down toward the bottom of the cup.",
      "Over the weekend, I forgot all about my bean. On Monday, the towel was dry and the root looked limp. I felt terrible. I poured in water right away and set the cup back on the sunny windowsill.",
      "Two days later, a green shoot with two small leaves pushed up out of the top of the seed. I measured it with my ruler every morning. Now I write in my bean diary every day, and I water my cup before I do anything else.",
    ],
    es: [
      "El lunes, la maestra nos dio a cada uno una semilla de frijol, un vaso transparente y una toalla de papel. “Obsérvala bien, Priya”, me dijo. Doblé la toalla mojada dentro del vaso y metí mi semilla entre la toalla y el plástico. Así podría verla.",
      "El miércoles, mi semilla se veía más gorda y tenía la piel arrugada. Para el viernes, la piel se había abierto. Una raíz blanca y diminuta salió y se curvó hacia el fondo del vaso.",
      "Durante el fin de semana, me olvidé por completo de mi frijol. El lunes, la toalla estaba seca y la raíz se veía débil y caída. Me sentí muy mal. Enseguida le eché agua y volví a poner el vaso en la ventana soleada.",
      "Dos días después, un tallito verde con dos hojitas brotó por encima de la semilla. Lo medía con mi regla todas las mañanas. Ahora escribo en mi diario del frijol todos los días, y riego mi vaso antes de hacer cualquier otra cosa.",
    ],
    qs: [
      Q("sequence", ["Which of these happened first?", "¿Cuál de estas cosas pasó primero?"], ["A white root came out of the seed.", "Le salió una raíz blanca a la semilla."], [["A green shoot with two leaves grew.", "Creció un tallito verde con dos hojitas.", "wrong-order"], ["The paper towel dried out.", "La toalla de papel se secó.", "wrong-order"], ["The bean grew a flower.", "Al frijol le salió una flor.", "not-in-text"]], ["Use the days of the week in the story to put the events in order.", "Usa los días de la semana del cuento para ordenar los sucesos."], ["A tiny white root poked out and curled down toward the bottom of the cup.", "Una raíz blanca y diminuta salió y se curvó hacia el fondo del vaso."]),
      Q("theme", ["What lesson does Priya learn?", "¿Qué lección aprende Priya?"], ["A living thing needs care every day, not only when you remember it.", "Un ser vivo necesita cuidados todos los días, no solo cuando te acuerdas."], [["Priya grows a bean in a clear cup.", "Priya hace crecer un frijol en un vaso transparente.", "plot-summary"], ["Plants grow best when you leave them alone.", "Las plantas crecen mejor si las dejas solas.", "unsupported-lesson"], ["A ruler can measure a shoot.", "Con una regla se puede medir un tallito.", "too-narrow"]], ["What went wrong over the weekend, and what does Priya do now because of it?", "¿Qué salió mal el fin de semana y qué hace Priya ahora por eso?"], ["Over the weekend, I forgot all about my bean.", "Durante el fin de semana, me olvidé por completo de mi frijol."]),
      Q("character", ["How does Priya change by the end of the story?", "¿Cómo cambia Priya al final del cuento?"], ["She remembers to care for her bean every day.", "Se acuerda de cuidar su frijol todos los días."], [["She stops caring about her bean.", "Deja de interesarse en su frijol.", "opposite-of-text"], ["She gives her bean to her teacher.", "Le regala su frijol a la maestra.", "not-in-text"], ["She plants a whole garden outside.", "Siembra un jardín entero afuera.", "not-in-text"]], ["Read the last sentence. What does Priya do now before anything else?", "Lee la última oración. ¿Qué hace Priya ahora antes que nada?"], ["Now I write in my bean diary every day, and I water my cup before I do anything else.", "Ahora escribo en mi diario del frijol todos los días, y riego mi vaso antes de hacer cualquier otra cosa."]),
      Q("words", ["In this story, what does “limp” mean?", "En este cuento, ¿qué significa “caída”?"], ["Weak and drooping, not firm", "Doblada hacia abajo, sin fuerza"], [["Walking unevenly because of a hurt leg", "Un golpe al caerse al piso", "other-meaning"], ["Healthy and strong", "Sana y fuerte", "opposite-meaning"], ["Very long and thick", "Muy larga y gruesa", "ignored-context"]], ["The towel was dry. How does a plant look when it gets no water?", "La toalla estaba seca. ¿Cómo se ve una planta que no recibe agua?"], ["On Monday, the towel was dry and the root looked limp.", "El lunes, la toalla estaba seca y la raíz se veía débil y caída."]),
      Q("pov", ["Which sentence shows that Priya is the one telling this story?", "¿Qué oración muestra que Priya es quien cuenta esta historia?"], ["I felt terrible.", "Me sentí muy mal."], [["By Friday, the skin had split.", "Para el viernes, la piel se había abierto.", "no-narrator-clue"], ["Two days later, a green shoot with two small leaves pushed up out of the top of the seed.", "Dos días después, un tallito verde con dos hojitas brotó por encima de la semilla.", "no-narrator-clue"]], ["Look for words like I, me, or my outside of quotation marks.", "Busca palabras como yo, me o mi fuera de las comillas."], ["I measured it with my ruler every morning.", "Lo medía con mi regla todas las mañanas."]),
    ],
  },
  {
    id: "squirrel",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Every fall, Pip buried acorns all over the forest so he would have food for winter.", "Cada otoño, Pipo enterraba bellotas por todo el bosque para tener comida en el invierno."],
    title: ["The Squirrel Who Hid Too Many Acorns", "La ardilla que escondió demasiadas bellotas"],
    en: [
      "Long ago, in a forest of tall oaks, there lived a squirrel named Pip. Every fall, Pip buried acorns all over the forest so he would have food for winter.",
      "One year, Pip buried more acorns than ever. He hid them under rocks, beside streams, and in the soft ground near the meadow. “Why do you need so many?” asked his friend Dot, a small brown bird. “You could never eat them all.” Pip only shrugged and kept digging.",
      "When winter came, Pip dug up as many acorns as he could find. But he had hidden so many that he forgot where most of them were. In the spring, Pip was embarrassed. “All that work, wasted,” he sighed.",
      "Years later, Pip and Dot walked through the meadow. Young oak trees now stood in rows where the bare ground had been. Birds nested in their branches, and deer rested in their shade.",
      "“Those are your acorns,” said Dot. Pip looked around in wonder. The acorns he had forgotten had grown into something that helped the whole forest.",
    ],
    es: [
      "Hace mucho tiempo, en un bosque de robles altos, vivía una ardilla llamada Pipo. Cada otoño, Pipo enterraba bellotas por todo el bosque para tener comida en el invierno.",
      "Un año, Pipo enterró más bellotas que nunca. Las escondió bajo las piedras, junto a los arroyos y en la tierra blanda cerca de la pradera. “¿Para qué necesitas tantas?”, le preguntó su amiga Pinta, un pajarito café. “Nunca podrías comértelas todas”. Pipo solo se encogió de hombros y siguió cavando.",
      "Cuando llegó el invierno, Pipo desenterró todas las bellotas que pudo encontrar. Pero había escondido tantas que olvidó dónde estaba la mayoría. En la primavera, Pipo estaba avergonzado. “Tanto trabajo para nada”, suspiró.",
      "Años después, Pipo y Pinta pasearon por la pradera. Donde antes había tierra pelada, ahora crecían filas de robles jóvenes. Los pájaros hacían nidos en sus ramas y los venados descansaban a su sombra.",
      "“Esas son tus bellotas”, dijo Pinta. Pipo miró a su alrededor, asombrado. Las bellotas que había olvidado se habían convertido en algo que ayudaba a todo el bosque.",
    ],
    qs: [
      Q("sequence", ["Why did young oak trees grow in the meadow?", "¿Por qué crecieron robles jóvenes en la pradera?"], ["Pip forgot many of the acorns he buried, and they sprouted.", "Pipo olvidó muchas de las bellotas que enterró, y germinaron."], [["Birds built nests there.", "Los pájaros hicieron nidos ahí.", "effect-not-cause"], ["Dot planted them for the deer.", "Pinta los sembró para los venados.", "not-in-text"], ["Pip dug up every one of his acorns.", "Pipo desenterró hasta la última de sus bellotas.", "opposite-of-text"]], ["Dot says the trees are Pip's acorns. What happened to the acorns Pip never found?", "Pinta dice que los árboles son las bellotas de Pipo. ¿Qué pasó con las que Pipo nunca encontró?"], ["The acorns he had forgotten had grown into something that helped the whole forest.", "Las bellotas que había olvidado se habían convertido en algo que ayudaba a todo el bosque."]),
      Q("theme", ["What is the lesson of this fable?", "¿Cuál es la enseñanza de esta fábula?"], ["Something that seems like a mistake can still do good.", "Algo que parece un error puede terminar haciendo bien."], [["A squirrel buries acorns and forgets where they are.", "Una ardilla entierra bellotas y olvida dónde están.", "plot-summary"], ["Always do what your friends say.", "Siempre haz lo que dicen tus amigos.", "unsupported-lesson"], ["Deer like to rest in the shade.", "A los venados les gusta descansar a la sombra.", "too-narrow"]], ["In the spring, Pip thinks his work was wasted. Was it?", "En la primavera, Pipo cree que trabajó para nada. ¿Fue así?"], ["Young oak trees now stood in rows where the bare ground had been.", "Donde antes había tierra pelada, ahora crecían filas de robles jóvenes."]),
      Q("character", ["How does Pip feel in the spring?", "¿Cómo se siente Pipo en la primavera?"], ["Upset that he forgot so many acorns", "Mal por haber olvidado tantas bellotas"], [["Proud of all his hard work", "Orgulloso de todo su trabajo", "opposite-of-text"], ["Amazed by the new trees", "Asombrado por los árboles nuevos", "wrong-order"], ["Angry at Dot", "Enojado con Pinta", "not-in-text"]], ["Read what Pip says in the spring and how he says it.", "Lee lo que dice Pipo en la primavera y cómo lo dice."], ["“All that work, wasted,” he sighed.", "“Tanto trabajo para nada”, suspiró."]),
      Q("words", ["In the sentence “Pip looked around in wonder,” what does “wonder” mean?", "En la oración “Pipo miró a su alrededor, asombrado”, ¿qué significa “asombrado”?"], ["Feeling great surprise at something amazing", "Con gran sorpresa por algo increíble"], [["Feeling sad about wasted work", "Con tristeza por el trabajo perdido", "ignored-context"], ["Feeling bored", "Con aburrimiento", "opposite-meaning"], ["Feeling afraid", "Con miedo", "ignored-context"]], ["Pip has just learned that the trees came from his acorns. How would that make you feel?", "Pipo acaba de saber que los árboles salieron de sus bellotas. ¿Cómo te sentirías tú?"], ["Pip looked around in wonder.", "Pipo miró a su alrededor, asombrado."]),
    ],
  },
  {
    id: "snow-shovel",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Malik grabbed his shovel and crossed the street.", "Malik tomó su pala y cruzó la calle."],
    title: ["The Snow Shovel", "La pala de nieve"],
    en: [
      "School was closed because of the snow, and Malik had big plans. He was going to build the tallest snow fort on Maple Street.",
      "Before he could start, he saw his neighbor, Mrs. Ortiz, standing at her front door. She held a cane in one hand and looked at the deep snow covering her steps. Malik remembered that she walked to the corner store every morning for her newspaper.",
      "Malik grabbed his shovel and crossed the street. “I'll clear a path for you,” he said. The snow was heavy and wet. His arms ached, and his nose turned red from the cold. It took him almost an hour to finish her steps and the sidewalk.",
      "By then, his friends had already built a fort in the park. Malik was too tired to start his own. He sat on his porch, feeling a little disappointed.",
      "That afternoon, Mrs. Ortiz knocked on his door. She handed him a mug of hot chocolate and a plate of warm cinnamon cookies. “You gave me my morning walk back,” she said. Malik decided that was better than any snow fort.",
    ],
    es: [
      "No hubo clases por la nieve, y Malik tenía grandes planes. Iba a construir el fuerte de nieve más alto de la calle Arce.",
      "Antes de empezar, vio a su vecina, la señora Ortiz, parada en la puerta de su casa. Tenía un bastón en una mano y miraba la nieve profunda que cubría sus escalones. Malik recordó que ella caminaba todas las mañanas a la tienda de la esquina para comprar el periódico.",
      "Malik tomó su pala y cruzó la calle. “Yo le despejo el camino”, le dijo. La nieve estaba pesada y mojada. Al rato tenía los brazos adoloridos y la nariz roja por el frío. Tardó casi una hora en limpiar los escalones y la acera.",
      "Para entonces, sus amigos ya habían construido un fuerte en el parque. Malik estaba demasiado cansado para empezar el suyo. Se sentó en el porche, un poco desilusionado.",
      "Esa tarde, la señora Ortiz tocó a su puerta. Le dio una taza de chocolate caliente y un plato de galletas de canela recién horneadas. “Me devolviste mi paseo de cada mañana”, le dijo. Malik decidió que eso era mejor que cualquier fuerte de nieve.",
    ],
    qs: [
      Q("character", ["Why does Malik shovel Mrs. Ortiz's steps?", "¿Por qué Malik limpia los escalones de la señora Ortiz?"], ["He knows she needs a clear path for her morning walk.", "Sabe que ella necesita un camino limpio para su paseo de cada mañana."], [["He wants to earn money.", "Quiere ganar dinero.", "wrong-motive"], ["He wants the snow for his fort.", "Quiere la nieve para su fuerte.", "wrong-motive"], ["His friends tell him to.", "Sus amigos se lo piden.", "not-in-text"]], ["What does Malik remember when he sees Mrs. Ortiz?", "¿Qué recuerda Malik cuando ve a la señora Ortiz?"], ["Malik remembered that she walked to the corner store every morning for her newspaper.", "Malik recordó que ella caminaba todas las mañanas a la tienda de la esquina para comprar el periódico."]),
      Q("character", ["Which word best describes Malik?", "¿Qué palabra describe mejor a Malik?"], ["Helpful", "Servicial"], [["Lazy", "Perezoso", "opposite-trait"], ["Rude", "Grosero", "trait-not-shown"], ["Greedy", "Codicioso", "trait-not-shown"]], ["Malik gives up his plans. What does he do instead?", "Malik deja sus planes. ¿Qué hace en su lugar?"], ["“I'll clear a path for you,” he said.", "“Yo le despejo el camino”, le dijo."]),
      Q("sequence", ["What happened while Malik was shoveling?", "¿Qué pasó mientras Malik limpiaba la nieve?"], ["His friends built a fort in the park.", "Sus amigos construyeron un fuerte en el parque."], [["Mrs. Ortiz brought him hot chocolate.", "La señora Ortiz le llevó chocolate caliente.", "wrong-order"], ["Malik built the tallest fort on the street.", "Malik construyó el fuerte más alto de la calle.", "opposite-of-text"], ["Malik's mom called him inside.", "La mamá de Malik lo llamó para que entrara.", "not-in-text"]], ["Look at the words “By then.” What had his friends been doing?", "Fíjate en las palabras “Para entonces”. ¿Qué habían hecho sus amigos?"], ["By then, his friends had already built a fort in the park.", "Para entonces, sus amigos ya habían construido un fuerte en el parque."]),
      Q("theme", ["What is the theme of the story?", "¿Cuál es el tema del cuento?"], ["Helping others can bring a joy worth more than fun for yourself.", "Ayudar a otros puede dar una alegría que vale más que divertirse uno solo."], [["Malik shovels snow instead of building a fort.", "Malik limpia nieve en vez de construir un fuerte.", "plot-summary"], ["Snow forts are a waste of time.", "Los fuertes de nieve son una pérdida de tiempo.", "unsupported-lesson"], ["Hot chocolate tastes best on cold days.", "El chocolate caliente sabe mejor en días fríos.", "too-narrow"]], ["Read the last sentence. What does Malik decide?", "Lee la última oración. ¿Qué decide Malik?"], ["Malik decided that was better than any snow fort.", "Malik decidió que eso era mejor que cualquier fuerte de nieve."]),
      Q("words", ["In this story, what does “ached” mean?", "En este cuento, ¿qué significa “adoloridos”?"], ["Sore from hard work", "Que duelen por el esfuerzo"], [["Warm and strong", "Calientes y fuertes", "opposite-meaning"], ["Red from the cold", "Rojos por el frío", "wrong-detail"], ["Moving very fast", "Que se mueven muy rápido", "ignored-context"]], ["The snow was heavy, and he shoveled for almost an hour. How would your arms feel?", "La nieve pesaba y trabajó casi una hora. ¿Cómo sentirías los brazos?"], ["His arms ached, and his nose turned red from the cold.", "Al rato tenía los brazos adoloridos y la nariz roja por el frío."]),
    ],
  },
  {
    id: "new-school",
    kind: "fiction",
    band: 1,
    pov: "first",
    povEv: ["I was so busy that I did not notice a girl sitting down across from me.", "Estaba tan ocupada que no me di cuenta de que una niña se sentó frente a mí."],
    title: ["A Friend in My Sketchbook", "Una amiga en mi cuaderno"],
    en: [
      "My family moved from Seattle to San Antonio in March, right in the middle of third grade. On my first day at Oak Hill Elementary, I did not know a single person. At lunch, I sat at the end of a long table and opened my sketchbook so I would not have to look at anyone.",
      "I started drawing the cafeteria: the tall windows, the lunch line, a boy balancing three milk cartons. I was so busy that I did not notice a girl sitting down across from me.",
      "“Is that Marcus?” she asked, pointing at the boy with the milk cartons. “You got his hair exactly right.” Her name was Lupe. She told me she liked to draw too, but only horses.",
      "The next day, Lupe brought her own sketchbook, and we traded pages. I showed her how I draw faces, and she showed me how to draw a horse's legs so they do not look like sticks.",
      "Moving to a new school was still hard. But every day at lunch, I had a place to sit and someone to draw with.",
    ],
    es: [
      "Mi familia se mudó de Seattle a San Antonio en marzo, justo a mitad del tercer grado. En mi primer día en la escuela primaria Oak Hill, no conocía a nadie. En el almuerzo, me senté en la punta de una mesa larga y abrí mi cuaderno de dibujo para no tener que mirar a nadie.",
      "Empecé a dibujar la cafetería: las ventanas altas, la fila del almuerzo, un niño que equilibraba tres cartones de leche. Estaba tan ocupada que no me di cuenta de que una niña se sentó frente a mí.",
      "“¿Ese es Marcus?”, me preguntó, señalando al niño de los cartones de leche. “Le dibujaste el pelo igualito”. Se llamaba Lupe. Me contó que a ella también le gustaba dibujar, pero solo caballos.",
      "Al día siguiente, Lupe trajo su propio cuaderno de dibujo y nos intercambiamos páginas. Yo le enseñé cómo dibujo las caras y ella me enseñó a dibujar las patas de un caballo para que no parezcan palitos.",
      "Cambiarme de escuela seguía siendo difícil. Pero todos los días, en el almuerzo, tenía un lugar donde sentarme y alguien con quien dibujar.",
    ],
    qs: [
      Q("character", ["How does the narrator feel at lunch on the first day?", "¿Cómo se siente la narradora en el almuerzo de su primer día?"], ["Lonely and shy", "Sola y tímida"], [["Excited to meet everyone", "Emocionada por conocer a todos", "opposite-of-text"], ["Bored with drawing", "Aburrida de dibujar", "opposite-of-text"], ["Angry at Lupe", "Enojada con Lupe", "not-in-text"]], ["Why does the narrator open a sketchbook at lunch?", "¿Para qué abre su cuaderno de dibujo en el almuerzo?"], ["At lunch, I sat at the end of a long table and opened my sketchbook so I would not have to look at anyone.", "En el almuerzo, me senté en la punta de una mesa larga y abrí mi cuaderno de dibujo para no tener que mirar a nadie."]),
      Q("sequence", ["What did Lupe and the narrator do the day after they met?", "¿Qué hicieron Lupe y la narradora el día después de conocerse?"], ["They taught each other how to draw.", "Se enseñaron a dibujar una a la otra."], [["The narrator drew Marcus for the first time.", "La narradora dibujó a Marcus por primera vez.", "wrong-order"], ["The family moved to San Antonio.", "La familia se mudó a San Antonio.", "wrong-order"], ["Lupe moved to a different school.", "Lupe se cambió de escuela.", "not-in-text"]], ["Find the words “The next day.” What did the two of them do?", "Busca las palabras “Al día siguiente”. ¿Qué hicieron las dos?"], ["I showed her how I draw faces, and she showed me how to draw a horse's legs so they do not look like sticks.", "Yo le enseñé cómo dibujo las caras y ella me enseñó a dibujar las patas de un caballo para que no parezcan palitos."]),
      Q("details", ["What does Lupe think of the drawing of Marcus?", "¿Qué le parece a Lupe el dibujo de Marcus?"], ["She thinks it looks just like him.", "Le parece que se ve igual a él."], [["She thinks the hair is wrong.", "Cree que el pelo quedó mal.", "opposite-of-text"], ["She thinks horses are easier to draw.", "Cree que es más fácil dibujar caballos.", "not-in-text"], ["She thinks it is too small.", "Cree que es demasiado pequeño.", "not-in-text"]], ["Read what Lupe says when she first sees the drawing.", "Lee lo que dice Lupe cuando ve el dibujo por primera vez."], ["“You got his hair exactly right.”", "“Le dibujaste el pelo igualito”"]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Sharing what you love can help you make friends.", "Compartir lo que te gusta puede ayudarte a hacer amigos."], [["A family moves from Seattle to San Antonio.", "Una familia se muda de Seattle a San Antonio.", "plot-summary"], ["It is best to eat lunch alone.", "Es mejor almorzar sin compañía.", "unsupported-lesson"], ["Horses are hard to draw.", "Los caballos son difíciles de dibujar.", "too-narrow"]], ["What brings the narrator and Lupe together?", "¿Qué une a la narradora y a Lupe?"], ["She told me she liked to draw too, but only horses.", "Me contó que a ella también le gustaba dibujar, pero solo caballos."]),
      Q("words", ["In this story, what does “balancing” mean?", "En este cuento, ¿qué significa “equilibraba”?"], ["Holding steady so nothing falls", "Sostenía con cuidado para que nada se cayera"], [["Dropping on the floor", "Tiraba al piso", "opposite-meaning"], ["Counting carefully", "Contaba con cuidado", "ignored-context"], ["Checking how much money is left", "Hacía cuentas para no gastar más dinero del que tenía", "other-meaning"]], ["Picture a boy carrying three milk cartons at once. What does he have to do?", "Imagina a un niño que lleva tres cartones de leche a la vez. ¿Qué tiene que hacer?"], ["I started drawing the cafeteria: the tall windows, the lunch line, a boy balancing three milk cartons.", "Empecé a dibujar la cafetería: las ventanas altas, la fila del almuerzo, un niño que equilibraba tres cartones de leche."]),
    ],
  },
  {
    id: "goalie",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Sofia stood up.", "Sofía se levantó."],
    title: ["The Goalie", "La portera"],
    en: [
      "Sofia was the goalie for the Hornets, and the championship game was tied 1 to 1. With two minutes left, a player on the other team kicked the ball hard toward the corner of the net. Sofia dove, but the ball slipped past her fingertips.",
      "The other team cheered. Sofia lay in the grass with her face in her gloves. She was sure everyone was angry with her.",
      "Then she felt a hand on her shoulder. It was Jamal, the team captain. “One goal doesn't lose a game,” he said. “We still have two minutes. We need you.”",
      "Sofia stood up. For the rest of the game, she shouted directions to her teammates, telling them where to stand. When the other team rushed forward again, she caught the ball and threw it far down the field. Ana kicked it into the net just before the final whistle.",
      "The game ended in a tie. There was no trophy that day, but on the bus ride home, the whole team sang together. Sofia sang the loudest.",
    ],
    es: [
      "Sofía era la portera de los Avispones, y el partido de campeonato iba empatado 1 a 1. Faltando dos minutos, un jugador del otro equipo pateó el balón con fuerza hacia la esquina de la portería. Sofía se lanzó, pero el balón le pasó rozando la punta de los dedos.",
      "El otro equipo festejó. Sofía se quedó tirada en el pasto, con la cara entre los guantes. Estaba segura de que todos estaban enojados con ella.",
      "Entonces sintió una mano en el hombro. Era Jamal, el capitán del equipo. “Por un gol no se pierde un partido”, le dijo. “Todavía quedan dos minutos. Te necesitamos”.",
      "Sofía se levantó. Durante el resto del partido, les gritó indicaciones a sus compañeros para decirles dónde pararse. Cuando el otro equipo volvió a atacar, atrapó el balón y lo lanzó lejos, hacia el otro lado de la cancha. Ana lo metió en la portería justo antes del silbatazo final.",
      "El partido terminó empatado. Ese día no hubo trofeo, pero en el autobús de regreso, todo el equipo cantó junto. Sofía era la que cantaba más fuerte.",
    ],
    qs: [
      Q("character", ["How does Sofia feel right after the other team scores?", "¿Cómo se siente Sofía justo después del gol del otro equipo?"], ["Ashamed and sure she let the team down", "Avergonzada y segura de que le falló al equipo"], [["Proud of her dive", "Orgullosa de su salto", "opposite-of-text"], ["Happy that the game is almost over", "Feliz porque el partido casi termina", "not-in-text"], ["Angry at Jamal", "Enojada con Jamal", "not-in-text"]], ["Look at what Sofia does after the ball goes in and what she believes.", "Fíjate en lo que hace Sofía cuando entra el balón y en lo que cree."], ["She was sure everyone was angry with her.", "Estaba segura de que todos estaban enojados con ella."]),
      Q("character", ["What do Jamal's words show about him?", "¿Qué muestran las palabras de Jamal sobre él?"], ["He is a leader who supports his team.", "Es un líder que apoya a su equipo."], [["He is upset with Sofia.", "Está molesto con Sofía.", "opposite-of-text"], ["He thinks the game is already lost.", "Cree que el partido ya está perdido.", "opposite-of-text"], ["He wants to be the goalie.", "Quiere ser el portero.", "not-in-text"]], ["Read Jamal's words. Is he blaming Sofia or helping her?", "Lee las palabras de Jamal. ¿Culpa a Sofía o la ayuda?"], ["“One goal doesn't lose a game,” he said.", "“Por un gol no se pierde un partido”, le dijo."]),
      Q("sequence", ["What happened because Sofia caught the ball and threw it down the field?", "¿Qué pasó porque Sofía atrapó el balón y lo lanzó lejos?"], ["Ana was able to score and tie the game.", "Ana pudo meter un gol y empatar el partido."], [["Jamal put a hand on her shoulder.", "Jamal le puso la mano en el hombro.", "wrong-order"], ["The team won a trophy.", "El equipo ganó un trofeo.", "opposite-of-text"], ["The other team kicked the ball into the corner of the net.", "El otro equipo metió el balón en la esquina de la portería.", "wrong-order"]], ["Follow the ball after Sofia throws it. Who kicks it next?", "Sigue el balón después de que Sofía lo lanza. ¿Quién lo patea?"], ["Ana kicked it into the net just before the final whistle.", "Ana lo metió en la portería justo antes del silbatazo final."]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Teammates lift each other up after a mistake.", "Los compañeros de equipo se apoyan después de un error."], [["Sofia misses a save, and the game ends in a tie.", "Sofía no ataja un tiro y el partido termina empatado.", "plot-summary"], ["Winning a trophy is all that matters.", "Ganar un trofeo es lo único que importa.", "unsupported-lesson"], ["Goalies should wear gloves.", "Los porteros deben usar guantes.", "too-narrow"]], ["Think about what Jamal does and how the team acts on the bus.", "Piensa en lo que hace Jamal y en cómo actúa el equipo en el autobús."], ["There was no trophy that day, but on the bus ride home, the whole team sang together.", "Ese día no hubo trofeo, pero en el autobús de regreso, todo el equipo cantó junto."]),
      Q("details", ["What did Sofia do for the rest of the game?", "¿Qué hizo Sofía durante el resto del partido?"], ["She called out to her teammates where to stand.", "Les indicaba a gritos a sus compañeros dónde ponerse."], [["She lay in the grass with her face in her gloves.", "Se quedó en el pasto con la cara entre los guantes.", "wrong-detail"], ["She sat on the bench.", "Se sentó en la banca.", "not-in-text"], ["She kicked the winning goal.", "Metió el gol del triunfo.", "not-in-text"]], ["Find the sentence that begins “For the rest of the game.”", "Busca la oración que empieza con “Durante el resto del partido”."], ["For the rest of the game, she shouted directions to her teammates, telling them where to stand.", "Durante el resto del partido, les gritó indicaciones a sus compañeros para decirles dónde pararse."]),
    ],
  },
  {
    id: "kofi-drum",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Kofi pulled his balloon tighter and tapped again.", "Kofi estiró más el globo y volvió a tocar."],
    title: ["Kofi's Drum", "El tambor de Kofi"],
    en: [
      "In music class, Ms. Rivera gave each student an empty oatmeal can, a balloon, and a rubber band. “Today you will build a drum,” she said.",
      "Kofi cut the neck off his balloon and stretched it over the open end of the can. He snapped the rubber band around the edge to hold it in place. When he tapped the balloon, the drum made a soft, low thump.",
      "His friend Hana's drum sounded different. Her balloon was pulled so tight that her drum made a high, sharp tap. “Why is mine so low?” Kofi asked.",
      "Ms. Rivera pressed her finger gently on Kofi's drum. “Your balloon is loose,” she said. “When you hit a drum, the top shakes very fast. A loose top shakes more slowly and makes a low sound. A tight top shakes faster and makes a higher sound.”",
      "Kofi pulled his balloon tighter and tapped again. This time the sound was higher. Then he loosened it a little, and the sound dropped again. Now he could make two different notes, and he played a beat for the whole class.",
    ],
    es: [
      "En la clase de música, la maestra Rivera le dio a cada estudiante un bote vacío de avena, un globo y una banda elástica. “Hoy van a construir un tambor”, dijo.",
      "Kofi le cortó la boquilla al globo y lo estiró sobre la boca abierta del bote. Le puso la banda elástica alrededor del borde para sujetarlo. Cuando golpeó el globo, el tambor sonó con un golpe suave y grave.",
      "El tambor de su amiga Hana sonaba distinto. Su globo estaba tan estirado que hacía un sonido agudo y seco. “¿Por qué el mío suena tan grave?”, preguntó Kofi.",
      "La maestra Rivera apretó con cuidado el tambor de Kofi. “Tu globo está flojo”, le dijo. “Cuando golpeas un tambor, la parte de arriba tiembla muy rápido. Si está floja, tiembla más despacio y el sonido es grave. Si está tensa, tiembla más rápido y el sonido es más agudo”.",
      "Kofi estiró más el globo y volvió a tocar. Esta vez el sonido fue más agudo. Luego lo aflojó un poco y el sonido volvió a bajar. Ya podía hacer dos notas distintas, y tocó un ritmo para toda la clase.",
    ],
    qs: [
      Q("sequence", ["Why did Kofi's drum make a low sound at first?", "¿Por qué el tambor de Kofi sonaba grave al principio?"], ["His balloon was not stretched tight.", "Su globo no estaba bien estirado."], [["Hana's balloon was pulled tight.", "El globo de Hana estaba muy estirado.", "wrong-detail"], ["His drum was smaller than Hana's.", "Su tambor era más chico que el de Hana.", "not-in-text"], ["He tapped it too hard.", "Lo golpeó demasiado fuerte.", "not-in-text"]], ["What does Ms. Rivera notice when she presses on Kofi's drum?", "¿Qué nota la maestra Rivera cuando aprieta el tambor de Kofi?"], ["“Your balloon is loose,” she said.", "“Tu globo está flojo”, le dijo."]),
      Q("theme", ["What lesson does this story show?", "¿Qué lección muestra este cuento?"], ["Asking questions and trying things helps you learn how they work.", "Hacer preguntas y probar cosas te ayuda a aprender cómo funcionan."], [["Kofi builds a drum in music class.", "Kofi construye un tambor en la clase de música.", "plot-summary"], ["High notes are better than low notes.", "Las notas agudas son mejores que las graves.", "unsupported-lesson"], ["A balloon can cover the top of a can.", "Un globo puede tapar la boca de un bote.", "too-narrow"]], ["Kofi asks a question, then tests the answer. What does he end up able to do?", "Kofi hace una pregunta y luego pone a prueba la respuesta. ¿Qué logra hacer al final?"], ["Now he could make two different notes, and he played a beat for the whole class.", "Ya podía hacer dos notas distintas, y tocó un ritmo para toda la clase."]),
      Q("details", ["How did Kofi hold the balloon in place on the can?", "¿Cómo sujetó Kofi el globo sobre el bote?"], ["With a rubber band around the edge", "Con una banda elástica alrededor del borde"], [["By tying the neck of the balloon", "Amarrando la boquilla del globo", "opposite-of-text"], ["With tape across the top", "Con cinta adhesiva por encima", "not-in-text"], ["With glue inside the can", "Con pegamento dentro del bote", "not-in-text"]], ["Look at what Kofi does right after he stretches the balloon.", "Fíjate en lo que hace Kofi justo después de estirar el globo."], ["He snapped the rubber band around the edge to hold it in place.", "Le puso la banda elástica alrededor del borde para sujetarlo."]),
      Q("character", ["Which word best describes Kofi in this story?", "¿Qué palabra describe mejor a Kofi en este cuento?"], ["Curious", "Curioso"], [["Bored", "Aburrido", "opposite-trait"], ["Bossy", "Mandón", "trait-not-shown"], ["Careless", "Descuidado", "trait-not-shown"]], ["Kofi notices that his drum sounds different. What does he do about it?", "Kofi nota que su tambor suena distinto. ¿Qué hace al respecto?"], ["“Why is mine so low?” Kofi asked.", "“¿Por qué el mío suena tan grave?”, preguntó Kofi."]),
      Q("words", ["In this story, what does “loose” mean?", "En este cuento, ¿qué significa “flojo”?"], ["Not pulled tight", "Poco estirado, no tenso"], [["Pulled very tight", "Muy estirado", "opposite-meaning"], ["Free and running away, like an escaped dog", "Perezoso, que no quiere trabajar", "other-meaning"], ["Broken and torn", "Roto y rasgado", "ignored-context"]], ["Ms. Rivera compares a loose top with a tight top. What is the opposite of tight?", "La maestra compara una parte de arriba floja con una tensa. ¿Qué es lo contrario de tenso?"], ["A loose top shakes more slowly and makes a low sound.", "Si está floja, tiembla más despacio y el sonido es grave."]),
    ],
  },
];
