import { Q, type Passage } from "./types";

// Band 1 informational articles, grade 2–3 text band (draft: written for KaizenEDU, not yet reviewed by a teacher).
export const BAND1_INFO: Passage[] = [
  {
    id: "bees",
    kind: "info",
    band: 1,
    title: ["How Bees Make Honey", "Cómo hacen miel las abejas"],
    en: [
      "Honey is made by honeybees, and it takes a lot of teamwork. The bees that do this work are called worker bees. All worker bees are female.",
      "Collecting Nectar",
      "A worker bee flies from flower to flower. At each one, she uses her long, straw-like tongue to drink nectar, a sweet liquid inside the flower. She stores the nectar in a special part of her body called the honey stomach.",
      "Back at the Hive",
      "When her honey stomach is full, the bee flies home. She passes the nectar to younger bees inside the hive. They pass it from bee to bee and add substances from their bodies that start to change it into honey.",
      "Drying and Sealing",
      "The bees put the nectar into tiny six-sided cells made of wax. The nectar is still too watery, so the bees fan it with their wings to dry it out. When it is thick enough, they cover each cell with a lid of wax.",
      "Fast fact: In her whole life, one worker bee makes only about one-twelfth of a teaspoon of honey.",
    ],
    es: [
      "La miel la hacen las abejas melíferas, y se necesita mucho trabajo en equipo. Las abejas que hacen este trabajo se llaman obreras. Todas las obreras son hembras.",
      "La recolección del néctar",
      "Una abeja obrera vuela de flor en flor. En cada una, usa su lengua larga, parecida a un tubito, para beber néctar, un líquido dulce que hay dentro de la flor. Guarda el néctar en una parte especial de su cuerpo llamada estómago de la miel.",
      "De vuelta en la colmena",
      "Cuando tiene lleno el estómago de la miel, la abeja vuelve a casa. Les pasa el néctar a abejas más jóvenes dentro de la colmena. Ellas se lo pasan de una a otra y le agregan sustancias de su cuerpo que empiezan a convertirlo en miel.",
      "Secar y sellar",
      "Las abejas ponen el néctar en celdas diminutas de cera con seis lados. El néctar todavía tiene demasiada agua, así que las abejas lo abanican con las alas para secarlo. Cuando ya está espeso, tapan cada celda con una capa de cera.",
      "Dato curioso: En toda su vida, una abeja obrera produce apenas la doceava parte de una cucharadita de miel.",
    ],
    qs: [
      Q("features", ["Under which heading can you read about how bees dry the nectar?", "¿En qué subtítulo puedes leer cómo secan el néctar las abejas?"], ["Drying and Sealing", "Secar y sellar"], [["Back at the Hive", "De vuelta en la colmena", "wrong-section"], ["Collecting Nectar", "La recolección del néctar", "wrong-section"], ["Fast fact", "Dato curioso", "wrong-feature"]], ["Think about which step comes last, after the nectar is in the hive.", "Piensa en qué paso viene al final, cuando el néctar ya está en la colmena."], ["The nectar is still too watery, so the bees fan it with their wings to dry it out.", "El néctar todavía tiene demasiada agua, así que las abejas lo abanican con las alas para secarlo."]),
      Q("features", ["Why did the author add the “Fast fact” at the end?", "¿Para qué puso quien escribe el “Dato curioso” al final?"], ["To share a surprising number about bees", "Para compartir un dato sorprendente sobre las abejas"], [["To tell the steps in order", "Para contar los pasos en orden", "wrong-feature"], ["To explain the meaning of a hard word", "Para explicar el significado de una palabra difícil", "wrong-feature"], ["To name the next section", "Para nombrar la siguiente sección", "wrong-feature"]], ["Read the fast fact at the end. What does it add to the article?", "Lee el dato curioso del final. ¿Qué le agrega al artículo?"], ["Fast fact: In her whole life, one worker bee makes only about one-twelfth of a teaspoon of honey.", "Dato curioso: En toda su vida, una abeja obrera produce apenas la doceava parte de una cucharadita de miel."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Worker bees take several steps together to turn nectar into honey.", "Las obreras siguen varios pasos en equipo para convertir el néctar en miel."], [["Bees drink nectar with their long tongues.", "Las abejas beben néctar con su lengua larga.", "one-paragraph-only"], ["Insects are important to the world.", "Los insectos son importantes para el mundo.", "too-broad"], ["Honey is the healthiest food.", "La miel es el alimento más sano.", "not-in-text"]], ["The title and the headings together tell what the whole article explains.", "El título y los subtítulos juntos dicen qué explica todo el artículo."], ["Honey is made by honeybees, and it takes a lot of teamwork.", "La miel la hacen las abejas melíferas, y se necesita mucho trabajo en equipo."]),
      Q("sequence", ["What do the bees do right before they cover a cell with wax?", "¿Qué hacen las abejas justo antes de tapar una celda con cera?"], ["They fan the nectar with their wings until it is thick.", "Abanican el néctar con las alas hasta que se pone espeso."], [["They pass the nectar from bee to bee.", "Se pasan el néctar de una a otra.", "wrong-order"], ["They drink nectar from a flower.", "Beben néctar de una flor.", "wrong-order"], ["They carry the honey back to the flowers.", "Llevan la miel de vuelta a las flores.", "not-in-text"]], ["Look at the last step in the article. What has to happen to the nectar first?", "Mira el último paso del artículo. ¿Qué tiene que pasarle antes al néctar?"], ["When it is thick enough, they cover each cell with a lid of wax.", "Cuando ya está espeso, tapan cada celda con una capa de cera."]),
      Q("words", ["In this article, what does “nectar” mean?", "En este artículo, ¿qué significa “néctar”?"], ["Sweet juice that bees drink from flowers", "Jugo dulce que las abejas beben de las flores"], [["Finished honey", "La miel ya terminada", "ignored-context"], ["The wax lid on a cell", "La tapa de cera de una celda", "wrong-detail"], ["A part of the bee's body", "Una parte del cuerpo de la abeja", "wrong-detail"]], ["The writer tells what nectar is right after the word, after a comma.", "Quien escribe dice qué es el néctar justo después de la palabra, tras una coma."], ["At each one, she uses her long, straw-like tongue to drink nectar, a sweet liquid inside the flower.", "En cada una, usa su lengua larga, parecida a un tubito, para beber néctar, un líquido dulce que hay dentro de la flor."]),
    ],
  },
  {
    id: "sea-turtles",
    kind: "info",
    band: 1,
    title: ["A Sea Turtle's Nest", "El nido de una tortuga marina"],
    en: [
      "Sea turtles spend almost their whole lives in the ocean. But when it is time to lay eggs, a female sea turtle must come onto land.",
      "Coming Ashore",
      "On a summer night, the female swims to a sandy beach, often near the beach where she hatched long ago. She crawls slowly up the sand, past the line where the waves stop.",
      "Digging the Nest",
      "With her back flippers, she digs a deep hole. She lays about 100 eggs, each about the size of a golf ball. Then she covers the nest with sand and returns to the sea. She does not stay to guard her eggs.",
      "The Race to the Sea",
      "About two months later, the baby turtles, called hatchlings, break out of their shells. Usually at night, they dig up through the sand together. Then they hurry toward the brightest part of the sky, which on a dark beach is over the water.",
      "How you can help: Bright lights from houses and streets can lead hatchlings the wrong way. Families who live near nesting beaches can turn off outdoor lights at night.",
    ],
    es: [
      "Las tortugas marinas pasan casi toda su vida en el océano. Pero cuando llega el momento de poner huevos, la hembra tiene que salir a tierra.",
      "La llegada a la playa",
      "Una noche de verano, la hembra nada hasta una playa de arena, muchas veces cerca de la playa donde ella nació hace mucho tiempo. Se arrastra despacio por la arena, más allá de donde llegan las olas.",
      "Cavar el nido",
      "Con las aletas de atrás, cava un hoyo profundo. Pone unos 100 huevos, cada uno del tamaño de una pelota de golf. Luego tapa el nido con arena y regresa al mar. No se queda a cuidar sus huevos.",
      "La carrera hacia el mar",
      "Unos dos meses después, las tortuguitas, llamadas crías, rompen el cascarón. Casi siempre de noche, escarban juntas hacia la superficie. Luego corren hacia la parte más brillante del cielo, que en una playa oscura está sobre el agua.",
      "Cómo puedes ayudar: Las luces brillantes de casas y calles pueden hacer que las crías se vayan por el camino equivocado. Las familias que viven cerca de las playas donde anidan las tortugas pueden apagar las luces de afuera por la noche.",
    ],
    qs: [
      Q("features", ["Under which heading would you find out how many eggs a sea turtle lays?", "¿En qué subtítulo encontrarías cuántos huevos pone una tortuga marina?"], ["Digging the Nest", "Cavar el nido"], [["Coming Ashore", "La llegada a la playa", "wrong-section"], ["The Race to the Sea", "La carrera hacia el mar", "wrong-section"], ["How you can help", "Cómo puedes ayudar", "wrong-feature"]], ["Think about where the turtle puts her eggs.", "Piensa en dónde pone la tortuga sus huevos."], ["She lays about 100 eggs, each about the size of a golf ball.", "Pone unos 100 huevos, cada uno del tamaño de una pelota de golf."]),
      Q("mainidea", ["What is the main idea of the whole article?", "¿Cuál es la idea principal de todo el artículo?"], ["A mother sea turtle comes ashore to lay eggs, and the babies find their way to the sea.", "La tortuga madre sale a la playa a poner huevos, y las crías encuentran el camino al mar."], [["Sea turtle eggs are about the size of golf balls.", "Los huevos de tortuga marina son del tamaño de una pelota de golf.", "one-paragraph-only"], ["Many animals live in the ocean.", "Muchos animales viven en el océano.", "too-broad"], ["Sea turtles are the fastest swimmers in the sea.", "Las tortugas marinas son las que nadan más rápido en el mar.", "not-in-text"]], ["Read the title and all the headings. What do they tell about together?", "Lee el título y todos los subtítulos. ¿De qué hablan juntos?"], ["But when it is time to lay eggs, a female sea turtle must come onto land.", "Pero cuando llega el momento de poner huevos, la hembra tiene que salir a tierra."]),
      Q("mainidea", ["Which detail supports the idea that hatchlings can be led the wrong way?", "¿Qué detalle apoya la idea de que las crías se pueden desviar del camino?"], ["Bright lights from houses can confuse them.", "Las luces brillantes de las casas pueden confundirlas."], [["The mother covers the nest with sand.", "La madre tapa el nido con arena.", "supports-other-point"], ["The eggs hatch about two months later.", "Los huevos se abren unos dos meses después.", "supports-other-point"], ["The mother feeds the hatchlings.", "La madre alimenta a las crías.", "opposite-of-text"]], ["Look in the part that tells how people can help.", "Busca en la parte que dice cómo puede ayudar la gente."], ["Bright lights from houses and streets can lead hatchlings the wrong way.", "Las luces brillantes de casas y calles pueden hacer que las crías se vayan por el camino equivocado."]),
      Q("sequence", ["What do the hatchlings do right after they dig up through the sand?", "¿Qué hacen las crías justo después de salir de la arena?"], ["They head for the water, where the sky is brightest.", "Van hacia el agua, donde el cielo brilla más."], [["They break out of their shells.", "Rompen el cascarón.", "wrong-order"], ["They dig a deep hole for eggs.", "Cavan un hoyo profundo para los huevos.", "wrong-character"], ["They wait for their mother to come back.", "Esperan a que regrese su madre.", "not-in-text"]], ["Find the sentence that starts with “Then” in the last section.", "Busca la oración que empieza con “Luego” en la última sección."], ["Then they hurry toward the brightest part of the sky, which on a dark beach is over the water.", "Luego corren hacia la parte más brillante del cielo, que en una playa oscura está sobre el agua."]),
      Q("details", ["Does the mother turtle stay with her eggs?", "¿La tortuga madre se queda con sus huevos?"], ["No, she goes back to the sea.", "No, regresa al mar."], [["Yes, she guards them for two months.", "Sí, los cuida durante dos meses.", "opposite-of-text"], ["Yes, she stays until they hatch.", "Sí, se queda hasta que nacen.", "opposite-of-text"], ["No, she goes to find food on the beach.", "No, va a buscar comida en la playa.", "not-in-text"]], ["Read the end of the section about the nest.", "Lee el final de la sección sobre el nido."], ["She does not stay to guard her eggs.", "No se queda a cuidar sus huevos."]),
    ],
  },
  {
    id: "butter",
    kind: "info",
    band: 1,
    title: ["Shake Up Some Butter", "Agita y haz mantequilla"],
    en: [
      "Butter is made from cream, the thick, fatty part of milk. For hundreds of years, people made butter by stirring or shaking cream for a long time. You can make a small batch in your kitchen with just a jar and your own two arms.",
      "What You Need",
      "A clean jar with a tight lid, one cup of heavy cream, a pinch of salt, and a grown-up helper.",
      "Steps",
      "1. Pour the cream into the jar until it is about half full. Close the lid tightly.\n2. Shake the jar hard. After about five minutes, the cream will turn into whipped cream, and you will not hear it slosh anymore.\n3. Keep shaking. Soon you will hear a thump. A yellow lump of butter has formed, with a thin, watery liquid around it.\n4. Pour off the liquid, which is called buttermilk. Rinse the butter in cold water and stir in the salt.",
      "Why It Works",
      "Cream is full of tiny drops of fat. Shaking makes the drops bump into each other and stick together. After enough shaking, the fat forms one big lump: butter.",
    ],
    es: [
      "La mantequilla se hace con crema, la parte espesa y grasosa de la leche. Durante cientos de años, la gente hizo mantequilla batiendo o agitando la crema por mucho tiempo. Tú puedes hacer un poco en tu cocina con solo un frasco y tus dos brazos.",
      "Qué necesitas",
      "Un frasco limpio con una tapa que cierre bien, una taza de crema para batir, una pizca de sal y la ayuda de un adulto.",
      "Pasos",
      "1. Vierte la crema en el frasco hasta que esté más o menos a la mitad. Cierra bien la tapa.\n2. Agita el frasco con fuerza. Después de unos cinco minutos, la crema se convertirá en crema batida y ya no la oirás chapotear.\n3. Sigue agitando. Pronto oirás un golpe seco. Se formó una bola amarilla de mantequilla, rodeada de un líquido delgado y aguado.\n4. Saca el líquido, que se llama suero de leche. Enjuaga la mantequilla con agua fría y mézclale la sal.",
      "Por qué funciona",
      "La crema está llena de gotitas de grasa. Al agitarla, las gotitas chocan entre sí y se pegan. Después de agitar lo suficiente, la grasa forma una sola bola: la mantequilla.",
    ],
    qs: [
      Q("features", ["Why does the author put the steps in a numbered list?", "¿Por qué quien escribe pone los pasos en una lista numerada?"], ["So readers can follow the steps in the right order", "Para que se sigan los pasos en el orden correcto"], [["To explain why the cream turns into butter", "Para explicar por qué la crema se vuelve mantequilla", "wrong-feature"], ["To tell how long people have made butter", "Para contar desde cuándo se hace mantequilla", "wrong-feature"], ["To list words and their meanings", "Para dar una lista de palabras y sus significados", "wrong-feature"]], ["What would happen if you shook the jar before you poured in the cream?", "¿Qué pasaría si agitaras el frasco antes de echar la crema?"], ["1. Pour the cream into the jar until it is about half full.", "1. Vierte la crema en el frasco hasta que esté más o menos a la mitad."]),
      Q("features", ["Under which heading does the author explain why shaking turns cream into butter?", "¿En qué subtítulo explica quien escribe por qué al agitar la crema se hace mantequilla?"], ["Why It Works", "Por qué funciona"], [["Steps", "Pasos", "wrong-section"], ["What You Need", "Qué necesitas", "wrong-section"], ["Shake Up Some Butter", "Agita y haz mantequilla", "wrong-feature"]], ["Look for the section that gives the reason, not the directions.", "Busca la sección que da la razón, no las instrucciones."], ["Shaking makes the drops bump into each other and stick together.", "Al agitarla, las gotitas chocan entre sí y se pegan."]),
      Q("mainidea", ["What is this article mostly about?", "¿De qué trata principalmente este artículo?"], ["How to make butter by shaking cream, and why it works", "Cómo hacer mantequilla agitando crema, y por qué funciona"], [["What you need to make butter", "Qué se necesita para hacer mantequilla", "one-paragraph-only"], ["Foods that come from cows", "Alimentos que vienen de las vacas", "too-broad"], ["Why butter is better than oil", "Por qué la mantequilla es mejor que el aceite", "not-in-text"]], ["Look at all three headings, not just one.", "Mira los tres subtítulos, no solo uno."], ["You can make a small batch in your kitchen with just a jar and your own two arms.", "Tú puedes hacer un poco en tu cocina con solo un frasco y tus dos brazos."]),
      Q("sequence", ["What happens right after the cream turns into whipped cream?", "¿Qué pasa justo después de que la crema se vuelve crema batida?"], ["You keep shaking until a lump of butter forms.", "Sigues agitando hasta que se forma una bola de mantequilla."], [["You rinse the butter in cold water.", "Enjuagas la mantequilla con agua fría.", "wrong-order"], ["You pour the cream into the jar.", "Echas la crema en el frasco.", "wrong-order"], ["You put the jar in the oven.", "Metes el frasco al horno.", "not-in-text"]], ["Read the step that comes after the one about whipped cream.", "Lee el paso que sigue al de la crema batida."], ["3. Keep shaking. Soon you will hear a thump.", "3. Sigue agitando. Pronto oirás un golpe seco."]),
      Q("words", ["In this article, what is “buttermilk”?", "En este artículo, ¿qué es el “suero de leche”?"], ["The watery liquid left after the butter forms", "El líquido aguado que queda al formarse la mantequilla"], [["The heavy cream you start with", "La crema espesa con la que empiezas", "wrong-detail"], ["Melted butter", "Mantequilla derretida", "ignored-context"], ["The cold water used for rinsing", "El agua fría para enjuagar", "wrong-detail"]], ["Find the sentence where the writer names the liquid.", "Busca la oración donde quien escribe le pone nombre al líquido."], ["4. Pour off the liquid, which is called buttermilk.", "4. Saca el líquido, que se llama suero de leche."]),
    ],
  },
  {
    id: "moon",
    kind: "info",
    band: 1,
    title: ["Why the Moon Changes Shape", "¿Por qué cambia de forma la Luna?"],
    en: [
      "Some nights the Moon looks like a round, glowing ball. Other nights it is a thin curve, and some nights you cannot see it at all. The Moon is not really changing shape. What changes is how much of its bright side we can see.",
      "Borrowed Light",
      "The Moon does not make its own light. Sunlight shines on it, and the Moon reflects that light, the way a mirror does. At every moment, the Sun lights up half of the Moon. The other half is dark.",
      "A Trip Around Earth",
      "The Moon travels around Earth about once a month. As it moves, we see different amounts of its sunlit half. When the lit side faces away from us, we see almost nothing. This is called a new moon. When the whole lit side faces us, we see a full moon.",
      "Growing and Shrinking",
      "After a new moon, the bright part grows a little each night. Astronomers say the Moon is waxing. After a full moon, the bright part shrinks, and the Moon is waning. The whole pattern repeats about every 29 and a half days.",
    ],
    es: [
      "Algunas noches la Luna parece una pelota redonda y brillante. Otras noches es una curva delgada, y algunas noches no se ve. En realidad, la Luna no cambia de forma. Lo que cambia es cuánto vemos de su lado iluminado.",
      "Luz prestada",
      "La Luna no tiene luz propia. La luz del Sol le llega y la Luna la refleja, como lo hace un espejo. En todo momento, el Sol ilumina la mitad de la Luna. La otra mitad está oscura.",
      "Un viaje alrededor de la Tierra",
      "La Luna le da la vuelta a la Tierra más o menos una vez al mes. Mientras se mueve, vemos partes distintas de su mitad iluminada. Cuando el lado iluminado no mira hacia nosotros, casi no vemos nada. A esto se le llama luna nueva. Cuando todo el lado iluminado mira hacia nosotros, vemos la luna llena.",
      "Crecer y menguar",
      "Después de la luna nueva, la parte brillante crece un poco cada noche. Los astrónomos dicen que la Luna está en fase creciente. Después de la luna llena, la parte brillante se achica, y la Luna está en fase menguante. Todo el ciclo se repite más o menos cada 29 días y medio.",
    ],
    qs: [
      Q("details", ["Where does the Moon's light come from?", "¿De dónde viene la luz de la Luna?"], ["It is sunlight bouncing off the Moon.", "Es luz del Sol que rebota en la Luna."], [["The Moon makes its own light.", "La Luna produce su propia luz.", "opposite-of-text"], ["It comes from stars behind the Moon.", "Viene de estrellas detrás de la Luna.", "not-in-text"], ["It comes from city lights on Earth.", "Viene de las luces de las ciudades de la Tierra.", "not-in-text"]], ["Read the section about borrowed light.", "Lee la sección sobre la luz prestada."], ["Sunlight shines on it, and the Moon reflects that light, the way a mirror does.", "La luz del Sol le llega y la Luna la refleja, como lo hace un espejo."]),
      Q("sequence", ["Why can we not see the Moon during a new moon?", "¿Por qué no vemos la Luna cuando hay luna nueva?"], ["Its lit side is turned away from Earth.", "Su lado iluminado no mira hacia la Tierra."], [["The Moon is waning.", "La Luna está menguante.", "wrong-detail"], ["The Moon stops reflecting light.", "La Luna deja de reflejar la luz.", "opposite-of-text"], ["Clouds always cover it.", "Siempre la tapan las nubes.", "not-in-text"]], ["Look at what the article says about which way the lit side is facing.", "Fíjate en lo que dice el artículo sobre hacia dónde mira el lado iluminado."], ["When the lit side faces away from us, we see almost nothing.", "Cuando el lado iluminado no mira hacia nosotros, casi no vemos nada."]),
      Q("words", ["In this article, what does “waxing” mean?", "En este artículo, ¿qué significa “creciente”?"], ["Showing a bigger bright part each night", "Que muestra cada noche una parte brillante más grande"], [["Shrinking a little each night", "Que se achica un poco cada noche", "opposite-meaning"], ["Rubbing wax on something to make it shiny", "Una subida del agua de un río", "other-meaning"], ["Completely dark", "Totalmente oscura", "ignored-context"]], ["Read the sentence before the word. What is happening to the bright part?", "Lee la oración antes de la palabra. ¿Qué le pasa a la parte brillante?"], ["After a new moon, the bright part grows a little each night.", "Después de la luna nueva, la parte brillante crece un poco cada noche."]),
      Q("features", ["What does the heading “A Trip Around Earth” tell you about that section?", "¿Qué te dice el subtítulo “Un viaje alrededor de la Tierra” sobre esa sección?"], ["It explains how the Moon moves around Earth.", "Que explica cómo se mueve la Luna alrededor de la Tierra."], [["It tells how sunlight reaches the Moon.", "Que cuenta cómo llega la luz del Sol a la Luna.", "wrong-section"], ["It explains how astronauts travel to the Moon.", "Que explica cómo viajan los astronautas a la Luna.", "not-in-text"], ["It tells how long one day lasts.", "Que dice cuánto dura un día.", "not-in-text"]], ["A heading names what its section is about. Read the section under it.", "Un subtítulo dice de qué trata su sección. Lee la sección que está debajo."], ["The Moon travels around Earth about once a month.", "La Luna le da la vuelta a la Tierra más o menos una vez al mes."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["The Moon seems to change shape because we see different amounts of its sunlit half.", "La Luna parece cambiar de forma porque vemos partes distintas de su mitad iluminada."], [["The Moon does not make its own light.", "La Luna no tiene luz propia.", "one-paragraph-only"], ["The night sky is full of interesting things.", "El cielo nocturno está lleno de cosas interesantes.", "too-broad"], ["The Moon gets smaller every year.", "La Luna se hace más pequeña cada año.", "not-in-text"]], ["The first paragraph sets up the big idea. The rest explains it.", "El primer párrafo presenta la idea principal. El resto la explica."], ["What changes is how much of its bright side we can see.", "Lo que cambia es cuánto vemos de su lado iluminado."]),
    ],
  },
  {
    id: "monarchs",
    kind: "info",
    band: 1,
    title: ["The Monarch's Long Trip", "El largo viaje de la mariposa monarca"],
    en: [
      "Every fall, millions of monarch butterflies in eastern North America do something amazing. They fly south to the mountains of central Mexico. Some of them travel as far as 3,000 miles.",
      "Winter in the Forest",
      "In Mexico, the monarchs gather in forests of tall fir trees. So many butterflies cling to the branches that the trees look orange. The cool mountain air helps them rest and save energy until spring.",
      "Heading North",
      "In early spring, the monarchs fly north. Along the way, the females lay eggs on milkweed plants. The caterpillars that hatch eat only milkweed leaves. It takes several generations of butterflies to make it all the way back north.",
      "A Longer Life",
      "Most monarchs live only two to six weeks. But the butterflies that make the trip south can live about eight months. Their long lives give them time to fly to Mexico and start the trip back.",
      "Glossary",
      "generation: parents are one generation, and their young are the next.\nmilkweed: a wild plant with milky juice in its leaves and stems.",
    ],
    es: [
      "Cada otoño, millones de mariposas monarca del este de América del Norte hacen algo asombroso. Vuelan hacia el sur, hasta las montañas del centro de México. Algunas recorren hasta 4800 kilómetros.",
      "El invierno en el bosque",
      "En México, las monarcas se juntan en bosques de oyameles, unos abetos muy altos. Hay tantas mariposas colgadas de las ramas que los árboles se ven anaranjados. El aire fresco de la montaña las ayuda a descansar y a ahorrar energía hasta la primavera.",
      "Rumbo al norte",
      "A principios de la primavera, las monarcas vuelan hacia el norte. En el camino, las hembras ponen huevos en plantas de algodoncillo. Las orugas que nacen solo comen hojas de algodoncillo. Se necesitan varias generaciones de mariposas para llegar de nuevo hasta el norte.",
      "Una vida más larga",
      "La mayoría de las monarcas vive solo de dos a seis semanas. Pero las que hacen el viaje al sur pueden vivir unos ocho meses. Su larga vida les da tiempo de volar hasta México y empezar el regreso.",
      "Glosario",
      "generación: los padres son una generación y sus crías son la siguiente.\nalgodoncillo: planta silvestre con un jugo lechoso en las hojas y los tallos.",
    ],
    qs: [
      Q("features", ["Where in the article can you find what “milkweed” means?", "¿En qué parte del artículo puedes encontrar qué significa “algodoncillo”?"], ["In the glossary", "En el glosario"], [["In the section “A Longer Life”", "En la sección “Una vida más larga”", "wrong-section"], ["In the first paragraph", "En el primer párrafo", "wrong-section"], ["In the title", "En el título", "wrong-feature"]], ["Some articles end with a special list of words and their meanings.", "Algunos artículos terminan con una lista especial de palabras y sus significados."], ["milkweed: a wild plant with milky juice in its leaves and stems.", "algodoncillo: planta silvestre con un jugo lechoso en las hojas y los tallos."]),
      Q("features", ["Under which heading can you learn how long monarchs live?", "¿En qué subtítulo puedes saber cuánto tiempo viven las monarcas?"], ["A Longer Life", "Una vida más larga"], [["Heading North", "Rumbo al norte", "wrong-section"], ["Winter in the Forest", "El invierno en el bosque", "wrong-section"], ["Glossary", "Glosario", "wrong-feature"]], ["Think about which heading is about how long something lasts.", "Piensa en qué subtítulo habla de cuánto dura algo."], ["Most monarchs live only two to six weeks.", "La mayoría de las monarcas vive solo de dos a seis semanas."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Eastern monarchs make an amazing trip to Mexico and back each year.", "Las monarcas del este hacen cada año un viaje asombroso a México y de regreso."], [["Caterpillars eat only milkweed leaves.", "Las orugas solo comen hojas de algodoncillo.", "one-paragraph-only"], ["Butterflies are beautiful insects.", "Las mariposas son insectos hermosos.", "too-broad"], ["Monarchs are disappearing from Mexico.", "Las monarcas están desapareciendo de México.", "outside-knowledge"]], ["What do all the sections have in common?", "¿Qué tienen en común todas las secciones?"], ["Every fall, millions of monarch butterflies in eastern North America do something amazing.", "Cada otoño, millones de mariposas monarca del este de América del Norte hacen algo asombroso."]),
      Q("mainidea", ["Which detail supports the idea that the monarchs that fly south are special?", "¿Qué detalle apoya la idea de que las monarcas que vuelan al sur son especiales?"], ["They live about eight months instead of a few weeks.", "Viven unos ocho meses y no solo unas semanas."], [["Females lay eggs on milkweed.", "Las hembras ponen huevos en el algodoncillo.", "supports-other-point"], ["The trees look orange.", "Los árboles se ven anaranjados.", "supports-other-point"], ["They fly faster than birds.", "Vuelan más rápido que los pájaros.", "not-in-text"]], ["Compare the two lifespans in the section about how long monarchs live.", "Compara las dos duraciones de vida en la sección sobre cuánto viven las monarcas."], ["But the butterflies that make the trip south can live about eight months.", "Pero las que hacen el viaje al sur pueden vivir unos ocho meses."]),
      Q("details", ["What do monarch caterpillars eat?", "¿Qué comen las orugas de la monarca?"], ["Only the leaves of milkweed plants", "Nada más que hojas de algodoncillo"], [["Fir tree needles", "Hojas de oyamel", "wrong-detail"], ["Nectar from many flowers", "Néctar de muchas flores", "not-in-text"], ["Small insects", "Insectos pequeños", "not-in-text"]], ["Read the section about the trip north.", "Lee la sección sobre el viaje al norte."], ["The caterpillars that hatch eat only milkweed leaves.", "Las orugas que nacen solo comen hojas de algodoncillo."]),
    ],
  },
  {
    id: "seeds",
    kind: "info",
    band: 1,
    title: ["From Seed to Sprout", "De semilla a brote"],
    en: [
      "A seed may look like a tiny stone, but it is alive. Inside each seed is a baby plant and a supply of food. The seed waits, sometimes for months, until conditions are right for it to start growing. This is called sprouting.",
      "What a Seed Needs",
      "To sprout, a seed needs water, air, and the right amount of warmth. Most seeds do not need light to sprout, which is why they can start growing underground.",
      "The First Root",
      "First, the seed soaks up water and swells. Its hard outer coat splits open. A root pushes out and grows down into the soil. The root holds the plant in place and drinks in water.",
      "Up Toward the Light",
      "Next, a shoot grows up toward the surface. When it breaks through the soil, its first leaves open. Now the young plant can use sunlight to make its own food. It no longer needs the food that was stored in the seed.",
    ],
    es: [
      "Una semilla puede parecer una piedrita, pero está viva. Dentro de cada semilla hay una plantita bebé y una reserva de alimento. La semilla espera, a veces durante meses, hasta que las condiciones sean las adecuadas para empezar a crecer. A esto se le llama germinar.",
      "Lo que necesita una semilla",
      "Para germinar, una semilla necesita agua, aire y la temperatura adecuada. La mayoría de las semillas no necesita luz para germinar; por eso pueden empezar a crecer bajo la tierra.",
      "La primera raíz",
      "Primero, la semilla absorbe agua y se hincha. Su cubierta dura se abre. Una raíz sale y crece hacia abajo, dentro de la tierra. La raíz sostiene a la planta en su lugar y absorbe agua.",
      "Hacia la luz",
      "Después, un tallo crece hacia la superficie. Cuando sale de la tierra, se abren sus primeras hojas. Ahora la planta joven puede usar la luz del sol para fabricar su propio alimento. Ya no necesita el alimento que estaba guardado en la semilla.",
    ],
    qs: [
      Q("sequence", ["What happens right after a seed's hard coat splits open?", "¿Qué pasa justo después de que se abre la cubierta dura de la semilla?"], ["A root comes out and grows into the soil.", "Sale una raíz que crece dentro de la tierra."], [["The seed soaks up water.", "La semilla absorbe agua.", "wrong-order"], ["The first leaves open.", "Se abren las primeras hojas.", "wrong-order"], ["A flower blooms.", "Se abre una flor.", "not-in-text"]], ["Find the section about the first root and read the steps in order.", "Busca la sección sobre la primera raíz y lee los pasos en orden."], ["A root pushes out and grows down into the soil.", "Una raíz sale y crece hacia abajo, dentro de la tierra."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["A seed sprouts in steps once it gets what it needs.", "Una semilla germina paso a paso cuando recibe lo que necesita."], [["Roots hold a plant in place.", "Las raíces sostienen a la planta en su lugar.", "one-paragraph-only"], ["Plants are living things.", "Las plantas son seres vivos.", "too-broad"], ["Gardens need a lot of sunlight.", "Los huertos necesitan mucho sol.", "not-in-text"]], ["Look at the order of the headings from top to bottom.", "Fíjate en el orden de los subtítulos, de arriba abajo."], ["The seed waits, sometimes for months, until conditions are right for it to start growing.", "La semilla espera, a veces durante meses, hasta que las condiciones sean las adecuadas para empezar a crecer."]),
      Q("features", ["What does the heading “What a Seed Needs” help you find?", "¿Qué te ayuda a encontrar el subtítulo “Lo que necesita una semilla”?"], ["The things a seed must have before it can sprout", "Lo que una semilla debe tener para poder germinar"], [["How the leaves make food", "Cómo fabrican alimento las hojas", "wrong-section"], ["How deep to plant a seed", "A qué profundidad sembrar una semilla", "not-in-text"], ["Which seeds taste best", "Qué semillas saben mejor", "not-in-text"]], ["Read the two sentences under that heading.", "Lee las dos oraciones que están debajo de ese subtítulo."], ["To sprout, a seed needs water, air, and the right amount of warmth.", "Para germinar, una semilla necesita agua, aire y la temperatura adecuada."]),
      Q("words", ["In this article, what does “sprouting” mean?", "En este artículo, ¿qué significa “germinar”?"], ["Starting to grow out of the seed", "Empezar a crecer y salir de la semilla"], [["Planting a seed in a garden", "Sembrar una semilla en un huerto", "ignored-context"], ["Drying out in the sun", "Secarse al sol", "opposite-meaning"], ["Making seeds for next year", "Producir semillas para el año siguiente", "ignored-context"]], ["The sentence before tells what the seed is waiting to do.", "La oración anterior dice qué está esperando hacer la semilla."], ["This is called sprouting.", "A esto se le llama germinar."]),
      Q("details", ["Why can most seeds start growing underground?", "¿Por qué la mayoría de las semillas puede empezar a crecer bajo la tierra?"], ["Sprouting does not require light.", "Para germinar no hace falta luz."], [["They need light to sprout.", "Necesitan luz para germinar.", "opposite-of-text"], ["The soil feeds them right away.", "La tierra las alimenta enseguida.", "not-in-text"], ["Their roots grow before they are planted.", "Sus raíces crecen antes de sembrarlas.", "not-in-text"]], ["Read the section about what a seed needs.", "Lee la sección sobre lo que necesita una semilla."], ["Most seeds do not need light to sprout, which is why they can start growing underground.", "La mayoría de las semillas no necesita luz para germinar; por eso pueden empezar a crecer bajo la tierra."]),
    ],
  },
  {
    id: "basketball",
    kind: "info",
    band: 1,
    title: ["How Basketball Began", "Cómo empezó el baloncesto"],
    en: [
      "In the winter of 1891, a teacher named James Naismith had a problem. He taught at a school in Springfield, Massachusetts, where young men trained to become coaches and leaders. It was too cold to play outside, and his students were bored with indoor exercises. His boss gave him two weeks to invent a new indoor game.",
      "Naismith wanted a game that was active but safe for a small gym. He decided that players would score by tossing a ball into a goal high above their heads. He nailed two peach baskets to the railing of a balcony, ten feet above the floor.",
      "The first game was not very exciting. It ended with a score of 1 to 0. Every time someone made a basket, a person had to climb up and take the ball out. Still, the students loved the new game, and they taught it to others.",
      "Timeline",
      "1891: James Naismith invents basketball.\n1892: His 13 rules for the game are printed in the school newspaper.\n1893: Students at Smith College, a college for women, play their first game.\n1936: Basketball becomes an Olympic sport.",
    ],
    es: [
      "En el invierno de 1891, un maestro llamado James Naismith tenía un problema. Trabajaba en una escuela de Springfield, Massachusetts, donde los jóvenes se preparaban para ser entrenadores y líderes. Hacía demasiado frío para jugar afuera, y sus alumnos estaban aburridos de los ejercicios bajo techo. Su jefe le dio dos semanas para inventar un juego nuevo que se pudiera jugar adentro.",
      "Naismith quería un juego activo, pero seguro para un gimnasio pequeño. Decidió que los jugadores anotarían lanzando un balón a una meta alta, por encima de sus cabezas. Clavó dos canastas de duraznos en la baranda de un balcón, a unos tres metros del suelo.",
      "El primer partido no fue muy emocionante. Terminó 1 a 0. Cada vez que alguien encestaba, una persona tenía que subir a sacar el balón. Aun así, a los estudiantes les encantó el juego nuevo y se lo enseñaron a otros.",
      "Línea del tiempo",
      "1891: James Naismith inventa el baloncesto.\n1892: Sus 13 reglas del juego se publican en el periódico de la escuela.\n1893: Las estudiantes de Smith College, una universidad para mujeres, juegan su primer partido.\n1936: El baloncesto se vuelve deporte olímpico.",
    ],
    qs: [
      Q("features", ["What does the timeline at the end help readers do?", "¿Para qué les sirve a los lectores la línea del tiempo del final?"], ["See important events in basketball's history in order", "Para ver en orden sucesos importantes de la historia del baloncesto"], [["Learn the 13 rules of the game", "Para aprender las 13 reglas del juego", "wrong-feature"], ["Find out what peach baskets are", "Para saber qué son las canastas de duraznos", "wrong-feature"], ["Read Naismith's own words", "Para leer las palabras del propio Naismith", "not-in-text"]], ["Look at how each line of the timeline starts.", "Fíjate en cómo empieza cada renglón de la línea del tiempo."], ["1936: Basketball becomes an Olympic sport.", "1936: El baloncesto se vuelve deporte olímpico."]),
      Q("features", ["According to the timeline, what happened in 1892?", "Según la línea del tiempo, ¿qué pasó en 1892?"], ["Naismith's rules were printed in the school paper.", "Las reglas de Naismith salieron en el periódico de la escuela."], [["Naismith invented basketball.", "Naismith inventó el baloncesto.", "wrong-detail"], ["Basketball became an Olympic sport.", "El baloncesto se volvió deporte olímpico.", "wrong-detail"], ["The first game ended 1 to 0.", "El primer partido terminó 1 a 0.", "wrong-detail"]], ["Find 1892 on the timeline.", "Busca 1892 en la línea del tiempo."], ["1892: His 13 rules for the game are printed in the school newspaper.", "1892: Sus 13 reglas del juego se publican en el periódico de la escuela."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["James Naismith invented basketball to solve a winter problem, and the game spread.", "James Naismith inventó el baloncesto para resolver un problema de invierno, y el juego se difundió."], [["The first basketball game ended 1 to 0.", "El primer partido de baloncesto terminó 1 a 0.", "one-paragraph-only"], ["Sports are fun to play.", "Los deportes son divertidos.", "too-broad"], ["Basketball is the most popular sport in the world.", "El baloncesto es el deporte más popular del mundo.", "not-in-text"]], ["What problem did Naismith have, and what did he make?", "¿Qué problema tenía Naismith y qué creó?"], ["His boss gave him two weeks to invent a new indoor game.", "Su jefe le dio dos semanas para inventar un juego nuevo que se pudiera jugar adentro."]),
      Q("details", ["Why did someone have to climb up after each basket?", "¿Por qué alguien tenía que subir después de cada canasta?"], ["The ball stayed inside the peach basket.", "El balón se quedaba dentro de la canasta de duraznos."], [["The baskets had to be nailed up again.", "Había que volver a clavar las canastas.", "not-in-text"], ["The referee kept score from up high.", "El árbitro llevaba la cuenta desde arriba.", "not-in-text"], ["The players were not allowed to touch the ball.", "Los jugadores no podían tocar el balón.", "not-in-text"]], ["Think about what the bottom of a peach basket is like.", "Piensa en cómo es el fondo de una canasta de duraznos."], ["Every time someone made a basket, a person had to climb up and take the ball out.", "Cada vez que alguien encestaba, una persona tenía que subir a sacar el balón."]),
      Q("words", ["In this article, what does “railing” mean?", "En este artículo, ¿qué significa “baranda”?"], ["A bar along the edge of a balcony", "Una barra a lo largo del borde de un balcón"], [["A kind of basket", "Un tipo de canasta", "wrong-detail"], ["The floor of the gym", "El piso del gimnasio", "ignored-context"], ["A tall ladder", "Una escalera alta", "ignored-context"]], ["The baskets were nailed high above the floor. What part of a balcony could hold them?", "Las canastas quedaron clavadas muy por encima del suelo. ¿Qué parte de un balcón podría sostenerlas?"], ["He nailed two peach baskets to the railing of a balcony, ten feet above the floor.", "Clavó dos canastas de duraznos en la baranda de un balcón, a unos tres metros del suelo."]),
    ],
  },
  {
    id: "hummingbirds",
    kind: "info",
    band: 1,
    title: ["Tiny Helicopters of the Bird World", "Pequeños helicópteros del mundo de las aves"],
    en: [
      "Hummingbirds are some of the smallest birds on Earth. A ruby-throated hummingbird weighs less than a nickel. Even so, these tiny birds are amazing fliers.",
      "Hummingbirds can hover, or stay in one spot in the air, like a helicopter. To do this, they beat their wings about 50 times every second. Their wings move in a pattern shaped like the number eight. Hummingbirds can even fly backward.",
      "All that flying uses a lot of energy. A hummingbird's heart can beat up to about 1,200 times a minute. To get enough fuel, it drinks nectar from hundreds of flowers a day. It also eats tiny insects.",
      "At night, a hummingbird can slow its body down in a deep, sleep-like state called torpor. Its heartbeat and breathing slow, and its body cools. This helps it save energy until morning, when it can eat again.",
      "Fast fact: The hum you hear when a hummingbird flies by comes from its wings beating so fast.",
    ],
    es: [
      "Los colibríes están entre las aves más pequeñas de la Tierra. Un colibrí garganta de rubí pesa menos que una moneda de cinco centavos de dólar. Aun así, estas avecitas son voladoras asombrosas.",
      "Los colibríes pueden quedarse suspendidos, es decir, quietos en un punto del aire, como un helicóptero. Para lograrlo, baten las alas unas 50 veces por segundo. Sus alas se mueven dibujando la forma de un ocho. Los colibríes hasta pueden volar hacia atrás.",
      "Volar tanto gasta mucha energía. El corazón de un colibrí puede latir hasta unas 1200 veces por minuto. Para conseguir suficiente combustible, bebe néctar de cientos de flores al día. También come insectos diminutos.",
      "De noche, un colibrí puede hacer que su cuerpo funcione más despacio en un estado profundo, parecido al sueño, llamado letargo. Su corazón y su respiración se hacen más lentos y su cuerpo se enfría. Así ahorra energía hasta la mañana, cuando puede volver a comer.",
      "Dato curioso: El zumbido que oyes cuando pasa un colibrí viene de sus alas, que baten muy rápido.",
    ],
    qs: [
      Q("features", ["Why does the title call hummingbirds “Tiny Helicopters”?", "¿Por qué el título llama a los colibríes “Pequeños helicópteros”?"], ["They can stay in one spot in the air, as helicopters do.", "Pueden quedarse quietos en el aire, como los helicópteros."], [["They carry people from place to place.", "Llevan personas de un lugar a otro.", "took-literally"], ["They are made of metal.", "Están hechos de metal.", "took-literally"], ["They fly only at night.", "Solo vuelan de noche.", "opposite-of-text"]], ["Find the sentence in the article that mentions a helicopter.", "Busca la oración del artículo que menciona un helicóptero."], ["Hummingbirds can hover, or stay in one spot in the air, like a helicopter.", "Los colibríes pueden quedarse suspendidos, es decir, quietos en un punto del aire, como un helicóptero."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Hummingbirds are tiny birds with special ways of flying and saving energy.", "Los colibríes son aves diminutas con maneras especiales de volar y de ahorrar energía."], [["Hummingbirds eat tiny insects.", "Los colibríes comen insectos diminutos.", "one-paragraph-only"], ["Birds live all around the world.", "Hay aves en todo el mundo.", "too-broad"], ["Hummingbirds are the fastest birds alive.", "Los colibríes son las aves más rápidas que existen.", "not-in-text"]], ["The first paragraph says these tiny birds are amazing fliers. What do the other paragraphs add?", "El primer párrafo dice que estas avecitas son voladoras asombrosas. ¿Qué agregan los otros párrafos?"], ["Even so, these tiny birds are amazing fliers.", "Aun así, estas avecitas son voladoras asombrosas."]),
      Q("mainidea", ["Which detail supports the idea that flying uses a lot of energy?", "¿Qué detalle apoya la idea de que volar gasta mucha energía?"], ["A hummingbird drinks nectar from hundreds of flowers a day.", "Un colibrí bebe néctar de cientos de flores al día."], [["Its wings move in a pattern shaped like an eight.", "Sus alas se mueven en forma de ocho.", "supports-other-point"], ["A ruby-throated hummingbird weighs less than a nickel.", "Un colibrí garganta de rubí pesa menos que una moneda de cinco centavos.", "supports-other-point"], ["Hummingbirds sleep all day.", "Los colibríes duermen todo el día.", "not-in-text"]], ["Find the paragraph that begins by talking about energy. Which details follow?", "Busca el párrafo que empieza hablando de energía. ¿Qué detalles siguen?"], ["All that flying uses a lot of energy.", "Volar tanto gasta mucha energía."]),
      Q("words", ["In this article, what does “torpor” mean?", "En este artículo, ¿qué significa “letargo”?"], ["A deep rest that slows the body to save energy", "Un descanso profundo en que el cuerpo se hace lento para ahorrar energía"], [["Being wide awake and busy", "Estar bien despierto y activo", "opposite-meaning"], ["A fast way of flying", "Una manera rápida de volar", "ignored-context"], ["A kind of flower", "Un tipo de flor", "ignored-context"]], ["Read the sentences right after the word. What happens to the bird's body?", "Lee las oraciones que siguen a la palabra. ¿Qué le pasa al cuerpo del ave?"], ["Its heartbeat and breathing slow, and its body cools.", "Su corazón y su respiración se hacen más lentos y su cuerpo se enfría."]),
      Q("details", ["How can a hummingbird hover?", "¿Cómo logra un colibrí quedarse suspendido?"], ["It beats its wings very fast in a figure-eight pattern.", "Bate las alas muy rápido, en forma de ocho."], [["It flies backward.", "Vuela hacia atrás.", "wrong-detail"], ["It floats on the wind without moving its wings.", "Flota en el viento sin mover las alas.", "opposite-of-text"], ["It holds on to a flower with its feet.", "Se agarra de una flor con las patas.", "not-in-text"]], ["Read the sentences right after the word “hover.”", "Lee las oraciones que siguen a la palabra “suspendidos”."], ["To do this, they beat their wings about 50 times every second.", "Para lograrlo, baten las alas unas 50 veces por segundo."]),
    ],
  },
  {
    id: "drums",
    kind: "info",
    band: 1,
    title: ["How Drums Make Sound", "Cómo suenan los tambores"],
    en: [
      "Every sound you hear starts with something shaking back and forth very fast. This quick shaking is called vibration. A drum is a simple tool for making vibrations.",
      "From Drumhead to Ear",
      "When you hit a drum, its stretched top, called the drumhead, starts to vibrate. The drumhead pushes on the air around it. Those pushes travel through the air as sound waves. When the waves reach your ears, you hear the beat.",
      "High and Low",
      "Some drums make high sounds, and others make low ones. A tight drumhead vibrates faster and makes a higher sound. A loose drumhead vibrates more slowly and makes a lower sound. Size matters too. A big drum usually sounds lower than a small one.",
      "Around the World",
      "People all over the world play drums. In Trinidad and Tobago, musicians play steel pans made from metal barrels. Each dented section of a pan's top plays a different note, so one drum can play a whole song.",
    ],
    es: [
      "Todo sonido que oyes empieza con algo que se mueve de un lado a otro muy rápido. Ese movimiento rápido se llama vibración. Un tambor es una herramienta sencilla para producir vibraciones.",
      "Del parche al oído",
      "Cuando golpeas un tambor, su parte de arriba, estirada, que se llama parche, empieza a vibrar. El parche empuja el aire que lo rodea. Esos empujones viajan por el aire como ondas de sonido. Cuando las ondas llegan a tus oídos, oyes el golpe.",
      "Agudos y graves",
      "Algunos tambores suenan agudo y otros suenan grave. Un parche tenso vibra más rápido y da un sonido más agudo. Un parche flojo vibra más despacio y da un sonido más grave. El tamaño también importa. Un tambor grande casi siempre suena más grave que uno pequeño.",
      "Por todo el mundo",
      "En todo el mundo se tocan tambores. En Trinidad y Tobago, los músicos tocan tambores de acero hechos con barriles de metal. Cada sección abollada de la parte de arriba da una nota distinta, así que un solo tambor puede tocar una canción entera.",
    ],
    qs: [
      Q("sequence", ["What happens because the drumhead pushes on the air?", "¿Qué pasa porque el parche empuja el aire?"], ["Sound waves travel to your ears.", "Las ondas de sonido viajan hasta tus oídos."], [["You hit the drum.", "Golpeas el tambor.", "cause-not-effect"], ["The drumhead gets looser.", "El parche se afloja.", "not-in-text"], ["The drum gets bigger.", "El tambor se hace más grande.", "not-in-text"]], ["Follow the steps in the section about how sound gets from the drum to your ear.", "Sigue los pasos de la sección sobre cómo llega el sonido del tambor al oído."], ["Those pushes travel through the air as sound waves.", "Esos empujones viajan por el aire como ondas de sonido."]),
      Q("features", ["Under which heading would you find out how a drum's size changes its sound?", "¿En qué subtítulo encontrarías cómo cambia el sonido según el tamaño del tambor?"], ["High and Low", "Agudos y graves"], [["From Drumhead to Ear", "Del parche al oído", "wrong-section"], ["Around the World", "Por todo el mundo", "wrong-section"], ["How Drums Make Sound", "Cómo suenan los tambores", "wrong-feature"]], ["Which section compares different kinds of sounds?", "¿Qué sección compara distintos tipos de sonidos?"], ["A big drum usually sounds lower than a small one.", "Un tambor grande casi siempre suena más grave que uno pequeño."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Drums make sound by vibrating, and the way a drum is built changes its sound.", "Los tambores suenan porque vibran, y la forma en que están hechos cambia su sonido."], [["People in Trinidad and Tobago play steel pans.", "En Trinidad y Tobago se tocan tambores de acero.", "one-paragraph-only"], ["Music is important to people.", "La música es importante para la gente.", "too-broad"], ["Drums are the oldest instruments.", "Los tambores son los instrumentos más antiguos.", "not-in-text"]], ["The first paragraph names the big idea. The sections explain it.", "El primer párrafo nombra la idea principal. Las secciones la explican."], ["A drum is a simple tool for making vibrations.", "Un tambor es una herramienta sencilla para producir vibraciones."]),
      Q("details", ["How can one steel pan play a whole song?", "¿Cómo puede un solo tambor de acero tocar una canción entera?"], ["Different parts of its top play different notes.", "Distintas partes de su superficie dan notas diferentes."], [["Its drumhead is very loose.", "Su parche está muy flojo.", "wrong-detail"], ["Many people play it at once.", "Lo tocan muchas personas a la vez.", "not-in-text"], ["It is bigger than other drums.", "Es más grande que otros tambores.", "not-in-text"]], ["Read the last section, about drums around the world.", "Lee la última sección, sobre tambores de todo el mundo."], ["Each dented section of a pan's top plays a different note, so one drum can play a whole song.", "Cada sección abollada de la parte de arriba da una nota distinta, así que un solo tambor puede tocar una canción entera."]),
    ],
  },
  {
    id: "water-cycle",
    kind: "info",
    band: 1,
    title: ["Where Does Rain Come From?", "¿De dónde viene la lluvia?"],
    en: [
      "The rain that falls on your street has been on a long trip. Earth's water moves again and again between the ground and the sky. This never-ending trip is called the water cycle.",
      "Up Into the Air",
      "The Sun warms water in oceans, lakes, and rivers. Some of the water evaporates, which means it turns into an invisible gas called water vapor. The water vapor rises into the sky.",
      "Making Clouds",
      "High in the sky, the air is cold. The cold air cools the water vapor, and it condenses into tiny drops of water. Billions of these drops together make a cloud.",
      "Back Down Again",
      "Inside a cloud, tiny drops bump together and grow bigger. When they get too heavy to float, they fall as rain. When the air is very cold, water can fall as snow instead. The water flows into rivers and lakes or soaks into the ground, and the trip starts over.",
      "Words to know: Evaporate means to change from a liquid into a gas. Condense means to change from a gas into a liquid.",
    ],
    es: [
      "La lluvia que cae en tu calle ha hecho un viaje largo. El agua de la Tierra se mueve una y otra vez entre el suelo y el cielo. Este viaje que nunca termina se llama ciclo del agua.",
      "Hacia el aire",
      "El Sol calienta el agua de los océanos, los lagos y los ríos. Parte del agua se evapora, es decir, se convierte en un gas invisible llamado vapor de agua. El vapor de agua sube al cielo.",
      "Se forman las nubes",
      "En lo alto del cielo, el aire está frío. El aire frío enfría el vapor de agua, que se condensa en gotitas de agua. Miles de millones de esas gotitas juntas forman una nube.",
      "De vuelta abajo",
      "Dentro de una nube, las gotitas chocan entre sí y se hacen más grandes. Cuando pesan demasiado para flotar, caen como lluvia. Cuando el aire está muy frío, el agua puede caer como nieve. El agua corre hacia los ríos y los lagos o se filtra en la tierra, y el viaje vuelve a empezar.",
      "Palabras clave: Evaporarse quiere decir pasar de líquido a gas. Condensarse quiere decir pasar de gas a líquido.",
    ],
    qs: [
      Q("sequence", ["What happens right after water vapor rises into the cold sky?", "¿Qué pasa justo después de que el vapor de agua sube al cielo frío?"], ["It cools and turns into tiny drops that form clouds.", "Se enfría y se convierte en gotitas que forman nubes."], [["The Sun warms the ocean.", "El Sol calienta el océano.", "wrong-order"], ["Rain soaks into the ground.", "La lluvia se filtra en la tierra.", "wrong-order"], ["It turns into snow right away.", "Se convierte en nieve enseguida.", "not-in-text"]], ["Read the section about clouds.", "Lee la sección sobre las nubes."], ["The cold air cools the water vapor, and it condenses into tiny drops of water.", "El aire frío enfría el vapor de agua, que se condensa en gotitas de agua."]),
      Q("features", ["What is the job of the “Words to know” part at the end?", "¿Para qué sirve la parte de “Palabras clave” al final?"], ["To explain two science words used in the article", "Para explicar dos palabras de ciencias que usa el artículo"], [["To show the steps in order", "Para mostrar los pasos en orden", "wrong-feature"], ["To name each section", "Para nombrar cada sección", "wrong-feature"], ["To tell a fun fact about snow", "Para contar un dato curioso sobre la nieve", "wrong-feature"]], ["Read that part. What kind of information is in it?", "Lee esa parte. ¿Qué tipo de información tiene?"], ["Condense means to change from a gas into a liquid.", "Condensarse quiere decir pasar de gas a líquido."]),
      Q("mainidea", ["What is the main idea of this article?", "¿Cuál es la idea principal de este artículo?"], ["Water moves in a cycle from the ground to the sky and back again.", "El agua se mueve en un ciclo del suelo al cielo y de regreso."], [["Clouds are made of billions of tiny drops.", "Las nubes están hechas de miles de millones de gotitas.", "one-paragraph-only"], ["The weather changes every day.", "El tiempo cambia todos los días.", "too-broad"], ["Rain is better than snow.", "La lluvia es mejor que la nieve.", "not-in-text"]], ["Read the first paragraph. What does it say the whole article is about?", "Lee el primer párrafo. ¿De qué dice que trata todo el artículo?"], ["This never-ending trip is called the water cycle.", "Este viaje que nunca termina se llama ciclo del agua."]),
      Q("words", ["In this article, what does “evaporates” mean?", "En este artículo, ¿qué significa “se evapora”?"], ["Turns from water into a gas you cannot see", "Pasa de agua líquida a un gas que no se ve"], [["Changes from a gas into a liquid", "Pasa de gas a líquido", "opposite-meaning"], ["Falls from a cloud as rain", "Cae de una nube como lluvia", "ignored-context"], ["Turns into ice", "Se convierte en hielo", "ignored-context"]], ["The writer explains the word right after it.", "Quien escribe explica la palabra justo después."], ["Some of the water evaporates, which means it turns into an invisible gas called water vapor.", "Parte del agua se evapora, es decir, se convierte en un gas invisible llamado vapor de agua."]),
    ],
  },
];
