import { how, Q, type Passage } from "./types";

// More band 1 stories, grade 2–3 text band (draft: written for KaizenEDU, not yet reviewed by a teacher).
export const BAND1_STORIES_2: Passage[] = [
  {
    id: "leaf-book",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Noor kept checking.", "Noor siguió revisando."],
    title: ["Noor's Leaf Book", "El libro de hojas de Noor"],
    en: [
      "Noor's class was making a leaf book. Each student had to pick one tree and visit it every week until winter. Noor picked the maple tree outside her apartment building.",
      "In September, the maple was green from top to bottom. Noor taped a green leaf into her book and wrote the date under it. Her cousin Sami laughed. “That tree is boring,” he said. “Pick one that does something.”",
      "Noor kept checking. In early October, she noticed a little orange at the tips of the leaves. A week later, the whole tree looked like it was on fire. Noor taped a red leaf next to the green one.",
      "By November, the leaves were falling every time the wind blew. Noor's grandfather, Jiddo, helped her rake them into a pile. “Is the tree dying?” she asked. “No,” said Jiddo. “It is resting. Watch it again in the spring.”",
      "When Sami saw Noor's finished book, he turned the pages slowly. “Okay,” he said. “Your tree does a lot.”",
    ],
    es: [
      "La clase de Noor estaba haciendo un libro de hojas. Cada estudiante tenía que escoger un árbol y visitarlo cada semana hasta el invierno. Noor escogió el arce que estaba frente a su edificio.",
      "En septiembre, el arce estaba verde de arriba abajo. Noor pegó una hoja verde en su libro y escribió la fecha debajo. Su primo Sami se rio. “Ese árbol es aburrido”, dijo. “Escoge uno que haga algo”.",
      "Noor siguió revisando. A principios de octubre, vio un poco de anaranjado en las puntas de las hojas. Una semana después, el árbol entero parecía estar en llamas. Noor pegó una hoja roja junto a la verde.",
      "Para noviembre, las hojas caían cada vez que soplaba el viento. Jiddo, el abuelo de Noor, la ayudó a juntarlas en un montón con el rastrillo. “¿Se está muriendo el árbol?”, preguntó ella. “No”, dijo Jiddo. “Está descansando. Míralo otra vez en la primavera”.",
      "Cuando Sami vio el libro terminado de Noor, pasó las páginas despacio. “Está bien”, dijo. “Tu árbol hace muchas cosas”.",
    ],
    qs: [
      Q("character", ["Which word best describes Noor?", "¿Qué palabra describe mejor a Noor?"], ["Patient", "Paciente"], [["Impatient", "Impaciente", "opposite-trait"], ["Bossy", "Mandona", "trait-not-shown"], ["Careless", "Descuidada", "trait-not-shown"]], ["Think about what Noor does even after Sami calls her tree boring.", "Piensa en lo que hace Noor aunque Sami diga que su árbol es aburrido."], ["Noor kept checking.", "Noor siguió revisando."]),
      Q("character", ["Why does Sami change his mind about the tree?", "¿Por qué cambia de opinión Sami sobre el árbol?"], ["Noor's book shows how much the tree changed.", "El libro de Noor muestra cuánto cambió el árbol."], [["Jiddo tells him the tree is resting.", "Jiddo le dice que el árbol está descansando.", "wrong-character"], ["He picks the same tree for his own book.", "Escoge el mismo árbol para su propio libro.", "not-in-text"], ["The tree grows new leaves in the spring.", "Al árbol le salen hojas nuevas en la primavera.", "not-in-text"]], ["Read the last paragraph. What does Sami look at?", "Lee el último párrafo. ¿Qué mira Sami?"], ["When Sami saw Noor's finished book, he turned the pages slowly.", "Cuando Sami vio el libro terminado de Noor, pasó las páginas despacio."]),
      Q("theme", ["What lesson does the story show?", "¿Qué lección muestra el cuento?"], ["If you keep watching closely, you can see changes that others miss.", "Si sigues observando con atención, puedes ver cambios que otros no ven."], [["Noor makes a book about a maple tree.", "Noor hace un libro sobre un arce.", "plot-summary"], ["You should always pick the biggest tree.", "Siempre hay que escoger el árbol más grande.", "unsupported-lesson"], ["Leaves fall when the wind blows.", "Las hojas se caen cuando sopla el viento.", "too-narrow"]], ["Compare what Sami says at the start with what he says at the end.", "Compara lo que dice Sami al principio con lo que dice al final."], ["“That tree is boring,” he said.", "“Ese árbol es aburrido”, dijo."]),
      Q("words", ["In the story, what does “looked like it was on fire” mean?", "En el cuento, ¿qué significa “parecía estar en llamas”?"], ["Was bright red and orange all over", "Estaba todo rojo y anaranjado brillante"], [["Was really burning", "Se estaba quemando de verdad", "took-literally"], ["Was still all green", "Seguía todo verde", "opposite-meaning"], ["Was losing all its leaves", "Estaba perdiendo todas sus hojas", "ignored-context"]], ["Think about the colors of fire. What colors were the leaves turning?", "Piensa en los colores del fuego. ¿De qué colores se estaban poniendo las hojas?"], ["A week later, the whole tree looked like it was on fire.", "Una semana después, el árbol entero parecía estar en llamas."]),
      Q("sequence", ["What did Noor see right before the whole tree turned red?", "¿Qué vio Noor justo antes de que todo el árbol se pusiera rojo?"], ["The leaf tips starting to turn orange", "Las puntas de las hojas empezando a ponerse anaranjadas"], [["The leaves falling in the wind", "Las hojas cayendo con el viento", "wrong-order"], ["The tree green from top to bottom", "El árbol verde de arriba abajo", "wrong-order"], ["New leaves growing in the spring", "Hojas nuevas creciendo en la primavera", "not-in-text"]], ["Find the time words “In early October” and “A week later.”", "Busca las palabras de tiempo “A principios de octubre” y “Una semana después”."], ["In early October, she noticed a little orange at the tips of the leaves.", "A principios de octubre, vio un poco de anaranjado en las puntas de las hojas."]),
    ],
  },
  {
    id: "thunder-count",
    kind: "fiction",
    band: 1,
    pov: "first",
    povEv: ["I sit by the window with Papa and count.", "Me siento junto a la ventana con papá y cuento."],
    whoTells: true,
    title: ["Counting the Thunder", "Contando los truenos"],
    en: [
      "I used to hide under my blanket every time a storm came. The thunder sounded like a giant falling down the stairs.",
      "One night, the lights flickered, and I ran to the kitchen. Papa was sitting by the window. “Come here,” he said. “Let's be storm scientists.”",
      "He showed me what to do. When the lightning flashed, we counted out loud together. We got all the way to fifteen before the thunder rumbled. “Every five seconds is about one mile,” Papa said. “So that storm is about three miles away.”",
      "We kept counting. The next time, we got to twenty. Then we got to twenty-five. The storm was moving away.",
      "Now when a storm comes, I do not hide. I sit by the window with Papa and count. The thunder is still loud, but now I know what it is telling me.",
    ],
    es: [
      "Antes, yo me escondía bajo la cobija cada vez que llegaba una tormenta. Los truenos sonaban como un gigante que se cae por las escaleras.",
      "Una noche, las luces parpadearon y corrí a la cocina. Papá estaba sentado junto a la ventana. “Ven”, me dijo. “Vamos a ser científicos de tormentas”.",
      "Me enseñó qué hacer. Cuando brilló el relámpago, contamos en voz alta los dos juntos. Llegamos hasta quince antes de que retumbara el trueno. “Cada tres segundos son más o menos un kilómetro”, dijo papá. “Así que esa tormenta está a unos cinco kilómetros”.",
      "Seguimos contando. La siguiente vez, llegamos a veinte. Luego llegamos a veinticinco. La tormenta se estaba alejando.",
      "Ahora, cuando llega una tormenta, no me escondo. Me siento junto a la ventana con papá y cuento. Los truenos todavía suenan fuerte, pero ahora sé lo que me están diciendo.",
    ],
    qs: [
      Q("character", ["How does the narrator change by the end of the story?", "¿Cómo cambia quien narra al final del cuento?"], ["The narrator stops hiding and watches storms instead.", "Quien narra deja de esconderse y ahora mira las tormentas."], [["The narrator becomes more afraid of storms.", "Quien narra les tiene más miedo a las tormentas.", "opposite-of-text"], ["The narrator learns how to make thunder.", "Quien narra aprende a hacer truenos.", "not-in-text"], ["Papa starts hiding under a blanket.", "Papá empieza a esconderse bajo la cobija.", "wrong-character"]], ["Compare the first paragraph with the last one.", "Compara el primer párrafo con el último."], ["Now when a storm comes, I do not hide.", "Ahora, cuando llega una tormenta, no me escondo."]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Understanding something can make it less scary.", "Entender algo puede hacer que dé menos miedo."], [["Someone counts with Papa during a storm.", "Alguien cuenta con su papá durante una tormenta.", "plot-summary"], ["Storms are dangerous, so always hide.", "Las tormentas son peligrosas, así que siempre hay que esconderse.", "unsupported-lesson"], ["Thunder comes after lightning.", "El trueno llega después del relámpago.", "too-narrow"]], ["Read the last sentence. What does the narrator know now?", "Lee la última oración. ¿Qué sabe ahora quien narra?"], ["but now I know what it is telling me", "pero ahora sé lo que me están diciendo"]),
      Q("sequence", ["What did the narrator and Papa do right after the lightning flashed?", "¿Qué hicieron quien narra y papá justo después de que brilló el relámpago?"], ["They counted out loud.", "Contaron en voz alta."], [["They ran to the kitchen.", "Corrieron a la cocina.", "wrong-order"], ["They turned off the lights.", "Apagaron las luces.", "not-in-text"], ["They hid under a blanket.", "Se escondieron bajo la cobija.", "wrong-order"]], ["Find the word “When” in the third paragraph.", "Busca la palabra “Cuando” en el tercer párrafo."], ["When the lightning flashed, we counted out loud together.", "Cuando brilló el relámpago, contamos en voz alta los dos juntos."]),
      Q("details", ["About how far away was the storm the first time they counted?", "¿Más o menos qué tan lejos estaba la tormenta la primera vez que contaron?"], ["About three miles", "A unos cinco kilómetros"], [["About fifteen miles", "A unos quince kilómetros", "wrong-detail"], ["About twenty-five miles", "A unos veinticinco kilómetros", "wrong-detail"], ["Right over the house", "Justo encima de la casa", "not-in-text"]], ["How many seconds did they count? How many seconds does Papa say make a mile?", "¿Cuántos segundos contaron? ¿Cuántos segundos dice papá que son un kilómetro?"], ["We got all the way to fifteen before the thunder rumbled.", "Llegamos hasta quince antes de que retumbara el trueno."]),
      Q("pov", ["Which sentence shows that the narrator is a character in the story?", "¿Qué oración muestra que quien narra es un personaje del cuento?"], ["He showed me what to do.", "Me enseñó qué hacer."], [["Papa was sitting by the window.", "Papá estaba sentado junto a la ventana.", "no-narrator-clue"], ["The thunder sounded like a giant falling down the stairs.", "Los truenos sonaban como un gigante que se cae por las escaleras.", "no-narrator-clue"]], ["Look for words like “I,” “me,” or “my” outside of quotation marks.", "Busca palabras como “yo”, “me” o “mi” fuera de las comillas."], ["I sit by the window with Papa and count.", "Me siento junto a la ventana con papá y cuento."]),
    ],
  },
  {
    id: "cracked-pot",
    kind: "fiction",
    band: 1,
    pov: "first",
    povEv: ["She lets me help her water the plants on her shelf", "Me deja ayudarla a regar las plantas de su estante"],
    whoTells: true,
    title: ["The Blue Pot", "La maceta azul"],
    en: [
      "My aunt Mei makes clay pots in her garage. She lets me help her water the plants on her shelf, but she always says, “Walk slowly near the pots.”",
      "One afternoon, I was in a hurry to finish. I swung the watering can, and it bumped a small blue pot. The pot did not fall, but a crack ran down one side.",
      "My stomach felt cold. I turned the pot so the crack faced the wall. Nobody would ever know.",
      "At dinner, Aunt Mei talked about the blue pot. She was going to give it to her neighbor for her birthday. I could not eat. I kept thinking about the crack facing the wall.",
      "After dinner, I told her the truth and said I was sorry. Aunt Mei was quiet for a moment. Then she said, “Thank you for telling me. A crack can be fixed. Hiding it is harder to fix.” The next Saturday, she showed me how to mend the pot with gold paint along the crack.",
    ],
    es: [
      "Mi tía Mei hace macetas de barro en su garaje. Me deja ayudarla a regar las plantas de su estante, pero siempre dice: “Camina despacio cerca de las macetas”.",
      "Una tarde, yo tenía prisa por terminar. Moví la regadera muy rápido y golpeó una maceta azul pequeña. La maceta no se cayó, pero se le hizo una grieta en un lado.",
      "Sentí frío en el estómago. Giré la maceta para que la grieta quedara contra la pared. Nadie se iba a enterar.",
      "En la cena, la tía Mei habló de la maceta azul. Se la iba a regalar a su vecina por su cumpleaños. Yo no podía comer. No dejaba de pensar en la grieta contra la pared.",
      "Después de cenar, le dije la verdad y le pedí perdón. La tía Mei se quedó callada un momento. Luego dijo: “Gracias por decírmelo. Una grieta se puede arreglar. Esconderla es más difícil de arreglar”. El sábado siguiente, me enseñó a reparar la maceta con pintura dorada a lo largo de la grieta.",
    ],
    qs: [
      Q("character", ["Why does the narrator turn the pot so the crack faces the wall?", "¿Por qué quien narra gira la maceta para que la grieta quede contra la pared?"], ["To hide the crack so nobody finds out", "Para esconder la grieta y que nadie se entere"], [["Because the pot looks better that way", "Porque así se ve más bonita la maceta", "wrong-motive"], ["To show the crack to the neighbor", "Para mostrarle la grieta a la vecina", "opposite-of-text"], ["Because Aunt Mei asked", "Porque la tía Mei se lo pidió", "not-in-text"]], ["Read the third paragraph. What does the narrator hope?", "Lee el tercer párrafo. ¿Qué espera quien narra?"], ["Nobody would ever know.", "Nadie se iba a enterar."]),
      Q("character", ["How does the narrator feel at dinner?", "¿Cómo se siente quien narra en la cena?"], ["Guilty about hiding the crack", "Culpable por haber escondido la grieta"], [["Happy about the birthday gift", "Feliz por el regalo de cumpleaños", "not-in-text"], ["Hungry for more food", "Con ganas de comer más", "opposite-of-text"], ["Bored by the talk about pots", "Le aburre la plática de las macetas", "not-in-text"]], ["Read the fourth paragraph. Why can't the narrator eat?", "Lee el cuarto párrafo. ¿Por qué no puede comer quien narra?"], ["I kept thinking about the crack facing the wall.", "No dejaba de pensar en la grieta contra la pared."]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Telling the truth is better than hiding a mistake.", "Decir la verdad es mejor que esconder un error."], [["A pot gets a crack in Aunt Mei's garage.", "Una maceta se agrieta en el garaje de la tía Mei.", "plot-summary"], ["Never help with chores.", "Nunca ayudes con las tareas de la casa.", "unsupported-lesson"], ["Gold paint is pretty.", "La pintura dorada es bonita.", "too-narrow"]], ["Read what Aunt Mei says after the narrator tells her.", "Lee lo que dice la tía Mei cuando quien narra se lo cuenta."], ["Hiding it is harder to fix.", "Esconderla es más difícil de arreglar"]),
      Q("sequence", ["What happened right after the watering can bumped the pot?", "¿Qué pasó justo después de que la regadera golpeó la maceta?"], ["A crack showed up down one side.", "Se le abrió una grieta."], [["The pot fell and broke.", "La maceta se cayó y se rompió.", "opposite-of-text"], ["Aunt Mei talked about the pot.", "La tía Mei habló de la maceta.", "wrong-order"], ["The narrator painted the crack gold.", "Quien narra pintó la grieta de dorado.", "wrong-order"]], ["Find the sentence about the watering can, then read the next one.", "Busca la oración de la regadera y luego lee la que sigue."], ["The pot did not fall, but a crack ran down one side.", "La maceta no se cayó, pero se le hizo una grieta en un lado."]),
      how(Q("pov", ["The narrator says, “Nobody would ever know.” What does the reader know that Aunt Mei does not know yet?", "Quien narra dice: “Nadie se iba a enterar”. ¿Qué sabe el lector que la tía Mei todavía no sabe?"], ["That the blue pot has a crack", "Que la maceta azul tiene una grieta"], [["That the pot is a birthday gift", "Que la maceta es un regalo de cumpleaños", "swapped-views"], ["That gold paint can fix a crack", "Que la pintura dorada puede arreglar una grieta", "swapped-views"], ["That the neighbor broke the pot", "Que la vecina rompió la maceta", "not-in-text"]], ["Think about what the narrator did with the pot and who saw it.", "Piensa en lo que hizo quien narra con la maceta y en quién lo vio."], ["I turned the pot so the crack faced the wall.", "Giré la maceta para que la grieta quedara contra la pared."]), ["A first-person narrator shares secrets with the reader. Think about what the narrator did that no one else saw.", "Un narrador en primera persona le cuenta secretos al lector. Piensa en lo que hizo que nadie más vio."]),
    ],
  },
  {
    id: "bus-card",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["That weekend, Keoni folded a big sheet of paper into a card.", "Ese fin de semana, Keoni dobló una hoja grande de papel para hacer una tarjeta."],
    title: ["A Card for Bus Number 9", "Una tarjeta para el autobús número 9"],
    en: [
      "Every morning, Ms. Ortiz drove bus number 9. She knew every student's name. When it rained, she waited an extra minute for kids running down the street.",
      "One Friday, Keoni heard that Ms. Ortiz was retiring at the end of the month. He thought about all the mornings she had said good morning to him, even when he was grumpy.",
      "That weekend, Keoni folded a big sheet of paper into a card. On the front, he drew bus number 9 with a smiling face in every window. Inside, he wrote, “Thank you for getting us to school safe, rain or shine.”",
      "On Monday, he asked every kid on the bus to sign it. Some kids wrote their names. The kindergartners drew hearts and stars. By Friday, there was no empty space left.",
      "When Keoni handed Ms. Ortiz the card, she read every name. Then she wiped her eyes and taped the card above the steering wheel. “Now I get to see all of you,” she said, “even on my last day.”",
    ],
    es: [
      "Todas las mañanas, la señora Ortiz manejaba el autobús número 9. Se sabía el nombre de cada estudiante. Cuando llovía, esperaba un minuto más a los niños que venían corriendo por la calle.",
      "Un viernes, Keoni oyó que la señora Ortiz se iba a jubilar a fin de mes. Pensó en todas las mañanas en que ella le había dado los buenos días, aun cuando él estaba de mal humor.",
      "Ese fin de semana, Keoni dobló una hoja grande de papel para hacer una tarjeta. En la portada, dibujó el autobús número 9 con una cara sonriente en cada ventana. Adentro escribió: “Gracias por llevarnos a la escuela sanos y salvos, con lluvia o con sol”.",
      "El lunes, les pidió a todos los niños del autobús que la firmaran. Algunos escribieron su nombre. Los de kínder dibujaron corazones y estrellas. Para el viernes, ya no quedaba ningún espacio vacío.",
      "Cuando Keoni le dio la tarjeta a la señora Ortiz, ella leyó cada nombre. Luego se secó los ojos y pegó la tarjeta arriba del volante. “Ahora puedo verlos a todos”, dijo, “hasta en mi último día”.",
    ],
    qs: [
      Q("character", ["Which word best describes Keoni?", "¿Qué palabra describe mejor a Keoni?"], ["Grateful", "Agradecido"], [["Rude", "Grosero", "opposite-trait"], ["Lazy", "Flojo", "trait-not-shown"], ["Shy", "Tímido", "trait-not-shown"]], ["Think about why Keoni makes the card.", "Piensa en por qué Keoni hace la tarjeta."], ["That weekend, Keoni folded a big sheet of paper into a card.", "Ese fin de semana, Keoni dobló una hoja grande de papel para hacer una tarjeta."]),
      Q("character", ["Why does Ms. Ortiz tape the card above the steering wheel?", "¿Por qué la señora Ortiz pega la tarjeta arriba del volante?"], ["So she can see all the students while she drives", "Para ver a todos los estudiantes mientras maneja"], [["Because the card is too big for her bag", "Porque la tarjeta no le cabe en la bolsa", "wrong-motive"], ["So Keoni can read it again", "Para que Keoni la vuelva a leer", "wrong-motive"], ["Because the bus needs a new sign", "Porque el autobús necesita un letrero nuevo", "not-in-text"]], ["Read what Ms. Ortiz says at the end.", "Lee lo que dice la señora Ortiz al final."], ["“Now I get to see all of you,” she said", "“Ahora puedo verlos a todos”, dijo"]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Everyday kindness deserves a thank-you.", "La amabilidad de todos los días merece un agradecimiento."], [["Keoni makes a card for the bus driver.", "Keoni hace una tarjeta para la conductora del autobús.", "plot-summary"], ["Rainy days are the worst days.", "Los días de lluvia son los peores.", "unsupported-lesson"], ["Kindergartners like to draw hearts.", "A los de kínder les gusta dibujar corazones.", "too-narrow"]], ["Think about what Ms. Ortiz did every day and what Keoni did about it.", "Piensa en lo que hacía la señora Ortiz todos los días y en lo que hizo Keoni por eso."], ["She knew every student's name.", "Se sabía el nombre de cada estudiante."]),
      Q("details", ["What did Ms. Ortiz do when it rained?", "¿Qué hacía la señora Ortiz cuando llovía?"], ["She waited a little longer for kids who were running.", "Esperaba un poco más a los niños que venían corriendo."], [["She said good morning to every student.", "Les daba los buenos días a todos.", "wrong-detail"], ["She drove extra fast.", "Manejaba más rápido.", "not-in-text"], ["She gave kids umbrellas.", "Les daba paraguas a los niños.", "not-in-text"]], ["Read the first paragraph.", "Lee el primer párrafo."], ["When it rained, she waited an extra minute for kids running down the street.", "Cuando llovía, esperaba un minuto más a los niños que venían corriendo por la calle."]),
      Q("words", ["In the story, what does “retiring” mean?", "En el cuento, ¿qué significa “jubilar”?"], ["Leaving her job for good, after many years", "Dejar su trabajo para siempre, después de muchos años"], [["Going to bed for the night", "Irse a dormir", "other-meaning", "ignored-context"], ["Driving a different bus", "Manejar otro autobús", "ignored-context"], ["Starting her very first job", "Empezar su primer trabajo", "opposite-meaning"]], ["It happens at the end of the month, and later she talks about her last day. What does that tell you?", "Pasa a fin de mes, y luego ella habla de su último día. ¿Qué te dice eso?"], ["Ms. Ortiz was retiring at the end of the month", "la señora Ortiz se iba a jubilar a fin de mes"]),
    ],
  },
  {
    id: "paint-set",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Zara kept painting, but the house felt very quiet.", "Zara siguió pintando, pero la casa se sentía muy callada."],
    whoTells: true,
    title: ["Zara's Paint Set", "La caja de pinturas de Zara"],
    en: [
      "For her birthday, Zara got a paint set with twenty-four colors. Each color sat in its own little square, shiny and new. She did not want anyone else to touch it.",
      "On Saturday, Zara's little brother, Omar, watched her paint a sunflower. “Can I try?” he asked. “No,” said Zara. “You will mix the colors and make them muddy.”",
      "Omar went to his room. Zara kept painting, but the house felt very quiet. Painting alone was not as much fun as she had thought.",
      "After a while, Zara knocked on Omar's door. She showed him how to rinse the brush in water before picking a new color. Omar painted a blue sky above her sunflower. Then he added a tiny orange bird.",
      "Some of the yellow did turn a little green. Zara did not mind. She hung the painting on the refrigerator, and it was the best one she had ever made.",
    ],
    es: [
      "Para su cumpleaños, a Zara le regalaron una caja de pinturas con veinticuatro colores. Cada color estaba en su propio cuadrito, brillante y nuevo. No quería que nadie más la tocara.",
      "El sábado, Omar, el hermanito de Zara, la miraba pintar un girasol. “¿Puedo probar?”, preguntó. “No”, dijo Zara. “Vas a mezclar los colores y los vas a dejar todos sucios”.",
      "Omar se fue a su cuarto. Zara siguió pintando, pero la casa se sentía muy callada. Pintar sola no era tan divertido como ella pensaba.",
      "Después de un rato, Zara tocó la puerta del cuarto de Omar. Le enseñó a enjuagar el pincel en agua antes de escoger otro color. Omar pintó un cielo azul arriba del girasol. Luego agregó un pajarito anaranjado.",
      "Un poco del amarillo sí se puso verdoso. A Zara no le importó. Colgó la pintura en el refrigerador, y fue la más bonita que había hecho en su vida.",
    ],
    qs: [
      Q("character", ["Why does Zara say no when Omar asks to try?", "¿Por qué Zara le dice que no a Omar cuando le pide probar?"], ["She is afraid he will spoil her new colors.", "Tiene miedo de que él eche a perder sus colores nuevos."], [["She wants him to paint his own sunflower.", "Quiere que él pinte su propio girasol.", "wrong-motive"], ["Omar does not know how to paint.", "Omar no sabe pintar.", "wrong-motive"], ["The paint set belongs to Omar.", "La caja de pinturas es de Omar.", "opposite-of-text"]], ["Read what Zara tells Omar.", "Lee lo que Zara le dice a Omar."], ["“You will mix the colors and make them muddy.”", "“Vas a mezclar los colores y los vas a dejar todos sucios”"]),
      Q("character", ["How does Zara change by the end of the story?", "¿Cómo cambia Zara al final del cuento?"], ["She shares her paints and enjoys it.", "Comparte sus pinturas y lo disfruta."], [["She hides her paint set from Omar.", "Esconde su caja de pinturas para que Omar no la vea.", "opposite-of-text"], ["She gets angry about the green yellow.", "Se enoja porque el amarillo se puso verdoso.", "opposite-of-text"], ["She stops painting for good.", "Deja de pintar para siempre.", "not-in-text"]], ["Compare what Zara wants in the first paragraph with what she does in the fourth.", "Compara lo que quiere Zara en el primer párrafo con lo que hace en el cuarto."], ["She showed him how to rinse the brush in water before picking a new color.", "Le enseñó a enjuagar el pincel en agua antes de escoger otro color."]),
      Q("theme", ["What lesson does the story teach?", "¿Qué lección enseña el cuento?"], ["Sharing can make something more fun, even if it does not stay perfect.", "Compartir puede hacer algo más divertido, aunque no quede perfecto."], [["Zara and Omar paint a sunflower and a bird.", "Zara y Omar pintan un girasol y un pájaro.", "plot-summary"], ["Never let anyone touch your things.", "Nunca dejes que nadie toque tus cosas.", "unsupported-lesson"], ["Rinse your brush before you use a new color.", "Enjuaga el pincel antes de usar otro color.", "too-narrow"]], ["Read the last paragraph. Why is this painting her best one?", "Lee el último párrafo. ¿Por qué es su mejor pintura?"], ["and it was the best one she had ever made", "y fue la más bonita que había hecho en su vida"]),
      Q("sequence", ["What did Zara do after the house felt quiet?", "¿Qué hizo Zara después de que la casa se sintió callada?"], ["She went and knocked on Omar's door.", "Fue a tocar la puerta de Omar."], [["She painted a blue sky.", "Pintó un cielo azul.", "wrong-character"], ["She opened her birthday present.", "Abrió su regalo de cumpleaños.", "wrong-order"], ["She threw the painting away.", "Tiró la pintura a la basura.", "not-in-text"]], ["Find the words “After a while.”", "Busca las palabras “Después de un rato”."], ["After a while, Zara knocked on Omar's door.", "Después de un rato, Zara tocó la puerta del cuarto de Omar."]),
      Q("details", ["What did Omar add to the painting?", "¿Qué le agregó Omar a la pintura?"], ["A blue sky and a small orange bird", "Un cielo azul y un pajarito anaranjado"], [["A yellow sunflower", "Un girasol amarillo", "wrong-character"], ["A green tree", "Un árbol verde", "not-in-text"], ["His name in big letters", "Su nombre con letras grandes", "not-in-text"]], ["Read the fourth paragraph.", "Lee el cuarto párrafo."], ["Omar painted a blue sky above her sunflower.", "Omar pintó un cielo azul arriba del girasol."]),
    ],
  },
  {
    id: "dock-fishing",
    kind: "fiction",
    band: 1,
    pov: "first",
    povEv: ["I noticed the sky turning pink.", "Me fijé en que el cielo se ponía rosado."],
    title: ["Waiting on the Dock", "Esperando en el muelle"],
    en: [
      "Before the sun was up, my grandmother and I sat on the dock with our fishing poles. I call her Lola. The lake was so still that it looked like a mirror.",
      "I cast my line and waited. And waited. After ten minutes, I reeled it in to check the worm. It was still there. I cast again.",
      "“Fish do not like a line that keeps moving,” Lola said. She had not moved her pole once. Her bobber floated in the same spot, like a tiny red apple.",
      "I tried to be still. I watched a dragonfly land on my pole. I listened to a bird calling across the water. I noticed the sky turning pink.",
      "Suddenly my bobber dipped under. I pulled, and a silver fish flipped onto the dock. Lola clapped. “See?” she said. “The lake gives to people who wait.” We let the fish go, and I watched it swim away.",
    ],
    es: [
      "Antes de que saliera el sol, mi abuela y yo nos sentamos en el muelle con nuestras cañas de pescar. Yo le digo Lola. El lago estaba tan quieto que parecía un espejo.",
      "Lancé el anzuelo y esperé. Y esperé. A los diez minutos, recogí el hilo para revisar la lombriz. Seguía ahí. Lo volví a lanzar.",
      "“A los peces no les gusta un hilo que se mueve a cada rato”, dijo Lola. Ella no había movido su caña ni una vez. Su boya flotaba en el mismo lugar, como una manzanita roja.",
      "Traté de no moverme. Vi una libélula que se paró en mi caña. Escuché a un pájaro que cantaba al otro lado del agua. Me fijé en que el cielo se ponía rosado.",
      "De pronto, mi boya se hundió. Jalé, y un pez plateado cayó dando saltos en el muelle. Lola aplaudió. “¿Ves?”, dijo. “El lago les da a los que saben esperar”. Soltamos el pez, y lo vi alejarse nadando.",
    ],
    qs: [
      Q("character", ["Why does the narrator keep reeling in the line?", "¿Por qué quien narra recoge el hilo una y otra vez?"], ["The narrator is impatient and wants to check the worm.", "Le falta paciencia y quiere revisar la lombriz."], [["Lola tells the narrator to move it.", "Lola le dice que lo mueva.", "opposite-of-text"], ["The narrator catches a fish each time.", "Pesca un pez cada vez.", "not-in-text"], ["The worm fell off the hook.", "La lombriz se cayó del anzuelo.", "opposite-of-text"]], ["Read the second paragraph. How long does the narrator wait?", "Lee el segundo párrafo. ¿Cuánto espera quien narra?"], ["After ten minutes, I reeled it in to check the worm.", "A los diez minutos, recogí el hilo para revisar la lombriz."]),
      Q("character", ["Which word best describes Lola?", "¿Qué palabra describe mejor a Lola?"], ["Calm", "Tranquila"], [["Restless", "Inquieta", "opposite-trait"], ["Bossy", "Mandona", "trait-not-shown"], ["Forgetful", "Olvidadiza", "trait-not-shown"]], ["Look at what Lola's pole and bobber do.", "Fíjate en lo que hacen la caña y la boya de Lola."], ["She had not moved her pole once.", "Ella no había movido su caña ni una vez."]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Being patient can bring good things.", "Tener paciencia puede traer cosas buenas."], [["Someone goes fishing with a grandmother.", "Alguien va a pescar con su abuela.", "plot-summary"], ["Always let a fish go.", "Siempre hay que soltar a los peces.", "unsupported-lesson"], ["A bobber floats on the water.", "La boya flota en el agua.", "too-narrow"]], ["Read what Lola says at the end.", "Lee lo que dice Lola al final."], ["“The lake gives to people who wait.”", "“El lago les da a los que saben esperar”"]),
      how(Q("pov", ["The narrator tells about a dragonfly, a bird, and a pink sky. Why does the reader learn about these things?", "Quien narra cuenta de una libélula, un pájaro y un cielo rosado. ¿Por qué el lector se entera de estas cosas?"], ["The narrator notices them while sitting still.", "Quien narra se fija en ellas mientras está sin moverse."], [["Lola explains them to the narrator.", "Lola se las explica.", "wrong-character"], ["The narrator reads about them in a book.", "Quien narra lee sobre ellas en un libro.", "not-in-text"], ["They are what the fish can see.", "Son lo que ven los peces.", "not-in-text"]], ["Read the fourth paragraph. What is the narrator trying to do?", "Lee el cuarto párrafo. ¿Qué trata de hacer quien narra?"], ["I tried to be still.", "Traté de no moverme."]), ["A first-person narrator tells what they see, hear, and notice. Think about why the narrator has time to notice so much.", "Un narrador en primera persona cuenta lo que ve, oye y nota. Piensa en por qué tiene tiempo de fijarse en tantas cosas."]),
      Q("words", ["In the story, what does “looked like a mirror” tell about the lake?", "En el cuento, ¿qué dice del lago la frase “parecía un espejo”?"], ["The water was smooth and still.", "El agua estaba lisa y quieta."], [["The lake was made of glass.", "El lago era de vidrio.", "took-literally"], ["The water was rough and wavy.", "El agua tenía muchas olas.", "opposite-meaning"], ["The lake was very deep.", "El lago era muy hondo.", "ignored-context"]], ["What can you see in a mirror? What would a lake have to be like to do that?", "¿Qué se ve en un espejo? ¿Cómo tendría que estar un lago para hacer lo mismo?"], ["The lake was so still that it looked like a mirror.", "El lago estaba tan quieto que parecía un espejo."]),
    ],
  },
  {
    id: "first-word",
    kind: "fiction",
    band: 1,
    pov: "third",
    povEv: ["Mina's hands got sweaty.", "A Mina le sudaron las manos."],
    title: ["Mina's Word", "La palabra de Mina"],
    en: [
      "Mina's family spoke Korean at home. At school, she spoke English, and she never said a Korean word out loud. She worried the other kids would think it sounded strange.",
      "One morning, Mr. Banks asked everyone to share a word from a language their family knew. Mina's hands got sweaty. When it was her turn, she said quietly, “Annyeong. It means hello.”",
      "Nobody laughed. Instead, Leo asked, “Can you say it again, slower?” Mina said it again, and the whole class tried it. Some kids said it wrong, so Mina helped them.",
      "At lunch, Leo waved and said, “Annyeong, Mina.” Two girls at the next table said it too. Mina laughed and said it back.",
      "That night, Mina told her grandmother what had happened. Her grandmother smiled and taught her one more word to bring to school the next day.",
    ],
    es: [
      "En la casa de Mina hablaban coreano. En la escuela, ella hablaba inglés y nunca decía en voz alta ni una palabra en coreano. Le preocupaba que a los demás niños les sonara rara.",
      "Una mañana, el maestro Banks les pidió a todos que compartieran una palabra de algún idioma que supiera su familia. A Mina le sudaron las manos. Cuando le tocó, dijo en voz baja: “Annyeong. Quiere decir hola”.",
      "Nadie se rio. Al contrario, Leo preguntó: “¿Lo puedes decir otra vez, más despacio?”. Mina lo repitió, y toda la clase lo intentó. Algunos niños lo decían mal, así que Mina los ayudó.",
      "En el almuerzo, Leo la saludó con la mano y le dijo: “Annyeong, Mina”. Dos niñas de la mesa de al lado también lo dijeron. Mina se rio y les contestó lo mismo.",
      "Esa noche, Mina le contó a su abuela lo que había pasado. Su abuela sonrió y le enseñó otra palabra para llevar a la escuela al día siguiente.",
    ],
    qs: [
      Q("character", ["Why does Mina never say Korean words at school at first?", "¿Por qué al principio Mina nunca dice palabras en coreano en la escuela?"], ["She is afraid the other kids will think it sounds strange.", "Tiene miedo de que a los demás niños les suene raro."], [["She does not know any Korean words.", "No sabe ninguna palabra en coreano.", "opposite-of-text"], ["She wants to keep the words a secret game.", "Quiere que las palabras sean un juego secreto.", "wrong-motive"], ["Mr. Banks told her not to.", "El maestro Banks le dijo que no lo hiciera.", "not-in-text"]], ["Read the end of the first paragraph.", "Lee el final del primer párrafo."], ["She worried the other kids would think it sounded strange.", "Le preocupaba que a los demás niños les sonara rara."]),
      Q("theme", ["What is the theme of this story?", "¿Cuál es el tema de este cuento?"], ["Sharing who you are can help you make friends.", "Compartir quién eres te puede ayudar a hacer amigos."], [["Mina teaches her class a Korean word.", "Mina le enseña a su clase una palabra en coreano.", "plot-summary"], ["You should speak only one language.", "Solo se debe hablar un idioma.", "unsupported-lesson"], ["Annyeong means hello.", "Annyeong quiere decir hola.", "too-narrow"]], ["Think about how the other kids act after Mina shares her word.", "Piensa en cómo actúan los demás niños después de que Mina comparte su palabra."], ["Nobody laughed.", "Nadie se rio."]),
      Q("sequence", ["What happened right after Mina said “Annyeong” in class?", "¿Qué pasó justo después de que Mina dijo “Annyeong” en clase?"], ["Leo asked her to say it again more slowly.", "Leo le pidió que lo repitiera más despacio."], [["Leo waved to her at lunch.", "Leo la saludó en el almuerzo.", "wrong-order"], ["Some kids laughed at her.", "Algunos niños se rieron de ella.", "opposite-of-text"], ["Her grandmother taught her a new word.", "Su abuela le enseñó otra palabra.", "wrong-order"]], ["Find the paragraph that begins “Nobody laughed.”", "Busca el párrafo que empieza con “Nadie se rio”."], ["Instead, Leo asked", "Al contrario, Leo preguntó"]),
      Q("details", ["What did Mina do when some kids said the word wrong?", "¿Qué hizo Mina cuando algunos niños dijeron mal la palabra?"], ["She helped them say it.", "Les ayudó a decirla bien."], [["She said it again for the whole class.", "La repitió para toda la clase.", "wrong-detail"], ["She stopped talking.", "Se quedó callada.", "not-in-text"], ["She told Mr. Banks.", "Le avisó al maestro Banks.", "not-in-text"]], ["Read the end of the third paragraph.", "Lee el final del tercer párrafo."], ["Some kids said it wrong, so Mina helped them.", "Algunos niños lo decían mal, así que Mina los ayudó."]),
      how(Q("pov", ["This story is told by a narrator outside it. What does the narrator tell that Mina's classmates cannot see?", "Este cuento lo cuenta un narrador que está fuera de la historia. ¿Qué cuenta el narrador que los compañeros de Mina no pueden ver?"], ["That Mina is worried before she speaks", "Que Mina está preocupada antes de hablar"], [["What Mina's word means", "Qué significa la palabra de Mina", "wrong-detail"], ["That Leo waves at lunch", "Que Leo saluda en el almuerzo", "wrong-detail"], ["What Mr. Banks is thinking", "Lo que piensa el maestro Banks", "not-in-text"]], ["Read the first paragraph. Whose thoughts does the narrator share?", "Lee el primer párrafo. ¿Los pensamientos de quién cuenta el narrador?"], ["She worried the other kids would think it sounded strange.", "Le preocupaba que a los demás niños les sonara rara."]), ["A narrator outside the story can tell what a character thinks. Look for what Mina thinks, not what she says.", "Un narrador que está fuera de la historia puede contar lo que piensa un personaje. Busca lo que piensa Mina, no lo que dice."]),
    ],
  },
];
