import { Q, type Pair } from "./types";

/** Pairs on one topic: Text 1 is always the article, Text 2 the poem or story. A pair's band is its passages' band. */
export const PAIRS: Pair[] = [
  {
    a: "bees",
    b: "hive",
    qs: [
      Q("compare", ["Which fact about bees is in both texts?", "¿Qué dato sobre las abejas aparece en los dos textos?"], ["Bees fan the nectar with their wings to thicken it.", "Las abejas abanican el néctar con las alas para espesarlo."], [["One bee makes about one-twelfth of a teaspoon of honey.", "Una abeja produce la doceava parte de una cucharadita de miel.", "only-text-1"], ["Bees visit clover and apple trees.", "Las abejas visitan el trébol y el manzano.", "only-text-2"], ["Bees sleep inside flowers at night.", "Las abejas duermen dentro de las flores.", "not-in-text"]], ["Find a step that the article explains and the poem describes in its own way.", "Busca un paso que el artículo explica y que el poema describe a su manera."], ["the bees fan it with their wings to dry it out", "las abejas lo abanican con las alas para secarlo"], ["then beat our wings like tiny fans", "y batimos las alas como abanicos diminutos"]),
      Q("compare", ["How is the poem different from the article?", "¿En qué se diferencia el poema del artículo?"], ["In the poem the bees speak as “we”; the article explains the steps with facts.", "En el poema hablan las abejas como “nosotras”; el artículo explica los pasos con datos."], [["The article is told by a bee, and the poem has headings.", "El artículo lo cuenta una abeja y el poema tiene subtítulos.", "mixed-up-texts"], ["The poem gives more numbers than the article.", "El poema da más números que el artículo.", "mixed-up-texts"], ["Both texts are told by a beekeeper.", "Los dos textos los cuenta un apicultor.", "not-in-text"]], ["Who is speaking in each text? Which one has headings?", "¿Quién habla en cada texto? ¿Cuál tiene subtítulos?"], ["A worker bee flies from flower to flower.", "Una abeja obrera vuela de flor en flor."], ["We are the sisters of the hive", "Somos las hermanas de la colmena"]),
      Q("compare", ["Which detail is in the poem but not in the article?", "¿Qué detalle está en el poema, pero no en el artículo?"], ["Bees visit clover and apple trees.", "Las abejas visitan el trébol y el manzano."], [["Worker bees are female.", "Las obreras son hembras.", "in-both-texts"], ["Honey is stored in six-sided wax cells.", "La miel se guarda en celdas de cera de seis lados.", "in-both-texts"], ["Bees make honey from tree sap.", "Las abejas hacen miel con savia de árbol.", "not-in-text"]], ["Look for names of plants. Which text gives them?", "Busca nombres de plantas. ¿Qué texto los da?"], ["A worker bee flies from flower to flower.", "Una abeja obrera vuela de flor en flor."], ["We visit the clover, the apple tree", "Visitamos el trébol, el manzano"]),
      Q("compare", ["What idea do both texts share about how honey gets made?", "¿Qué idea comparten los dos textos sobre cómo se hace la miel?"], ["It takes many bees working together.", "Se necesitan muchas abejas trabajando juntas."], [["One bee can fill a jar of honey alone.", "Una sola abeja puede llenar un frasco de miel.", "opposite-of-text"], ["Bees work only at night.", "Las abejas solo trabajan de noche.", "not-in-text"], ["Beekeepers make the honey.", "Los apicultores hacen la miel.", "not-in-text"]], ["Read the first sentence of the article and the last stanza of the poem.", "Lee la primera oración del artículo y la última estrofa del poema."], ["and it takes a lot of teamwork", "y se necesita mucho trabajo en equipo"], ["It takes us all, and all our days.", "Hacemos falta todas, y todos nuestros días."]),
    ],
  },
  {
    a: "moon",
    b: "moon-watch",
    qs: [
      Q("compare", ["What do both texts say about the Moon on the night of a new moon?", "¿Qué dicen los dos textos sobre la Luna en la noche de luna nueva?"], ["It is still there, even though we cannot see it.", "Sigue ahí, aunque no la veamos."], [["It is gone from the sky for good.", "Desapareció del cielo para siempre.", "opposite-of-text"], ["It looks like a thin silver thread.", "Parece un hilo de plata.", "only-text-2"], ["It hides behind the Sun.", "Se esconde detrás del Sol.", "not-in-text"]], ["Compare what the article says about a new moon with what Grandma says.", "Compara lo que dice el artículo de la luna nueva con lo que dice la abuela."], ["When the lit side faces away from us, we see almost nothing.", "Cuando el lado iluminado no mira hacia nosotros, casi no vemos nada."], ["It's still up there", "Sigue ahí arriba"]),
      Q("compare", ["Which detail is only in the poem?", "¿Qué detalle está solo en el poema?"], ["Moonlight lets the speaker see a shadow without a lamp.", "La luz de la luna deja ver una sombra sin lámpara."], [["The bright part grows each night after a new moon.", "La parte brillante crece cada noche después de la luna nueva.", "in-both-texts"], ["The Moon reflects sunlight like a mirror.", "La Luna refleja la luz del Sol como un espejo.", "only-text-1"], ["The pattern repeats about every 29 and a half days.", "El ciclo se repite más o menos cada 29 días y medio.", "only-text-1"]], ["Which text tells about one person's nights, and what did that person see?", "¿Qué texto cuenta las noches de una persona, y qué vio esa persona?"], ["Sunlight shines on it, and the Moon reflects that light, the way a mirror does.", "La luz del Sol le llega y la Luna la refleja, como lo hace un espejo."], ["I could see my shadow on the sidewalk", "Podía ver mi sombra en la acera"]),
      Q("compare", ["How do the two texts describe the Moon's shapes differently?", "¿En qué se diferencian los dos textos al describir las formas de la Luna?"], ["The article uses science words like waxing; the poem compares the shapes to a thread, a lemon, and a plate.", "El artículo usa palabras de ciencias como creciente; el poema compara las formas con un hilo, un limón y un plato."], [["The article compares the Moon to a lemon; the poem uses the word waxing.", "El artículo compara la Luna con un limón; el poema usa la palabra creciente.", "mixed-up-texts"], ["Both texts say the Moon really changes its shape.", "Los dos textos dicen que la Luna de verdad cambia de forma.", "opposite-of-text"], ["Neither text describes a full moon.", "Ningún texto describe la luna llena.", "opposite-of-text"]], ["Look at the kinds of words each text uses for the shapes.", "Fíjate en el tipo de palabras que usa cada texto para las formas."], ["Astronomers say the Moon is waxing.", "Los astrónomos dicen que la Luna está en fase creciente."], ["a slice, a half, a lemon", "una tajada, una mitad, un limón"]),
    ],
  },
  {
    a: "seeds",
    b: "bean-diary",
    qs: [
      Q("compare", ["What do both texts say comes out of a seed first?", "¿Qué dicen los dos textos que sale primero de una semilla?"], ["A root that grows downward", "Una raíz que crece hacia abajo"], [["Two small green leaves", "Dos hojitas verdes", "wrong-order"], ["A shoot that reaches for light", "Un tallo que busca la luz", "wrong-order"], ["A flower", "Una flor", "not-in-text"]], ["Find the first thing that grows in the article and in Priya's diary.", "Busca lo primero que crece en el artículo y en el diario de Priya."], ["A root pushes out and grows down into the soil.", "Una raíz sale y crece hacia abajo, dentro de la tierra."], ["A tiny white root poked out and curled down toward the bottom of the cup.", "Una raíz blanca y diminuta salió y se curvó hacia el fondo del vaso."]),
      Q("compare", ["Priya's root went limp when her towel dried out. Which fact from the article explains why?", "La raíz de Priya se veía caída cuando se secó la toalla. ¿Qué dato del artículo explica por qué?"], ["A seed needs water to sprout and grow.", "Una semilla necesita agua para germinar y crecer."], [["Most seeds do not need light to sprout.", "La mayoría de las semillas no necesita luz para germinar.", "wrong-detail"], ["A seed can wait for months.", "Una semilla puede esperar meses.", "wrong-detail"], ["Priya measured the shoot every morning.", "Priya medía el tallito todas las mañanas.", "only-text-2"]], ["What was missing when the root went limp? Find that need in the article.", "¿Qué faltaba cuando la raíz se veía caída? Busca esa necesidad en el artículo."], ["To sprout, a seed needs water, air, and the right amount of warmth.", "Para germinar, una semilla necesita agua, aire y la temperatura adecuada."], ["On Monday, the towel was dry and the root looked limp.", "El lunes, la toalla estaba seca y la raíz se veía débil y caída."]),
      Q("compare", ["How is Priya's diary different from the article “From Seed to Sprout”?", "¿En qué se diferencia el diario de Priya del artículo “De semilla a brote”?"], ["The diary tells one girl's experience; the article explains how seeds sprout in general.", "El diario cuenta lo que vivió una niña; el artículo explica cómo germinan las semillas en general."], [["The article is told by Priya, and the diary has headings.", "El artículo lo cuenta Priya, y el diario tiene subtítulos.", "mixed-up-texts"], ["The diary explains how leaves make food from sunlight.", "El diario explica cómo fabrican alimento las hojas con la luz del sol.", "only-text-1"], ["Both texts are about planting a garden outside.", "Los dos textos tratan de sembrar un huerto afuera.", "not-in-text"]], ["Who is telling each text? Is it about one seed or about seeds in general?", "¿Quién cuenta cada texto? ¿Trata de una semilla o de las semillas en general?"], ["Inside each seed is a baby plant and a supply of food.", "Dentro de cada semilla hay una plantita bebé y una reserva de alimento."], ["On Monday, my teacher gave everyone a bean seed, a clear cup, and a paper towel.", "El lunes, la maestra nos dio a cada uno una semilla de frijol, un vaso transparente y una toalla de papel."]),
    ],
  },
  {
    a: "drums",
    b: "kofi-drum",
    qs: [
      Q("compare", ["What do both texts say about a drum top that is stretched tight?", "¿Qué dicen los dos textos sobre la parte de arriba de un tambor cuando está muy estirada?"], ["It vibrates more quickly, so the sound is higher.", "Vibra más rápido, así que el sonido es más agudo."], [["It makes a lower sound.", "Da un sonido más grave.", "opposite-of-text"], ["It makes the drum bigger.", "Hace más grande el tambor.", "not-in-text"], ["It stops the drum from making any sound.", "Hace que el tambor no suene.", "not-in-text"]], ["Find what the article says about a tight drumhead and what Ms. Rivera says about a tight top.", "Busca lo que dice el artículo sobre un parche tenso y lo que dice la maestra Rivera sobre una parte de arriba tensa."], ["A tight drumhead vibrates faster and makes a higher sound.", "Un parche tenso vibra más rápido y da un sonido más agudo."], ["A tight top shakes faster and makes a higher sound.", "Si está tensa, tiembla más rápido y el sonido es más agudo"]),
      Q("compare", ["Which idea is in the article but not in the story?", "¿Qué idea está en el artículo, pero no en el cuento?"], ["A big drum usually sounds lower than a small one.", "Un tambor grande casi siempre suena más grave que uno pequeño."], [["A loose top makes a lower sound.", "Una parte de arriba floja da un sonido más grave.", "in-both-texts"], ["A drum can be made from an oatmeal can.", "Un tambor se puede hacer con un bote de avena.", "only-text-2"], ["Drums are the loudest instruments.", "Los tambores son los instrumentos más fuertes.", "not-in-text"]], ["Kofi's and Hana's drums are the same kind. Which text also talks about the size of a drum?", "Los tambores de Kofi y de Hana son del mismo tipo. ¿Qué texto habla también del tamaño del tambor?"], ["Size matters too.", "El tamaño también importa."], ["His friend Hana's drum sounded different.", "El tambor de su amiga Hana sonaba distinto."]),
      Q("compare", ["How is the purpose of the story different from the purpose of the article?", "¿En qué se diferencia el propósito del cuento del propósito del artículo?"], ["The story shows a boy discovering an idea; the article explains it with facts.", "El cuento muestra a un niño que descubre una idea; el artículo la explica con datos."], [["The article tells about Kofi's music class.", "El artículo cuenta la clase de música de Kofi.", "mixed-up-texts"], ["The story explains sound waves step by step.", "El cuento explica las ondas de sonido paso a paso.", "mixed-up-texts"], ["Both texts teach how to play steel pans.", "Los dos textos enseñan a tocar tambores de acero.", "not-in-text"]], ["Which text has characters, and which one has headings?", "¿Qué texto tiene personajes y cuál tiene subtítulos?"], ["Every sound you hear starts with something shaking back and forth very fast.", "Todo sonido que oyes empieza con algo que se mueve de un lado a otro muy rápido."], ["“Why is mine so low?” Kofi asked.", "“¿Por qué el mío suena tan grave?”, preguntó Kofi."]),
    ],
  },
  {
    a: "coral",
    b: "under-the-reef",
    qs: [
      Q("compare", ["Which detail about coral is in both texts?", "¿Qué detalle sobre el coral aparece en los dos textos?"], ["Some coral has turned white.", "Hay coral que se ha vuelto blanco."], [["Warm water makes corals push out their algae.", "El agua caliente hace que los corales expulsen sus algas.", "only-text-1"], ["The white patch has no fish at all.", "En el parche blanco no hay ni un pez.", "only-text-2"], ["White coral grows faster than colorful coral.", "El coral blanco crece más rápido que el de colores.", "not-in-text"]], ["Read the section about reefs in danger and the poem's fourth stanza.", "Lee la sección sobre los arrecifes en peligro y la cuarta estrofa del poema."], ["corals push out their algae and turn white", "los corales expulsan sus algas y se vuelven blancos"], ["a patch gone white as bone", "un parche blanco como un hueso"]),
      Q("compare", ["Why might the patch in the poem be white? Use the article to explain.", "¿Por qué podría estar blanco el parche del poema? Usa el artículo para explicarlo."], ["The water may have stayed too warm, so the coral pushed out its algae.", "El agua pudo mantenerse demasiado caliente, y el coral expulsó sus algas."], [["A parrotfish ate its colors.", "Un pez loro se comió sus colores.", "not-in-text"], ["The snorkeler touched it.", "La persona que bucea lo tocó.", "not-in-text"], ["Coral is always white at the edge of a reef.", "El coral siempre es blanco en la orilla del arrecife.", "not-in-text"]], ["The poem shows the white patch. Which section of the article explains white coral?", "El poema muestra el parche blanco. ¿Qué sección del artículo explica el coral blanco?"], ["When ocean water stays too warm for too long, corals push out their algae and turn white.", "Cuando el agua del mar se mantiene demasiado caliente por mucho tiempo, los corales expulsan sus algas y se vuelven blancos."], ["But at the edge of the reef I find", "Pero en la orilla del arrecife encuentro"]),
      Q("compare", ["How is the poem different from the article?", "¿En qué se diferencia el poema del artículo?"], ["The poem shows what the reef is like for one swimmer; the article explains how reefs work.", "El poema muestra cómo es el arrecife para una persona que nada; el artículo explica cómo funcionan los arrecifes."], [["The article is told by a snorkeler.", "El artículo lo cuenta alguien que bucea.", "mixed-up-texts"], ["The poem explains what polyps are.", "El poema explica qué son los pólipos.", "mixed-up-texts"], ["Both texts say reefs are made of rocks.", "Los dos textos dicen que los arrecifes son de roca.", "not-in-text"]], ["Which text has a speaker who says “I,” and which one has headings?", "¿Qué texto tiene a alguien que dice “yo” y cuál tiene subtítulos?"], ["Each piece of coral is made of hundreds or thousands of tiny animals called polyps.", "Cada trozo de coral está formado por cientos o miles de animalitos llamados pólipos."], ["I float above the reef in my mask", "Floto sobre el arrecife con mi visor"]),
    ],
  },
  {
    a: "space-station",
    b: "launch-day",
    qs: [
      Q("compare", ["Which fact about life on the station appears in both texts?", "¿Qué dato sobre la vida en la estación aparece en los dos textos?"], ["Astronauts sleep tied to the walls so they will not float away.", "Los astronautas duermen sujetos a las paredes para no irse flotando."], [["The station travels about 17,500 miles per hour.", "La estación viaja a unos 28 000 kilómetros por hora.", "only-text-1"], ["The ground shakes when a rocket launches.", "El suelo tiembla cuando despega un cohete.", "only-text-2"], ["Astronauts grow food in gardens on the station.", "Los astronautas cultivan comida en huertos de la estación.", "not-in-text"]], ["Look for a detail about sleeping in each text.", "Busca un detalle sobre dormir en cada texto."], ["Astronauts sleep in sleeping bags strapped to the walls so they do not drift around at night.", "Los astronautas duermen en sacos de dormir sujetos a las paredes para no andar flotando de noche."], ["and sleep tied to a wall", "y dormirá sujeta a una pared"]),
      Q("compare", ["The poem says the aunt will see “sixteen sunsets every day.” Which fact in the article explains this?", "El poema dice que la tía verá “dieciséis atardeceres cada día”. ¿Qué dato del artículo lo explica?"], ["The station circles Earth about every 90 minutes.", "La estación le da la vuelta a la Tierra cada 90 minutos más o menos."], [["Astronauts exercise about two hours a day.", "Los astronautas hacen ejercicio unas dos horas al día.", "wrong-detail"], ["The station is about 250 miles above Earth.", "La estación está a unos 400 kilómetros de la Tierra.", "wrong-detail"], ["Rockets launch in the morning.", "Los cohetes despegan en la mañana.", "only-text-2"]], ["Look in the article's section about sunrises.", "Busca en la sección del artículo sobre los amaneceres."], ["At that speed, it goes all the way around Earth about every 90 minutes.", "A esa velocidad, le da la vuelta completa a la Tierra más o menos cada 90 minutos."], ["sixteen sunsets every day", "dieciséis atardeceres cada día"]),
      Q("compare", ["How is the poem's point of view different from the article's?", "¿En qué se diferencia el punto de vista del poema del punto de vista del artículo?"], ["The poem shares a family member's feelings; the article gives facts.", "El poema comparte los sentimientos de un familiar; el artículo da datos."], [["The article is told by the aunt in the rocket.", "El artículo lo cuenta la tía que va en el cohete.", "mixed-up-texts"], ["The poem gives the station's exact speed.", "El poema da la velocidad exacta de la estación.", "mixed-up-texts"], ["Both texts are told by astronauts.", "Los dos textos los cuentan astronautas.", "not-in-text"]], ["Which text says “I” and tells how someone feels?", "¿Qué texto dice “yo” y cuenta cómo se siente alguien?"], ["The station travels about 17,500 miles per hour.", "La estación viaja a unos 28 000 kilómetros por hora."], ["and I hold my breath in fright", "y yo contengo el aliento, temblando"]),
      Q("compare", ["Which detail is in the poem but not in the article?", "¿Qué detalle está en el poema, pero no en el artículo?"], ["From the ground, the station looks like a bright moving dot.", "Desde el suelo, la estación se ve como un punto brillante que se mueve."], [["Astronauts float inside the station.", "Los astronautas flotan dentro de la estación.", "in-both-texts"], ["Water on the station is cleaned and used again.", "En la estación, el agua se limpia y se vuelve a usar.", "only-text-1"], ["The station has a swimming pool.", "La estación tiene una piscina.", "not-in-text"]], ["Which text tells what someone on the ground can see at night?", "¿Qué texto cuenta lo que alguien puede ver desde el suelo de noche?"], ["Inside the station, astronauts float.", "Dentro de la estación, los astronautas flotan."], ["a bright dot sliding through the night", "un punto brillante que cruza la noche"]),
    ],
  },
  {
    a: "bread",
    b: "saturday-bread",
    qs: [
      Q("compare", ["What do both texts say happens when yeast is put in warm water?", "¿Qué dicen los dos textos que pasa cuando se pone levadura en agua tibia?"], ["Foam rises on top of the water.", "Sube espuma sobre el agua."], [["The foam is made of carbon dioxide.", "La espuma está hecha de dióxido de carbono.", "only-text-1"], ["The foam looks like a tiny cloud.", "La espuma parece una nubecita.", "only-text-2"], ["The yeast sinks and disappears.", "La levadura se hunde y desaparece.", "not-in-text"]], ["Find the warm water in the “Try it” steps and in the first stanza.", "Busca el agua tibia en los pasos de “Pruébalo” y en la primera estrofa."], ["3. Look for foam on top.", "3. Busca espuma arriba."], ["We watch the foam rise like a tiny cloud.", "Vemos subir la espuma como una nubecita."]),
      Q("compare", ["Grandma says the yeast “is breathing.” Which fact from the article is she describing in her own way?", "La abuela dice que la levadura “está respirando”. ¿Qué dato del artículo describe a su manera?"], ["As yeast eats, it gives off carbon dioxide gas.", "Mientras come, la levadura suelta dióxido de carbono."], [["Yeast is related to mushrooms.", "La levadura es pariente de los champiñones.", "wrong-detail"], ["The heat of the oven kills the yeast.", "El calor del horno mata la levadura.", "wrong-detail"], ["Yeast has tiny lungs.", "La levadura tiene pulmones diminutos.", "not-in-text"]], ["What does yeast give off as it eats?", "¿Qué suelta la levadura mientras come?"], ["As it eats, it gives off a gas called carbon dioxide.", "Mientras come, suelta un gas llamado dióxido de carbono."], ["“It is breathing,” she tells me.", "“Está respirando”, me dice."]),
      Q("compare", ["How is the poem different from the article?", "¿En qué se diferencia el poema del artículo?"], ["The poem shares a family memory; the article explains the science of rising bread.", "El poema comparte un recuerdo familiar; el artículo explica la ciencia de por qué crece el pan."], [["The article is about a grandmother's kitchen.", "El artículo trata de la cocina de una abuela.", "mixed-up-texts"], ["The poem has a glossary.", "El poema tiene un glosario.", "mixed-up-texts"], ["Both texts give a recipe with exact amounts.", "Los dos textos dan una receta con cantidades exactas.", "not-in-text"]], ["Which text has a speaker and a grandmother, and which one has headings?", "¿Qué texto tiene a alguien que habla y a una abuela, y cuál tiene subtítulos?"], ["Yeast is a kind of fungus, related to mushrooms.", "La levadura es un tipo de hongo, pariente de los champiñones."], ["On Saturdays, my grandmother", "Los sábados, mi abuela"]),
    ],
  },
  {
    a: "beavers",
    b: "beaver-pond",
    qs: [
      Q("compare", ["What do both texts say about how a beaver lodge is entered?", "¿Qué dicen los dos textos sobre cómo se entra a una madriguera de castores?"], ["You get in from below the water.", "Se entra por debajo del agua."], [["It has a dry room inside.", "Tiene un cuarto seco por dentro.", "only-text-1"], ["Wolves can sneak in easily.", "Los lobos pueden meterse fácilmente.", "opposite-of-text"], ["It has a door made of stone.", "Tiene una puerta de piedra.", "not-in-text"]], ["Find the lodge in the article and in what Nadia tells Eli.", "Busca la madriguera en el artículo y en lo que Nadia le dice a Eli."], ["The entrances are underwater, which keeps out hungry animals such as wolves.", "Las entradas están bajo el agua, lo que impide el paso de animales hambrientos como los lobos."], ["The door is underwater, so other animals can't sneak in.", "La entrada está bajo el agua, para que otros animales no puedan meterse"]),
      Q("compare", ["In the story, the beaver slaps its tail and dives. Which fact from the article explains why?", "En el cuento, el castor golpea el agua con la cola y se sumerge. ¿Qué dato del artículo explica por qué?"], ["Beavers slap their tails on the water to warn of danger.", "Los castores golpean el agua con la cola para avisar que hay peligro."], [["Beavers are most active at night.", "Los castores están más activos de noche.", "wrong-detail"], ["Beaver teeth never stop growing.", "Los dientes del castor nunca dejan de crecer.", "wrong-detail"], ["Beavers slap their tails to catch fish.", "Los castores golpean con la cola para pescar.", "not-in-text"]], ["Look at the fast facts at the end of the article.", "Mira los datos curiosos al final del artículo."], ["To warn their family of danger, they slap their flat tails on the water.", "Para avisarle a su familia que hay peligro, golpean el agua con su cola plana."], ["Suddenly the beaver slapped its flat tail against the water with a crack like a slamming door, and it dove out of sight.", "De pronto, el castor golpeó el agua con su cola plana, con un chasquido como de puerta que se cierra de golpe, y se sumergió."]),
      Q("compare", ["Ranger Dee told Nadia's class that beavers come out around sunset. How does the article support this?", "La guardabosques Dee le dijo a la clase de Nadia que los castores salen cuando se pone el sol. ¿Cómo lo apoya el artículo?"], ["It says beavers are most active at dusk and at night.", "Dice que los castores están más activos al atardecer y de noche."], [["It never mentions what time beavers are active.", "Nunca dice a qué hora están activos los castores.", "opposite-of-text"], ["It says beavers sleep from dusk until morning.", "Dice que los castores duermen del atardecer a la mañana.", "opposite-of-text"], ["It says beavers come out only at noon.", "Dice que los castores solo salen al mediodía.", "not-in-text"]], ["Look for a time of day in the article.", "Busca una hora del día en el artículo."], ["Beavers are most active at dusk and at night.", "Los castores están más activos al atardecer y de noche."], ["Ranger Dee told our class that beavers come out around sunset.", "La guardabosques Dee le dijo a nuestra clase que los castores salen cuando se pone el sol."]),
    ],
  },
];
