import { Q, type Pair } from "./types";

/** More pairs on one topic: Text 1 is always the article, Text 2 the poem or story. */
export const PAIRS_2: Pair[] = [
  {
    a: "penguins",
    b: "father-penguin",
    qs: [
      Q("compare", ["Which fact about penguins is in both texts?", "¿Qué dato sobre los pingüinos aparece en los dos textos?"], ["The father keeps the egg warm on his feet.", "El papá mantiene caliente el huevo sobre sus patas."], [["An emperor penguin can be almost four feet tall.", "Un pingüino emperador puede medir casi 120 centímetros.", "only-text-1"], ["The father hums to the egg.", "El papá le canturrea al huevo.", "only-text-2"], ["Penguins build nests of sticks.", "Los pingüinos hacen nidos de palitos.", "not-in-text"]], ["Find what the father does with the egg in the article and in the poem.", "Busca lo que hace el papá con el huevo en el artículo y en el poema."], ["The father holds the egg on top of his feet", "El papá sostiene el huevo sobre sus patas"], ["and I lifted it onto my feet", "y yo lo subí a mis patas"]),
      Q("compare", ["The poem's speaker moves “into the crowded middle.” Which fact from the article explains why?", "Quien habla en el poema se mueve “hacia el centro apretado”. ¿Qué dato del artículo explica por qué?"], ["Penguins take turns in the warm middle of the huddle.", "Los pingüinos se turnan para estar en el centro calientito del grupo."], [["Penguins have a thick layer of fat.", "Los pingüinos tienen una capa gruesa de grasa.", "wrong-detail"], ["The mother goes to the sea to eat.", "La mamá se va al mar a comer.", "wrong-detail"], ["Penguins like crowded places best.", "A los pingüinos les gustan más los lugares llenos.", "not-in-text"]], ["Find the section of the article about the whole group.", "Busca la sección del artículo sobre todo el grupo."], ["each one takes a turn in the warm middle", "cada uno toma su turno en el centro, donde hace más calor"], ["into the crowded middle", "hacia el centro apretado"]),
      Q("compare", ["How is the poem different from the article?", "¿En qué se diferencia el poema del artículo?"], ["The poem is told by one penguin father; the article gives facts about many penguins.", "El poema lo cuenta un papá pingüino; el artículo da datos sobre muchos pingüinos."], [["The article is told by a penguin, and the poem has headings.", "El artículo lo cuenta un pingüino y el poema tiene subtítulos.", "mixed-up-texts"], ["The poem tells how tall penguins grow.", "El poema dice qué tan altos son los pingüinos.", "mixed-up-texts"], ["Both texts are about penguins in a zoo.", "Los dos textos tratan de pingüinos de un zoológico.", "not-in-text"]], ["Think about who is talking in the poem and what the article teaches.", "Piensa en quién habla en el poema y en lo que enseña el artículo."], ["Emperor penguins live in Antarctica, the coldest place on Earth.", "Los pingüinos emperador viven en la Antártida, el lugar más frío de la Tierra."], ["Still I stand here on the ice.", "Aun así, yo sigo de pie sobre el hielo."]),
    ],
  },
  {
    a: "spiders",
    b: "morning-web",
    qs: [
      Q("compare", ["What do both texts say happens when an insect hits a web?", "¿Qué dicen los dos textos que pasa cuando un insecto choca con una telaraña?"], ["The web shakes, and the spider hurries over.", "La telaraña se mueve y la araña se acerca rápido."], [["The spider wraps it in silk to save for later.", "La araña lo envuelve en seda para después.", "only-text-1"], ["The dew on the web dries up.", "El rocío de la telaraña se seca.", "only-text-2"], ["The web breaks apart.", "La telaraña se rompe.", "not-in-text"]], ["Find the insect in the article and the fly in the poem.", "Busca el insecto en el artículo y la mosca en el poema."], ["The spider feels the threads shake and hurries over.", "La araña siente que los hilos se mueven y se acerca rápido."], ["The whole web trembled", "Toda la telaraña tembló"]),
      Q("compare", ["In the poem, the web is gone by lunchtime. Which fact from the article could explain this?", "En el poema, la telaraña ya no está a la hora del almuerzo. ¿Qué dato del artículo podría explicarlo?"], ["Garden spiders often take down their old web and build a new one each day.", "Las arañas de jardín suelen quitar su telaraña vieja y hacer otra cada día."], [["Some spiders never build webs.", "Algunas arañas nunca hacen telarañas.", "wrong-detail"], ["A web can be finished in less than an hour.", "Una telaraña se puede terminar en menos de una hora.", "wrong-detail"], ["Webs melt in the sun.", "Las telarañas se derriten con el sol.", "not-in-text"]], ["Read the box at the end of the article.", "Lee el recuadro del final del artículo."], ["Many garden spiders eat their old web and spin a new one every day.", "Muchas arañas de jardín se comen su telaraña vieja y tejen una nueva cada día."], ["and so was the web", "ni la telaraña tampoco"]),
      Q("compare", ["How is the poem different from the article?", "¿En qué se diferencia el poema del artículo?"], ["The poem tells about one web that a person watched; the article explains how spiders use silk.", "El poema habla de una telaraña que alguien miró; el artículo explica cómo usan la seda las arañas."], [["The article is about one web in a garden, and the poem has headings.", "El artículo trata de una telaraña de un huerto, y el poema tiene subtítulos.", "mixed-up-texts"], ["The poem lists spiders that do not spin webs.", "El poema nombra arañas que no tejen telarañas.", "mixed-up-texts"], ["Both texts say spiders are insects.", "Los dos textos dicen que las arañas son insectos.", "opposite-of-text"]], ["Who is talking in the poem? What does the article teach?", "¿Quién habla en el poema? ¿Qué enseña el artículo?"], ["All spiders can make silk, a strong thread that comes out of their bodies.", "Todas las arañas pueden hacer seda, un hilo resistente que sale de su cuerpo."], ["I found a wheel made of silver thread", "encontré una rueda hecha de hilo plateado"]),
    ],
  },
  {
    a: "leaves",
    b: "leaf-book",
    qs: [
      Q("compare", ["What do both texts say happens to leaves in the fall?", "¿Qué dicen los dos textos que les pasa a las hojas en otoño?"], ["They change color and then drop from the tree.", "Cambian de color y luego se caen del árbol."], [["A thin layer grows where the leaf joins the branch.", "Crece una capa delgada donde la hoja se une a la rama.", "only-text-1"], ["Noor tapes them into a book.", "Noor las pega en un libro.", "only-text-2"], ["They turn blue before winter.", "Se ponen azules antes del invierno.", "not-in-text"]], ["Find what the leaves do in the fall in the article, and in October and November in the story.", "Busca lo que hacen las hojas en otoño en el artículo, y en octubre y noviembre en el cuento."], ["Then the leaves drop to the ground.", "Luego las hojas caen al suelo."], ["By November, the leaves were falling every time the wind blew.", "Para noviembre, las hojas caían cada vez que soplaba el viento."]),
      Q("compare", ["Noor asks if the tree is dying. Which fact from the article shows that Jiddo is right?", "Noor pregunta si el árbol se está muriendo. ¿Qué dato del artículo muestra que Jiddo tiene razón?"], ["After winter, the tree grows new green leaves.", "Después del invierno, al árbol le salen hojas verdes nuevas."], [["The tree stops making chlorophyll.", "El árbol deja de fabricar clorofila.", "wrong-detail"], ["Leaves make food from sunlight.", "Las hojas fabrican alimento con la luz del sol.", "wrong-detail"], ["Old trees lose their leaves forever.", "Los árboles viejos pierden sus hojas para siempre.", "opposite-of-text"]], ["Think about what happens to the tree after winter.", "Piensa en lo que le pasa al árbol después del invierno."], ["The tree rests through the cold months", "El árbol descansa durante los meses fríos"], ["Watch it again in the spring", "Míralo otra vez en la primavera"]),
      Q("compare", ["How is the story different from the article?", "¿En qué se diferencia el cuento del artículo?"], ["The story follows one girl watching one tree; the article explains why leaves change.", "El cuento sigue a una niña que observa un árbol; el artículo explica por qué cambian las hojas."], [["The article is about Noor's maple tree.", "El artículo trata del arce de Noor.", "mixed-up-texts"], ["The story explains what chlorophyll is.", "El cuento explica qué es la clorofila.", "mixed-up-texts"], ["Both texts are about trees in the spring.", "Los dos textos tratan de árboles en primavera.", "not-in-text"]], ["Think about who is in the story and what the article teaches.", "Piensa en quién está en el cuento y en lo que enseña el artículo."], ["To do this, it uses chlorophyll, a green material inside the leaf.", "Para hacerlo, usa clorofila, una sustancia verde que hay dentro de la hoja."], ["Noor picked the maple tree outside her apartment building.", "Noor escogió el arce que estaba frente a su edificio."]),
    ],
  },
  {
    a: "lightning",
    b: "thunder-count",
    qs: [
      Q("compare", ["What do both texts say counting seconds during a storm can tell you?", "¿Qué dicen los dos textos que te puede decir contar los segundos durante una tormenta?"], ["About how far away the lightning is", "Más o menos a qué distancia está el rayo"], [["How hot the lightning is", "Qué tan caliente está el rayo", "only-text-1"], ["When the lights will flicker", "Cuándo van a parpadear las luces", "not-in-text"], ["How to make the storm go away", "Cómo hacer que se vaya la tormenta", "not-in-text"]], ["Find the counting in the last section of the article and in what Papa says.", "Busca cómo se cuenta en la última sección del artículo y en lo que dice papá."], ["To guess how far away the lightning is, count the seconds until you hear thunder.", "Para calcular qué tan lejos está el rayo, cuenta los segundos hasta que oigas el trueno."], ["“Every five seconds is about one mile,” Papa said.", "“Cada tres segundos son más o menos un kilómetro”, dijo papá."]),
      Q("compare", ["In the story, the count gets longer each time. Using the article, what does that mean?", "En el cuento, cada vez cuentan más segundos. Según el artículo, ¿qué quiere decir eso?"], ["The lightning is getting farther away.", "Los rayos están cada vez más lejos."], [["The lightning is getting closer.", "Los rayos están cada vez más cerca.", "opposite-of-text"], ["The thunder is getting louder.", "Los truenos suenan cada vez más fuerte.", "not-in-text"], ["Light is slowing down.", "La luz va más despacio.", "not-in-text"]], ["Find the rule in the article about seconds and distance, then look at the counts in the story.", "Busca la regla del artículo sobre los segundos y la distancia, y luego fíjate en lo que cuentan en el cuento."], ["Every five seconds means about one mile.", "Cada tres segundos son más o menos un kilómetro."], ["The next time, we got to twenty.", "La siguiente vez, llegamos a veinte."]),
      Q("compare", ["How is the story different from the article?", "¿En qué se diferencia el cuento del artículo?"], ["The story shows one family using the counting rule; the article explains the science.", "El cuento muestra a una familia que usa la regla de contar; el artículo explica la ciencia."], [["The article is told by a child who is afraid of storms.", "El artículo lo cuenta alguien que les tiene miedo a las tormentas.", "mixed-up-texts"], ["The story explains how thunder is made.", "El cuento explica cómo se forma el trueno.", "mixed-up-texts"], ["Both texts say to hide under a blanket.", "Los dos textos dicen que hay que esconderse bajo la cobija.", "not-in-text"]], ["Which text has a narrator and a papa? What does the other one do?", "¿Qué texto tiene a alguien que narra y a un papá? ¿Qué hace el otro?"], ["Lightning is a giant spark of electricity.", "Un rayo es una chispa gigante de electricidad."], ["“Let's be storm scientists.”", "“Vamos a ser científicos de tormentas”"]),
    ],
  },
];
