import { PRODUCT, publicConfig } from '@/kaizen.config';
import { PRODUCT_ROUTES } from '@/lib/tutor/contracts';
import { LEGAL_VERSIONS } from '@/lib/tutor/client/legal';

import { LegalPage } from './legal-page';

const NAME = PRODUCT.workingName;
const AI_LABEL = publicConfig.product.aiLabel;

export function AiDisclosure() {
  return (
    <LegalPage
      title="AI disclosure"
      version={LEGAL_VERSIONS.ai}
      summary={`What the tutor is, what it is not, where it can be wrong, and what it will not do.`}
      current={PRODUCT_ROUTES.legalAi}
    >
      <h2>The tutor is software</h2>
      <p>
        The tutor in {NAME} is an artificial-intelligence system: a language model that writes each
        reply, a speech system that reads it aloud, and a drawing system that puts steps on the
        whiteboard. It is shown as an abstract presence, not a face or a person, so that a learner
        can see it listen, think, and talk. It is not a person, it is not a recording of a person,
        and it does not pretend to be either. The label {AI_LABEL} stays on screen during every
        session, and the tutor says it is an AI whenever a learner asks.
      </p>

      <h2>What it will not do</h2>
      <ul>
        <li>
          It will not claim to be human, say it misses a learner, or ask a learner to come back.
        </li>
        <li>
          It will not give the final answer to graded-looking work before the learner tries a step
          (coach mode).
        </li>
        <li>
          It will not ask a learner for their name, school, address, or contacts, and it redirects
          off-topic requests back to studying.
        </li>
        <li>
          It will not produce sexual, violent, or hateful content, or romantic roleplay, and it
          applies stricter rules for learners aged 9 to 12.
        </li>
        <li>
          It will not lengthen a session to keep a learner on screen. Sessions end at their
          scheduled length.
        </li>
        <li>
          It will not use attention signals to pull a learner back later. They adapt the lesson and
          inform the parent; they never trigger a notification to the learner or a reminder to come
          back.
        </li>
      </ul>

      <h2>Where it can be wrong</h2>
      <p>
        Language models make mistakes: an explanation can be misleading, a graded check can be
        marked wrongly, a drawing can be off. The tutor checks arithmetic before stating it and says
        when it is unsure, but none of that makes it reliable in the way a textbook or a teacher is.
        Treat what it says as a strong first explanation, not as an authority. Every progress number
        in the product is labelled an estimate until an unaided check at least a day later confirms
        it, and the tutor never grades its own help as mastery.
      </p>

      <h2>What it must never be relied on for</h2>
      <p>
        The progress report is generated by software from a handful of check items. It is not a
        professional assessment, and it must never be read as one. Specifically, nothing the tutor
        or the report produces is:
      </p>
      <ul>
        <li>
          An assessment of a learner&rsquo;s ability, aptitude, or needs by a teacher, psychologist,
          educational diagnostician, or any other qualified person.
        </li>
        <li>
          A diagnosis of anything &mdash; a learning disability, ADHD, dyscalculia, dyslexia, or any
          other condition. The tutor does not screen for these, and no number it produces means
          anything about them.
        </li>
        <li>
          A basis for a placement, grade-level, or eligibility decision, including anything feeding
          an IEP or a 504 plan.
        </li>
        <li>Medical, psychological, legal, or financial advice.</li>
        <li>
          Crisis support. If a learner discloses self-harm or abuse, the tutor responds with care,
          gives crisis resources, and stops tutoring &mdash; it does not counsel, and it is not a
          substitute for a person.
        </li>
        <li>
          Supervision. It is not a childminder and does not know what is happening in the room.
        </li>
      </ul>

      <h2>What to do when something is off</h2>
      <p>
        Every session has a report button. Use it for an answer that is wrong, a reply that is
        inappropriate, or anything that worried you. A report creates a flagged record that a person
        reviews. If a learner discloses self-harm or abuse, the tutor stops tutoring, offers crisis
        resources, and the session is flagged to the account holder and for review.
      </p>

      <h2>What the AI sees</h2>
      <p>
        The models receive the text of the conversation, the problem the learner brought &mdash;
        including the uploaded photo or PDF, for the stage that reads it &mdash; and a compact
        summary of the learner’s skills and past misconceptions. Voice is transcribed to text and
        the recording is discarded. No camera image ever reaches an AI provider or our servers,
        because there is no camera in this product. We do not use learner data to train models. The
        full list of providers and what each receives is in the privacy policy.
      </p>

      <h2>Which models</h2>
      <p>
        The operator routes each stage of a session (the live turn, grading, the summary, reading an
        uploaded problem) to a specific model from Google, Anthropic, or OpenAI, and can change that
        routing to improve quality, speed, or cost. Learners and parents never configure a provider,
        and no provider key ever reaches the browser.
      </p>
    </LegalPage>
  );
}
