import { PLAN, PRODUCT, publicConfig } from '@/kaizen.config';
import { PRODUCT_ROUTES } from '@/lib/tutor/contracts';
import { formatMoney } from '@/lib/tutor/client/format';
import { LEGAL_VERSIONS } from '@/lib/tutor/client/legal';

import { LegalPage } from './legal-page';

const NAME = PRODUCT.workingName;
const AI_LABEL = publicConfig.product.aiLabel;

export function TermsOfService() {
  return (
    <LegalPage
      title="Terms of service"
      version={LEGAL_VERSIONS.terms}
      summary={`The agreement between you and the operator of ${NAME} when you create an account, add a learner profile, or use a session.`}
      current={PRODUCT_ROUTES.legalTerms}
    >
      <h2>1. Who can open an account</h2>
      <p>
        An account is opened by an adult: a parent or guardian, or an adult learning for themselves.
        A learner under 18 uses the service only through a profile that the account holder created.
        Teen profiles (ages 13 to 17) get their own login name under the account. Profiles for
        learners under 13 &mdash; which includes the 9-to-12 band &mdash; can be created but stay
        locked, and collect nothing beyond the name and birth year you type, until the
        parental-consent flow described in the privacy policy is live and the account holder has
        completed it.
      </p>
      <p>
        By opening an account you confirm that you are 18 or over, and that you are the parent or
        legal guardian of any learner under 18 you add to it.
      </p>

      <h2>2. What the service is</h2>
      <p>
        {NAME} is a one-to-one {AI_LABEL} that works by voice and text, draws on a shared
        whiteboard, asks check questions, keeps a record of each session, and shows the account
        holder a per-skill progress report. The tutor is software. It is presented as a stylized
        character, it is labelled {AI_LABEL} throughout a session, and it says so when asked. It is
        not a person, a teacher of record, a substitute for a school, or a diagnostic or clinical
        service of any kind.
      </p>

      <h2>3. Coach mode</h2>
      <p>
        For a problem that looks like graded work, the tutor withholds the final answer until the
        learner has attempted at least one step, then offers a worked example and a similar problem.
        You agree not to present the tutor’s output as the learner’s own work where that is
        prohibited by a school or an examination body.
      </p>

      <h2>4. Accuracy, and the limits of what the report means</h2>
      <p>
        The tutor can be wrong. It checks arithmetic before stating it and admits uncertainty, but
        explanations, grading, and progress estimates are produced by a language model and are
        estimates. Mastery is shown as an estimate until an unaided check at least a day later
        confirms it. Use the report button in any session to flag an answer that is wrong or
        inappropriate; flagged sessions are reviewed by a person.
      </p>
      <p>
        <strong>
          The parent report is generated by software. It is not a professional assessment.
        </strong>{' '}
        Nothing in it is an evaluation by a teacher, a psychologist, an educational diagnostician,
        or any other qualified person. A per-skill number is an estimate drawn from a handful of
        check items. Do not rely on it for placement, for a diagnosis, for an IEP or 504 decision,
        or for any determination about a learner&rsquo;s ability or needs.
      </p>

      <h2>5. Plan, trial, and payment</h2>
      <p>
        One plan: {formatMoney(PLAN.priceCentsMonthly)} a month for up to {PLAN.learnerProfiles}{' '}
        learner profiles and {PLAN.pooledMinutesMonthly / 60} hours of tutoring a month, pooled
        across the profiles on the account. Learners aged 13 and over and adults get a{' '}
        {PLAN.trialMinutes13Plus}-minute free trial with no card. Under-13 profiles have no trial;
        the parent pays first, and the card transaction is intended to double as the identity check
        for parental consent, with a {PLAN.moneyBackDaysUnder13}-day money-back guarantee. That
        consent step is not built yet, and no under-13 profile can start a session until it is.
        Minutes are metered per session; a session stops when the minutes on the account run out,
        and the dashboard warns at {PLAN.warnAtPercent} percent. Payments are processed by Stripe
        under its own terms; we never see your full card number.
      </p>

      <h2>6. Cancellation and refunds</h2>
      <p>
        Cancel at any time from the billing page, through the customer portal, in one step. The
        subscription ends at the close of the paid period and is not renewed. Apart from the
        under-13 money-back guarantee above, fees for a period already started are not refunded
        unless the law where you live requires it.
      </p>

      <h2>7. Acceptable use</h2>
      <ul>
        <li>
          Do not use the service to obtain sexual, violent, or hateful content, or to try to make
          the tutor act as a person or a romantic partner.
        </li>
        <li>Do not enter another person’s personal information into a session.</li>
        <li>
          Do not share an account or a teen login with anyone outside the family on the account.
        </li>
        <li>Do not probe, overload, or reverse-engineer the service or its safety rules.</li>
      </ul>
      <p>
        We may suspend an account that breaks these rules. If a learner discloses self-harm or
        abuse, the tutor stops tutoring, offers crisis resources, and the session is flagged to the
        account holder and for review.
      </p>

      <h2>8. Your content and our software</h2>
      <p>
        Problems you upload, what you say, and what the tutor draws in response stay yours to export
        and delete. You give us the licence needed to run the service: to transcribe, store, and
        process that content for tutoring, the report, and safety review. We do not use it to train
        AI models. The software, the character, the voices, and the skill content are ours or our
        licensors’. The engine underneath is built on OpenMAIC, released under the MIT licence; its
        notice is kept in the source repository and in the site footer.
      </p>

      <h2>9. Termination and deletion</h2>
      <p>
        You can delete a learner profile or the whole account from the data page. Filing the request
        freezes the profile immediately, so nothing further is collected; erasure follows on the
        schedule in the privacy policy. We may close accounts that breach these terms, with notice
        where the law requires it.
      </p>

      <h2>10. Liability</h2>
      <p>
        The service is provided as is. To the extent the law allows, we are not liable for indirect
        losses, and our total liability for any claim is limited to the fees you paid in the three
        months before the claim arose. Nothing here limits rights that consumer law gives you and
        that cannot be waived.
      </p>

      <h2>11. Changes</h2>
      <p>
        We will post any change to these terms on this page with a new version number and, for a
        change that reduces your rights, notify the account holder by email at least 14 days before
        it takes effect.
      </p>

      <h2>12. Contact</h2>
      <p>
        For questions about these terms, write to the contact address published on the pricing page.
      </p>
    </LegalPage>
  );
}
