// THIRD_PARTY_NOTICES.md freshness — the class, not the instance.
//
// The 2026-08-18 audit found the notices file describing a dependency tree we
// had long since moved off. Wave 2 regenerated it, which fixed that day and
// nothing else: the file is generated by hand (`npm run notices`) and rots
// silently on the next bump, because a stale legal artifact throws no error,
// breaks no page, and looks exactly like a fresh one. This test is what makes
// regenerating it non-optional — it lives in test/*.test.mjs, so `npm test`
// picks it up with no wiring to forget.
//
// The audit is in scripts/checkNotices.mjs (also runnable on its own:
// `npm run notices:check`), with the reasoning for each check and for what it
// deliberately does NOT look at — no lockfile, no hash, no timestamp, so
// lockfile churn that moves no version fails nothing.
//
// The second test exists because a guard nobody has ever seen fail is a guard
// nobody knows works. It builds a deliberately rotten fixture and asserts the
// audit catches it.

import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { auditNotices } from '../scripts/checkNotices.mjs';

test('THIRD_PARTY_NOTICES.md matches package.json and the installed tree', (t) => {
  const { problems, sawInstalledTree, counts } = auditNotices();
  if (!sawInstalledTree) {
    // Explicit, never silent: without node_modules the version-liveness half
    // cannot run, and saying so beats a green tick that means less than it looks.
    t.diagnostic('node_modules absent — checked against package.json only, not installed versions.');
  }
  assert.deepEqual(
    problems, [],
    `THIRD_PARTY_NOTICES.md no longer describes what we ship. Regenerate it (npm run notices) and commit the result:\n  - ${problems.join('\n  - ')}`,
  );
  assert.ok(counts.direct > 0 && counts.blocks > 0, 'the audit found no dependencies at all — it is not reading the files it thinks it is');
});

test('the freshness guard actually fails on a rotten file', () => {
  const dir = mkdtempSync(join(tmpdir(), 'kaizen-notices-'));
  try {
    // A tree with widget@2.0.0 installed and a ghost@1.0.0 that never was.
    mkdirSync(join(dir, 'node_modules', 'widget'), { recursive: true });
    writeFileSync(join(dir, 'node_modules', 'widget', 'package.json'), JSON.stringify({ name: 'widget', version: '2.0.0' }));
    writeFileSync(join(dir, 'package.json'), JSON.stringify({
      dependencies: { widget: '^2.0.0', newcomer: '^1.0.0' },
    }));
    writeFileSync(join(dir, 'THIRD_PARTY_NOTICES.md'), [
      '## License summary (2 installed packages)',
      '',
      '## Direct dependencies — full license texts',
      '',
      '### widget@1.0.0 — MIT',
      '',
      '### ghost@1.0.0 — MIT',
      '',
      '## All installed packages',
      '',
      '| Package | Version | License |',
      '|---|---|---|',
      '| widget | 1.0.0 | MIT |',
      '| ghost | 1.0.0 | MIT |',
      '',
    ].join('\n'));

    const { problems, sawInstalledTree } = auditNotices({ root: dir });
    assert.equal(sawInstalledTree, true);
    const joined = problems.join('\n');
    assert.match(joined, /newcomer is a direct dependency with no license block/, 'a dependency added without regenerating must fail');
    assert.match(joined, /widget.*1\.0\.0.*2\.0\.0 installed/, 'a documented version that is not installed must fail');
    assert.match(joined, /ghost .*no longer a dependency/, 'a license text left behind by a removed dependency must fail');
    // ghost is not installed at all, so the row check stays quiet about it —
    // that tolerance is what keeps platform-optional packages from flaking.
    assert.doesNotMatch(joined, /not installed — npm run notices — ghost/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
