import type { CatalogueEntry } from "./types";

const rimasSilabasEs: CatalogueEntry = {
  id: "english-rhymes-syllables-es",
  title: "Rimas y sílabas",
  summary: "Escucha palabras que riman, inventa rimas y aplaude las sílabas.",
  subject: "english",
  grade: "K",
  locale: "es",
  lessons: [
    {
      id: "what-rhymes",
      title: "Palabras que riman",
      summary: "Las palabras que riman suenan igual al final.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Palabras que riman",
          blocks: [
            { type: "text", text: "Di gato. Ahora di pato." },
            { type: "text", text: "Suenan igual al final. Gato y pato riman." },
            {
              type: "points",
              items: ["Las palabras que riman suenan igual al final.", "Gato, pato y zapato riman.", "Gato y perro no riman."],
            },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Escucha el final",
          blocks: [
            { type: "text", text: "Di luna y cuna. Riman." },
            { type: "text", text: "Ahora di luna y lobo. Empiezan igual." },
            { type: "text", text: "Empezar igual no es rimar. La rima está al final." },
            { type: "points", items: ["Luna y cuna: riman.", "Luna y lobo: no riman."] },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "¿Rima con gato?",
          prompt: "Di cada palabra. ¿Rima con gato?",
          widget: {
            kind: "sorter",
            categories: ["Rima con gato", "No rima"],
            items: [
              { id: "pato", text: "pato", answer: 0 },
              { id: "sol", text: "sol", answer: 1 },
              { id: "zapato", text: "zapato", answer: 0 },
              { id: "luna", text: "luna", answer: 1 },
              { id: "plato", text: "plato", answer: 0 },
              { id: "mesa", text: "mesa", answer: 1 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué palabra rima con sol?",
              choices: ["caracol", "silla", "pez"],
              answer: 0,
              hint: "Di sol. Luego di cada palabra. Escucha el final.",
              explain: "Sol y caracol suenan igual al final. Riman.",
            },
            {
              id: "q2",
              prompt: "¿Riman luna y cuna?",
              choices: ["Sí", "No"],
              answer: 0,
              hint: "Di luna y luego cuna. ¿Terminan igual?",
              explain: "Luna y cuna suenan igual al final. Riman.",
            },
            {
              id: "q3",
              prompt: "¿Riman mesa y mano?",
              choices: ["Sí", "No"],
              answer: 1,
              hint: "Para rimar, tienen que sonar igual al final.",
              explain: "Mesa y mano empiezan igual, pero terminan distinto. No riman.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Busca rimas en casa",
          brief: "Busca cosas en tu casa que rimen.",
          steps: [
            "Elige un juguete, como un pato.",
            "Di su nombre en voz alta.",
            "Busca palabras que rimen: pato, gato, plato.",
            "También valen palabras inventadas, si riman.",
            "Elige dos juguetes más. Busca una rima para cada uno.",
          ],
        },
      ],
    },
    {
      id: "make-rhymes",
      title: "Inventa rimas",
      summary: "Deja igual el final de una palabra. Cambia el principio.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Cambia el principio",
          blocks: [
            { type: "text", text: "Empieza con ratón." },
            { type: "text", text: "Cambia el principio. Ratón se vuelve jabón o botón." },
            { type: "text", text: "El final se queda igual. Por eso riman." },
            { type: "points", items: ["ratón, jabón, botón, camión", "rana, manzana, ventana, campana"] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Rimas en una canción",
          blocks: [
            { type: "text", text: "Escucha esta canción tradicional." },
            { type: "text", text: "Los pollitos dicen pío, pío, pío." },
            { type: "text", text: "Cuando tienen hambre, cuando tienen frío." },
            { type: "text", text: "Pío y frío riman. Suenan igual al final." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "¿Ratón o rana?",
          prompt: "Di cada palabra. ¿Rima con ratón o con rana?",
          widget: {
            kind: "sorter",
            categories: ["Rima con ratón", "Rima con rana"],
            items: [
              { id: "jabon", text: "jabón", answer: 0 },
              { id: "manzana", text: "manzana", answer: 1 },
              { id: "camion", text: "camión", answer: 0 },
              { id: "ventana", text: "ventana", answer: 1 },
              { id: "boton", text: "botón", answer: 0 },
              { id: "campana", text: "campana", answer: 1 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué palabra rima con ratón?",
              choices: ["jabón", "rata", "rueda"],
              answer: 0,
              hint: "Di ratón despacio. Escucha el final.",
              explain: "Jabón rima con ratón. Rata y rueda empiezan igual, pero terminan distinto.",
            },
            {
              id: "q2",
              prompt: "Los pollitos dicen pío cuando tienen ___. ¿Qué palabra rima con pío?",
              choices: ["frío", "sueño", "sed"],
              answer: 0,
              hint: "Di pío. Luego prueba cada palabra.",
              explain: "Frío rima con pío. Así dice la canción.",
            },
            {
              id: "q3",
              prompt: "Inventa una rima para gato. ¿Cuál sirve?",
              choices: ["pato", "gota", "goma"],
              answer: 0,
              hint: "Deja igual el final de gato. Cambia solo el principio.",
              explain: "Pato rima con gato. Gota y goma empiezan igual, pero no riman.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Cadena de rimas",
          brief: "Juega a las rimas con un adulto.",
          steps: [
            "Siéntate con un adulto.",
            "Una persona dice una palabra, como sol.",
            "Por turnos, digan palabras que rimen.",
            "También valen palabras inventadas.",
            "Cuando no se les ocurra otra, elijan otra palabra.",
          ],
        },
      ],
    },
    {
      id: "clap-syllables",
      title: "Aplaude las sílabas",
      summary: "Las palabras tienen golpes llamados sílabas. Aplaude cada golpe.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Las palabras tienen golpes",
          blocks: [
            { type: "text", text: "Di sol. Da una palmada al decirlo." },
            { type: "visual", visual: { kind: "dots", groups: [1] }, alt: "Un punto. Sol tiene una palmada." },
            { type: "text", text: "Di ca-sa. Da dos palmadas: ca, sa." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1] }, alt: "Dos puntos, uno para ca y otro para sa. Casa tiene dos palmadas." },
            { type: "text", text: "Cada palmada es una sílaba." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Más palmadas",
          blocks: [
            { type: "text", text: "Pe-lo-ta tiene tres sílabas." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1, 1] }, alt: "Tres puntos, para pe, lo y ta." },
            { type: "text", text: "Ma-ri-po-sa tiene cuatro sílabas." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1, 1, 1] }, alt: "Cuatro puntos, para ma, ri, po y sa." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Las sílabas de tortuga",
          prompt: "Di tortuga. Da una palmada por cada sílaba. Mueve el marcador al número de palmadas.",
          widget: { kind: "number-line", min: 0, max: 5, step: 1, start: 0, target: 3 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Ordena por sílabas",
          prompt: "Di cada palabra y aplaude. ¿Cuántas sílabas tiene?",
          widget: {
            kind: "sorter",
            categories: ["Una sílaba", "Dos sílabas", "Tres sílabas"],
            items: [
              { id: "pan", text: "pan", answer: 0 },
              { id: "mesa", text: "mesa", answer: 1 },
              { id: "zapato", text: "zapato", answer: 2 },
              { id: "flor", text: "flor", answer: 0 },
              { id: "gato", text: "gato", answer: 1 },
              { id: "conejo", text: "conejo", answer: 2 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuántas sílabas tiene luna?",
              choices: ["1", "2", "3"],
              answer: 1,
              hint: "Di lu-na. Da una palmada por cada parte.",
              explain: "Lu-na tiene dos partes. Tiene 2 sílabas.",
            },
            {
              id: "q2",
              prompt: "¿Qué palabra tiene una sola sílaba?",
              choices: ["pez", "perro", "pescado"],
              answer: 0,
              hint: "Aplaude cada palabra. ¿Cuál termina más rápido?",
              explain: "Pez tiene 1 sílaba. Pe-rro tiene 2. Pes-ca-do tiene 3.",
            },
            {
              id: "q3",
              prompt: "Pon la mano bajo la barbilla. Di elefante. ¿Cuántas veces baja la barbilla?",
              choices: ["2", "3", "4"],
              answer: 2,
              hint: "Di e-le-fan-te despacio. Siente cómo se mueve la barbilla.",
              explain: "E-le-fan-te tiene cuatro sílabas. La barbilla baja una vez por cada una.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Aplaude los nombres",
          brief: "Aplaude los nombres de las personas que conoces.",
          steps: [
            "Di tu nombre. Da una palmada por cada sílaba.",
            "Aplaude los nombres de tu familia.",
            "¿Qué nombre tiene más palmadas?",
            "Aplaude los nombres de tres comidas de tu cocina.",
          ],
        },
      ],
    },
    {
      id: "rhyme-and-beat",
      title: "Rimas y palmadas en un poema",
      summary: "Busca las rimas de un poema corto. Aplaude palabras largas.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Los poemas juegan con los sonidos",
          blocks: [
            { type: "text", text: "Muchos poemas tienen palabras que riman." },
            { type: "text", text: "Los poemas también tienen ritmo. Puedes aplaudir al leerlos." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Escucha: Mi gato",
          blocks: [
            { type: "text", text: "Mi gato tiene un zapato." },
            { type: "text", text: "Mi pato tiene un plato." },
            { type: "text", text: "Mi ratón tiene un botón." },
            { type: "points", items: ["Gato, zapato, pato y plato riman.", "Ratón y botón riman."] },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Rimas del poema",
          prompt: "Di cada palabra. ¿Rima con pato o con botón?",
          widget: {
            kind: "sorter",
            categories: ["Rima con pato", "Rima con botón"],
            items: [
              { id: "zapato", text: "zapato", answer: 0 },
              { id: "camion", text: "camión", answer: 1 },
              { id: "gato", text: "gato", answer: 0 },
              { id: "jabon", text: "jabón", answer: 1 },
              { id: "plato", text: "plato", answer: 0 },
              { id: "corazon", text: "corazón", answer: 1 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Aplaude una palabra larga",
          prompt: "Di cocodrilo. Da una palmada por cada sílaba. Mueve el marcador al número de palmadas.",
          widget: { kind: "number-line", min: 0, max: 5, step: 1, start: 0, target: 4 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué palabra rima con plato?",
              choices: ["gato", "plata", "pluma"],
              answer: 0,
              hint: "Di plato. Escucha el final.",
              explain: "Gato rima con plato. Plata y pluma empiezan parecido, pero no riman.",
            },
            {
              id: "q2",
              prompt: "¿Qué pareja rima?",
              choices: ["ratón y botón", "ratón y rana", "pato y perro"],
              answer: 0,
              hint: "La rima está al final, no al principio.",
              explain: "Ratón y botón suenan igual al final. Las otras parejas solo empiezan igual.",
            },
            {
              id: "q3",
              prompt: "¿Cuántas sílabas tiene zapato?",
              choices: ["2", "3", "4"],
              answer: 1,
              hint: "Di za-pa-to. Da una palmada por cada parte.",
              explain: "Za-pa-to tiene tres partes. Tiene 3 sílabas.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Haz un libro de rimas",
          brief: "Haz un librito de parejas que riman.",
          steps: [
            "Dobla una hoja de papel por la mitad.",
            "Elige dos palabras que rimen, como luna y cuna.",
            "Dibuja una en cada lado.",
            "Di las dos palabras. Aplaude cada una.",
            "Haz más páginas con otras rimas.",
          ],
        },
      ],
    },
  ],
};

export { practice } from "./english-rhymes-syllables";

export default rimasSilabasEs;
