import type { CatalogueEntry } from "./types";

const rhymesSyllables: CatalogueEntry = {
  id: "english-rhymes-syllables",
  title: "Rhymes and syllables",
  summary: "Hear rhymes, make your own, and clap each syllable.",
  subject: "english",
  grade: "K",
  locale: "en",
  lessons: [
    {
      id: "what-rhymes",
      title: "Words that rhyme",
      summary: "Rhyming words sound the same at the end.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Rhyming words",
          blocks: [
            { type: "text", text: "Say cat. Now say hat." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1] }, alt: "Two dots side by side. One is for cat, one for hat." },
            { type: "text", text: "Touch a dot as you say each word." },
            { type: "text", text: "They sound the same at the end. Cat and hat rhyme." },
            {
              type: "points",
              items: ["Rhyming words sound the same at the end.", "Cat, hat, mat and bat all rhyme.", "Cat and dog do not rhyme."],
            },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Listen to the end",
          blocks: [
            { type: "text", text: "Say bee and tree. They rhyme." },
            { type: "text", text: "Now say bee and bus. They start the same." },
            { type: "text", text: "Starting the same is not rhyming. Rhymes match at the end." },
            { type: "points", items: ["Bee and tree: they rhyme.", "Bee and bus: they do not rhyme."] },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Does it rhyme with cat?",
          prompt: "Say each word. Does it rhyme with cat?",
          widget: {
            kind: "sorter",
            categories: ["Rhymes with cat", "Does not rhyme"],
            items: [
              { id: "hat", text: "hat", answer: 0 },
              { id: "dog", text: "dog", answer: 1 },
              { id: "bat", text: "bat", answer: 0 },
              { id: "car", text: "car", answer: 1 },
              { id: "mat", text: "mat", answer: 0 },
              { id: "cup", text: "cup", answer: 1 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which word rhymes with bee?",
              choices: ["bus", "cake", "tree"],
              answer: 2,
              hint: "Say bee. Then say each word. Listen to the end.",
              explain: "Bee and tree sound the same at the end. They rhyme.",
            },
            {
              id: "q2",
              prompt: "Do sun and fun rhyme?",
              choices: ["Yes", "No"],
              answer: 0,
              hint: "Say sun, then fun. Do the ends match?",
              explain: "Sun and fun sound the same at the end. They rhyme.",
            },
            {
              id: "q3",
              prompt: "Do dog and duck rhyme?",
              choices: ["Yes", "No"],
              answer: 1,
              hint: "Rhymes match at the end, not the start.",
              explain: "Dog and duck start the same. Their ends are different. They do not rhyme.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Rhyme hunt",
          brief: "Look for things at home that rhyme.",
          steps: [
            "Pick a toy, like a car.",
            "Say its name out loud.",
            "Think of words that rhyme: car, star, jar.",
            "Silly words count too: car, zar.",
            "Pick two more toys. Find a rhyme for each.",
          ],
        },
      ],
    },
    {
      id: "make-rhymes",
      title: "Make a rhyme",
      summary: "Keep the end of a word. Change the first sound.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Change the first sound",
          blocks: [
            { type: "text", text: "Start with bug." },
            { type: "text", text: "Change the first sound. Bug becomes hug, mug or rug." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1, 1, 1] }, alt: "Four dots in a row. One each for bug, hug, mug and rug." },
            { type: "text", text: "Touch each dot and say its word." },
            { type: "text", text: "The end stays the same, so they all rhyme." },
            { type: "points", items: ["bug, hug, mug, rug", "pig, wig, dig, big"] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Rhymes in an old song",
          blocks: [
            { type: "text", text: "Listen to this old rhyme." },
            { type: "text", text: "Hickory, dickory, dock. The mouse ran up the clock." },
            { type: "text", text: "Dock and clock rhyme. They sound the same at the end." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Bug or pig?",
          prompt: "Say each word. Does it rhyme with bug or with pig?",
          widget: {
            kind: "sorter",
            categories: ["Rhymes with bug", "Rhymes with pig"],
            items: [
              { id: "hug", text: "hug", answer: 0 },
              { id: "wig", text: "wig", answer: 1 },
              { id: "rug", text: "rug", answer: 0 },
              { id: "dig", text: "dig", answer: 1 },
              { id: "mug", text: "mug", answer: 0 },
              { id: "big", text: "big", answer: 1 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which word rhymes with bug?",
              choices: ["bag", "hug", "big"],
              answer: 1,
              hint: "Say bug slowly. Listen to the end.",
              explain: "Hug rhymes with bug. Bag and big start like bug, but end differently.",
            },
            {
              id: "q2",
              prompt: "The mouse ran up the ___. Which word rhymes with dock?",
              choices: ["chair", "tree", "clock"],
              answer: 2,
              hint: "Say dock. Then try each word after it.",
              explain: "Clock rhymes with dock. That is the word in the old rhyme.",
            },
            {
              id: "q3",
              prompt: "Make a rhyme for pig. Which one works?",
              choices: ["wig", "pin", "pan"],
              answer: 0,
              hint: "Keep the end of pig. Change only the first sound.",
              explain: "Wig keeps the end of pig. Pin and pan change the end. They do not rhyme.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Rhyme chain",
          brief: "Play a rhyming game with a grown-up.",
          steps: [
            "Sit with a grown-up.",
            "One of you says a word, like cat.",
            "Take turns saying a word that rhymes.",
            "Silly words are fine, like zat.",
            "When you run out, pick a new word.",
          ],
        },
      ],
    },
    {
      id: "clap-syllables",
      title: "Clap the syllables",
      summary: "Words have beats called syllables. Clap once for each beat.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Words have beats",
          blocks: [
            { type: "text", text: "Say dog. Clap once as you say it." },
            { type: "visual", visual: { kind: "dots", groups: [1] }, alt: "One dot. Dog has one clap." },
            { type: "text", text: "Say table. Clap twice, once for each part." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1] }, alt: "Two dots, one for each part of table. Table has two claps." },
            { type: "text", text: "Each clap is one syllable." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "More claps",
          blocks: [
            { type: "text", text: "Say butterfly slowly. It has three claps." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1, 1] }, alt: "Three dots, one for each clap in butterfly." },
            { type: "text", text: "Say watermelon slowly. It has four claps." },
            { type: "visual", visual: { kind: "dots", groups: [1, 1, 1, 1] }, alt: "Four dots, one for each clap in watermelon." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Claps in banana",
          prompt: "Say banana. Clap each part. Move the marker to the number of claps.",
          widget: { kind: "number-line", min: 0, max: 5, step: 1, start: 0, target: 3 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Sort by claps",
          prompt: "Say each word and clap. How many claps?",
          widget: {
            kind: "sorter",
            categories: ["1 clap", "2 claps", "3 claps"],
            items: [
              { id: "fish", text: "fish", answer: 0 },
              { id: "rabbit", text: "rabbit", answer: 1 },
              { id: "tomato", text: "tomato", answer: 2 },
              { id: "sun", text: "sun", answer: 0 },
              { id: "apple", text: "apple", answer: 1 },
              { id: "elephant", text: "elephant", answer: 2 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "How many claps in pizza?",
              choices: ["1", "2", "3"],
              answer: 1,
              hint: "Say pizza and clap each part. Count your claps.",
              explain: "Piz-za has two parts. That is 2 claps.",
            },
            {
              id: "q2",
              prompt: "Which word has just one clap?",
              choices: ["kitten", "caterpillar", "cat"],
              answer: 2,
              hint: "Clap each word. Which one is done fastest?",
              explain: "Cat has 1 clap. Kit-ten has 2. Cat-er-pil-lar has 4.",
            },
            {
              id: "q3",
              prompt: "Put a hand under your chin. Say tiger. How many times does your chin drop?",
              choices: ["2", "3", "4"],
              answer: 0,
              hint: "Say tiger slowly. Count each time your chin drops.",
              explain: "Ti-ger has two syllables. Your chin drops once for each one.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Clap your names",
          brief: "Clap the names of people you know.",
          steps: [
            "Say your name. Clap once for each part.",
            "Clap the names of people at home.",
            "Whose name has the most claps?",
            "Clap the names of three foods in your kitchen.",
          ],
        },
      ],
    },
    {
      id: "rhyme-and-beat",
      title: "Rhymes and claps in a poem",
      summary: "Find rhymes in a short poem. Clap long words.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Poems play with sounds",
          blocks: [
            { type: "text", text: "Many poems use rhyming words." },
            { type: "text", text: "Poems have a beat, too. You can clap along." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Listen: Frog and Dog",
          blocks: [
            { type: "text", text: "A frog sat on a log." },
            { type: "text", text: "He sang a song to a dog." },
            { type: "text", text: "The dog said, “Hop.”" },
            { type: "text", text: "The frog said, “Stop.”" },
            { type: "points", items: ["Frog, log and dog rhyme.", "Hop and stop rhyme."] },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Rhymes from the poem",
          prompt: "Say each word. Does it rhyme with frog or with hop?",
          widget: {
            kind: "sorter",
            categories: ["Rhymes with frog", "Rhymes with hop"],
            items: [
              { id: "log", text: "log", answer: 0 },
              { id: "stop", text: "stop", answer: 1 },
              { id: "dog", text: "dog", answer: 0 },
              { id: "mop", text: "mop", answer: 1 },
              { id: "fog", text: "fog", answer: 0 },
              { id: "top", text: "top", answer: 1 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Clap a long word",
          prompt: "Say alligator. Clap each part. Move the marker to the number of claps.",
          widget: { kind: "number-line", min: 0, max: 5, step: 1, start: 0, target: 4 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which word rhymes with log?",
              choices: ["fog", "leg", "lip"],
              answer: 0,
              hint: "Say log. Listen to the end.",
              explain: "Fog rhymes with log. Leg and lip start like log, but end differently.",
            },
            {
              id: "q2",
              prompt: "Which pair rhymes?",
              choices: ["hop and hat", "dog and duck", "hop and stop"],
              answer: 2,
              hint: "Rhymes match at the end, not the start.",
              explain: "Hop and stop sound the same at the end. The other pairs only match at the start.",
            },
            {
              id: "q3",
              prompt: "How many claps in rainbow?",
              choices: ["1", "2", "3"],
              answer: 1,
              hint: "Say rainbow and clap each part. Count your claps.",
              explain: "Rain-bow has two parts. That is 2 claps.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Make a rhyme book",
          brief: "Make a little book of rhyming pairs.",
          steps: [
            "Fold a sheet of paper in half.",
            "Pick two words that rhyme, like bee and tree.",
            "Draw one on each side.",
            "Say both words. Clap each one.",
            "Make more pages with new rhymes.",
          ],
        },
      ],
    },
  ],
};

/** Practice on the skill map that fits each lesson (lesson id → skill ids). Not linked from the lesson screen yet. */
export const practice: Record<string, string[]> = {
  "what-rhymes": ["e.rhyme"],
  "make-rhymes": ["e.rhyme", "e.word.families"],
  "clap-syllables": ["e.syllables"],
  "rhyme-and-beat": ["e.rhyme", "e.syllables"],
};

export default rhymesSyllables;
