import type { CatalogueEntry } from "./types";

const partesOracionEs: CatalogueEntry = {
  id: "english-parts-of-speech-es",
  title: "Sustantivos, verbos y adjetivos",
  summary: "Los sustantivos nombran. Los verbos dicen qué pasa. Los adjetivos describen.",
  subject: "english",
  grade: "2",
  locale: "es",
  lessons: [
    {
      id: "nouns",
      title: "Los sustantivos",
      summary: "Un sustantivo nombra personas, animales, lugares o cosas.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "¿Qué es un sustantivo?",
          blocks: [
            { type: "text", text: "Un sustantivo nombra personas, animales, lugares o cosas." },
            {
              type: "points",
              items: [
                "Personas: maestra, papá, bebé",
                "Animales: perro, rana, abeja",
                "Lugares: parque, escuela, cocina",
                "Cosas: pelota, manzana, silla",
              ],
            },
            { type: "text", text: "Los nombres como Ana y México también son sustantivos." },
            { type: "text", text: "Empiezan con mayúscula." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "¿Es un sustantivo?",
          blocks: [
            { type: "text", text: "¿Nombra una persona, un animal, un lugar o una cosa?" },
            { type: "text", text: "Lámpara nombra una cosa. Es un sustantivo." },
            { type: "text", text: "También puedes contar: “dos lámparas” tiene sentido." },
            { type: "text", text: "“Dos come” no tiene sentido. Come no es un sustantivo." },
            { type: "points", items: ["Esta prueba sirve para muchos sustantivos.", "Ana no se puede contar, pero también es un sustantivo."] },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "¿El o la?",
          blocks: [
            { type: "text", text: "En español, los sustantivos son masculinos o femeninos." },
            { type: "text", text: "Decimos el perro y la mesa." },
            {
              type: "points",
              items: ["Muchos que terminan en o van con el.", "Muchos que terminan en a van con la.", "Pero hay sorpresas: decimos la mano y el día."],
            },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Persona, lugar o cosa?",
          prompt: "Clasifica cada sustantivo. ¿Es una persona, un lugar o una cosa?",
          widget: {
            kind: "sorter",
            categories: ["Persona", "Lugar", "Cosa"],
            items: [
              { id: "doctora", text: "doctora", answer: 0 },
              { id: "cocina", text: "cocina", answer: 1 },
              { id: "lapiz", text: "lápiz", answer: 2 },
              { id: "bebe", text: "bebé", answer: 0 },
              { id: "playa", text: "playa", answer: 1 },
              { id: "cuchara", text: "cuchara", answer: 2 },
            ],
          },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿Va con el o con la?",
          prompt: "Di cada palabra con el y con la. ¿Cuál suena bien?",
          widget: {
            kind: "sorter",
            categories: ["Va con el", "Va con la"],
            items: [
              { id: "perro", text: "perro", answer: 0 },
              { id: "mesa", text: "mesa", answer: 1 },
              { id: "libro", text: "libro", answer: 0 },
              { id: "casa", text: "casa", answer: 1 },
              { id: "lapiz", text: "lápiz", answer: 0 },
              { id: "flor", text: "flor", answer: 1 },
              { id: "mano", text: "mano", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué palabra es un sustantivo?",
              choices: ["come", "lámpara", "muy"],
              answer: 1,
              hint: "¿Cuál nombra una persona, un lugar o una cosa?",
              explain: "“Dos lámparas” tiene sentido, y una lámpara es una cosa. Come dice lo que alguien hace. Muy dice cuánto.",
            },
            {
              id: "q2",
              prompt: "Sofía juega en el parque. ¿Qué palabra nombra un lugar?",
              choices: ["Sofía", "juega", "parque"],
              answer: 2,
              hint: "Un lugar es un sitio adonde puedes ir.",
              explain: "El parque es un lugar. Sofía es una persona. Juega dice lo que hace.",
            },
            {
              id: "q3",
              prompt: "¿Qué palabra va con la?",
              choices: ["mano", "día", "perro"],
              answer: 0,
              hint: "Di cada palabra con la y con el. ¿Cuál suena bien?",
              explain: "Decimos la mano, aunque termina en o. Decimos el día y el perro.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Busca sustantivos en casa",
          brief: "Busca sustantivos por toda tu casa.",
          steps: [
            "Dobla una hoja en tres columnas.",
            "Escribe arriba: persona, lugar, cosa.",
            "Recorre tu casa. Escribe o dibuja sustantivos.",
            "Busca por lo menos tres para cada columna.",
            "Lee tu lista a alguien. ¿Está de acuerdo?",
          ],
        },
      ],
    },
    {
      id: "verbs",
      title: "Los verbos",
      summary: "Un verbo dice lo que alguien o algo hace.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "¿Qué es un verbo?",
          blocks: [
            { type: "text", text: "Un verbo dice lo que alguien o algo hace." },
            { type: "points", items: ["El perro corre.", "Los pájaros cantan.", "Mamá lee."] },
            { type: "text", text: "Corre, cantan y lee son verbos." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "El nombre del verbo",
          blocks: [
            { type: "text", text: "El nombre de un verbo se llama infinitivo." },
            {
              type: "points",
              items: ["Unos terminan en ar: cantar, saltar.", "Otros terminan en er: comer, correr.", "Otros terminan en ir: vivir, subir."],
            },
            { type: "text", text: "En una oración, el verbo cambia." },
            { type: "text", text: "Yo canto, tú cantas, ella canta." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "¿Sustantivo o verbo?",
          prompt: "Clasifica cada palabra. ¿Es un sustantivo o un verbo?",
          widget: {
            kind: "sorter",
            categories: ["Sustantivo", "Verbo"],
            items: [
              { id: "cantar", text: "cantar", answer: 1 },
              { id: "arbol", text: "árbol", answer: 0 },
              { id: "escribir", text: "escribir", answer: 1 },
              { id: "gatito", text: "gatito", answer: 0 },
              { id: "traer", text: "traer", answer: 1 },
              { id: "ventana", text: "ventana", answer: 0 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Como cantar, comer o vivir?",
          prompt: "Mira cómo termina cada verbo. ¿Termina como cantar, comer o vivir?",
          widget: {
            kind: "sorter",
            categories: ["Como cantar", "Como comer", "Como vivir"],
            items: [
              { id: "bailar", text: "bailar", answer: 0 },
              { id: "correr", text: "correr", answer: 1 },
              { id: "escribir", text: "escribir", answer: 2 },
              { id: "saltar", text: "saltar", answer: 0 },
              { id: "beber", text: "beber", answer: 1 },
              { id: "subir", text: "subir", answer: 2 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "El bebé duerme en su cuna. ¿Qué palabra es el verbo?",
              choices: ["bebé", "cuna", "duerme"],
              answer: 2,
              hint: "¿De quién habla la oración? ¿Qué hace el bebé?",
              explain: "Duerme dice lo que hace el bebé. Por eso es el verbo.",
            },
            {
              id: "q2",
              prompt: "¿Qué palabra es un verbo?",
              choices: ["dibujar", "plátano", "suave"],
              answer: 0,
              hint: "Prueba cada palabra después de “Yo puedo”.",
              explain: "“Yo puedo dibujar” tiene sentido. Dibujar es algo que haces.",
            },
            {
              id: "q3",
              prompt: "¿Qué verbo termina como comer?",
              choices: ["cantar", "correr", "subir"],
              answer: 1,
              hint: "Fíjate en las dos últimas letras.",
              explain: "Correr y comer terminan en er. Cantar termina en ar. Subir termina en ir.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Adivina el verbo",
          brief: "Actúa verbos y adivínalos en familia.",
          steps: [
            "Escribe cinco verbos en papelitos: saltar, nadar, comer, dormir, leer.",
            "Mezcla los papelitos. Saca uno.",
            "Actúa el verbo sin hablar.",
            "Tu familia adivina el verbo.",
            "Túrnense. Agreguen verbos nuevos.",
          ],
        },
      ],
    },
    {
      id: "adjectives",
      title: "Los adjetivos",
      summary: "Un adjetivo dice cómo es un sustantivo.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "¿Qué es un adjetivo?",
          blocks: [
            { type: "text", text: "Un adjetivo dice cómo es un sustantivo." },
            { type: "points", items: ["Cómo es: un perro grande", "De qué color: una flor roja", "Cómo se siente: una manta suave"] },
            { type: "text", text: "Muchas veces va después del sustantivo: la casa grande." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "El adjetivo concuerda",
          blocks: [
            { type: "text", text: "En español, el adjetivo cambia para ir con el sustantivo." },
            { type: "points", items: ["Un gato negro. Una gata negra.", "Dos gatos negros. Dos gatas negras."] },
            { type: "text", text: "Algunos no cambian: niño feliz, niña feliz." },
            { type: "text", text: "Pero sí cambian en plural: niños felices." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "¿Sustantivo, verbo o adjetivo?",
          prompt: "Lee: El perro hambriento come un hueso grande. Clasifica cada palabra.",
          widget: {
            kind: "sorter",
            categories: ["Sustantivo", "Verbo", "Adjetivo"],
            items: [
              { id: "perro", text: "perro", answer: 0 },
              { id: "hambriento", text: "hambriento", answer: 2 },
              { id: "come", text: "come", answer: 1 },
              { id: "hueso", text: "hueso", answer: 0 },
              { id: "grande", text: "grande", answer: 2 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Niño, niña o los dos?",
          prompt: "¿Con quién va cada adjetivo?",
          widget: {
            kind: "sorter",
            categories: ["Va con niño", "Va con niña", "Va con los dos"],
            items: [
              { id: "alto", text: "alto", answer: 0 },
              { id: "alta", text: "alta", answer: 1 },
              { id: "contenta", text: "contenta", answer: 1 },
              { id: "contento", text: "contento", answer: 0 },
              { id: "feliz", text: "feliz", answer: 2 },
              { id: "amable", text: "amable", answer: 2 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Comimos un durazno jugoso. ¿Qué palabra es el adjetivo?",
              choices: ["jugoso", "Comimos", "durazno"],
              answer: 0,
              hint: "Busca primero el sustantivo. Luego busca cómo es.",
              explain: "Durazno es el sustantivo. Jugoso dice cómo es el durazno.",
            },
            {
              id: "q2",
              prompt: "¿Cuál está bien dicho?",
              choices: ["las flores amarillo", "la flores amarillas", "las flores amarillas"],
              answer: 2,
              hint: "Flores es femenino y plural. ¿Y las otras palabras?",
              explain: "Flores es femenino y plural. Las y amarillas también. Las tres concuerdan.",
            },
            {
              id: "q3",
              prompt: "La biblioteca está tranquila. ¿Qué palabra dice cómo está?",
              choices: ["biblioteca", "tranquila", "está"],
              answer: 1,
              hint: "¿Cómo está la biblioteca?",
              explain: "Tranquila describe la biblioteca. Aquí el adjetivo va después del verbo.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "La bolsa misteriosa",
          brief: "Describe con adjetivos un objeto escondido.",
          steps: [
            "Pide a un adulto que esconda algo en una bolsa.",
            "Toca el objeto sin mirar.",
            "Di tres adjetivos sobre él, como liso, frío, redondo.",
            "Adivina qué es. Luego míralo.",
            "Cambien. Ahora tú escondes algo.",
          ],
        },
      ],
    },
    {
      id: "sentence-parts",
      title: "Todo junto",
      summary: "Usa sustantivos, verbos y adjetivos para hacer mejores oraciones.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Quién y qué hace",
          blocks: [
            { type: "text", text: "Una oración dice quién hace algo y qué hace." },
            { type: "text", text: "Los pájaros cantan. Pájaros es el sustantivo. Cantan es el verbo." },
            { type: "points", items: ["Quién: muchas veces, un sustantivo.", "Qué hace: el verbo."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Agrega adjetivos",
          blocks: [
            { type: "text", text: "Empieza con poco: Los gatos duermen." },
            { type: "text", text: "Agrega un adjetivo: Los gatos gordos duermen." },
            { type: "text", text: "Agrega otro: Los gatos gordos y blancos duermen." },
            { type: "text", text: "Cada adjetivo te ayuda a imaginar a los gatos." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Clasifica las palabras",
          prompt: "Lee: La niña pequeña patea una pelota roja. Clasifica cada palabra.",
          widget: {
            kind: "sorter",
            categories: ["Sustantivo", "Verbo", "Adjetivo"],
            items: [
              { id: "nina", text: "niña", answer: 0 },
              { id: "pequena", text: "pequeña", answer: 2 },
              { id: "patea", text: "patea", answer: 1 },
              { id: "pelota", text: "pelota", answer: 0 },
              { id: "roja", text: "roja", answer: 2 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué oración tiene un adjetivo?",
              choices: ["El árbol se mueve.", "El árbol alto se mueve.", "Los árboles se mueven."],
              answer: 1,
              hint: "Busca una palabra que diga cómo es el árbol.",
              explain: "Alto describe al árbol. Las otras dos oraciones no tienen adjetivo.",
            },
            {
              id: "q2",
              prompt: "Dos caballos blancos corren rápido. ¿Qué palabra es el sustantivo?",
              choices: ["caballos", "blancos", "corren"],
              answer: 0,
              hint: "Pregunta: ¿de qué habla la oración?",
              explain: "Caballos es el sustantivo. Blancos dice cómo son. Corren dice qué hacen.",
            },
            {
              id: "q3",
              prompt: "El gatito ___ duerme. ¿Qué palabra va?",
              choices: ["salta", "peluda", "peludo"],
              answer: 2,
              hint: "Busca un adjetivo que vaya con gatito.",
              explain: "Peludo describe al gatito y concuerda con él. Peluda iría con gatita. Salta es un verbo.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Oraciones locas",
          brief: "Arma oraciones locas con tres montones de palabras.",
          steps: [
            "Haz tres montones de papelitos: sustantivos, verbos, adjetivos.",
            "Escribe cinco palabras para cada montón.",
            "Saca un sustantivo, un adjetivo y un verbo.",
            "Arma una oración, como: El cerdo morado canta.",
            "Revisa que el adjetivo concuerde con el sustantivo.",
            "Lee tu oración más loca a alguien.",
          ],
        },
      ],
    },
  ],
};

export { practice } from "./english-parts-of-speech";

export default partesOracionEs;
