import type { CatalogueEntry } from "./types";

const multiplicationEs: CatalogueEntry = {
  id: "math-multiplication-es",
  title: "Multiplicación: grupos iguales y arreglos",
  summary: "Los grupos iguales y los arreglos muestran qué es multiplicar. Cuenta de tanto en tanto y usa lo que ya sabes para hallar productos nuevos.",
  subject: "math",
  grade: "3",
  locale: "es",
  lessons: [
    {
      id: "equal-groups",
      title: "Grupos iguales",
      summary: "La multiplicación cuenta grupos iguales: el número de grupos por el número de cosas en cada grupo.",
      minutes: 12,
      practice: ["m.mult.groups"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Grupos del mismo tamaño",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [4, 4, 4] }, alt: "3 grupos de puntos con 4 puntos en cada grupo." },
            { type: "text", text: "Aquí hay 3 grupos. Cada grupo tiene 4 puntos." },
            { type: "text", text: "Puedes sumar: 4 + 4 + 4 = 12." },
            { type: "text", text: "O puedes multiplicar: 3 × 4 = 12. Se lee “3 por 4”." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Qué dice cada número",
          blocks: [
            {
              type: "points",
              items: [
                "El primer número dice cuántos grupos hay: 3.",
                "El segundo número dice cuántos hay en cada grupo: 4.",
                "El resultado se llama producto: 12 en total.",
              ],
            },
            { type: "text", text: "Puedes multiplicar cuando todos los grupos son del mismo tamaño." },
            { type: "text", text: "Si los grupos son de distinto tamaño, súmalos." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Cuenta de 5 en 5",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [5, 5, 5, 5] }, alt: "4 grupos de puntos con 5 puntos en cada grupo." },
            { type: "text", text: "Para hallar 4 × 5, cuenta de 5 en 5, una vez por cada grupo." },
            { type: "text", text: "5, 10, 15, 20. Así que 4 × 5 = 20." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Salta en grupos iguales",
          prompt: "Halla 6 × 3. Empieza en 0 y da 6 saltos de 3. ¿Dónde caes?",
          widget: { kind: "number-line", min: 0, max: 30, step: 3, start: 0, target: 18 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿Grupos iguales o no?",
          prompt: "¿Puedes multiplicar para hallar el total? Clasifica cada uno.",
          widget: {
            kind: "sorter",
            categories: ["Grupos iguales", "Grupos distintos"],
            items: [
              { id: "bags", text: "4 bolsas con 5 manzanas en cada bolsa", answer: 0 },
              { id: "boxes", text: "3 cajas: 6 crayones, 6 crayones y 6 crayones", answer: 0 },
              { id: "plates", text: "2 platos: uno con 3 galletas y otro con 5", answer: 1 },
              { id: "cars", text: "5 carros con 4 ruedas cada uno", answer: 0 },
              { id: "vases", text: "Un florero con 7 rosas y otro con 4 tulipanes", answer: 1 },
              { id: "tables", text: "6 mesas con 2 sillas en cada mesa", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Hay 5 floreros con 3 flores en cada uno. ¿Qué operación da el total?",
              choices: ["5 × 3", "5 + 3", "5 − 3"],
              answer: 0,
              hint: "¿Los grupos son del mismo tamaño? ¿Cuántos grupos hay?",
              explain: "Hay 5 grupos iguales de 3, así que el total es 5 × 3 = 15 flores.",
            },
            {
              id: "q2",
              prompt: "Hay 4 vasos con 6 lápices en cada uno. ¿Cuántos lápices hay?",
              choices: ["10", "20", "24"],
              answer: 2,
              hint: "Cuenta de 6 en 6, una vez por cada vaso.",
              explain: "6, 12, 18, 24. Así que 4 × 6 = 24 lápices. 4 + 6 = 10 suma los vasos con los lápices de un solo vaso. No cuenta todos los lápices.",
            },
            {
              id: "q3",
              prompt: "¿Qué situación corresponde a 2 × 7?",
              choices: ["2 bolsas con 7 canicas en cada una", "7 bolsas con 7 canicas en cada una", "Una bolsa con 2 canicas y otra con 7"],
              answer: 0,
              hint: "El primer número dice cuántos grupos hay. El segundo, cuántos hay en cada uno.",
              explain: "2 × 7 significa 2 grupos iguales con 7 en cada grupo.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Grupos iguales en casa",
          brief: "Busca grupos iguales en tu casa y escríbelos como multiplicación.",
          steps: [
            "Busca cosas que vienen en grupos iguales, como huevos en un cartón, ruedas en bicicletas o patas en sillas.",
            "Escoge una. Cuenta los grupos. Luego cuenta cuántos hay en un grupo.",
            "Escríbelo como multiplicación. Para 4 sillas con 4 patas cada una, escribe 4 × 4 = 16.",
            "Comprueba el producto contando de tanto en tanto.",
            "Forma tus propios grupos iguales con cucharas o monedas. Pide a alguien que escriba la multiplicación.",
          ],
        },
      ],
    },
    {
      id: "arrays",
      title: "Arreglos",
      summary: "Las filas iguales muestran grupos iguales. Girar un arreglo muestra que el orden no cambia el producto.",
      minutes: 12,
      practice: ["m.mult.groups", "m.mult.props"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Filas y columnas",
          blocks: [
            { type: "visual", visual: { kind: "array", rows: 3, cols: 5 }, alt: "Un arreglo de puntos con 3 filas y 5 puntos en cada fila." },
            { type: "text", text: "Un arreglo acomoda las cosas en filas iguales." },
            { type: "text", text: "Este arreglo tiene 3 filas de 5. Eso es 3 × 5 = 15." },
            { type: "points", items: ["Las filas van de lado a lado.", "Las columnas van de arriba abajo.", "Este arreglo también tiene 5 columnas de 3."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Gíralo",
          blocks: [
            { type: "visual", visual: { kind: "array", rows: 5, cols: 3 }, alt: "El mismo arreglo girado: 5 filas con 3 puntos en cada fila." },
            { type: "text", text: "Gira el arreglo. Ahora muestra 5 filas de 3." },
            { type: "text", text: "No se agregó ni se quitó ningún punto. Así que 5 × 3 = 15 también." },
            { type: "text", text: "Puedes multiplicar dos números en cualquier orden. El producto es el mismo." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Arreglos por todas partes",
          blocks: [
            { type: "text", text: "Los cartones de huevos, los moldes para pastelitos y algunas ventanas suelen ser arreglos." },
            {
              type: "visual",
              visual: { kind: "array", rows: 2, cols: 6 },
              alt: "Un arreglo de puntos con 2 filas y 6 puntos en cada fila, como un cartón de 12 huevos.",
            },
            { type: "text", text: "Un cartón de 12 huevos tiene 2 filas de 6: 2 × 6 = 12." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Cuenta las filas",
          prompt: "Un arreglo tiene 4 filas con 7 en cada fila. Salta de 7 en 7, un salto por fila. ¿Cuántos hay en total?",
          widget: { kind: "number-line", min: 0, max: 35, step: 7, start: 0, target: 28 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿El mismo producto?",
          prompt: "Un arreglo de 3 filas de 8 tiene 24 puntos. ¿Qué otros arreglos tienen 24 puntos? Clasifícalos.",
          widget: {
            kind: "sorter",
            categories: ["24 puntos", "No son 24 puntos"],
            items: [
              { id: "a8x3", text: "8 filas de 3", answer: 0 },
              { id: "a4x6", text: "4 filas de 6", answer: 0 },
              { id: "a3x7", text: "3 filas de 7", answer: 1 },
              { id: "a2x12", text: "2 filas de 12", answer: 0 },
              { id: "a5x5", text: "5 filas de 5", answer: 1 },
              { id: "a6x4", text: "6 filas de 4", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Un huerto tiene 4 filas de plantas. Cada fila tiene 6 plantas. ¿Cuántas plantas hay?",
              choices: ["10", "24", "46"],
              answer: 1,
              hint: "Cuenta de 6 en 6, una vez por cada fila.",
              explain: "6, 12, 18, 24. Así que 4 × 6 = 24 plantas.",
            },
            {
              id: "q2",
              prompt: "Andrés sabe que 7 × 3 = 21. ¿Cuánto es 3 × 7?",
              choices: ["10", "21", "37"],
              answer: 1,
              hint: "Imagina un arreglo de 7 filas de 3. Ahora gíralo.",
              explain: "Girar un arreglo no cambia cuántos puntos tiene. Así que 3 × 7 = 21 también.",
            },
            {
              id: "q3",
              prompt: "¿Qué arreglo tiene 12 puntos?",
              choices: ["2 filas de 5", "3 filas de 5", "3 filas de 4"],
              answer: 2,
              hint: "Multiplica el número de filas por cuántos hay en cada fila.",
              explain: "3 × 4 = 12. Los otros son 2 × 5 = 10 y 3 × 5 = 15.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Arma arreglos",
          brief: "Forma todos los arreglos que puedas con 12 cosas pequeñas.",
          steps: [
            "Cuenta 12 monedas, frijoles o bloques.",
            "Forma filas iguales. Prueba con 2 filas, luego con 3 y luego con 4.",
            "Para cada arreglo, escribe la multiplicación, como 2 × 6 = 12.",
            "Prueba con 5 filas. ¿Salen filas iguales?",
            "Dibuja tu arreglo favorito en papel y marca sus filas.",
          ],
        },
      ],
    },
    {
      id: "facts-patterns",
      title: "Las tablas del 2, del 5 y del 10",
      summary: "Usa patrones para multiplicar por 2, 5 y 10, y descubre qué pasa con el 0 y el 1.",
      minutes: 12,
      practice: ["m.mult.easy"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Por 2 es el doble",
          blocks: [
            { type: "visual", visual: { kind: "array", rows: 2, cols: 8 }, alt: "Un arreglo de puntos con 2 filas y 8 puntos en cada fila." },
            { type: "text", text: "2 × 8 significa 2 grupos de 8. Es el doble de 8." },
            { type: "text", text: "8 + 8 = 16, así que 2 × 8 = 16." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Por 5 y por 10",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 50, marks: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50] },
              alt: "Una recta numérica del 0 al 50 con una marca cada 5.",
            },
            {
              type: "points",
              items: [
                "Cuenta de 10 en 10: 10, 20, 30, 40. Todos terminan en 0.",
                "Cuenta de 5 en 5: 5, 10, 15, 20. Terminan en 5 o en 0.",
                "5 × 6 es la mitad de 10 × 6. La mitad de 60 es 30, así que 5 × 6 = 30.",
              ],
            },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "El cero y el uno",
          blocks: [
            { type: "text", text: "1 × 9 significa 1 grupo de 9. Eso es 9." },
            { type: "text", text: "0 × 9 significa 0 grupos de 9. Eso es 0." },
            { type: "points", items: ["Cualquier número por 1 da ese mismo número.", "Cualquier número por 0 da 0."] },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Cuenta de 5 en 5",
          prompt: "Halla 7 × 5. Cuenta de 5 en 5, 7 veces. ¿Dónde caes?",
          widget: { kind: "number-line", min: 0, max: 50, step: 5, start: 0, target: 35 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿Verdadero o falso?",
          prompt: "¿Cada multiplicación es verdadera o falsa? Clasifícalas.",
          widget: {
            kind: "sorter",
            categories: ["Verdadero", "Falso"],
            items: [
              { id: "f2x9", text: "2 × 9 = 18", answer: 0 },
              { id: "f5x7", text: "5 × 7 = 30", answer: 1 },
              { id: "f10x4", text: "10 × 4 = 40", answer: 0 },
              { id: "f0x6", text: "0 × 6 = 6", answer: 1 },
              { id: "f1x8", text: "1 × 8 = 8", answer: 0 },
              { id: "f5x8", text: "5 × 8 = 40", answer: 0 },
              { id: "f2x7", text: "2 × 7 = 15", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuánto es 5 × 9?",
              choices: ["14", "40", "45"],
              answer: 2,
              hint: "Halla primero 10 × 9. Luego saca la mitad.",
              explain: "10 × 9 = 90. La mitad de 90 es 45. Así que 5 × 9 = 45.",
            },
            {
              id: "q2",
              prompt: "Lucía tiene 0 cajas de crayones. Cada caja trae 8 crayones. ¿Cuántos crayones tiene?",
              choices: ["0", "8", "80"],
              answer: 0,
              hint: "¿Cuántos grupos hay?",
              explain: "0 grupos de 8 son 0. Así que 0 × 8 = 0.",
            },
            {
              id: "q3",
              prompt: "¿Qué número dices al contar de 5 en 5?",
              choices: ["32", "35", "53"],
              answer: 1,
              hint: "Cuenta de 5 en 5 desde 5: 5, 10, 15… Sigue. ¿Cuál de estos números dices?",
              explain: "35 termina en 5, y 5 × 7 = 35. 32 y 53 terminan en 2 y en 3.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Cuenta monedas de 5 y de 10",
          brief: "Usa monedas de 5 y de 10 centavos para practicar por 5 y por 10.",
          steps: [
            "Pon 6 monedas de 5 centavos en fila. También sirven monedas de papel.",
            "Cuenta de 5 en 5 para hallar el total. Escribe 6 × 5 = ___.",
            "Haz lo mismo con 6 monedas de 10 centavos.",
            "Compara los totales. ¿6 × 5 es la mitad de 6 × 10?",
            "Cuenta los pares de zapatos junto a la puerta. ¿Cuántos zapatos son? Escríbelo como ___ × 2.",
          ],
        },
      ],
    },
    {
      id: "break-apart",
      title: "Descomponer para multiplicar",
      summary: "Separa una multiplicación que no sabes en dos que sí sabes, y luego suma.",
      minutes: 14,
      // Not m.mult.props: its × 9 items call 9 the number of groups, the reverse of this course's rule.
      practice: ["m.mult.facts"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Separa el arreglo",
          blocks: [
            { type: "visual", visual: { kind: "array", rows: 6, cols: 7 }, alt: "Un arreglo de puntos con 6 filas y 7 puntos en cada fila." },
            { type: "text", text: "Quizás todavía no sabes 6 × 7. Separa cada fila de 7 en 5 y 2." },
            { type: "visual", visual: { kind: "array", rows: 6, cols: 5 }, alt: "La primera parte: 6 filas de 5 puntos." },
            { type: "visual", visual: { kind: "array", rows: 6, cols: 2 }, alt: "La segunda parte: 6 filas de 2 puntos." },
            { type: "text", text: "6 × 5 = 30 y 6 × 2 = 12. Súmalos: 30 + 12 = 42." },
            { type: "text", text: "Así que 6 × 7 = 42." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Usa lo que ya sabes",
          blocks: [
            {
              type: "points",
              items: [
                "Con el 5: 7 × 8 = (7 × 5) + (7 × 3) = 35 + 21 = 56.",
                "Con dobles: 4 × 6 es el doble de 2 × 6. El doble de 12 es 24.",
                "Con el 10: 9 × 6 es un grupo de 6 menos que 10 × 6. 60 − 6 = 54.",
              ],
            },
            { type: "text", text: "Los paréntesis muestran qué partes se multiplican primero. Después se suman." },
            { type: "text", text: "Escoge la forma de separar que use multiplicaciones que ya sabes." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Un grupo más",
          prompt: "Halla 6 × 8. El marcador empieza en 40, que es 5 × 8. Salta 8 más para sumar otro grupo de 8.",
          widget: { kind: "number-line", min: 30, max: 60, step: 1, start: 40, target: 48 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Qué formas funcionan?",
          prompt: "¿Cuáles son iguales a 7 × 6? Clasifica cada una.",
          widget: {
            kind: "sorter",
            categories: ["Igual a 7 × 6", "No es igual a 7 × 6"],
            items: [
              { id: "b51", text: "(7 × 5) + (7 × 1)", answer: 0 },
              { id: "b33", text: "(7 × 3) + (7 × 3)", answer: 0 },
              { id: "b56", text: "(7 × 5) + (7 × 6)", answer: 1 },
              { id: "b26", text: "(5 × 6) + (2 × 6)", answer: 0 },
              { id: "b44", text: "(7 × 4) + (7 × 4)", answer: 1 },
              { id: "b24", text: "(7 × 2) + (7 × 4)", answer: 0 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Para hallar 6 × 8, Inés separa el 8 en 5 y 3. ¿Qué suma?",
              choices: ["6 × 5 y 6 × 3", "6 × 5 y 3", "6 + 5 y 6 + 3"],
              answer: 0,
              hint: "Imagina 6 filas de 8. Corta cada fila en 5 y 3. ¿Qué dos arreglos te quedan?",
              explain: "6 × 8 = (6 × 5) + (6 × 3) = 30 + 18 = 48.",
            },
            {
              id: "q2",
              prompt: "¿Cuánto es 9 × 7?",
              choices: ["56", "63", "72"],
              answer: 1,
              hint: "Halla 10 × 7. Luego quita un grupo de 7.",
              explain: "10 × 7 = 70. 70 − 7 = 63. Así que 9 × 7 = 63.",
            },
            {
              id: "q3",
              prompt: "4 × 7 es el doble de 2 × 7. ¿Cuánto es 4 × 7?",
              choices: ["14", "21", "28"],
              answer: 2,
              hint: "¿Cuánto es 2 × 7? Luego duplica ese número.",
              explain: "14 + 14 = 28. Así que 4 × 7 = 28.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Tarjetas de estrategias",
          brief: "Haz tarjetas para las multiplicaciones que todavía estás aprendiendo, con una forma de separar cada una.",
          steps: [
            "Escribe en tarjetas 6 multiplicaciones que te cuesten, una por tarjeta, como 7 × 8.",
            "Del otro lado, escribe una forma de separarla, como (7 × 5) + (7 × 3).",
            "Halla el producto y escríbelo del otro lado también.",
            "Practica con alguien en casa unos minutos cada día.",
            "Cuando sepas una sin voltear la tarjeta, ponla en la pila de “ya me la sé”.",
          ],
        },
      ],
    },
  ],
};

export default multiplicationEs;
