import type { CatalogueEntry } from "./types";

const numbersTo10: CatalogueEntry = {
  id: "math-numbers-to-10",
  title: "Numbers to 10 and making 10",
  summary: "Count to 10. Compare numbers. Find the pairs that make 10.",
  subject: "math",
  grade: "K",
  locale: "en",
  lessons: [
    {
      id: "count-to-10",
      title: "Count to 10",
      summary: "Say one number for each thing. The last number tells how many.",
      minutes: 10,
      practice: ["m.count.10"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "One number for each thing",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [5] }, alt: "5 dots in a row." },
            { type: "text", text: "Touch each dot once. Say one number as you touch it." },
            { type: "text", text: "1, 2, 3, 4, 5." },
            { type: "text", text: "The last number you say tells how many. There are 5 dots." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Rows of five",
          blocks: [
            {
              type: "visual",
              visual: { kind: "ten-frame", filled: 7 },
              alt: "A ten-frame with 7 dots. The top row of 5 is full. The bottom row has 2 dots.",
            },
            { type: "text", text: "A ten-frame has 10 boxes. Each row has 5." },
            { type: "text", text: "The top row is full. That is 5." },
            { type: "text", text: "Count on from 5: 6, 7. There are 7 dots." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "All the way to 10",
          blocks: [
            {
              type: "visual",
              visual: { kind: "ten-frame", filled: 10 },
              alt: "A full ten-frame. Both rows have 5 dots. There are 10 dots.",
            },
            { type: "text", text: "Two full rows of 5 make 10." },
            { type: "text", text: "Count on from 5: 6, 7, 8, 9, 10." },
            { type: "text", text: "An empty ten-frame has 0 dots. 0 means none." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Count each one once",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [6] }, alt: "6 dots: a row of 5 and 1 more below." },
            { type: "points", items: ["Count each thing once.", "Do not skip one.", "Do not count one twice."] },
            { type: "text", text: "If you move the dots around, there are still 6." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Count to 9",
          prompt: "Start at 0. Move one jump at a time. Say each number. Stop at 9.",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 0, target: 9 },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Sam counts his cars: 1, 2, 3, 4, 5. How many cars?",
              choices: ["1", "4", "5"],
              answer: 2,
              hint: "Listen for the last number Sam says.",
              explain: "The last number Sam says is 5. So there are 5 cars.",
            },
            {
              id: "q2",
              prompt: "Ava counts 6 blocks. Then she spreads them out. How many now?",
              choices: ["Fewer than 6", "6", "More than 6"],
              answer: 1,
              hint: "Did Ava add any blocks? Did she take any away?",
              explain: "Moving blocks does not change how many. There are still 6.",
            },
            {
              id: "q3",
              prompt: "Leo counts one dot two times. Is his count right?",
              choices: ["Yes", "No"],
              answer: 1,
              hint: "How many numbers should each dot get?",
              explain: "No. Each dot gets one number. Counting a dot twice makes the count too big.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Count at home",
          brief: "Count real things at home, up to 10.",
          steps: [
            "Pick small things, like spoons, shoes or crayons.",
            "Line them up in a row.",
            "Touch each one and say a number.",
            "Say how many there are.",
            "Mix them up. Count again. Is it the same?",
          ],
        },
      ],
    },
    {
      id: "more-and-less",
      title: "More, less and the same",
      summary: "Find the number that comes next. Tell which number is more.",
      minutes: 10,
      practice: ["m.compare.10", "m.next.number"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "One more, one less",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 10, marks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], marker: 4 },
              alt: "A number line from 0 to 10. A dot sits on 4.",
            },
            { type: "text", text: "Numbers go up by one as you go right." },
            { type: "text", text: "The number after 4 is 5. 5 is one more." },
            { type: "text", text: "The number before 4 is 3. 3 is one less." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Which is more?",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [6, 3] }, alt: "Two groups of dots: 6 dots and 3 dots." },
            { type: "text", text: "Count each group. One has 6. One has 3." },
            { type: "text", text: "When you count, 6 comes after 3." },
            { type: "text", text: "So 6 is more than 3. 3 is less than 6." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "One more than 7",
          prompt: "What number comes after 7? Move the marker there.",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 7, target: 8 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "More or less than 5",
          prompt: "Is each number less than 5 or more than 5? Tap to sort.",
          widget: {
            kind: "sorter",
            categories: ["Less than 5", "More than 5"],
            items: [
              { id: "n3", text: "3", answer: 0 },
              { id: "n8", text: "8", answer: 1 },
              { id: "n1", text: "1", answer: 0 },
              { id: "n6", text: "6", answer: 1 },
              { id: "n9", text: "9", answer: 1 },
              { id: "n4", text: "4", answer: 0 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which is more, 7 or 4?",
              choices: ["7", "4"],
              answer: 0,
              hint: "Count up from 1. Which number do you say later?",
              explain: "You say 7 after 4. So 7 is more.",
            },
            {
              id: "q2",
              prompt: "What number comes just before 6?",
              choices: ["5", "7", "4"],
              answer: 0,
              hint: "Count up to 6. What did you say right before it?",
              explain: "Count 4, 5, 6. So 5 comes just before 6.",
            },
            {
              id: "q3",
              prompt: "Mia has 5 grapes. Raj has 5 grapes. Who has more?",
              choices: ["Mia", "Raj", "They have the same"],
              answer: 2,
              hint: "Are the two numbers different?",
              explain: "They both have 5. 5 and 5 are the same.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Two piles",
          brief: "Make two piles and find which has more.",
          steps: [
            "Make a pile of beans, buttons or blocks. Use 10 or fewer.",
            "Make a second pile with a different number.",
            "Count each pile.",
            "Put each pile in a row, side by side.",
            "Match each thing with one in the other row.",
            "Which row has extra? That row has more.",
          ],
        },
      ],
    },
    {
      id: "number-pairs",
      title: "Two parts make a number",
      summary: "Break a number into two parts. Put the parts back together.",
      minutes: 10,
      practice: ["m.decompose.10", "m.add.5"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "5 in two parts",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [3, 2] }, alt: "Two groups of dots: 3 dots and 2 dots." },
            { type: "text", text: "Here are 5 dots in two parts." },
            { type: "text", text: "3 and 2 make 5." },
            { type: "visual", visual: { kind: "dots", groups: [4, 1] }, alt: "Two groups of dots: 4 dots and 1 dot." },
            { type: "text", text: "4 and 1 make 5 too." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Many ways",
          blocks: [
            { type: "text", text: "A number can break apart in many ways." },
            { type: "points", items: ["7 is 6 and 1.", "7 is 5 and 2.", "7 is 4 and 3."] },
            {
              type: "visual",
              visual: { kind: "ten-frame", filled: 7 },
              alt: "A ten-frame with 7 dots. 5 are in the top row. 2 are in the bottom row.",
            },
            { type: "text", text: "This ten-frame shows 7 as 5 and 2." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Which make 6?",
          prompt: "Do the two parts make 6? Tap to sort.",
          widget: {
            kind: "sorter",
            categories: ["Makes 6", "Not 6"],
            items: [
              { id: "p33", text: "3 and 3", answer: 0 },
              { id: "p42", text: "4 and 2", answer: 0 },
              { id: "p52", text: "5 and 2", answer: 1 },
              { id: "p15", text: "1 and 5", answer: 0 },
              { id: "p22", text: "2 and 2", answer: 1 },
              { id: "p60", text: "6 and 0", answer: 0 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "4 and 2 more",
          prompt: "Start at 4. Jump 2 more. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 4, target: 6 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "8 is 5 and how many more?",
              choices: ["2", "3", "4"],
              answer: 1,
              hint: "Start at 5. Count on until you say 8.",
              explain: "Count on from 5: 6, 7, 8. That is 3 more. 8 is 5 and 3.",
            },
            {
              id: "q2",
              prompt: "Which two parts make 5?",
              choices: ["2 and 2", "4 and 2", "3 and 2"],
              answer: 2,
              hint: "Put the parts together. Count them all.",
              explain: "3 and 2 make 5. 2 and 2 make 4. 4 and 2 make 6.",
            },
            {
              id: "q3",
              prompt: "4 apples are in two bags. One bag has all 4. How many are in the other bag?",
              choices: ["0", "1", "4"],
              answer: 0,
              hint: "All 4 apples are in one bag already.",
              explain: "The other bag is empty. 4 is 4 and 0.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Shake and spill",
          brief: "Spill coins to find ways to make 5.",
          steps: [
            "Put 5 coins in a cup.",
            "Shake the cup. Spill the coins on a plate.",
            "Count the heads. Count the tails.",
            "Say it, like: 3 heads and 2 tails make 5.",
            "Spill again. Find a new way to make 5.",
          ],
        },
      ],
    },
    {
      id: "make-10",
      title: "Make 10",
      summary: "Find how many more make 10. Use a ten-frame and your fingers.",
      minutes: 10,
      practice: ["m.make.10"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Fill the ten-frame",
          blocks: [
            { type: "visual", visual: { kind: "ten-frame", filled: 7 }, alt: "A ten-frame with 7 dots and 3 empty boxes." },
            { type: "text", text: "This ten-frame has 7 dots." },
            { type: "text", text: "Count the empty boxes: 1, 2, 3." },
            { type: "text", text: "7 and 3 make 10." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Pairs that make 10",
          blocks: [
            { type: "points", items: ["1 and 9", "2 and 8", "3 and 7", "4 and 6", "5 and 5"] },
            { type: "text", text: "Each pair makes 10." },
            { type: "text", text: "Hold up 10 fingers. Put 4 down. 6 are still up." },
            { type: "text", text: "So 4 and 6 make 10." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Makes 10?",
          prompt: "Do the two numbers make 10? Tap to sort.",
          widget: {
            kind: "sorter",
            categories: ["Makes 10", "Not 10"],
            items: [
              { id: "t64", text: "6 and 4", answer: 0 },
              { id: "t54", text: "5 and 4", answer: 1 },
              { id: "t82", text: "8 and 2", answer: 0 },
              { id: "t72", text: "7 and 2", answer: 1 },
              { id: "t91", text: "9 and 1", answer: 0 },
              { id: "t36", text: "3 and 6", answer: 1 },
              { id: "t55", text: "5 and 5", answer: 0 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "From 6 to 10",
          prompt: "Start at 6. Jump until you reach 10. Count your jumps.",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 6, target: 10 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "6 and how many more make 10?",
              choices: ["3", "4", "5"],
              answer: 1,
              hint: "Start at 6. Count on to 10.",
              explain: "Count on from 6: 7, 8, 9, 10. That is 4. 6 and 4 make 10.",
            },
            {
              id: "q2",
              prompt: "A ten-frame has 2 empty boxes. How many dots are in it?",
              choices: ["2", "10", "8"],
              answer: 2,
              hint: "A full ten-frame has 10. Take away the 2 empty boxes.",
              explain: "8 dots and 2 empty boxes make 10. So there are 8 dots.",
            },
            {
              id: "q3",
              prompt: "Which pair makes 10?",
              choices: ["3 and 7", "5 and 4", "6 and 3"],
              answer: 0,
              hint: "Put the two numbers together. Do you get 10?",
              explain: "3 and 7 make 10. 5 and 4 make 9. 6 and 3 make 9.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Hide and find 10",
          brief: "Play a make-10 hiding game with 10 small things.",
          steps: [
            "Count out 10 small toys or beans.",
            "A grown-up hides some under a cup.",
            "Count the ones you can see.",
            "Say how many are hiding. Lift the cup to check.",
            "Switch. Now you hide some.",
          ],
        },
      ],
    },
  ],
};

export default numbersTo10;
