import type { CatalogueEntry } from "./types";

const decimals: CatalogueEntry = {
  id: "math-decimals",
  title: "Decimals and place value",
  summary: "Read and compare decimals to thousandths, and round them to whole numbers, tenths and hundredths. Multiply and divide by 10, 100 and 1,000, and add and subtract decimals.",
  subject: "math",
  grade: "5",
  locale: "en",
  lessons: [
    {
      id: "tenths-hundredths",
      title: "Tenths and hundredths",
      summary: "Split one whole into 10 or 100 equal parts, and write the parts as decimals.",
      minutes: 12,
      practice: ["m.dec.tenths"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Tenths",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 10, shaded: 3 }, alt: "A bar split into 10 equal parts with 3 parts shaded." },
            { type: "text", text: "Split one whole into 10 equal parts. Each part is one tenth." },
            { type: "text", text: "3 tenths can be written as a fraction, 3/10, or as a decimal, 0.3." },
            { type: "text", text: "The decimal point separates the whole number part from the parts of a whole." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Hundredths",
          blocks: [
            { type: "text", text: "Split each tenth into 10 smaller parts. Now the whole has 100 equal parts, called hundredths." },
            { type: "points", items: ["1 hundredth = 1/100 = 0.01", "25 hundredths = 25/100 = 0.25", "0.25 is also 2 tenths and 5 hundredths."] },
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 1, tens: 2, ones: 5 },
              alt: "In this model, the big square is 1 whole. A rod is 1 tenth. A small cube is 1 hundredth. The picture shows 1 whole, 2 tenths and 5 hundredths.",
            },
            { type: "text", text: "If the big square is 1 whole, this picture shows 1.25." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Tenths on a number line",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 1, marks: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1], marker: 0.7 },
              alt: "A number line from 0 to 1 in 10 equal jumps of 0.1. A dot sits on 0.7.",
            },
            { type: "text", text: "Each jump is one tenth. Seven jumps from 0 land on 0.7." },
            { type: "text", text: "Ten tenths make one whole, so 1.0 is the same as 1." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Shade 0.6",
          prompt: "Cut the bar into 10 equal parts. Then shade 0.6 of it.",
          widget: { kind: "fraction-bar", parts: 1, shaded: 0, target: { parts: 10, shaded: 6 } },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Zoom in to hundredths",
          prompt: "This line zooms in between 0.3 and 0.4. Each jump is one hundredth. Move the marker to 0.35.",
          widget: { kind: "number-line", min: 0.3, max: 0.4, step: 0.01, start: 0.3, target: 0.35 },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which decimal means 7 tenths?",
              choices: ["0.07", "0.7", "7.0"],
              answer: 1,
              hint: "On the tenths number line, each jump is 0.1. Where do 7 jumps from 0 land?",
              explain: "7 tenths is 0.7. 0.07 is 7 hundredths, and 7.0 is 7 wholes.",
            },
            {
              id: "q2",
              prompt: "How do you write 43/100 as a decimal?",
              choices: ["4.3", "0.043", "0.43"],
              answer: 2,
              hint: "43 hundredths is the same as 4 tenths and 3 hundredths. Where does each digit go?",
              explain: "43 hundredths is 0.43: 4 tenths and 3 hundredths.",
            },
            {
              id: "q3",
              prompt: "Which is the same amount as 0.5?",
              choices: ["0.50", "0.05", "5.0"],
              answer: 0,
              hint: "5 tenths is the same as how many hundredths?",
              explain: "5 tenths is 50 hundredths, so 0.5 = 0.50. A zero at the end, after the decimal point, doesn't change the value.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Money as decimals",
          brief: "Dimes and pennies are tenths and hundredths of a dollar.",
          steps: [
            "A dime is one tenth of a dollar: $0.10. A penny is one hundredth of a dollar: $0.01.",
            "Lay out 3 dimes and 4 pennies. Write the amount as a decimal of a dollar.",
            "Now lay out 34 pennies. Is it the same amount?",
            "Find a price tag at home or in a store flyer. Say what each digit after the decimal point is worth.",
          ],
        },
      ],
    },
    {
      id: "thousandths",
      title: "Thousandths, comparing and rounding",
      summary: "Read decimals to the thousandths place, compare them place by place, and round them.",
      minutes: 15,
      practice: ["m.dec.thousandths"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Three places after the point",
          blocks: [
            { type: "text", text: "Split a hundredth into 10 equal parts and you get thousandths. One thousandth is 1/1,000, written 0.001." },
            { type: "points", items: ["In 2.358, the 2 is 2 ones.", "The 3 is 3 tenths: 0.3.", "The 5 is 5 hundredths: 0.05.", "The 8 is 8 thousandths: 0.008."] },
            { type: "text", text: "In expanded form, 2.358 = 2 + 0.3 + 0.05 + 0.008." },
            { type: "text", text: "Read it as “two and three hundred fifty-eight thousandths.” The word “and” marks the decimal point." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Each place is 10 times the next",
          blocks: [
            { type: "text", text: "Each place is worth 10 times the place to its right, just as in whole numbers." },
            { type: "points", items: ["1 = 10 tenths", "0.1 = 10 hundredths", "0.01 = 10 thousandths"] },
            { type: "text", text: "So each place is also one tenth of the place to its left." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Compare place by place",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 0.4, max: 0.5, marks: [0.4, 0.42, 0.45, 0.5], marker: 0.42 },
              alt: "A number line from 0.4 to 0.5. A dot at 0.42 sits a little to the right of 0.4.",
            },
            { type: "text", text: "To compare 0.42 and 0.4, line up the decimal points." },
            { type: "text", text: "Both have 4 tenths. 0.42 has 2 hundredths and 0.4 has none. So 0.42 > 0.4." },
            { type: "text", text: "More digits doesn't mean greater. 0.5 > 0.432, because 5 tenths is more than 4 tenths." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Round decimals",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 3.4, max: 3.5, marks: [3.4, 3.45, 3.5], marker: 3.47 },
              alt: "A number line from 3.4 to 3.5 with its halfway point, 3.45, marked. A dot at 3.47 is past the halfway point, closer to 3.5.",
            },
            { type: "text", text: "To round 3.47 to the nearest tenth, find the two tenths it sits between: 3.4 and 3.5." },
            { type: "text", text: "3.47 is past the halfway point, 3.45, so it rounds up to 3.5." },
            {
              type: "points",
              items: [
                "Look at the digit just to the right of the place you are rounding to.",
                "If it is 5 or more, round up. If it is less than 5, round down.",
                "To the nearest whole number, 3.47 rounds to 3, because its tenths digit is 4.",
                "To the nearest hundredth, 2.358 rounds to 2.36, because its thousandths digit is 8.",
              ],
            },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Less or greater than 0.6",
          prompt: "Is each number less than 0.6 or greater than 0.6? Sort them.",
          widget: {
            kind: "sorter",
            categories: ["Less than 0.6", "Greater than 0.6"],
            items: [
              { id: "d059", text: "0.59", answer: 0 },
              { id: "d061", text: "0.61", answer: 1 },
              { id: "d0506", text: "0.506", answer: 0 },
              { id: "d065", text: "0.65", answer: 1 },
              { id: "d07", text: "0.7", answer: 1 },
              { id: "d0098", text: "0.098", answer: 0 },
              { id: "d0555", text: "0.555", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "interactive",
          title: "Round 2.36",
          prompt: "Round 2.36 to the nearest tenth. Move the marker to the answer.",
          widget: { kind: "number-line", min: 2, max: 3, step: 0.1, start: 2, target: 2.4 },
        },
        {
          id: "s7",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is the 7 in 4.073 worth?",
              choices: ["7 tenths", "7 hundredths", "7 thousandths"],
              answer: 1,
              hint: "Name the places after the decimal point in order: tenths, hundredths, thousandths.",
              explain: "4.073 has 0 tenths, 7 hundredths and 3 thousandths. The 7 is worth 0.07.",
            },
            {
              id: "q2",
              prompt: "Which is greater: 0.8 or 0.75?",
              choices: ["0.8", "0.75", "They are equal"],
              answer: 0,
              hint: "Write 0.8 with two places after the point: 0.80.",
              explain: "0.80 is 80 hundredths and 0.75 is 75 hundredths. So 0.8 > 0.75.",
            },
            {
              id: "q3",
              prompt: "Round 5.64 to the nearest whole number.",
              choices: ["5", "5.6", "6"],
              answer: 2,
              hint: "Which two whole numbers is 5.64 between? Look at the tenths digit to see which is closer.",
              explain: "The tenths digit is 6, which is 5 or more, so 5.64 rounds up to 6. 5.6 is 5.64 rounded to the nearest tenth.",
            },
            {
              id: "q4",
              prompt: "Which number is “six and twelve thousandths”?",
              choices: ["6.012", "6.12", "6.0012"],
              answer: 0,
              hint: "Write twelve thousandths as a fraction first: 12/1,000.",
              explain: "Twelve thousandths is 0.012, so the number is 6.012. 6.12 would be six and twelve hundredths.",
            },
          ],
        },
        {
          id: "s8",
          kind: "project",
          title: "Stopwatch game",
          brief: "Use a stopwatch that shows hundredths of a second to compare and round decimals.",
          steps: [
            "Find a stopwatch, or a phone stopwatch, that shows hundredths of a second.",
            "Start it and try to stop it at exactly 5 seconds without looking. Take turns.",
            "Write down each time, like 4.87 or 5.12.",
            "Put all the times in order from least to greatest.",
            "Round each time to the nearest tenth. Do any players tie after rounding?",
          ],
        },
      ],
    },
    {
      id: "powers-of-ten",
      title: "Multiply and divide by 10, 100 and 1,000",
      summary: "When you multiply or divide by 10, every digit moves one place.",
      minutes: 14,
      practice: ["m.pow10"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Times 10: digits move left",
          blocks: [
            { type: "text", text: "Multiplying by 10 makes each digit worth 10 times as much. So each digit moves one place to the left." },
            { type: "text", text: "Use the blocks: a big square is 1 whole, and a rod is 1 tenth of it. 4 rods show 0.4." },
            { type: "text", text: "Times 10, each rod grows to the size of a whole square. The 4 rods become 4 squares:" },
            { type: "visual", visual: { kind: "base-ten", hundreds: 4, tens: 0, ones: 0 }, alt: "4 big squares. Each one is 1 whole, so they show 4." },
            { type: "text", text: "4 tenths become 4 ones, so 0.4 × 10 = 4." },
            { type: "points", items: ["0.4 × 10 = 4", "0.4 × 100 = 40", "0.4 × 1,000 = 400"] },
            { type: "text", text: "Fill any empty places before the decimal point with 0." },
            { type: "text", text: "You may hear this called moving the decimal point to the right. It gives the same answer." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Divide: digits move right",
          blocks: [
            { type: "text", text: "Dividing by 10 makes each digit worth one tenth as much. So each digit moves one place to the right." },
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 3, tens: 6, ones: 0 },
              alt: "In the same model, 3 big squares and 6 rods. They show 3 wholes and 6 tenths, or 3.6.",
            },
            { type: "text", text: "Divide 36 wholes by 10 and each whole shrinks to a rod. 36 rods are 36 tenths, which is 3 wholes and 6 tenths. So 36 ÷ 10 = 3.6." },
            { type: "points", items: ["36 ÷ 10 = 3.6", "36 ÷ 100 = 0.36", "36 ÷ 1,000 = 0.036"] },
            { type: "text", text: "Count the zeros: 10 has one, 100 has two, and 1,000 has three. That is how many places each digit moves." },
            { type: "text", text: "An empty place right after the decimal point gets a 0, like the tenths place in 0.036." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Powers of 10",
          blocks: [
            { type: "points", items: ["10¹ = 10", "10² = 10 × 10 = 100", "10³ = 10 × 10 × 10 = 1,000"] },
            { type: "text", text: "The small raised number is called an exponent. For powers of 10, it matches the number of zeros." },
            { type: "text", text: "So 2.5 × 10³ = 2.5 × 1,000 = 2,500." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Find 7 ÷ 10",
          prompt: "Find 7 ÷ 10. Move the marker to the quotient.",
          widget: { kind: "number-line", min: 0, max: 1, step: 0.1, start: 0, target: 0.7 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Which equal 4.5?",
          prompt: "Which of these are equal to 4.5? Sort each one.",
          widget: {
            kind: "sorter",
            categories: ["Equals 4.5", "Does not equal 4.5"],
            items: [
              { id: "e45d10", text: "45 ÷ 10", answer: 0 },
              { id: "e045x10", text: "0.45 × 10", answer: 0 },
              { id: "e450d100", text: "450 ÷ 100", answer: 0 },
              { id: "e4500d100", text: "4,500 ÷ 100", answer: 1 },
              { id: "e0045x100", text: "0.045 × 100", answer: 0 },
              { id: "e45x10", text: "45 × 10", answer: 1 },
              { id: "e045d10", text: "0.45 ÷ 10", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 3.27 × 100?",
              choices: ["32.7", "327", "3,270"],
              answer: 1,
              hint: "100 has two zeros. Which way do the digits move when you multiply?",
              explain: "Each digit moves two places to the left: 3.27 × 100 = 327.",
            },
            {
              id: "q2",
              prompt: "What is 52 ÷ 1,000?",
              choices: ["0.052", "0.52", "5.2"],
              answer: 0,
              hint: "1,000 has three zeros. Dividing moves the digits to the right.",
              explain: "Each digit moves three places to the right: 52 ÷ 1,000 = 0.052.",
            },
            {
              id: "q3",
              prompt: "Which is the same as 10³?",
              choices: ["30", "100", "1,000"],
              answer: 2,
              hint: "10³ means 10 × 10 × 10.",
              explain: "10 × 10 × 10 = 1,000. The exponent 3 matches the three zeros. 30 is 10 × 3, not 10 × 10 × 10.",
            },
            {
              id: "q4",
              prompt: "Jo says 0.6 × 10 = 0.60. What went wrong?",
              choices: ["Nothing. She is right.", "She wrote a 0 at the end instead of moving the digits", "She should have divided by 10"],
              answer: 1,
              hint: "Is 0.60 any bigger than 0.6?",
              explain: "0.60 is the same as 0.6, so the value did not change. Multiplying by 10 moves the 6 from the tenths place to the ones place: 0.6 × 10 = 6.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Metric measuring",
          brief: "Metric units are built on powers of 10. Changing units means multiplying or dividing by 10, 100 or 1,000.",
          steps: [
            "Find a ruler or tape measure with centimeters. 100 centimeters make 1 meter.",
            "Measure 3 things in centimeters, like a book, a table and a door.",
            "Divide each length by 100 to write it in meters. A table 75 cm tall is 0.75 m tall.",
            "Find a food label that shows grams. 1,000 grams make 1 kilogram. Divide by 1,000 to write it in kilograms.",
            "Explain to someone why the digits moved two places for meters and three places for kilograms.",
          ],
        },
      ],
    },
    {
      id: "add-subtract",
      title: "Add and subtract decimals",
      summary: "Line up the decimal points so you add tenths to tenths and hundredths to hundredths.",
      minutes: 14,
      practice: ["m.dec.addsub"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Line up the points",
          blocks: [
            { type: "text", text: "To add 2.4 + 1.35, line up the decimal points. That puts each place under the same place." },
            { type: "text", text: "Write 2.4 as 2.40 so both numbers have hundredths. A zero at the end doesn't change the value." },
            { type: "points", items: ["Hundredths: 0 + 5 = 5", "Tenths: 4 + 3 = 7", "Ones: 2 + 1 = 3"] },
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 3, tens: 7, ones: 5 },
              alt: "In this model, the big square is 1 whole. A rod is 1 tenth. A small cube is 1 hundredth. The picture shows 3 wholes, 7 tenths and 5 hundredths.",
            },
            { type: "text", text: "So 2.4 + 1.35 = 3.75." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Regroup like whole numbers",
          blocks: [
            { type: "text", text: "Add 4.68 + 2.57." },
            {
              type: "points",
              items: [
                "Hundredths: 8 + 7 = 15. Write 5 and carry 1 tenth.",
                "Tenths: 6 + 5 + 1 = 12. Write 2 and carry 1 one.",
                "Ones: 4 + 2 + 1 = 7.",
              ],
            },
            { type: "text", text: "So 4.68 + 2.57 = 7.25. Ten hundredths make a tenth, and ten tenths make a one." },
            { type: "text", text: "Estimate to check: 4.68 is about 5 and 2.57 is about 3. 5 + 3 = 8, which is close to 7.25." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Subtract",
          blocks: [
            { type: "text", text: "Find 5 − 1.38. Write 5 as 5.00 so the places match." },
            {
              type: "points",
              items: [
                "You can't take 8 hundredths from 0. Trade 1 one for 10 tenths, then 1 tenth for 10 hundredths.",
                "Now 5.00 is 4 ones, 9 tenths and 10 hundredths.",
                "Hundredths: 10 − 8 = 2. Tenths: 9 − 3 = 6. Ones: 4 − 1 = 3.",
              ],
            },
            { type: "text", text: "So 5 − 1.38 = 3.62. Check by adding: 3.62 + 1.38 = 5." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Cross the whole",
          prompt: "Find 0.7 + 0.5. Start at 0.7 and jump 5 tenths. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 2, step: 0.1, start: 0.7, target: 1.2 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Reasonable or way off?",
          prompt: "Round each number to the nearest whole number to estimate. Is each answer reasonable, or way off?",
          widget: {
            kind: "sorter",
            categories: ["Reasonable", "Way off"],
            items: [
              { id: "r1", text: "3.6 + 2.5 = 6.1", answer: 0 },
              { id: "w1", text: "8.25 − 3.9 = 7.86", answer: 1 },
              { id: "r2", text: "1.75 + 4.5 = 6.25", answer: 0 },
              { id: "w2", text: "6.2 + 1.45 = 2.07", answer: 1 },
              { id: "r3", text: "10 − 0.35 = 9.65", answer: 0 },
              { id: "w3", text: "5.06 + 2.9 = 5.35", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 3.5 + 1.25?",
              choices: ["1.60", "4.30", "4.75"],
              answer: 2,
              hint: "Write 3.5 as 3.50 and line up the decimal points.",
              explain: "3.50 + 1.25 = 4.75: 0 + 5 = 5 hundredths, 5 + 2 = 7 tenths and 3 + 1 = 4 ones.",
            },
            {
              id: "q2",
              prompt: "What is 6 − 2.7?",
              choices: ["3.3", "4.3", "4.7"],
              answer: 0,
              hint: "Write 6 as 6.0. You will need to trade 1 one for 10 tenths.",
              explain: "6.0 is 5 ones and 10 tenths. 10 − 7 = 3 tenths and 5 − 2 = 3 ones, so 6 − 2.7 = 3.3.",
            },
            {
              id: "q3",
              prompt: "Maya buys a book for $4.75 and a pen for $1.50. How much does she spend?",
              choices: ["$5.25", "$4.90", "$6.25"],
              answer: 2,
              hint: "Add the cents first: 75 cents + 50 cents.",
              explain: "75 cents + 50 cents = $1.25. $4 + $1 + $1.25 = $6.25.",
            },
            {
              id: "q4",
              prompt: "Ben says 0.4 + 0.8 = 0.12. What is wrong?",
              choices: ["Nothing. He is right.", "4 tenths + 8 tenths is 12 tenths, which is 1.2", "The answer should be 0.32"],
              answer: 1,
              hint: "How many tenths are there in all? How many tenths make 1?",
              explain: "4 tenths + 8 tenths = 12 tenths. 10 tenths make 1 whole, so 12 tenths is 1.2, not 0.12.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Shopping math",
          brief: "Use real prices to add and subtract decimals.",
          steps: [
            "Find a grocery receipt or a store flyer with prices.",
            "Pick 3 items. Estimate the total by rounding each price to the nearest dollar.",
            "Add the exact prices, lining up the decimal points.",
            "Compare the exact total with your estimate. Is it close?",
            "Pretend you pay with a $20 bill. Subtract to find your change. If the total is more than $20, pick cheaper items.",
          ],
        },
      ],
    },
  ],
};

export default decimals;
