import type { CatalogueEntry } from "./types";

const multiplyBigger: CatalogueEntry = {
  id: "math-multiply-bigger",
  title: "Multiplying bigger numbers",
  summary: "Multiply by 10 and 100, and split numbers by place value. Multiply up to four digits by one digit, and two digits by two digits.",
  subject: "math",
  grade: "4",
  locale: "en",
  lessons: [
    {
      id: "tens-hundreds",
      title: "Times 10, times 100",
      summary: "Multiplying by 10 makes each digit worth ten times as much.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Ten times as much",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 0, ones: 3 }, alt: "3 single cubes." },
            { type: "visual", visual: { kind: "base-ten", tens: 3, ones: 0 }, alt: "3 rods of ten." },
            { type: "text", text: "Multiply 3 by 10, and each of the 3 ones becomes a ten." },
            { type: "text", text: "3 × 10 = 30. The 3 now stands for 3 tens." },
            { type: "text", text: "In a whole number, each place is worth 10 times the place to its right." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Digits move left",
          blocks: [
            { type: "points", items: ["4 × 10 = 40", "4 × 100 = 400", "4 × 1,000 = 4,000"] },
            { type: "text", text: "When you multiply a whole number by 10, each digit moves one place to the left." },
            { type: "text", text: "A 0 fills the empty ones place. That is why 23 × 10 = 230." },
            { type: "text", text: "Multiplying by 100 moves each digit two places: 23 × 100 = 2,300." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Facts times tens",
          blocks: [
            { type: "text", text: "To find 6 × 40, think of 40 as 4 tens." },
            { type: "text", text: "6 × 4 tens = 24 tens, and 24 tens is 240." },
            { type: "points", items: ["7 × 30 = 21 tens = 210", "3 × 200 = 6 hundreds = 600", "5 × 80 = 40 tens = 400"] },
            { type: "text", text: "Watch 5 × 80. The fact 5 × 8 = 40 already ends in 0, so the product has two zeros." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Jump by 40",
          prompt: "Find 6 × 40. Make 6 jumps of 40. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 400, step: 40, start: 0, target: 240 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Which make 1,200?",
          prompt: "Which of these products equal 1,200? Sort each one.",
          widget: {
            kind: "sorter",
            categories: ["Equals 1,200", "Does not equal 1,200"],
            items: [
              { id: "p12x100", text: "12 × 100", answer: 0 },
              { id: "p3x400", text: "3 × 400", answer: 0 },
              { id: "p4x300", text: "4 × 300", answer: 0 },
              { id: "p6x20", text: "6 × 20", answer: 1 },
              { id: "p2x600", text: "2 × 600", answer: 0 },
              { id: "p120x100", text: "120 × 100", answer: 1 },
              { id: "p6x200", text: "6 × 200", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 8 × 50?",
              choices: ["400", "40", "4,000"],
              answer: 0,
              hint: "50 is 5 tens. What is 8 × 5 tens?",
              explain: "8 × 5 = 40, so 8 × 5 tens = 40 tens. 40 tens is 400.",
            },
            {
              id: "q2",
              prompt: "What is 36 × 100?",
              choices: ["360", "3,600", "36,000"],
              answer: 1,
              hint: "Multiplying by 100 moves each digit two places to the left.",
              explain: "The 3 moves from the tens place to the thousands place. The 6 moves from the ones place to the hundreds place. 36 × 100 = 3,600.",
            },
            {
              id: "q3",
              prompt: "In 770, how does the value of the first 7 compare with the value of the second 7?",
              choices: ["It is the same", "It is 100 times as much", "It is 10 times as much"],
              answer: 2,
              hint: "Which places are the two 7s in?",
              explain: "The first 7 is worth 700 and the second is worth 70. 700 is 10 times 70.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "A place value chart",
          brief: "Make a chart that shows the digits moving when you multiply by 10, 100 and 1,000.",
          steps: [
            "Draw 4 columns on paper. Label them thousands, hundreds, tens and ones.",
            "Write 7 in the ones column.",
            "On the next line, write 7 × 10. Move the 7 to the tens column and write 0 in the ones column.",
            "Keep going with 7 × 100 and 7 × 1,000.",
            "Now try a two-digit number: 45 × 10 and 45 × 100.",
            "Explain to someone at home why the digits move.",
          ],
        },
      ],
    },
    {
      id: "split-place-value",
      title: "Split by place value",
      summary: "Break the bigger number into hundreds, tens and ones, multiply each part, and add.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Split, multiply, add",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 2, ones: 3 }, alt: "2 rods of ten and 3 single cubes: one group of 23." },
            { type: "text", text: "4 × 23 means 4 groups of 23." },
            { type: "text", text: "Split 23 into 20 and 3. Multiply each part by 4." },
            { type: "points", items: ["4 × 20 = 80", "4 × 3 = 12"] },
            { type: "text", text: "Add the parts: 80 + 12 = 92. So 4 × 23 = 92." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Bigger numbers, same idea",
          blocks: [
            { type: "text", text: "To find 3 × 456, split 456 by place value: 400 + 50 + 6." },
            { type: "points", items: ["3 × 400 = 1,200", "3 × 50 = 150", "3 × 6 = 18"] },
            { type: "text", text: "Each of these answers is called a partial product." },
            { type: "text", text: "Add the partial products: 1,200 + 150 + 18 = 1,368." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Estimate first",
          blocks: [
            { type: "text", text: "Before you multiply, estimate. 456 is close to 500." },
            { type: "text", text: "3 × 500 = 1,500. So 3 × 456 should be a little less than 1,500." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 2000, marks: [0, 500, 1000, 1500, 2000], marker: 1368 },
              alt: "A number line from 0 to 2,000, marked every 500. A dot at 1,368 sits a little to the left of 1,500.",
            },
            { type: "text", text: "1,368 is a little less than 1,500, so the answer makes sense." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Add the last part",
          prompt: "Find 5 × 34. You know 5 × 30 = 150, so the marker starts there. Now add 5 × 4 = 20, which is 4 jumps of 5. Where do you land?",
          widget: { kind: "number-line", min: 100, max: 200, step: 5, start: 150, target: 170 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Parts of 6 × 245",
          prompt: "Split 245 by place value. Which partial products belong to 6 × 245? Sort each one.",
          widget: {
            kind: "sorter",
            categories: ["Belongs", "Does not belong"],
            items: [
              { id: "h", text: "6 × 200 = 1,200", answer: 0 },
              { id: "t", text: "6 × 40 = 240", answer: 0 },
              { id: "o", text: "6 × 5 = 30", answer: 0 },
              { id: "t-as-ones", text: "6 × 4 = 24", answer: 1 },
              { id: "h-as-ones", text: "6 × 2 = 12", answer: 1 },
              { id: "h-as-tens", text: "6 × 20 = 120", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 7 × 46?",
              choices: ["282", "322", "2,842"],
              answer: 1,
              hint: "Split 46 into 40 and 6. Multiply each part by 7.",
              explain: "7 × 40 = 280 and 7 × 6 = 42. 280 + 42 = 322.",
            },
            {
              id: "q2",
              prompt: "Which shows 4 × 1,203 split by place value?",
              choices: ["4 × 1 + 4 × 2 + 4 × 3", "4 × 1,000 + 200 + 3", "4 × 1,000 + 4 × 200 + 4 × 3"],
              answer: 2,
              hint: "Write 1,203 in expanded form first. What is each digit worth?",
              explain: "1,203 = 1,000 + 200 + 3. So 4 × 1,203 = 4,000 + 800 + 12 = 4,812.",
            },
            {
              id: "q3",
              prompt: "Lena estimates 6 × 389 by finding 6 × 400. What is her estimate?",
              choices: ["2,400", "240", "24,000"],
              answer: 0,
              hint: "6 × 4 hundreds is how many hundreds?",
              explain: "6 × 400 = 24 hundreds, which is 2,400. The exact product, 2,334, is close to it.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Time facts",
          brief: "Use facts about time to practice multiplying bigger numbers.",
          steps: [
            "A day has 24 hours. Find the hours in 3 days by splitting 24 into 20 and 4.",
            "An hour has 60 minutes. Find the minutes in 7 hours.",
            "A year that is not a leap year has 365 days. How many days are in 4 of those years? Split 365 into 300 + 60 + 5.",
            "Estimate each answer first. Is your exact answer close to your estimate?",
            "Ask someone at home to check one answer another way.",
          ],
        },
      ],
    },
    {
      id: "columns",
      title: "Multiply in columns",
      summary: "Write the problem in columns, multiply each place, and carry as you go.",
      minutes: 15,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Partial products in a column",
          blocks: [
            {
              type: "visual",
              visual: { kind: "column", op: "×", top: 1452, bottom: 3 },
              alt: "1,452 written above 3, lined up by place, with empty boxes for the answer.",
            },
            { type: "text", text: "Line up the digits by place. Start with the ones." },
            {
              type: "points",
              items: ["3 × 2 ones = 6", "3 × 5 tens = 15 tens = 150", "3 × 4 hundreds = 12 hundreds = 1,200", "3 × 1 thousand = 3,000"],
            },
            { type: "text", text: "Add the partial products: 6 + 150 + 1,200 + 3,000 = 4,356." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Carry as you go",
          blocks: [
            { type: "text", text: "A shorter way writes one digit at a time and carries the extra to the next place." },
            {
              type: "points",
              items: [
                "Ones: 3 × 2 = 6. Write 6.",
                "Tens: 3 × 5 = 15 tens. Write 5 and carry 1 hundred.",
                "Hundreds: 3 × 4 = 12, plus the 1 you carried, is 13 hundreds. Write 3 and carry 1 thousand.",
                "Thousands: 3 × 1 = 3, plus the 1 you carried, is 4 thousands. Write 4.",
              ],
            },
            { type: "text", text: "Both ways give 4,356." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Zeros and carrying",
          blocks: [
            { type: "text", text: "Find 6 × 1,045." },
            { type: "points", items: ["6 × 1,000 = 6,000", "6 × 0 hundreds = 0", "6 × 40 = 240", "6 × 5 = 30"] },
            { type: "text", text: "6,000 + 0 + 240 + 30 = 6,270." },
            {
              type: "text",
              text: "1,045 has 0 hundreds, but the product has 2 hundreds. They come from 6 × 4 tens = 24 tens, which is 2 hundreds and 4 tens.",
            },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Estimate 4 × 2,890",
          prompt: "Estimate 4 × 2,890. Round 2,890 to the nearest thousand, multiply by 4, and move the marker to your estimate.",
          widget: { kind: "number-line", min: 0, max: 20000, step: 1000, start: 0, target: 12000 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Reasonable or way off?",
          prompt: "Use an estimate to check each answer. Is it reasonable, or way off?",
          widget: {
            kind: "sorter",
            categories: ["Reasonable", "Way off"],
            items: [
              { id: "r1", text: "5 × 398 = 1,990", answer: 0 },
              { id: "w1", text: "3 × 2,104 = 632", answer: 1 },
              { id: "r2", text: "7 × 61 = 427", answer: 0 },
              { id: "w2", text: "4 × 1,250 = 50,000", answer: 1 },
              { id: "r3", text: "9 × 512 = 4,608", answer: 0 },
              { id: "w3", text: "6 × 703 = 42,180", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 4 × 1,326?",
              choices: ["4,304", "5,284", "5,304"],
              answer: 2,
              hint: "Multiply each place by 4, starting with the ones. Add what you carry.",
              explain: "4 × 6 = 24, 4 × 20 = 80, 4 × 300 = 1,200 and 4 × 1,000 = 4,000. 4,000 + 1,200 + 80 + 24 = 5,304.",
            },
            {
              id: "q2",
              prompt: "What is 7 × 2,005?",
              choices: ["14,035", "1,435", "14,350"],
              answer: 0,
              hint: "2,005 is 2,000 + 5.",
              explain: "7 × 2,000 = 14,000 and 7 × 5 = 35. 14,000 + 35 = 14,035.",
            },
            {
              id: "q3",
              prompt: "Sam says 5 × 1,980 = 990. How can you tell quickly that he is wrong?",
              choices: [
                "990 is an even number",
                "1,980 is close to 2,000, and 5 × 2,000 = 10,000",
                "A product always has more digits than the numbers you multiply",
              ],
              answer: 1,
              hint: "Round 1,980 to a number that is easy to multiply.",
              explain: "5 × 2,000 = 10,000, so the product should be close to 10,000. The exact product is 9,900, so 990 is far too small.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Check each other",
          brief: "Make multiplication problems for someone at home and check them with estimates.",
          steps: [
            "Write 3 problems that multiply a four-digit number by a one-digit number, like 6 × 2,415.",
            "Solve each one in columns.",
            "Estimate each one by rounding. Is your answer close?",
            "Ask someone at home to solve one too, any way they like.",
            "Compare your work. If your answers are different, find the first step where they split apart.",
          ],
        },
      ],
    },
    {
      id: "two-by-two",
      title: "Two digits times two digits",
      summary: "Split both numbers into tens and ones, find four partial products, and add.",
      minutes: 15,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Four partial products",
          blocks: [
            { type: "text", text: "To find 23 × 14, split both numbers: 23 = 20 + 3 and 14 = 10 + 4." },
            { type: "text", text: "Each part of one number multiplies each part of the other." },
            { type: "points", items: ["20 × 10 = 200", "20 × 4 = 80", "3 × 10 = 30", "3 × 4 = 12"] },
            { type: "text", text: "Add them: 200 + 80 + 30 + 12 = 322. So 23 × 14 = 322." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "An area model",
          blocks: [
            { type: "visual", visual: { kind: "rect", w: 23, h: 14, unit: "units" }, alt: "A rectangle 23 units long and 14 units tall." },
            { type: "text", text: "This rectangle has an area of 23 × 14 square units." },
            { type: "text", text: "Cut the long side into 20 and 3. Cut the short side into 10 and 4. You get these four smaller rectangles:" },
            { type: "visual", visual: { kind: "rect", w: 20, h: 10, unit: "units" }, alt: "A rectangle 20 units long and 10 units tall. Its area is 20 × 10 = 200 square units." },
            { type: "visual", visual: { kind: "rect", w: 3, h: 10, unit: "units" }, alt: "A rectangle 3 units long and 10 units tall. Its area is 3 × 10 = 30 square units." },
            { type: "visual", visual: { kind: "rect", w: 20, h: 4, unit: "units" }, alt: "A rectangle 20 units long and 4 units tall. Its area is 20 × 4 = 80 square units." },
            { type: "visual", visual: { kind: "rect", w: 3, h: 4, unit: "units" }, alt: "A rectangle 3 units long and 4 units tall. Its area is 3 × 4 = 12 square units." },
            { type: "text", text: "Each area is one partial product. Together they make the whole rectangle: 200 + 30 + 80 + 12 = 322." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Tens times tens",
          blocks: [
            { type: "text", text: "20 × 10 is 2 tens times 1 ten." },
            { type: "text", text: "A ten times a ten is a hundred. So 2 tens × 1 ten = 2 hundreds = 200." },
            { type: "points", items: ["30 × 40 = 12 hundreds = 1,200", "60 × 20 = 12 hundreds = 1,200", "50 × 40 = 20 hundreds = 2,000"] },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Estimate first",
          prompt: "Estimate 36 × 24 by rounding to 40 × 20. Move the marker to your estimate.",
          widget: { kind: "number-line", min: 0, max: 1000, step: 100, start: 0, target: 800 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Parts of 36 × 24",
          prompt: "Split 36 into 30 + 6 and 24 into 20 + 4. Which are partial products of 36 × 24? Sort each one.",
          widget: {
            kind: "sorter",
            categories: ["Partial product", "Not a partial product"],
            items: [
              { id: "tt", text: "30 × 20 = 600", answer: 0 },
              { id: "to", text: "30 × 4 = 120", answer: 0 },
              { id: "ot", text: "6 × 20 = 120", answer: 0 },
              { id: "oo", text: "6 × 4 = 24", answer: 0 },
              { id: "digits", text: "3 × 2 = 6", answer: 1 },
              { id: "partial", text: "36 × 2 = 72", answer: 1 },
              { id: "ones-tens", text: "6 × 2 = 12", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 32 × 15?",
              choices: ["160", "310", "480"],
              answer: 2,
              hint: "Split 32 into 30 + 2 and 15 into 10 + 5. Find all four partial products.",
              explain: "30 × 10 = 300, 30 × 5 = 150, 2 × 10 = 20 and 2 × 5 = 10. 300 + 150 + 20 + 10 = 480. 310 uses only two of the four parts.",
            },
            {
              id: "q2",
              prompt: "In 47 × 26, what is the partial product 40 × 20?",
              choices: ["80", "800", "8,000"],
              answer: 1,
              hint: "4 tens × 2 tens = 8 of what?",
              explain: "4 tens × 2 tens = 8 hundreds, which is 800.",
            },
            {
              id: "q3",
              prompt: "A theater has 24 rows with 18 seats in each row. How many seats are there?",
              choices: ["432", "232", "192"],
              answer: 0,
              hint: "Split 24 into 20 + 4 and 18 into 10 + 8.",
              explain: "20 × 10 = 200, 20 × 8 = 160, 4 × 10 = 40 and 4 × 8 = 32. 200 + 160 + 40 + 32 = 432 seats.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Grid paper area model",
          brief: "Draw an area model on grid paper and check it by counting.",
          steps: [
            "On grid paper, draw a rectangle 13 squares long and 12 squares tall. No grid paper? Draw a grid with a ruler.",
            "Draw a line that splits 13 into 10 and 3. Draw another that splits 12 into 10 and 2.",
            "Find the area of each part: 10 × 10, 3 × 10, 10 × 2 and 3 × 2.",
            "Add the four areas to find 13 × 12.",
            "Count the squares in the smallest part to check it.",
          ],
        },
      ],
    },
  ],
};

/** Practice on the skill map that fits each lesson (lesson id → skill ids). */
// tens-hundreds: the whole-number level of m.pow10 is the nearest skill (it also divides, which this lesson leaves out).
export const practice: Record<string, string[]> = {
  "tens-hundreds": ["m.pow10"],
  "split-place-value": ["m.mult.multi"],
  columns: ["m.mult.multi"],
  "two-by-two": ["m.mult.multi"],
};

export default multiplyBigger;
