import type { CatalogueEntry } from "./types";

const fractions: CatalogueEntry = {
  id: "math-fractions",
  title: "Fractions: parts of a whole",
  summary: "Cut one whole into equal parts, name the parts, and find them on a number line.",
  subject: "math",
  grade: "3",
  locale: "en",
  lessons: [
    {
      id: "halves-quarters",
      title: "Halves and quarters",
      summary: "Cut one whole into 2 and 4 equal parts, and name each part.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "One whole, cut fairly",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 1, shaded: 1 }, alt: "A bar that is one whole piece, fully shaded." },
            { type: "text", text: "Here is one whole. A fraction is a part of a whole." },
            { type: "visual", visual: { kind: "fraction", parts: 2, shaded: 1 }, alt: "The same bar cut into 2 equal parts. 1 part is shaded." },
            { type: "text", text: "Cut it into 2 equal parts. Each part is one half. We write it 1/2." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Quarters",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 1 }, alt: "The same bar cut into 4 equal parts. 1 part is shaded." },
            { type: "text", text: "Cut the same whole into 4 equal parts. Each part is one quarter: 1/4." },
            {
              type: "points",
              items: ["The bottom number says how many equal parts the whole has.", "The top number says how many of those parts we mean."],
            },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Make three quarters",
          prompt: "Cut the bar into 4 equal parts. Then shade 3 of them.",
          widget: { kind: "fraction-bar", parts: 1, shaded: 0, target: { parts: 4, shaded: 3 } },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Two quarters",
          prompt: "Show 2/4. Look closely: is it the same amount as 1/2?",
          widget: { kind: "fraction-bar", parts: 2, shaded: 1, target: { parts: 4, shaded: 2 } },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "A pizza is cut into 4 equal slices. You eat 1 slice. What fraction of the pizza did you eat?",
              choices: ["1/2", "1/4", "4/1", "1/3"],
              answer: 1,
              hint: "Count all the equal slices. That number goes on the bottom.",
              explain: "There are 4 equal slices and you ate 1 of them, so you ate 1/4.",
            },
            {
              id: "q2",
              prompt: "Which is more of the same sandwich: 1/2 or 1/4?",
              choices: ["1/2", "1/4", "They are the same"],
              answer: 0,
              hint: "Imagine cutting the sandwich into more pieces. What happens to the size of each piece?",
              explain: "Cutting into 4 makes smaller pieces than cutting into 2, so 1/2 is more.",
            },
            {
              id: "q3",
              prompt: "A bar is cut into 4 pieces, but the pieces are different sizes. Is one piece 1/4 of the bar?",
              choices: ["Yes", "No"],
              answer: 1,
              hint: "Fractions need parts that are all the same size.",
              explain: "1/4 means one of 4 equal parts. Pieces of different sizes aren't quarters.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Fractions at home",
          brief: "Find something you can share fairly: a sandwich, a sheet of paper, or a tortilla.",
          steps: [
            "Fold or cut it into 2 equal parts. Say: each part is one half.",
            "Fold or cut it again so there are 4 equal parts. Say: each part is one quarter.",
            "Put 3 parts together to show 3/4.",
            "Show someone why 2/4 is the same amount as 1/2.",
          ],
        },
      ],
    },
    {
      id: "thirds-sixths-eighths",
      title: "Thirds, sixths and eighths",
      summary: "More ways to cut the same whole, and why more parts means smaller parts.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Thirds",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 1 }, alt: "A bar cut into 3 equal parts. 1 part is shaded." },
            { type: "text", text: "Cut one whole into 3 equal parts. Each part is one third: 1/3." },
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 2 }, alt: "The same bar cut into 3 equal parts. 2 parts are shaded." },
            { type: "text", text: "Shade 2 of the 3 parts and you have two thirds: 2/3." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Sixths and eighths",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 6, shaded: 1 }, alt: "The same bar cut into 6 equal parts. 1 part is shaded." },
            { type: "text", text: "Cut the whole into 6 equal parts. Each part is one sixth: 1/6." },
            { type: "visual", visual: { kind: "fraction", parts: 8, shaded: 1 }, alt: "The same bar cut into 8 equal parts. 1 part is shaded." },
            { type: "text", text: "Cut it into 8 equal parts. Each part is one eighth: 1/8." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "More parts, smaller parts",
          blocks: [
            { type: "text", text: "The more equal parts you cut a whole into, the smaller each part is." },
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 1 }, alt: "A bar cut into 3 equal parts. 1 part is shaded." },
            {
              type: "visual",
              visual: { kind: "fraction", parts: 8, shaded: 1 },
              alt: "A bar of the same length cut into 8 equal parts. 1 part is shaded. It is much narrower than the shaded third above.",
            },
            { type: "points", items: ["1/3 is bigger than 1/6.", "1/6 is bigger than 1/8.", "The whole stays the same size. Only the parts change."] },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Make five eighths",
          prompt: "Show 5/8 of the bar.",
          widget: { kind: "fraction-bar", parts: 1, shaded: 0, target: { parts: 8, shaded: 5 } },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which is the smallest piece of the same cake?",
              choices: ["1/3", "1/6", "1/8"],
              answer: 2,
              hint: "Think about cutting the cake for 3 people or for 8 people.",
              explain: "Cutting the cake into 8 equal pieces makes the smallest pieces. So 1/8 is the smallest.",
            },
            {
              id: "q2",
              prompt: "A sandwich is cut into 3 equal parts. You eat 2. What fraction did you eat?",
              choices: ["2/3", "3/2", "1/3"],
              answer: 0,
              hint: "The bottom number counts all the equal parts.",
              explain: "There are 3 equal parts and you ate 2 of them, so you ate 2/3.",
            },
            {
              id: "q3",
              prompt: "Mia says 1/8 is bigger than 1/3 because 8 is bigger than 3. Is she right?",
              choices: ["Yes", "No"],
              answer: 1,
              hint: "Picture a bar cut into 8 parts and the same bar cut into 3. Which part is wider?",
              explain: "No. Eighths are smaller than thirds of the same whole, so 1/8 is less than 1/3.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Paper strips",
          brief: "Fold paper strips to compare thirds, sixths and eighths.",
          steps: [
            "Cut three strips of paper, all the same size.",
            "Fold the first strip into 3 equal parts. Color 1 part: that is 1/3.",
            "Fold the second strip in half, then into 3 parts. Now it has 6 equal parts.",
            "Fold the third strip in half three times. Now it has 8 equal parts.",
            "Line up the strips. Which is wider: 1/3, 1/6 or 1/8?",
          ],
        },
        {
          id: "s7",
          kind: "interactive",
          title: "Cut a pan into eighths",
          prompt:
            "A pan of cornbread is cut into 2 rows, with 4 equal pieces in each row. Set the rows and columns to match, then count the pieces. One piece is one of that many equal parts of the pan.",
          widget: { kind: "area-model", rows: 1, cols: 1, target: { rows: 2, cols: 4 } },
        },
      ],
    },
    {
      id: "number-line",
      title: "Fractions on a number line",
      summary: "A fraction is also a number. Find it between 0 and 1.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "From a bar to a line",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 3 }, alt: "A bar cut into 4 equal parts with 3 shaded." },
            { type: "text", text: "Stretch the bar out into a line that starts at 0 and ends at 1." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 1, marks: [0, 0.25, 0.5, 0.75, 1], denominator: 4 },
              alt: "A number line from 0 to 1 split into 4 equal jumps, marked 0, 1/4, 2/4, 3/4 and 1.",
            },
            { type: "text", text: "Each equal jump is 1/4. Three jumps from 0 lands on 3/4." },
          ],
        },
        {
          id: "s2",
          kind: "interactive",
          title: "Land on three quarters",
          prompt: "Move the marker to 3/4.",
          widget: { kind: "number-line", min: 0, max: 1, step: 0.25, start: 0, target: 0.75, denominator: 4 },
        },
        {
          id: "s3",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "A line from 0 to 1 is split into 4 equal jumps. Where is 1/4?",
              choices: ["After 1 jump", "After 4 jumps", "Exactly in the middle"],
              answer: 0,
              hint: "The top number counts the jumps from 0.",
              explain: "1/4 is one equal jump from 0.",
            },
            {
              id: "q2",
              prompt: "Which fraction sits exactly halfway between 0 and 1?",
              choices: ["1/4", "2/4", "3/4"],
              answer: 1,
              hint: "Halfway means half of the jumps.",
              explain: "2/4 is two of four equal jumps — the middle. It's the same point as 1/2.",
            },
          ],
        },
      ],
    },
    {
      id: "comparing",
      title: "Comparing fractions",
      summary: "Use pictures and the number line to tell which fraction is bigger.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Parts the same size",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 3 }, alt: "A bar cut into 4 equal parts with 3 shaded." },
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 1 }, alt: "The same bar cut into 4 equal parts with 1 shaded." },
            { type: "text", text: "Both bars are cut into quarters, so the parts are the same size." },
            { type: "text", text: "3 parts is more than 1 part, so 3/4 is bigger than 1/4." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "The same number of parts",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 2 }, alt: "A bar cut into 3 equal parts with 2 shaded." },
            { type: "visual", visual: { kind: "fraction", parts: 8, shaded: 2 }, alt: "The same bar cut into 8 equal parts with 2 shaded." },
            { type: "text", text: "Both bars show 2 parts. But thirds are bigger than eighths." },
            { type: "text", text: "So 2/3 is bigger than 2/8." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "On the number line",
          blocks: [
            { type: "text", text: "On a number line, the fraction farther to the right is bigger." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 1, marks: [0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1], denominator: 8 },
              alt: "A number line from 0 to 1 split into 8 equal jumps, marked 0, 1/8, 2/8, 3/8, 4/8, 5/8, 6/8, 7/8 and 1.",
            },
            { type: "text", text: "7/8 is to the right of 2/8, so 7/8 is bigger." },
            { type: "points", items: ["Only compare parts of the same whole.", "Half of a big pizza is more than half of a small one."] },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Pick the bigger one",
          prompt: "Which is bigger, 3/8 or 5/8? Move the marker to the bigger one.",
          widget: { kind: "number-line", min: 0, max: 1, step: 0.125, start: 0, target: 0.625, denominator: 8 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which is bigger: 2/8 or 5/8?",
              choices: ["2/8", "5/8", "They are the same"],
              answer: 1,
              hint: "The parts are the same size. Count how many parts each one has.",
              explain: "Both are eighths, so the parts are the same size. 5 parts is more than 2 parts, so 5/8 is bigger.",
            },
            {
              id: "q2",
              prompt: "Which is bigger: 1/3 or 1/6?",
              choices: ["1/3", "1/6"],
              answer: 0,
              hint: "Both are one part. Which whole was cut into fewer, bigger pieces?",
              explain: "A whole cut into 3 has bigger parts than a whole cut into 6. So 1/3 is bigger.",
            },
            {
              id: "q3",
              prompt: "Lee ate 1/2 of a small pizza. Kim ate 1/2 of a large pizza. Did they eat the same amount?",
              choices: ["Yes, 1/2 is always the same amount", "No, Kim ate more"],
              answer: 1,
              hint: "Picture half of each pizza. Are the two wholes the same size?",
              explain: "Half of a large pizza is more than half of a small one. You can only compare fractions of the same whole.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Which piece is bigger?",
          brief: "Compare halves and quarters with two things that are the same size.",
          steps: [
            "Get two sheets of paper the same size. Bread slices or tortillas work too.",
            "Fold or cut one into 2 equal parts. Fold or cut the other into 4 equal parts.",
            "Put 1/2 next to 1/4. Which is bigger?",
            "Put 2/4 next to 1/2. What do you notice?",
            "Ask someone at home: would you rather have 1/2 or 1/4 of a treat? Explain why.",
          ],
        },
      ],
    },
  ],
};

export default fractions;
