import type { CatalogueEntry } from "./types";

const numbersTo10Es: CatalogueEntry = {
  id: "math-numbers-to-10-es",
  title: "Números hasta 10 y formar 10",
  summary: "Cuenta hasta 10. Compara números. Encuentra las parejas que forman 10.",
  subject: "math",
  grade: "K",
  locale: "es",
  lessons: [
    {
      id: "count-to-10",
      title: "Contar hasta 10",
      summary: "Di un número por cada cosa. El último número dice cuántas hay.",
      minutes: 10,
      practice: ["m.count.10"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Un número para cada cosa",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [5] }, alt: "5 puntos en una fila." },
            { type: "text", text: "Toca cada punto una vez. Di un número al tocarlo." },
            { type: "text", text: "1, 2, 3, 4, 5." },
            { type: "text", text: "El último número que dices te dice cuántos hay. Hay 5 puntos." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Filas de cinco",
          blocks: [
            {
              type: "visual",
              visual: { kind: "ten-frame", filled: 7 },
              alt: "Un marco de diez con 7 puntos. La fila de arriba está llena con 5. La de abajo tiene 2.",
            },
            { type: "text", text: "Un marco de diez tiene 10 casillas. Cada fila tiene 5." },
            { type: "text", text: "La fila de arriba está llena. Eso es 5." },
            { type: "text", text: "Sigue contando desde 5: 6, 7. Hay 7 puntos." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Hasta el 10",
          blocks: [
            {
              type: "visual",
              visual: { kind: "ten-frame", filled: 10 },
              alt: "Un marco de diez lleno. Las dos filas tienen 5 puntos. Hay 10 puntos.",
            },
            { type: "text", text: "Dos filas llenas de 5 son 10." },
            { type: "text", text: "Sigue desde 5: 6, 7, 8, 9, 10." },
            { type: "text", text: "Un marco vacío tiene 0 puntos. Cero quiere decir ninguno." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Cuenta cada uno una vez",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [6] }, alt: "6 puntos: una fila de 5 y 1 más abajo." },
            { type: "points", items: ["Cuenta cada cosa una vez.", "No te saltes ninguna.", "No cuentes ninguna dos veces."] },
            { type: "text", text: "Si mueves los puntos, sigue habiendo 6." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Cuenta hasta 9",
          prompt: "Empieza en 0. Avanza un salto a la vez. Di cada número. Detente en 9.",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 0, target: 9 },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Mateo cuenta sus carritos: 1, 2, 3, 4, 5. ¿Cuántos carritos tiene?",
              choices: ["1", "4", "5"],
              answer: 2,
              hint: "Escucha el último número que dice Mateo.",
              explain: "El último número que dice Mateo es 5. Tiene 5 carritos.",
            },
            {
              id: "q2",
              prompt: "Sofía cuenta 6 bloques. Luego los separa. ¿Cuántos hay ahora?",
              choices: ["Menos de 6", "6", "Más de 6"],
              answer: 1,
              hint: "¿Sofía agregó bloques? ¿Quitó alguno?",
              explain: "Mover los bloques no cambia cuántos hay. Siguen siendo 6.",
            },
            {
              id: "q3",
              prompt: "Diego cuenta un punto dos veces. ¿Su cuenta está bien?",
              choices: ["Sí", "No"],
              answer: 1,
              hint: "¿Cuántos números le tocan a cada punto?",
              explain: "No. Cada punto lleva un número. Contar un punto dos veces hace el total más grande.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Cuenta en casa",
          brief: "Cuenta cosas de verdad en casa, hasta 10.",
          steps: [
            "Escoge cosas pequeñas, como cucharas, zapatos o crayones.",
            "Ponlas en fila.",
            "Toca cada una y di un número.",
            "Di cuántas hay.",
            "Revuélvelas. Cuenta otra vez. ¿Te da el mismo número?",
          ],
        },
      ],
    },
    {
      id: "more-and-less",
      title: "Más, menos e igual",
      summary: "Encuentra el número que sigue. Di qué número es mayor.",
      minutes: 10,
      practice: ["m.compare.10", "m.next.number"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Uno más, uno menos",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 10, marks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], marker: 4 },
              alt: "Una recta numérica del 0 al 10. Un punto está en el 4.",
            },
            { type: "text", text: "Hacia la derecha, los números suben de uno en uno." },
            { type: "text", text: "Después del 4 viene el 5. El 5 es uno más." },
            { type: "text", text: "Antes del 4 viene el 3. El 3 es uno menos." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "¿Cuál es mayor?",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [6, 3] }, alt: "Dos grupos de puntos: 6 puntos y 3 puntos." },
            { type: "text", text: "Cuenta cada grupo. Uno tiene 6. El otro tiene 3." },
            { type: "text", text: "Al contar, el 6 viene después del 3." },
            { type: "text", text: "Entonces 6 es mayor que 3. 3 es menor que 6." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Uno más que 7",
          prompt: "¿Qué número viene después del 7? Mueve el marcador ahí.",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 7, target: 8 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Menor o mayor que 5",
          prompt: "¿Cada número es menor o mayor que 5? Toca para clasificar.",
          widget: {
            kind: "sorter",
            categories: ["Menor que 5", "Mayor que 5"],
            items: [
              { id: "n3", text: "3", answer: 0 },
              { id: "n8", text: "8", answer: 1 },
              { id: "n1", text: "1", answer: 0 },
              { id: "n6", text: "6", answer: 1 },
              { id: "n9", text: "9", answer: 1 },
              { id: "n4", text: "4", answer: 0 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué número es mayor, 7 o 4?",
              choices: ["7", "4"],
              answer: 0,
              hint: "Cuenta desde 1. ¿Qué número dices después?",
              explain: "Dices el 7 después del 4. Por eso 7 es mayor.",
            },
            {
              id: "q2",
              prompt: "¿Qué número viene justo antes del 6?",
              choices: ["5", "7", "4"],
              answer: 0,
              hint: "Cuenta hasta 6. ¿Qué dijiste justo antes?",
              explain: "Cuenta 4, 5, 6. El 5 viene justo antes del 6.",
            },
            {
              id: "q3",
              prompt: "Valeria tiene 5 uvas. Luis tiene 5 uvas. ¿Quién tiene más?",
              choices: ["Valeria", "Luis", "Tienen la misma cantidad"],
              answer: 2,
              hint: "¿Los dos números son distintos?",
              explain: "Los dos tienen 5. 5 y 5 son iguales.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Dos montones",
          brief: "Haz dos montones y encuentra cuál tiene más.",
          steps: [
            "Haz un montón de frijoles, botones o bloques. Usa 10 o menos.",
            "Haz otro montón con un número distinto.",
            "Cuenta cada montón.",
            "Pon cada montón en una fila. Pon las filas lado a lado.",
            "Empareja cada cosa con una de la otra fila.",
            "¿En qué fila sobran cosas? Esa fila tiene más.",
          ],
        },
      ],
    },
    {
      id: "number-pairs",
      title: "Dos partes forman un número",
      summary: "Separa un número en dos partes. Vuelve a juntar las partes.",
      minutes: 10,
      practice: ["m.decompose.10", "m.add.5"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "El 5 en dos partes",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [3, 2] }, alt: "Dos grupos de puntos: 3 puntos y 2 puntos." },
            { type: "text", text: "Aquí hay 5 puntos en dos partes." },
            { type: "text", text: "3 y 2 forman 5." },
            { type: "visual", visual: { kind: "dots", groups: [4, 1] }, alt: "Dos grupos de puntos: 4 puntos y 1 punto." },
            { type: "text", text: "4 y 1 también forman 5." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Muchas maneras",
          blocks: [
            { type: "text", text: "Un número se puede separar de muchas maneras." },
            { type: "points", items: ["7 es 6 y 1.", "7 es 5 y 2.", "7 es 4 y 3."] },
            { type: "visual", visual: { kind: "ten-frame", filled: 7 }, alt: "Un marco de diez con 7 puntos. Hay 5 arriba y 2 abajo." },
            { type: "text", text: "Este marco muestra el 7 como 5 y 2." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "¿Cuáles forman 6?",
          prompt: "¿Las dos partes forman 6? Toca para clasificar.",
          widget: {
            kind: "sorter",
            categories: ["Forma 6", "No forma 6"],
            items: [
              { id: "p33", text: "3 y 3", answer: 0 },
              { id: "p42", text: "4 y 2", answer: 0 },
              { id: "p52", text: "5 y 2", answer: 1 },
              { id: "p15", text: "1 y 5", answer: 0 },
              { id: "p22", text: "2 y 2", answer: 1 },
              { id: "p60", text: "6 y 0", answer: 0 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "4 y 2 más",
          prompt: "Empieza en 4. Salta 2 más. ¿Dónde caes?",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 4, target: 6 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿5 y cuántos más forman 8?",
              choices: ["2", "3", "4"],
              answer: 1,
              hint: "Empieza en 5. Sigue contando hasta llegar a 8.",
              explain: "Desde 5: 6, 7, 8. Son 3 más. 8 es 5 y 3.",
            },
            {
              id: "q2",
              prompt: "¿Qué dos partes forman 5?",
              choices: ["2 y 2", "4 y 2", "3 y 2"],
              answer: 2,
              hint: "Junta las partes. Cuéntalas todas.",
              explain: "3 y 2 forman 5. 2 y 2 forman 4. 4 y 2 forman 6.",
            },
            {
              id: "q3",
              prompt: "Hay 4 manzanas en dos bolsas. Una bolsa tiene las 4. ¿Cuántas hay en la otra?",
              choices: ["0", "1", "4"],
              answer: 0,
              hint: "Las 4 manzanas ya están en una bolsa.",
              explain: "La otra bolsa está vacía. 4 es 4 y 0.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "En mis dos manos",
          brief: "Reparte 5 cosas entre tus manos. Encuentra muchas maneras de formar 5.",
          steps: [
            "Toma 5 frijoles o botones.",
            "Reparte los 5 entre tus dos manos.",
            "Abre una mano y cuenta. Luego abre la otra.",
            "Dilo así: 3 y 2 forman 5.",
            "Repártelos otra vez de otra manera.",
          ],
        },
      ],
    },
    {
      id: "make-10",
      title: "Formar 10",
      summary: "Encuentra cuántos faltan para 10. Usa un marco de diez y tus dedos.",
      minutes: 10,
      practice: ["m.make.10"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Llena el marco de diez",
          blocks: [
            { type: "visual", visual: { kind: "ten-frame", filled: 7 }, alt: "Un marco de diez: 7 puntos y 3 casillas vacías." },
            { type: "text", text: "Este marco de diez tiene 7 puntos." },
            { type: "text", text: "Cuenta las casillas vacías: 1, 2, 3." },
            { type: "text", text: "7 y 3 forman 10." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Parejas que forman 10",
          blocks: [
            { type: "points", items: ["1 y 9", "2 y 8", "3 y 7", "4 y 6", "5 y 5"] },
            { type: "text", text: "Cada pareja forma 10." },
            { type: "text", text: "Levanta tus 10 dedos. Baja 4. Quedan 6 arriba." },
            { type: "text", text: "Entonces 4 y 6 forman 10." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "¿Forma 10?",
          prompt: "¿Los dos números forman 10? Toca para clasificar.",
          widget: {
            kind: "sorter",
            categories: ["Forma 10", "No forma 10"],
            items: [
              { id: "t64", text: "6 y 4", answer: 0 },
              { id: "t54", text: "5 y 4", answer: 1 },
              { id: "t82", text: "8 y 2", answer: 0 },
              { id: "t72", text: "7 y 2", answer: 1 },
              { id: "t91", text: "9 y 1", answer: 0 },
              { id: "t36", text: "3 y 6", answer: 1 },
              { id: "t55", text: "5 y 5", answer: 0 },
            ],
          },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Del 6 al 10",
          prompt: "Empieza en 6. Salta hasta llegar a 10. Cuenta tus saltos.",
          widget: { kind: "number-line", min: 0, max: 10, step: 1, start: 6, target: 10 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿6 y cuántos más forman 10?",
              choices: ["3", "4", "5"],
              answer: 1,
              hint: "Empieza en 6. Sigue contando hasta 10.",
              explain: "Desde 6: 7, 8, 9, 10. Son 4. 6 y 4 forman 10.",
            },
            {
              id: "q2",
              prompt: "Un marco de diez tiene 2 casillas vacías. ¿Cuántos puntos tiene?",
              choices: ["2", "10", "8"],
              answer: 2,
              hint: "Un marco lleno tiene 10. Quita las 2 vacías.",
              explain: "8 puntos y 2 casillas vacías forman 10. Tiene 8 puntos.",
            },
            {
              id: "q3",
              prompt: "¿Qué pareja forma 10?",
              choices: ["3 y 7", "5 y 4", "6 y 3"],
              answer: 0,
              hint: "Junta los dos números. ¿Te da 10?",
              explain: "3 y 7 forman 10. 5 y 4 forman 9. 6 y 3 forman 9.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Esconde y encuentra 10",
          brief: "Juega a esconder cosas para formar 10.",
          steps: [
            "Cuenta 10 juguetes pequeños o frijoles.",
            "Un adulto esconde algunos debajo de un vaso.",
            "Cuenta los que ves.",
            "Di cuántos están escondidos. Levanta el vaso para comprobar.",
            "Cambien. Ahora tú escondes algunos.",
          ],
        },
      ],
    },
  ],
};

export default numbersTo10Es;
