import type { CatalogueEntry } from "./types";

const hundredsTensOnesEs: CatalogueEntry = {
  id: "math-hundreds-tens-ones-es",
  title: "Centenas, decenas y unidades",
  summary: "Forma números hasta 1000 con centenas, decenas y unidades. Cuenta de 10 en 10 y de 100 en 100. Compara números de tres cifras.",
  subject: "math",
  grade: "2",
  locale: "es",
  lessons: [
    {
      id: "ten-tens",
      title: "Diez decenas forman una centena",
      summary: "Agrupa unidades en decenas. Agrupa decenas en una centena.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Unidades y decenas",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 1, ones: 3 }, alt: "1 barra de diez y 3 cubitos sueltos." },
            { type: "text", text: "Un cubito vale 1. Se llama unidad." },
            { type: "text", text: "Junta 10 unidades y formas una barra." },
            { type: "text", text: "Una barra es 1 decena. 1 decena y 3 unidades son 13." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Una centena",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 10, ones: 0 }, alt: "10 barras de diez en fila." },
            { type: "text", text: "Cuenta estas barras de 10 en 10, hasta 100." },
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 1, tens: 0, ones: 0 },
              alt: "1 placa cuadrada. Es tan grande como 10 barras juntas.",
            },
            { type: "text", text: "Junta 10 decenas. Tienes 1 centena." },
            { type: "points", items: ["10 unidades forman 1 decena.", "10 decenas forman 1 centena."] },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Decenas y unidades",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 4, ones: 6 }, alt: "4 barras de diez y 6 cubitos sueltos." },
            { type: "text", text: "4 decenas son 40. 6 unidades son 6." },
            { type: "text", text: "40 y 6 son 46." },
            { type: "text", text: "El 4 está en el lugar de las decenas. El 6, en el de las unidades." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Salta de 10 en 10",
          prompt: "Salta de 10 en 10 desde 0. Da 7 saltos. ¿Dónde caes?",
          widget: { kind: "number-line", min: 0, max: 100, step: 10, start: 0, target: 70 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuántas decenas forman 1 centena?",
              choices: ["1", "10", "100"],
              answer: 1,
              hint: "Cuenta de 10 en 10 hasta 100. ¿Cuántas decenas dijiste?",
              explain: "10, 20, 30, 40, 50, 60, 70, 80, 90, 100. Son 10 decenas.",
            },
            {
              id: "q2",
              prompt: "¿Cuántas unidades hay en 1 centena?",
              choices: ["1", "10", "100"],
              answer: 2,
              hint: "1 centena son 10 decenas. Cada decena tiene 10 unidades.",
              explain: "10 decenas de 10 unidades cada una son 100 unidades.",
            },
            {
              id: "q3",
              prompt: "¿Qué número son 6 decenas y 4 unidades?",
              choices: ["10", "46", "64"],
              answer: 2,
              hint: "6 decenas son 60. Luego suma las unidades.",
              explain: "6 decenas son 60. 60 y 4 unidades son 64.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Paquetes de diez",
          brief: "Agrupa un montón grande en decenas para contarlo.",
          steps: [
            "Junta un montón de pasta seca, frijoles o palitos.",
            "Haz grupos de 10. Pon cada grupo en un vaso.",
            "Cuenta los vasos de 10 en 10.",
            "Cuenta las unidades que sobran.",
            "Escribe el número. 5 decenas y 3 unidades son 53.",
            "¿Llenaste 10 vasos? Diez decenas son 100.",
          ],
        },
      ],
    },
    {
      id: "three-digits",
      title: "Lo que vale cada cifra",
      summary: "El lugar de una cifra dice cuánto vale.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Tres lugares",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 2, tens: 4, ones: 3 },
              alt: "2 placas de cien y 4 barras de diez. Hay 3 cubitos sueltos.",
            },
            { type: "text", text: "2 centenas, 4 decenas y 3 unidades son 243." },
            { type: "text", text: "Se lee: doscientos cuarenta y tres." },
            { type: "points", items: ["El 2 vale 2 centenas, o sea 200.", "El 4 vale 4 decenas, o sea 40.", "El 3 vale 3 unidades, o sea 3."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Forma desarrollada",
          blocks: [
            { type: "text", text: "Podemos escribir 243 como 200 + 40 + 3." },
            { type: "text", text: "Esto se llama forma desarrollada. Muestra cuánto vale cada cifra." },
            { type: "text", text: "Si cambias las cifras de lugar, cambia el número." },
            { type: "text", text: "342 es 300 + 40 + 2." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "El cero guarda un lugar",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 3, tens: 0, ones: 5 },
              alt: "3 placas de cien y ninguna barra de diez. Hay 5 cubitos sueltos.",
            },
            { type: "text", text: "Esto es 3 centenas, 0 decenas y 5 unidades." },
            { type: "text", text: "Se escribe 305. El 0 dice que no hay decenas." },
            { type: "text", text: "Sin el 0 diría 35. Eso es mucho menos." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Dónde está el 4?",
          prompt: "¿En qué lugar está el 4? Toca para clasificar cada número.",
          widget: {
            kind: "sorter",
            categories: ["Centenas", "Decenas", "Unidades"],
            items: [
              { id: "n427", text: "427", answer: 0 },
              { id: "n148", text: "148", answer: 1 },
              { id: "n304", text: "304", answer: 2 },
              { id: "n940", text: "940", answer: 1 },
              { id: "n492", text: "492", answer: 0 },
              { id: "n714", text: "714", answer: 2 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuánto vale el 6 en 362?",
              choices: ["6", "60", "600"],
              answer: 1,
              hint: "¿En qué lugar está el 6?",
              explain: "El 6 está en el lugar de las decenas. 6 decenas son 60.",
            },
            {
              id: "q2",
              prompt: "¿Qué número tiene 2 centenas, 0 decenas y 7 unidades?",
              choices: ["207", "27", "270"],
              answer: 0,
              hint: "Pon cada cifra en su lugar: centenas, decenas, unidades.",
              explain: "2 centenas, 0 decenas y 7 unidades son 207.",
            },
            {
              id: "q3",
              prompt: "¿Cuánto es 500 + 30 + 8?",
              choices: ["538", "500308", "583"],
              answer: 0,
              hint: "500 son las centenas. 30, las decenas. 8, las unidades.",
              explain: "5 centenas, 3 decenas y 8 unidades son 538. Cada lugar lleva una sola cifra.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Centavos y valor posicional",
          brief: "El dinero también se agrupa en unidades, decenas y centenas.",
          steps: [
            "1 centavo es como una unidad. 10 centavos, como una decena.",
            "Un dólar son 100 centavos. Es como una centena.",
            "Usa dinero de verdad o de juguete.",
            "Muestra 1 dólar y 2 monedas de 10. Agrega 5 monedas de 1.",
            "¿Cuántos centavos son? Escribe el número.",
            "Ahora muestra 203 centavos. ¿Necesitas monedas de 10?",
          ],
        },
      ],
    },
    {
      id: "skip-count",
      title: "Contar de 10 en 10 y de 100 en 100",
      summary: "Encuentra 10 más, 10 menos, 100 más y 100 menos.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "10 más, 10 menos",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 2, tens: 3, ones: 4 },
              alt: "2 placas de cien y 3 barras de diez. Hay 4 cubitos sueltos. Muestran 234.",
            },
            { type: "text", text: "Súmale 1 decena a 234. Te da 244." },
            { type: "text", text: "Solo cambia la cifra de las decenas. Sube 1." },
            { type: "text", text: "Quítale 1 decena a 234. Te da 224." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "100 más, 100 menos",
          blocks: [
            { type: "text", text: "Súmale 1 centena a 234. Te da 334." },
            { type: "text", text: "Ahora sube 1 la cifra de las centenas." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 1000, marks: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] },
              alt: "Una recta numérica del 0 al 1000. Tiene una marca en cada centena.",
            },
            { type: "text", text: "En esta recta, cada marca es 100 más." },
            { type: "text", text: "Quítale 1 centena a 234. Te da 134." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Al pasar una centena",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 180, max: 210, marks: [180, 190, 200, 210] },
              alt: "Una recta numérica marcada con 180, 190, 200 y 210.",
            },
            { type: "text", text: "Cuenta de 10 en 10: 180, 190, 200, 210." },
            { type: "text", text: "190 es 1 centena y 9 decenas. Suma 1 decena." },
            { type: "text", text: "Ahora hay 10 decenas. Forman 1 centena más." },
            { type: "text", text: "Por eso 190 + 10 = 200." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Pasa del 200",
          prompt: "Empieza en 170. Cuenta de 10 en 10 cuatro veces. ¿Dónde caes?",
          widget: { kind: "number-line", min: 100, max: 300, step: 10, start: 170, target: 210 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Salta de 100 en 100",
          prompt: "Empieza en 400. Salta 300 más. ¿Dónde caes?",
          widget: { kind: "number-line", min: 0, max: 1000, step: 100, start: 400, target: 700 },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuánto es 10 más que 452?",
              choices: ["453", "462", "552"],
              answer: 1,
              hint: "Cuenta de 10 en 10 desde 452. ¿Qué dices después?",
              explain: "La cifra de las decenas pasa de 5 a 6. 452 + 10 = 462.",
            },
            {
              id: "q2",
              prompt: "¿Cuánto es 100 menos que 608?",
              choices: ["508", "598", "607"],
              answer: 0,
              hint: "Quítale 1 centena a 608. ¿Cuántas centenas quedan?",
              explain: "La cifra de las centenas pasa de 6 a 5. 608 − 100 = 508.",
            },
            {
              id: "q3",
              prompt: "Cuenta de 10 en 10: 370, 380, 390. ¿Qué sigue?",
              choices: ["391", "400", "3100"],
              answer: 1,
              hint: "390 es 3 centenas y 9 decenas. Suma 1 decena.",
              explain: "Ahora hay 10 decenas. Forman 1 centena más. 390 + 10 = 400.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "El juego de 10 más",
          brief: "Un juego de 10 y 100 más o menos.",
          steps: [
            "Escribe un número de tres cifras, como 345.",
            "Un adulto escoge una regla, como 100 menos.",
            "Escribe el número nuevo. Di qué cifra cambió.",
            "Túrnense para decir y resolver.",
            "Prueba 395 y 10 más. ¿Qué pasa con las cifras?",
          ],
        },
      ],
    },
    {
      id: "compare",
      title: "Comparar números de tres cifras",
      summary: "Compara primero las centenas. Luego las decenas. Luego las unidades.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Primero las centenas",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 3, tens: 1, ones: 2 },
              alt: "3 placas de cien y 1 barra de diez. Hay 2 cubitos sueltos. Muestran 312.",
            },
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 2, tens: 9, ones: 8 },
              alt: "2 placas de cien y 9 barras de diez. Hay 8 cubitos sueltos. Muestran 298.",
            },
            { type: "text", text: "312 tiene 3 centenas. 298 tiene solo 2." },
            { type: "text", text: "Así que 312 es mayor, aunque 298 tenga más decenas." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Cuando las centenas son iguales",
          blocks: [
            { type: "text", text: "Compara 456 y 437." },
            { type: "text", text: "Los dos tienen 4 centenas. Entonces mira las decenas." },
            { type: "text", text: "5 decenas son más que 3 decenas. Así que 456 es mayor." },
            { type: "points", items: ["¿Mismas centenas? Compara las decenas.", "¿Mismas decenas también? Compara las unidades."] },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Los símbolos",
          blocks: [
            {
              type: "points",
              items: ["> significa mayor que: 456 > 437.", "< significa menor que: 437 < 456.", "= significa igual a: 500 = 500."],
            },
            { type: "text", text: "El lado abierto mira hacia el número mayor." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Menor o mayor que 500",
          prompt: "¿Cada número es menor o mayor que 500? Toca para clasificar.",
          widget: {
            kind: "sorter",
            categories: ["Menor que 500", "Mayor que 500"],
            items: [
              { id: "n498", text: "498", answer: 0 },
              { id: "n512", text: "512", answer: 1 },
              { id: "n509", text: "509", answer: 1 },
              { id: "n490", text: "490", answer: 0 },
              { id: "n601", text: "601", answer: 1 },
              { id: "n399", text: "399", answer: 0 },
              { id: "n95", text: "95", answer: 0 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuál es mayor, 389 o 412?",
              choices: ["389", "412"],
              answer: 1,
              hint: "Compara primero las centenas.",
              explain: "412 tiene 4 centenas. 389 tiene 3 centenas. Así que 412 es mayor.",
            },
            {
              id: "q2",
              prompt: "¿Cuál es verdadero?",
              choices: ["251 < 215", "251 = 215", "251 > 215"],
              answer: 2,
              hint: "Las centenas son iguales. Ahora compara las decenas.",
              explain: "Los dos tienen 2 centenas. 5 decenas son más que 1 decena. Así que 251 > 215.",
            },
            {
              id: "q3",
              prompt: "Camila dice que 102 es mayor que 98. ¿Tiene razón?",
              choices: ["Sí", "No"],
              answer: 0,
              hint: "¿Cuántas centenas tiene cada número?",
              explain: "Sí. 102 tiene 1 centena. 98 no tiene centenas. Así que 102 es mayor.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "El número más grande",
          brief: "Forma el número más grande que puedas con 3 tarjetas.",
          steps: [
            "Escribe cada cifra del 0 al 9 en una tarjeta.",
            "Revuélvelas. Cada jugador toma 3 tarjetas.",
            "Forma el número más grande que puedas.",
            "Lean los dos números en voz alta. ¿Cuál es mayor?",
            "Escríbelo con >, < o =.",
          ],
        },
      ],
    },
  ],
};

export { practice } from "./math-hundreds-tens-ones";

export default hundredsTensOnesEs;
