import type { CatalogueEntry } from "./types";

const multiplication: CatalogueEntry = {
  id: "math-multiplication",
  title: "Multiplication: equal groups and arrays",
  summary: "Equal groups and arrays show what multiplication means. Skip count to find products, and use facts you know to find new ones.",
  subject: "math",
  grade: "3",
  locale: "en",
  lessons: [
    {
      id: "equal-groups",
      title: "Equal groups",
      summary: "Multiplication counts equal groups: how many groups, times how many in each group.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Groups of the same size",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [4, 4, 4] }, alt: "3 groups of dots with 4 dots in each group." },
            { type: "text", text: "Here are 3 groups. Each group has 4 dots." },
            { type: "text", text: "You can add: 4 + 4 + 4 = 12." },
            { type: "text", text: "Or you can multiply: 3 × 4 = 12. We say “3 times 4.”" },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "What the numbers mean",
          blocks: [
            {
              type: "points",
              items: [
                "The first number tells how many groups: 3.",
                "The second number tells how many are in each group: 4.",
                "The answer is called the product: 12 in all.",
              ],
            },
            { type: "text", text: "Multiplying works when every group is the same size." },
            { type: "text", text: "If the groups are different sizes, add them instead." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Skip count",
          blocks: [
            { type: "visual", visual: { kind: "dots", groups: [5, 5, 5, 5] }, alt: "4 groups of dots with 5 dots in each group." },
            { type: "text", text: "To find 4 × 5, count by fives, once for each group." },
            { type: "text", text: "5, 10, 15, 20. So 4 × 5 = 20." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Jump in equal groups",
          prompt: "Find 6 × 3. Start at 0 and make 6 jumps of 3. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 30, step: 3, start: 0, target: 18 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Equal groups or not?",
          prompt: "Can you multiply to find the total? Sort each one.",
          widget: {
            kind: "sorter",
            categories: ["Equal groups", "Not equal groups"],
            items: [
              { id: "bags", text: "4 bags with 5 apples in each bag", answer: 0 },
              { id: "boxes", text: "3 boxes: 6 crayons, 6 crayons and 6 crayons", answer: 0 },
              { id: "plates", text: "2 plates: one with 3 cookies, one with 5 cookies", answer: 1 },
              { id: "cars", text: "5 cars with 4 wheels on each car", answer: 0 },
              { id: "vases", text: "A vase with 7 roses and a vase with 4 tulips", answer: 1 },
              { id: "tables", text: "6 tables with 2 chairs at each table", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "There are 5 vases with 3 flowers in each vase. Which shows the total?",
              choices: ["5 + 3", "5 × 3", "5 − 3"],
              answer: 1,
              hint: "Are the groups the same size? How many groups are there?",
              explain: "There are 5 equal groups of 3, so the total is 5 × 3 = 15 flowers.",
            },
            {
              id: "q2",
              prompt: "There are 4 cups with 6 pencils in each cup. How many pencils are there?",
              choices: ["10", "24", "20"],
              answer: 1,
              hint: "Count by sixes, once for each cup.",
              explain: "6, 12, 18, 24. So 4 × 6 = 24 pencils. Adding 4 + 6 = 10 counts only one cup.",
            },
            {
              id: "q3",
              prompt: "Which story matches 2 × 7?",
              choices: ["2 bags with 7 marbles in each bag", "7 bags with 7 marbles in each bag", "A bag of 2 marbles and a bag of 7 marbles"],
              answer: 0,
              hint: "The first number tells how many groups. The second tells how many are in each.",
              explain: "2 × 7 means 2 equal groups with 7 in each group.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Equal groups at home",
          brief: "Find equal groups around your home and write them as multiplication.",
          steps: [
            "Look for things that come in equal groups, like eggs in a carton, wheels on bikes or legs on chairs.",
            "Pick one. Count the groups. Then count how many are in one group.",
            "Write it as multiplication. For 4 chairs with 4 legs each, write 4 × 4 = 16.",
            "Check your product by skip counting.",
            "Make your own equal groups with spoons or coins. Ask someone to write the multiplication.",
          ],
        },
      ],
    },
    {
      id: "arrays",
      title: "Arrays",
      summary: "Equal rows make equal groups easy to see. Turning an array shows the order of the numbers doesn't change the product.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Rows and columns",
          blocks: [
            { type: "visual", visual: { kind: "array", rows: 3, cols: 5 }, alt: "An array of dots in 3 rows, with 5 dots in each row." },
            { type: "text", text: "An array puts things in equal rows." },
            { type: "text", text: "This array has 3 rows of 5. That is 3 × 5 = 15." },
            { type: "points", items: ["Rows go across.", "Columns go up and down.", "This array also has 5 columns of 3."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Turn it around",
          blocks: [
            {
              type: "visual",
              visual: { kind: "array", rows: 5, cols: 3 },
              alt: "The same array turned on its side: 5 rows, with 3 dots in each row.",
            },
            { type: "text", text: "Turn the array on its side. Now it shows 5 rows of 3." },
            { type: "text", text: "No dots were added or taken away. So 5 × 3 = 15 too." },
            { type: "text", text: "You can multiply two numbers in either order. The product is the same." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Arrays all around",
          blocks: [
            { type: "text", text: "Egg cartons, muffin pans and windows with many panes are often arrays." },
            {
              type: "visual",
              visual: { kind: "array", rows: 2, cols: 6 },
              alt: "An array of dots in 2 rows, with 6 dots in each row, like a carton of 12 eggs.",
            },
            { type: "text", text: "A carton of 12 eggs is 2 rows of 6: 2 × 6 = 12." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Count the rows",
          prompt: "An array has 4 rows with 7 in each row. Jump by sevens, one jump for each row. How many in all?",
          widget: { kind: "number-line", min: 0, max: 35, step: 7, start: 0, target: 28 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Same product?",
          prompt: "An array with 3 rows of 8 has 24 dots. Which of these arrays also have 24 dots? Sort them.",
          widget: {
            kind: "sorter",
            categories: ["24 dots", "Not 24 dots"],
            items: [
              { id: "a8x3", text: "8 rows of 3", answer: 0 },
              { id: "a4x6", text: "4 rows of 6", answer: 0 },
              { id: "a3x7", text: "3 rows of 7", answer: 1 },
              { id: "a2x12", text: "2 rows of 12", answer: 0 },
              { id: "a5x5", text: "5 rows of 5", answer: 1 },
              { id: "a6x4", text: "6 rows of 4", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "A garden has 4 rows of plants. Each row has 6 plants. How many plants are there?",
              choices: ["10", "24", "46"],
              answer: 1,
              hint: "Count by sixes, once for each row.",
              explain: "6, 12, 18, 24. So 4 × 6 = 24 plants.",
            },
            {
              id: "q2",
              prompt: "Ava knows that 7 × 3 = 21. What is 3 × 7?",
              choices: ["21", "37", "10"],
              answer: 0,
              hint: "Picture an array of 7 rows of 3 turned on its side.",
              explain: "Turning an array doesn't change how many dots it has. So 3 × 7 = 21 too.",
            },
            {
              id: "q3",
              prompt: "Which array has 12 dots?",
              choices: ["3 rows of 4", "3 rows of 5", "2 rows of 5"],
              answer: 0,
              hint: "Multiply the number of rows by the number in each row.",
              explain: "3 × 4 = 12. The others are 3 × 5 = 15 and 2 × 5 = 10.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Build arrays",
          brief: "Make every array you can with 12 small things.",
          steps: [
            "Count out 12 coins, beans or blocks.",
            "Make equal rows. Try 2 rows, then 3 rows, then 4 rows.",
            "For each array, write the multiplication, like 2 × 6 = 12.",
            "Try 5 rows. Do the rows come out equal?",
            "Draw your favorite array on paper and label its rows.",
          ],
        },
      ],
    },
    {
      id: "facts-patterns",
      title: "Facts with 2, 5 and 10",
      summary: "Use patterns to multiply by 2, 5 and 10, and see what happens with 0 and 1.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Times 2 is a double",
          blocks: [
            { type: "visual", visual: { kind: "array", rows: 2, cols: 8 }, alt: "An array of dots in 2 rows, with 8 dots in each row." },
            { type: "text", text: "2 × 8 means 2 groups of 8. That is double 8." },
            { type: "text", text: "8 + 8 = 16, so 2 × 8 = 16." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Times 5 and times 10",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 50, marks: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50] },
              alt: "A number line from 0 to 50 with a mark every 5.",
            },
            {
              type: "points",
              items: [
                "Count by tens: 10, 20, 30, 40. Each one ends in 0.",
                "Count by fives: 5, 10, 15, 20. Each one ends in 5 or 0.",
                "5 × 6 is half of 10 × 6. Half of 60 is 30, so 5 × 6 = 30.",
              ],
            },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Zero and one",
          blocks: [
            { type: "text", text: "1 × 9 means 1 group of 9. That is 9." },
            { type: "text", text: "0 × 9 means 0 groups of 9. That is 0." },
            { type: "points", items: ["Any number times 1 is that same number.", "Any number times 0 is 0."] },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Count by fives",
          prompt: "Find 7 × 5. Count by fives, 7 times. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 50, step: 5, start: 0, target: 35 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "True or false?",
          prompt: "Is each fact true or false? Sort them.",
          widget: {
            kind: "sorter",
            categories: ["True", "False"],
            items: [
              { id: "f2x9", text: "2 × 9 = 18", answer: 0 },
              { id: "f5x7", text: "5 × 7 = 30", answer: 1 },
              { id: "f10x4", text: "10 × 4 = 40", answer: 0 },
              { id: "f0x6", text: "0 × 6 = 6", answer: 1 },
              { id: "f1x8", text: "1 × 8 = 8", answer: 0 },
              { id: "f5x8", text: "5 × 8 = 40", answer: 0 },
              { id: "f2x7", text: "2 × 7 = 15", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 5 × 9?",
              choices: ["45", "40", "14"],
              answer: 0,
              hint: "Find 10 × 9 first. Then take half.",
              explain: "10 × 9 = 90. Half of 90 is 45. So 5 × 9 = 45.",
            },
            {
              id: "q2",
              prompt: "Liam has 0 boxes of crayons. Each box holds 8 crayons. How many crayons does he have?",
              choices: ["0", "8", "80"],
              answer: 0,
              hint: "How many groups are there?",
              explain: "0 groups of 8 is 0. So 0 × 8 = 0.",
            },
            {
              id: "q3",
              prompt: "Which number do you say when you count by fives?",
              choices: ["32", "35", "53"],
              answer: 1,
              hint: "Counting by fives lands on numbers that end in 5 or 0.",
              explain: "35 ends in 5, and 5 × 7 = 35. 32 and 53 end in 2 and 3.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Count coins by 5s and 10s",
          brief: "Use nickels and dimes to practice times 5 and times 10.",
          steps: [
            "Put 6 nickels in a row. A nickel is worth 5 cents. Paper coins work too.",
            "Count by fives to find the total. Write 6 × 5 = ___.",
            "Do the same with 6 dimes. A dime is worth 10 cents.",
            "Compare the totals. Is 6 × 5 half of 6 × 10?",
            "Count the pairs of shoes by your door. How many shoes is that? Write it as ___ × 2.",
          ],
        },
      ],
    },
    {
      id: "break-apart",
      title: "Break apart to multiply",
      summary: "Split a fact you don't know into two facts you do know, then add.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Split the array",
          blocks: [
            { type: "visual", visual: { kind: "array", rows: 6, cols: 7 }, alt: "An array of dots in 6 rows, with 7 dots in each row." },
            { type: "text", text: "Maybe you don't know 6 × 7 yet. Split each row of 7 into 5 and 2." },
            { type: "visual", visual: { kind: "array", rows: 6, cols: 5 }, alt: "The first part of the split: 6 rows of 5 dots." },
            { type: "visual", visual: { kind: "array", rows: 6, cols: 2 }, alt: "The second part of the split: 6 rows of 2 dots." },
            { type: "text", text: "6 × 5 = 30 and 6 × 2 = 12. Add them: 30 + 12 = 42." },
            { type: "text", text: "So 6 × 7 = 42." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Use facts you know",
          blocks: [
            {
              type: "points",
              items: [
                "Use fives: 7 × 8 = (7 × 5) + (7 × 3) = 35 + 21 = 56.",
                "Use doubles: 4 × 6 is double 2 × 6. Double 12 is 24.",
                "Use tens: 9 × 6 is one group of 6 less than 10 × 6. 60 − 6 = 54.",
              ],
            },
            { type: "text", text: "The parentheses show which parts to multiply first. Then add the parts." },
            { type: "text", text: "Pick the split that uses facts you already know." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "One more group",
          prompt: "Find 8 × 6. The marker starts at 40, which is 8 × 5. Jump 8 more to add one more group of 8.",
          widget: { kind: "number-line", min: 30, max: 60, step: 1, start: 40, target: 48 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Which splits work?",
          prompt: "Which of these are equal to 7 × 6? Sort each one.",
          widget: {
            kind: "sorter",
            categories: ["Equal to 7 × 6", "Not equal to 7 × 6"],
            items: [
              { id: "b51", text: "(7 × 5) + (7 × 1)", answer: 0 },
              { id: "b33", text: "(7 × 3) + (7 × 3)", answer: 0 },
              { id: "b56", text: "(7 × 5) + (7 × 6)", answer: 1 },
              { id: "b26", text: "(5 × 6) + (2 × 6)", answer: 0 },
              { id: "b44", text: "(7 × 4) + (7 × 4)", answer: 1 },
              { id: "b24", text: "(7 × 2) + (7 × 4)", answer: 0 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "To find 6 × 8, Noor splits 8 into 5 and 3. What does she add?",
              choices: ["6 × 5 and 6 × 3", "6 × 5 and 3", "6 + 5 and 6 + 3"],
              answer: 0,
              hint: "Both parts of the 8 still need to be multiplied by 6.",
              explain: "6 × 8 = (6 × 5) + (6 × 3) = 30 + 18 = 48.",
            },
            {
              id: "q2",
              prompt: "What is 9 × 7?",
              choices: ["63", "56", "72"],
              answer: 0,
              hint: "Find 10 × 7. Then take away one group of 7.",
              explain: "10 × 7 = 70. 70 − 7 = 63. So 9 × 7 = 63.",
            },
            {
              id: "q3",
              prompt: "4 × 7 is double 2 × 7. What is 4 × 7?",
              choices: ["14", "28", "21"],
              answer: 1,
              hint: "2 × 7 = 14. Now double it.",
              explain: "14 + 14 = 28. So 4 × 7 = 28.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Strategy cards",
          brief: "Make cards for the facts you are still learning, with a way to break each one apart.",
          steps: [
            "Write 6 facts you find hard on cards, one fact per card, like 7 × 8.",
            "On the back, write a way to split it, like (7 × 5) + (7 × 3).",
            "Work out the product and write it on the back too.",
            "Practice with someone at home for a few minutes each day.",
            "When you know a fact without turning the card, put it in a “know it” pile.",
          ],
        },
      ],
    },
  ],
};

/** Practice on the skill map that fits each lesson (lesson id → skill ids). */
export const practice: Record<string, string[]> = {
  "equal-groups": ["m.mult.groups"],
  arrays: ["m.mult.groups"],
  "facts-patterns": ["m.mult.easy"],
  "break-apart": ["m.mult.facts"],
};

export default multiplication;
