import type { CatalogueEntry } from "./types";

const addNumberLine: CatalogueEntry = {
  id: "math-add-number-line",
  title: "Adding on the number line",
  summary: "Start at a number, then jump forward to add.",
  subject: "math",
  grade: "1",
  locale: "en",
  lessons: [
    {
      id: "jump-forward",
      title: "Start, then jump",
      summary: "Put your finger on the first number. Jump forward to add the second.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Numbers in a row",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 10, marks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
              alt: "A number line from 0 to 10, with a mark at every number.",
            },
            { type: "text", text: "A number line puts numbers in order." },
            { type: "points", items: ["Numbers get bigger as you go right.", "One jump to the right adds 1."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Count the jumps",
          blocks: [
            { type: "text", text: "To add 3 + 5, start at 3. Then jump 5 times." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 3, max: 8, marks: [3, 4, 5, 6, 7, 8] },
              alt: "A short number line from 3 to 8, with a mark at every number. There are 5 spaces between 3 and 8.",
            },
            { type: "text", text: "Each jump crosses one space. You land on 8, so 3 + 5 = 8." },
            { type: "points", items: ["Do not count the number you start on.", "Count each jump: 4, 5, 6, 7, 8."] },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Jump to add",
          prompt: "Start at 3. Jump 5 more. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 20, step: 1, start: 3, target: 8 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Jump past 10",
          prompt: "Start at 9. Jump 6 more. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 20, step: 1, start: 9, target: 15 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Start at 4. Jump 3 more. Where do you land?",
              choices: ["6", "7", "8"],
              answer: 1,
              hint: "Put your finger on 4. Say the next number with each jump.",
              explain: "From 4, the jumps land on 5, 6, 7. So 4 + 3 = 7.",
            },
            {
              id: "q2",
              prompt: "Mia adds 3 + 3. She counts 3, 4, 5. She says 5. What went wrong?",
              choices: ["She counted the 3 she started on.", "She jumped too far."],
              answer: 0,
              hint: "Look at the first number Mia said. Was that a jump?",
              explain: "Mia counted the 3 she started on. Start on 3, then jump: 4, 5, 6. So 3 + 3 = 6.",
            },
            {
              id: "q3",
              prompt: "You have 8 crayons. You get 4 more. How many do you have now?",
              choices: ["11", "12", "13"],
              answer: 1,
              hint: "Start at 8 on the number line. Make 4 jumps.",
              explain: "From 8, jump 4 times: 9, 10, 11, 12. You have 12 crayons.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "A number line on the floor",
          brief: "Make a number line you can walk on.",
          steps: [
            "Write 0 to 10 on 11 pieces of paper, one number each.",
            "Lay them on the floor in order, one step apart.",
            "A grown-up says a problem, like 2 + 5.",
            "Stand on 2. Take 5 steps forward. Say where you land.",
            "Now you make up a problem for the grown-up to walk.",
          ],
        },
      ],
    },
    {
      id: "bigger-first",
      title: "Start with the bigger number",
      summary: "You can add in any order. Starting with the bigger number means fewer jumps.",
      minutes: 8,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Fewer jumps",
          blocks: [
            { type: "text", text: "2 + 9 and 9 + 2 both make 11." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 9, max: 11, marks: [9, 10, 11] },
              alt: "A short number line from 9 to 11. There are 2 spaces between 9 and 11.",
            },
            { type: "text", text: "Start at 9 and jump 2: 10, 11. That is faster than 9 jumps from 2." },
            { type: "points", items: ["You can add in any order.", "Start with the bigger number. Then you make fewer jumps."] },
          ],
        },
        {
          id: "s2",
          kind: "interactive",
          title: "Find 3 + 8",
          prompt: "Find 3 + 8. The marker starts on 8, the bigger number. Jump 3 more.",
          widget: { kind: "number-line", min: 0, max: 20, step: 1, start: 8, target: 11 },
        },
        {
          id: "s3",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "To find 2 + 7, which way has fewer jumps?",
              choices: ["Start at 2. Jump 7.", "Start at 7. Jump 2."],
              answer: 1,
              hint: "The number you jump tells how many jumps. Which is fewer, 7 or 2?",
              explain: "Starting at 7 takes only 2 jumps: 8, 9. Both ways land on 9.",
            },
            {
              id: "q2",
              prompt: "Does 4 + 6 land on the same number as 6 + 4?",
              choices: ["Yes", "No"],
              answer: 0,
              hint: "Try both on a number line. Where does each one land?",
              explain: "Both land on 10. You can add in either order.",
            },
          ],
        },
      ],
    },
    {
      id: "jump-to-ten",
      title: "Jump to 10 first",
      summary: "Split a jump into two parts: up to 10, then the rest.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Stop at 10 on the way",
          blocks: [
            { type: "text", text: "To add 8 + 5, you can stop at 10 first." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 8, max: 13, marks: [8, 9, 10, 11, 12, 13] },
              alt: "A number line from 8 to 13. Every number has a mark.",
            },
            { type: "points", items: ["From 8, jump 2 to get to 10.", "5 is 2 and 3. So jump 3 more.", "You land on 13. So 8 + 5 = 13."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Try 7 + 6",
          blocks: [
            { type: "text", text: "Start at 7. It takes 3 jumps to get to 10." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 7, max: 13, marks: [7, 10, 13] },
              alt: "A number line from 7 to 13. It has marks only at 7, 10 and 13. 10 is halfway between 7 and 13.",
            },
            { type: "text", text: "6 is 3 and 3. From 10, jump 3 more to 13." },
            { type: "text", text: "So 7 + 6 = 13." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Find 9 + 4",
          prompt: "Find 9 + 4. Jump 1 to get to 10. Then jump the rest.",
          widget: { kind: "number-line", min: 0, max: 20, step: 1, start: 9, target: 13 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Find 8 + 6",
          prompt: "Find 8 + 6. Jump to 10 first. Then jump the rest.",
          widget: { kind: "number-line", min: 0, max: 20, step: 1, start: 8, target: 14 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "You are on 7. How many jumps to get to 10?",
              choices: ["3", "4", "10"],
              answer: 0,
              hint: "Put your finger on 7. Count each jump until you reach 10.",
              explain: "From 7, the jumps land on 8, 9, 10. That is 3 jumps.",
            },
            {
              id: "q2",
              prompt: "For 8 + 5, you jump 2 to get to 10. How many more jumps?",
              choices: ["2", "3", "5"],
              answer: 1,
              hint: "You need 5 jumps in all. You already made 2.",
              explain: "5 is 2 and 3. After 10, jump 3 more to land on 13.",
            },
            {
              id: "q3",
              prompt: "What is 9 + 6?",
              choices: ["14", "15", "16"],
              answer: 1,
              hint: "Jump 1 to get to 10. Then jump the rest.",
              explain: "From 9, jump 1 to 10. Then jump 5 more to 15.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Fill the 10",
          brief: "Use an egg carton to add by filling up 10.",
          steps: [
            "Ask a grown-up to cut 2 cups off an egg carton.",
            "Now it has 10 cups. Put 8 beans in, one per cup.",
            "Add 5 more beans. Fill the empty cups first.",
            "The carton is full. That is 10. Count the beans left over.",
            "Say it: 10 and 3 make 13. Now try 7 + 6.",
          ],
        },
        {
          id: "s7",
          kind: "interactive",
          title: "Build 9 + 6 with blocks",
          prompt: "Find 9 + 6. Fill the 10 first, then add the rest. Show the answer with blocks: a ten rod for the full 10, and ones for the rest.",
          widget: { kind: "place-value", target: 15 },
        },
      ],
    },
    {
      id: "how-many-more",
      title: "How many more?",
      summary: "Count the jumps between two numbers to find how many more.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "How many more?",
          blocks: [
            { type: "text", text: "Tom has 5 stickers. Ana has 9." },
            { type: "text", text: "How many more stickers does Ana have?" },
            { type: "text", text: "Start at 5. Count the jumps to 9." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 5, max: 9, marks: [5, 6, 7, 8, 9] },
              alt: "A number line from 5 to 9. Every number has a mark. There are 4 spaces between 5 and 9.",
            },
            { type: "text", text: "There are 4 jumps. Ana has 4 more stickers." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Count jumps, not marks",
          blocks: [
            {
              type: "points",
              items: ["Start on the smaller number.", "Jump until you land on the bigger number.", "Count each jump. Do not count where you start."],
            },
            { type: "text", text: "The number of jumps tells how many more." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "From 7 to 12",
          prompt: "Lily has 7 shells. She wants 12. Jump from 7 to 12. Count each jump.",
          widget: { kind: "number-line", min: 0, max: 20, step: 1, start: 7, target: 12 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "From 9 to 15",
          prompt: "Kai has 15 cars. Sam has 9. Jump from 9 to 15. Count each jump.",
          widget: { kind: "number-line", min: 0, max: 20, step: 1, start: 9, target: 15 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Lily jumped from 7 to 12. How many jumps did she make?",
              choices: ["4", "5", "12"],
              answer: 1,
              hint: "8 is the first jump. Keep counting until 12.",
              explain: "The jumps land on 8, 9, 10, 11, 12. That is 5 jumps, so 12 is 5 more than 7.",
            },
            {
              id: "q2",
              prompt: "Ana has 6 grapes. Ben has 9 grapes. How many more does Ben have?",
              choices: ["3", "9", "15"],
              answer: 0,
              hint: "Start at 6. Count the jumps to 9.",
              explain: "From 6, the jumps land on 7, 8, 9. That is 3 jumps, so Ben has 3 more.",
            },
            {
              id: "q3",
              prompt: "Zoe counts from 4 to 7: 4, 5, 6, 7. She says 4 jumps. What went wrong?",
              choices: ["She counted the 4 she started on.", "She stopped too soon."],
              answer: 0,
              hint: "Was 4 a jump, or where she started?",
              explain: "4 is where Zoe started, not a jump. The jumps are 5, 6 and 7, so there are 3.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Two towers",
          brief: "Use two towers of blocks to see how many more.",
          steps: [
            "Build two towers of blocks. Make one taller.",
            "Count the blocks in each tower.",
            "Stand the towers side by side.",
            "Count the extra blocks at the top of the tall tower. That is how many more.",
            "Check on a number line. Start at the small number and count the jumps.",
          ],
        },
      ],
    },
  ],
};

export default addNumberLine;
