import type { CatalogueEntry } from "./types";

const hundredsTensOnes: CatalogueEntry = {
  id: "math-hundreds-tens-ones",
  title: "Hundreds, tens and ones",
  summary: "Build numbers to 1,000 with hundreds, tens and ones. Count by tens and hundreds, and compare.",
  subject: "math",
  grade: "2",
  locale: "en",
  lessons: [
    {
      id: "ten-tens",
      title: "Ten tens make a hundred",
      summary: "Group ones into tens. Group tens into a hundred.",
      minutes: 10,
      practice: ["m.place.tens", "m.skip.count"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Ones and tens",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 1, ones: 3 }, alt: "1 rod of ten and 3 single cubes." },
            { type: "text", text: "A small cube is 1. It is called a one." },
            { type: "text", text: "Snap 10 ones together to make a rod." },
            { type: "text", text: "A rod is 1 ten. 1 ten and 3 ones make 13." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "A hundred",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 10, ones: 0 }, alt: "10 rods of ten in a row." },
            { type: "text", text: "Count these rods by tens, up to 100." },
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 1, tens: 0, ones: 0 },
              alt: "1 flat square. It is as big as 10 rods side by side.",
            },
            { type: "text", text: "Put 10 tens together. You get 1 hundred." },
            { type: "points", items: ["10 ones make 1 ten.", "10 tens make 1 hundred."] },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Tens and ones",
          blocks: [
            { type: "visual", visual: { kind: "base-ten", tens: 4, ones: 6 }, alt: "4 rods of ten and 6 single cubes." },
            { type: "text", text: "4 tens is 40. 6 ones is 6." },
            { type: "text", text: "40 and 6 make 46." },
            { type: "text", text: "The 4 is in the tens place. The 6 is in the ones place." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Jump by tens",
          prompt: "Jump by tens from 0. Make 7 jumps. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 100, step: 10, start: 0, target: 70 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "How many tens make 1 hundred?",
              choices: ["1", "10", "100"],
              answer: 1,
              hint: "Count by tens to 100. How many tens did you say?",
              explain: "10, 20, 30, 40, 50, 60, 70, 80, 90, 100. That is 10 tens.",
            },
            {
              id: "q2",
              prompt: "How many ones are in 1 hundred?",
              choices: ["1", "10", "100"],
              answer: 2,
              hint: "1 hundred is 10 tens. Each ten is 10 ones.",
              explain: "10 tens of 10 ones each is 100 ones.",
            },
            {
              id: "q3",
              prompt: "What number is 6 tens and 4 ones?",
              choices: ["10", "46", "64"],
              answer: 2,
              hint: "6 tens is 60. Then add the ones.",
              explain: "6 tens is 60. 60 and 4 ones make 64.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Bundles of ten",
          brief: "Group a big pile into tens to count it.",
          steps: [
            "Get a big pile of dry pasta, straws or beans.",
            "Make groups of 10. Put each group in a cup.",
            "Count the cups by tens.",
            "Count the leftover ones.",
            "Write the number. 5 tens and 3 ones is 53.",
            "Got 10 cups? Ten tens make 100.",
          ],
        },
      ],
    },
    {
      id: "three-digits",
      title: "What each digit means",
      summary: "The place of a digit tells what it is worth.",
      minutes: 12,
      practice: ["m.place.1000"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Three places",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 2, tens: 4, ones: 3 },
              alt: "2 hundred flats, 4 ten rods and 3 single cubes.",
            },
            { type: "text", text: "2 hundreds, 4 tens and 3 ones make 243." },
            { type: "text", text: "We read it: two hundred forty-three." },
            { type: "points", items: ["The 2 means 2 hundreds, or 200.", "The 4 means 4 tens, or 40.", "The 3 means 3 ones, or 3."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Expanded form",
          blocks: [
            { type: "text", text: "We can write 243 as 200 + 40 + 3." },
            { type: "text", text: "This is called expanded form. It shows what each digit is worth." },
            { type: "text", text: "The same digits in new places make a new number." },
            { type: "text", text: "342 is 300 + 40 + 2." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Zero holds a place",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 3, tens: 0, ones: 5 },
              alt: "3 hundred flats, no ten rods and 5 single cubes.",
            },
            { type: "text", text: "This is 3 hundreds, 0 tens and 5 ones." },
            { type: "text", text: "We write 305. The 0 says there are no tens." },
            { type: "text", text: "Without the 0, it says 35. That is much less." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Where is the 4?",
          prompt: "Which place is the 4 in? Tap to sort each number.",
          widget: {
            kind: "sorter",
            categories: ["Hundreds", "Tens", "Ones"],
            items: [
              { id: "n427", text: "427", answer: 0 },
              { id: "n148", text: "148", answer: 1 },
              { id: "n304", text: "304", answer: 2 },
              { id: "n940", text: "940", answer: 1 },
              { id: "n492", text: "492", answer: 0 },
              { id: "n714", text: "714", answer: 2 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is the 6 in 362 worth?",
              choices: ["6", "60", "600"],
              answer: 1,
              hint: "Which place is the 6 in?",
              explain: "The 6 is in the tens place. 6 tens is 60.",
            },
            {
              id: "q2",
              prompt: "Which number has 2 hundreds, 0 tens and 7 ones?",
              choices: ["207", "27", "270"],
              answer: 0,
              hint: "Put each digit in its place: hundreds, tens, ones.",
              explain: "2 hundreds, 0 tens and 7 ones is 207.",
            },
            {
              id: "q3",
              prompt: "What is 500 + 30 + 8?",
              choices: ["538", "500308", "583"],
              answer: 0,
              hint: "500 is the hundreds. 30 is the tens. 8 is the ones.",
              explain: "5 hundreds, 3 tens and 8 ones make 538. Each place gets one digit.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Cents and place value",
          brief: "Use pennies, dimes and dollars to show a number.",
          steps: [
            "A penny is 1 cent. A dime is 10 cents.",
            "A dollar is 100 cents.",
            "Use real or play money. Show 1 dollar, 2 dimes and 5 pennies.",
            "How many cents is that? Write the number.",
            "Now show 203 cents. Do you need any dimes?",
          ],
        },
      ],
    },
    {
      id: "skip-count",
      title: "Count by tens and hundreds",
      summary: "Find 10 more, 10 less, 100 more and 100 less.",
      minutes: 12,
      practice: ["m.skip.count"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "10 more, 10 less",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 2, tens: 3, ones: 4 },
              alt: "2 hundred flats, 3 ten rods and 4 single cubes. They show 234.",
            },
            { type: "text", text: "Add 1 ten to 234. You get 244." },
            { type: "text", text: "Only the tens digit changes. It goes up by 1." },
            { type: "text", text: "Take 1 ten away from 234. You get 224." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "100 more, 100 less",
          blocks: [
            { type: "text", text: "Add 1 hundred to 234. You get 334." },
            { type: "text", text: "Now the hundreds digit goes up by 1." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 1000, marks: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] },
              alt: "A number line from 0 to 1,000. It has a mark at every hundred.",
            },
            { type: "text", text: "On this line, each mark is 100 more." },
            { type: "text", text: "Take 1 hundred away from 234. You get 134." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Past a hundred",
          blocks: [
            {
              type: "visual",
              visual: { kind: "number-line", min: 180, max: 210, marks: [180, 190, 200, 210] },
              alt: "A number line marked 180, 190, 200 and 210.",
            },
            { type: "text", text: "Count by tens: 180, 190, 200, 210." },
            { type: "text", text: "190 is 1 hundred and 9 tens. Add 1 ten." },
            { type: "text", text: "Now there are 10 tens. They make 1 more hundred." },
            { type: "text", text: "So 190 + 10 = 200." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Count past 200",
          prompt: "Start at 170. Count by tens 4 times. Where do you land?",
          widget: { kind: "number-line", min: 100, max: 300, step: 10, start: 170, target: 210 },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Jump by hundreds",
          prompt: "Start at 400. Jump 300 more. Where do you land?",
          widget: { kind: "number-line", min: 0, max: 1000, step: 100, start: 400, target: 700 },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What is 10 more than 452?",
              choices: ["453", "462", "552"],
              answer: 1,
              hint: "Count on by ten from 452. What do you say next?",
              explain: "The tens digit goes from 5 to 6. 452 + 10 = 462.",
            },
            {
              id: "q2",
              prompt: "What is 100 less than 608?",
              choices: ["508", "598", "607"],
              answer: 0,
              hint: "Take 1 hundred away from 608. How many hundreds are left?",
              explain: "The hundreds digit goes from 6 to 5. 608 − 100 = 508.",
            },
            {
              id: "q3",
              prompt: "Count by tens: 370, 380, 390. What comes next?",
              choices: ["391", "400", "3100"],
              answer: 1,
              hint: "390 is 3 hundreds and 9 tens. Add 1 ten.",
              explain: "Now there are 10 tens. They make 1 more hundred. 390 + 10 = 400.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "The 10 more game",
          brief: "A game of 10 and 100 more or less.",
          steps: [
            "Write a three-digit number, like 345.",
            "A grown-up picks a rule, like 100 less.",
            "Write the new number. Say which digit changed.",
            "Take turns giving and solving.",
            "Try 395 and 10 more. What happens to the digits?",
          ],
        },
      ],
    },
    {
      id: "compare",
      title: "Compare three-digit numbers",
      summary: "Compare the hundreds first. Then the tens. Then the ones.",
      minutes: 12,
      practice: ["m.compare.1000"],
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Hundreds first",
          blocks: [
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 3, tens: 1, ones: 2 },
              alt: "3 hundred flats, 1 ten rod and 2 single cubes. They show 312.",
            },
            {
              type: "visual",
              visual: { kind: "base-ten", hundreds: 2, tens: 9, ones: 8 },
              alt: "2 hundred flats, 9 ten rods and 8 single cubes. They show 298.",
            },
            { type: "text", text: "312 has 3 hundreds. 298 has only 2." },
            { type: "text", text: "So 312 is greater, even though 298 has more tens." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "When the hundreds match",
          blocks: [
            { type: "text", text: "Compare 456 and 437." },
            { type: "text", text: "Both have 4 hundreds. So look at the tens." },
            { type: "text", text: "5 tens is more than 3 tens. So 456 is greater." },
            { type: "points", items: ["Same hundreds? Compare the tens.", "Same tens too? Compare the ones."] },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "The symbols",
          blocks: [
            { type: "points", items: ["> means greater than: 456 > 437.", "< means less than: 437 < 456.", "= means equal to: 500 = 500."] },
            { type: "text", text: "The open side faces the greater number." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Less or greater than 500",
          prompt: "Is each number less than 500 or greater than 500? Tap to sort.",
          widget: {
            kind: "sorter",
            categories: ["Less than 500", "Greater than 500"],
            items: [
              { id: "n498", text: "498", answer: 0 },
              { id: "n512", text: "512", answer: 1 },
              { id: "n509", text: "509", answer: 1 },
              { id: "n490", text: "490", answer: 0 },
              { id: "n601", text: "601", answer: 1 },
              { id: "n399", text: "399", answer: 0 },
              { id: "n95", text: "95", answer: 0 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which is greater, 389 or 412?",
              choices: ["389", "412"],
              answer: 1,
              hint: "Compare the hundreds first.",
              explain: "412 has 4 hundreds. 389 has 3 hundreds. So 412 is greater.",
            },
            {
              id: "q2",
              prompt: "Which one is true?",
              choices: ["251 < 215", "251 = 215", "251 > 215"],
              answer: 2,
              hint: "The hundreds match. Now compare the tens.",
              explain: "Both have 2 hundreds. 5 tens is more than 1 ten. So 251 > 215.",
            },
            {
              id: "q3",
              prompt: "Kai says 102 is greater than 98. Is he right?",
              choices: ["Yes", "No"],
              answer: 0,
              hint: "How many hundreds does each number have?",
              explain: "Yes. 102 has 1 hundred. 98 has no hundreds. So 102 is greater.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Greatest number game",
          brief: "Make the greatest number you can from 3 digit cards.",
          steps: [
            "Write the digits 0 to 9 on 10 small cards.",
            "Mix them up. Each player takes 3 cards.",
            "Make the greatest number you can with your cards.",
            "Read both numbers out loud. Whose is greater?",
            "Write it with >, < or =.",
          ],
        },
      ],
    },
  ],
};

export default hundredsTensOnes;
