import type { CatalogueEntry } from "./types";

const fraccionesEs: CatalogueEntry = {
  id: "math-fractions-es",
  title: "Fracciones: partes de un entero",
  summary: "Corta un entero en partes iguales, nombra las partes y encuéntralas en una recta numérica.",
  subject: "math",
  grade: "3",
  locale: "es",
  lessons: [
    {
      id: "halves-quarters",
      title: "Medios y cuartos",
      summary: "Corta un entero en 2 y en 4 partes iguales, y nombra cada parte.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Un entero, en partes iguales",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 1, shaded: 1 }, alt: "Una barra que es un solo entero, toda sombreada." },
            { type: "text", text: "Esto es un entero. Una fracción es una parte de un entero." },
            { type: "visual", visual: { kind: "fraction", parts: 2, shaded: 1 }, alt: "La misma barra cortada en 2 partes iguales. 1 parte está sombreada." },
            { type: "text", text: "Córtalo en 2 partes iguales. Cada parte es un medio. Se escribe 1/2." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Cuartos",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 1 }, alt: "La misma barra cortada en 4 partes iguales. 1 parte está sombreada." },
            { type: "text", text: "Corta el mismo entero en 4 partes iguales. Cada parte es un cuarto: 1/4." },
            {
              type: "points",
              items: [
                "El número de abajo dice en cuántas partes iguales está dividido el entero.",
                "El número de arriba dice de cuántas de esas partes hablamos.",
              ],
            },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Haz tres cuartos",
          prompt: "Corta la barra en 4 partes iguales. Luego sombrea 3.",
          widget: { kind: "fraction-bar", parts: 1, shaded: 0, target: { parts: 4, shaded: 3 } },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Dos cuartos",
          prompt: "Muestra 2/4. Fíjate bien: ¿es la misma cantidad que 1/2?",
          widget: { kind: "fraction-bar", parts: 2, shaded: 1, target: { parts: 4, shaded: 2 } },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Una pizza está cortada en 4 rebanadas iguales. Te comes 1 rebanada. ¿Qué fracción de la pizza te comiste?",
              choices: ["1/2", "1/4", "4/1", "1/3"],
              answer: 1,
              hint: "Cuenta todas las rebanadas iguales. Ese número va abajo.",
              explain: "Hay 4 rebanadas iguales y te comiste 1, así que te comiste 1/4.",
            },
            {
              id: "q2",
              prompt: "Del mismo sándwich, ¿qué es más: 1/2 o 1/4?",
              choices: ["1/2", "1/4", "Son iguales"],
              answer: 0,
              hint: "Imagina que cortas el sándwich en más pedazos. ¿Qué pasa con el tamaño de cada pedazo?",
              explain: "Al cortarlo en 4, los pedazos son más pequeños que al cortarlo en 2, así que 1/2 es más.",
            },
            {
              id: "q3",
              prompt: "Una barra está cortada en 4 pedazos, pero los pedazos son de distintos tamaños. ¿Un pedazo es 1/4 de la barra?",
              choices: ["Sí", "No"],
              answer: 1,
              hint: "Las fracciones necesitan partes que sean todas del mismo tamaño.",
              explain: "1/4 quiere decir una de 4 partes iguales. Los pedazos de distintos tamaños no son cuartos.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Fracciones en casa",
          brief: "Busca algo que puedas repartir en partes iguales: un sándwich, una hoja de papel o una tortilla.",
          steps: [
            "Dóblalo o córtalo en 2 partes iguales. Di: cada parte es un medio.",
            "Dóblalo o córtalo otra vez para que queden 4 partes iguales. Di: cada parte es un cuarto.",
            "Junta 3 partes para mostrar 3/4.",
            "Muéstrale a alguien por qué 2/4 es la misma cantidad que 1/2.",
          ],
        },
      ],
    },
    {
      id: "thirds-sixths-eighths",
      title: "Tercios, sextos y octavos",
      summary: "Más maneras de cortar el mismo entero, y por qué más partes quiere decir partes más pequeñas.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Tercios",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 1 }, alt: "Una barra cortada en 3 partes iguales. 1 parte está sombreada." },
            { type: "text", text: "Corta un entero en 3 partes iguales. Cada parte es un tercio: 1/3." },
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 2 }, alt: "La misma barra cortada en 3 partes iguales. 2 partes están sombreadas." },
            { type: "text", text: "Sombrea 2 de las 3 partes y tienes dos tercios: 2/3." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Sextos y octavos",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 6, shaded: 1 }, alt: "La misma barra cortada en 6 partes iguales. 1 parte está sombreada." },
            { type: "text", text: "Corta el entero en 6 partes iguales. Cada parte es un sexto: 1/6." },
            { type: "visual", visual: { kind: "fraction", parts: 8, shaded: 1 }, alt: "La misma barra cortada en 8 partes iguales. 1 parte está sombreada." },
            { type: "text", text: "Córtalo en 8 partes iguales. Cada parte es un octavo: 1/8." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Más partes, partes más pequeñas",
          blocks: [
            { type: "text", text: "Mientras más partes iguales cortes en un entero, más pequeña es cada parte." },
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 1 }, alt: "Una barra cortada en 3 partes iguales. 1 parte está sombreada." },
            {
              type: "visual",
              visual: { kind: "fraction", parts: 8, shaded: 1 },
              alt: "Una barra del mismo largo cortada en 8 partes iguales. 1 parte está sombreada. Es mucho más angosta que el tercio sombreado de arriba.",
            },
            {
              type: "points",
              items: ["1/3 es más grande que 1/6.", "1/6 es más grande que 1/8.", "El entero sigue del mismo tamaño. Solo cambian las partes."],
            },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Haz cinco octavos",
          prompt: "Muestra 5/8 de la barra.",
          widget: { kind: "fraction-bar", parts: 1, shaded: 0, target: { parts: 8, shaded: 5 } },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuál es el pedazo más pequeño del mismo pastel?",
              choices: ["1/3", "1/6", "1/8"],
              answer: 2,
              hint: "Piensa en cortar el pastel para 3 personas o para 8 personas.",
              explain: "Si cortas el pastel en 8 pedazos iguales, los pedazos son los más pequeños. Por eso 1/8 es el más pequeño.",
            },
            {
              id: "q2",
              prompt: "Un sándwich está cortado en 3 partes iguales. Te comes 2. ¿Qué fracción te comiste?",
              choices: ["2/3", "3/2", "1/3"],
              answer: 0,
              hint: "El número de abajo cuenta todas las partes iguales.",
              explain: "Hay 3 partes iguales y te comiste 2, así que te comiste 2/3.",
            },
            {
              id: "q3",
              prompt: "Mia dice que 1/8 es más grande que 1/3 porque 8 es más grande que 3. ¿Tiene razón?",
              choices: ["Sí", "No"],
              answer: 1,
              hint: "Imagina una barra cortada en 8 partes y la misma barra cortada en 3. ¿Qué parte es más ancha?",
              explain: "No. Los octavos son más pequeños que los tercios del mismo entero, así que 1/8 es menor que 1/3.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Tiras de papel",
          brief: "Dobla tiras de papel para comparar tercios, sextos y octavos.",
          steps: [
            "Corta tres tiras de papel, todas del mismo tamaño.",
            "Dobla la primera tira en 3 partes iguales. Colorea 1 parte: eso es 1/3.",
            "Dobla la segunda tira por la mitad y luego en 3 partes. Ahora tiene 6 partes iguales.",
            "Dobla la tercera tira por la mitad tres veces. Ahora tiene 8 partes iguales.",
            "Pon las tiras una junto a la otra. ¿Qué es más ancho: 1/3, 1/6 o 1/8?",
          ],
        },
      ],
    },
    {
      id: "number-line",
      title: "Fracciones en la recta numérica",
      summary: "Una fracción también es un número. Encuéntrala entre 0 y 1.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "De una barra a una recta",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 3 }, alt: "Una barra cortada en 4 partes iguales con 3 sombreadas." },
            { type: "text", text: "Estira la barra hasta que sea una recta que empieza en 0 y termina en 1." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 1, marks: [0, 0.25, 0.5, 0.75, 1], denominator: 4 },
              alt: "Una recta numérica de 0 a 1 dividida en 4 saltos iguales, marcada con 0, 1/4, 2/4, 3/4 y 1.",
            },
            { type: "text", text: "Cada salto igual es 1/4. Con tres saltos desde 0 llegas a 3/4." },
          ],
        },
        {
          id: "s2",
          kind: "interactive",
          title: "Llega a tres cuartos",
          prompt: "Mueve el marcador a 3/4.",
          widget: { kind: "number-line", min: 0, max: 1, step: 0.25, start: 0, target: 0.75, denominator: 4 },
        },
        {
          id: "s3",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Una recta de 0 a 1 está dividida en 4 saltos iguales. ¿Dónde está 1/4?",
              choices: ["Después de 1 salto", "Después de 4 saltos", "Justo en el medio"],
              answer: 0,
              hint: "El número de arriba cuenta los saltos desde 0.",
              explain: "1/4 está a un salto igual desde 0.",
            },
            {
              id: "q2",
              prompt: "¿Qué fracción está justo a la mitad entre 0 y 1?",
              choices: ["1/4", "2/4", "3/4"],
              answer: 1,
              hint: "A la mitad quiere decir la mitad de los saltos.",
              explain: "2/4 son dos de cuatro saltos iguales: justo en el medio. Es el mismo punto que 1/2.",
            },
          ],
        },
      ],
    },
    {
      id: "comparing",
      title: "Comparar fracciones",
      summary: "Usa dibujos y la recta numérica para saber qué fracción es mayor.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Partes del mismo tamaño",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 3 }, alt: "Una barra cortada en 4 partes iguales con 3 sombreadas." },
            { type: "visual", visual: { kind: "fraction", parts: 4, shaded: 1 }, alt: "La misma barra cortada en 4 partes iguales con 1 sombreada." },
            { type: "text", text: "Las dos barras están cortadas en cuartos, así que las partes son del mismo tamaño." },
            { type: "text", text: "3 partes son más que 1 parte, así que 3/4 es mayor que 1/4." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "El mismo número de partes",
          blocks: [
            { type: "visual", visual: { kind: "fraction", parts: 3, shaded: 2 }, alt: "Una barra cortada en 3 partes iguales con 2 sombreadas." },
            { type: "visual", visual: { kind: "fraction", parts: 8, shaded: 2 }, alt: "La misma barra cortada en 8 partes iguales con 2 sombreadas." },
            { type: "text", text: "Las dos barras muestran 2 partes. Pero los tercios son más grandes que los octavos." },
            { type: "text", text: "Por eso 2/3 es mayor que 2/8." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "En la recta numérica",
          blocks: [
            { type: "text", text: "En una recta numérica, la fracción que está más a la derecha es mayor." },
            {
              type: "visual",
              visual: { kind: "number-line", min: 0, max: 1, marks: [0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1], denominator: 8 },
              alt: "Una recta numérica de 0 a 1 dividida en 8 saltos iguales, marcada con 0, 1/8, 2/8, 3/8, 4/8, 5/8, 6/8, 7/8 y 1.",
            },
            { type: "text", text: "7/8 está a la derecha de 2/8, así que 7/8 es mayor." },
            {
              type: "points",
              items: ["Compara solo partes del mismo entero.", "La mitad de una pizza grande es más que la mitad de una pizza pequeña."],
            },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Elige la mayor",
          prompt: "¿Cuál es mayor, 3/8 o 5/8? Mueve el marcador a la mayor.",
          widget: { kind: "number-line", min: 0, max: 1, step: 0.125, start: 0, target: 0.625, denominator: 8 },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Cuál es mayor: 2/8 o 5/8?",
              choices: ["2/8", "5/8", "Son iguales"],
              answer: 1,
              hint: "Las partes son del mismo tamaño. Cuenta cuántas partes tiene cada una.",
              explain: "Las dos son octavos, así que las partes son del mismo tamaño. 5 partes son más que 2 partes, así que 5/8 es mayor.",
            },
            {
              id: "q2",
              prompt: "¿Cuál es mayor: 1/3 o 1/6?",
              choices: ["1/3", "1/6"],
              answer: 0,
              hint: "Las dos son una sola parte. ¿Qué entero se cortó en menos pedazos, y más grandes?",
              explain: "Un entero cortado en 3 tiene partes más grandes que uno cortado en 6. Por eso 1/3 es mayor.",
            },
            {
              id: "q3",
              prompt: "Lee se comió 1/2 de una pizza pequeña. Kim se comió 1/2 de una pizza grande. ¿Comieron la misma cantidad?",
              choices: ["Sí, 1/2 siempre es la misma cantidad", "No, Kim comió más"],
              answer: 1,
              hint: "Imagina la mitad de cada pizza. ¿Los dos enteros son del mismo tamaño?",
              explain: "La mitad de una pizza grande es más que la mitad de una pequeña. Solo puedes comparar fracciones del mismo entero.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "¿Qué pedazo es más grande?",
          brief: "Compara medios y cuartos con dos cosas del mismo tamaño.",
          steps: [
            "Busca dos hojas de papel del mismo tamaño. También sirven rebanadas de pan o tortillas.",
            "Dobla o corta una en 2 partes iguales. Dobla o corta la otra en 4 partes iguales.",
            "Pon 1/2 junto a 1/4. ¿Cuál es más grande?",
            "Pon 2/4 junto a 1/2. ¿Qué notas?",
            "Pregúntale a alguien en casa: ¿prefieres 1/2 o 1/4 de un postre? Explica por qué.",
          ],
        },
      ],
    },
  ],
};

export default fraccionesEs;
