import type { CatalogueEntry } from "./types";

// Habilidades de práctica de este curso: s.water.cycle, s.states.matter (src/practice/science/early.ts).
const waterCycleEs: CatalogueEntry = {
  id: "science-water-cycle-es",
  title: "El ciclo del agua",
  summary: "La evaporación, la condensación y la precipitación mueven el agua entre el océano, el aire y la tierra, en forma de hielo, agua líquida y vapor. El Sol impulsa todo el viaje.",
  subject: "science",
  grade: "5",
  locale: "es",
  lessons: [
    {
      id: "three-states",
      title: "Los tres estados del agua",
      summary: "El agua puede ser hielo sólido, agua líquida o un gas invisible llamado vapor de agua.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Hielo y agua líquida",
          blocks: [
            { type: "text", text: "El agua está hecha de partículas demasiado pequeñas para verlas. Según cómo se acomodan, el agua es sólida, líquida o gaseosa." },
            { type: "visual", visual: { kind: "particles", state: "solid" }, alt: "Partículas en filas ordenadas, cada una fija en su lugar: hielo." },
            { type: "text", text: "En el hielo, las partículas están fijas en un patrón. Vibran, pero no cambian de lugar. Por eso el hielo mantiene su forma." },
            {
              type: "visual",
              visual: { kind: "particles", state: "liquid" },
              alt: "Partículas juntas y tocándose, pero desordenadas en el fondo de la caja: agua líquida.",
            },
            { type: "text", text: "En el agua líquida, las partículas siguen juntas pero se deslizan unas sobre otras. Por eso el agua fluye y toma la forma del recipiente." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "El vapor de agua",
          blocks: [
            {
              type: "visual",
              visual: { kind: "particles", state: "gas" },
              alt: "Pocas partículas muy separadas por toda la caja, con mucho espacio vacío entre ellas: vapor de agua.",
            },
            { type: "text", text: "En el vapor de agua, las partículas están muy separadas y se mueven rápido en todas direcciones. El vapor de agua es un gas." },
            { type: "text", text: "El vapor de agua es invisible. Ahora mismo, el aire que te rodea tiene un poco." },
            {
              type: "text",
              text: "La nube blanca que sale de una olla hirviendo no es vapor. Son gotitas de agua líquida que se formaron cuando el vapor se enfrió en el aire.",
            },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Cambios de estado",
          blocks: [
            {
              type: "points",
              items: [
                "Fusión: de sólido a líquido. El hielo se derrite cuando pasa de 0 °C.",
                "Solidificación: de líquido a sólido. El agua se congela a 0 °C.",
                "Evaporación: de líquido a gas, desde la superficie. Ocurre a cualquier temperatura, y más rápido con calor.",
                "Ebullición: a 100 °C, al nivel del mar, el agua se vuelve vapor en todo el líquido y hace burbujas.",
                "Condensación: de gas a líquido, cuando el vapor de agua se enfría.",
              ],
            },
            { type: "text", text: "El calor empuja estos cambios en un sentido. El frío los empuja de regreso." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Derrite el hielo",
          prompt: "Esta agua empieza como hielo a −20 °C. Caliéntala hasta que se derrita y sea agua líquida. Fíjate cómo cambian las partículas.",
          widget: { kind: "states-of-matter", startC: -20, target: "liquid" },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Haz hervir el agua",
          prompt: "Ahora calienta el agua líquida hasta que toda se vuelva vapor. En este modelo eso pasa a 100 °C, el punto de ebullición al nivel del mar.",
          widget: { kind: "states-of-matter", startC: 20, target: "gas" },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué estado del agua es invisible?",
              choices: ["El hielo", "El agua líquida", "El vapor de agua"],
              answer: 2,
              hint: "¿Cuál es un gas, como el aire?",
              explain: "El vapor de agua es un gas y es invisible. El hielo y el agua líquida sí se ven, aunque sean transparentes.",
            },
            {
              id: "q2",
              prompt: "¿Qué es la nube blanca que sale de una olla de agua hirviendo?",
              choices: ["Vapor de agua, un gas", "Gotitas de agua líquida", "Aire que escapó de las burbujas"],
              answer: 1,
              hint: "El vapor de agua es invisible. Entonces, ¿qué es lo que ves?",
              explain: "El vapor invisible se enfría al subir y se condensa en gotitas de líquido. Esas gotitas forman la nube blanca. Las burbujas del agua hirviendo son vapor, no aire.",
            },
            {
              id: "q3",
              prompt: "Un charco se seca en un día fresco y nublado. ¿Cómo puede ser, si el agua hierve a 100 °C?",
              choices: ["Los charcos hierven a una temperatura más baja", "El aire frío jala el agua hacia arriba", "El agua se evapora a cualquier temperatura"],
              answer: 2,
              hint: "Hervir y evaporarse no son lo mismo.",
              explain: "Para hervir hacen falta 100 °C, pero para evaporarse no. Las partículas de la superficie escapan al aire todo el tiempo, y más rápido si hace calor, viento o el aire está seco.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "¿Adónde se fue el agua?",
          brief: "Compara qué tan rápido se evapora el agua en distintos lugares.",
          steps: [
            "Pon la misma cantidad de agua, unas 2 cucharadas, en tres vasos transparentes iguales.",
            "Marca el nivel del agua por fuera de cada vaso con un marcador.",
            "Pon un vaso al sol, otro a la sombra y otro dentro de una caja cerrada.",
            "Revisa una vez al día durante 3 a 5 días, y marca el nuevo nivel cada vez.",
            "¿Qué vaso perdió agua más rápido? ¿Qué crees que hizo la diferencia?",
          ],
        },
      ],
    },
    {
      id: "evaporation-condensation",
      title: "Sube al aire y regresa",
      summary: "El Sol evapora el agua y la sube al aire. Cuando el vapor se enfría, se condensa en gotitas.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Evaporación",
          blocks: [
            {
              type: "text",
              text: "El Sol calienta océanos, lagos, ríos y charcos. Las partículas de agua de la superficie escapan al aire como vapor. Esto es la evaporación.",
            },
            { type: "text", text: "La mayor parte del vapor de agua del aire viene del océano." },
            { type: "text", text: "Cuando se evapora el agua del mar, la sal se queda atrás. Al aire solo sube el agua." },
            {
              type: "text",
              text: "Las plantas también agregan vapor. Suben el agua desde las raíces y la sueltan como vapor por agujeritos de sus hojas. Esto se llama transpiración.",
            },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Condensación",
          blocks: [
            { type: "text", text: "Cuando el vapor de agua se enfría, sus partículas se frenan y se juntan en gotitas de líquido. Esto es la condensación." },
            {
              type: "points",
              items: [
                "Se forman gotas por fuera de un vaso de limonada fría.",
                "El espejo del baño se empaña después de una ducha caliente.",
                "Por la mañana, si la noche fue fresca y despejada, aparece rocío en el pasto.",
                "Las nubes se forman arriba en el cielo, donde el aire está frío.",
              ],
            },
            { type: "text", text: "Las gotas del vaso frío no salieron de adentro. Vienen del vapor de agua del aire." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Enfría el vapor",
          prompt:
            "Esto es vapor de agua a 120 °C. Enfríalo hasta que se condense en líquido. El modelo muestra agua pura; el vapor mezclado con el aire se condensa a temperaturas mucho más bajas, pero enfriarlo también lo vuelve líquido.",
          widget: { kind: "states-of-matter", startC: 120, target: "liquid" },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Evaporación o condensación?",
          prompt: "¿Cada caso es evaporación (de líquido a gas) o condensación (de gas a líquido)?",
          widget: {
            kind: "sorter",
            categories: ["Evaporación", "Condensación"],
            items: [
              { id: "can", text: "Se forman gotas en una lata de jugo fría", answer: 1 },
              { id: "clothes", text: "La ropa mojada se seca en el tendedero", answer: 0 },
              { id: "puddle", text: "Un charco desaparece en una tarde de sol", answer: 0 },
              { id: "mirror", text: "El espejo se empaña después de bañarte", answer: 1 },
              { id: "dew", text: "El pasto amanece cubierto de rocío", answer: 1 },
              { id: "sweat", text: "El sudor se seca en tu piel", answer: 0 },
              { id: "hair", text: "El pelo mojado se seca sin secadora", answer: 0 },
              { id: "cloud", text: "Se forma una nube en el cielo", answer: 1 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "El agua del mar es salada. ¿Por qué la lluvia es dulce y no salada?",
              choices: ["Las nubes filtran la sal de la lluvia", "Solo se evapora el agua, no la sal", "La lluvia viene solo de lagos y ríos"],
              answer: 1,
              hint: "Piensa en qué sube al aire cuando se evapora el agua del mar.",
              explain: "Solo las partículas de agua escapan al aire como vapor. La sal se queda en el mar, así que las nubes y la lluvia son de agua dulce. La mayor parte de la lluvia empieza como agua del mar.",
            },
            {
              id: "q2",
              prompt: "Aparecen gotas de agua por fuera de un vaso frío. ¿De dónde vienen?",
              choices: ["Del agua que se salió a través del vidrio", "Del frío, que fabricó agua nueva", "Del vapor de agua del aire"],
              answer: 2,
              hint: "¿Se formarían las mismas gotas en un vaso tibio?",
              explain: "El vapor de agua del aire tocó el vaso frío, se enfrió y se condensó en gotas. El vaso no gotea.",
            },
            {
              id: "q3",
              prompt: "¿Cómo agregan vapor de agua al aire las plantas?",
              choices: ["Por agujeritos de sus hojas", "Solo por sus flores", "No agregan nada de vapor"],
              answer: 0,
              hint: "El agua sube desde las raíces hasta las hojas.",
              explain: "Las plantas suben agua desde la tierra y sueltan vapor por agujeritos de sus hojas. Esto es la transpiración.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Lluvia en un frasco",
          brief: "Haz que haya evaporación, condensación y precipitación dentro de un frasco.",
          steps: [
            "Pide a un adulto que llene un frasco de vidrio con agua caliente de la llave, hasta un tercio.",
            "Tapa el frasco con un plato pequeño y pon unos cubitos de hielo encima del plato.",
            "Observa la parte de abajo del plato durante 5 a 10 minutos.",
            "Busca gotas que se forman y vuelven a caer al frasco. Las gotas que caen de nuevo son precipitación.",
            "Dibuja el frasco. Marca dónde hubo evaporación, condensación y precipitación.",
          ],
        },
      ],
    },
    {
      id: "around-the-cycle",
      title: "Lluvia, nieve y el viaje de regreso",
      summary: "Las gotitas de las nubes crecen hasta caer. El agua se acumula en océanos, lagos, ríos, hielo y bajo tierra, y el ciclo sigue.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Precipitación",
          blocks: [
            { type: "text", text: "Una nube está hecha de miles de millones de gotitas de agua o cristales de hielo. Son tan pequeños que el aire que sube los mantiene flotando." },
            { type: "text", text: "Las gotitas chocan, se unen y crecen. Cuando pesan demasiado para flotar, caen. El agua que cae de las nubes es la precipitación." },
            {
              type: "points",
              items: [
                "Lluvia: gotas de agua líquida.",
                "Nieve: cristales de hielo que crecieron en nubes frías.",
                "Gránulos de hielo: gotas de lluvia que se congelan en bolitas al caer por aire frío.",
                "Granizo: bolas de hielo que crecen dentro de las tormentas, mientras vientos fuertes las suben y las bajan.",
              ],
            },
          ],
        },
        {
          id: "s2",
          kind: "interactive",
          title: "Congélala",
          prompt: "En lo alto de una nube fría, las gotas pueden congelarse. Enfría esta agua hasta que se vuelva hielo. En el modelo, el agua es sólida a 0 °C o menos.",
          widget: { kind: "states-of-matter", startC: 10, target: "solid" },
        },
        {
          id: "s3",
          kind: "slide",
          title: "Acumulación",
          blocks: [
            { type: "text", text: "La precipitación cae sobre la tierra, los lagos y el océano. La gravedad la jala cuesta abajo." },
            {
              type: "points",
              items: [
                "Escurrimiento: el agua corre por el suelo hacia arroyos, ríos, lagos y el mar.",
                "Agua subterránea: parte del agua se mete en la tierra y llena huecos en las rocas. Los pozos y los manantiales la sacan de nuevo.",
                "Hielo: en lugares fríos, el agua puede quedarse congelada en glaciares durante miles de años antes de derretirse.",
              ],
            },
            { type: "text", text: "El agua que se junta en océanos, lagos, ríos, hielo y bajo tierra es la acumulación. Desde ahí, el ciclo sigue." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Qué mueve el ciclo",
          blocks: [
            { type: "text", text: "La energía del Sol evapora el agua y la sube al cielo. La gravedad la hace caer y la lleva cuesta abajo hasta el mar." },
            { type: "text", text: "El ciclo no tiene principio ni fin. No crea agua nueva ni la gasta. Mueve la misma agua, una y otra vez." },
            {
              type: "text",
              text: "Una vuelta puede ser rápida o lenta. En promedio, el agua pasa unos 9 días en el aire, pero puede pasar miles de años en el agua subterránea profunda o en el hielo.",
            },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿Qué paso es?",
          prompt: "¿Qué paso del ciclo del agua es cada uno?",
          widget: {
            kind: "sorter",
            categories: ["Evaporación", "Condensación", "Precipitación", "Acumulación"],
            items: [
              { id: "snow", text: "Cae nieve en las montañas", answer: 2 },
              { id: "lake", text: "El Sol calienta un lago y el agua sube como vapor", answer: 0 },
              { id: "runoff", text: "El agua de lluvia corre por la calle hasta un río", answer: 3 },
              { id: "fog", text: "En una mañana fría se forma neblina sobre un lago", answer: 1 },
              { id: "hail", text: "El granizo rebota en la acera", answer: 2 },
              { id: "ground", text: "La nieve derretida se mete en la tierra y se vuelve agua subterránea", answer: 3 },
              { id: "ocean", text: "El agua del mar se vuelve vapor en un día caluroso", answer: 0 },
              { id: "cloud", text: "El vapor se enfría allá arriba y forma una nube", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué paso viene justo después de la evaporación?",
              choices: ["La condensación", "La precipitación", "La acumulación"],
              answer: 0,
              hint: "Cuando el vapor sube, se enfría. ¿Qué hace el vapor al enfriarse?",
              explain: "El vapor sube, se enfría y se condensa en las gotitas que forman las nubes. Después viene la precipitación.",
            },
            {
              id: "q2",
              prompt: "¿De qué están hechas las nubes?",
              choices: ["De vapor de agua, el agua en forma de gas", "De gotitas de agua o de hielo", "De aire frío que se ve blanco"],
              answer: 1,
              hint: "Las nubes se ven. ¿Se ve el vapor de agua?",
              explain: "El vapor de agua es invisible. Las nubes se ven porque están hechas de gotitas de agua o cristales de hielo.",
            },
            {
              id: "q3",
              prompt: "¿De dónde saca su energía el ciclo del agua?",
              choices: ["Del calor del interior de la Tierra", "De las olas del mar", "Del Sol"],
              answer: 2,
              hint: "¿Qué calienta el agua para que se evapore?",
              explain: "La energía del Sol produce la evaporación, que sube el agua al aire. La gravedad la hace bajar de nuevo.",
            },
            {
              id: "q4",
              prompt: "¿El agua que tomas hoy es agua nueva?",
              choices: ["No, ya dio muchas vueltas", "Sí, la lluvia hace agua nueva cada día", "Sí, la compañía de agua la fabrica"],
              answer: 0,
              hint: "¿El ciclo del agua fabrica agua o la mueve?",
              explain: "El ciclo del agua mueve la misma agua. El agua de tu vaso ya fue mar, nube y lluvia muchas veces. La lluvia es agua vieja que vuelve a caer, y la compañía de agua la limpia, pero no la fabrica.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "El viaje de una gota",
          brief: "Dibuja una historieta que siga a una gota de agua por todo el ciclo.",
          steps: [
            "Dobla una hoja en 6 cuadros.",
            "Elige dónde empieza tu gota: el mar, un charco, un glaciar o tu vaso de agua.",
            "En cada cuadro, dibuja el siguiente paso de la gota y ponle nombre: evaporación, condensación, precipitación o acumulación.",
            "Dale a tu gota un desvío: se mete en la tierra, se congela en un glaciar o la absorben las raíces de un árbol.",
            "Termina la historieta donde empezó tu gota, lista para dar otra vuelta.",
          ],
        },
      ],
    },
    {
      id: "where-water-is",
      title: "Dónde está el agua de la Tierra",
      summary: "Casi toda el agua de la Tierra es salada. La mayor parte del agua dulce está congelada o bajo tierra, así que la que podemos usar con facilidad es poca.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Salada y dulce",
          blocks: [
            { type: "text", text: "Unas 97 de cada 100 gotas de agua de la Tierra son saladas. Casi toda esa agua salada está en el océano." },
            { type: "text", text: "Menos de 3 de cada 100 gotas son de agua dulce, la que necesitan las personas, los cultivos y casi todos los animales de tierra." },
            { type: "text", text: "La lluvia es dulce porque la sal se queda atrás cuando se evapora el agua del mar. El ciclo del agua convierte agua de mar en agua dulce." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Dónde está el agua dulce",
          blocks: [
            {
              type: "points",
              items: [
                "Unas dos terceras partes del agua dulce de la Tierra están congeladas en glaciares y capas de hielo.",
                "Casi todo el resto es agua subterránea, bajo tierra, entre el suelo y las rocas.",
                "Solo 1 de cada 100 gotas de agua dulce, más o menos, está en lagos, ríos, el aire y los seres vivos.",
              ],
            },
            { type: "text", text: "Por eso cavamos pozos, construimos presas y cuidamos que el agua no se ensucie ni se desperdicie." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "¿Cuánta está congelada?",
          prompt: "Piensa en toda el agua dulce de la Tierra como un entero. ¿Más o menos qué fracción está congelada? Mueve el marcador ahí.",
          widget: { kind: "number-line", min: 0, max: 1, step: 1 / 3, start: 0, target: 2 / 3, denominator: 3 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Salada o dulce?",
          prompt: "¿El agua de cada lugar es salada o dulce?",
          widget: {
            kind: "sorter",
            categories: ["Salada", "Dulce"],
            items: [
              { id: "rain", text: "La lluvia", answer: 1 },
              { id: "pacific", text: "El océano Pacífico", answer: 0 },
              { id: "glacier", text: "Un glaciar", answer: 1 },
              { id: "caribbean", text: "El mar Caribe", answer: 0 },
              { id: "river", text: "Un río", answer: 1 },
              { id: "iceberg", text: "Un iceberg que se desprendió de un glaciar", answer: 1 },
              { id: "dead-sea", text: "El mar Muerto", answer: 0 },
              { id: "snowmelt", text: "Un lago de montaña que se llena con nieve derretida", answer: 1 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Más o menos cuánta agua de la Tierra es salada?",
              choices: ["Unas 3 de cada 100 gotas", "Unas 50 de cada 100 gotas", "Unas 97 de cada 100 gotas"],
              answer: 2,
              hint: "Piensa en cuánto de la Tierra cubre el océano, y qué tan profundo es.",
              explain: "Unas 97 de cada 100 gotas son saladas, casi todas en el océano. Menos de 3 son de agua dulce.",
            },
            {
              id: "q2",
              prompt: "¿Dónde está la mayor parte del agua dulce de la Tierra?",
              choices: ["Congelada en glaciares y hielo", "Bajo tierra, entre suelo y rocas", "En lagos, ríos y nubes"],
              answer: 0,
              hint: "Vuelve a mirar dónde está el agua dulce. ¿Qué lugar tiene la parte más grande?",
              explain: "Unas dos terceras partes del agua dulce están congeladas, sobre todo en el hielo de la Antártida y Groenlandia. Casi todo el resto es agua subterránea. Los lagos y ríos tienen solo una parte muy pequeña.",
            },
            {
              id: "q3",
              prompt: "Una familia saca agua de un pozo. ¿De dónde viene esa agua?",
              choices: ["De un lago subterráneo que nunca se llena de nuevo", "Del agua que se metió en la tierra", "Del agua de mar que se filtra desde el océano"],
              answer: 1,
              hint: "¿Adónde va el agua cuando se mete en la tierra?",
              explain: "Un pozo llega al agua subterránea, que se metió en el suelo y las rocas después de la lluvia o el deshielo. Si se saca más rápido de lo que la lluvia la repone, el pozo se puede secar.",
            },
            {
              id: "q4",
              prompt: "El ciclo del agua nunca gasta el agua. Entonces, ¿por qué cuidamos el agua dulce?",
              choices: ["El agua dulce útil es escasa y puede ensuciarse", "El ciclo del agua dejará de funcionar si usamos demasiada", "El agua que se va por el desagüe desaparece de la Tierra"],
              answer: 0,
              hint: "¿Cuánta agua de la Tierra es dulce y fácil de alcanzar?",
              explain: "La cantidad total de agua no cambia, pero el agua dulce de un lugar puede escasear o ensuciarse. Lagos, ríos y pozos se reponen solo al ritmo de la lluvia y la nieve.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "¿De dónde viene nuestra agua?",
          brief: "Averigua de dónde viene el agua de tu casa y cuánta sale de una llave.",
          steps: [
            "Pregunta a un adulto de dónde viene el agua de tu casa: de un río, un lago, una presa o un pozo.",
            "Abre una llave durante 10 segundos mientras un adulto junta el agua en una taza medidora o una jarra. Anota cuánta salió.",
            "Multiplica por 12 para saber cuánta saldría en 2 minutos, el tiempo que recomiendan los dentistas para cepillarse, si la llave quedara abierta.",
            "Haz una lista de tres maneras en que tu familia podría usar menos agua.",
            "Riega una planta con el agua que juntaste, para no desperdiciarla.",
          ],
        },
      ],
    },
  ],
};

export default waterCycleEs;
