import type { CatalogueEntry } from "./types";

// Practice skill this course teaches: s.energy.forms (src/practice/science/early.ts).
const energy: CatalogueEntry = {
  id: "science-energy",
  title: "Energy all around",
  summary: "Energy makes things move, light up, heat up and make sound. See how energy travels and changes form, and where ours comes from.",
  subject: "science",
  grade: "4",
  locale: "en",
  lessons: [
    {
      id: "what-energy-does",
      title: "What energy does",
      summary: "Energy is what it takes to make something move, light up, heat up or make a sound.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Energy makes things happen",
          blocks: [
            { type: "text", text: "Energy is what it takes to make something move or change. You cannot see energy itself, but you can see what it does." },
            {
              type: "points",
              items: [
                "A kicked ball flies across the field: motion energy.",
                "A bell rings: sound energy.",
                "A lamp glows: light energy.",
                "A stove burner gets hot: heat, which scientists call thermal energy.",
                "Wires carry power to a TV: electrical energy.",
              ],
            },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Stored energy",
          blocks: [
            { type: "text", text: "Some energy is stored, waiting to be used." },
            {
              type: "points",
              items: [
                "Food stores energy. Your body uses it to move, grow and stay warm.",
                "A battery stores energy and gives it out as electricity.",
                "Gasoline stores energy. A car engine releases it by burning the gasoline.",
                "A stretched rubber band stores energy. Let go, and it snaps back.",
                "A ball held up high stores energy. Let go, and it falls faster and faster.",
              ],
            },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "What kind of energy?",
          prompt: "What kind of energy does each one mainly show?",
          widget: {
            kind: "sorter",
            categories: ["Motion", "Sound", "Light", "Heat"],
            items: [
              { id: "skateboard", text: "A skateboard rolling down a ramp", answer: 0 },
              { id: "ball", text: "A ball flying through the air", answer: 0 },
              { id: "dog", text: "A dog barking", answer: 1 },
              { id: "phone", text: "A phone ringing", answer: 1 },
              { id: "star", text: "A star shining in the night sky", answer: 2 },
              { id: "firefly", text: "A firefly glowing", answer: 2 },
              { id: "cocoa", text: "A warm mug of cocoa", answer: 3 },
              { id: "sidewalk", text: "A sunny sidewalk that feels hot", answer: 3 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which one has motion energy?",
              choices: ["A rolling bowling ball", "A book sitting on a shelf", "A rock on the ground"],
              answer: 0,
              hint: "Motion energy is the energy of things that are moving.",
              explain: "The bowling ball is moving, so it has motion energy. The book and the rock are still.",
            },
            {
              id: "q2",
              prompt: "Where does your body get the energy to run and play?",
              choices: ["From the food you eat", "From the air you breathe out", "From your shoes"],
              answer: 0,
              hint: "What does your body need more of after a long game?",
              explain: "Food stores energy. Your body releases that energy to move, grow and stay warm.",
            },
            {
              id: "q3",
              prompt: "You stretch a rubber band and let go. It snaps back fast. Where did its energy come from?",
              choices: ["The energy stored when you stretched it", "It made energy from nothing", "From the air in the room"],
              answer: 0,
              hint: "What did you do to the rubber band before you let go?",
              explain: "Stretching the rubber band stored energy in it. Letting go changed that stored energy into motion. Never aim a rubber band at anyone.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Energy hunt",
          brief: "Find energy at work in your home.",
          steps: [
            "Walk through your home and find 8 things that are using energy.",
            "For each one, write what it does: moves, lights up, heats up or makes sound. Some do more than one.",
            "Circle the ones that run on electricity. Put a star next to the ones that use stored energy, like food or batteries.",
            "Do not touch plugs, outlets or hot surfaces while you look.",
          ],
        },
      ],
    },
    {
      id: "speed-and-energy",
      title: "Faster means more energy",
      summary: "The faster something moves, the more motion energy it has. When things collide, energy moves between them.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Speed and energy",
          blocks: [
            { type: "text", text: "A ball rolling fast has more motion energy than the same ball rolling slowly." },
            { type: "text", text: "You can tell when it hits something. The fast ball knocks things farther and makes a louder sound." },
            { type: "text", text: "Weight matters too. At the same speed, a bowling ball has more motion energy than a tennis ball." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Collisions pass energy along",
          blocks: [
            { type: "text", text: "When a moving object hits another object, some of its energy moves to the other object." },
            {
              type: "points",
              items: [
                "A rolling ball hits a still ball. The first ball slows down, and the second ball starts to roll.",
                "A hammer hits a nail. The nail moves into the wood.",
                "In every collision, some energy also becomes sound and heat. That is why crashes are noisy.",
              ],
            },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "More or less motion energy?",
          prompt: "These come in pairs. In each pair, which one has more motion energy?",
          widget: {
            kind: "sorter",
            categories: ["More motion energy", "Less motion energy"],
            items: [
              { id: "kick", text: "A soccer ball kicked hard", answer: 0 },
              { id: "roll", text: "The same soccer ball rolled gently", answer: 1 },
              { id: "highway", text: "A car driving on the highway", answer: 0 },
              { id: "parking", text: "The same car creeping into a parking space", answer: 1 },
              { id: "downhill", text: "A bike racing downhill", answer: 0 },
              { id: "walked", text: "The same bike being walked", answer: 1 },
              { id: "bowling", text: "A bowling ball rolling fast", answer: 0 },
              { id: "tennis", text: "A tennis ball rolling at the same speed", answer: 1 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Two toy cars are exactly the same. Car A rolls fast. Car B rolls slowly. Which has more motion energy?",
              choices: ["Car A", "Car B", "They have the same"],
              answer: 0,
              hint: "Same cars, different speeds.",
              explain: "The cars are the same, so the faster one has more motion energy. It would hit a wall harder and louder.",
            },
            {
              id: "q2",
              prompt: "A rolling marble hits a marble that is sitting still. What happens to the energy?",
              choices: [
                "Some moves to the still marble, so it starts to roll",
                "All of it disappears",
                "The still marble stays put and the first one speeds up",
              ],
              answer: 0,
              hint: "What do you see the second marble do?",
              explain: "In the collision, motion energy moves from the first marble to the second. A little also becomes the click you hear, and a tiny bit of heat.",
            },
            {
              id: "q3",
              prompt: "Why does a car crash make a loud noise?",
              choices: ["Some motion energy changes into sound", "Sound was stored in the engine", "The crash makes brand-new energy"],
              answer: 0,
              hint: "In a collision, motion energy changes into other forms.",
              explain: "In a crash, some motion energy changes into sound and some into heat. Energy is never made from nothing.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Ramp test",
          brief: "Test how a ball's speed changes what it can do.",
          steps: [
            "Lean a stiff piece of cardboard on a stack of books to make a ramp.",
            "Lay a paper cup on its side at the bottom of the ramp, with the open end facing up the ramp.",
            "Roll a ball or a marble down from a low ramp. Measure how far the cup slides.",
            "Add books to make the ramp higher. Roll the same ball and measure again.",
            "Try each height 3 times. Did the faster ball push the cup farther?",
          ],
        },
      ],
    },
    {
      id: "energy-moves-changes",
      title: "Energy moves and changes",
      summary: "Energy travels as light, heat, sound and electric current, and machines change it from one form to another.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Four ways energy travels",
          blocks: [
            {
              type: "points",
              items: [
                "Light: sunlight carries energy from the Sun to Earth.",
                "Heat: heat flows from a hot stove into a pan, then into the food.",
                "Sound: a drum's vibrations carry energy through the air to your ears.",
                "Electric current: wires carry electrical energy from a power plant to your home.",
              ],
            },
            { type: "text", text: "Heat always flows from warmer things to cooler things. A cold drink warms up because heat flows into it from the room." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Machines change energy",
          blocks: [
            { type: "text", text: "Many machines take in energy in one form and give it out in another." },
            {
              type: "points",
              items: [
                "A lamp: electrical energy in, light out, plus some heat.",
                "A toaster: electrical energy in, heat out.",
                "A fan: electrical energy in, motion out.",
                "A speaker: electrical energy in, sound out.",
                "A solar panel: light in, electrical energy out.",
              ],
            },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Never used up",
          blocks: [
            { type: "text", text: "A fan does not make cold air. It moves air. Moving air carries heat away from your skin, so you feel cooler. The fan's motor even warms up a little." },
            { type: "text", text: "Energy is never made from nothing, and it never disappears. It only moves or changes form." },
            { type: "text", text: "When a battery is used up, its stored energy has changed into other forms, like light, motion and heat." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "What comes out?",
          prompt: "Each machine takes in electrical energy. What does it mainly give out?",
          widget: {
            kind: "sorter",
            categories: ["Light", "Heat", "Motion", "Sound"],
            items: [
              { id: "night-light", text: "A night-light", answer: 0 },
              { id: "flashlight", text: "A flashlight", answer: 0 },
              { id: "toaster", text: "A toaster", answer: 1 },
              { id: "burner", text: "An electric stove burner", answer: 1 },
              { id: "fan", text: "A ceiling fan", answer: 2 },
              { id: "drill", text: "An electric drill", answer: 2 },
              { id: "doorbell", text: "A doorbell", answer: 3 },
              { id: "speaker", text: "A speaker", answer: 3 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "A solar panel changes which form of energy into electrical energy?",
              choices: ["Light", "Sound", "Motion"],
              answer: 0,
              hint: "What does the Sun send to the panel?",
              explain: "A solar panel takes in sunlight and gives out electrical energy.",
            },
            {
              id: "q2",
              prompt: "You leave a metal spoon in hot soup. Soon the handle feels warm. Why?",
              choices: ["Heat flowed from the soup through the spoon", "Cold flowed out of the spoon", "The spoon made its own heat"],
              answer: 0,
              hint: "Heat flows from warmer things to cooler things.",
              explain: "Heat moved from the hot soup into the spoon and along the metal to the handle. Heat flows; cold does not.",
            },
            {
              id: "q3",
              prompt: "An electric fan is on. What does it mostly change electrical energy into?",
              choices: ["Motion", "Cold", "Light"],
              answer: 0,
              hint: "What do the blades do?",
              explain: "The motor spins the blades, so electrical energy becomes motion. Moving air helps you feel cooler, but the fan does not make cold.",
            },
            {
              id: "q4",
              prompt: "A toy car stops when its batteries run down. What happened to the energy?",
              choices: ["It changed into motion, sound and heat while the car ran", "It disappeared", "It is all still in the batteries"],
              answer: 0,
              hint: "Energy never disappears. It changes form.",
              explain: "While the car ran, the batteries' stored energy changed into motion, sound and heat. That energy spread out into the room.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Energy in, energy out",
          brief: "Follow the energy through one machine at home.",
          steps: [
            "Pick a machine at home, like a lamp, a blender, a toaster or a radio.",
            "Draw a box for the machine. Draw an arrow going in, and label the energy that goes in.",
            "Draw an arrow coming out for each form of energy that comes out. Remember sound and heat.",
            "With a grown-up, hold your hand near the machine, not on it, after it has run. Is it warm?",
            "Think one step back: where does the electricity come from before it reaches your home?",
          ],
        },
      ],
    },
    {
      id: "energy-resources",
      title: "Where our energy comes from",
      summary: "Some energy sources run out and some are refilled by nature. Every source has costs as well as benefits.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Fuels from long ago",
          blocks: [
            { type: "text", text: "Much of the electricity people use is made by burning coal, oil or natural gas." },
            { type: "text", text: "These are fossil fuels. They formed from the remains of plants and tiny sea creatures, buried for millions of years." },
            { type: "text", text: "Once we burn them, they are gone. They would take millions of years to form again, so they are nonrenewable." },
            { type: "text", text: "Burning them adds carbon dioxide to the air, which is warming Earth's climate. It can also make the air dirty to breathe." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Sources nature refills",
          blocks: [
            { type: "text", text: "Renewable sources are refilled by nature, so they do not run out." },
            {
              type: "points",
              items: [
                "Sunlight: solar panels change it into electricity.",
                "Wind: wind turns the blades of big turbines.",
                "Moving water: river water flowing through a dam spins turbines.",
                "Heat from inside Earth: in some places, hot water or steam from underground turns turbines.",
              ],
            },
            {
              type: "text",
              text: "Renewable sources have costs too. Wind and sunlight come and go, dams change rivers, and every power plant needs land and materials to build.",
            },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Renewable or nonrenewable?",
          prompt: "Will nature refill it, or will it run out once we use it?",
          widget: {
            kind: "sorter",
            categories: ["Renewable", "Nonrenewable"],
            items: [
              { id: "sunlight", text: "Sunlight", answer: 0 },
              { id: "wind", text: "Wind", answer: 0 },
              { id: "coal", text: "Coal", answer: 1 },
              { id: "oil", text: "Oil", answer: 1 },
              { id: "gas", text: "Natural gas", answer: 1 },
              { id: "river", text: "A flowing river", answer: 0 },
              { id: "gasoline", text: "Gasoline, which is made from oil", answer: 1 },
              { id: "earth-heat", text: "Heat from deep inside Earth", answer: 0 },
            ],
          },
        },
        {
          id: "s4",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Why is coal called nonrenewable?",
              choices: ["It takes millions of years to form, so once burned it is gone", "It is too heavy to move", "It only works at night"],
              answer: 0,
              hint: "How long did coal take to form?",
              explain: "Coal formed from plants buried millions of years ago. We burn it far faster than nature can make more.",
            },
            {
              id: "q2",
              prompt: "Which energy source is renewable?",
              choices: ["Wind", "Natural gas", "Oil"],
              answer: 0,
              hint: "Which one will nature keep refilling?",
              explain: "The wind keeps blowing because the Sun keeps heating Earth. Natural gas and oil are gone once they are burned.",
            },
            {
              id: "q3",
              prompt: "What is one problem with burning fossil fuels?",
              choices: ["It adds carbon dioxide to the air, which warms the climate", "It makes the Sun dimmer", "It uses up the wind"],
              answer: 0,
              hint: "Think about what goes into the air when something burns.",
              explain: "Burning fossil fuels releases carbon dioxide and other gases. Carbon dioxide traps heat, and it is warming Earth's climate.",
            },
            {
              id: "q4",
              prompt: "A town wants to get its electricity from wind turbines. What is one real drawback?",
              choices: ["The wind does not always blow", "Wind runs out after a few years", "Wind turbines burn coal"],
              answer: 0,
              hint: "Is the wind just as strong every day?",
              explain: "Wind is renewable, but it is not steady. A town that uses wind also needs other sources, or a way to store energy, for calm days.",
            },
          ],
        },
        {
          id: "s5",
          kind: "project",
          title: "Energy saver week",
          brief: "Make a plan to save energy at home for one week.",
          steps: [
            "With a grown-up, list the things in your home that use electricity.",
            "Pick three easy changes, like turning off lights in empty rooms or unplugging chargers you are not using.",
            "Make a chart with the days of the week. Check off each change on the days you do it.",
            "At the end of the week, talk about which change was easiest to keep doing, and why.",
          ],
        },
      ],
    },
  ],
};

export default energy;
