import type { CatalogueEntry } from "./types";

// Practice skills this course teaches: s.living, s.needs (src/practice/science/early.ts).
const living: CatalogueEntry = {
  id: "science-living",
  title: "Living and nonliving things",
  summary: "Living things grow and need food, water and air. Find out what is living and what is not.",
  subject: "science",
  grade: "K",
  locale: "en",
  lessons: [
    {
      id: "what-living-things-do",
      title: "What living things do",
      summary: "Living things grow. They need food, water and air. They make more living things.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Living things grow",
          blocks: [
            { type: "text", text: "A living thing grows and changes." },
            { type: "points", items: ["A puppy grows into a dog.", "A seed grows into a plant.", "A baby grows into a big kid."] },
            { type: "text", text: "You are a living thing. You are growing, too." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Living things need food, water and air",
          blocks: [
            { type: "text", text: "Living things need food, water and air." },
            { type: "points", items: ["Animals eat food.", "Plants use light to make their own food.", "Plants and animals both need water and air."] },
            { type: "text", text: "A plant with no water dries up." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Living things make more",
          blocks: [
            { type: "text", text: "Living things make more living things like them." },
            { type: "points", items: ["Dogs have puppies.", "Birds lay eggs. Chicks hatch out.", "Plants make seeds. Seeds grow into new plants."] },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "A rock is not living",
          blocks: [
            { type: "text", text: "A rock does not grow. It does not eat or drink." },
            { type: "text", text: "A rock never makes baby rocks. So a rock is not living." },
            { type: "text", text: "A toy car can move. But it does not grow. It is not living." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Living or not living?",
          prompt: "Is it living? Tap Living or Not living for each one.",
          widget: {
            kind: "sorter",
            categories: ["Living", "Not living"],
            items: [
              { id: "dog", text: "A dog", answer: 0 },
              { id: "rock", text: "A rock", answer: 1 },
              { id: "tree", text: "A tree", answer: 0 },
              { id: "spoon", text: "A spoon", answer: 1 },
              { id: "fish", text: "A fish", answer: 0 },
              { id: "ball", text: "A ball", answer: 1 },
              { id: "flower", text: "A flower growing in a garden", answer: 0 },
              { id: "shoe", text: "A shoe", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which one is living?",
              choices: ["A rock", "A cat", "A spoon"],
              answer: 1,
              hint: "Which one eats, drinks and grows?",
              explain: "A cat eats, drinks and grows. It can have kittens. A cat is living.",
            },
            {
              id: "q2",
              prompt: "A puppy gets bigger every week. What is it doing?",
              choices: ["Growing", "Melting", "Sleeping"],
              answer: 0,
              hint: "You get bigger every year, too.",
              explain: "The puppy is growing. Living things grow.",
            },
            {
              id: "q3",
              prompt: "What do plants and animals both need?",
              choices: ["Water and air", "Toys", "Shoes"],
              answer: 0,
              hint: "Think of a plant and a cat. What do both need?",
              explain: "Plants and animals both need water and air to live.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Living hunt",
          brief: "Look for living and nonliving things at home or outside.",
          steps: [
            "Walk around with a grown-up.",
            "Find 3 living things. Draw them.",
            "Find 3 things that are not living. Draw them, too.",
            "For each living thing, say how you know.",
          ],
        },
      ],
    },
    {
      id: "tricky-ones",
      title: "Tricky ones",
      summary: "Some things move but are not living. Some living things stay still.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Moving is not enough",
          blocks: [
            { type: "text", text: "A car moves. The wind moves. A river moves." },
            { type: "text", text: "But they do not grow. They never have babies." },
            { type: "text", text: "Moving does not make something living." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Still, but living",
          blocks: [
            { type: "text", text: "A tree cannot walk. But a tree is living." },
            { type: "points", items: ["It grows taller each year.", "It takes in water through its roots.", "It makes seeds that grow new trees."] },
            { type: "text", text: "A mushroom is living, too. It grows and makes more mushrooms." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Sleeping seeds",
          blocks: [
            { type: "text", text: "A seed looks a bit like a tiny pebble." },
            { type: "text", text: "But inside is a tiny plant. It is waiting." },
            { type: "text", text: "Give it water and a warm spot. It starts to grow." },
            { type: "text", text: "A seed is living." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Fire and clouds",
          blocks: [
            { type: "text", text: "Fire can get bigger. Clouds move and change shape." },
            { type: "text", text: "But fire never grows up or has babies. Clouds do not either." },
            { type: "text", text: "Fire and clouds are not living." },
            { type: "text", text: "Never touch fire. Fire can burn you." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Tricky sort",
          prompt: "These are tricky. Is each one living or not living?",
          widget: {
            kind: "sorter",
            categories: ["Living", "Not living"],
            items: [
              { id: "seed", text: "A seed", answer: 0 },
              { id: "robot", text: "A robot", answer: 1 },
              { id: "mushroom", text: "A mushroom", answer: 0 },
              { id: "cloud", text: "A cloud", answer: 1 },
              { id: "campfire", text: "A campfire", answer: 1 },
              { id: "tree", text: "A tall tree", answer: 0 },
              { id: "wind", text: "The wind", answer: 1 },
              { id: "snail", text: "A snail", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "A robot can walk and talk. Is it living?",
              choices: ["Yes", "No"],
              answer: 1,
              hint: "Can a robot grow or have babies?",
              explain: "People build robots. A robot never grows or has babies. It is not living.",
            },
            {
              id: "q2",
              prompt: "A bean seed sits in a jar. Is it living?",
              choices: ["Yes", "No"],
              answer: 0,
              hint: "What happens when you plant a seed and water it?",
              explain: "Inside the seed is a tiny plant. It is waiting to grow. A seed is living.",
            },
            {
              id: "q3",
              prompt: "Which one is living, but cannot walk?",
              choices: ["A tree", "A car", "The wind"],
              answer: 0,
              hint: "Which one grows taller every year?",
              explain: "A tree stays in one place. It still grows and makes seeds. It is living.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Wake up a seed",
          brief: "Show that a dry seed is living.",
          steps: [
            "Fold a wet paper towel. Put it inside a clear cup.",
            "Push a dry bean between the towel and the cup.",
            "Keep the towel wet. Look at the bean every day.",
            "After a few days, look for a tiny root.",
            "Tell a grown-up: is the bean living? How do you know?",
          ],
        },
      ],
    },
    {
      id: "what-they-need",
      title: "What plants and animals need",
      summary: "Animals need food, water and air. Plants need light, water and air.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "What animals need",
          blocks: [
            { type: "text", text: "Animals need food, water and air." },
            { type: "points", items: ["A cow eats grass.", "A dog drinks water.", "You breathe air all day and all night."] },
            { type: "text", text: "Animals cannot make food. They have to find it." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "What plants need",
          blocks: [
            { type: "text", text: "Plants need light, water and air." },
            { type: "text", text: "Plants do not eat. They make their own food." },
            { type: "text", text: "Leaves use light, air and water to make food." },
            { type: "text", text: "Roots take in water from the soil." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "A safe place",
          blocks: [
            { type: "text", text: "Many animals need a safe place to rest. It is called a shelter." },
            { type: "points", items: ["A bird builds a nest for its eggs.", "A fox digs a den.", "Some bears sleep in caves in winter."] },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Plants, animals or both?",
          prompt: "Who does this? Plants, animals, or both?",
          widget: {
            kind: "sorter",
            categories: ["Plants", "Animals", "Both"],
            items: [
              { id: "eats", text: "Eats food", answer: 1 },
              { id: "makes-food", text: "Makes its own food", answer: 0 },
              { id: "water", text: "Needs water", answer: 2 },
              { id: "air", text: "Needs air", answer: 2 },
              { id: "light", text: "Uses light to make food", answer: 0 },
              { id: "grows", text: "Grows", answer: 2 },
              { id: "roots", text: "Has roots", answer: 0 },
              { id: "hunts", text: "Walks, swims or flies to find food", answer: 1 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "What does a plant get from the Sun?",
              choices: ["Light", "Soil", "Water"],
              answer: 0,
              hint: "What do you see when the Sun comes up?",
              explain: "The Sun gives plants light. Plants use light to make food.",
            },
            {
              id: "q2",
              prompt: "Where does a plant get its food?",
              choices: ["It makes its own food", "It eats soil", "It eats bread"],
              answer: 0,
              hint: "Does a plant have a mouth?",
              explain: "Leaves use light, air and water to make food. Plants do not eat soil.",
            },
            {
              id: "q3",
              prompt: "A bird builds a nest. What does the nest give it?",
              choices: ["A safe place", "Food", "Water"],
              answer: 0,
              hint: "What does a bird put in its nest?",
              explain: "A nest is a shelter. It keeps eggs and chicks safe.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Light or dark?",
          brief: "Find out if a plant needs light.",
          steps: [
            "Get two small plants that look the same.",
            "Put one plant by a sunny window.",
            "Put the other plant in a dark closet.",
            "Give both plants the same water.",
            "Look at the leaves each day for a week.",
            "What changed? Then put both plants back in the light.",
          ],
        },
      ],
    },
    {
      id: "changing-homes",
      title: "Living things change their homes",
      summary: "Animals, plants and people change the places where they live.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Diggers and builders",
          blocks: [
            { type: "text", text: "Living things change the places where they live." },
            { type: "points", items: ["A squirrel digs holes to hide nuts.", "Worms dig tunnels in the soil.", "A bird builds a nest from twigs and grass."] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "A beaver makes a pond",
          blocks: [
            { type: "text", text: "A beaver chews down trees with its teeth." },
            { type: "text", text: "It piles sticks and mud across a stream. That is a dam." },
            { type: "text", text: "The water backs up behind the dam. It makes a pond." },
            { type: "text", text: "Now ducks and frogs can live there, too." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Plants change places, too",
          blocks: [
            { type: "text", text: "Tree roots grow under the ground." },
            { type: "text", text: "Big roots can push up and crack a sidewalk." },
            { type: "text", text: "Roots also hold soil in place when it rains." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "People change places, too",
          blocks: [
            { type: "text", text: "People are living things. We change places, too." },
            { type: "points", items: ["People build houses and roads.", "People cut down trees.", "People plant gardens and trees."] },
            { type: "text", text: "We can choose changes that help other living things." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Who made the change?",
          prompt: "Look at each change. Did a living thing make it?",
          widget: {
            kind: "sorter",
            categories: ["A living thing", "Not a living thing"],
            items: [
              { id: "nut-hole", text: "A hole where a squirrel hid a nut", answer: 0 },
              { id: "puddle", text: "A puddle after the rain", answer: 1 },
              { id: "pond", text: "A pond behind a beaver dam", answer: 0 },
              { id: "leaf-pile", text: "Leaves blown into a pile by the wind", answer: 1 },
              { id: "ant-tunnels", text: "Tunnels dug by ants", answer: 0 },
              { id: "sidewalk", text: "A sidewalk cracked by tree roots", answer: 0 },
              { id: "snow", text: "Snow piled up after a storm", answer: 1 },
              { id: "garden", text: "A garden that a family planted", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "How does a beaver change a stream?",
              choices: ["It builds a dam", "It drinks all the water", "It freezes the water"],
              answer: 0,
              hint: "Think of sticks and mud.",
              explain: "A beaver builds a dam of sticks and mud. The water makes a pond.",
            },
            {
              id: "q2",
              prompt: "Tree roots cracked a sidewalk. What made the change?",
              choices: ["A living thing", "The wind", "The rain"],
              answer: 0,
              hint: "Roots are part of something. What is it?",
              explain: "Roots are part of a tree. A tree is living. So a living thing made the change.",
            },
            {
              id: "q3",
              prompt: "Which change do people make?",
              choices: ["Building a road", "Digging a worm tunnel", "Building a nest of twigs"],
              answer: 0,
              hint: "Who drives cars on roads?",
              explain: "People build roads. Worms dig tunnels. Birds build nests.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Change detectives",
          brief: "Find changes that living things made near your home.",
          steps: [
            "Go outside with a grown-up.",
            "Look for holes, nests, chewed leaves or tracks.",
            "Look for a sidewalk cracked by roots.",
            "Draw one change. Who made it?",
            "Tell a grown-up how the change helps that living thing.",
          ],
        },
      ],
    },
  ],
};

export default living;
