import type { CatalogueEntry } from "./types";

// Practice skills this course teaches: s.water.cycle, s.states.matter (src/practice/science/early.ts).
const waterCycle: CatalogueEntry = {
  id: "science-water-cycle",
  title: "The water cycle",
  summary: "Evaporation, condensation and precipitation move water between the ocean, the air and the land, as ice, liquid and vapor. The Sun powers the whole trip.",
  subject: "science",
  grade: "5",
  locale: "en",
  lessons: [
    {
      id: "three-states",
      title: "Water's three states",
      summary: "Water can be solid ice, liquid water or an invisible gas called water vapor.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Ice and liquid water",
          blocks: [
            { type: "text", text: "Water is made of particles far too small to see. How they are arranged decides whether water is a solid, a liquid or a gas." },
            { type: "visual", visual: { kind: "particles", state: "solid" }, alt: "Particles in neat rows, each held in its place: ice." },
            { type: "text", text: "In ice, the particles are locked in a pattern. They jiggle but stay in place, so ice keeps its shape." },
            {
              type: "visual",
              visual: { kind: "particles", state: "liquid" },
              alt: "Particles close together and touching, but jumbled at the bottom of the box: liquid water.",
            },
            { type: "text", text: "In liquid water, the particles stay close but slide past each other, so water flows and takes the shape of its container." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Water vapor",
          blocks: [
            {
              type: "visual",
              visual: { kind: "particles", state: "gas" },
              alt: "A few particles spread far apart across the whole box, with lots of empty space between them: water vapor.",
            },
            { type: "text", text: "In water vapor, the particles are far apart and move fast in every direction. Water vapor is a gas." },
            { type: "text", text: "Water vapor is invisible. The air around you has some in it right now." },
            {
              type: "text",
              text: "The white cloud above a boiling kettle is not vapor. It is tiny drops of liquid water that formed when the vapor cooled in the air.",
            },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Changing state",
          blocks: [
            {
              type: "points",
              items: [
                "Melting: solid to liquid. Ice melts when it warms above 0 °C.",
                "Freezing: liquid to solid. Water freezes at 0 °C.",
                "Evaporation: liquid to gas at the surface. It happens at any temperature, faster when it is warm.",
                "Boiling: at 100 °C at sea level, water turns to vapor all through the liquid, making bubbles.",
                "Condensation: gas to liquid, when water vapor cools.",
              ],
            },
            { type: "text", text: "Heating drives these changes one way. Cooling drives them back." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Melt the ice",
          prompt: "This water starts as ice at −20 °C. Warm it until it melts into liquid water, and watch how the particles change.",
          widget: { kind: "states-of-matter", startC: -20, target: "liquid" },
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Boil the water",
          prompt: "Now heat liquid water until it all turns into vapor. In this model that happens at 100 °C, the boiling point at sea level.",
          widget: { kind: "states-of-matter", startC: 20, target: "gas" },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which state of water is invisible?",
              choices: ["Ice", "Liquid water", "Water vapor"],
              answer: 2,
              hint: "Which state is a gas, like the air?",
              explain: "Water vapor is a gas, and it is invisible. You can see ice and liquid water, even when they are clear.",
            },
            {
              id: "q2",
              prompt: "What is the white cloud above a pot of boiling water?",
              choices: ["Water vapor, a gas", "Tiny drops of liquid water", "Air that escaped from the bubbles"],
              answer: 1,
              hint: "Water vapor is invisible. So what could you be seeing?",
              explain: "The invisible vapor cools as it rises and condenses into tiny liquid drops. Those drops make the white cloud. The bubbles in boiling water are vapor, not air.",
            },
            {
              id: "q3",
              prompt: "A puddle dries up on a cool, cloudy day. How is that possible if water boils at 100 °C?",
              choices: ["Puddles boil at a lower temperature", "Cold air sucks it up like a straw", "Water evaporates at any temperature"],
              answer: 2,
              hint: "Boiling and evaporating are not the same thing.",
              explain: "Boiling needs 100 °C, but evaporation does not. Particles at the surface escape into the air all the time, faster when it is warm, windy or dry.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Where did the water go?",
          brief: "Compare how fast water evaporates in different places.",
          steps: [
            "Pour the same amount of water, about 2 tablespoons, into three clear cups that are the same.",
            "Mark the water level on the outside of each cup with a marker.",
            "Put one cup in a sunny spot, one in the shade, and one inside a closed box.",
            "Check once a day for 3 to 5 days, and mark the new level each time.",
            "Which cup lost water fastest? What do you think made the difference?",
          ],
        },
      ],
    },
    {
      id: "evaporation-condensation",
      title: "Up into the air and back",
      summary: "The Sun evaporates water into the air. When water vapor cools, it condenses into drops.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Evaporation",
          blocks: [
            { type: "text", text: "The Sun warms oceans, lakes, rivers and puddles. Water particles at the surface escape into the air as vapor. This is evaporation." },
            { type: "text", text: "Most of the water vapor in the air comes from the ocean." },
            { type: "text", text: "When ocean water evaporates, the salt stays behind. Only the water goes into the air." },
            {
              type: "text",
              text: "Plants add water vapor too. They pull water up from their roots and release vapor through tiny holes in their leaves. This is called transpiration.",
            },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Condensation",
          blocks: [
            { type: "text", text: "When water vapor cools, its particles slow down and cling together as tiny drops of liquid. This is condensation." },
            {
              type: "points",
              items: [
                "Drops form on the outside of a cold glass of lemonade.",
                "A bathroom mirror fogs up after a hot shower.",
                "Dew forms on grass on a cool, clear morning.",
                "Clouds form high in the sky, where the air is cold.",
              ],
            },
            { type: "text", text: "The drops on a cold glass did not leak through it. They came from water vapor in the air." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "Cool the vapor",
          prompt:
            "This is water vapor at 120 °C. Cool it until it condenses into liquid. The model shows pure water; vapor mixed into air condenses at much cooler temperatures, but cooling still turns it back into liquid.",
          widget: { kind: "states-of-matter", startC: 120, target: "liquid" },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Evaporation or condensation?",
          prompt: "Is each one evaporation (liquid to gas) or condensation (gas to liquid)?",
          widget: {
            kind: "sorter",
            categories: ["Evaporation", "Condensation"],
            items: [
              { id: "can", text: "Drops form on a cold can of juice", answer: 1 },
              { id: "clothes", text: "Wet clothes dry on a line", answer: 0 },
              { id: "puddle", text: "A puddle disappears on a sunny afternoon", answer: 0 },
              { id: "mirror", text: "A mirror fogs up after a shower", answer: 1 },
              { id: "dew", text: "Dew covers the grass at sunrise", answer: 1 },
              { id: "sweat", text: "Sweat dries on your skin", answer: 0 },
              { id: "hair", text: "Wet hair dries without a hair dryer", answer: 0 },
              { id: "cloud", text: "A cloud forms in the sky", answer: 1 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Ocean water is salty. Why is rain fresh, not salty?",
              choices: ["The clouds filter the salt out of the rain", "Only the water evaporates, not the salt", "Rain comes only from lakes and rivers"],
              answer: 1,
              hint: "Think about what goes into the air when ocean water evaporates.",
              explain: "Only water particles escape into the air as vapor. The salt stays in the ocean, so clouds and rain are fresh water. Most rain starts as ocean water.",
            },
            {
              id: "q2",
              prompt: "Drops of water appear on the outside of a cold glass. Where did they come from?",
              choices: ["Water that leaked through the glass", "New water made by the cold", "Water vapor in the air"],
              answer: 2,
              hint: "Would the same drops form on a warm glass?",
              explain: "Water vapor in the air touched the cold glass, cooled and condensed into drops. The glass did not leak.",
            },
            {
              id: "q3",
              prompt: "How do plants add water vapor to the air?",
              choices: ["Through tiny holes in their leaves", "Through the bark on their stems and trunks", "They do not add any vapor"],
              answer: 0,
              hint: "Water moves up from the roots to the leaves.",
              explain: "Plants pull water up from the soil and release vapor through tiny holes in their leaves. This is transpiration.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Rain in a jar",
          brief: "Make evaporation, condensation and precipitation happen in a jar.",
          steps: [
            "Ask a grown-up to pour hot tap water into a glass jar until it is about one third full.",
            "Cover the jar with a small plate, and put a few ice cubes on the plate.",
            "Watch the underside of the plate for 5 to 10 minutes.",
            "Look for drops forming and falling back into the jar. Drops that fall back down are precipitation.",
            "Draw the jar. Label where evaporation, condensation and precipitation happened.",
          ],
        },
      ],
    },
    {
      id: "around-the-cycle",
      title: "Rain, snow and the trip back",
      summary: "Drops in clouds grow until they fall. The water collects in oceans, lakes, rivers, ice and underground, and the cycle goes on.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Precipitation",
          blocks: [
            { type: "text", text: "A cloud is made of billions of tiny drops of water or crystals of ice. They are so small that rising air keeps them floating." },
            { type: "text", text: "As drops bump together and join, they grow. When they are too heavy to float, they fall. Water falling from clouds is precipitation." },
            {
              type: "points",
              items: [
                "Rain: drops of liquid water.",
                "Snow: ice crystals that grew in cold clouds.",
                "Sleet: raindrops that freeze into ice pellets as they fall through cold air.",
                "Hail: balls of ice that grow inside thunderstorms as strong winds carry them up and down.",
              ],
            },
          ],
        },
        {
          id: "s2",
          kind: "interactive",
          title: "Freeze it",
          prompt: "High in a cold cloud, water drops can freeze. Cool this water until it turns to ice. In the model, water is solid at 0 °C and below.",
          widget: { kind: "states-of-matter", startC: 10, target: "solid" },
        },
        {
          id: "s3",
          kind: "slide",
          title: "Collection",
          blocks: [
            { type: "text", text: "Precipitation lands on the ground, on lakes and on the ocean. Gravity pulls it downhill." },
            {
              type: "points",
              items: [
                "Runoff: water flows over the ground into streams, rivers, lakes and the ocean.",
                "Groundwater: some water soaks into the soil and fills spaces in rock underground. Wells and springs bring it back up.",
                "Ice: in cold places, water can stay frozen in glaciers for thousands of years before it melts and flows away.",
              ],
            },
            { type: "text", text: "Water gathering in oceans, lakes, rivers, ice and underground is called collection. From there, the cycle goes on." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "What powers the cycle",
          blocks: [
            { type: "text", text: "The Sun's energy evaporates water and lifts it into the sky. Gravity brings it back down and pulls it downhill to the sea." },
            { type: "text", text: "The cycle has no start and no end. It does not make new water or use any up. It moves the same water around, again and again." },
            { type: "text", text: "One trip can be quick or slow. Water stays in the air for about 9 days on average, but it can stay in deep groundwater or ice for thousands of years." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Name the step",
          prompt: "Which step of the water cycle is each one?",
          widget: {
            kind: "sorter",
            categories: ["Evaporation", "Condensation", "Precipitation", "Collection"],
            items: [
              { id: "snow", text: "Snow falls on the mountains", answer: 2 },
              { id: "lake", text: "The Sun heats a lake, and water rises as vapor", answer: 0 },
              { id: "runoff", text: "Rainwater runs down a street into a river", answer: 3 },
              { id: "fog", text: "Fog forms over a lake on a cold morning", answer: 1 },
              { id: "hail", text: "Hail bounces on the sidewalk", answer: 2 },
              { id: "ground", text: "Melted snow soaks into the ground and becomes groundwater", answer: 3 },
              { id: "ocean", text: "Ocean water turns into vapor on a warm day", answer: 0 },
              { id: "cloud", text: "Water vapor cools high up and forms a cloud", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which step comes right after evaporation?",
              choices: ["Condensation", "Precipitation", "Collection"],
              answer: 0,
              hint: "After vapor rises, it cools. What does cooling vapor do?",
              explain: "Rising vapor cools and condenses into the drops that make clouds. Precipitation comes after that.",
            },
            {
              id: "q2",
              prompt: "What are clouds made of?",
              choices: ["Water vapor, the gas form of water", "Tiny drops of water or ice", "Puffs of cold, white air"],
              answer: 1,
              hint: "You can see clouds. Can you see water vapor?",
              explain: "Water vapor is invisible. Clouds are visible because they are made of tiny drops of water or crystals of ice.",
            },
            {
              id: "q3",
              prompt: "What gives the water cycle its energy?",
              choices: ["Heat from inside Earth", "Ocean waves", "The Sun"],
              answer: 2,
              hint: "What warms the water so it can evaporate?",
              explain: "The Sun's energy drives evaporation, which lifts water into the air. Gravity brings it back down.",
            },
            {
              id: "q4",
              prompt: "Is the water you drink today new water?",
              choices: ["No, it has gone around many times", "Yes, rain makes new water each day", "Yes, the water company makes it"],
              answer: 0,
              hint: "Does the water cycle make water, or move it?",
              explain: "The water cycle moves the same water around. The water in your glass has been ocean, cloud and rain many times before. Rain is old water falling again, and a water company cleans water but does not make it.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "A drop's journey",
          brief: "Draw a comic that follows one drop of water around the cycle.",
          steps: [
            "Fold a sheet of paper into 6 boxes.",
            "Pick where your drop starts: the ocean, a puddle, a glacier or your water glass.",
            "In each box, draw the drop's next step and name it: evaporation, condensation, precipitation or collection.",
            "Give your drop a detour: it soaks into the ground, freezes in a glacier, or is pulled up by a tree's roots.",
            "End the comic where your drop started, ready to go around again.",
          ],
        },
      ],
    },
    {
      id: "where-water-is",
      title: "Where Earth's water is",
      summary: "Almost all of Earth's water is salty. Most fresh water is frozen or underground, so the water we can easily use is a small share.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Salty and fresh",
          blocks: [
            { type: "text", text: "About 97 out of every 100 drops of water on Earth are salty. Most of that salty water is in the ocean." },
            { type: "text", text: "Fewer than 3 out of every 100 drops are fresh water, the kind that people, farms and most land animals need." },
            { type: "text", text: "Rain is fresh because the salt stays behind when seawater evaporates. The water cycle turns seawater into fresh water." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Where the fresh water is",
          blocks: [
            {
              type: "points",
              items: [
                "About two thirds of Earth's fresh water is frozen in glaciers and ice sheets.",
                "Almost all of the rest is groundwater, underground in soil and rock.",
                "Only about 1 out of every 100 drops of fresh water is in lakes, rivers, the air and living things.",
              ],
            },
            { type: "text", text: "That is why people dig wells, build reservoirs, and work to keep water clean and not waste it." },
          ],
        },
        {
          id: "s3",
          kind: "interactive",
          title: "How much is frozen?",
          prompt: "Think of all of Earth's fresh water as one whole. About what fraction of it is frozen? Move the marker there.",
          widget: { kind: "number-line", min: 0, max: 1, step: 1 / 3, start: 0, target: 2 / 3, denominator: 3 },
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Salty or fresh?",
          prompt: "Is the water in each place salty or fresh?",
          widget: {
            kind: "sorter",
            categories: ["Salty", "Fresh"],
            items: [
              { id: "rain", text: "Rain", answer: 1 },
              { id: "pacific", text: "The Pacific Ocean", answer: 0 },
              { id: "glacier", text: "A glacier", answer: 1 },
              { id: "salt-lake", text: "The Great Salt Lake in Utah", answer: 0 },
              { id: "river", text: "A river", answer: 1 },
              { id: "iceberg", text: "An iceberg that broke off a glacier", answer: 1 },
              { id: "dead-sea", text: "The Dead Sea", answer: 0 },
              { id: "snowmelt", text: "A mountain lake filled by melting snow", answer: 1 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "About how much of Earth's water is salty?",
              choices: ["About 3 out of every 100 drops", "About 50 out of every 100 drops", "About 97 out of every 100 drops"],
              answer: 2,
              hint: "Think of how much of Earth is covered by ocean, and how deep it is.",
              explain: "About 97 out of every 100 drops are salty, mostly in the ocean. Fewer than 3 are fresh.",
            },
            {
              id: "q2",
              prompt: "Where is most of Earth's fresh water?",
              choices: ["Frozen in glaciers and ice", "Underground in soil and rock", "In lakes, rivers and clouds"],
              answer: 0,
              hint: "Look back at where the fresh water is. Which place holds the biggest share?",
              explain: "About two thirds of fresh water is frozen, mostly in the ice sheets of Antarctica and Greenland. Almost all the rest is groundwater. Lakes and rivers hold only a tiny share.",
            },
            {
              id: "q3",
              prompt: "A family gets its water from a well. Where does that water come from?",
              choices: ["An underground lake that never refills", "Water that soaked into the ground", "Seawater that seeps in from the ocean"],
              answer: 1,
              hint: "Where does water go when it soaks into the soil?",
              explain: "A well reaches groundwater, water that soaked into soil and rock after rain or snowmelt. If people pump it out faster than rain refills it, the well can run dry.",
            },
            {
              id: "q4",
              prompt: "The water cycle never uses water up. So why do people work to save fresh water?",
              choices: ["Usable fresh water is scarce and can get dirty", "The water cycle will stop working if we use too much", "Water that goes down the drain is gone from Earth"],
              answer: 0,
              hint: "How much of Earth's water is fresh and easy to reach?",
              explain: "The total amount of water stays the same, but the fresh water in one place can run low or get dirty. Lakes, rivers and wells refill only as fast as rain and snow return.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Where does our water come from?",
          brief: "Find out where your home's water comes from, and how much runs out of a faucet.",
          steps: [
            "Ask a grown-up where your tap water comes from: a river, a lake, a reservoir or a well.",
            "Turn on a faucet for 10 seconds while a grown-up catches the water in a measuring cup or jug. Write down how much came out.",
            "Multiply by 12 to find how much would run out in 2 minutes, the time dentists suggest for brushing, if the tap stayed on.",
            "List three ways your family could use less water.",
            "Pour the water you caught on a plant, so it is not wasted.",
          ],
        },
      ],
    },
  ],
};

export default waterCycle;
