import type { CatalogueEntry } from "./types";

// No grade 1 practice skill covers light and sound yet. Nearest: s.energy.forms (sound from vibration,
// light) and s.earth.sun.moon (shadows), both in src/practice/science/early.ts.
const lightSound: CatalogueEntry = {
  id: "science-light-sound",
  title: "Light and sound",
  summary: "Sounds start with vibrations. Light sources like the Sun make their own light. We see when light reaches our eyes. Shadows form where light is stopped.",
  subject: "science",
  grade: "1",
  locale: "en",
  lessons: [
    {
      id: "sound-vibrates",
      title: "Sound comes from shaking",
      summary: "Things that make sound shake back and forth very fast.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Feel a sound",
          blocks: [
            { type: "text", text: "Put your hand on your throat. Now hum." },
            { type: "text", text: "Can you feel a buzz? Your throat is shaking." },
            { type: "text", text: "Fast shaking like this is called vibrating. It makes the sound." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Sounds come from vibrations",
          blocks: [
            { type: "text", text: "When something makes a sound, it vibrates." },
            {
              type: "points",
              items: ["Hit a drum. Its top vibrates.", "Pluck a guitar string. The string vibrates.", "Blow a whistle. The air inside vibrates."],
            },
            { type: "text", text: "When the vibrating stops, the sound stops." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Sound travels",
          blocks: [
            { type: "text", text: "Vibrations travel through the air to your ears." },
            { type: "text", text: "Sound can also travel through water, wood and walls." },
            { type: "text", text: "That is why you can hear someone through a door." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Loud and soft",
          blocks: [
            { type: "text", text: "A hard hit makes a big vibration. It sounds loud." },
            { type: "text", text: "A gentle tap makes a small vibration. It sounds soft." },
            { type: "text", text: "Very loud sounds can hurt your ears. Cover them." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "How do you make it vibrate?",
          prompt: "How do you play each one? Hit it, pluck it, or blow into it?",
          widget: {
            kind: "sorter",
            categories: ["Hit it", "Pluck it", "Blow into it"],
            items: [
              { id: "guitar", text: "A guitar string", answer: 1 },
              { id: "drum", text: "A drum", answer: 0 },
              { id: "whistle", text: "A whistle", answer: 2 },
              { id: "trumpet", text: "A trumpet", answer: 2 },
              { id: "triangle", text: "A metal triangle", answer: 0 },
              { id: "rubber-band", text: "A stretched rubber band", answer: 1 },
              { id: "recorder", text: "A recorder", answer: 2 },
              { id: "xylophone", text: "A xylophone", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Something is making a sound. What is it doing?",
              choices: ["Glowing", "Vibrating", "Standing still"],
              answer: 1,
              hint: "Think of the buzz in your throat when you hum.",
              explain: "Things that make sound vibrate. They shake back and forth very fast.",
            },
            {
              id: "q2",
              prompt: "A bell is ringing. You hold it tight. What happens?",
              choices: ["It gets louder", "It rings the same", "The sound stops"],
              answer: 2,
              hint: "Can the bell shake while you hold it tight?",
              explain: "Your hand stops the bell from vibrating. So the sound stops.",
            },
            {
              id: "q3",
              prompt: "How can you make a drum sound louder?",
              choices: ["Hit it more gently", "Hit it harder", "Stand farther away"],
              answer: 1,
              hint: "Think of a big shake and a tiny shake.",
              explain: "A harder hit makes the drum vibrate more. A bigger vibration sounds louder. From far away, a drum sounds softer.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Dancing rice",
          brief: "See a sound make something else vibrate.",
          steps: [
            "Stretch plastic wrap tight over a bowl.",
            "Put a few grains of rice on top.",
            "Hold a pot near the bowl. Bang it with a spoon.",
            "Watch the rice. Does it jump?",
            "Try a soft tap, then a hard bang. What changes?",
          ],
        },
      ],
    },
    {
      id: "light-to-see",
      title: "We need light to see",
      summary: "Light bounces off things and into our eyes. In total darkness, we see nothing.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "How you see",
          blocks: [
            { type: "text", text: "Light bounces off things. Then it goes into your eyes." },
            { type: "text", text: "That is how you see a ball or a face." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "In the dark",
          blocks: [
            { type: "text", text: "Think of a room with no light at all." },
            { type: "text", text: "No light can bounce off anything. So you see nothing." },
            { type: "text", text: "Your eyes need light to see. So do a cat's eyes." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Things that make light",
          blocks: [
            { type: "text", text: "Some things make their own light." },
            { type: "points", items: ["The Sun", "A lamp that is on", "A fire", "A firefly"] },
            { type: "text", text: "Most things do not make light. We see them by bounced light." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "The Moon only bounces light",
          blocks: [
            { type: "text", text: "The Moon looks bright at night." },
            { type: "text", text: "But the Moon does not make its own light." },
            { type: "text", text: "Sunlight bounces off the Moon. Then it reaches your eyes." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Does it make light?",
          prompt: "Does it make its own light? Or do we see it by bounced light?",
          widget: {
            kind: "sorter",
            categories: ["Makes light", "Does not make light"],
            items: [
              { id: "moon", text: "The Moon", answer: 1 },
              { id: "sun", text: "The Sun", answer: 0 },
              { id: "flashlight", text: "A flashlight that is on", answer: 0 },
              { id: "mirror", text: "A mirror", answer: 1 },
              { id: "ball", text: "A red ball", answer: 1 },
              { id: "candle", text: "A candle flame", answer: 0 },
              { id: "book", text: "A book", answer: 1 },
              { id: "firefly", text: "A firefly", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "How do you see a book?",
              choices: ["Light bounces off it to your eyes", "The book glows with its own light", "Your eyes shine light onto the book"],
              answer: 0,
              hint: "Can you see the book in a totally dark room?",
              explain: "Light bounces off the book and into your eyes. That is how you see it.",
            },
            {
              id: "q2",
              prompt: "Which one makes its own light?",
              choices: ["A campfire", "The full Moon", "A mirror"],
              answer: 0,
              hint: "Which one would still shine if the Sun went away?",
              explain: "A campfire makes its own light. The Moon and a mirror only bounce light.",
            },
            {
              id: "q3",
              prompt: "A cat is in a totally dark room. Can it see?",
              choices: ["Yes", "No"],
              answer: 1,
              hint: "What do all eyes need to see?",
              explain: "Cats see well in dim light. With no light at all, they cannot see.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Dark box",
          brief: "Find out if you can see without light.",
          steps: [
            "Find a shoebox with a lid.",
            "Put a small toy inside. Close the lid.",
            "Ask a grown-up to poke a hole in one end.",
            "Look in the hole. Can you see the toy?",
            "Now poke a second hole. Shine a flashlight into it.",
            "Look again. What changed?",
          ],
        },
      ],
    },
    {
      id: "light-through",
      title: "Light gets through, or not",
      summary: "Some things let light through. Some things block it and make a shadow.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Clear things",
          blocks: [
            { type: "text", text: "Light passes through clear glass. You can see through it." },
            { type: "text", text: "Clear things let light through. The science word is transparent." },
            { type: "points", items: ["A window", "Clear plastic wrap", "Clean water in a glass"] },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Cloudy things",
          blocks: [
            { type: "text", text: "Wax paper lets some light through. Things behind it look blurry." },
            { type: "text", text: "The science word is translucent." },
            { type: "points", items: ["Wax paper", "Tissue paper", "A frosted bathroom window"] },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Things that block light",
          blocks: [
            { type: "text", text: "Wood blocks light. So does cardboard. So do you." },
            { type: "text", text: "The science word is opaque." },
            { type: "text", text: "A thing that blocks light makes a shadow behind it." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Mirrors bounce light",
          blocks: [
            { type: "text", text: "A mirror bounces light back. It changes where light goes." },
            { type: "text", text: "A mirror can bounce sunlight onto a wall." },
            { type: "text", text: "Never shine light into anyone's eyes. Never look at the Sun." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Through or blocked?",
          prompt: "Does it let light through? Some light? Or does it block light?",
          widget: {
            kind: "sorter",
            categories: ["Lets light through", "Lets some light through", "Blocks light"],
            items: [
              { id: "book", text: "A book", answer: 2 },
              { id: "window", text: "Window glass", answer: 0 },
              { id: "wax-paper", text: "Wax paper", answer: 1 },
              { id: "door", text: "A wooden door", answer: 2 },
              { id: "bottle", text: "A clear plastic bottle", answer: 0 },
              { id: "cardboard", text: "A cardboard box", answer: 2 },
              { id: "tissue", text: "Tissue paper", answer: 1 },
              { id: "wrap", text: "Clear plastic wrap", answer: 0 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which one makes the darkest shadow?",
              choices: ["A clear glass jar", "A sheet of wax paper", "A wooden block"],
              answer: 2,
              hint: "Which one blocks all the light?",
              explain: "Wood blocks the light, so it makes a dark shadow. Clear glass lets light through.",
            },
            {
              id: "q2",
              prompt: "You hold wax paper up to a lamp. What do you see?",
              choices: ["Some light, but blurry", "Everything clear and sharp", "No light at all"],
              answer: 0,
              hint: "Is wax paper clear, cloudy, or a light blocker?",
              explain: "Wax paper lets some light through. Things behind it look blurry.",
            },
            {
              id: "q3",
              prompt: "The Sun is behind you. Where is your shadow?",
              choices: ["Behind you", "In front of you", "On top of your head"],
              answer: 1,
              hint: "A shadow falls on the side away from the light.",
              explain: "Your body blocks the sunlight. So your shadow falls in front of you.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Light test",
          brief: "Test things at home. Do they let light through?",
          steps: [
            "Get a flashlight and five things to test.",
            "Try a cup, a towel and a sheet of paper.",
            "Try foil and a plastic bag, too.",
            "Shine the flashlight at each one. Look at the wall behind it.",
            "Sort them: lets light through, some light, or none.",
          ],
        },
      ],
    },
    {
      id: "signals",
      title: "Messages with light and sound",
      summary: "People use light and sound to send messages far away.",
      minutes: 10,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Messages you hear",
          blocks: [
            { type: "text", text: "A sound can carry a message." },
            {
              type: "points",
              items: ["A smoke alarm beeps. It means: go outside.", "A school bell rings. It means: class starts.", "A siren means: move out of the way."],
            },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Messages you see",
          blocks: [
            { type: "text", text: "Light can carry a message, too." },
            {
              type: "points",
              items: ["A red traffic light means stop.", "A lighthouse flashes. It warns ships about rocks.", "A blinking car light shows which way it will turn."],
            },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Long ago and now",
          blocks: [
            { type: "text", text: "Long ago, people sent messages with drums and smoke." },
            { type: "text", text: "Sailors flashed lamps from ship to ship." },
            { type: "text", text: "Today, phones carry voices far away." },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Light or sound?",
          prompt: "Does each one send its message with light or sound?",
          widget: {
            kind: "sorter",
            categories: ["Uses light", "Uses sound"],
            items: [
              { id: "siren", text: "A fire truck siren", answer: 1 },
              { id: "traffic", text: "A traffic light", answer: 0 },
              { id: "lighthouse", text: "A lighthouse", answer: 0 },
              { id: "doorbell", text: "A doorbell", answer: 1 },
              { id: "whistle", text: "A coach's whistle", answer: 1 },
              { id: "turn", text: "A car's blinking turn light", answer: 0 },
              { id: "flashes", text: "Flashlight blinks in a secret code", answer: 0 },
              { id: "bell", text: "A school bell", answer: 1 },
            ],
          },
        },
        {
          id: "s5",
          kind: "slide",
          title: "How a cup phone works",
          blocks: [
            { type: "text", text: "Two cups are joined by a tight string." },
            { type: "text", text: "You talk into one cup. Its bottom vibrates." },
            { type: "text", text: "The vibrations travel along the string to the other cup." },
            { type: "text", text: "That cup vibrates, too. Your friend hears you." },
          ],
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "A lighthouse flashes at night. What does it tell ships?",
              choices: ["Land and rocks are near", "Where to find fish", "The water here is deep and safe"],
              answer: 0,
              hint: "Ships can hit rocks in the dark.",
              explain: "The flashing light warns ships that land is near. They can steer away.",
            },
            {
              id: "q2",
              prompt: "Which one uses sound to send a message?",
              choices: ["A red traffic light", "A turn signal", "A smoke alarm"],
              answer: 2,
              hint: "Which one do you hear, not see?",
              explain: "A smoke alarm beeps. The sound warns everyone to get out.",
            },
            {
              id: "q3",
              prompt: "Why does a fire truck have a siren and lights?",
              choices: ["To light up the road at night", "To wake up the firefighters", "So people hear it and see it"],
              answer: 2,
              hint: "Some people hear it first. Others see it first.",
              explain: "The siren is a sound message. The lights are a light message. Both together reach more people.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Make a cup phone",
          brief: "Send your voice along a string.",
          steps: [
            "Get two paper cups and a long string.",
            "Ask a grown-up to poke a hole in each cup.",
            "Push the string ends through the holes. Tie a knot inside.",
            "Walk apart until the string is tight.",
            "Talk into one cup. Your partner listens at the other.",
            "Now let the string go loose. What happens?",
          ],
        },
      ],
    },
  ],
};

export default lightSound;
