import type { CatalogueEntry } from "./types";

// Practice skill this course teaches: s.life.cycles (src/practice/science/early.ts).
const lifeCycles: CatalogueEntry = {
  id: "science-life-cycles",
  title: "Life cycles",
  summary: "Every plant and animal is born, grows, reproduces and dies. Follow butterflies, frogs and bean plants through their life cycles.",
  subject: "science",
  grade: "3",
  locale: "en",
  lessons: [
    {
      id: "every-life-cycle",
      title: "What every life cycle has",
      summary: "Living things are born, grow, reproduce and die. Then the cycle starts again with their young.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "A pattern that repeats",
          blocks: [
            { type: "text", text: "A cycle is a pattern that repeats, like the days of the week." },
            { type: "text", text: "A life cycle is the set of changes in a living thing's life. It runs from birth until it has young of its own." },
            { type: "text", text: "When those young grow up and have young, the pattern goes around again." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Four parts of every life cycle",
          blocks: [
            {
              type: "points",
              items: [
                "Birth: a new living thing starts out. Animals are born or hatch. Plants sprout from seeds.",
                "Growth: it gets bigger and changes.",
                "Reproduction: it makes new living things of its own kind.",
                "Death: its life ends. Every living thing dies at some point.",
              ],
            },
            { type: "text", text: "The details are different for every kind of plant and animal. These four parts are in all of their life cycles." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Fast and slow life cycles",
          blocks: [
            { type: "text", text: "Some life cycles go around quickly. Others take a very long time." },
            {
              type: "points",
              items: [
                "An adult mayfly may live only a single day.",
                "A pet dog often lives 10 to 13 years.",
                "Some giant tortoises live more than 100 years.",
                "Some bristlecone pine trees are more than 4,000 years old.",
              ],
            },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "Which part of the life cycle?",
          prompt: "Sort each event into the part of the life cycle it shows.",
          widget: {
            kind: "sorter",
            categories: ["Birth", "Growth", "Reproduction", "Death"],
            items: [
              { id: "calf", text: "A calf is born on a farm.", answer: 0 },
              { id: "chick", text: "A chick pecks its way out of its egg.", answer: 0 },
              { id: "puppy", text: "A puppy gets bigger and stronger.", answer: 1 },
              { id: "tadpole", text: "A tadpole grows its back legs.", answer: 1 },
              { id: "apple", text: "An apple tree makes flowers, then fruit with seeds.", answer: 2 },
              { id: "kittens", text: "A cat has a litter of kittens.", answer: 2 },
              { id: "pumpkin", text: "A pumpkin vine dies in the first hard frost.", answer: 3 },
              { id: "oak", text: "A very old oak tree dies.", answer: 3 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Which four parts do all life cycles share?",
              choices: ["Birth, growth, reproduction, death", "Egg, larva, pupa, adult", "Seed, flower, fruit, tree", "Baby, child, teen, adult"],
              answer: 0,
              hint: "One choice fits only some insects. One fits only plants. Which one fits every living thing?",
              explain: "Birth, growth, reproduction and death are in every life cycle. Egg, larva, pupa, adult fits only some insects.",
            },
            {
              id: "q2",
              prompt: "Why is it called a life cycle?",
              choices: ["The young grow up and have young, so the pattern repeats", "Living things move in circles", "It always takes one year"],
              answer: 0,
              hint: "Think of a bicycle wheel. It goes around and around.",
              explain: "Adults have young. The young grow into adults and have young of their own. The pattern goes around again and again.",
            },
            {
              id: "q3",
              prompt: "A goldfish lays eggs. Which part of the life cycle is this?",
              choices: ["Reproduction", "Growth", "Death"],
              answer: 0,
              hint: "What will come out of the eggs?",
              explain: "Laying eggs is how goldfish make new goldfish. Making new living things is reproduction.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Life cycle detective",
          brief: "Pick a plant or animal near your home and find clues about its life cycle.",
          steps: [
            "Pick something you can find near home, like a dandelion, a robin or an ant.",
            "Draw a big circle on paper with four arrows going around it.",
            "Draw its birth, growth, reproduction and death at the four points of the circle.",
            "Look outside for clues: seeds, eggs, flowers, young ones or empty shells. Look, but never touch a nest or eggs.",
            "Show your circle to someone and explain how the cycle starts again.",
          ],
        },
      ],
    },
    {
      id: "butterfly",
      title: "A butterfly's four stages",
      summary: "Egg, larva, pupa and adult: a butterfly changes completely as it grows.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Egg",
          blocks: [
            { type: "text", text: "A butterfly starts as an egg, about the size of a pinhead." },
            { type: "text", text: "A monarch butterfly lays each egg on a milkweed leaf. Milkweed is the only plant monarch caterpillars eat." },
            { type: "text", text: "In warm weather, a tiny caterpillar hatches after 3 to 5 days." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Larva",
          blocks: [
            { type: "text", text: "The caterpillar is the larva. Its job is to eat and grow." },
            { type: "text", text: "It grows so fast that it gets too big for its skin. It sheds its old skin several times." },
            { type: "text", text: "A monarch caterpillar spends about two weeks eating." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Pupa",
          blocks: [
            { type: "text", text: "Next, the caterpillar hangs upside down and sheds its skin one last time. Underneath is a hard case called a chrysalis." },
            { type: "text", text: "This stage is the pupa. On the outside, it looks still. Inside, its body is being rebuilt into a butterfly." },
            { type: "text", text: "For a monarch, this takes about one to two weeks." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Adult",
          blocks: [
            { type: "text", text: "The adult butterfly crawls out of the chrysalis. Its wings are wet and crumpled. It pumps them open and waits for them to dry before it flies." },
            { type: "text", text: "Adults drink nectar from flowers. They do not grow any more." },
            { type: "text", text: "Adult females lay eggs, and the cycle begins again." },
            { type: "points", items: ["Egg, then larva (caterpillar), then pupa (chrysalis), then adult.", "A change this big is called complete metamorphosis."] },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Which stage?",
          prompt: "Each clue is about one stage of a butterfly's life. Sort them.",
          widget: {
            kind: "sorter",
            categories: ["Egg", "Larva", "Pupa", "Adult"],
            items: [
              { id: "round", text: "Tiny and round, stuck to a leaf", answer: 0 },
              { id: "hatch", text: "A tiny caterpillar is about to come out of it", answer: 0 },
              { id: "eats", text: "Eats leaves all day and grows fast", answer: 1 },
              { id: "sheds", text: "Sheds its skin as it gets bigger", answer: 1 },
              { id: "case", text: "Hangs still inside a hard case", answer: 2 },
              { id: "rebuilt", text: "Its body is being rebuilt inside", answer: 2 },
              { id: "nectar", text: "Has wings and drinks nectar", answer: 3 },
              { id: "lays", text: "Lays eggs on milkweed", answer: 3 },
            ],
          },
        },
        {
          id: "s6",
          kind: "slide",
          title: "Other insects with four stages",
          blocks: [
            { type: "text", text: "Ladybugs, beetles, bees, ants, flies and mosquitoes also go through egg, larva, pupa and adult." },
            { type: "text", text: "A ladybug larva looks nothing like a ladybug. It is long and spiky, a bit like a tiny alligator." },
            { type: "text", text: "Many moths spin a silk cocoon around their pupa. A butterfly's pupa has no silk around it. It is called a chrysalis." },
          ],
        },
        {
          id: "s7",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Egg, caterpillar, ___, butterfly. Which stage is missing?",
              choices: ["Pupa", "Tadpole", "Seedling"],
              answer: 0,
              hint: "This is the stage where the caterpillar hangs inside a hard case.",
              explain: "Egg, larva, pupa, adult. The caterpillar becomes a pupa inside a chrysalis, and then a butterfly comes out.",
            },
            {
              id: "q2",
              prompt: "Which stage does most of the eating and growing?",
              choices: ["Larva", "Pupa", "Adult"],
              answer: 0,
              hint: "Adults stop growing. A pupa does not eat at all.",
              explain: "The larva, the caterpillar, eats and grows. Adults sip nectar but do not grow, and the pupa does not eat.",
            },
            {
              id: "q3",
              prompt: "A butterfly with small wings is a young butterfly that will grow. True or false?",
              choices: ["False", "True"],
              answer: 0,
              hint: "Do adult insects keep growing?",
              explain: "False. A butterfly is already an adult when it comes out of the chrysalis, and it does not grow. A small butterfly is a smaller kind, or one that had less food as a caterpillar.",
            },
          ],
        },
        {
          id: "s8",
          kind: "project",
          title: "Caterpillar hunt",
          brief: "Look for insect eggs, caterpillars or a chrysalis outside, and follow what happens.",
          steps: [
            "With a grown-up, check the undersides of leaves in a garden or a park.",
            "If you find eggs or a caterpillar, look closely but leave it on its plant.",
            "Draw what you see, and draw the plant it is on.",
            "Check again every few days. Did it grow? Did it move? Did it shed its skin?",
            "You may not find one on the first try. Keep a list of the plants you checked.",
          ],
        },
      ],
    },
    {
      id: "frogs-and-more",
      title: "Frogs, chickens and other paths",
      summary: "Frogs change completely, chicks grow up inside an egg, and many young look like small adults.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "A frog's life cycle",
          blocks: [
            { type: "text", text: "Most frogs lay their eggs in water." },
            {
              type: "points",
              items: [
                "Egg: a tiny dark dot inside clear jelly.",
                "Tadpole: it hatches with a tail and gills, and lives underwater.",
                "Froglet: it grows legs, its tail shrinks, and it starts to breathe air.",
                "Adult frog: it has lungs and four legs. Most adult frogs live both on land and in water.",
              ],
            },
            { type: "text", text: "A frog's body changes completely, so this is metamorphosis too." },
          ],
        },
        {
          id: "s2",
          kind: "interactive",
          title: "Frog stages",
          prompt: "Each clue is about one stage of a frog's life. Sort them.",
          widget: {
            kind: "sorter",
            categories: ["Egg", "Tadpole", "Froglet", "Adult frog"],
            items: [
              { id: "jelly", text: "A dark dot in a ball of jelly", answer: 0 },
              { id: "gills", text: "Swims with a tail and breathes with gills", answer: 1 },
              { id: "algae", text: "Has no legs and nibbles algae in the pond", answer: 1 },
              { id: "short-tail", text: "Has four legs and a short tail", answer: 2 },
              { id: "shrinking", text: "Its tail is shrinking away", answer: 2 },
              { id: "tongue", text: "Breathes with lungs and catches insects with its tongue", answer: 3 },
              { id: "lays", text: "Lays eggs in a pond", answer: 3 },
            ],
          },
        },
        {
          id: "s3",
          kind: "slide",
          title: "A chick grows inside its egg",
          blocks: [
            {
              type: "points",
              items: [
                "Egg: a hen sits on her eggs to keep them warm.",
                "Chick: after about 21 days, a fluffy chick pecks its way out.",
                "Adult: the chick grows feathers and becomes a hen or a rooster.",
              ],
            },
            { type: "text", text: "Only eggs with a chick growing inside can hatch. Eggs from the store will not hatch." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Young that look like small adults",
          blocks: [
            { type: "text", text: "Some young look like small copies of their parents. They mostly just grow bigger." },
            {
              type: "points",
              items: [
                "A kitten looks like a small cat.",
                "A baby turtle looks like a small turtle.",
                "A grasshopper hatches as a nymph: a small grasshopper without working wings. It sheds its skin several times, and after the last time it has full wings.",
              ],
            },
            { type: "text", text: "People are like this too. A baby has the same body shape as a grown-up, only smaller." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "Big change or just growing?",
          prompt: "Does the young animal change shape a lot, or does it look like a small adult?",
          widget: {
            kind: "sorter",
            categories: ["Changes shape a lot", "Looks like a small adult"],
            items: [
              { id: "frog", text: "A frog", answer: 0 },
              { id: "butterfly", text: "A butterfly", answer: 0 },
              { id: "cat", text: "A cat", answer: 1 },
              { id: "ladybug", text: "A ladybug", answer: 0 },
              { id: "turtle", text: "A turtle", answer: 1 },
              { id: "horse", text: "A horse", answer: 1 },
              { id: "mosquito", text: "A mosquito", answer: 0 },
              { id: "person", text: "A person", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "Egg, tadpole, ___, adult frog. Which stage is missing?",
              choices: ["Froglet", "Chick", "Pupa"],
              answer: 0,
              hint: "This stage has legs and a shrinking tail.",
              explain: "A tadpole grows legs and becomes a froglet. Then its tail disappears and it is an adult frog.",
            },
            {
              id: "q2",
              prompt: "Which young animal looks like a small copy of its parents?",
              choices: ["A kitten", "A caterpillar", "A tadpole"],
              answer: 0,
              hint: "Which baby has the same body shape as the grown-up?",
              explain: "A kitten has the same shape as a cat and just grows. Caterpillars and tadpoles change shape completely.",
            },
            {
              id: "q3",
              prompt: "How does a tadpole breathe underwater?",
              choices: ["With gills", "With lungs", "It holds its breath"],
              answer: 0,
              hint: "Fish breathe underwater the same way.",
              explain: "Tadpoles have gills, like fish. As they turn into frogs, they grow lungs and start to breathe air.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Life cycle wheel",
          brief: "Make a paper wheel that turns through a frog's life cycle.",
          steps: [
            "Cut out two paper circles the same size.",
            "Divide one circle into four equal parts, like a pizza. Draw egg, tadpole, froglet and adult frog in order, one in each part.",
            "Cut a window the size of one part out of the other circle.",
            "Put the window circle on top. Ask a grown-up to push a paper fastener through both centers.",
            "Turn the wheel. Tell the story of each stage as it shows in the window.",
          ],
        },
      ],
    },
    {
      id: "plant-life-cycle",
      title: "A plant's life cycle",
      summary: "Seeds sprout, plants grow and flower, flowers make seeds, and seeds travel to new places.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "From seed to seedling",
          blocks: [
            { type: "text", text: "Inside a seed is a tiny plant and a store of food for it." },
            { type: "text", text: "With water, air and warmth, the seed sprouts. The root comes out first and grows down. Then a shoot grows up toward the light." },
            { type: "text", text: "The young plant is called a seedling. Once it has leaves, it can make its own food from sunlight." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "How a bean plant grows",
          blocks: [
            { type: "text", text: "This graph shows how one bean plant might grow in its first month. Real plants vary." },
            {
              type: "visual",
              visual: {
                kind: "line-graph",
                points: [
                  [0, 0],
                  [5, 0],
                  [10, 4],
                  [15, 10],
                  [20, 18],
                  [25, 24],
                  [30, 27],
                ],
                xLabel: "Days after planting",
                yLabel: "Height (cm)",
              },
              alt: "A line graph of a bean plant's height over 30 days. It is 0 cm until day 5, 4 cm on day 10, 10 cm on day 15, 18 cm on day 20, 24 cm on day 25 and 27 cm on day 30.",
            },
            { type: "text", text: "At first nothing shows above the soil. Then the plant grows quickly, and later it slows down." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Flowers make seeds",
          blocks: [
            { type: "text", text: "A grown plant makes flowers." },
            {
              type: "text",
              text: "Bees and other animals carry a dust called pollen from flower to flower. For some plants, like grasses and corn, the wind carries the pollen.",
            },
            { type: "text", text: "When pollen reaches the right part of a flower, seeds start to form. Many plants grow a fruit around the seeds. An apple, a bean pod and a tomato are all fruits that hold seeds." },
            { type: "text", text: "Some plants, like beans and sunflowers, die after they make seeds. Others, like apple trees, flower year after year." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Seeds on the move",
          blocks: [
            { type: "text", text: "Seeds need room to grow, so plants have ways to spread them." },
            {
              type: "points",
              items: [
                "Wind: dandelion seeds float on fluffy parachutes. Maple seeds spin like helicopters.",
                "Animals: burrs stick to fur. Birds eat berries and drop the seeds far away. Squirrels bury acorns, and the ones they forget can grow into oak trees.",
                "Water: a coconut can float across the sea to a new beach.",
              ],
            },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "How does it travel?",
          prompt: "How does each seed get to a new place: by wind, by animals or by water?",
          widget: {
            kind: "sorter",
            categories: ["Wind", "Animals", "Water"],
            items: [
              { id: "dandelion", text: "Dandelion seeds with fluffy tops", answer: 0 },
              { id: "maple", text: "A spinning maple seed", answer: 0 },
              { id: "milkweed", text: "Milkweed seeds with silky threads", answer: 0 },
              { id: "burr", text: "A burr stuck to a dog's fur", answer: 1 },
              { id: "cherry", text: "Cherry seeds inside fruit that a bird ate", answer: 1 },
              { id: "acorn", text: "An acorn a squirrel buried", answer: 1 },
              { id: "coconut", text: "A coconut floating in the ocean", answer: 2 },
              { id: "mangrove", text: "A young mangrove plant floating to a new shore", answer: 2 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Check what you know",
          questions: [
            {
              id: "q1",
              prompt: "When a bean seed sprouts, what comes out first?",
              choices: ["The root", "A flower", "A bean pod"],
              answer: 0,
              hint: "Before the young plant can grow up, it needs to take in water.",
              explain: "The root comes out first and grows down to take in water. Then a shoot grows up toward the light.",
            },
            {
              id: "q2",
              prompt: "A bean plant was 10 cm tall on day 15, 18 cm on day 20 and 24 cm on day 25. When did it grow more?",
              choices: ["From day 15 to day 20", "From day 20 to day 25", "It grew the same both times"],
              answer: 0,
              hint: "Subtract to find each change: 18 − 10, then 24 − 18.",
              explain: "From day 15 to day 20 it grew 8 cm. From day 20 to day 25 it grew 6 cm. So it grew more in the first of those two stretches.",
            },
            {
              id: "q3",
              prompt: "How does a fruit like a berry help a plant spread?",
              choices: ["Animals eat it and drop the seeds in new places", "It keeps the plant warm at night", "It soaks up water for the roots"],
              answer: 0,
              hint: "Think about the bird and the cherries.",
              explain: "Animals eat the fruit and drop the seeds somewhere else, often far away. That carries the plant to new places.",
            },
            {
              id: "q4",
              prompt: "A sunflower dies after it makes seeds. Is that the end of sunflowers in that garden?",
              choices: ["No, its seeds can grow into new sunflowers", "Yes, there can be no more sunflowers"],
              answer: 0,
              hint: "What did the sunflower make before it died?",
              explain: "Each seed holds a tiny new sunflower plant. When the seeds sprout, the cycle starts again.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Bean in a bag",
          brief: "Watch a bean seed start its life cycle, and measure it as it grows.",
          steps: [
            "Wet a paper towel and slide it into a clear zip bag.",
            "Put 2 or 3 dry beans between the towel and the side of the bag.",
            "Tape the bag to a bright window, out of hot direct sun. Keep the towel damp.",
            "Every two days, draw what you see. Measure the root and the shoot with a ruler.",
            "When the shoot has leaves, plant it in a cup of soil and keep measuring.",
            "Make a graph of your plant's height. Is its line shaped like the one in this lesson?",
          ],
        },
      ],
    },
  ],
};

export default lifeCycles;
