import type { CatalogueEntry } from "./types";

// Habilidad de práctica de este curso: s.life.cycles (src/practice/science/early.ts).
const lifeCyclesEs: CatalogueEntry = {
  id: "science-life-cycles-es",
  title: "Ciclos de vida",
  summary: "Toda planta y todo animal nace, crece, se reproduce y muere. Sigue el ciclo de vida de mariposas, ranas y frijoles.",
  subject: "science",
  grade: "3",
  locale: "es",
  lessons: [
    {
      id: "every-life-cycle",
      title: "Lo que tiene todo ciclo de vida",
      summary: "Los seres vivos nacen, crecen, se reproducen y mueren. Con sus crías, el ciclo vuelve a empezar.",
      minutes: 12,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Un patrón que se repite",
          blocks: [
            { type: "text", text: "Un ciclo es algo que se repite una y otra vez, como los días de la semana." },
            { type: "text", text: "El ciclo de vida son los cambios por los que pasa un ser vivo. Va desde que nace hasta que tiene sus propias crías." },
            { type: "text", text: "Cuando esas crías crecen y tienen crías, el ciclo da otra vuelta." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Las cuatro partes de todo ciclo de vida",
          blocks: [
            {
              type: "points",
              items: [
                "Nacimiento: empieza una vida nueva. Los animales nacen o salen de un huevo. Las plantas brotan de una semilla.",
                "Crecimiento: se hace más grande y cambia.",
                "Reproducción: forma nuevos seres vivos de su misma especie.",
                "Muerte: su vida termina. Todos los seres vivos mueren en algún momento.",
              ],
            },
            { type: "text", text: "Los detalles cambian de una especie a otra. Pero las cuatro partes están en el ciclo de vida de todas." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Ciclos rápidos y ciclos lentos",
          blocks: [
            { type: "text", text: "Algunos ciclos de vida dan la vuelta muy rápido. Otros tardan muchísimo." },
            {
              type: "points",
              items: [
                "Una efímera adulta puede vivir un solo día.",
                "Un perro de casa suele vivir de 10 a 13 años.",
                "Algunas tortugas gigantes viven más de 100 años.",
                "Algunos pinos longevos tienen más de 4000 años.",
              ],
            },
          ],
        },
        {
          id: "s4",
          kind: "interactive",
          title: "¿Qué parte del ciclo es?",
          prompt: "Clasifica cada suceso según la parte del ciclo de vida que muestra.",
          widget: {
            kind: "sorter",
            categories: ["Nacimiento", "Crecimiento", "Reproducción", "Muerte"],
            items: [
              { id: "calf", text: "Nace un ternero en una granja.", answer: 0 },
              { id: "chick", text: "Un pollito rompe el cascarón y sale del huevo.", answer: 0 },
              { id: "puppy", text: "Un cachorro se hace más grande y fuerte.", answer: 1 },
              { id: "tadpole", text: "A un renacuajo le salen las patas de atrás.", answer: 1 },
              { id: "apple", text: "Un manzano da flores y luego frutos con semillas.", answer: 2 },
              { id: "kittens", text: "Una gata tiene una camada de gatitos.", answer: 2 },
              { id: "pumpkin", text: "Una planta de calabaza muere con la primera helada fuerte.", answer: 3 },
              { id: "oak", text: "Un roble muy viejo muere.", answer: 3 },
            ],
          },
        },
        {
          id: "s5",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "¿Qué cuatro partes comparten todos los ciclos de vida?",
              choices: ["Nacimiento, crecimiento, reproducción, muerte", "Huevo, larva, pupa, adulto", "Semilla, flor, fruto, árbol", "Bebé, niño, adolescente, adulto"],
              answer: 0,
              hint: "Una opción sirve solo para algunos insectos. Otra, solo para plantas. ¿Cuál sirve para todos los seres vivos?",
              explain: "Nacimiento, crecimiento, reproducción y muerte están en todo ciclo de vida. Huevo, larva, pupa y adulto es solo para algunos insectos.",
            },
            {
              id: "q2",
              prompt: "¿Por qué se llama ciclo de vida?",
              choices: ["Las crías crecen y tienen crías, así que se repite", "Los seres vivos se mueven en círculos", "Siempre dura un año"],
              answer: 0,
              hint: "Piensa en la rueda de una bicicleta. Da vueltas y vueltas.",
              explain: "Los adultos tienen crías. Las crías crecen, se hacen adultas y tienen sus propias crías. Así, el ciclo da vueltas sin parar.",
            },
            {
              id: "q3",
              prompt: "Un pez dorado pone huevos. ¿Qué parte del ciclo de vida es?",
              choices: ["Reproducción", "Crecimiento", "Muerte"],
              answer: 0,
              hint: "¿Qué saldrá de esos huevos?",
              explain: "Poner huevos es la forma en que los peces dorados forman peces nuevos. Formar nuevos seres vivos es reproducción.",
            },
          ],
        },
        {
          id: "s6",
          kind: "project",
          title: "Detective de ciclos",
          brief: "Elige una planta o un animal cerca de tu casa y busca pistas sobre su ciclo de vida.",
          steps: [
            "Elige algo que puedas encontrar cerca, como un diente de león, una paloma o una hormiga.",
            "Dibuja un círculo grande en una hoja, con cuatro flechas que den la vuelta.",
            "En los cuatro puntos del círculo, dibuja su nacimiento, crecimiento, reproducción y muerte.",
            "Busca pistas afuera: semillas, huevos, flores, crías o cáscaras vacías. Mira, pero nunca toques un nido ni sus huevos.",
            "Muéstrale tu círculo a alguien y explícale cómo vuelve a empezar el ciclo.",
          ],
        },
      ],
    },
    {
      id: "butterfly",
      title: "Las cuatro etapas de la mariposa",
      summary: "Huevo, larva, pupa y adulto: la mariposa cambia por completo mientras crece.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "Huevo",
          blocks: [
            { type: "text", text: "La mariposa empieza como un huevo del tamaño de la cabeza de un alfiler." },
            { type: "text", text: "La mariposa monarca pone cada huevo en una hoja de algodoncillo. Es la única planta que comen sus orugas." },
            { type: "text", text: "Si hace calor, a los 3 a 5 días sale una oruga diminuta." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Larva",
          blocks: [
            { type: "text", text: "La oruga es la larva. Su trabajo es comer y crecer." },
            { type: "text", text: "Crece tan rápido que su piel le queda chica. Por eso cambia de piel varias veces." },
            { type: "text", text: "Una oruga de monarca pasa unas dos semanas comiendo." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Pupa",
          blocks: [
            { type: "text", text: "Luego, la oruga se cuelga de cabeza y cambia de piel por última vez. Debajo aparece una funda dura: la crisálida." },
            { type: "text", text: "Esta etapa es la pupa. Por fuera parece quieta. Por dentro, su cuerpo se está transformando en mariposa." },
            { type: "text", text: "En la monarca, esto tarda entre una y dos semanas." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Adulto",
          blocks: [
            { type: "text", text: "La mariposa adulta sale de la crisálida con las alas mojadas y arrugadas. Las extiende y espera a que se sequen para volar." },
            { type: "text", text: "Las adultas beben néctar de las flores. Ya no crecen más." },
            { type: "text", text: "Las hembras adultas ponen huevos, y el ciclo vuelve a empezar." },
            {
              type: "points",
              items: ["Huevo, luego larva (oruga), luego pupa (crisálida), luego adulto.", "Un cambio tan grande se llama metamorfosis completa."],
            },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿Qué etapa es?",
          prompt: "Cada pista habla de una etapa de la vida de la mariposa. Clasifícalas.",
          widget: {
            kind: "sorter",
            categories: ["Huevo", "Larva", "Pupa", "Adulto"],
            items: [
              { id: "round", text: "Diminuto y redondo, pegado a una hoja", answer: 0 },
              { id: "hatch", text: "De aquí está por salir una oruga diminuta", answer: 0 },
              { id: "eats", text: "Come hojas todo el día y crece rápido", answer: 1 },
              { id: "sheds", text: "Cambia de piel a medida que crece", answer: 1 },
              { id: "case", text: "Cuelga quieta dentro de una funda dura", answer: 2 },
              { id: "rebuilt", text: "Su cuerpo se transforma por dentro", answer: 2 },
              { id: "nectar", text: "Tiene alas y bebe néctar", answer: 3 },
              { id: "lays", text: "Pone huevos en el algodoncillo", answer: 3 },
            ],
          },
        },
        {
          id: "s6",
          kind: "slide",
          title: "Otros insectos con cuatro etapas",
          blocks: [
            { type: "text", text: "Las mariquitas, los escarabajos, las abejas, las hormigas, las moscas y los mosquitos también pasan por huevo, larva, pupa y adulto." },
            { type: "text", text: "La larva de la mariquita no se parece en nada a una mariquita. Es larga y con espinas, como un caimán diminuto." },
            { type: "text", text: "Muchas polillas tejen un capullo de seda alrededor de su pupa. La pupa de la mariposa no tiene seda alrededor. Se llama crisálida." },
          ],
        },
        {
          id: "s7",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Huevo, oruga, ___, mariposa. ¿Qué etapa falta?",
              choices: ["Pupa", "Renacuajo", "Plántula"],
              answer: 0,
              hint: "Es la etapa en que la oruga cuelga dentro de una funda dura.",
              explain: "Huevo, larva, pupa y adulto. La oruga se vuelve pupa dentro de la crisálida, y de ahí sale la mariposa.",
            },
            {
              id: "q2",
              prompt: "¿Qué etapa come y crece más?",
              choices: ["La larva", "La pupa", "El adulto"],
              answer: 0,
              hint: "Los adultos ya no crecen. La pupa no come nada.",
              explain: "La larva, es decir, la oruga, come y crece. Los adultos beben néctar pero no crecen, y la pupa no come.",
            },
            {
              id: "q3",
              prompt: "Una mariposa con alas pequeñas es una mariposa joven que va a crecer. ¿Verdadero o falso?",
              choices: ["Falso", "Verdadero"],
              answer: 0,
              hint: "¿Los insectos adultos siguen creciendo?",
              explain: "Falso. Cuando sale de la crisálida, la mariposa ya es adulta y no crece más. Una mariposa pequeña es de una especie más chica, o comió menos cuando era oruga.",
            },
          ],
        },
        {
          id: "s8",
          kind: "project",
          title: "A buscar orugas",
          brief: "Busca afuera huevos de insecto, orugas o una crisálida, y observa qué pasa.",
          steps: [
            "Con una persona adulta, revisa el revés de las hojas en un jardín o un parque.",
            "Si encuentras huevos o una oruga, obsérvalos de cerca, pero déjalos en su planta.",
            "Dibuja lo que ves y también la planta donde está.",
            "Vuelve a mirar cada pocos días. ¿Creció? ¿Se movió? ¿Cambió de piel?",
            "Quizá no encuentres nada la primera vez. Anota las plantas que revisaste.",
          ],
        },
      ],
    },
    {
      id: "frogs-and-more",
      title: "Ranas, gallinas y otros caminos",
      summary: "La rana cambia por completo, el pollito se forma dentro del huevo y muchas crías se parecen a sus padres.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "El ciclo de vida de la rana",
          blocks: [
            { type: "text", text: "La mayoría de las ranas ponen sus huevos en el agua." },
            {
              type: "points",
              items: [
                "Huevo: un puntito oscuro dentro de una gelatina transparente.",
                "Renacuajo: nace con cola y branquias, y vive bajo el agua.",
                "Rana joven: le salen patas, la cola se le encoge y empieza a respirar aire.",
                "Rana adulta: tiene pulmones y cuatro patas. Casi todas viven en la tierra y en el agua.",
              ],
            },
            { type: "text", text: "El cuerpo de la rana cambia por completo. Eso también es metamorfosis." },
          ],
        },
        {
          id: "s2",
          kind: "interactive",
          title: "Las etapas de la rana",
          prompt: "Cada pista habla de una etapa de la vida de la rana. Clasifícalas.",
          widget: {
            kind: "sorter",
            categories: ["Huevo", "Renacuajo", "Rana joven", "Rana adulta"],
            items: [
              { id: "jelly", text: "Un puntito oscuro en una bolita de gelatina", answer: 0 },
              { id: "gills", text: "Nada con su cola y respira con branquias", answer: 1 },
              { id: "algae", text: "No tiene patas y mordisquea algas en el estanque", answer: 1 },
              { id: "short-tail", text: "Tiene cuatro patas y una cola corta", answer: 2 },
              { id: "shrinking", text: "La cola se le está encogiendo", answer: 2 },
              { id: "tongue", text: "Respira con pulmones y atrapa insectos con la lengua", answer: 3 },
              { id: "lays", text: "Pone huevos en un estanque", answer: 3 },
            ],
          },
        },
        {
          id: "s3",
          kind: "slide",
          title: "El pollito se forma dentro del huevo",
          blocks: [
            {
              type: "points",
              items: [
                "Huevo: la gallina se echa sobre sus huevos para darles calor.",
                "Pollito: unos 21 días después, un pollito con plumón rompe el cascarón.",
                "Adulto: al pollito le salen plumas y se hace gallina o gallo.",
              ],
            },
            { type: "text", text: "Solo nacen pollitos de los huevos que tienen un pollito formándose adentro. Los huevos de la tienda no sirven para eso." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Crías que parecen adultos pequeños",
          blocks: [
            { type: "text", text: "Algunas crías parecen copias pequeñas de sus padres. Más que nada, solo crecen." },
            {
              type: "points",
              items: [
                "Un gatito parece un gato pequeño.",
                "Una tortuguita parece una tortuga pequeña.",
                "El saltamontes nace como ninfa: un saltamontes pequeño sin alas para volar. Cambia de piel varias veces, y después de la última ya tiene alas completas.",
              ],
            },
            { type: "text", text: "Las personas también somos así. Un bebé tiene la forma de un adulto, pero en pequeño." },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿Gran cambio o solo crece?",
          prompt: "¿La cría de este animal cambia mucho de forma, o parece un adulto pequeño?",
          widget: {
            kind: "sorter",
            categories: ["Cambia mucho de forma", "Parece un adulto pequeño"],
            items: [
              { id: "frog", text: "La rana", answer: 0 },
              { id: "butterfly", text: "La mariposa", answer: 0 },
              { id: "cat", text: "El gato", answer: 1 },
              { id: "ladybug", text: "La mariquita", answer: 0 },
              { id: "turtle", text: "La tortuga", answer: 1 },
              { id: "horse", text: "El caballo", answer: 1 },
              { id: "mosquito", text: "El mosquito", answer: 0 },
              { id: "person", text: "La persona", answer: 1 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Huevo, renacuajo, ___, rana adulta. ¿Qué etapa falta?",
              choices: ["Rana joven", "Pollito", "Pupa"],
              answer: 0,
              hint: "En esta etapa tiene patas y la cola se le encoge.",
              explain: "Al renacuajo le salen patas y se vuelve rana joven. Luego la cola desaparece y ya es una rana adulta.",
            },
            {
              id: "q2",
              prompt: "¿Qué cría parece una copia pequeña de sus padres?",
              choices: ["Un gatito", "Una oruga", "Un renacuajo"],
              answer: 0,
              hint: "¿Qué cría tiene la misma forma que el adulto?",
              explain: "El gatito tiene la forma de un gato y solo crece. La oruga y el renacuajo cambian de forma por completo.",
            },
            {
              id: "q3",
              prompt: "¿Cómo respira un renacuajo bajo el agua?",
              choices: ["Con branquias", "Con pulmones", "Aguanta la respiración"],
              answer: 0,
              hint: "Los peces respiran bajo el agua de la misma manera.",
              explain: "Los renacuajos tienen branquias, como los peces. Al volverse ranas, les crecen pulmones y empiezan a respirar aire.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Rueda del ciclo de vida",
          brief: "Haz una rueda de papel que gire por el ciclo de vida de la rana.",
          steps: [
            "Recorta dos círculos de papel del mismo tamaño.",
            "Divide un círculo en cuatro partes iguales, como una pizza. Dibuja en orden huevo, renacuajo, rana joven y rana adulta, una en cada parte.",
            "En el otro círculo, recorta una ventana del tamaño de una parte.",
            "Pon encima el círculo con ventana. Pide a un adulto que atraviese los dos centros con un broche mariposa o encuadernador.",
            "Gira la rueda. Cuenta la historia de cada etapa cuando aparezca en la ventana.",
          ],
        },
      ],
    },
    {
      id: "plant-life-cycle",
      title: "El ciclo de vida de una planta",
      summary: "La semilla brota, la planta crece y florece, las flores dan semillas y las semillas viajan a lugares nuevos.",
      minutes: 14,
      scenes: [
        {
          id: "s1",
          kind: "slide",
          title: "De semilla a plántula",
          blocks: [
            { type: "text", text: "Dentro de una semilla hay una plantita y una reserva de alimento para ella." },
            { type: "text", text: "Con agua, aire y calor, la semilla brota. Primero sale la raíz, que crece hacia abajo. Luego sale un tallito que crece hacia la luz." },
            { type: "text", text: "La planta joven se llama plántula. Cuando ya tiene hojas, puede hacer su propio alimento con la luz del Sol." },
          ],
        },
        {
          id: "s2",
          kind: "slide",
          title: "Cómo crece una planta de frijol",
          blocks: [
            { type: "text", text: "Esta gráfica muestra cómo podría crecer una planta de frijol en su primer mes. Las plantas reales varían." },
            {
              type: "visual",
              visual: {
                kind: "line-graph",
                points: [
                  [0, 0],
                  [5, 0],
                  [10, 4],
                  [15, 10],
                  [20, 18],
                  [25, 24],
                  [30, 27],
                ],
                xLabel: "Días desde la siembra",
                yLabel: "Altura (cm)",
              },
              alt: "Gráfica de la altura de una planta de frijol durante 30 días. Mide 0 cm hasta el día 5, 4 cm el día 10, 10 cm el día 15, 18 cm el día 20, 24 cm el día 25 y 27 cm el día 30.",
            },
            { type: "text", text: "Al principio no se ve nada sobre la tierra. Luego la planta crece rápido, y más adelante crece más despacio." },
          ],
        },
        {
          id: "s3",
          kind: "slide",
          title: "Las flores dan semillas",
          blocks: [
            { type: "text", text: "Una planta adulta da flores." },
            {
              type: "text",
              text: "Las abejas y otros animales llevan un polvo llamado polen de flor en flor. En algunas plantas, como el pasto y el maíz, el viento lleva el polen.",
            },
            {
              type: "text",
              text: "Cuando el polen llega a la parte correcta de la flor, empiezan a formarse semillas. Muchas plantas forman un fruto alrededor. La manzana, la vaina del frijol y el tomate son frutos con semillas.",
            },
            { type: "text", text: "Algunas plantas, como el frijol y el girasol, mueren después de dar semillas. Otras, como el manzano, florecen año tras año." },
          ],
        },
        {
          id: "s4",
          kind: "slide",
          title: "Semillas viajeras",
          blocks: [
            { type: "text", text: "Las semillas necesitan espacio para crecer. Por eso las plantas tienen maneras de esparcirlas." },
            {
              type: "points",
              items: [
                "Viento: las semillas del diente de león flotan con paracaídas de pelusa. Las del arce giran como helicópteros.",
                "Animales: los cadillos se pegan al pelaje. Los pájaros comen frutos y dejan caer las semillas lejos. Las ardillas entierran bellotas, y las que olvidan pueden volverse robles.",
                "Agua: un coco puede flotar por el mar hasta una playa nueva.",
              ],
            },
          ],
        },
        {
          id: "s5",
          kind: "interactive",
          title: "¿Cómo viaja?",
          prompt: "¿Cómo llega cada semilla a un lugar nuevo: con el viento, con los animales o con el agua?",
          widget: {
            kind: "sorter",
            categories: ["Viento", "Animales", "Agua"],
            items: [
              { id: "dandelion", text: "Semillas de diente de león con pelusa", answer: 0 },
              { id: "maple", text: "Una semilla de arce que gira", answer: 0 },
              { id: "milkweed", text: "Semillas de algodoncillo con hilos sedosos", answer: 0 },
              { id: "burr", text: "Un cadillo pegado al pelo de un perro", answer: 1 },
              { id: "cherry", text: "Semillas dentro de cerezas que se comió un pájaro", answer: 1 },
              { id: "acorn", text: "Una bellota que enterró una ardilla", answer: 1 },
              { id: "coconut", text: "Un coco que flota en el mar", answer: 2 },
              { id: "mangrove", text: "Una plantita de mangle que flota hasta otra orilla", answer: 2 },
            ],
          },
        },
        {
          id: "s6",
          kind: "quiz",
          title: "Comprueba lo que sabes",
          questions: [
            {
              id: "q1",
              prompt: "Cuando brota una semilla de frijol, ¿qué sale primero?",
              choices: ["La raíz", "Una flor", "Una vaina"],
              answer: 0,
              hint: "Antes de crecer hacia arriba, la plantita necesita tomar agua.",
              explain: "Primero sale la raíz, que crece hacia abajo para tomar agua. Después sale un tallito que crece hacia la luz.",
            },
            {
              id: "q2",
              prompt: "Una planta de frijol medía 10 cm el día 15, 18 cm el día 20 y 24 cm el día 25. ¿Cuándo creció más?",
              choices: ["Del día 15 al día 20", "Del día 20 al día 25", "Creció lo mismo las dos veces"],
              answer: 0,
              hint: "Resta para hallar cada cambio: 18 − 10 y luego 24 − 18.",
              explain: "Del día 15 al 20 creció 8 cm. Del día 20 al 25 creció 6 cm. Así que creció más en el primer tramo.",
            },
            {
              id: "q3",
              prompt: "¿Cómo ayuda un fruto, como una baya, a que la planta se esparza?",
              choices: ["Los animales lo comen y dejan las semillas en otros lugares", "Mantiene caliente a la planta de noche", "Absorbe agua para las raíces"],
              answer: 0,
              hint: "Piensa en el pájaro y las cerezas.",
              explain: "Los animales comen el fruto y dejan caer las semillas en otro lugar, muchas veces lejos. Así la planta llega a lugares nuevos.",
            },
            {
              id: "q4",
              prompt: "Un girasol muere después de dar semillas. ¿Se acabaron los girasoles en ese jardín?",
              choices: ["No, sus semillas pueden volverse girasoles nuevos", "Sí, ya no puede haber más girasoles"],
              answer: 0,
              hint: "¿Qué formó el girasol antes de morir?",
              explain: "Cada semilla guarda una plantita de girasol. Cuando las semillas brotan, el ciclo vuelve a empezar.",
            },
          ],
        },
        {
          id: "s7",
          kind: "project",
          title: "Frijol en bolsa",
          brief: "Observa cómo un frijol empieza su ciclo de vida, y mídelo mientras crece.",
          steps: [
            "Moja una toalla de papel y métela en una bolsa transparente con cierre.",
            "Pon 2 o 3 frijoles secos entre la toalla y la pared de la bolsa.",
            "Pega la bolsa en una ventana con luz, pero sin sol fuerte directo. Mantén la toalla húmeda.",
            "Cada dos días, dibuja lo que ves. Mide la raíz y el tallo con una regla.",
            "Cuando el tallo tenga hojas, siémbralo en un vaso con tierra y sigue midiendo.",
            "Haz una gráfica de la altura de tu planta. ¿Su línea se parece a la de esta lección?",
          ],
        },
      ],
    },
  ],
};

export default lifeCyclesEs;
