/**
 * WRAP (spec §5.2 WRAP, §5.5, §5.9; strategy law 2). Ends one session and
 * leaves behind everything the next session and the parent report read:
 *
 *   1. the session summary from the `tutor-summary` stage — recap and practice
 *      spoken to the learner, plus one `tutorNote` for the account holder;
 *   2. the learner profile regenerated by `tutor-model-update`, merged over the
 *      previous one so a bad reply cannot erase what was known;
 *   3. the remaining minutes settled against the entitlement;
 *   4. a `session` evidence row (ids, counts, tags — never transcript text).
 *
 * Law 2: the parent-facing note is written as generated text and is stored
 * with `GENERATED_LABEL` beside it in the report, never as a human's words.
 * A model failure is not a failed wrap: the session still ends, with a
 * deterministic summary assembled from the session's own counters.
 */
import { createLogger } from '@/lib/logger';
import type {
  LearnerProfile,
  SessionSummary,
  TutorSession,
  TurnRecord,
} from '@/lib/tutor/contracts';
import { TUTOR_LLM_SOURCES } from '@/lib/tutor/cost/sources';
import type { Queryable } from '@/lib/tutor/db';
import { skillById } from '@/lib/tutor/graph/graph';
import { isSubjectSkillId } from '@/lib/tutor/graph/subjects';
import { writeEvidence } from '@/lib/tutor/model/evidence';
import { listMisconceptionRows } from '@/lib/tutor/model/service';
import { loadPromptFile } from '@/lib/tutor/prompts/loader';
import {
  listTurns,
  loadSession,
  meterMinutes,
  saveSessionState,
} from '@/lib/tutor/session/service';
import { loadLearnerProfile, toLearnerProfile } from '@/lib/tutor/turn/context';
import { extractJsonObject, tutorCallLLM, type TutorLlmScope } from '@/lib/tutor/turn/llm-call';
import type { Principal } from '@/lib/tutor/contracts';
import type { WrapResponse } from '@/lib/tutor/wire';

const log = createLogger('tutor-wrap');

/** Turns of the session the summary stage reads. Enough for a recap, bounded for cost. */
export const WRAP_TRANSCRIPT_TURNS = 40;
const RECAP_MAX = 700;
const PRACTICE_MAX = 200;
const NOTE_MAX = 500;

export type WrapErrorCode = 'NOT_FOUND';

export type WrapOutcome =
  | { ok: true; response: WrapResponse }
  | { ok: false; code: WrapErrorCode; message: string };

export interface WrapDeps {
  now?: Date;
}

function sentence(value: unknown, max: number): string {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim().slice(0, max) : '';
}

function skillNames(ids: readonly string[], topic: string | null = null): string {
  const names = ids.map((id) => skillById(id)?.name ?? id);
  if (names.length === 0) return topic ?? 'what you brought';
  // One subject skill and the learner's own words: say the words, not "Math".
  if (names.length === 1) return topic && isSubjectSkillId(ids[0]) ? topic : names[0]!;
  return `${names.slice(0, -1).join(', ')} and ${names.at(-1)}`;
}

/**
 * The summary the server can always produce: plain sentences over the counters
 * the loop already wrote. Used when the model is unavailable or answers badly,
 * so WRAP never leaves a session without a record.
 */
export function fallbackSummary(input: {
  skillsTouched: readonly string[];
  checks: number;
  checksCorrect: number;
  minutes: number;
  openMisconceptions: readonly string[];
  /** The learner's own words for a topic session (D35). */
  topic?: string | null;
}): SessionSummary {
  const topic = skillNames(input.skillsTouched, input.topic ?? null);
  const checkLine =
    input.checks > 0
      ? ` You answered ${input.checksCorrect} of ${input.checks} checks correctly.`
      : '';
  return {
    recap: `We worked on ${topic} for about ${Math.max(1, input.minutes)} minutes.${checkLine}`,
    practice: [`Try two more ${topic} problems on your own before next time.`],
    tutorNote:
      `The learner spent ${Math.max(1, input.minutes)} minutes on ${topic} and answered ` +
      `${input.checksCorrect} of ${input.checks} checks correctly.` +
      (input.openMisconceptions.length > 0
        ? ` Open misconception tags: ${input.openMisconceptions.join(', ')}.`
        : ''),
    skillsTouched: [...input.skillsTouched],
    checks: input.checks,
    checksCorrect: input.checksCorrect,
  };
}

/** Parses the summary stage's JSON; null when the shape is not usable. */
export function parseSummaryReply(
  text: string,
  counters: { skillsTouched: readonly string[]; checks: number; checksCorrect: number },
): SessionSummary | null {
  const json = extractJsonObject(text);
  if (!json) return null;
  const recap = sentence(json.recap, RECAP_MAX);
  const tutorNote = sentence(json.tutorNote, NOTE_MAX);
  if (!recap || !tutorNote) return null;
  const practice = Array.isArray(json.practice)
    ? json.practice
        .map((item) => sentence(item, PRACTICE_MAX))
        .filter(Boolean)
        .slice(0, 3)
    : [];
  return {
    recap,
    practice: practice.length > 0 ? practice : ['Try two more problems like the ones we did.'],
    tutorNote,
    skillsTouched: [...counters.skillsTouched],
    checks: counters.checks,
    checksCorrect: counters.checksCorrect,
  };
}

/** Merges the model's profile over the previous one; unusable fields keep their old value. */
export function mergeProfile(
  previous: LearnerProfile | null,
  reply: string,
  now: Date,
): LearnerProfile | null {
  const json = extractJsonObject(reply);
  if (!json) return previous;
  const merged = toLearnerProfile(
    {
      subjects: json.subjects ?? previous?.subjects ?? [],
      recurringMisconceptions:
        json.recurringMisconceptions ?? previous?.recurringMisconceptions ?? [],
      pace: json.pace ?? previous?.pace ?? 'steady',
      explanationStylesThatWorked:
        json.explanationStylesThatWorked ?? previous?.explanationStylesThatWorked ?? [],
      notes: typeof json.notes === 'string' ? json.notes : (previous?.notes ?? ''),
    },
    now.toISOString(),
  );
  return merged ?? previous;
}

function transcriptLines(turns: readonly TurnRecord[]): string {
  return turns
    .slice(-WRAP_TRANSCRIPT_TURNS)
    .map((turn) => `${turn.role === 'tutor' ? 'Tutor' : 'Learner'}: ${turn.text}`)
    .join('\n');
}

async function writeProfile(
  db: Queryable,
  accountId: string,
  learnerId: string,
  profile: LearnerProfile,
): Promise<void> {
  await db.query(
    `INSERT INTO learner_profiles (learner_id, account_id, profile, updated_at)
     VALUES ($1, $2, $3::jsonb, now())
     ON CONFLICT (learner_id) DO UPDATE SET profile = EXCLUDED.profile, updated_at = now()`,
    [
      learnerId,
      accountId,
      JSON.stringify({
        subjects: profile.subjects,
        recurringMisconceptions: profile.recurringMisconceptions,
        pace: profile.pace,
        explanationStylesThatWorked: profile.explanationStylesThatWorked,
        notes: profile.notes,
      }),
    ],
  );
}

/**
 * Ends the session and writes its record. Idempotent: wrapping an already
 * wrapped session answers the stored summary without calling the model again.
 */
export async function wrapSession(
  db: Queryable,
  principal: Principal,
  sessionId: string,
  deps: WrapDeps = {},
): Promise<WrapOutcome> {
  const now = deps.now ?? new Date();
  const record = await loadSession(db, principal, sessionId);
  if (!record || !principal.learnerId) {
    return { ok: false, code: 'NOT_FOUND', message: 'No such session.' };
  }
  const { accountId } = principal;
  const learnerId = principal.learnerId;
  if (record.session.phase === 'ended' && record.session.summary) {
    return { ok: true, response: { summary: record.session.summary, session: record.session } };
  }

  const [turns, misconceptions, previousProfile] = await Promise.all([
    listTurns(db, sessionId, WRAP_TRANSCRIPT_TURNS),
    listMisconceptionRows(db, accountId, learnerId),
    loadLearnerProfile(db, accountId, learnerId),
  ]);
  const open = misconceptions.filter((row) => row.status === 'open').map((row) => row.tag);
  const resolved = misconceptions.filter((row) => row.status === 'resolved').map((row) => row.tag);

  const metered = await meterMinutes(db, record, now, { settleRemainder: true });
  const minutes = record.session.minutes + metered.minutes;
  const counters = {
    skillsTouched: record.state.skillsTouched,
    checks: record.state.checks.count,
    checksCorrect: record.state.checks.correct,
  };
  const scope: TutorLlmScope = { accountId, learnerId, sessionId, turnId: null };
  const facts = [
    `Band: ${record.band}. Minutes: ${minutes}.`,
    ...(record.state.topic
      ? [`Topic the learner chose: "${record.state.topic.text}" (${record.state.topic.subject}).`]
      : []),
    `Skills touched: ${counters.skillsTouched.map((id) => skillById(id)?.name ?? id).join(', ') || 'none recorded'}.`,
    `Checks: ${counters.checksCorrect} correct of ${counters.checks}.`,
    `Hints given: ${record.state.hints}.`,
    `Open misconceptions: ${open.join(', ') || 'none'}. Resolved: ${resolved.join(', ') || 'none'}.`,
    `Re-teach approaches used: ${record.state.reteachUsed.join(', ') || 'none'}.`,
    '',
    'Transcript:',
    transcriptLines(turns),
  ].join('\n');

  let cents = 0;
  let summary = fallbackSummary({
    ...counters,
    minutes,
    openMisconceptions: open,
    topic: record.state.topic?.text ?? null,
  });
  try {
    const result = await tutorCallLLM({
      db,
      scope,
      source: TUTOR_LLM_SOURCES.summary,
      band: record.band,
      system: loadPromptFile('wrap'),
      prompt: facts,
      maxOutputTokens: 600,
    });
    cents += result.cents;
    summary = parseSummaryReply(result.text, counters) ?? summary;
  } catch (error) {
    log.warn(
      `summary stage failed session=${sessionId}: ${error instanceof Error ? error.name : 'error'}`,
    );
  }

  let profile = previousProfile;
  try {
    const result = await tutorCallLLM({
      db,
      scope,
      source: TUTOR_LLM_SOURCES.modelUpdate,
      band: record.band,
      system: loadPromptFile('profile'),
      prompt: [
        `Previous profile: ${previousProfile ? JSON.stringify(previousProfile) : '(none)'}`,
        `This session's summary: ${summary.recap}`,
        `Tutor note: ${summary.tutorNote}`,
        facts,
      ].join('\n'),
      maxOutputTokens: 500,
    });
    cents += result.cents;
    profile = mergeProfile(previousProfile, result.text, now);
  } catch (error) {
    log.warn(
      `profile stage failed session=${sessionId}: ${error instanceof Error ? error.name : 'error'}`,
    );
  }
  if (profile) await writeProfile(db, accountId, learnerId, profile);

  await db.query(`UPDATE sessions SET summary = $2::jsonb WHERE id = $1`, [
    sessionId,
    JSON.stringify(summary),
  ]);
  await saveSessionState(db, sessionId, 'ended', metered.state, {
    costCentsDelta: cents,
    endedAt: now,
  });
  await writeEvidence(db, {
    accountId,
    learnerId,
    sessionId,
    type: 'session',
    assisted: record.state.hints > 0,
    payload: {
      minutes,
      checks: counters.checks,
      checksCorrect: counters.checksCorrect,
      hints: record.state.hints,
      skillsTouched: counters.skillsTouched,
      misconceptionsOpen: open,
      misconceptionsResolved: resolved,
      droppedActions: record.state.droppedActions,
      target: record.state.target,
      cents,
    },
  });

  const reloaded = await loadSession(db, principal, sessionId);
  const session: TutorSession = reloaded?.session ?? {
    ...record.session,
    phase: 'ended',
    minutes,
    summary,
  };
  return { ok: true, response: { summary, session } };
}
