import { type Passage, q } from "./types";

// Level 1 poems and the first informational articles.
export const L1_POEMS_INFO: Passage[] = [
  {
    id: "river-keeps",
    level: 1,
    genre: "poem",
    en: [
      {
        title: "What the River Keeps",
        paras: [
          "In March the river is loud.\nIt shoulders the broken ice aside\nand hurries under the Elm Street bridge\nas if it is late for something important.",
          "In June it slows down and spreads out,\nlazy and brown and warm as bathwater,\nand lets the kids from Maple Street\nfloat on their backs and argue about the clouds.",
          "In August it shrinks to a whisper.\nRocks we have never seen before\nlift their gray heads out of the water,\nand the herons stand in it up to their knees.",
          "In October it goes quiet and thin.\nIt carries the maple leaves away,\none red boat at a time,\nand never tells us where they land.",
          "In January it hides\nunder a hard white lid,\nand you would swear it was gone for good\nif you didn't kneel at the frozen edge,",
          "press your ear against the ice,\nand hear it, small and steady underneath,\nstill traveling the way it always travels,\nstill keeping its one promise to the sea.",
          "My grandfather says I've changed this year,\ntaller and quieter, harder to read,\nalways somewhere else when he calls my name.\nMaybe so. But if he listens closely,\nhe will hear me underneath, still going.",
        ],
      },
    ],
    es: [
      {
        title: "Lo que guarda el río",
        paras: [
          "En marzo el río es ruidoso.\nEmpuja con el hombro el hielo roto\ny corre bajo el puente de la calle Olmo\ncomo si llegara tarde a algo importante.",
          "En junio se calma y se ensancha,\nperezoso, café y tibio como agua de baño,\ny deja que los niños de la calle Arce\nfloten bocarriba discutiendo sobre las nubes.",
          "En agosto se encoge hasta ser un susurro.\nPiedras que nunca habíamos visto\nasoman sus cabezas grises sobre el agua,\ny las garzas se paran en él con el agua a las rodillas.",
          "En octubre se queda callado y delgado.\nSe lleva las hojas del arce,\nun barquito rojo a la vez,\ny nunca nos dice dónde llegan.",
          "En enero se esconde\nbajo una tapa dura y blanca,\ny jurarías que se fue para siempre\nsi no te arrodillaras en la orilla helada,",
          "pegaras la oreja al hielo\ny lo oyeras, pequeño y constante allá abajo,\ntodavía viajando como siempre viaja,\ntodavía cumpliendo su única promesa al mar.",
          "Mi abuelo dice que este año he cambiado,\nmás alto y más callado, más difícil de entender,\nsiempre en otra parte cuando dice mi nombre.\nTal vez. Pero si escucha con atención,\nme oirá allá abajo, todavía en camino.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "plot-not-theme", "contradicts-text"],
        [
          "Which statement best expresses a theme of the poem?",
          "A person can change on the outside and still stay the same underneath.",
          ["Rivers", "The river is loud in March, warm in June, thin in October, and frozen over in January.", "Growing up means losing the person you used to be."],
          ["he will hear me underneath, still going"],
          "The river looks different every season but keeps flowing under the ice. The speaker says the same is true of them, which is the poem's message.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del poema?",
          "Una persona puede cambiar por fuera y seguir siendo la misma por dentro.",
          ["Los ríos", "El río es ruidoso en marzo, tibio en junio, delgado en octubre y se congela en enero.", "Crecer significa perder a la persona que eras antes."],
          ["me oirá allá abajo, todavía en camino"],
          "El río se ve distinto en cada estación, pero sigue corriendo bajo el hielo. La voz poética dice que a ella le pasa lo mismo, y ese es el mensaje del poema.",
        ],
      ),
      q(
        "theme.develop",
        ["contradicts-text", "too-narrow", "not-in-text"],
        [
          "How does the last stanza connect the speaker to the river?",
          "Like the frozen river, the speaker has changed on the surface but keeps going underneath.",
          ["The speaker has stopped changing, the way the river stops moving once it freezes in winter.", "The speaker has grown taller this year.", "The speaker wants to follow the river all the way to the sea."],
          ["still traveling the way it always travels", "he will hear me underneath, still going"],
          "The river is still traveling under the ice, and the speaker is still “going” underneath a quieter surface. The last stanza ties the two together.",
        ],
        [
          "¿Cómo conecta la última estrofa a la voz poética con el río?",
          "Como el río congelado, la voz poética cambió por fuera, pero sigue en camino por dentro.",
          ["La voz poética dejó de cambiar, igual que el río deja de moverse cuando se congela en invierno.", "La voz poética creció este año.", "La voz poética quiere seguir el río hasta llegar al mar."],
          ["todavía viajando como siempre viaja", "me oirá allá abajo, todavía en camino"],
          "El río sigue viajando bajo el hielo, y la voz poética sigue “en camino” por debajo de su silencio. La última estrofa une a los dos.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "not-in-text", "contradicts-text"],
        [
          "In stanza 4, what does the poet mean by “one red boat at a time”?",
          "The floating leaves look like tiny boats carried downstream.",
          ["Children are sailing small red boats down the river in the fall.", "The river is too thin in October for real boats to pass.", "The leaves are sinking to the bottom of the river one by one."],
          ["It carries the maple leaves away,"],
          "The red maple leaves float on the water like little boats. The phrase is a metaphor, not real boats.",
        ],
        [
          "En la estrofa 4, ¿qué quiere decir el poeta con “un barquito rojo a la vez”?",
          "Las hojas que flotan parecen barquitos que el río lleva corriente abajo.",
          ["Unos niños navegan barquitos rojos por el río en el otoño.", "En octubre el río está tan delgado que no pueden pasar barcos de verdad.", "Las hojas se hunden una por una hasta el fondo del río."],
          ["Se lleva las hojas del arce,"],
          "Las hojas rojas del arce flotan en el agua como barquitos. La frase es una metáfora, no habla de barcos de verdad.",
        ],
      ),
      q(
        "words.tone",
        ["opposite-tone", "too-narrow", "ignores-connotation"],
        [
          "Which word best describes the speaker's attitude toward the river?",
          "Admiring",
          ["Fearful", "Sad", "Indifferent"],
          ["still keeping its one promise to the sea"],
          "The speaker describes the river with respectful words like “steady” and “promise” and even compares themself to it. That shows admiration.",
        ],
        [
          "¿Qué palabra describe mejor la actitud de la voz poética hacia el río?",
          "Admirativa",
          ["Temerosa", "Triste", "Indiferente"],
          ["todavía cumpliendo su única promesa al mar"],
          "La voz poética describe el río con palabras de respeto como “constante” y “promesa”, y hasta se compara con él. Eso muestra admiración.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "What can you infer about the speaker's grandfather from stanza 7?",
          "He has noticed the speaker growing up and pulling away a little.",
          ["He is proud that the speaker has grown taller than he is this year.", "He no longer pays any attention to the speaker.", "He believes all young people stop listening to their families."],
          ["always somewhere else when he calls my name"],
          "The grandfather sees that the speaker is quieter, harder to read, and often “somewhere else.” He has noticed a change and feels some distance.",
        ],
        [
          "¿Qué puedes inferir sobre el abuelo de la voz poética en la estrofa 7?",
          "Ha notado que su nieto está creciendo y se aleja un poco.",
          ["Está orgulloso de que su nieto ya sea más alto que él.", "Ya no le presta ninguna atención a su nieto.", "Cree que todos los jóvenes dejan de escuchar a su familia."],
          ["siempre en otra parte cuando dice mi nombre"],
          "El abuelo ve que su nieto está más callado, es más difícil de entender y a menudo está “en otra parte”. Notó un cambio y siente cierta distancia.",
        ],
      ),
    ],
  },
  {
    id: "grandmother-hands",
    level: 1,
    genre: "poem",
    en: [
      {
        title: "My Grandmother's Hands",
        paras: [
          "My grandmother's hands are not soft.\nThey are maps of everything they have done:\na white scar from a tin can in 1979,\na burn shaped like a comma from the comal.",
          "Every Sunday they wake before the sun.\nThey press the masa into perfect circles,\nflip each tortilla with bare fingertips,\nand never once complain about the heat.",
          "They have sewn the hems of my brothers' jeans\nand the torn knee of my soccer uniform.\nThey have braided my hair so tight\nI could feel my thoughts lining up.",
          "When I was small and sick with fever,\nthey rested on my forehead all night,\ncool as river stones,\nand the fever did not dare to stay.",
          "She does not say “I love you” very often.\nThe words seem too small for her mouth,\nlike shoes she has outgrown.\nShe says “Eat,” and “Sit up straight,” and “Did you finish?”",
          "But I have learned to read her hands\nthe way you read a letter from far away,\nslowly, more than once,\nfinding something new each time I read it.",
          "Someday my hands will be maps too.\nI hope they show the same roads:\nthe early mornings, the patient stitches,\nthe warm circle of a tortilla, given away.",
        ],
      },
    ],
    es: [
      {
        title: "Las manos de mi abuela",
        paras: [
          "Las manos de mi abuela no son suaves.\nSon mapas de todo lo que han hecho:\nuna cicatriz blanca de una lata en 1979,\nuna quemadura en forma de coma, del comal.",
          "Cada domingo despiertan antes que el sol.\nAplanan la masa en círculos perfectos,\nvoltean cada tortilla con la punta de los dedos\ny nunca, ni una sola vez, se quejan del calor.",
          "Han cosido el dobladillo de los pantalones de mis hermanos\ny la rodilla rota de mi uniforme de fútbol.\nMe han trenzado el pelo tan apretado\nque sentía mis ideas ponerse en fila.",
          "Cuando era pequeña y ardía en fiebre,\ndescansaron en mi frente toda la noche,\nfrescas como piedras de río,\ny la fiebre no se atrevió a quedarse.",
          "Ella no dice “te quiero” muy seguido.\nLas palabras parecen quedarle chicas,\ncomo zapatos que ya no le entran.\nDice “Come”, “Siéntate derecha” y “¿Ya terminaste?”.",
          "Pero he aprendido a leer sus manos\ncomo se lee una carta que viene de lejos:\ndespacio, más de una vez,\nencontrando algo nuevo cada vez que la leo.",
          "Algún día mis manos también serán mapas.\nOjalá muestren los mismos caminos:\nlas madrugadas, las puntadas pacientes,\nel círculo tibio de una tortilla regalada.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "plot-not-theme", "contradicts-text"],
        [
          "Which statement best expresses a theme of the poem?",
          "Love can be shown through everyday acts of care, not only through words.",
          ["Cooking", "The grandmother makes tortillas, sews jeans, braids hair, and stays up with the speaker during a fever.", "People who love each other always say so out loud."],
          ["But I have learned to read her hands"],
          "The grandmother rarely says “I love you,” but every stanza shows her caring through work. The speaker learns to read that love in her hands.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del poema?",
          "El cariño se puede mostrar con actos de cuidado de todos los días, no solo con palabras.",
          ["La cocina", "La abuela hace tortillas, cose pantalones, trenza el pelo y se queda despierta cuando la voz poética tiene fiebre.", "Las personas que se quieren siempre lo dicen en voz alta."],
          ["Pero he aprendido a leer sus manos"],
          "La abuela casi nunca dice “te quiero”, pero cada estrofa muestra su cariño a través del trabajo. La voz poética aprende a leer ese amor en sus manos.",
        ],
      ),
      q(
        "theme.develop",
        ["contradicts-text", "not-in-text", "off-point-evidence"],
        [
          "How does stanza 5 help develop the poem's theme?",
          "It shows that she rarely says loving words, so her actions must carry her love.",
          ["It shows that the grandmother is too strict and busy to care much about the speaker.", "It shows that the grandmother can barely speak because she is sick.", "It describes the Sunday mornings when the grandmother makes tortillas for the whole family."],
          ["The words seem too small for her mouth"],
          "Stanza 5 says the grandmother almost never says “I love you.” That is why the rest of the poem looks for her love in what her hands do.",
        ],
        [
          "¿Cómo ayuda la estrofa 5 a desarrollar el mensaje del poema?",
          "Muestra que casi no dice palabras de cariño, así que sus acciones tienen que expresar su amor.",
          ["Muestra que la abuela es demasiado estricta y está muy ocupada para que le importe la voz poética.", "Muestra que la abuela casi no puede hablar porque está enferma.", "Describe las mañanas de domingo en que la abuela hace tortillas para toda la familia."],
          ["Las palabras parecen quedarle chicas"],
          "La estrofa 5 dice que la abuela casi nunca dice “te quiero”. Por eso el resto del poema busca su amor en lo que hacen sus manos.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In stanza 5, what does the simile “like shoes she has outgrown” suggest?",
          "The words “I love you” feel too small for how much she cares.",
          ["The grandmother needs a new pair of shoes.", "The grandmother loves the speaker less as the speaker grows older.", "The grandmother is embarrassed by her old clothes and shoes."],
          ["like shoes she has outgrown"],
          "Outgrown shoes are too small for you. The simile says the words are too small to hold what the grandmother feels.",
        ],
        [
          "En la estrofa 5, ¿qué sugiere el símil “como zapatos que ya no le entran”?",
          "Decir “te quiero” le queda chico para todo lo que siente.",
          ["La abuela necesita un par de zapatos nuevos.", "La abuela quiere menos a la voz poética a medida que crece.", "La abuela se avergüenza de su ropa y sus zapatos viejos."],
          ["como zapatos que ya no le entran"],
          "Los zapatos que ya no te entran te quedan chicos. El símil dice que esas palabras son demasiado pequeñas para lo que siente la abuela.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "wrong-context-meaning", "contradicts-text"],
        [
          "In stanza 1, the speaker calls the hands “maps of everything they have done.” What does this metaphor mean?",
          "The marks on her hands tell the story of her work.",
          ["Her hands have lines that look like the roads on a map.", "She uses her hands to point the way when someone is lost.", "Her hands are soft and smooth from many years of rest."],
          ["a white scar from a tin can in 1979"],
          "A map shows where someone has been. The scars and burns on the grandmother's hands show the work she has done.",
        ],
        [
          "En la estrofa 1, la voz poética dice que las manos “Son mapas de todo lo que han hecho”. ¿Qué significa esta metáfora?",
          "Las marcas de sus manos cuentan la historia de su trabajo.",
          ["Sus manos tienen líneas que parecen los caminos de un mapa.", "Usa las manos para indicar el camino cuando alguien se pierde.", "Sus manos son suaves por tantos años de descanso."],
          ["una cicatriz blanca de una lata en 1979"],
          "Un mapa muestra por dónde ha pasado alguien. Las cicatrices y quemaduras de las manos de la abuela muestran el trabajo que ha hecho.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "What can you infer about the speaker's feelings in the last stanza?",
          "The speaker admires her and wants to care for others the same way.",
          ["The speaker hopes never to work as hard as the grandmother does.", "The speaker plans to study maps and become a mapmaker someday.", "The speaker believes that all hands end up looking the same in old age, no matter what."],
          ["I hope they show the same roads"],
          "The speaker hopes their own hands will show “the same roads”: early mornings, patient stitches, and food given away. That shows admiration and a wish to care for others.",
        ],
        [
          "¿Qué puedes inferir sobre los sentimientos de la voz poética en la última estrofa?",
          "Admira a su abuela y quiere cuidar a otros de la misma manera.",
          ["Espera nunca tener que trabajar tanto como su abuela.", "Piensa estudiar mapas y dedicarse a dibujarlos algún día.", "Cree que todas las manos terminan viéndose igual en la vejez, pase lo que pase."],
          ["Ojalá muestren los mismos caminos"],
          "La voz poética desea que sus manos muestren “los mismos caminos”: madrugadas, puntadas pacientes y comida regalada. Eso muestra admiración y ganas de cuidar a otros.",
        ],
      ),
    ],
  },
  {
    id: "alligator-crocodile",
    level: 1,
    genre: "informational",
    structure: {
      kind: "compare-contrast",
      en: [["Both", "But", "while", "also differ"], "The passage sets the two animals side by side: first how they are alike, then how their snouts, teeth, color, and homes differ."],
      es: [["Ambos", "Pero", "mientras que", "también se diferencian"], "El texto pone a los dos animales lado a lado: primero en qué se parecen y luego cómo se diferencian su hocico, sus dientes, su color y dónde viven."],
    },
    en: [
      {
        title: "Alligator or Crocodile?",
        paras: [
          "At first glance, alligators and crocodiles look almost identical. Both are large reptiles with armored skin, powerful tails, and eyes and nostrils on top of their heads, so they can watch and breathe while the rest of the body stays hidden underwater. Both belong to ancient groups whose relatives lived alongside the dinosaurs. But if you know where to look, telling them apart is not hard.",
          "The quickest clue is the snout. An alligator has a wide, rounded snout shaped like the letter U. A crocodile's snout is narrower and more pointed, closer to a V. The teeth offer a second clue. When an alligator closes its mouth, its upper jaw covers most of its lower teeth. When a crocodile closes its mouth, a large tooth near the front of the lower jaw still shows on each side, giving it a jagged grin.",
          "Color can help too, though less reliably. Adult alligators tend to be dark, almost black, while many crocodiles are lighter, closer to olive or tan.",
          "The two animals also differ in where they live. Alligators live mainly in fresh water, such as swamps, rivers, and lakes. Only two species exist: the American alligator of the southeastern United States and the much rarer Chinese alligator. Crocodiles are found in tropical parts of Africa, Asia, Australia, and the Americas, and many crocodiles have glands that remove extra salt from their bodies, which lets them live in salty coastal waters.",
          "There is one place on Earth where both animals live side by side in the wild: southern Florida. There, in the brackish water where rivers meet the sea, a lucky visitor might spot an American alligator and an American crocodile on the same muddy bank, and now you would know which is which.",
        ],
      },
    ],
    es: [
      {
        title: "¿Aligátor o cocodrilo?",
        paras: [
          "A primera vista, los aligátores y los cocodrilos parecen casi idénticos. Ambos son reptiles grandes con piel acorazada, colas poderosas y los ojos y las fosas nasales en lo alto de la cabeza, así que pueden mirar y respirar mientras el resto del cuerpo queda escondido bajo el agua. Ambos pertenecen a grupos muy antiguos cuyos parientes vivieron junto a los dinosaurios. Pero si sabes dónde mirar, no es difícil distinguirlos.",
          "La pista más rápida es el hocico. El aligátor tiene un hocico ancho y redondeado, con forma de U. El hocico del cocodrilo es más angosto y puntiagudo, más parecido a una V. Los dientes dan una segunda pista. Cuando el aligátor cierra la boca, la mandíbula de arriba tapa casi todos los dientes de abajo. Cuando el cocodrilo cierra la boca, todavía se ve a cada lado un diente grande cerca del frente de la mandíbula inferior, lo que le da una sonrisa dentada.",
          "El color también ayuda, aunque es menos confiable. Los aligátores adultos suelen ser oscuros, casi negros, mientras que muchos cocodrilos son más claros, de color oliva o canela.",
          "Los dos animales también se diferencian en dónde viven. Los aligátores viven sobre todo en agua dulce, como pantanos, ríos y lagos. Solo existen dos especies: el aligátor americano, del sureste de Estados Unidos, y el aligátor chino, mucho más escaso. Los cocodrilos viven en zonas tropicales de África, Asia, Australia y América, y muchos tienen glándulas que eliminan el exceso de sal de su cuerpo, lo que les permite vivir en las aguas saladas de la costa.",
          "Hay un solo lugar en la Tierra donde los dos animales viven juntos en estado salvaje: el sur de Florida. Allí, en el agua salobre donde los ríos se juntan con el mar, un visitante con suerte podría ver un aligátor americano y un cocodrilo americano en la misma orilla lodosa, y ahora sabría cuál es cuál.",
        ],
      },
    ],
    qs: [
      q(
        "structure.section",
        ["wrong-section-role", "wrong-section-role", "not-in-text"],
        [
          "What is the main purpose of paragraph 5?",
          "To end by naming the one place where both animals could be seen together.",
          ["To explain how crocodiles get rid of the extra salt in their bodies so they can live in salty water.", "To describe the differences between the two animals' snouts and teeth.", "To argue that Florida should protect crocodiles but not alligators."],
          ["There is one place on Earth where both animals live side by side in the wild: southern Florida."],
          "After the comparison, the last paragraph brings the two animals together in one real place and invites the reader to use the clues.",
        ],
        [
          "¿Cuál es el propósito principal del párrafo 5?",
          "Terminar con el único lugar donde se podría ver a los dos animales juntos.",
          ["Explicar cómo los cocodrilos eliminan el exceso de sal de su cuerpo para poder vivir en agua salada.", "Describir las diferencias entre el hocico y los dientes de los dos animales.", "Convencer de que Florida debería proteger a los cocodrilos, pero no a los aligátores."],
          ["Hay un solo lugar en la Tierra donde los dos animales viven juntos en estado salvaje: el sur de Florida."],
          "Después de la comparación, el último párrafo junta a los dos animales en un lugar real e invita al lector a usar las pistas.",
        ],
      ),
      q(
        "central.idea",
        ["too-narrow", "too-broad", "contradicts-text"],
        [
          "What is the central idea of the passage?",
          "Alligators and crocodiles look alike, but clear differences set them apart.",
          ["A crocodile has a large lower tooth that shows on each side when its mouth is closed.", "Reptiles are animals that have lived on Earth for a very long time.", "Alligators and crocodiles are so alike that even experts cannot tell them apart."],
          ["But if you know where to look, telling them apart is not hard."],
          "Every paragraph after the first gives a way to tell the animals apart: snout, teeth, color, and habitat.",
        ],
        [
          "¿Cuál es la idea central del texto?",
          "Los aligátores y los cocodrilos se parecen, pero hay diferencias claras entre ellos.",
          ["El cocodrilo tiene un diente inferior grande que se ve a cada lado cuando cierra la boca.", "Los reptiles son animales que han vivido en la Tierra durante mucho tiempo.", "Los aligátores y los cocodrilos se parecen tanto que ni los expertos pueden distinguirlos."],
          ["Pero si sabes dónde mirar, no es difícil distinguirlos."],
          "Cada párrafo después del primero da una manera de distinguir a los animales: el hocico, los dientes, el color y dónde viven.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "Why does the author say color helps “though less reliably”?",
          "Some animals do not match the usual colors, so color alone could fool you.",
          ["Alligators change color from one season to the next.", "Color is the most dependable clue of all, even more than the snout or the teeth.", "Every crocodile is tan and every alligator is black."],
          ["Adult alligators tend to be dark, almost black, while many crocodiles are lighter"],
          "The author says alligators “tend to be” dark and “many” crocodiles are lighter. Those words leave room for exceptions, so color is a weaker clue than the snout or teeth.",
        ],
        [
          "¿Por qué el texto dice que el color ayuda, “aunque es menos confiable”?",
          "Algunos animales no tienen el color usual, así que el color solo puede engañar.",
          ["Los aligátores cambian de color de una estación a otra.", "El color es la pista más segura de todas, incluso más que el hocico o los dientes.", "Todos los cocodrilos son de color canela y todos los aligátores son negros."],
          ["Los aligátores adultos suelen ser oscuros, casi negros, mientras que muchos cocodrilos son más claros"],
          "El texto dice que los aligátores “suelen ser” oscuros y que “muchos” cocodrilos son más claros. Esas palabras dejan espacio para excepciones, así que el color es una pista más débil que el hocico o los dientes.",
        ],
      ),
      q(
        "words.connotation",
        ["too-literal", "wrong-context-meaning", "not-in-text"],
        [
          "The author says a crocodile's visible tooth gives it a “jagged grin.” What does the word “grin” add?",
          "It makes the closed mouth look like a sly smile, so readers can picture it.",
          ["It shows that crocodiles are friendly animals that enjoy meeting people up close.", "It means that the crocodile's teeth are broken.", "It shows that the author is afraid of crocodiles."],
          ["giving it a jagged grin"],
          "A grin is a wide smile. Using it for a row of showing teeth gives readers a vivid, slightly sly picture of the crocodile's face.",
        ],
        [
          "El texto dice que el diente visible le da al cocodrilo una “sonrisa dentada”. ¿Qué agrega la palabra “sonrisa”?",
          "Hace que la boca cerrada parezca una sonrisa pícara, así el lector puede imaginarla.",
          ["Muestra que los cocodrilos son animales amistosos a los que les gusta conocer gente.", "Quiere decir que los dientes del cocodrilo están rotos.", "Muestra que al autor le dan miedo los cocodrilos."],
          ["lo que le da una sonrisa dentada"],
          "Una sonrisa enseña los dientes. Usar esa palabra para los dientes que se asoman le da al lector una imagen viva, un poco pícara, de la cara del cocodrilo.",
        ],
      ),
    ],
  },
  {
    id: "braille-dots",
    level: 1,
    genre: "informational",
    structure: {
      kind: "chronological",
      en: [["in 1809", "In 1821", "By 1824", "two years later"], "The passage follows Louis Braille's life and his invention in time order, from his birth in 1809 to the school's adoption of braille in 1854."],
      es: [["en 1809", "En 1821", "Para 1824", "dos años después"], "El texto sigue la vida de Louis Braille y su invento en orden de tiempo, desde su nacimiento en 1809 hasta que la escuela adoptó el braille en 1854."],
    },
    en: [
      {
        title: "Six Dots That Changed Reading",
        paras: [
          "Louis Braille was born in 1809 in Coupvray, a small town east of Paris, France. When he was three years old, he was hurt in an accident in his father's leather workshop, and an infection that followed left him completely blind by the age of five.",
          "Louis was a bright student, and in 1819, at age ten, he won a place at the Royal Institute for Blind Youth in Paris, one of the first schools of its kind. The school owned a few books for blind readers, but they were printed with large raised letters. The books were huge and heavy, and reading them was painfully slow, because fingers had to trace the shape of each letter.",
          "In 1821, a former army captain named Charles Barbier visited the school. He had invented a system of raised dots that soldiers could read in the dark, which he called “night writing.” Barbier's code used up to twelve dots for each sound, which made it hard to feel under one fingertip, but Louis saw something important in it: dots were much easier to feel than the shapes of letters.",
          "Louis began experimenting. By 1824, when he was only fifteen, he had created a simpler system. Each letter fit in a small cell of just six dots, arranged in two columns of three, so a single fingertip could feel a whole letter at once. In 1829 he published his method, which also included a way to write music.",
          "For years, the system spread mostly from student to student. Louis Braille died in 1852, and two years later, in 1854, the school officially adopted his system. Today braille is used around the world, in many languages, on everything from library books to elevator buttons.",
        ],
      },
    ],
    es: [
      {
        title: "Seis puntos que cambiaron la lectura",
        paras: [
          "Louis Braille nació en 1809 en Coupvray, un pueblo pequeño al este de París, Francia. Cuando tenía tres años, se lastimó en un accidente en el taller de cuero de su padre, y una infección posterior lo dejó completamente ciego a los cinco años.",
          "Louis era un estudiante brillante, y en 1819, a los diez años, obtuvo un lugar en el Real Instituto para Jóvenes Ciegos de París, una de las primeras escuelas de su tipo. La escuela tenía algunos libros para lectores ciegos, pero estaban impresos con letras grandes en relieve. Los libros eran enormes y pesados, y leerlos era dolorosamente lento, porque los dedos tenían que recorrer la forma de cada letra.",
          "En 1821, un excapitán del ejército llamado Charles Barbier visitó la escuela. Había inventado un sistema de puntos en relieve que los soldados podían leer en la oscuridad, al que llamó “escritura nocturna”. El código de Barbier usaba hasta doce puntos para cada sonido, lo que lo hacía difícil de sentir con la yema de un dedo, pero Louis vio algo importante: los puntos eran mucho más fáciles de sentir que la forma de las letras.",
          "Louis empezó a experimentar. Para 1824, cuando tenía apenas quince años, había creado un sistema más sencillo. Cada letra cabía en una celda pequeña de solo seis puntos, ordenados en dos columnas de tres, así que la yema de un dedo podía sentir una letra completa de una vez. En 1829 publicó su método, que también incluía una manera de escribir música.",
          "Durante años, el sistema se difundió sobre todo de estudiante a estudiante. Louis Braille murió en 1852, y dos años después, en 1854, la escuela adoptó oficialmente su sistema. Hoy el braille se usa en todo el mundo, en muchos idiomas, en todo tipo de cosas, desde libros de biblioteca hasta botones de elevador.",
        ],
      },
    ],
    qs: [
      q(
        "structure.section",
        ["wrong-section-role", "contradicts-text", "not-in-text"],
        [
          "How does paragraph 3 connect to paragraph 4?",
          "Paragraph 3 shows the idea Louis learned from, and paragraph 4 shows how he improved it.",
          ["Paragraph 3 describes Louis's early childhood, and paragraph 4 describes the end of his life.", "Paragraph 4 explains that Louis gave up on dots and went back to raised letters.", "Paragraph 3 explains why Louis was chosen for the school in Paris."],
          ["dots were much easier to feel than the shapes of letters", "By 1824, when he was only fifteen, he had created a simpler system."],
          "Paragraph 3 introduces Barbier's twelve-dot code and what Louis noticed about it. Paragraph 4 shows what he built from that idea: a six-dot cell one fingertip could feel at once.",
        ],
        [
          "¿Cómo se conecta el párrafo 3 con el párrafo 4?",
          "El párrafo 3 muestra la idea de la que Louis aprendió, y el párrafo 4 muestra cómo la mejoró.",
          ["El párrafo 3 describe la primera infancia de Louis, y el párrafo 4 describe el final de su vida.", "El párrafo 4 explica que Louis abandonó los puntos y volvió a las letras en relieve.", "El párrafo 3 explica por qué eligieron a Louis para la escuela de París."],
          ["los puntos eran mucho más fáciles de sentir que la forma de las letras", "Para 1824, cuando tenía apenas quince años, había creado un sistema más sencillo."],
          "El párrafo 3 presenta el código de doce puntos de Barbier y lo que Louis notó en él. El párrafo 4 muestra lo que construyó con esa idea: una celda de seis puntos que una sola yema podía sentir de una vez.",
        ],
      ),
      q(
        "central.idea",
        ["too-narrow", "too-broad", "not-in-text"],
        [
          "What is the central idea of the passage?",
          "Louis Braille, blind from childhood, turned an idea about raised dots into a reading system now used worldwide.",
          ["Charles Barbier invented a code of raised dots so that soldiers could read messages in the dark without using a light.", "Many inventions change the way people live and work.", "Louis Braille became famous in Paris for writing music for blind students."],
          ["Today braille is used around the world"],
          "The passage traces how Louis went from slow raised-letter books to his six-dot system, and it ends with braille used around the world.",
        ],
        [
          "¿Cuál es la idea central del texto?",
          "Louis Braille, ciego desde niño, convirtió una idea de puntos en relieve en un sistema de lectura usado en todo el mundo.",
          ["Charles Barbier inventó un código de puntos en relieve para que los soldados pudieran leer mensajes a oscuras, sin encender ninguna luz.", "Muchos inventos cambian la manera en que la gente vive y trabaja.", "Louis Braille se hizo famoso en París por componer música para estudiantes ciegos."],
          ["Hoy el braille se usa en todo el mundo"],
          "El texto cuenta cómo Louis pasó de los libros lentos de letras en relieve a su sistema de seis puntos, y termina con el braille usado en todo el mundo.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "What can you infer from the fact that braille “spread mostly from student to student” before 1854?",
          "Students found the system useful before the school officially accepted it.",
          ["The teachers taught braille in every class from the very first day.", "Braille was a secret code that only former soldiers in the army knew how to read.", "Every blind person in France had learned braille by 1830."],
          ["For years, the system spread mostly from student to student."],
          "The school did not adopt braille until 1854, yet students kept passing it to each other. They would only do that if they found it useful.",
        ],
        [
          "¿Qué puedes inferir del hecho de que el braille “se difundió sobre todo de estudiante a estudiante” antes de 1854?",
          "A los estudiantes les sirvió el sistema antes de que la escuela lo aceptara oficialmente.",
          ["Los maestros enseñaron braille en todas las clases desde el primer día.", "El braille era un código secreto que solo sabían leer los antiguos soldados del ejército francés.", "Todas las personas ciegas de Francia habían aprendido braille para 1830."],
          ["Durante años, el sistema se difundió sobre todo de estudiante a estudiante."],
          "La escuela no adoptó el braille hasta 1854, pero los estudiantes se lo seguían pasando entre ellos. Solo lo harían si les resultaba útil.",
        ],
      ),
      q(
        "words.connotation",
        ["too-literal", "not-in-text", "opposite-tone"],
        [
          "In paragraph 2, the author says reading the old books was “painfully slow.” Why does the author choose the word “painfully”?",
          "To stress how frustrating and tiring the old way of reading was.",
          ["To show that touching the raised letters hurt the students' fingers.", "To show that the students did not want to learn to read.", "To suggest that the old books were a fun and pleasant challenge."],
          ["reading them was painfully slow"],
          "“Painfully” here means “so much that it was hard to bear.” It stresses how slow and frustrating the old books were, which makes Louis's invention matter more.",
        ],
        [
          "En el párrafo 2, el texto dice que leer los libros viejos era “dolorosamente lento”. ¿Por qué el autor elige la palabra “dolorosamente”?",
          "Para resaltar lo frustrante y cansado que era leer de la manera antigua.",
          ["Para mostrar que tocar las letras en relieve lastimaba los dedos de los estudiantes.", "Para mostrar que los estudiantes no querían aprender a leer.", "Para sugerir que los libros viejos eran un reto divertido y agradable."],
          ["leerlos era dolorosamente lento"],
          "Aquí “dolorosamente” quiere decir “tanto que costaba soportarlo”. Resalta lo lentos y frustrantes que eran los libros viejos, y eso hace más importante el invento de Louis.",
        ],
      ),
    ],
  },
  {
    id: "dust-bowl",
    level: 1,
    genre: "informational",
    structure: {
      kind: "cause-effect",
      en: [["because", "The first cause", "As a result", "most visible effect"], "The passage explains the causes of the Dust Bowl, plowing and drought, and then its effects, from the storms to the families who left."],
      es: [["porque", "La primera causa", "Como resultado", "El efecto más visible"], "El texto explica las causas del desastre, el arado y la sequía, y luego sus efectos, desde las tormentas hasta las familias que se fueron."],
    },
    en: [
      {
        title: "What Caused the Dust Bowl?",
        paras: [
          "During the 1930s, huge dust storms swept across the southern Great Plains, a region that includes parts of Oklahoma, Texas, Kansas, Colorado, and New Mexico. The disaster became known as the Dust Bowl. It did not have a single cause. It happened because human choices and natural forces combined at the worst possible time.",
          "The first cause was the plow. The Plains had once been covered in tough prairie grasses whose deep, tangled roots held the soil in place, even in dry years. But when wheat prices rose and new tractors made plowing fast, farmers turned millions of acres of grassland into wheat fields. While the rain lasted, harvests were huge, so even more grass was plowed under.",
          "The second cause was the weather. In the early 1930s, a long drought dried the bare fields. Without roots to anchor it, the loose topsoil had nothing to hold it down. As a result, when the strong winds of the Plains blew, they lifted the soil into enormous clouds of dust.",
          "The most visible effect was the storms themselves. These “black blizzards” could turn day into night. Dust piled against fences like snowdrifts, buried farm equipment, and crept into houses through cracks around windows and doors. Families hung wet sheets over doorways and still found grit in their food.",
          "The effects reached far beyond the storms. Crops failed year after year, and many families lost their farms. Hundreds of thousands of people left the region, many heading west to California in search of work. The disaster also changed how Americans thought about land, because it showed that the way people farm can affect the soil for generations.",
        ],
      },
    ],
    es: [
      {
        title: "¿Qué causó el Cuenco de Polvo?",
        paras: [
          "Durante la década de 1930, enormes tormentas de polvo azotaron el sur de las Grandes Llanuras de Estados Unidos, una región que incluye partes de Oklahoma, Texas, Kansas, Colorado y Nuevo México. El desastre se conoció como el Dust Bowl, o “Cuenco de Polvo”. No tuvo una sola causa. Ocurrió porque las decisiones humanas y las fuerzas de la naturaleza se juntaron en el peor momento posible.",
          "La primera causa fue el arado. Las Llanuras habían estado cubiertas de pastos resistentes, cuyas raíces profundas y enredadas sujetaban el suelo, incluso en los años secos. Pero cuando subió el precio del trigo y los tractores nuevos hicieron que arar fuera rápido, los agricultores convirtieron millones de acres de pastizal en campos de trigo. Mientras duraron las lluvias, las cosechas fueron enormes, así que se aró todavía más pasto.",
          "La segunda causa fue el clima. A principios de la década de 1930, una larga sequía secó los campos desnudos. Sin raíces que la sujetaran, la capa superior del suelo quedó suelta, sin nada que la retuviera. Como resultado, cuando soplaban los fuertes vientos de las Llanuras, levantaban la tierra en nubes gigantescas de polvo.",
          "El efecto más visible fueron las tormentas mismas. Estas “ventiscas negras” podían convertir el día en noche. El polvo se amontonaba contra las cercas como montones de nieve, enterraba la maquinaria agrícola y se metía en las casas por las rendijas de puertas y ventanas. Las familias colgaban sábanas mojadas en las puertas y aun así encontraban tierra en la comida.",
          "Los efectos llegaron mucho más allá de las tormentas. Las cosechas se perdieron año tras año, y muchas familias perdieron sus granjas. Cientos de miles de personas dejaron la región, y muchas se fueron al oeste, a California, en busca de trabajo. El desastre también cambió la manera en que los estadounidenses pensaban sobre la tierra, porque mostró que la forma de cultivar puede afectar el suelo por generaciones.",
        ],
      },
    ],
    qs: [
      q(
        "structure.section",
        ["wrong-section-role", "not-in-text", "wrong-section-role"],
        [
          "What is the role of paragraph 4 in the passage?",
          "It describes the most visible result of the causes explained before it.",
          ["It explains the second cause of the Dust Bowl, the long drought of the early 1930s.", "It tells how farmers finally solved the problem of blowing dust.", "It introduces the region where the Dust Bowl took place."],
          ["The most visible effect was the storms themselves."],
          "Paragraphs 2 and 3 give the two causes. Paragraph 4 turns to the effects, starting with the storms people could see.",
        ],
        [
          "¿Qué función tiene el párrafo 4 en el texto?",
          "Describe el resultado más visible de las causas que se explicaron antes.",
          ["Explica la segunda causa del desastre: la larga sequía de principios de la década de 1930.", "Cuenta cómo los agricultores por fin resolvieron el problema del polvo.", "Presenta la región donde ocurrió el desastre."],
          ["El efecto más visible fueron las tormentas mismas."],
          "Los párrafos 2 y 3 dan las dos causas. El párrafo 4 pasa a los efectos, empezando por las tormentas que la gente podía ver.",
        ],
      ),
      q(
        "central.idea",
        ["too-narrow", "too-broad", "contradicts-text"],
        [
          "What is the central idea of the passage?",
          "Plowing removed the grass that held the soil, and then drought and wind blew the soil away.",
          ["Families hung wet sheets over their doorways and windows to try to keep the blowing dust out of their homes.", "Weather can change the way people live.", "The Dust Bowl was caused only by a lack of rain."],
          ["It happened because human choices and natural forces combined at the worst possible time."],
          "The passage says the Dust Bowl had more than one cause: farmers plowed up the grass, and then drought and wind did the rest.",
        ],
        [
          "¿Cuál es la idea central del texto?",
          "El arado quitó el pasto que sujetaba el suelo, y luego la sequía y el viento se llevaron la tierra.",
          ["Las familias colgaban sábanas mojadas en puertas y ventanas para intentar que el polvo no entrara a sus casas.", "El clima puede cambiar la forma en que vive la gente.", "El desastre se debió solo a la falta de lluvia."],
          ["Ocurrió porque las decisiones humanas y las fuerzas de la naturaleza se juntaron en el peor momento posible."],
          "El texto dice que el desastre tuvo más de una causa: los agricultores araron el pasto, y luego la sequía y el viento hicieron el resto.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "Based on paragraph 2, why did farmers keep plowing up more grassland?",
          "Big harvests in rainy years made plowing seem safe and profitable.",
          ["They knew a long drought was coming and wanted to harvest as much wheat as they could before it arrived.", "The government had ordered them to protect the prairie grass.", "Farmers never think about what might happen in the future."],
          ["While the rain lasted, harvests were huge, so even more grass was plowed under."],
          "When it rained, the wheat grew well and prices were high. Those good years made more plowing look like a smart choice.",
        ],
        [
          "Según el párrafo 2, ¿por qué los agricultores siguieron arando más pastizal?",
          "Las grandes cosechas de los años lluviosos hacían que arar pareciera seguro y rentable.",
          ["Sabían que venía una larga sequía y querían cosechar todo el trigo posible antes de que llegara.", "El gobierno les había ordenado proteger el pasto de la pradera.", "Los agricultores nunca piensan en lo que podría pasar en el futuro."],
          ["Mientras duraron las lluvias, las cosechas fueron enormes, así que se aró todavía más pasto."],
          "Cuando llovía, el trigo crecía bien y los precios estaban altos. Esos buenos años hacían que arar más pareciera una buena decisión.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "not-in-text", "contradicts-text"],
        [
          "Why does the author call the dust storms “black blizzards”?",
          "Like snowstorms, they filled the air and piled up drifts, but with dark dust.",
          ["The storms brought dark-colored snow to the Plains.", "The storms happened only in the coldest months of winter.", "The storms were milder and much shorter than the regular snowstorms of a Plains winter."],
          ["Dust piled against fences like snowdrifts"],
          "A blizzard is a storm so thick you cannot see. The dust storms were like that, and the dust even piled up like snow, but it was dark soil.",
        ],
        [
          "¿Por qué el autor llama a las tormentas de polvo “ventiscas negras”?",
          "Como las tormentas de nieve, llenaban el aire y formaban montones, pero de polvo oscuro.",
          ["Las tormentas traían nieve de color oscuro a las Llanuras.", "Las tormentas solo ocurrían en los meses más fríos del invierno.", "Las tormentas eran más suaves y mucho más cortas que las tormentas de nieve del invierno en las Llanuras."],
          ["El polvo se amontonaba contra las cercas como montones de nieve"],
          "Una ventisca es una tormenta tan espesa que no se ve nada. Las tormentas de polvo eran así, y el polvo hasta se amontonaba como nieve, pero era tierra oscura.",
        ],
      ),
    ],
  },
];
