import { type Passage, q } from "./types";

// Level 1 (grades 6–7) stories.
export const L1_STORIES: Passage[] = [
  {
    id: "night-market",
    level: 1,
    genre: "story",
    en: [
      {
        title: "The Night Market",
        paras: [
          "Every Saturday in summer, the parking lot behind the hardware store turned into a night market. Strings of lights went up between the poles, and by seven o'clock the air smelled like grilled corn, frying dough, and rain on hot pavement. Mei's grandmother had a stall near the middle, where she sold pork dumplings from a steamer as tall as Mei's waist.",
          "Mei had spent the first two Saturdays of summer hiding behind the steamer. Kids from her school walked past in groups, and she was sure they were staring at the hand-painted sign with its crooked letters. She kept her hood up and counted change without looking at anyone's face.",
          "On the third Saturday, a boy from her math class, Darius, stopped at the stall. Mei froze. He read the sign out loud, ordered six dumplings, and ate the first one standing right there. Then he closed his eyes. “These are better than my uncle's,” he said, “and my uncle thinks he's a chef.”",
          "Nai Nai laughed and slid two extra dumplings into his box. Darius came back twenty minutes later with his cousins.",
          "That night, Mei pushed her hood back. She folded the boxes faster than her grandmother could fill them, and when someone asked what was in the dipping sauce, she answered before Nai Nai could. “Black vinegar, ginger, and a secret,” she said. Her grandmother raised an eyebrow, then nodded, as if Mei had passed a test she hadn't known she was taking.",
          "When the lights came down at eleven, Mei carried the empty steamer to the car. It was heavier than it looked. She didn't mind.",
        ],
      },
    ],
    es: [
      {
        title: "El mercado nocturno",
        paras: [
          "Cada sábado de verano, el estacionamiento detrás de la ferretería se convertía en un mercado nocturno. Colgaban hileras de luces entre los postes y, a las siete, el aire olía a elote asado, a masa frita y a lluvia sobre el pavimento caliente. La abuela de Mei tenía un puesto cerca del centro, donde vendía empanadillas chinas de cerdo, cocidas en una vaporera tan alta como la cintura de Mei.",
          "Mei había pasado los dos primeros sábados del verano escondida detrás de la vaporera. Chicos de su escuela pasaban en grupos, y ella estaba segura de que se fijaban en el letrero pintado a mano, con sus letras chuecas. Se dejaba la capucha puesta y contaba el cambio sin mirarle la cara a nadie.",
          "El tercer sábado, un chico de su clase de matemáticas, Darius, se detuvo en el puesto. Mei se quedó helada. Él leyó el letrero en voz alta, pidió seis empanadillas y se comió la primera ahí mismo, de pie. Luego cerró los ojos. —Están mejores que las de mi tío —dijo—, y mi tío se cree chef.",
          "Nai Nai se rio y le metió dos empanadillas de más en la caja. Darius volvió veinte minutos después con sus primos.",
          "Esa noche, Mei se bajó la capucha. Armaba las cajas más rápido de lo que su abuela alcanzaba a llenarlas, y cuando alguien preguntó qué llevaba la salsa, contestó antes que Nai Nai. —Vinagre negro, jengibre y un secreto —dijo. Su abuela levantó una ceja y luego asintió, como si Mei hubiera pasado una prueba que no sabía que estaba presentando.",
          "Cuando apagaron las luces a las once, Mei cargó la vaporera vacía hasta el carro. Pesaba más de lo que parecía. No le importó.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["contradicts-text", "too-narrow", "not-in-text"],
        [
          "Which statement best expresses a theme of the story?",
          "Embarrassment about your family can turn into pride once you see the value of what they do.",
          ["Hiding what makes your family different is the safest way to fit in with the kids at your school.", "Good cooking can win over a new customer.", "Kids can learn more at a market stall than in a math class."],
          ["That night, Mei pushed her hood back."],
          "Mei starts out hiding her face and ends up working proudly beside her grandmother. That change carries the story's message.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "La vergüenza por la propia familia puede volverse orgullo cuando uno ve el valor de lo que hace.",
          ["Esconder lo que hace diferente a tu familia es la forma más segura de encajar con los chicos de tu escuela.", "La buena comida puede conquistar a un cliente nuevo.", "Se puede aprender más en un puesto del mercado que en una clase de matemáticas."],
          ["Esa noche, Mei se bajó la capucha."],
          "Al principio Mei esconde la cara y al final trabaja con orgullo junto a su abuela. Ese cambio lleva el mensaje del cuento.",
        ],
      ),
      q(
        "theme.develop",
        ["misses-the-change", "wrong-character", "off-point-evidence"],
        [
          "How does the author show that Mei's feelings have changed by the end?",
          "She pushes back her hood and answers a customer herself.",
          ["She keeps her hood up and counts change without looking at anyone.", "Darius says the dumplings are better than his uncle's cooking.", "The market lights come down at eleven o'clock."],
          ["she answered before Nai Nai could"],
          "At first Mei hid and would not look at customers. Now she shows her face and speaks up for the stall, which shows pride instead of embarrassment.",
        ],
        [
          "¿Cómo muestra el autor que los sentimientos de Mei cambiaron al final?",
          "Se baja la capucha y le contesta ella misma a un cliente.",
          ["Se deja la capucha puesta y cuenta el cambio sin mirar a nadie.", "Darius dice que las empanadillas están mejores que las de su tío.", "Las luces del mercado se apagan a las once."],
          ["contestó antes que Nai Nai"],
          "Al principio Mei se escondía y no miraba a los clientes. Ahora da la cara y habla por el puesto, lo que muestra orgullo en lugar de vergüenza.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "Why does Nai Nai raise an eyebrow and then nod at the end of paragraph 5?",
          "She is surprised and pleased that Mei is speaking up for the stall.",
          ["She is annoyed that Mei almost gave away the secret ingredient to a stranger.", "She wants Mei to fold the boxes more slowly.", "She tests every person who helps at the stall."],
          ["as if Mei had passed a test she hadn't known she was taking"],
          "A raised eyebrow shows surprise, and the nod and the test Mei “passed” show approval.",
        ],
        [
          "¿Por qué Nai Nai levanta una ceja y luego asiente al final del párrafo 5?",
          "Está sorprendida y contenta de que Mei hable por el puesto.",
          ["Está molesta porque Mei casi le revela el ingrediente secreto a un desconocido.", "Quiere que Mei arme las cajas más despacio.", "Pone a prueba a toda persona que ayuda en el puesto."],
          ["como si Mei hubiera pasado una prueba que no sabía que estaba presentando"],
          "Levantar una ceja muestra sorpresa, y el gesto de asentir y la prueba que Mei “pasó” muestran aprobación.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "not-in-text", "contradicts-text"],
        [
          "In paragraph 3, the narrator says “Mei froze.” What does “froze” mean here?",
          "She was suddenly too nervous to move.",
          ["She felt very cold in the night air.", "She was angry that Darius read the sign out loud.", "She hurried to serve him before anyone else."],
          ["Mei froze."],
          "“Froze” does not mean cold here. Mei stopped moving because she was nervous that a classmate had seen her.",
        ],
        [
          "En el párrafo 3, el narrador dice: “Mei se quedó helada”. ¿Qué significa “se quedó helada” aquí?",
          "De pronto estaba tan nerviosa que no podía moverse.",
          ["Tenía mucho frío por el aire de la noche.", "Estaba enojada porque Darius leyó en voz alta el letrero.", "Se apuró a atenderlo antes que a cualquier otro cliente."],
          ["Mei se quedó helada."],
          "Aquí “se quedó helada” no tiene que ver con el frío. Mei se paralizó de nervios porque un compañero la había visto.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Mei hides at her grandmother's dumpling stall until a classmate loves the food and comes back with his cousins. Then she works openly beside her grandmother.",
          ["Mei's grandmother makes the best dumplings at the market, and Mei was silly to feel embarrassed about them.", "Mei goes to a night market that smells like grilled corn and frying dough, sees a hand-painted sign with crooked letters, and carries an empty steamer to the car at eleven.", "Mei quits working at the stall after a classmate laughs at the crooked letters on the sign."],
          ["Darius came back twenty minutes later with his cousins."],
          "A good summary tells the main events and the change in Mei, and it leaves out the reader's own opinions.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Mei se esconde en el puesto de su abuela hasta que a un compañero le encanta la comida y vuelve con sus primos. Después trabaja sin esconderse junto a su abuela.",
          ["La abuela de Mei hace las mejores empanadillas del mercado, y fue una tontería que Mei sintiera vergüenza.", "Mei va a un mercado nocturno que huele a elote asado y a masa frita, ve un letrero pintado a mano con letras chuecas y a las once lleva una vaporera vacía al carro.", "Mei deja de trabajar en el puesto después de que un compañero se ríe de las letras chuecas del letrero."],
          ["Darius volvió veinte minutos después con sus primos."],
          "Un buen resumen cuenta los hechos principales y el cambio de Mei, sin las opiniones de quien lee.",
        ],
      ),
    ],
  },
  {
    id: "second-chair",
    level: 1,
    genre: "story",
    en: [
      {
        title: "Second Chair",
        paras: [
          "For a whole year, Mateo had sat in the first chair of the trumpet section, the seat closest to the conductor and the one that played the solos. Then, in January, a new student named Amara joined the band. At the spring auditions she played the hardest passage without a single cracked note, and Ms. Lindqvist moved her to first chair. Mateo moved one seat to the right.",
          "It was only one seat, but it felt like a mile. For two weeks he barely spoke to Amara. When she asked which page they were starting on, he pointed instead of answering. At home he practiced the solo from the spring concert anyway, over and over, as if someone might change their mind.",
          "On the night of the concert, the band warmed up in the noisy hallway behind the stage. Mateo noticed Amara pressing the third valve of her trumpet again and again. It was sticking. She had no valve oil, and her face had gone pale.",
          "Mateo's own bottle of oil was in his pocket. For a moment he just stood there, feeling the cold plastic against his fingers. If her trumpet failed, the solo would probably come back to him. He thought about that for exactly as long as it took to cross the hallway.",
          "“Here,” he said, holding out the bottle. “Two drops. Then work the valve up and down.”",
          "Amara's solo was clean and bright, and the audience clapped before the song was even over. Mateo played his part underneath it, steady and quiet, and he was surprised to find that the clapping felt partly like his.",
          "Afterward, Amara tapped her trumpet bell gently against his. “Next audition,” she said, “you'd better be ready.”",
          "“I will,” Mateo said, and he meant it in a friendly way.",
        ],
      },
    ],
    es: [
      {
        title: "Segunda silla",
        paras: [
          "Durante un año entero, Mateo se había sentado en la primera silla de la sección de trompetas, el asiento más cerca de la directora y el que tocaba los solos. Luego, en enero, una estudiante nueva llamada Amara entró a la banda. En las audiciones de primavera tocó el pasaje más difícil sin un solo gallo, y la maestra Lindqvist la pasó a la primera silla. Mateo se movió un asiento a la derecha.",
          "Era solo un asiento, pero se sentía como un kilómetro. Durante dos semanas casi no le habló a Amara. Cuando ella preguntó en qué página empezaban, él señaló en lugar de contestar. En casa practicaba de todos modos el solo del concierto de primavera, una y otra vez, como si alguien pudiera cambiar de opinión.",
          "La noche del concierto, la banda calentaba en el pasillo ruidoso detrás del escenario. Mateo notó que Amara apretaba el tercer pistón de su trompeta una y otra vez. Se estaba trabando. Ella no tenía aceite para pistones, y se había puesto pálida.",
          "El frasco de aceite de Mateo estaba en su bolsillo. Por un momento se quedó quieto, sintiendo el plástico frío entre los dedos. Si la trompeta de Amara fallaba, lo más probable era que el solo volviera a él. Lo pensó exactamente lo que tardó en cruzar el pasillo.",
          "—Toma —dijo, ofreciéndole el frasco—. Dos gotas. Luego mueve el pistón de arriba abajo.",
          "El solo de Amara sonó limpio y brillante, y el público aplaudió antes de que terminara la canción. Mateo tocó su parte por debajo, firme y suave, y se sorprendió al sentir que los aplausos eran, en parte, también suyos.",
          "Después, Amara chocó suavemente la campana de su trompeta contra la de él. —En la próxima audición —le dijo—, más te vale estar listo.",
          "—Lo estaré —dijo Mateo, y lo dijo sin rencor.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["contradicts-text", "plot-not-theme", "too-narrow"],
        [
          "Which statement best expresses a theme of the story?",
          "Another person's success does not have to be your loss.",
          ["Losing your place to someone new means you were never good enough.", "Mateo loses first chair to Amara but lends her his valve oil before the concert.", "A newcomer can earn respect by playing well."],
          ["the clapping felt partly like his"],
          "Mateo helps the person who took his seat, and her success ends up feeling partly like his own. Losing the seat did not mean losing everything.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "El éxito de otra persona no tiene por qué ser una pérdida para ti.",
          ["Perder tu lugar ante alguien nuevo significa que nunca fuiste lo bastante bueno.", "Mateo pierde la primera silla ante Amara, pero le presta su aceite antes del concierto.", "Quien llega nuevo puede ganarse el respeto si toca bien."],
          ["los aplausos eran, en parte, también suyos"],
          "Mateo ayuda a quien le quitó el asiento, y el éxito de ella termina sintiéndose en parte como suyo. Perder el asiento no significó perderlo todo.",
        ],
      ),
      q(
        "theme.develop",
        ["misses-the-change", "off-point-evidence", "wrong-character"],
        [
          "Which moment is the turning point in how Mateo treats Amara?",
          "He crosses the hallway and offers her his valve oil.",
          ["He points to the page number instead of answering her.", "The audience claps before the song is over.", "Amara tells him he had better be ready for the next audition."],
          ["He thought about that for exactly as long as it took to cross the hallway."],
          "Until then, Mateo avoids Amara. When he chooses to help her even though her failure could help him, the way he treats her changes.",
        ],
        [
          "¿Qué momento marca el cambio en cómo trata Mateo a Amara?",
          "Cruza el pasillo y le ofrece su aceite para pistones.",
          ["Le señala el número de página en lugar de contestarle.", "El público aplaude antes de que termine la canción.", "Amara le dice que más le vale estar listo para la próxima audición."],
          ["Lo pensó exactamente lo que tardó en cruzar el pasillo."],
          "Hasta ese momento, Mateo evita a Amara. Cuando decide ayudarla aunque el fracaso de ella podría beneficiarlo, cambia su manera de tratarla.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In paragraph 2, what does the narrator mean by “It was only one seat, but it felt like a mile”?",
          "The small move felt like a huge loss to Mateo.",
          ["Mateo's new seat was far away from the rest of the band.", "Mateo was glad to have more room to play.", "The band room was much bigger than Mateo expected."],
          ["It was only one seat, but it felt like a mile."],
          "Moving one seat is a tiny distance, but comparing it to a mile shows how big the loss felt to him.",
        ],
        [
          "En el párrafo 2, ¿qué quiere decir el narrador con “Era solo un asiento, pero se sentía como un kilómetro”?",
          "El pequeño cambio se sintió como una gran pérdida para Mateo.",
          ["El nuevo asiento de Mateo quedaba muy lejos del resto de la banda.", "Mateo estaba contento de tener más espacio para tocar.", "El salón de la banda era mucho más grande de lo que Mateo esperaba."],
          ["Era solo un asiento, pero se sentía como un kilómetro."],
          "Moverse un asiento es una distancia mínima, pero compararlo con un kilómetro muestra lo grande que se sintió la pérdida.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "What does the last line suggest about how Mateo now sees Amara?",
          "He sees her as a friendly rival, not an enemy.",
          ["He is still angry that she took his seat.", "He plans to quit the band before the next audition.", "He has decided that competition always ruins friendships."],
          ["he meant it in a friendly way"],
          "Mateo still wants to compete for first chair, but he says so “in a friendly way.” He no longer treats Amara as an enemy.",
        ],
        [
          "¿Qué sugiere la última línea sobre cómo ve Mateo ahora a Amara?",
          "La ve como una rival amistosa, no como enemiga.",
          ["Sigue enojado porque ella le quitó el asiento.", "Piensa dejar la banda antes de la próxima audición.", "Decidió que competir siempre arruina las amistades."],
          ["lo dijo sin rencor"],
          "Mateo todavía quiere competir por la primera silla, pero lo dice “sin rencor”. Ya no trata a Amara como enemiga.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "After Amara wins first chair, Mateo avoids her. On concert night he gives her the valve oil she needs, and her solo succeeds with his support.",
          ["Amara is simply a better trumpet player than Mateo, so she deserves the solo more than he does.", "The band warms up in a noisy hallway behind the stage, a trumpet valve sticks, Mateo plays his part steady and quiet, and the audience claps before a song is over.", "Mateo wins back first chair by playing the solo himself when Amara's trumpet breaks on stage."],
          ["“Here,” he said, holding out the bottle."],
          "The summary has to include the lost seat, Mateo's choice to help, and the result, with no opinions added.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Después de que Amara gana la primera silla, Mateo la evita. La noche del concierto le da el aceite que necesita, y el solo de ella sale bien con su apoyo.",
          ["Amara simplemente toca la trompeta mejor que Mateo, así que merece el solo más que él.", "La banda calienta en un pasillo ruidoso detrás del escenario, un pistón se traba, Mateo toca su parte firme y suave, y el público aplaude antes de que termine una canción.", "Mateo recupera la primera silla al tocar él mismo el solo cuando la trompeta de Amara falla en el escenario."],
          ["—Toma —dijo, ofreciéndole el frasco—."],
          "El resumen tiene que incluir el asiento perdido, la decisión de Mateo de ayudar y el resultado, sin agregar opiniones.",
        ],
      ),
    ],
  },
  {
    id: "fourth-street",
    level: 1,
    genre: "story",
    en: [
      {
        title: "The Garden on Fourth Street",
        paras: [
          "The lot on Fourth Street had been empty for as long as Rosa could remember. It was a square of broken glass, tall weeds, and one shopping cart lying on its side like a tired animal. People walked past it quickly, the way you walk past a dog that might bark.",
          "Then, one Saturday in April, Mr. Haddad from the third floor of Rosa's building carried a rake and a stack of trash bags across the street. He was seventy-three and walked with a cane, so he worked slowly. He filled one bag, rested on an upturned bucket, and filled another.",
          "Rosa watched from her window for an hour. Finally she went down. “Why are you doing this?” she asked. “The city owns it. They'll never let you keep it.”",
          "Mr. Haddad shrugged. “Maybe not. But today it will have less glass in it.” He handed her a pair of gloves that were much too big.",
          "The next Saturday, Rosa's little brother came too. The Saturday after that, Mrs. Obi from the laundromat brought tomato seedlings in coffee cans, and two teenagers dragged the shopping cart to the curb. By June, someone had painted a sign that said FOURTH STREET GARDEN in uneven green letters, and the city had agreed to let the neighbors use the land for a dollar a year.",
          "In August, Rosa picked the first ripe tomato and carried it up two flights of stairs to Mr. Haddad's apartment. He held it up to the light as if it were a jewel.",
          "“You see?” he said. “Less glass.”",
        ],
      },
    ],
    es: [
      {
        title: "El huerto de la calle Cuarta",
        paras: [
          "El terreno de la calle Cuarta había estado vacío desde que Rosa tenía memoria. Era un cuadro de vidrios rotos, hierba alta y un carrito de supermercado tirado de lado como un animal cansado. La gente pasaba rápido frente a él, como se pasa junto a un perro que podría ladrar.",
          "Entonces, un sábado de abril, el señor Haddad, del tercer piso del edificio de Rosa, cruzó la calle con un rastrillo y un montón de bolsas de basura. Tenía setenta y tres años y caminaba con bastón, así que trabajaba despacio. Llenó una bolsa, descansó sobre una cubeta volteada y llenó otra.",
          "Rosa lo miró desde su ventana durante una hora. Por fin bajó. —¿Por qué hace esto? —le preguntó—. El terreno es de la ciudad. Nunca se lo van a dejar.",
          "El señor Haddad se encogió de hombros. —Tal vez no. Pero hoy va a tener menos vidrio. —Le dio un par de guantes que le quedaban enormes.",
          "El sábado siguiente, el hermanito de Rosa también fue. El sábado después, la señora Obi, de la lavandería, llevó plantitas de tomate en latas de café, y dos adolescentes arrastraron el carrito hasta la banqueta. Para junio, alguien había pintado un letrero que decía HUERTO DE LA CALLE CUARTA con letras verdes disparejas, y la ciudad había aceptado que los vecinos usaran el terreno por un dólar al año.",
          "En agosto, Rosa cortó el primer tomate maduro y lo subió dos pisos hasta el apartamento del señor Haddad. Él lo levantó hacia la luz como si fuera una joya.",
          "—¿Ves? —dijo—. Menos vidrio.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "contradicts-text", "not-in-text"],
        [
          "Which statement best expresses a theme of the story?",
          "One person's small, steady effort can inspire others to join in.",
          ["Gardening", "It is pointless to work hard on something you may never get to keep.", "Older neighbors can teach young people how to grow their own food."],
          ["The next Saturday, Rosa's little brother came too."],
          "Mr. Haddad starts alone and works slowly, and one by one other people join him. The story shows how a small effort can spread.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "El esfuerzo pequeño y constante de una persona puede animar a otras a unirse.",
          ["La jardinería", "No tiene sentido esforzarse por algo que tal vez nunca te van a dejar conservar.", "Los vecinos mayores pueden enseñarles a los jóvenes a cultivar su propia comida."],
          ["El sábado siguiente, el hermanito de Rosa también fue."],
          "El señor Haddad empieza solo y trabaja despacio, y poco a poco otras personas se le unen. El cuento muestra cómo un esfuerzo pequeño se contagia.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "What can you infer from Mr. Haddad's answer, “Maybe not. But today it will have less glass in it”?",
          "A small improvement today is worth it to him, even with no promise.",
          ["He expects the city to let him keep the lot once it is clean.", "He is cleaning the lot because he hopes to find something valuable buried there.", "He believes that no one should ever make plans."],
          ["Maybe not. But today it will have less glass in it."],
          "He admits the city may never let them keep the lot, but he works anyway, because each bag of trash makes the lot better today.",
        ],
        [
          "¿Qué puedes inferir de la respuesta del señor Haddad: “Tal vez no. Pero hoy va a tener menos vidrio”?",
          "Para él vale la pena mejorar un poco hoy, aunque nadie le prometa nada.",
          ["Espera que la ciudad le deje el terreno en cuanto esté limpio.", "Limpia el terreno porque espera encontrar algo de valor enterrado entre la basura.", "Cree que nadie debería hacer planes nunca."],
          ["Tal vez no. Pero hoy va a tener menos vidrio."],
          "Acepta que tal vez la ciudad nunca les deje el terreno, pero trabaja de todos modos, porque cada bolsa de basura mejora el terreno hoy.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In paragraph 1, the shopping cart is lying on its side “like a tired animal.” What does this comparison suggest about the lot?",
          "The lot looks neglected and worn out, as if it has given up.",
          ["Animals have made their home among the weeds and broken glass in the lot.", "The lot is a lively, cheerful place where children like to play.", "The cart belongs to someone who is resting nearby."],
          ["one shopping cart lying on its side like a tired animal"],
          "A tired animal lying on its side looks worn out. The comparison makes the whole lot feel abandoned.",
        ],
        [
          "En el párrafo 1, el carrito está tirado de lado “como un animal cansado”. ¿Qué sugiere esta comparación sobre el terreno?",
          "El terreno se ve descuidado y gastado, como si se hubiera rendido.",
          ["Algunos animales viven entre la hierba alta y los vidrios rotos del terreno.", "El terreno es un lugar alegre y lleno de vida donde a los niños les gusta jugar.", "El carrito es de alguien que está descansando cerca."],
          ["un carrito de supermercado tirado de lado como un animal cansado"],
          "Un animal cansado tirado de lado se ve agotado. La comparación hace que todo el terreno se sienta abandonado.",
        ],
      ),
      q(
        "theme.develop",
        ["too-narrow", "contradicts-text", "not-in-text"],
        [
          "How does the last line, “Less glass,” help develop the theme?",
          "It repeats Mr. Haddad's first small goal, showing how much that small start has grown.",
          ["It reminds readers that the lot was once covered in broken glass, tall weeds, and an old cart.", "It shows that Mr. Haddad has lost interest in the garden.", "It warns readers that the garden will soon be closed."],
          ["“You see?” he said. “Less glass.”"],
          "“Less glass” was Mr. Haddad's tiny goal on the first day. Repeating it while holding a ripe tomato shows how one small step grew into a whole garden.",
        ],
        [
          "¿Cómo ayuda la última línea, “Menos vidrio”, a desarrollar el mensaje?",
          "Repite la primera meta pequeña del señor Haddad y muestra cuánto creció ese pequeño comienzo.",
          ["Les recuerda a los lectores que el terreno antes estaba cubierto de vidrios rotos, hierba alta y un carrito viejo.", "Muestra que el señor Haddad perdió el interés en el huerto.", "Les advierte a los lectores que pronto van a cerrar el huerto."],
          ["—¿Ves? —dijo—. Menos vidrio."],
          "“Menos vidrio” fue la meta mínima del señor Haddad el primer día. Repetirla con un tomate maduro en la mano muestra cómo un paso pequeño se volvió todo un huerto.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Mr. Haddad begins cleaning an empty lot by himself. Rosa and other neighbors join him, and by August the lot has become a community garden.",
          ["Mr. Haddad is the kindest neighbor on Fourth Street, and everyone in the city should learn from him and start cleaning up the empty lots in their own neighborhoods.", "Rosa watches from her window, puts on gloves that are too big, and carries a tomato up two flights of stairs.", "The city cleans up the empty lot and builds a garden as a gift for the neighbors."],
          ["By June, someone had painted a sign that said FOURTH STREET GARDEN"],
          "A good summary covers how the garden began, who joined, and how it turned out, without opinions.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "El señor Haddad empieza a limpiar solo un terreno vacío. Rosa y otros vecinos se le unen, y para agosto el terreno es un huerto comunitario.",
          ["El señor Haddad es el vecino más bondadoso de la calle Cuarta, y todos en la ciudad deberían aprender de él y ponerse a limpiar los terrenos vacíos de sus propios vecindarios.", "Rosa mira desde su ventana, se pone unos guantes enormes y sube un tomate dos pisos.", "La ciudad limpia el terreno vacío y construye un huerto como regalo para los vecinos."],
          ["Para junio, alguien había pintado un letrero que decía HUERTO DE LA CALLE CUARTA"],
          "Un buen resumen cuenta cómo empezó el huerto, quiénes se unieron y cómo terminó, sin opiniones.",
        ],
      ),
    ],
  },
  {
    id: "low-tide",
    level: 1,
    genre: "story",
    en: [
      {
        title: "Low Tide",
        paras: [
          "The tide table said low tide would come at 9:42, and Jun had been watching the clock since breakfast. At low tide, the ocean pulled back from the rocks below the lighthouse and left behind hundreds of pools, each one a small, crowded world. He wanted to reach the far pools, the ones near the point, before the water came back.",
          "His sister Hana did not want to reach anything. She was seven, and she stood at the edge of the first rock in her new rain boots as if it were the edge of a cliff.",
          "“It's slippery,” she said.",
          "“Only the green parts,” Jun said. “Step on the brown parts.” He hopped across three rocks to show her how easy it was and then looked back. She hadn't moved.",
          "Jun sighed loudly enough for her to hear. The far pools were getting farther every minute. Then he noticed that her lip was shaking, and the sigh suddenly felt like something he wanted to take back.",
          "He came back and crouched beside the very first pool, the boring one, the one right next to the sand. “Okay,” he said. “Let's just look at this one.”",
          "They looked. At first it was only water and pebbles. Then a pebble walked. It was a hermit crab, carrying its borrowed shell. Hana gasped. A minute later she found a purple sea star the size of her hand, and then a green anemone that closed gently around her fingertip like a soft fist. She laughed, a big surprised laugh that echoed off the rocks.",
          "They never made it to the far pools. By the time Hana was ready to cross the brown rocks on her own, the tide was already coming in. Walking back, Jun realized he had seen more in one small pool than he usually saw on the whole point.",
        ],
      },
    ],
    es: [
      {
        title: "Marea baja",
        paras: [
          "La tabla de mareas decía que la marea baja llegaría a las 9:42, y Jun llevaba mirando el reloj desde el desayuno. Con la marea baja, el mar se retiraba de las rocas al pie del faro y dejaba cientos de pozas, cada una un mundo pequeño y lleno de vida. Él quería llegar a las pozas lejanas, las de la punta, antes de que volviera el agua.",
          "Su hermana Hana no quería llegar a ninguna parte. Tenía siete años y estaba parada en la orilla de la primera roca, con sus botas de lluvia nuevas, como si fuera el borde de un precipicio.",
          "—Está resbaloso —dijo.",
          "—Solo lo verde —dijo Jun—. Pisa lo café. —Saltó sobre tres rocas para mostrarle lo fácil que era y luego miró hacia atrás. Ella no se había movido.",
          "Jun suspiró lo bastante fuerte para que ella lo oyera. Las pozas lejanas se alejaban más cada minuto. Entonces notó que a ella le temblaba el labio, y de pronto el suspiro le pareció algo que quería retirar.",
          "Regresó y se agachó junto a la primerísima poza, la aburrida, la que estaba junto a la arena. —Bueno —dijo—. Vamos a ver solo esta.",
          "Miraron. Al principio solo había agua y piedritas. Luego, una piedrita caminó. Era un cangrejo ermitaño que cargaba su concha prestada. Hana ahogó un grito. Un minuto después encontró una estrella de mar morada del tamaño de su mano, y luego una anémona verde que se cerró con suavidad alrededor de la punta de su dedo, como un puño blando. Se rio con una risa grande y sorprendida que rebotó en las rocas.",
          "Nunca llegaron a las pozas lejanas. Cuando Hana por fin se animó a cruzar sola las rocas cafés, la marea ya estaba subiendo. De regreso, Jun se dio cuenta de que había visto más en una pequeña poza que lo que solía ver en toda la punta.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["contradicts-text", "wrong-character", "too-narrow"],
        [
          "Which statement best expresses a theme of the story?",
          "Slowing down for someone else can help you notice things you would have missed.",
          ["Reaching your goal matters more than waiting for someone who is slowing you down.", "Being brave means crossing the slippery rocks even when you are scared.", "Tide pools hold more living things than most people expect."],
          ["he had seen more in one small pool than he usually saw on the whole point"],
          "Jun gives up his race to the far pools to stay with Hana, and he ends up seeing more than ever. The story's message comes from that surprise.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "Ir más despacio por otra persona puede ayudarte a notar cosas que te habrías perdido.",
          ["Llegar a tu meta importa más que esperar a alguien que te está haciendo ir más despacio.", "Ser valiente es cruzar las rocas resbalosas aunque tengas miedo.", "Las pozas de marea tienen más seres vivos de lo que casi todos creen."],
          ["había visto más en una pequeña poza que lo que solía ver en toda la punta"],
          "Jun deja su carrera hacia las pozas lejanas para quedarse con Hana, y termina viendo más que nunca. El mensaje del cuento sale de esa sorpresa.",
        ],
      ),
      q(
        "theme.develop",
        ["misses-the-change", "wrong-character", "off-point-evidence"],
        [
          "Which detail best shows that Jun's attitude starts to change?",
          "He notices Hana's lip shaking and wishes he could take back his sigh.",
          ["He hops across three rocks to show her how easy it is.", "Hana laughs a big, surprised laugh when the anemone closes around her finger.", "The tide table says low tide will come at 9:42."],
          ["the sigh suddenly felt like something he wanted to take back"],
          "Until this moment Jun is impatient. Seeing that Hana is truly scared makes him regret his sigh, and he turns back to help her.",
        ],
        [
          "¿Qué detalle muestra mejor que la actitud de Jun empieza a cambiar?",
          "Nota que a Hana le tiembla el labio y quisiera retirar su suspiro.",
          ["Salta sobre tres rocas para mostrarle lo fácil que es.", "Hana suelta una risa grande y sorprendida cuando la anémona se cierra alrededor de su dedo.", "La tabla de mareas dice que la marea baja llegará a las 9:42."],
          ["de pronto el suspiro le pareció algo que quería retirar"],
          "Hasta ese momento Jun está impaciente. Ver que Hana de verdad tiene miedo hace que se arrepienta de su suspiro y regrese a ayudarla.",
        ],
      ),
      q(
        "words.connotation",
        ["contradicts-text", "not-in-text", "not-in-text"],
        [
          "Jun calls the first pool “the boring one.” Why does the author use that word here?",
          "It sets up a surprise: the pool Jun expects nothing from is full of life.",
          ["It shows that the first pool really has nothing living in it, unlike the far pools.", "It shows that Hana is bored by the ocean.", "It means the pool is shallow and easy to walk across."],
          ["the boring one, the one right next to the sand"],
          "Jun thinks the nearest pool will be dull. When it turns out to be full of life, the word “boring” makes the surprise stronger.",
        ],
        [
          "Jun llama a la primera poza “la aburrida”. ¿Por qué el autor usa esa palabra aquí?",
          "Prepara una sorpresa: la poza de la que Jun no espera nada está llena de vida.",
          ["Muestra que en la primera poza de verdad no vive nada, a diferencia de las lejanas.", "Muestra que a Hana le aburre el mar.", "Quiere decir que la poza es poco profunda y fácil de cruzar."],
          ["la aburrida, la que estaba junto a la arena"],
          "Jun cree que la poza más cercana será sosa. Cuando resulta llena de vida, la palabra “aburrida” hace más fuerte la sorpresa.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "What can you infer from the fact that Jun “sighed loudly enough for her to hear”?",
          "He wants Hana to know he is impatient with her.",
          ["He is out of breath from hopping across the rocks.", "He wants Hana to feel proud of how brave she is.", "He gets angry at his sister about everything."],
          ["Jun sighed loudly enough for her to hear."],
          "Sighing so that someone hears it is a way to show impatience. Jun is frustrated that Hana is slowing him down.",
        ],
        [
          "¿Qué puedes inferir del hecho de que Jun “suspiró lo bastante fuerte para que ella lo oyera”?",
          "Quiere que Hana sepa que está impaciente con ella.",
          ["Se quedó sin aliento de tanto saltar sobre las rocas.", "Quiere que Hana se sienta orgullosa de lo valiente que es.", "Se enoja con su hermana por todo."],
          ["Jun suspiró lo bastante fuerte para que ella lo oyera."],
          "Suspirar para que alguien lo oiga es una manera de mostrar impaciencia. Jun está frustrado porque Hana lo retrasa.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Jun wants to rush to the far tide pools, but his little sister is scared of the rocks. He stays with her at the nearest pool, where they find more than he expected.",
          ["Jun is an impatient brother who should have been kinder to Hana from the very beginning of the day.", "Jun and Hana go to the beach below a lighthouse, look at the green and brown rocks, find a hermit crab, a purple sea star, and a green anemone, and walk back when the tide comes in.", "Jun leaves Hana on the sand and explores the far pools near the point by himself."],
          ["“Okay,” he said. “Let's just look at this one.”"],
          "A good summary tells Jun's goal, the problem with Hana's fear, his choice, and the result, without judging him.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Jun quiere correr a las pozas lejanas, pero a su hermanita le dan miedo las rocas. Él se queda con ella en la poza más cercana, donde encuentran más de lo que esperaba.",
          ["Jun es un hermano impaciente que debió ser más amable con Hana desde el principio del día.", "Jun y Hana van a la playa al pie de un faro, miran las rocas verdes y cafés, encuentran un cangrejo ermitaño, una estrella de mar morada y una anémona verde, y regresan cuando sube la marea.", "Jun deja a Hana en la arena y explora él solo las pozas lejanas de la punta."],
          ["—Bueno —dijo—. Vamos a ver solo esta."],
          "Un buen resumen cuenta la meta de Jun, el problema del miedo de Hana, la decisión de él y el resultado, sin juzgarlo.",
        ],
      ),
    ],
  },
  {
    id: "the-map",
    level: 1,
    genre: "story",
    en: [
      {
        title: "The Map",
        paras: [
          "The week Kofi's family moved to Duluth, the snow was already up to the mailbox, and every street looked the same: white, quiet, and unfamiliar. In Houston, he had known which corner store sold the best mango ice pops and which neighbor's dog would follow you to school. Here he didn't even know which way the lake was.",
          "So he made a map. He taped four sheets of paper together on the kitchen table and drew his new building in the middle. Then he added what he knew: the bus stop, the school, the laundromat with the broken dryer. It took about five minutes. The rest of the paper stayed blank.",
          "On Monday, a girl named Ingrid showed him a shortcut behind the library, and he drew it in with a dotted line. On Wednesday, the man at the bakery, Mr. Kowalski, gave him a day-old cardamom roll for free, and Kofi drew a tiny roll next to the bakery and wrote “Mr. K.” Over the next few weeks the map filled up: the sledding hill where Ingrid's brothers raced, the steep street everyone called the Ski Jump, the bench where an old woman fed the pigeons and told him their names.",
          "By March, the paper was soft from being folded and unfolded. Kofi noticed something strange. When he looked at it, he didn't really see streets anymore. He saw Ingrid's shortcut, Mr. K's rolls, and the pigeon lady's bench. Almost every mark on the map had a person attached to it.",
          "One night his mother leaned over his shoulder. “You need more paper,” she said.",
          "Kofi looked at the blank edges. For the first time since the move, the empty space didn't look lonely. It looked like room to grow.",
        ],
      },
    ],
    es: [
      {
        title: "El mapa",
        paras: [
          "La semana en que la familia de Kofi se mudó a Duluth, la nieve ya llegaba al buzón, y todas las calles se veían iguales: blancas, calladas y desconocidas. En Houston, él sabía qué tiendita de la esquina vendía las mejores paletas de mango y qué perro del vecindario te seguía hasta la escuela. Aquí ni siquiera sabía para qué lado quedaba el lago.",
          "Así que hizo un mapa. Pegó cuatro hojas de papel con cinta sobre la mesa de la cocina y dibujó su nuevo edificio en el centro. Luego agregó lo que conocía: la parada del autobús, la escuela, la lavandería con la secadora descompuesta. Le tomó unos cinco minutos. El resto del papel se quedó en blanco.",
          "El lunes, una niña llamada Ingrid le enseñó un atajo detrás de la biblioteca, y él lo dibujó con una línea punteada. El miércoles, el señor de la panadería, el señor Kowalski, le regaló un pan de cardamomo del día anterior, y Kofi dibujó un panecito junto a la panadería y escribió “Sr. K.” En las semanas siguientes, el mapa se fue llenando: la colina donde los hermanos de Ingrid competían en trineo, la calle empinada que todos llamaban el Trampolín, la banca donde una señora mayor alimentaba a las palomas y le decía cómo se llamaba cada una.",
          "Para marzo, el papel estaba suave de tanto doblarlo y desdoblarlo. Kofi notó algo raro. Cuando lo miraba, ya no veía calles. Veía el atajo de Ingrid, los panes del Sr. K y la banca de la señora de las palomas. Casi cada marca del mapa tenía una persona detrás.",
          "Una noche, su mamá se asomó por encima de su hombro. —Te hace falta más papel —le dijo.",
          "Kofi miró los bordes en blanco. Por primera vez desde la mudanza, el espacio vacío no se veía solitario. Parecía espacio por llenar.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "too-narrow", "contradicts-text"],
        [
          "Which statement best expresses a theme of the story?",
          "A new place starts to feel like home as you get to know the people in it.",
          ["Moving", "Making a map can help you learn your way around a new city.", "You can only feel at home in the place where you grew up."],
          ["Almost every mark on the map had a person attached to it."],
          "Kofi's map fills up with places tied to the people he meets, and by the end the city no longer feels lonely. The people are what make it home.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "Un lugar nuevo empieza a sentirse como un hogar cuando conoces a la gente que vive ahí.",
          ["La mudanza", "Hacer un mapa puede ayudarte a orientarte en una ciudad nueva.", "Solo puedes sentirte en casa en el lugar donde creciste."],
          ["Casi cada marca del mapa tenía una persona detrás."],
          "El mapa de Kofi se llena de lugares unidos a las personas que conoce, y al final la ciudad ya no se siente solitaria. La gente es lo que la vuelve un hogar.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "not-in-text", "contradicts-text"],
        [
          "What does the narrator mean in the last line: “It looked like room to grow”?",
          "The blank space now feels like a chance for new places and friends.",
          ["The map is big enough to cover a whole wall.", "Kofi wants to move again to a bigger apartment.", "The empty space reminds Kofi how lonely he still feels in his new city."],
          ["the empty space didn't look lonely"],
          "The blank edges once felt lonely. Now they look like space for the people and places Kofi has not found yet.",
        ],
        [
          "¿Qué quiere decir el narrador en la última línea: “Parecía espacio por llenar”?",
          "El espacio en blanco ahora se siente como una oportunidad para nuevos lugares y amigos.",
          ["El mapa es tan grande que puede cubrir una pared entera.", "Kofi quiere mudarse otra vez a un apartamento más grande.", "El espacio vacío le recuerda a Kofi lo solo que todavía se siente en su nueva ciudad fría."],
          ["el espacio vacío no se veía solitario"],
          "Antes, los bordes en blanco se sentían solitarios. Ahora parecen espacio para las personas y los lugares que Kofi todavía no ha encontrado.",
        ],
      ),
      q(
        "theme.develop",
        ["misses-the-change", "not-in-text", "contradicts-text"],
        [
          "How does the change in Kofi's map help develop the theme?",
          "It goes from a few buildings to places tied to people, showing that people make the city home.",
          ["The first map shows only a bus stop and a school, so Kofi cares only about getting places.", "The paper gets soft from folding, showing that Kofi is careless with his things.", "His mother says he needs more paper, showing that she wants him to stop drawing."],
          ["He saw Ingrid's shortcut, Mr. K's rolls, and the pigeon lady's bench."],
          "At first the map holds only buildings. By March it is full of people's places, which shows how Kofi's connections turn the city into home.",
        ],
        [
          "¿Cómo ayuda el cambio en el mapa de Kofi a desarrollar el mensaje?",
          "Pasa de tener unos cuantos edificios a tener lugares unidos a personas, y muestra que la gente vuelve la ciudad un hogar.",
          ["El primer mapa solo tiene la parada y la escuela, así que a Kofi solo le importa llegar a los lugares.", "El papel se pone suave de tanto doblarlo, y eso muestra que Kofi descuida sus cosas.", "Su mamá dice que le hace falta más papel, y eso muestra que quiere que deje de dibujar."],
          ["Veía el atajo de Ingrid, los panes del Sr. K y la banca de la señora de las palomas."],
          "Al principio el mapa solo tiene edificios. Para marzo está lleno de lugares de personas, lo que muestra cómo los lazos de Kofi vuelven la ciudad un hogar.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "What can you infer about how Kofi felt during his first week in Duluth?",
          "He felt lost and lonely in a place where nothing was familiar.",
          ["He was excited to go sledding right away.", "He was glad to leave everything about his old life in Houston behind him.", "Everyone who moves to a cold, snowy city stays lonely there forever."],
          ["Here he didn't even know which way the lake was."],
          "Kofi compares how well he knew Houston with how little he knows Duluth. Not even knowing where the lake is shows he felt lost.",
        ],
        [
          "¿Qué puedes inferir sobre cómo se sentía Kofi en su primera semana en Duluth?",
          "Se sentía perdido y solo en un lugar donde nada le era conocido.",
          ["Estaba emocionado por ir a deslizarse en trineo de inmediato.", "Estaba contento de dejar atrás todo lo de su vida anterior en Houston.", "Todos los que se mudan a una ciudad fría se sienten solos para siempre."],
          ["Aquí ni siquiera sabía para qué lado quedaba el lago."],
          "Kofi compara lo bien que conocía Houston con lo poco que conoce Duluth. No saber ni dónde queda el lago muestra que se sentía perdido.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "After moving to Duluth, Kofi draws a map. As he meets people and adds the places tied to them, the city starts to feel like home.",
          ["Kofi's map is a clever idea, and every kid who moves to a new city should make one just like it.", "Kofi tapes four sheets of paper together and draws a bus stop, a school, and a laundromat.", "Kofi gets lost in the snow his first week, gives up on his map, and wants his family to move back to Houston."],
          ["Over the next few weeks the map filled up"],
          "The summary needs the move, the map, the people who fill it, and how Kofi's feelings change, without opinions.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Tras mudarse a Duluth, Kofi dibuja un mapa. Al conocer gente y agregar los lugares unidos a ella, la ciudad empieza a sentirse como un hogar.",
          ["El mapa de Kofi es una idea ingeniosa, y todos los niños que se mudan deberían hacer uno igual.", "Kofi pega cuatro hojas con cinta y dibuja una parada de autobús, una escuela y una lavandería.", "Kofi se pierde en la nieve su primera semana, abandona su mapa y quiere que su familia vuelva a Houston."],
          ["En las semanas siguientes, el mapa se fue llenando"],
          "El resumen necesita la mudanza, el mapa, las personas que lo llenan y cómo cambian los sentimientos de Kofi, sin opiniones.",
        ],
      ),
    ],
  },
];
