import { type Passage, q } from "./types";

// Level 2 arguments by student writers on civic questions. Each has real evidence and one weak spot in
// its reasoning on purpose, so the argument can be judged. Facts were checked when written.
export const L2_ARGUMENTS: Passage[] = [
  {
    id: "bag-ban",
    level: 2,
    genre: "argument",
    en: [
      {
        title: "Bag the Bags",
        paras: [
          "Members of the Riverton City Council: Every spring, my science class joins the cleanup along Mill Creek. This year, we sorted and counted everything we pulled out of the water and the brush along its banks. Plastic shopping bags were the single most common item, more than bottles, cans, or food wrappers. I am here to ask you to ban single-use plastic bags at stores in our city.",
          "Plastic bags are a problem because of what they are designed to be: light, thin, and cheap. They are used for a few minutes, but they can last for many years. The wind carries them out of trash cans and off of landfills. They clog storm drains, tangle in trees, and break into small pieces that fish and birds can mistake for food.",
          "A ban is not an untested idea. California banned single-use plastic bags at large stores statewide in 2014, and voters chose to keep the law in 2016. Several states and many cities have passed similar laws since then.",
          "Some store owners worry that a ban will cost them money and annoy their customers. That concern deserves an answer. Our proposal would give stores six months to prepare and would allow paper bags for a small fee, so shoppers who forget a reusable bag will still have a choice.",
          "Others say paper bags are no better for the environment. It is true that paper bags take energy to make. But a paper bag that blows into Mill Creek breaks down; a plastic one stays. And the real goal is not to swap one bag for another; it is to get people to bring their own.",
          "Finally, anyone who truly cares about Riverton's wildlife will support this ban. If you vote no, you are choosing convenience over the creek. I hope you will vote yes.",
        ],
      },
    ],
    es: [
      {
        title: "Adiós a las bolsas",
        paras: [
          "Miembros del Concejo Municipal de Riverton: Cada primavera, mi clase de ciencias participa en la limpieza del arroyo Mill. Este año clasificamos y contamos todo lo que sacamos del agua y de la maleza de la orilla. Las bolsas de plástico del súper fueron el objeto más común, por encima de las botellas, las latas y las envolturas de comida. Vengo a pedirles que prohíban las bolsas de plástico de un solo uso en las tiendas de nuestra ciudad.",
          "Las bolsas de plástico son un problema justamente por cómo están diseñadas: ligeras, delgadas y baratas. Se usan unos minutos, pero pueden durar muchos años. El viento se las lleva de los botes de basura y de los rellenos sanitarios. Tapan las coladeras, se enredan en los árboles y se rompen en pedacitos que los peces y las aves pueden confundir con comida.",
          "Una prohibición no es una idea sin probar. California prohibió las bolsas de plástico de un solo uso en las tiendas grandes de todo el estado en 2014, y los votantes decidieron mantener la ley en 2016. Desde entonces, varios estados y muchas ciudades han aprobado leyes parecidas.",
          "A algunos dueños de tiendas les preocupa que la prohibición les cueste dinero y moleste a sus clientes. Esa preocupación merece una respuesta. Nuestra propuesta les daría a las tiendas seis meses para prepararse y permitiría bolsas de papel por una pequeña cuota, así que quien olvide su bolsa reutilizable todavía tendrá opción.",
          "Otros dicen que las bolsas de papel no son mejores para el medio ambiente. Es cierto que fabricar bolsas de papel gasta energía. Pero una bolsa de papel que el viento lleva al arroyo Mill se deshace; una de plástico se queda. Y la verdadera meta no es cambiar una bolsa por otra, sino que la gente traiga la suya.",
          "Por último, cualquiera a quien de verdad le importen los animales de Riverton apoyará esta prohibición. Si votan que no, están eligiendo la comodidad por encima del arroyo. Espero que voten que sí.",
        ],
      },
    ],
    qs: [
      q(
        "argument.claim",
        ["evidence-not-claim", "counterclaim-not-claim", "evidence-not-claim"],
        [
          "Which sentence states the author's main claim?",
          "I am here to ask you to ban single-use plastic bags at stores in our city.",
          ["Plastic shopping bags were the single most common item, more than bottles, cans, or food wrappers.", "Some store owners worry that a ban will cost them money and annoy their customers.", "California banned single-use plastic bags at large stores statewide in 2014, and voters chose to keep the law in 2016."],
          ["I am here to ask you to ban single-use plastic bags at stores in our city."],
          "Everything else in the testimony supports this request or answers objections to it. The cleanup count and California's law are evidence; the store owners' worry is the other side.",
        ],
        [
          "¿Qué oración presenta la afirmación principal de quien escribe?",
          "Vengo a pedirles que prohíban las bolsas de plástico de un solo uso en las tiendas de nuestra ciudad.",
          ["Las bolsas de plástico del súper fueron el objeto más común, por encima de las botellas, las latas y las envolturas de comida.", "A algunos dueños de tiendas les preocupa que la prohibición les cueste dinero y moleste a sus clientes.", "California prohibió las bolsas de plástico de un solo uso en las tiendas grandes de todo el estado en 2014, y los votantes decidieron mantener la ley en 2016."],
          ["Vengo a pedirles que prohíban las bolsas de plástico de un solo uso en las tiendas de nuestra ciudad."],
          "Todo lo demás del testimonio apoya esta petición o responde a objeciones. El conteo de la limpieza y la ley de California son evidencia; la preocupación de los dueños de tiendas es la otra postura.",
        ],
      ),
      q(
        "argument.evidence",
        ["off-point-evidence", "opinion-as-evidence", "off-point-evidence"],
        [
          "Which evidence best supports the claim that plastic bags are a real problem in Riverton itself?",
          "The class's count from the Mill Creek cleanup.",
          ["California's statewide ban in 2014.", "The author's belief that anyone who cares about wildlife will agree.", "The point that paper bags take energy to make."],
          ["we sorted and counted everything we pulled out of the water"],
          "Only the cleanup count is about Riverton: bags were the most common item in the local creek. California's law happened elsewhere, the belief about wildlife is an opinion, and the energy point is about paper.",
        ],
        [
          "¿Qué evidencia apoya mejor la afirmación de que las bolsas de plástico son un problema real en el propio Riverton?",
          "El conteo de la clase en la limpieza del arroyo Mill.",
          ["La prohibición de California en todo el estado en 2014.", "La creencia de quien escribe de que cualquiera a quien le importen los animales estará de acuerdo.", "La idea de que fabricar bolsas de papel gasta energía."],
          ["clasificamos y contamos todo lo que sacamos del agua"],
          "Solo el conteo de la limpieza trata de Riverton: las bolsas fueron el objeto más común en el arroyo de la ciudad. La ley de California ocurrió en otro lugar, lo de los animales es una opinión y lo de la energía trata del papel.",
        ],
      ),
      q(
        "argument.reasoning",
        ["not-a-flaw", "not-a-flaw", "not-a-flaw"],
        [
          "Which part of the testimony relies on the weakest reasoning?",
          "The claim that anyone who truly cares about wildlife will support the ban.",
          ["The count of items pulled from Mill Creek during the cleanup.", "The plan to give stores six months and allow paper bags for a fee.", "The point that a paper bag breaks down in the creek while a plastic one stays."],
          ["If you vote no, you are choosing convenience over the creek."],
          "That claim treats every no vote as not caring about wildlife and offers only two choices. A council member could care about the creek and still have doubts about this law.",
        ],
        [
          "¿Qué parte del testimonio se apoya en el razonamiento más débil?",
          "La afirmación de que cualquiera a quien de verdad le importen los animales apoyará la prohibición.",
          ["El conteo de los objetos que se sacaron del arroyo Mill durante la limpieza.", "El plan de darles seis meses a las tiendas y permitir bolsas de papel por una cuota.", "La idea de que una bolsa de papel se deshace en el arroyo Mill mientras que una de plástico se queda ahí."],
          ["Si votan que no, están eligiendo la comodidad por encima del arroyo."],
          "Esa afirmación trata cada voto en contra como falta de interés por los animales y ofrece solo dos opciones. Un concejal podría preocuparse por el arroyo y aun así tener dudas sobre esta ley.",
        ],
      ),
      q(
        "pov.response",
        ["misses-author-stance", "contradicts-text", "contradicts-text"],
        [
          "How does the author respond to the concern that paper bags are no better?",
          "The author admits a cost of paper, then argues that plastic does more lasting harm and that reuse is the real goal.",
          ["The author agrees that paper bags are just as harmful as plastic ones and decides the city should ban paper bags as well.", "The author says paper bags take no energy at all to make.", "The author ignores the concern and moves on."],
          ["It is true that paper bags take energy to make."],
          "The author grants the point about energy, then answers it: paper breaks down in the creek, plastic stays, and the aim is for people to bring their own bags.",
        ],
        [
          "¿Cómo responde quien escribe a la preocupación de que las bolsas de papel no son mejores?",
          "Admite un costo del papel y luego argumenta que el plástico hace un daño más duradero y que la meta real es reutilizar.",
          ["Le da la razón, dice que las bolsas de papel son igual de dañinas que las de plástico y decide que la ciudad también debe prohibirlas.", "Dice que fabricar bolsas de papel no gasta nada de energía.", "Ignora la preocupación y pasa a otro tema."],
          ["Es cierto que fabricar bolsas de papel gasta energía."],
          "Quien escribe acepta lo de la energía y luego responde: el papel se deshace en el arroyo, el plástico se queda, y la meta es que la gente traiga sus propias bolsas.",
        ],
      ),
      q(
        "structure.section",
        ["wrong-section-role", "wrong-section-role", "contradicts-text"],
        [
          "What is the purpose of paragraph 4?",
          "To answer store owners' worries with details of the plan.",
          ["To present the main evidence from the creek cleanup.", "To explain why plastic bags last so long in the environment.", "To admit that the ban is a bad idea for small stores."],
          ["That concern deserves an answer."],
          "Paragraph 4 names the store owners' worry and answers it with six months to prepare and paper bags for a fee, which makes the proposal harder to dismiss.",
        ],
        [
          "¿Cuál es el propósito del párrafo 4?",
          "Responder a las preocupaciones de los dueños de tiendas con detalles del plan.",
          ["Presentar la evidencia principal de la limpieza del arroyo.", "Explicar por qué las bolsas de plástico duran tantos años en el arroyo y en el medio ambiente.", "Admitir que la prohibición es una mala idea para las tiendas pequeñas."],
          ["Esa preocupación merece una respuesta."],
          "El párrafo 4 nombra la preocupación de los dueños de tiendas y la responde con seis meses para prepararse y bolsas de papel por una cuota, lo que hace la propuesta más difícil de rechazar.",
        ],
      ),
    ],
  },
  {
    id: "vote-sixteen",
    level: 2,
    genre: "argument",
    en: [
      {
        title: "Sixteen Is Old Enough",
        paras: [
          "In my city, a sixteen-year-old can drive a car, hold a job, and pay taxes on every paycheck. What she cannot do is vote for the city council that decides how those taxes are spent. Our city should lower the voting age to sixteen for local elections.",
          "This would not be a wild experiment. Takoma Park, Maryland, became the first city in the United States to let sixteen-year-olds vote in local elections in 2013, and a few other Maryland cities have followed. Austria lowered its voting age to sixteen for all national elections in 2007.",
          "Local government shapes the things teenagers use every day: parks, libraries, buses, and the schools themselves. Students know which bus routes are always late and which parks have broken lights. Their experience is exactly the kind of information a council needs.",
          "Voting is also a habit. Researchers who study elections have found that people who vote in the first election they are eligible for are more likely to keep voting. At sixteen, most young people still live at home and attend school, where teachers can explain how to register and parents can bring them to the polls. At eighteen, many are moving away, starting jobs, or heading to college, which is a hard time to start a new habit.",
          "Some people argue that sixteen-year-olds are not mature enough to vote. But no one gives adults a maturity test before they vote, and plenty of teenagers follow local news more closely than adults do. Besides, my older brother voted for the first time last year and could not name a single candidate, which proves that eighteen-year-olds are no better.",
          "Sixteen-year-olds already live with the decisions the council makes. It is time to let them help make those decisions.",
        ],
      },
    ],
    es: [
      {
        title: "Dieciséis años es suficiente",
        paras: [
          "En mi ciudad, alguien de dieciséis años puede manejar un carro, tener un trabajo y pagar impuestos con cada cheque. Lo que no puede hacer es votar por el concejo municipal que decide cómo se gastan esos impuestos. Nuestra ciudad debería bajar la edad para votar a los dieciséis años en las elecciones locales.",
          "Esto no sería un experimento loco. En 2013, Takoma Park, Maryland, se convirtió en la primera ciudad de Estados Unidos en dejar votar en elecciones locales a los jóvenes de dieciséis años, y otras pocas ciudades de Maryland la han seguido. Austria bajó la edad para votar a los dieciséis años en todas sus elecciones nacionales en 2007.",
          "El gobierno local decide sobre las cosas que los adolescentes usan todos los días: parques, bibliotecas, autobuses y las propias escuelas. Los estudiantes saben qué rutas de autobús siempre llegan tarde y qué parques tienen las luces rotas. Su experiencia es justo el tipo de información que necesita un concejo.",
          "Votar también es un hábito. Los investigadores que estudian las elecciones han encontrado que las personas que votan en la primera elección en la que pueden hacerlo tienen más probabilidades de seguir votando. A los dieciséis, la mayoría de los jóvenes todavía vive en casa y va a la escuela, donde los maestros pueden explicarles cómo registrarse y los padres pueden llevarlos a votar. A los dieciocho, muchos se están mudando, empezando a trabajar o yéndose a la universidad, y es un momento difícil para empezar un hábito nuevo.",
          "Algunas personas dicen que a los dieciséis años no se tiene la madurez para votar. Pero a los adultos nadie les hace una prueba de madurez antes de votar, y muchos adolescentes siguen las noticias locales más de cerca que los adultos. Además, mi hermano mayor votó por primera vez el año pasado y no pudo nombrar a un solo candidato, lo que demuestra que los de dieciocho no son mejores.",
          "Los jóvenes de dieciséis años ya viven con las decisiones que toma el concejo. Es hora de dejarlos ayudar a tomarlas.",
        ],
      },
    ],
    qs: [
      q(
        "argument.claim",
        ["counterclaim-not-claim", "evidence-not-claim", "evidence-not-claim"],
        [
          "Which sentence states the author's main claim?",
          "Our city should lower the voting age to sixteen for local elections.",
          ["Some people argue that sixteen-year-olds are not mature enough to vote.", "Austria lowered its voting age to sixteen for all national elections in 2007.", "Local government shapes the things teenagers use every day: parks, libraries, buses, and the schools themselves."],
          ["Our city should lower the voting age to sixteen for local elections."],
          "This is the position every paragraph supports. The maturity sentence is the other side's view, and the Austria and local-government sentences are support.",
        ],
        [
          "¿Qué oración presenta la afirmación principal de quien escribe?",
          "Nuestra ciudad debería bajar la edad para votar a los dieciséis años en las elecciones locales.",
          ["Algunas personas dicen que a los dieciséis años no se tiene la madurez para votar.", "Austria bajó la edad para votar a los dieciséis años en todas sus elecciones nacionales en 2007.", "El gobierno local decide sobre las cosas que los adolescentes usan todos los días: parques, bibliotecas, autobuses y las propias escuelas."],
          ["Nuestra ciudad debería bajar la edad para votar a los dieciséis años en las elecciones locales."],
          "Esta es la postura que apoyan todos los párrafos. La oración de la madurez es la postura contraria, y las de Austria y el gobierno local son apoyo.",
        ],
      ),
      q(
        "argument.evidence",
        ["anecdote-as-proof", "off-point-evidence", "off-point-evidence"],
        [
          "Which evidence best supports the claim that voting at sixteen could build a lasting habit?",
          "Research finding that people who vote in their first eligible election tend to keep voting.",
          ["The author's older brother voted for the first time last year and could not name a single candidate.", "A sixteen-year-old can drive a car and hold a job.", "Teenagers know which parks have broken lights."],
          ["Voting is also a habit."],
          "The claim is about habits that last. Research on first-time voters speaks to that directly. One brother's story is a single case, and the other details are about different points.",
        ],
        [
          "¿Qué evidencia apoya mejor la afirmación de que votar a los dieciséis podría crear un hábito duradero?",
          "Investigaciones que encontraron que quienes votan en su primera elección posible suelen seguir votando.",
          ["El hermano mayor de quien escribe votó por primera vez el año pasado y no pudo nombrar a un solo candidato.", "Alguien de dieciséis años puede manejar un carro y tener un trabajo.", "Los adolescentes saben qué parques tienen las luces rotas."],
          ["Votar también es un hábito."],
          "La afirmación trata de hábitos que duran. Las investigaciones sobre quienes votan por primera vez hablan justo de eso. La historia de un hermano es un solo caso, y los otros detalles tratan de otros puntos.",
        ],
      ),
      q(
        "argument.reasoning",
        ["not-a-flaw", "not-a-flaw", "not-a-flaw"],
        [
          "Which sentence relies on the weakest reasoning?",
          "Besides, my older brother voted for the first time last year and could not name a single candidate, which proves that eighteen-year-olds are no better.",
          ["Takoma Park, Maryland, became the first city in the United States to let sixteen-year-olds vote in local elections in 2013, and a few other Maryland cities have followed.", "Students know which bus routes are always late and which parks have broken lights.", "Researchers who study elections have found that people who vote in the first election they are eligible for are more likely to keep voting."],
          ["which proves that eighteen-year-olds are no better"],
          "One brother cannot prove anything about all eighteen-year-olds. The sentence turns a single story into a rule about a whole group.",
        ],
        [
          "¿Qué oración se apoya en el razonamiento más débil?",
          "Además, mi hermano mayor votó por primera vez el año pasado y no pudo nombrar a un solo candidato, lo que demuestra que los de dieciocho no son mejores.",
          ["En 2013, Takoma Park, Maryland, se convirtió en la primera ciudad de Estados Unidos en dejar votar en elecciones locales a los jóvenes de dieciséis años, y otras pocas ciudades de Maryland la han seguido.", "Los estudiantes saben qué rutas de autobús siempre llegan tarde y qué parques tienen las luces rotas.", "Los investigadores que estudian las elecciones han encontrado que las personas que votan en la primera elección en la que pueden hacerlo tienen más probabilidades de seguir votando."],
          ["lo que demuestra que los de dieciocho no son mejores"],
          "Un solo hermano no puede probar nada sobre todos los jóvenes de dieciocho años. La oración convierte una sola historia en una regla sobre todo un grupo.",
        ],
      ),
      q(
        "pov.response",
        ["misses-author-stance", "not-in-text", "contradicts-text"],
        [
          "How does the author respond to the argument that sixteen-year-olds are not mature enough to vote?",
          "By pointing out that adults face no maturity test and that many teens follow local news closely.",
          ["By agreeing with the objection and suggesting that teenage voters should first pass a maturity test.", "By saying that maturity matters more than anything else in voting.", "By ignoring the argument entirely."],
          ["But no one gives adults a maturity test before they vote"],
          "The author names the objection and answers it with two points: no adult is tested for maturity, and many teens already follow local news.",
        ],
        [
          "¿Cómo responde quien escribe al argumento de que a los dieciséis años no se tiene la madurez para votar?",
          "Señala que a los adultos no se les hace una prueba de madurez y que muchos adolescentes siguen de cerca las noticias locales.",
          ["Le da la razón a la objeción y propone que los votantes adolescentes tengan que pasar primero una prueba de madurez antes de votar.", "Dice que la madurez importa más que cualquier otra cosa al votar.", "Ignora el argumento por completo."],
          ["Pero a los adultos nadie les hace una prueba de madurez antes de votar"],
          "Quien escribe nombra la objeción y la responde con dos ideas: a ningún adulto se le mide la madurez, y muchos adolescentes ya siguen las noticias locales.",
        ],
      ),
      q(
        "structure.section",
        ["wrong-section-role", "wrong-section-role", "wrong-section-role"],
        [
          "What is the role of paragraph 2?",
          "To show that the idea has already been tried elsewhere.",
          ["To state the author's main claim for the first time.", "To answer the argument that teenagers are not mature enough.", "To explain why voting becomes a habit."],
          ["This would not be a wild experiment."],
          "Right after the claim, paragraph 2 heads off the worry that the idea is untested by naming a city and a country that already let sixteen-year-olds vote.",
        ],
        [
          "¿Qué función tiene el párrafo 2?",
          "Mostrar que la idea ya se ha probado en otros lugares.",
          ["Presentar por primera vez la afirmación principal de quien escribe.", "Responder al argumento de que los adolescentes no tienen suficiente madurez.", "Explicar por qué votar se vuelve un hábito."],
          ["Esto no sería un experimento loco."],
          "Justo después de la afirmación, el párrafo 2 se adelanta a la duda de que la idea no está probada y nombra una ciudad y un país que ya dejan votar a los jóvenes de dieciséis años.",
        ],
      ),
    ],
  },
  {
    id: "free-buses",
    level: 2,
    genre: "argument",
    en: [
      {
        title: "Make the Buses Free",
        paras: [
          "Every weekday morning, the number 9 bus passes my stop with empty seats while a long line of cars waits at the light on Grand Avenue. Our city spends millions of dollars a year on its buses, and yet most people drive. I believe the city should make its buses free to ride.",
          "Fares are a bigger barrier than they seem. A round trip in our city costs $4.50. For a family with two working parents and a teenager who rides to school, that can add up to more than $250 a month. For people with low incomes, that money competes with groceries and rent.",
          "Free buses are not a fantasy. Kansas City, Missouri, became one of the first large American cities to make its buses free, beginning in 2020. Tallinn, the capital of Estonia, has offered free public transit to its residents since 2013.",
          "Collecting fares also costs money. Fare boxes must be bought, repaired, and emptied, and drivers spend time making change while the bus sits at the curb. Some of what the city collects in fares already goes right back out to pay for collecting them.",
          "Critics say that free buses would cost the city money it cannot spare. That is a fair concern, and the city would need to replace the lost fares with other funds. But the city already pays for roads, parking garages, and traffic police that mostly serve drivers. Spending some of that money on buses would help everyone, including drivers, who would face less traffic.",
          "Of course, if the buses were free, everyone in the city would immediately leave their cars at home, and traffic would disappear for good. A free bus is a simple idea whose time has come.",
        ],
      },
    ],
    es: [
      {
        title: "Que los autobuses sean gratis",
        paras: [
          "Cada mañana entre semana, el autobús 9 pasa por mi parada con asientos vacíos mientras una larga fila de carros espera el semáforo en la avenida Grand. Nuestra ciudad gasta millones de dólares al año en sus autobuses, y aun así la mayoría de la gente maneja. Creo que la ciudad debería hacer que sus autobuses sean gratis.",
          "El pasaje es un obstáculo más grande de lo que parece. Un viaje de ida y vuelta en nuestra ciudad cuesta $4.50. Para una familia con dos padres que trabajan y un adolescente que va a la escuela en autobús, eso puede sumar más de $250 al mes. Para las personas de bajos ingresos, ese dinero compite con la comida y la renta.",
          "Los autobuses gratis no son una fantasía. Kansas City, en Missouri, fue una de las primeras ciudades grandes de Estados Unidos en hacer gratis sus autobuses, a partir de 2020. Tallin, la capital de Estonia, ofrece transporte público gratis a sus residentes desde 2013.",
          "Cobrar el pasaje también cuesta dinero. Hay que comprar las alcancías de cobro, repararlas y vaciarlas, y los choferes pierden tiempo dando cambio mientras el autobús espera junto a la banqueta. Parte de lo que la ciudad recibe en pasajes ya se va en pagar por cobrarlos.",
          "Los críticos dicen que los autobuses gratis le costarían a la ciudad un dinero que no le sobra. Es una preocupación justa, y la ciudad tendría que reponer los pasajes perdidos con otros fondos. Pero la ciudad ya paga calles, estacionamientos y policías de tránsito que sirven sobre todo a quienes manejan. Usar parte de ese dinero en los autobuses ayudaría a todos, incluso a quienes manejan, porque habría menos tráfico.",
          "Claro, si los autobuses fueran gratis, todo el mundo en la ciudad dejaría el carro en casa de inmediato, y el tráfico desaparecería para siempre. Un autobús gratis es una idea sencilla cuyo momento ha llegado.",
        ],
      },
    ],
    qs: [
      q(
        "argument.claim",
        ["counterclaim-not-claim", "evidence-not-claim", "evidence-not-claim"],
        [
          "Which sentence states the author's main claim?",
          "I believe the city should make its buses free to ride.",
          ["Critics say that free buses would cost the city money it cannot spare.", "A round trip in our city costs $4.50.", "Tallinn, the capital of Estonia, has offered free public transit to its residents since 2013."],
          ["I believe the city should make its buses free to ride."],
          "This is the position the whole essay defends. The fare and Tallinn sentences are evidence, and the critics' sentence is the other side.",
        ],
        [
          "¿Qué oración presenta la afirmación principal de quien escribe?",
          "Creo que la ciudad debería hacer que sus autobuses sean gratis.",
          ["Los críticos dicen que los autobuses gratis le costarían a la ciudad un dinero que no le sobra.", "Un viaje de ida y vuelta en nuestra ciudad cuesta $4.50.", "Tallin, la capital de Estonia, ofrece transporte público gratis a sus residentes desde 2013."],
          ["Creo que la ciudad debería hacer que sus autobuses sean gratis."],
          "Esta es la postura que defiende todo el ensayo. Las oraciones del pasaje y de Tallin son evidencia, y la de los críticos es la otra postura.",
        ],
      ),
      q(
        "argument.evidence",
        ["off-point-evidence", "off-point-evidence", "off-point-evidence"],
        [
          "Which detail best supports the claim that fares are a real burden for some families?",
          "A family of three riders can spend more than $250 a month on fares.",
          ["The number 9 bus passes the author's stop every morning with empty seats.", "Kansas City made its buses free beginning in 2020.", "Drivers spend time making change at the curb."],
          ["For people with low incomes, that money competes with groceries and rent."],
          "The claim is about what fares cost families. Only the monthly total shows that cost. Empty seats, Kansas City, and making change support other points.",
        ],
        [
          "¿Qué detalle apoya mejor la afirmación de que el pasaje es una carga real para algunas familias?",
          "Una familia con tres pasajeros puede gastar más de $250 al mes en pasajes.",
          ["El autobús 9 pasa cada mañana por la parada de quien escribe con asientos vacíos.", "Kansas City hizo gratis sus autobuses a partir de 2020.", "Los choferes pierden tiempo dando cambio junto a la banqueta."],
          ["Para las personas de bajos ingresos, ese dinero compite con la comida y la renta."],
          "La afirmación trata de lo que el pasaje les cuesta a las familias. Solo el total al mes muestra ese costo. Los asientos vacíos, Kansas City y el cambio apoyan otras ideas.",
        ],
      ),
      q(
        "argument.reasoning",
        ["not-a-flaw", "not-a-flaw", "not-a-flaw"],
        [
          "Which part of the essay relies on the weakest reasoning?",
          "The prediction that free buses would make traffic disappear for good.",
          ["The cost of fares for a family of three riders.", "The example of Kansas City and Tallinn, which already offer free public transit.", "The point that collecting fares has its own costs."],
          ["everyone in the city would immediately leave their cars at home"],
          "No change makes everyone do the same thing at once. Claiming that free buses would end traffic for good overstates what any evidence in the essay could show.",
        ],
        [
          "¿Qué parte del ensayo se apoya en el razonamiento más débil?",
          "La predicción de que los autobuses gratis harían desaparecer el tráfico para siempre.",
          ["El costo de los pasajes para una familia con tres pasajeros.", "El ejemplo de Kansas City y Tallin, que ya ofrecen transporte público gratis a su gente.", "La idea de que cobrar el pasaje tiene sus propios costos."],
          ["todo el mundo en la ciudad dejaría el carro en casa de inmediato"],
          "Ningún cambio hace que todos hagan lo mismo a la vez. Decir que los autobuses gratis acabarían con el tráfico para siempre exagera lo que cualquier evidencia del ensayo podría mostrar.",
        ],
      ),
      q(
        "pov.purpose",
        ["overstates-view", "not-in-text", "not-in-text"],
        [
          "Why does the author mention roads, parking garages, and traffic police in paragraph 5?",
          "To show that the city already spends public money on getting around, mostly for drivers.",
          ["To argue that the city should stop building and repairing roads altogether and spend everything on buses.", "To complain that the police give out too many parking tickets.", "To prove that buses cost more than roads do."],
          ["But the city already pays for roads, parking garages, and traffic police that mostly serve drivers."],
          "The author is answering the cost objection. Pointing to money already spent on drivers suggests that paying for buses would be a shift in spending, not something new.",
        ],
        [
          "¿Por qué quien escribe menciona las calles, los estacionamientos y los policías de tránsito en el párrafo 5?",
          "Para mostrar que la ciudad ya gasta dinero público en transporte, sobre todo para quienes manejan.",
          ["Para defender que la ciudad deje de construir y arreglar calles por completo y gaste todo en autobuses.", "Para quejarse de que la policía pone demasiadas multas de estacionamiento.", "Para probar que los autobuses cuestan más que las calles."],
          ["Pero la ciudad ya paga calles, estacionamientos y policías de tránsito que sirven sobre todo a quienes manejan."],
          "Quien escribe responde a la objeción del costo. Señalar el dinero que ya se gasta en quienes manejan sugiere que pagar los autobuses sería mover el gasto, no algo nuevo.",
        ],
      ),
      q(
        "structure.section",
        ["wrong-section-role", "wrong-section-role", "wrong-section-role"],
        [
          "How does paragraph 4 add to the argument?",
          "It shows that charging fares has its own costs, so free buses would lose less money than it seems.",
          ["It answers critics directly by agreeing that the city would need to replace lost fares with other funds.", "It gives examples of cities that already have free buses.", "It states the author's claim for the first time."],
          ["Collecting fares also costs money."],
          "Before the critics' objection in paragraph 5, paragraph 4 shrinks it: if collecting fares costs money, then giving up fares costs the city less than the full amount collected.",
        ],
        [
          "¿Cómo contribuye el párrafo 4 al argumento?",
          "Muestra que cobrar el pasaje tiene sus propios costos, así que los autobuses gratis perderían menos dinero de lo que parece.",
          ["Responde directamente a los críticos al aceptar que la ciudad tendría que reponer los pasajes perdidos con dinero de otros fondos.", "Da ejemplos de ciudades que ya tienen autobuses gratis.", "Presenta por primera vez la afirmación de quien escribe."],
          ["Cobrar el pasaje también cuesta dinero."],
          "Antes de la objeción de los críticos en el párrafo 5, el párrafo 4 la achica: si cobrar el pasaje cuesta dinero, dejar de cobrarlo le cuesta a la ciudad menos que todo lo que recibe.",
        ],
      ),
    ],
  },
  {
    id: "keep-cursive",
    level: 2,
    genre: "argument",
    en: [
      {
        title: "Bring Back Cursive",
        paras: [
          "When my grandmother sends me a birthday card, she writes in cursive, and every year I understand a little less of it. That is a loss, and our district can prevent it. Our schools should teach cursive handwriting again, starting in third grade.",
          "Cursive was once a standard part of every elementary school day. But the Common Core standards, adopted by most states after 2010, do not require it, and many schools dropped it to make room for typing and test preparation. Since then, a number of states have passed laws bringing cursive back.",
          "Being able to read cursive matters. Family letters, diaries, and many historical records are handwritten in it. A student who cannot read cursive cannot read the original handwriting of a great-grandparent's letters, or of many documents from the nation's past, without someone else's help.",
          "Some argue that cursive is a waste of time in a world of keyboards. It is true that students need to type well, and nothing about teaching cursive would change that. But cursive does not need to take much time. Fifteen minutes a day for part of third grade is enough for most children to learn the letters, and the ability to read cursive lasts a lifetime.",
          "Finally, if we stop teaching cursive, the next thing to go will be handwriting altogether, and soon students will not be able to sign their own names. We cannot let that happen.",
        ],
      },
    ],
    es: [
      {
        title: "Que vuelva la letra cursiva",
        paras: [
          "Cuando mi abuela me manda una tarjeta de cumpleaños, escribe en letra cursiva, y cada año entiendo un poco menos. Eso es una pérdida, y nuestro distrito puede evitarla. Nuestras escuelas deberían volver a enseñar letra cursiva, a partir de tercer grado.",
          "La letra cursiva antes era parte normal de cada día de la primaria. Pero los estándares Common Core, que adoptó la mayoría de los estados después de 2010, no la exigen, y muchas escuelas la dejaron para hacerle lugar a la mecanografía y a la preparación para los exámenes. Desde entonces, varios estados han aprobado leyes para que vuelva.",
          "Saber leer letra cursiva importa. Las cartas de familia, los diarios y muchos documentos históricos están escritos a mano en ella. Un estudiante que no sabe leer cursiva no puede leer la letra original de las cartas de un bisabuelo, ni muchos documentos del pasado del país, sin que alguien más lo ayude.",
          "Algunos dicen que la letra cursiva es una pérdida de tiempo en un mundo de teclados. Es cierto que los estudiantes necesitan escribir bien en el teclado, y enseñar cursiva no cambiaría eso. Pero la cursiva no tiene que tomar mucho tiempo. Quince minutos al día durante una parte del tercer grado bastan para que la mayoría de los niños aprenda las letras, y saber leer cursiva dura toda la vida.",
          "Por último, si dejamos de enseñar cursiva, lo siguiente en desaparecer será la escritura a mano por completo, y pronto los estudiantes no podrán firmar con su propio nombre. No podemos permitirlo.",
        ],
      },
    ],
    qs: [
      q(
        "argument.claim",
        ["counterclaim-not-claim", "evidence-not-claim", "evidence-not-claim"],
        [
          "Which sentence states the author's main claim?",
          "Our schools should teach cursive handwriting again, starting in third grade.",
          ["Some argue that cursive is a waste of time in a world of keyboards.", "Family letters, diaries, and many historical records are handwritten in it.", "When my grandmother sends me a birthday card, she writes in cursive, and every year I understand a little less of it."],
          ["Our schools should teach cursive handwriting again, starting in third grade."],
          "This is the change the essay asks for. The keyboard sentence is the other side, and the letters and birthday-card sentences are support.",
        ],
        [
          "¿Qué oración presenta la afirmación principal de quien escribe?",
          "Nuestras escuelas deberían volver a enseñar letra cursiva, a partir de tercer grado.",
          ["Algunos dicen que la letra cursiva es una pérdida de tiempo en un mundo de teclados.", "Las cartas de familia, los diarios y muchos documentos históricos están escritos a mano en ella.", "Cuando mi abuela me manda una tarjeta de cumpleaños, escribe en letra cursiva, y cada año entiendo un poco menos."],
          ["Nuestras escuelas deberían volver a enseñar letra cursiva, a partir de tercer grado."],
          "Este es el cambio que pide el ensayo. La oración de los teclados es la otra postura, y las de las cartas y la tarjeta de cumpleaños son apoyo.",
        ],
      ),
      q(
        "argument.evidence",
        ["off-point-evidence", "off-point-evidence", "anecdote-as-proof"],
        [
          "Which detail best supports the claim that reading cursive is a useful skill?",
          "Family letters and many historical records are handwritten in cursive.",
          ["Students must learn to type well.", "The Common Core standards do not require cursive.", "The author's grandmother writes every birthday card in cursive, and the author can read less of it each year."],
          ["Being able to read cursive matters."],
          "Records that exist only in cursive are a lasting reason to read it. Typing and the Common Core are about other points, and one grandmother's cards are a single example.",
        ],
        [
          "¿Qué detalle apoya mejor la afirmación de que leer letra cursiva es una habilidad útil?",
          "Las cartas de familia y muchos documentos históricos están escritos a mano en cursiva.",
          ["Los estudiantes deben aprender a escribir bien en el teclado.", "Los estándares Common Core no exigen la cursiva.", "La abuela de quien escribe manda cada tarjeta de cumpleaños en cursiva, y cada año se le entiende un poco menos."],
          ["Saber leer letra cursiva importa."],
          "Los documentos que solo existen en cursiva son una razón duradera para saber leerla. El teclado y el Common Core tratan de otras ideas, y las tarjetas de una abuela son un solo ejemplo.",
        ],
      ),
      q(
        "argument.reasoning",
        ["not-a-flaw", "not-a-flaw", "not-a-flaw"],
        [
          "Which sentence relies on the weakest reasoning?",
          "Finally, if we stop teaching cursive, the next thing to go will be handwriting altogether, and soon students will not be able to sign their own names.",
          ["But the Common Core standards, adopted by most states after 2010, do not require it, and many schools dropped it to make room for typing and test preparation.", "It is true that students need to type well, and nothing about teaching cursive would change that.", "Family letters, diaries, and many historical records are handwritten in it."],
          ["the next thing to go will be handwriting altogether"],
          "Nothing in the essay shows that dropping cursive leads to dropping all handwriting. The sentence predicts a chain of worse and worse events without evidence for any step.",
        ],
        [
          "¿Qué oración se apoya en el razonamiento más débil?",
          "Por último, si dejamos de enseñar cursiva, lo siguiente en desaparecer será la escritura a mano por completo, y pronto los estudiantes no podrán firmar con su propio nombre.",
          ["Pero los estándares Common Core, que adoptó la mayoría de los estados después de 2010, no la exigen, y muchas escuelas la dejaron para hacerle lugar a la mecanografía y a la preparación para los exámenes.", "Es cierto que los estudiantes necesitan escribir bien en el teclado, y enseñar cursiva no cambiaría eso.", "Las cartas de familia, los diarios y muchos documentos históricos están escritos a mano en ella."],
          ["lo siguiente en desaparecer será la escritura a mano por completo"],
          "Nada en el ensayo muestra que dejar la cursiva lleve a dejar toda la escritura a mano. La oración predice una cadena de sucesos cada vez peores sin evidencia para ningún paso.",
        ],
      ),
      q(
        "pov.response",
        ["misses-author-stance", "contradicts-text", "contradicts-text"],
        [
          "How does the author respond to the claim that cursive is a waste of time?",
          "The author agrees that typing matters but argues that cursive takes little time and lasts a lifetime.",
          ["The author agrees that cursive wastes time and suggests replacing it with extra typing lessons in third grade.", "The author says typing is no longer a useful skill.", "The author never mentions this objection."],
          ["But cursive does not need to take much time."],
          "The author grants that students need to type, then answers the objection: a short daily lesson is enough, and the skill lasts.",
        ],
        [
          "¿Cómo responde quien escribe a la idea de que la letra cursiva es una pérdida de tiempo?",
          "Acepta que escribir en el teclado importa, pero argumenta que la cursiva toma poco tiempo y dura toda la vida.",
          ["Le da la razón, acepta que la cursiva es una pérdida de tiempo y propone cambiarla por más clases de mecanografía en tercer grado.", "Dice que escribir en el teclado ya no es una habilidad útil.", "Nunca menciona esa objeción."],
          ["Pero la cursiva no tiene que tomar mucho tiempo."],
          "Quien escribe acepta que los estudiantes necesitan el teclado y luego responde la objeción: basta una lección corta al día, y la habilidad dura.",
        ],
      ),
      q(
        "structure.section",
        ["wrong-section-role", "wrong-section-role", "not-in-text"],
        [
          "What is the role of paragraph 2?",
          "It gives background on why many schools stopped teaching cursive.",
          ["It answers the people who think cursive is a waste of time in a world of keyboards.", "It describes the author's grandmother's birthday cards.", "It argues that typing should not be taught in schools."],
          ["many schools dropped it to make room for typing and test preparation"],
          "Before giving reasons, the author explains how cursive disappeared: the Common Core did not require it, and schools made room for other things.",
        ],
        [
          "¿Qué función tiene el párrafo 2?",
          "Da los antecedentes de por qué muchas escuelas dejaron de enseñar cursiva.",
          ["Responde a quienes piensan que la cursiva es una pérdida de tiempo en un mundo de teclados.", "Describe las tarjetas de cumpleaños de la abuela de quien escribe.", "Defiende que no se debería enseñar mecanografía en las escuelas."],
          ["muchas escuelas la dejaron para hacerle lugar a la mecanografía y a la preparación para los exámenes"],
          "Antes de dar razones, quien escribe explica cómo desapareció la cursiva: el Common Core no la exigía, y las escuelas le hicieron lugar a otras cosas.",
        ],
      ),
    ],
  },
];
