import { type Passage, q } from "./types";

// Level 2 poems and imagined historical documents (each one says it is imagined).
export const L2_POEMS_PRIMARY: Passage[] = [
  {
    id: "snow-day",
    level: 2,
    genre: "poem",
    en: [
      {
        title: "Snow Day, Fourteen",
        paras: [
          "At six the radio says it: no school.\nMy brother hears it through the wall\nand is out of bed before the second sentence,\nhis face against the window, breathing\na small gray cloud onto the glass.",
          "I remember that feeling the way you remember\na song you used to know all the words to,\nthe tune still there, the words gone.\nI pull the blanket over my head.\nSnow means shoveling now. Snow means wet socks.",
          "When I was his age, the whole street\nwas a country no one had mapped yet.\nThe hill behind the church was a mountain.\nThe drift by the mailbox was a fort\nwith room inside for three.",
          "Somewhere between then and now\nthe mountain shrank back into a hill.\nI did not notice it happening.\nNo one sends a letter to tell you\nthat the world has gotten smaller.",
          "He knocks on my door four times,\nthen five, then without stopping.\nHe is holding two pairs of mittens,\none of them mine from years ago,\nthe thumbs worn thin from snowballs.",
          "So I go. I don't know why.\nThe cold slaps my face awake.\nHe throws himself backward into the yard\nand moves his arms and legs, and for a second\nI see the angel before he stands up.",
          "The hill behind the church is still a hill.\nBut halfway down, with my brother screaming\nand the sled spinning, and snow down my collar,\nit is, for about eight seconds,\na mountain again.",
        ],
      },
    ],
    es: [
      {
        title: "Día de nieve, a los catorce",
        paras: [
          "A las seis lo dice el radio: no hay clases.\nMi hermano lo oye a través de la pared\ny sale de la cama antes de la segunda frase,\ncon la cara pegada a la ventana, soltando\nuna nubecita gris sobre el vidrio.",
          "Recuerdo esa emoción como se recuerda\nuna canción que antes te sabías de memoria:\nla melodía sigue ahí, la letra ya no.\nMe tapo la cabeza con la cobija.\nLa nieve ahora es la pala. La nieve son calcetines mojados.",
          "Cuando yo tenía su edad, toda la calle\nera un país que nadie había explorado.\nLa loma detrás de la iglesia era una montaña.\nEl montón de nieve junto al buzón era un fuerte\ncon lugar adentro para tres.",
          "En algún momento entre aquel entonces y ahora\nla montaña se encogió hasta volver a ser loma.\nNo me di cuenta de cuándo pasó.\nNadie te manda una carta para avisarte\nque el mundo se hizo más pequeño.",
          "Toca a mi puerta cuatro veces,\nluego cinco, luego sin parar.\nTrae dos pares de guantes,\nuno de ellos mío, de hace años,\ncon los pulgares gastados de tanta bola de nieve.",
          "Así que voy. No sé por qué.\nEl frío me abofetea la cara hasta despertarme.\nÉl se tira de espaldas en el patio\ny mueve brazos y piernas, y por un segundo\nveo el ángel antes de que se levante.",
          "La loma detrás de la iglesia sigue siendo loma.\nPero a media bajada, con mi hermano gritando,\nel trineo dando vueltas y nieve en el cuello,\nes, durante unos ocho segundos,\nuna montaña otra vez.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "too-narrow", "contradicts-text"],
        [
          "Which statement best expresses a theme of the poem?",
          "Growing up can dull everyday wonder, but you can choose to find it again.",
          ["Snow days", "Old things, like a pair of worn mittens, can bring back memories.", "Growing older can shrink the world back to its real size, and it stays that way."],
          ["a mountain again."],
          "The speaker has lost the old excitement about snow, but going out with the brother brings it back for a few seconds. The poem suggests wonder can be found again.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del poema?",
          "Crecer puede apagar el asombro por lo cotidiano, pero uno puede elegir recuperarlo.",
          ["Días nevados", "Las cosas viejas, como unos guantes gastados, pueden traer recuerdos.", "Crecer puede devolver el mundo a su tamaño real, y así se queda."],
          ["una montaña otra vez."],
          "La voz poética perdió la emoción de antes por la nieve, pero salir con su hermano se la devuelve por unos segundos. El poema sugiere que el asombro se puede recuperar.",
        ],
      ),
      q(
        "theme.develop",
        ["contradicts-text", "too-narrow", "contradicts-text"],
        [
          "How does the final stanza develop the theme?",
          "It shows the speaker briefly recovering the wonder that seemed lost.",
          ["It shows that the hill has grown into a real mountain since the speaker was small.", "It describes the snow going down the speaker's collar.", "It reveals that the speaker stays inside while the brother sleds alone."],
          ["The hill behind the church is still a hill."],
          "The hill has not changed, but for a few seconds on the sled the speaker feels it as a mountain again. The wonder from stanza 3 returns, if only briefly.",
        ],
        [
          "¿Cómo desarrolla el mensaje la última estrofa del poema?",
          "Muestra que la voz poética recupera por un momento el asombro que parecía perdido.",
          ["Muestra que la loma creció hasta volverse una montaña de verdad desde que la voz poética era pequeña.", "Describe la nieve que le entra a la voz poética por el cuello.", "Revela que la voz poética se queda adentro mientras el hermano baja solo en trineo."],
          ["La loma detrás de la iglesia sigue siendo loma."],
          "La loma no cambió, pero por unos segundos en el trineo la voz poética la siente otra vez como una montaña. El asombro de la estrofa 3 vuelve, aunque sea un momento.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In stanza 2, the speaker compares the snow-day feeling to “a song you used to know all the words to.” What does this comparison suggest?",
          "The speaker remembers that the feeling exists but can no longer fully feel it.",
          ["The speaker used to sing songs about snow with the brother.", "The speaker still feels the snow-day excitement just as strongly as when they were little.", "The radio played a song when it announced the snow day."],
          ["the tune still there, the words gone."],
          "Half-remembering a song means the tune is there but the words are not. The speaker still recognizes the excitement but cannot feel it the way the brother does.",
        ],
        [
          "En la estrofa 2, la voz poética compara la emoción del día de nieve con “una canción que antes te sabías de memoria”. ¿Qué sugiere esta comparación?",
          "La voz poética recuerda que esa emoción existe, pero ya no puede sentirla del todo.",
          ["La voz poética cantaba canciones sobre la nieve con su hermano.", "La voz poética todavía siente la emoción del día de nieve con la misma fuerza que cuando era pequeña.", "El radio puso una canción cuando anunció el día de nieve."],
          ["la melodía sigue ahí, la letra ya no."],
          "Recordar a medias una canción es tener la melodía pero no la letra. La voz poética todavía reconoce la emoción, pero no puede sentirla como su hermano.",
        ],
      ),
      q(
        "words.connotation",
        ["too-literal", "opposite-tone", "not-in-text"],
        [
          "In stanza 6, the speaker says, “The cold slaps my face awake.” What does the word “slaps” suggest?",
          "The cold is a sudden shock that jolts the speaker out of a sleepy mood.",
          ["Someone in the yard hits the speaker in the face.", "The cold feels gentle and comforting.", "The speaker is angry at the brother for knocking on the door and waking them up so early."],
          ["The cold slaps my face awake."],
          "A slap is sharp and sudden. The word makes the cold feel like a jolt that wakes the speaker up, in body and in spirit, just before the joy of sledding.",
        ],
        [
          "En la estrofa 6, la voz poética dice: “El frío me abofetea la cara hasta despertarme”. ¿Qué sugiere la palabra “abofetea”?",
          "El frío es un golpe repentino que sacude a la voz poética y le quita el sueño.",
          ["Alguien en el patio le pega en la cara a la voz poética.", "El frío se siente suave y reconfortante.", "La voz poética está enojada con su hermano por tocar la puerta sin parar y despertarla tan temprano."],
          ["El frío me abofetea la cara hasta despertarme."],
          "Una bofetada es fuerte y repentina. La palabra hace que el frío se sienta como una sacudida que despierta a la voz poética, en el cuerpo y en el ánimo, justo antes de la alegría del trineo.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "Why does the brother bring two pairs of mittens, one of them the speaker's old pair?",
          "He wants the speaker to come out and play, the way the speaker used to.",
          ["He has lost his own mittens somewhere in the house and needs to borrow a pair.", "He plans to sell the old mittens at school.", "Little brothers always copy everything older siblings do."],
          ["the thumbs worn thin from snowballs"],
          "The old mittens are worn from the speaker's own snowball fights. Bringing them is the brother's way of inviting the speaker back to the fun they used to have.",
        ],
        [
          "¿Por qué el hermano trae dos pares de guantes, uno de ellos el par viejo de la voz poética?",
          "Quiere que la voz poética salga a jugar, como lo hacía antes.",
          ["Perdió sus guantes y necesita unos prestados.", "Piensa vender los guantes viejos en la escuela.", "Los hermanos menores siempre copian todo lo que hacen los mayores."],
          ["con los pulgares gastados de tanta bola de nieve"],
          "Los guantes viejos están gastados por las guerras de bolas de nieve de la voz poética. Traerlos es la manera en que el hermano la invita a volver a la diversión de antes.",
        ],
      ),
    ],
  },
  {
    id: "night-shift",
    level: 2,
    genre: "poem",
    en: [
      {
        title: "Night Shift",
        paras: [
          "While the city sleeps, it is being kept.\nA baker on Fulton Street\nis folding butter into dough\nfor bread you will eat without thinking\nabout the hands that made it at three a.m.",
          "A bus driver with a thermos of coffee\nruns the two o'clock route for four passengers,\nthree of them on their way to work\nand one on his way home,\nall of them asleep by the second stop.",
          "A nurse on the fifth floor\nchecks a stranger's heartbeat\nthe way you would check on a sleeping child,\nquietly, without turning on the light,\nand writes the number down.",
          "My mother is one of them.\nShe cleans the offices downtown,\nthe glass ones that shine in the morning\nas if they had cleaned themselves,\nas if the dark had done it.",
          "When I wake for school, she is coming home,\nher coat smelling of lemon soap and cold air.\nShe makes my breakfast standing up.\nShe asks about my test.\nShe has been awake for twenty hours.",
          "Tomorrow the people in the shining offices\nwill sit down at clean desks\nand never wonder who emptied the trash\nor wiped the fingerprints from the glass.\nThat is how she knows she did it right.",
          "But I wonder. I want to write her name\nacross every window in the city,\nnot in ink, but in light,\nso that when the sun comes up\nsomeone, for once, will read it.",
        ],
      },
    ],
    es: [
      {
        title: "Turno de noche",
        paras: [
          "Mientras la ciudad duerme, alguien la cuida.\nUn panadero de la calle Fulton\nva doblando mantequilla en la masa\npara un pan que comerás sin pensar\nen las manos que lo hicieron a las tres de la mañana.",
          "Un chofer de autobús con un termo de café\nhace la ruta de las dos de la mañana para cuatro pasajeros,\ntres que van a trabajar\ny uno que vuelve a casa,\ntodos dormidos antes de la segunda parada.",
          "Una enfermera del quinto piso\nrevisa el latido de un desconocido\ncomo quien revisa a un niño dormido,\ncon cuidado, sin prender la luz,\ny anota el número.",
          "Mi mamá es una de ellos.\nLimpia las oficinas del centro,\nlas de vidrio que brillan en la mañana\ncomo si se hubieran limpiado solas,\ncomo si lo hubiera hecho la oscuridad.",
          "Cuando me despierto para ir a la escuela, ella va llegando,\ncon el abrigo oliendo a jabón de limón y a aire frío.\nMe hace el desayuno de pie.\nMe pregunta por mi examen.\nLleva veinte horas despierta.",
          "Mañana la gente de las oficinas brillantes\nse sentará en escritorios limpios\ny nunca se preguntará quién vació la basura\nni quién borró las huellas del vidrio.\nAsí sabe ella que lo hizo bien.",
          "Pero yo me lo pregunto. Quiero escribir su nombre\nen todas las ventanas de la ciudad,\nno con tinta, sino con luz,\npara que cuando salga el sol\nalguien, por una vez, lo lea.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["plot-not-theme", "contradicts-text", "too-narrow"],
        [
          "Which statement best expresses a theme of the poem?",
          "The people who do unseen work deserve to be noticed and honored.",
          ["A baker, a bus driver, a nurse, and the speaker's mother all work while the city sleeps.", "Work done at night, out of sight, matters less than work done during the day.", "Good work can be so smooth that people forget who did it."],
          ["someone, for once, will read it."],
          "The poem moves from night workers in general to the speaker's mother, whose work no one notices, and ends with the wish to make her name seen. That wish carries the message.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del poema?",
          "Quienes hacen un trabajo invisible merecen que se les note y se les honre.",
          ["Un panadero, un chofer, una enfermera y la mamá de la voz poética trabajan mientras la ciudad duerme.", "El trabajo que se hace de noche, sin que se vea, importa menos que el que se hace de día.", "Un buen trabajo puede salir tan bien que la gente olvida quién lo hizo."],
          ["alguien, por una vez, lo lea."],
          "El poema pasa de los trabajadores de la noche en general a la mamá de la voz poética, cuyo trabajo nadie nota, y termina con el deseo de que su nombre se vea. Ese deseo lleva el mensaje.",
        ],
      ),
      q(
        "theme.develop",
        ["contradicts-text", "too-narrow", "not-in-text"],
        [
          "How does stanza 6 help develop the theme?",
          "It shows her best work goes unnoticed, setting up the wish to honor her.",
          ["It shows that the office workers thank the speaker's mother every morning when they arrive at their desks.", "It lists the trash and the fingerprints on the glass that she cleans every night.", "It argues that the office workers should empty their own trash and clean their own desks."],
          ["and never wonder who emptied the trash"],
          "In stanza 6, doing the job right means no one ever thinks about who did it. The next stanza answers that silence: the speaker wants her name written where everyone will see it.",
        ],
        [
          "¿Cómo ayuda la estrofa 6 a desarrollar el mensaje?",
          "Muestra que su mejor trabajo pasa desapercibido y prepara el deseo de honrarla.",
          ["Muestra que la gente de las oficinas le da las gracias a la mamá cada mañana, en cuanto llega a sus escritorios limpios.", "Enumera la basura y las huellas en el vidrio que ella limpia cada noche en las oficinas.", "Defiende que la gente de las oficinas debería vaciar su propia basura y limpiar sus escritorios."],
          ["y nunca se preguntará quién vació la basura"],
          "En la estrofa 6, hacer bien el trabajo significa que nadie piensa en quién lo hizo. La estrofa siguiente responde a ese silencio: la voz poética quiere escribir su nombre donde todos lo vean.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "contradicts-text"],
        [
          "In stanza 4, what does the speaker suggest by saying the offices shine “as if they had cleaned themselves”?",
          "The cleaning is so invisible that it seems to happen by itself.",
          ["The office buildings have machines that clean the glass automatically.", "The offices are dirty because no one cleans them.", "The speaker's mother is proud that everyone in the offices thanks her."],
          ["as if the dark had done it."],
          "No one sees the mother at work, so the clean offices seem to clean themselves overnight. The image shows how completely her work disappears from view.",
        ],
        [
          "En la estrofa 4, ¿qué sugiere la voz poética al decir que las oficinas brillan “como si se hubieran limpiado solas”?",
          "La limpieza es tan invisible que parece hacerse sola.",
          ["Los edificios tienen máquinas que limpian el vidrio automáticamente.", "Las oficinas están sucias porque nadie las limpia.", "La mamá está orgullosa de que todos en las oficinas le den las gracias."],
          ["como si lo hubiera hecho la oscuridad."],
          "Nadie ve a la mamá trabajar, así que las oficinas limpias parecen limpiarse solas durante la noche. La imagen muestra que su trabajo desaparece por completo de la vista.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In the last stanza, the speaker wants to write the mother's name “not in ink, but in light.” What does this suggest?",
          "The speaker wants her work to be seen as clearly as the morning sun.",
          ["The speaker plans to paint her name on the windows tonight.", "The speaker wants the mother's name to stay a secret.", "The speaker thinks the mother should find a job with brighter lighting."],
          ["so that when the sun comes up"],
          "Ink can be ignored, but light on every window cannot. The speaker wants the mother's work to be as visible as sunrise, the very time when no one thinks of her.",
        ],
        [
          "En la última estrofa, la voz poética quiere escribir el nombre de su mamá “no con tinta, sino con luz”. ¿Qué sugiere esto?",
          "Quiere que el trabajo de su mamá se vea tan claro como el sol de la mañana.",
          ["Piensa pintar el nombre de su mamá en las ventanas esta noche.", "Quiere que el nombre de su mamá se quede en secreto.", "Cree que su mamá debería buscar otro trabajo, en un lugar con mejor iluminación."],
          ["para que cuando salga el sol"],
          "La tinta se puede ignorar, pero la luz en cada ventana no. La voz poética quiere que el trabajo de su mamá sea tan visible como el amanecer, justo la hora en que nadie piensa en ella.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "What can you infer about the speaker's mother from stanza 5?",
          "She puts her family first even when she is exhausted.",
          ["She dislikes her job and plans to quit it soon.", "She sleeps all night before she makes breakfast.", "Every parent who works nights is too tired to talk."],
          ["She has been awake for twenty hours."],
          "After twenty hours awake, she still makes breakfast and asks about a test. Those details show how much she cares, even when she is worn out.",
        ],
        [
          "¿Qué puedes inferir sobre la mamá de la voz poética a partir de la estrofa 5?",
          "Pone primero a su familia, aun cuando está agotada de trabajar.",
          ["No le gusta su trabajo y piensa dejarlo pronto.", "Duerme toda la noche antes de hacer el desayuno.", "Los que trabajan de noche están muy cansados para hablar."],
          ["Lleva veinte horas despierta."],
          "Después de veinte horas despierta, todavía hace el desayuno y pregunta por un examen. Esos detalles muestran cuánto le importa su familia, aun cuando está agotada.",
        ],
      ),
    ],
  },
  {
    id: "two-tongues",
    level: 2,
    genre: "poem",
    en: [
      {
        title: "Two Tongues",
        paras: [
          "At home the kitchen speaks Spanish.\nThe pots say it, and the radio,\nand my grandmother, who calls me\nmi cielo, my sky,\nwhich in English sounds like a mistake.",
          "At school I raise my hand in English.\nI know the word for photosynthesis\nand the word for the Treaty of Paris,\nbut not the word, in either language,\nfor how it feels to switch at the door.",
          "For a while I thought I was half of each,\na sentence cut down the middle,\nnot enough Spanish for my cousins in Monterrey,\nnot enough English for the boy in fourth period\nwho asked me where I was really from.",
          "Then my grandmother taught me sobremesa,\nthe time after a meal when no one leaves,\nwhen the plates are empty and the talking is full.\nEnglish has no single word for it.\nI looked.",
          "And my English teacher taught me threshold,\nthe line you cross from one room to another,\nand I thought: that is where I live,\nnot half in each room,\nbut in the doorway, seeing both.",
          "Now when I switch at the door,\nI do not feel cut in half.\nI feel like someone carrying two keys,\nand every house I walk into\nhas one more room than it used to.",
        ],
      },
    ],
    es: [
      {
        title: "Dos lenguas",
        paras: [
          "En casa, la cocina habla español.\nLo dicen las ollas, y el radio,\ny mi abuela, que me dice mi cielo,\nalgo que en inglés, my sky,\nsuena a equivocación.",
          "En la escuela levanto la mano en inglés.\nSé cómo se dice fotosíntesis\ny Tratado de París,\npero no cómo se dice, en ninguno de los dos idiomas,\nlo que se siente cambiar en la puerta.",
          "Por un tiempo creí que era mitad y mitad,\nuna oración cortada por la mitad,\nsin suficiente español para mis primos de Monterrey,\nsin suficiente inglés para el chico de cuarta hora\nque me preguntó de dónde era en realidad.",
          "Entonces mi abuela me enseñó la sobremesa,\nese rato después de comer en que nadie se levanta,\ncuando los platos están vacíos y la plática está llena.\nEl inglés no tiene una sola palabra para eso.\nLa busqué.",
          "Y mi maestra de inglés me enseñó threshold,\nel umbral, la línea que cruzas de un cuarto a otro,\ny pensé: ahí es donde vivo,\nno mitad en cada cuarto,\nsino en la puerta, mirando los dos.",
          "Ahora, cuando cambio en la puerta,\nya no me siento partida en dos.\nMe siento como quien carga dos llaves,\ny cada casa a la que entro\ntiene un cuarto más que antes.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["plot-not-theme", "contradicts-text", "too-narrow"],
        [
          "Which statement best expresses a theme of the poem?",
          "Living between two languages adds to who you are instead of splitting you.",
          ["The speaker speaks Spanish at home and English at school and learns the words sobremesa and threshold.", "People who speak two languages may feel out of place in both.", "Some words in one language have no exact match in another."],
          ["I do not feel cut in half."],
          "The speaker first feels like half of each language, then comes to see living between them as having more, not less. That change carries the message.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del poema?",
          "Vivir entre dos idiomas te enriquece en lugar de partirte en dos.",
          ["La voz poética habla español en casa e inglés en la escuela, y aprende las palabras sobremesa y threshold.", "Quienes hablan dos idiomas pueden sentirse fuera de lugar en los dos.", "Algunas palabras de un idioma no tienen un equivalente exacto en otro."],
          ["ya no me siento partida en dos."],
          "Al principio la voz poética se siente mitad de cada idioma, y luego llega a ver que vivir entre los dos es tener más, no menos. Ese cambio lleva el mensaje.",
        ],
      ),
      q(
        "theme.develop",
        ["contradicts-text", "misses-the-change", "not-in-text"],
        [
          "How does the speaker's view of being bilingual change from stanza 3 to stanza 6?",
          "The speaker goes from feeling cut in half to feeling richer for both.",
          ["The speaker goes from feeling richer for having both languages to feeling like half of each.", "The speaker still feels like a sentence cut down the middle, even at the end.", "The speaker decides to speak only English, both at home and at school."],
          ["For a while I thought I was half of each", "I feel like someone carrying two keys"],
          "Stanza 3 describes feeling “cut down the middle.” By stanza 6 the same switch at the door makes the speaker feel like someone with two keys, which is a gain.",
        ],
        [
          "¿Cómo cambia, de la estrofa 3 a la estrofa 6, la manera en que la voz poética ve el hecho de hablar dos idiomas?",
          "Pasa de sentirse partida en dos a sentirse más rica por tener los dos.",
          ["Pasa de sentirse más rica por tener los dos idiomas a sentirse mitad de cada uno.", "Sigue sintiéndose como una oración cortada por la mitad, incluso al final.", "Decide hablar solo inglés, tanto en su casa como en la escuela, desde ese día."],
          ["Por un tiempo creí que era mitad y mitad", "Me siento como quien carga dos llaves"],
          "La estrofa 3 describe sentirse “cortada por la mitad”. Para la estrofa 6, el mismo cambio en la puerta hace que se sienta como quien carga dos llaves, lo que es una ganancia.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In stanza 3, the speaker describes feeling like “a sentence cut down the middle.” What does this metaphor suggest?",
          "The speaker felt incomplete, as if neither half made full sense alone.",
          ["The speaker made a grammar mistake in English class.", "The speaker felt completely at home in both languages.", "The speaker's cousins tore a letter in half."],
          ["not enough Spanish for my cousins in Monterrey"],
          "Half a sentence does not make sense by itself. The speaker felt “not enough” in each language, as if neither part was complete.",
        ],
        [
          "En la estrofa 3, la voz poética dice que se sentía como “una oración cortada por la mitad”. ¿Qué sugiere esta metáfora?",
          "Se sentía incompleta, como si ninguna mitad tuviera sentido por sí sola.",
          ["Cometió un error de gramática en la clase de inglés.", "Se sentía totalmente en casa en los dos idiomas.", "Sus primos rompieron una carta por la mitad."],
          ["sin suficiente español para mis primos de Monterrey"],
          "Media oración no tiene sentido por sí sola. La voz poética se sentía “sin suficiente” de cada idioma, como si ninguna parte estuviera completa.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "What does the image of “someone carrying two keys” suggest in the last stanza?",
          "Knowing two languages opens more of the world to the speaker.",
          ["The speaker carries keys to two different houses.", "The speaker feels locked out of both languages.", "The speaker worries about losing things at school."],
          ["has one more room than it used to"],
          "Keys open doors, and every house now has “one more room.” Two languages give the speaker access to more people and places, not less.",
        ],
        [
          "¿Qué sugiere la imagen de alguien que “carga dos llaves” en la última estrofa?",
          "Saber dos idiomas le abre más partes del mundo a la voz poética.",
          ["La voz poética lleva las llaves de dos casas distintas.", "La voz poética se siente excluida de los dos idiomas.", "A la voz poética le preocupa perder cosas en la escuela."],
          ["tiene un cuarto más que antes."],
          "Las llaves abren puertas, y ahora cada casa tiene “un cuarto más”. Dos idiomas le dan a la voz poética acceso a más personas y lugares, no a menos.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "Why does the speaker write “I looked” at the end of stanza 4?",
          "The speaker searched English for a matching word and found none.",
          ["The speaker looked at the empty plates after the meal.", "The speaker looked for the grandmother, who had left.", "No word in one language ever has a match in another."],
          ["English has no single word for it."],
          "Right before “I looked,” the speaker says English has no single word for sobremesa. The short line shows the speaker really searched and came up empty.",
        ],
        [
          "¿Por qué la voz poética escribe “La busqué” al final de la estrofa 4?",
          "Buscó en inglés una palabra equivalente y no encontró ninguna.",
          ["Miró los platos vacíos después de la comida.", "Buscó a su abuela, que se había levantado de la mesa.", "Ninguna palabra tiene nunca equivalente en otro idioma."],
          ["El inglés no tiene una sola palabra para eso."],
          "Justo antes de “La busqué”, la voz poética dice que el inglés no tiene una sola palabra para sobremesa. El verso corto muestra que de verdad la buscó y no la encontró.",
        ],
      ),
    ],
  },
  {
    id: "suffrage-speech",
    level: 2,
    genre: "primary",
    note: {
      en: "An imagined speech, written for this practice in the style of 1915. The speaker and the town are invented; the arguments are ones suffragists really made, and women in New York could not yet vote.",
      es: "Un discurso imaginado, escrito para esta práctica al estilo de 1915. La oradora y el pueblo son inventados; los argumentos son los que de verdad usaban las sufragistas, y las mujeres de Nueva York todavía no podían votar.",
    },
    en: [
      {
        title: "To the Voters of Cedar Hollow, October 1915",
        paras: [
          "Friends and neighbors of Cedar Hollow, I thank you for coming out on so cold an evening. Next month the men of this state will vote on whether the women of this state may vote. I have come to ask them to vote yes, and I have come to ask the rest of you to help me persuade them.",
          "We are told that a woman's place is in the home. I do not dispute that many of us spend our days there. But the home does not end at the front door. When the city allows milk to be sold that sickens our children, the home is harmed. When a factory works a girl of fourteen for ten hours a day, some mother's home is harmed. If our place is in the home, then we must have a voice in the laws that reach into it.",
          "We are told that women do not understand public questions. Yet women have had the vote in Wyoming since 1869, and in Colorado, California, and other western states since, and I have not heard that the sky has fallen there. The women of those states read the newspapers, study the candidates, and then go home and cook supper, just as I intend to do tonight.",
          "And we are told, most often of all, that we should be patient. Women in this country first asked for the vote in 1848, at Seneca Falls. The girls who heard that call are grandmothers now, or in their graves. How many more grandmothers must we make before our patience is rewarded?",
          "I do not ask you to believe that women are better than men. I ask only that you believe we are citizens. Citizens obey the laws, and citizens pay the taxes, and citizens, in a free country, help choose who makes the laws. On election day, I ask the men of Cedar Hollow to remember their mothers, their wives, and their daughters, and to vote yes.",
        ],
      },
    ],
    es: [
      {
        title: "A los votantes de Cedar Hollow, octubre de 1915",
        paras: [
          "Amigos y vecinos de Cedar Hollow, les agradezco que hayan salido en una noche tan fría. El mes que viene, los hombres de este estado votarán para decidir si las mujeres de este estado pueden votar. He venido a pedirles que voten que sí, y he venido a pedirles a los demás que me ayuden a convencerlos.",
          "Nos dicen que el lugar de la mujer es el hogar. No niego que muchas pasamos ahí nuestros días. Pero el hogar no termina en la puerta de la calle. Cuando la ciudad permite que se venda leche que enferma a nuestros hijos, el hogar sufre. Cuando una fábrica pone a trabajar a una niña de catorce años diez horas al día, el hogar de alguna madre sufre. Si nuestro lugar es el hogar, entonces debemos tener voz en las leyes que entran en él.",
          "Nos dicen que las mujeres no entienden los asuntos públicos. Sin embargo, las mujeres tienen el voto en Wyoming desde 1869, y después en Colorado, California y otros estados del oeste, y no he oído que allá se haya caído el cielo. Las mujeres de esos estados leen los periódicos, estudian a los candidatos y luego vuelven a casa a preparar la cena, igual que pienso hacer yo esta noche.",
          "Y nos dicen, más que nada, que tengamos paciencia. Las mujeres de este país pidieron el voto por primera vez en 1848, en Seneca Falls. Las niñas que oyeron ese llamado hoy son abuelas, o ya están en la tumba. ¿Cuántas abuelas más tenemos que hacer antes de que se premie nuestra paciencia?",
          "No les pido que crean que las mujeres somos mejores que los hombres. Solo les pido que crean que somos ciudadanas. Los ciudadanos obedecen las leyes, pagan los impuestos y, en un país libre, ayudan a elegir a quienes hacen las leyes. El día de la elección, les pido a los hombres de Cedar Hollow que se acuerden de sus madres, sus esposas y sus hijas, y que voten que sí.",
        ],
      },
    ],
    qs: [
      q(
        "pov.view",
        ["overstates-view", "confuses-speaker-author", "misses-author-stance"],
        [
          "What is the speaker's main point of view in the speech?",
          "Women are citizens and should have a voice in the laws that affect them.",
          ["Women are better than men and should make all of the laws themselves from now on.", "Women should stay home and leave public questions to men.", "The vote matters less than how well women run their homes and raise their children."],
          ["I ask only that you believe we are citizens."],
          "The speaker answers each objection and ends on one idea: women are citizens, and citizens help choose who makes the laws. She says plainly that she is not claiming women are better.",
        ],
        [
          "¿Cuál es el punto de vista principal de la oradora en el discurso?",
          "Las mujeres son ciudadanas y deben tener voz en las leyes que las afectan.",
          ["Las mujeres son mejores que los hombres y deberían hacer ellas solas todas las leyes.", "Las mujeres deben quedarse en casa y dejarles la política a los hombres.", "El voto importa menos que la manera en que las mujeres llevan su casa y crían a sus hijos."],
          ["Solo les pido que crean que somos ciudadanas."],
          "La oradora responde cada objeción y termina con una idea: las mujeres son ciudadanas, y los ciudadanos ayudan a elegir a quienes hacen las leyes. Dice claramente que no afirma que las mujeres sean mejores.",
        ],
      ),
      q(
        "pov.response",
        ["misses-author-stance", "contradicts-text", "not-in-text"],
        [
          "How does the speaker respond to the claim that “a woman's place is in the home”?",
          "She accepts part of it, then argues that the home's welfare depends on the laws.",
          ["She agrees that women belong at home and therefore should not vote or take part in public questions.", "She says that women no longer spend any time at home.", "She ignores the claim and talks only about taxes."],
          ["But the home does not end at the front door."],
          "She grants that many women spend their days at home, then turns the claim around: unsafe milk and child labor reach into the home, so women need a voice in those laws.",
        ],
        [
          "¿Cómo responde la oradora a la idea de que “el lugar de la mujer es el hogar”?",
          "Acepta una parte y luego argumenta que el bienestar del hogar depende de las leyes.",
          ["Está de acuerdo en que las mujeres deben quedarse en casa y, por eso, no deberían votar ni opinar sobre asuntos públicos.", "Dice que las mujeres ya no pasan nada de tiempo en casa.", "Ignora la idea y solo habla de los impuestos."],
          ["Pero el hogar no termina en la puerta de la calle."],
          "Acepta que muchas mujeres pasan el día en casa y luego le da la vuelta a la idea: la leche que enferma y el trabajo infantil entran en el hogar, así que las mujeres necesitan voz en esas leyes.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the speech?",
          "The speaker urges Cedar Hollow's men to vote yes on women's suffrage, answers three common objections, and argues that women, as citizens, deserve a voice in the laws.",
          ["The speaker gives a brilliant speech that proves the men who opposed suffrage were foolish, and every reader should admire her.", "The speaker mentions a cold evening, milk, a factory, Wyoming, Seneca Falls, grandmothers, and supper.", "The speaker asks women to stop asking for the vote and to wait patiently until men decide to offer it."],
          ["I have come to ask them to vote yes"],
          "A good summary names her goal, the three objections she answers, and her closing argument about citizenship, without praising or blaming anyone.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del discurso?",
          "La oradora pide a los hombres de Cedar Hollow que voten a favor del voto femenino, responde tres objeciones comunes y argumenta que las mujeres, como ciudadanas, merecen voz en las leyes.",
          ["La oradora da un discurso brillante que demuestra que los hombres que se oponían al voto femenino eran tontos, y todos deberían admirarla.", "La oradora menciona una noche fría, la leche, una fábrica, Wyoming, Seneca Falls, unas abuelas y la cena.", "La oradora les pide a las mujeres que dejen de pedir el voto y esperen con paciencia a que los hombres decidan ofrecérselo."],
          ["He venido a pedirles que voten que sí"],
          "Un buen resumen dice su meta, las tres objeciones que responde y su argumento final sobre la ciudadanía, sin elogiar ni culpar a nadie.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "Why does the speaker say that women in the West “go home and cook supper,” just as she will tonight?",
          "To show that women who vote still keep up the duties her listeners value.",
          ["To let the audience know that the meeting will end early.", "To complain that she still has to do all the cooking.", "To suggest that every woman in the state enjoys cooking."],
          ["just as I intend to do tonight"],
          "Some listeners fear that voting would pull women away from their homes. Mentioning supper shows them that women who vote still run their households.",
        ],
        [
          "¿Por qué la oradora dice que las mujeres del oeste “vuelven a casa a preparar la cena”, igual que ella esta noche?",
          "Para mostrar que las mujeres que votan siguen cumpliendo con los deberes que su público valora.",
          ["Para avisar al público que la reunión va a terminar temprano.", "Para quejarse de que todavía tiene que cocinar todo en su casa.", "Para sugerir que a todas las mujeres del estado les encanta cocinar."],
          ["igual que pienso hacer yo esta noche"],
          "Algunos oyentes temen que votar aleje a las mujeres de su casa. Mencionar la cena les muestra que las mujeres que votan siguen llevando su hogar.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "What does the speaker mean by “I have not heard that the sky has fallen there”?",
          "Nothing terrible has happened where women already vote.",
          ["The weather in the West has been mild this year.", "Women in the West have stopped reading the newspapers.", "She has not had time to read the news from the West."],
          ["Yet women have had the vote in Wyoming since 1869"],
          "“The sky is falling” describes a disaster that people fear. Women have voted in the West for years, and none of the disasters that opponents predicted has come.",
        ],
        [
          "¿Qué quiere decir la oradora con “no he oído que allá se haya caído el cielo”?",
          "No ha pasado nada terrible donde las mujeres ya votan.",
          ["En el oeste el clima ha sido templado este año.", "Las mujeres del oeste dejaron de leer los periódicos.", "No ha tenido tiempo de leer las noticias del oeste."],
          ["las mujeres tienen el voto en Wyoming desde 1869"],
          "Decir que “se cae el cielo” describe un desastre que la gente teme. Las mujeres llevan años votando en el oeste, y no ha llegado ninguno de los desastres que anunciaban sus opositores.",
        ],
      ),
    ],
  },
  {
    id: "ccc-letter",
    level: 2,
    genre: "primary",
    note: {
      en: "An imagined letter, written for this practice in the style of 1934. The writer is invented; the Civilian Conservation Corps, its camps, and its pay were real.",
      es: "Una carta imaginada, escrita para esta práctica al estilo de 1934. El autor es inventado; el Cuerpo Civil de Conservación, sus campamentos y su paga fueron reales.",
    },
    en: [
      {
        title: "A Letter from a CCC Camp, 1934",
        paras: [
          "Camp in the Idaho mountains, June 10, 1934. Dear Mother, I have been here a month now, and I am sorry I have not written sooner. They keep us busy from the bugle at six until lights out at ten, and by then my hand is too tired to hold a pencil. But today is Sunday, and it is raining, so here is your letter at last.",
          "You asked what the work is like. Mostly we plant trees, rows and rows of them, on a hillside that burned two summers ago. A crew of us can plant a thousand seedlings before supper. At first my back ached so that I walked like Grandpa, but now I hardly notice. We have also built a trail up to the fire lookout and a bridge over the creek, and the foreman says the bridge will outlast all of us.",
          "The food is plain but there is plenty of it, and I have gained eight pounds. The fellows come from everywhere: two farm boys from Kansas, a boy from New York who had never seen a cow, and a quiet Polish boy from Chicago who is teaching me chess. Some of the boys could not read when they came. In the evenings a teacher holds classes in the mess hall, and one of those boys, Eddie, read his first letter from home out loud last week. Nobody laughed. A few of us had to look at our shoes.",
          "I know the twenty-five dollars comes to you each month, since they send it straight home. Please use it for the rent and for shoes for the girls, and do not save any for me. I have everything I need here, and for the first time since Father lost his job, I feel I am of some use.",
          "When I look down the hill at the rows we planted, they are only knee-high and do not look like much. But the foreman says that in forty years this will be a forest again. I like to think that someday I will bring my own children here and tell them I planted it. Your loving son, Walter.",
        ],
      },
    ],
    es: [
      {
        title: "Una carta desde un campamento del CCC, 1934",
        paras: [
          "Campamento en las montañas de Idaho, 10 de junio de 1934. Querida mamá: Ya llevo un mes aquí, y perdón por no haberte escrito antes. Nos tienen ocupados desde el toque de corneta a las seis hasta que apagan las luces a las diez, y para entonces la mano ya no me da para sostener un lápiz. Pero hoy es domingo y está lloviendo, así que por fin aquí va tu carta.",
          "Me preguntaste cómo es el trabajo. Más que nada plantamos árboles, hileras y más hileras, en una ladera que se quemó hace dos veranos. Una cuadrilla puede plantar mil arbolitos antes de la cena. Al principio me dolía tanto la espalda que caminaba como el abuelo, pero ahora casi ni lo noto. También construimos un sendero hasta la torre de vigilancia de incendios y un puente sobre el arroyo, y el capataz dice que el puente nos va a sobrevivir a todos.",
          "La comida es sencilla pero abundante, y he subido ocho libras. Los muchachos vienen de todas partes: dos de granja de Kansas, uno de Nueva York que nunca había visto una vaca y un muchacho polaco de Chicago, muy callado, que me está enseñando ajedrez. Algunos no sabían leer cuando llegaron. En las noches, un maestro da clases en el comedor, y uno de esos muchachos, Eddie, leyó en voz alta su primera carta de casa la semana pasada. Nadie se rio. Algunos tuvimos que mirarnos los zapatos.",
          "Sé que cada mes te llegan los veinticinco dólares, porque los mandan directo a casa. Por favor, úsalos para la renta y para zapatos para las niñas, y no me guardes nada. Aquí tengo todo lo que necesito, y por primera vez desde que papá perdió su trabajo, siento que sirvo para algo.",
          "Cuando miro ladera abajo las hileras que plantamos, apenas me llegan a la rodilla y no parecen gran cosa. Pero el capataz dice que en cuarenta años esto volverá a ser un bosque. Me gusta pensar que algún día traeré a mis propios hijos aquí y les diré que yo lo planté. Tu hijo que te quiere, Walter.",
        ],
      },
    ],
    qs: [
      q(
        "pov.view",
        ["contradicts-text", "overstates-view", "misses-author-stance"],
        [
          "How does Walter feel about his time in the camp?",
          "The work is hard but gives him pride and purpose.",
          ["He hates the camp and wants to come home as soon as he can.", "He thinks every young man in the country should be forced to join.", "He cares more about the chess games than about the work."],
          ["I feel I am of some use"],
          "Walter admits the work made his back ache, but he is proud of the trees and the bridge and says he finally feels useful. His view is positive and honest about the hardship.",
        ],
        [
          "¿Qué siente Walter sobre su tiempo en el campamento?",
          "El trabajo es duro, pero le da orgullo y un propósito.",
          ["Odia el campamento y quiere volver a casa lo antes posible.", "Cree que a todos los jóvenes del país se les debería obligar a entrar.", "Le importan más las partidas de ajedrez que el trabajo."],
          ["siento que sirvo para algo"],
          "Walter admite que el trabajo le dolía en la espalda, pero está orgulloso de los árboles y del puente, y dice que por fin se siente útil. Su visión es positiva y honesta sobre lo duro.",
        ],
      ),
      q(
        "pov.purpose",
        ["contradicts-text", "not-in-text", "wrong-purpose"],
        [
          "Why does Walter tell his mother about Eddie reading his first letter?",
          "To show that the camp is changing the boys' lives in more ways than work.",
          ["To make fun of the boys in camp who could not read.", "To complain that the evening classes in the mess hall take time away from his sleep.", "To explain how the trail to the fire lookout was built."],
          ["Nobody laughed."],
          "Eddie's letter shows the camp teaching boys to read, and the boys' quiet respect shows what it meant. Walter wants his mother to see that the camp gives more than wages.",
        ],
        [
          "¿Por qué Walter le cuenta a su mamá que Eddie leyó su primera carta?",
          "Para mostrar que el campamento cambia la vida de los muchachos en algo más que el trabajo.",
          ["Para burlarse de los muchachos del campamento que no sabían leer.", "Para quejarse de que las clases de la noche en el comedor le quitan horas de sueño después del trabajo.", "Para explicar cómo se construyó el sendero hasta la torre de vigilancia."],
          ["Nadie se rio."],
          "La carta de Eddie muestra que el campamento enseña a leer, y el respeto callado de los muchachos muestra lo que eso significó. Walter quiere que su mamá vea que el campamento da más que un sueldo.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the letter?",
          "Walter tells his mother about planting trees and building, the boys he lives with, and the pay sent home, and says the work makes him feel useful.",
          ["The CCC was the greatest program in American history, and every government should copy it today.", "Walter mentions a bugle, rain, a fire lookout, a cow, chess, a mess hall, shoes, and knee-high trees.", "Walter writes that he is saving all of his pay so that he can buy a farm in Kansas."],
          ["Mostly we plant trees, rows and rows of them"],
          "A good summary covers the work, camp life, the pay, and Walter's feelings, without judging the program.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo de la carta?",
          "Walter le cuenta a su mamá sobre la plantación de árboles y las obras, los muchachos con los que vive y la paga que manda a casa, y le dice que el trabajo lo hace sentirse útil.",
          ["El Cuerpo Civil de Conservación fue el mejor programa de la historia del país, y todos los gobiernos deberían copiarlo hoy.", "Walter menciona una corneta, la lluvia, una torre de vigilancia, una vaca, el ajedrez, un comedor, unos zapatos y unos árboles que llegan a la rodilla.", "Walter escribe que está ahorrando toda su paga para comprar una granja en Kansas."],
          ["Más que nada plantamos árboles, hileras y más hileras"],
          "Un buen resumen cubre el trabajo, la vida en el campamento, la paga y los sentimientos de Walter, sin juzgar el programa.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "When Eddie reads his first letter aloud, Walter writes that a few of the boys “had to look at our shoes.” Why?",
          "They are moved and do not want it to show.",
          ["They are embarrassed for Eddie because he read badly.", "They are checking whether their boots dried after the rain.", "Young men in the camp are never allowed to show their feelings."],
          ["Nobody laughed."],
          "No one laughs at Eddie. Looking down at your shoes is what people do to hide tears or strong feelings, so the boys were touched by what he had done.",
        ],
        [
          "Cuando Eddie lee en voz alta su primera carta, Walter escribe que algunos “tuvimos que mirarnos los zapatos”. ¿Por qué?",
          "Están conmovidos y no quieren que se les note.",
          ["Les da vergüenza ajena por Eddie porque leyó muy mal.", "Están revisando si sus botas se secaron después de la lluvia.", "En el campamento nunca se les permite a los jóvenes mostrar sus sentimientos."],
          ["Nadie se rio."],
          "Nadie se ríe de Eddie. Mirarse los zapatos es lo que hace la gente para esconder las lágrimas o una emoción fuerte, así que a los muchachos los conmovió lo que él logró.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "not-in-text", "contradicts-text"],
        [
          "What does the foreman mean by saying the bridge “will outlast all of us”?",
          "It is built so well that it will still stand after the workers are gone.",
          ["The bridge is so long that it takes a whole day to cross.", "The workers will live on the bridge for the rest of their lives.", "The bridge is weak and will not last the summer."],
          ["We have also built a trail up to the fire lookout and a bridge over the creek"],
          "To outlast someone is to keep going after they are gone. The foreman is proud of the work: the bridge will stand longer than the young men who built it will live.",
        ],
        [
          "¿Qué quiere decir el capataz con que el puente “nos va a sobrevivir a todos”?",
          "Está tan bien hecho que seguirá en pie cuando los trabajadores ya no estén.",
          ["El puente es tan largo que cruzarlo toma un día entero.", "Los trabajadores van a vivir en el puente el resto de su vida.", "El puente es débil y no va a durar el verano."],
          ["También construimos un sendero hasta la torre de vigilancia de incendios y un puente sobre el arroyo"],
          "Sobrevivir a alguien es seguir aquí cuando esa persona ya no está. El capataz está orgulloso del trabajo: el puente durará más que la vida de los jóvenes que lo construyeron.",
        ],
      ),
    ],
  },
];
