import { type Passage, q } from "./types";

// Level 2 (grades 8–9) stories: more is implied than stated, and the turning points are quieter.
export const L2_STORIES: Passage[] = [
  {
    id: "interpreter",
    level: 2,
    genre: "story",
    en: [
      {
        title: "The Interpreter",
        paras: [
          "Lucía had been translating for her father since she was eight, when she learned the English word for “prescription” before she learned how to spell it. By fourteen she could turn a landlord's letter, a parking ticket, or a doctor's warning into Spanish without slowing down. So when Papá asked her to come with him to the credit union about a loan for a second food truck, she didn't think twice.",
          "The loan officer, Ms. Pratt, wore a gray suit and kept glancing at the clock behind them. She flipped through the folder Papá had spent three nights preparing: his tax returns, his permits, a photograph of the line outside his truck on a Friday night. “Food trucks are risky,” she said, without looking up. “Most of them don't last. Frankly, I'm not sure your father understands what he's asking for.”",
          "Lucía felt the words land in her stomach. She turned to her father and said, in Spanish, “She says the business is risky, and she wants to know if you have a plan for slow months.”",
          "Papá was quiet for a moment. Then, in careful English, he said, “Please. Tell me what she said. All of it.”",
          "Lucía stared at him. She had always assumed his English stopped at prices and greetings. She had never asked. Her face went hot. Slowly, she repeated Ms. Pratt's words exactly, even the last sentence.",
          "Papá nodded as if he had expected it. He opened the folder to a page Lucía had never seen, a list of every month for the past six years with what he had earned and spent, and he walked Ms. Pratt through it in Spanish, one month at a time, while Lucía translated every word. Halfway through, Ms. Pratt stopped looking at the clock.",
          "On the bus home, Papá said that she looked after him the way he had looked after her when she was small. “But I am not small, mija,” he added. Lucía looked out the window for a long time. She had been carrying his words for six years. She had never thought about how much he could carry himself.",
        ],
      },
    ],
    es: [
      {
        title: "La intérprete",
        paras: [
          "Lucía traducía para su padre desde los ocho años, cuando aprendió a decir “receta médica” en inglés antes de saber escribirlo. A los catorce podía pasar al español la carta de un casero, una multa de estacionamiento o la advertencia de un médico sin ir más despacio. Así que cuando papá le pidió que lo acompañara a la cooperativa de crédito para pedir un préstamo para un segundo camión de comida, ella no lo pensó dos veces.",
          "La encargada de préstamos, la señora Pratt, llevaba un traje gris y miraba una y otra vez el reloj que estaba detrás de ellos. Hojeó la carpeta que papá había pasado tres noches preparando: sus declaraciones de impuestos, sus permisos, una foto de la fila frente a su camión un viernes en la noche. —Los camiones de comida son un riesgo —dijo, sin levantar la vista—. La mayoría no dura. Francamente, no estoy segura de que su padre entienda lo que está pidiendo.",
          "Lucía sintió que las palabras le caían en el estómago. Se volvió hacia su padre y le dijo en español: —Dice que el negocio es arriesgado y quiere saber si tienes un plan para los meses flojos.",
          "Papá se quedó callado un momento. Luego, en un inglés cuidadoso, dijo: —Por favor. Dime lo que dijo. Todo.",
          "Lucía se le quedó mirando. Siempre había creído que el inglés de su padre no pasaba de los precios y los saludos. Nunca se lo había preguntado. Se le encendió la cara. Despacio, repitió las palabras de la señora Pratt tal cual, incluso la última oración.",
          "Papá asintió como si lo hubiera esperado. Abrió la carpeta en una página que Lucía nunca había visto, una lista de cada mes de los últimos seis años con lo que había ganado y gastado, y se la explicó a la señora Pratt en español, mes por mes, mientras Lucía traducía cada palabra. A la mitad, la señora Pratt dejó de mirar el reloj.",
          "En el autobús de regreso, papá le dijo que ella lo cuidaba como él la había cuidado de chiquita. —Pero yo no soy chiquito, mija —agregó. Lucía miró por la ventana un buen rato. Llevaba seis años cargando las palabras de su padre. Nunca había pensado en todo lo que él podía cargar solo.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "plot-not-theme", "not-in-text"],
        [
          "Which statement best expresses a theme of the story?",
          "Shielding people from hard truths can underestimate their strength.",
          ["Translation", "Lucía translates at a credit union, softens a loan officer's words, and then repeats them exactly when her father asks her to.", "Banks should give loans to every small business that asks."],
          ["She had never thought about how much he could carry himself."],
          "Lucía softens Ms. Pratt's words to protect her father, but he asks for all of it and handles it well. The story suggests that protecting someone can mean underestimating them.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "Proteger a alguien de una verdad dura puede ser subestimar su fuerza.",
          ["La traducción", "Lucía traduce en una cooperativa de crédito, suaviza las palabras de una encargada de préstamos y luego las repite tal cual cuando su padre se lo pide.", "Los bancos deberían darles préstamos a todos los negocios pequeños que los pidan."],
          ["Nunca había pensado en todo lo que él podía cargar solo."],
          "Lucía suaviza las palabras de la señora Pratt para proteger a su padre, pero él pide escucharlo todo y lo maneja bien. El cuento sugiere que proteger a alguien puede ser subestimarlo.",
        ],
      ),
      q(
        "theme.develop",
        ["misses-the-change", "wrong-character", "off-point-evidence"],
        [
          "Which moment marks the turning point in how Lucía sees her father?",
          "He asks, in careful English, to hear exactly what Ms. Pratt said.",
          ["She translates a landlord's letter and a parking ticket without slowing down.", "Ms. Pratt glances at the clock and calls food trucks risky.", "The two of them ride the bus home after the meeting at the credit union."],
          ["Please. Tell me what she said. All of it."],
          "Until then, Lucía assumes his English “stopped at prices and greetings.” His request shows he understood more than she knew, and she begins to see him differently.",
        ],
        [
          "¿Qué momento marca el cambio en cómo ve Lucía a su padre?",
          "Él pide, en un inglés cuidadoso, oír exactamente lo que dijo la señora Pratt.",
          ["Ella traduce la carta de un casero y una multa sin ir más despacio.", "La señora Pratt mira el reloj y dice que los camiones de comida son un riesgo.", "Los dos vuelven a casa en autobús después de la reunión en la cooperativa."],
          ["Por favor. Dime lo que dijo. Todo."],
          "Hasta entonces, Lucía cree que el inglés de su padre “no pasaba de los precios y los saludos”. Su petición muestra que entendía más de lo que ella sabía, y ella empieza a verlo de otra manera.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "What can you infer from the detail that “Ms. Pratt stopped looking at the clock”?",
          "Papá's careful records have won her real attention.",
          ["She has decided to end the meeting early because she is running late.", "She cannot follow the records because they are written in Spanish.", "Loan officers always forget the clock once a meeting runs long."],
          ["Halfway through, Ms. Pratt stopped looking at the clock."],
          "Earlier she kept glancing at the clock, which showed impatience. Stopping halfway through Papá's month-by-month records shows that he has her full attention.",
        ],
        [
          "¿Qué puedes inferir del detalle de que “la señora Pratt dejó de mirar el reloj”?",
          "Los registros cuidadosos de papá lograron captar de verdad su atención.",
          ["Decidió terminar la reunión antes porque se le hacía tarde.", "No puede seguir los registros porque están escritos en español.", "Quienes dan préstamos siempre se olvidan del reloj cuando una reunión se alarga."],
          ["A la mitad, la señora Pratt dejó de mirar el reloj."],
          "Antes miraba el reloj una y otra vez, lo que mostraba impaciencia. Dejar de hacerlo a la mitad de los registros de papá muestra que él tiene toda su atención.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "opposite-tone", "not-in-text"],
        [
          "In paragraph 3, Lucía feels Ms. Pratt's words “land in her stomach.” What does this phrase suggest?",
          "The words hurt her, like a blow she could feel.",
          ["She suddenly felt hungry during the long meeting.", "She was relieved that the meeting was going well.", "She had trouble hearing Ms. Pratt over the noise."],
          ["Frankly, I'm not sure your father understands what he's asking for."],
          "Ms. Pratt has just belittled her father. Feeling words “land” in your stomach describes a sick, punched feeling, so the phrase shows how much they hurt Lucía.",
        ],
        [
          "En el párrafo 3, Lucía siente que las palabras de la señora Pratt “le caían en el estómago”. ¿Qué sugiere esta frase?",
          "Las palabras la lastimaron, como un golpe que podía sentir.",
          ["De pronto le dio hambre durante la larga reunión en la cooperativa de crédito.", "Sintió alivio porque la reunión iba bien.", "Le costaba oír a la señora Pratt por el ruido."],
          ["Francamente, no estoy segura de que su padre entienda lo que está pidiendo."],
          "La señora Pratt acaba de menospreciar a su padre. Sentir que unas palabras te caen en el estómago describe un malestar, como un golpe, así que la frase muestra cuánto le dolieron a Lucía.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Translating at a loan meeting, Lucía softens an insult to her father. He asks for every word, presents his records, and tells her he can handle the truth.",
          ["Ms. Pratt is rude and unfair, and the credit union should never let someone like her decide which hardworking families deserve a loan for their business.", "Lucía rides a bus home after a meeting where she sees a gray suit, a clock on the wall, a folder, tax returns, permits, and a photograph of a long line outside a food truck.", "Lucía refuses to translate at the credit union, so her father has to leave without speaking to the loan officer."],
          ["Slowly, she repeated Ms. Pratt's words exactly, even the last sentence."],
          "A good summary includes the softened translation, Papá's request, his answer with the records, and what he tells Lucía, without judging anyone.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Al traducir en una reunión de préstamos, Lucía suaviza un comentario que menosprecia a su padre. Él pide oír cada palabra, presenta sus registros y le dice que puede con la verdad.",
          ["La señora Pratt es grosera e injusta, y la cooperativa nunca debería dejar que alguien como ella decida qué familias trabajadoras merecen un préstamo para su negocio.", "Lucía regresa en autobús después de una reunión en la que ve un traje gris, un reloj en la pared, una carpeta, declaraciones de impuestos, permisos y la foto de una fila larga frente a un camión de comida.", "Lucía se niega a traducir en la cooperativa, así que su padre tiene que irse sin hablar con la encargada de préstamos."],
          ["Despacio, repitió las palabras de la señora Pratt tal cual, incluso la última oración."],
          "Un buen resumen incluye la traducción suavizada, la petición de papá, su respuesta con los registros y lo que le dice a Lucía, sin juzgar a nadie.",
        ],
      ),
    ],
  },
  {
    id: "radio-hands",
    level: 2,
    genre: "story",
    en: [
      {
        title: "What the Hands Remember",
        paras: [
          "The doctor called it memory loss, which made it sound like something Ông had misplaced, like his reading glasses. But it was more like a tide going out. Some days it took the names of the street and the month. Lately it had started taking Minh's.",
          "“Who are you?” Ông asked one Saturday, politely, the way you would ask a stranger on a bus. Minh had answered that question four times that week. He felt the old ache rise in his throat, and he went to his room and shut the door.",
          "That afternoon his mother brought home a broken radio from a yard sale, a brown plastic box with a cracked dial, and set it on the kitchen table. “Your grandfather fixed radios for thirty years,” she said. “Before you were born. Before he came here.”",
          "Minh didn't expect anything. But when he unscrewed the back panel, Ông leaned over his shoulder and made a small sound, the sound of someone recognizing a face. He pointed, with a finger that shook only a little, to a thin wire that had come loose. “There,” he said. “Always it is the simple thing.”",
          "For two hours they worked side by side. Ông could not have told anyone what day it was, but his hands knew exactly how to hold the soldering iron and how long to wait before touching the joint. Minh held the flashlight and passed him the tools and asked questions, and Ông answered every one.",
          "When the radio crackled to life, playing an old song in a language Minh only half understood, Ông laughed. Then he looked at Minh, really looked, and said, “You have good hands. Whose boy are you?”",
          "A week ago, the question would have hurt. Now Minh only smiled and handed him the screwdriver. “Yours,” he said. “Let's fix another one.”",
        ],
      },
    ],
    es: [
      {
        title: "Lo que recuerdan las manos",
        paras: [
          "El médico lo llamó pérdida de memoria, como si fuera algo que Ông hubiera dejado en otro lado, igual que sus lentes. Pero se parecía más a la marea cuando baja. Algunos días se llevaba los nombres de la calle y del mes. Últimamente había empezado a llevarse el de Minh.",
          "—¿Quién eres tú? —le preguntó Ông un sábado, con amabilidad, como se le pregunta algo a un desconocido en el autobús. Minh había contestado esa pregunta cuatro veces esa semana. Sintió que el dolor de siempre le subía a la garganta, se fue a su cuarto y cerró la puerta.",
          "Esa tarde, su mamá llegó con un radio descompuesto de una venta de garaje, una caja de plástico café con la perilla rajada, y lo puso en la mesa de la cocina. —Tu abuelo arregló radios durante treinta años —le dijo—. Antes de que nacieras. Antes de venir aquí.",
          "Minh no esperaba nada. Pero cuando desatornilló la tapa de atrás, Ông se inclinó sobre su hombro e hizo un ruidito, el ruido de alguien que reconoce una cara. Señaló, con un dedo que apenas temblaba, un cable delgado que se había soltado. —Ahí —dijo—. Siempre es lo sencillo.",
          "Durante dos horas trabajaron lado a lado. Ông no habría podido decirle a nadie qué día era, pero sus manos sabían exactamente cómo sostener el cautín y cuánto esperar antes de tocar la soldadura. Minh sostenía la linterna, le pasaba las herramientas y le hacía preguntas, y Ông las contestaba todas.",
          "Cuando el radio volvió a la vida con un chisporroteo y tocó una canción vieja en un idioma que Minh entendía a medias, Ông se rio. Luego miró a Minh, lo miró de verdad, y le dijo: —Tienes buenas manos. ¿Y tú de quién eres, muchacho?",
          "Una semana antes, la pregunta le habría dolido. Ahora Minh solo sonrió y le pasó el desarmador. —Tuyo —le dijo—. Vamos a arreglar otro.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "plot-not-theme", "contradicts-text"],
        [
          "Which statement best expresses a theme of the story?",
          "A bond can survive memory loss if you accept a person as they are now.",
          ["Memory loss", "Minh and his grandfather repair a broken radio from a yard sale and hear an old song.", "Once someone forgets your name, the relationship cannot be repaired."],
          ["Now Minh only smiled and handed him the screwdriver."],
          "Ông cannot remember Minh's name, but working on the radio gives them a way to be together. By the end, Minh accepts the question and chooses to keep connecting.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "El lazo con alguien puede sobrevivir a la pérdida de memoria si lo aceptas como es ahora.",
          ["El olvido", "Minh y su abuelo arreglan un radio descompuesto de una venta de garaje y oyen una canción vieja.", "Cuando alguien olvida tu nombre, la relación ya no se puede reparar."],
          ["Ahora Minh solo sonrió y le pasó el desarmador."],
          "Ông no recuerda el nombre de Minh, pero arreglar el radio les da una manera de estar juntos. Al final, Minh acepta la pregunta y elige seguir conectando con él.",
        ],
      ),
      q(
        "theme.develop",
        ["misses-the-change", "wrong-character", "not-in-text"],
        [
          "How does Minh's response to the question “Whose boy are you?” show that he has changed?",
          "He smiles and keeps working instead of leaving hurt, as he did before.",
          ["He goes to his room and shuts the door, as he did earlier that Saturday.", "Ông laughs when the radio plays an old song.", "He reminds his grandfather of his name and of the date."],
          ["A week ago, the question would have hurt."],
          "Earlier, being forgotten sent Minh to his room. Now the same kind of question makes him smile and invite his grandfather to keep working, which shows he has accepted Ông as he is.",
        ],
        [
          "¿Cómo muestra la respuesta de Minh a la pregunta “¿Y tú de quién eres, muchacho?” que él ha cambiado?",
          "Sonríe y sigue trabajando, en lugar de irse dolido como antes.",
          ["Se va a su cuarto y cierra la puerta, como hizo antes ese sábado.", "Ông se ríe cuando el radio toca una canción vieja.", "Le recuerda a su abuelo su nombre y la fecha de ese día."],
          ["Una semana antes, la pregunta le habría dolido."],
          "Antes, que lo olvidaran mandaba a Minh a su cuarto. Ahora la misma pregunta lo hace sonreír e invitar a su abuelo a seguir trabajando, lo que muestra que acepta a Ông como es.",
        ],
      ),
      q(
        "infer.support",
        ["off-point-evidence", "off-point-evidence", "off-point-evidence"],
        [
          "Which sentence best supports the inference that Ông's skill has outlasted his memory?",
          "Ông could not have told anyone what day it was, but his hands knew exactly how to hold the soldering iron and how long to wait before touching the joint.",
          ["Some days it took the names of the street and the month.", "When the radio crackled to life, playing an old song in a language Minh only half understood, Ông laughed.", "He felt the old ache rise in his throat, and he went to his room and shut the door."],
          ["his hands knew exactly how to hold the soldering iron"],
          "The sentence sets what Ông has lost, the day of the week, against what remains, the exact skill in his hands. That contrast is the proof.",
        ],
        [
          "¿Qué oración apoya mejor la inferencia de que la habilidad de Ông ha durado más que su memoria?",
          "Ông no habría podido decirle a nadie qué día era, pero sus manos sabían exactamente cómo sostener el cautín y cuánto esperar antes de tocar la soldadura.",
          ["Algunos días se llevaba los nombres de la calle y del mes.", "Cuando el radio volvió a la vida con un chisporroteo y tocó una canción vieja en un idioma que Minh entendía a medias, Ông se rio.", "Sintió que el dolor de siempre le subía a la garganta, se fue a su cuarto y cerró la puerta."],
          ["sus manos sabían exactamente cómo sostener el cautín"],
          "La oración pone lo que Ông perdió, el día de la semana, frente a lo que conserva, la habilidad exacta de sus manos. Ese contraste es la prueba.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In paragraph 1, the narrator says memory loss is “more like a tide going out.” What does this comparison suggest?",
          "The loss is gradual and keeps pulling more away.",
          ["Ông lost his memory at the beach during a storm.", "Ông's memory will soon return all at once and stay.", "Ông likes to watch the ocean from his window."],
          ["Lately it had started taking Minh's."],
          "A tide going out pulls the water back a little at a time. The comparison shows Ông's memory slipping away gradually: first street names, then months, now Minh's name.",
        ],
        [
          "En el párrafo 1, el narrador dice que la pérdida de memoria “se parecía más a la marea cuando baja”. ¿Qué sugiere esta comparación?",
          "La pérdida es gradual y se va llevando cada vez más.",
          ["Ông perdió la memoria en la playa durante una tormenta.", "La memoria de Ông pronto volverá de golpe y se quedará.", "A Ông le gusta mirar el mar desde su ventana."],
          ["Últimamente había empezado a llevarse el de Minh."],
          "Cuando la marea baja, se lleva el agua poco a poco. La comparación muestra que la memoria de Ông se va de a poco: primero los nombres de las calles, luego los meses y ahora el nombre de Minh.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Hurt that his grandfather no longer knows him, Minh finds they can still connect by repairing a radio together, and he accepts Ông as he is now.",
          ["Minh is a selfish grandson who should have been far more patient with his grandfather from the very first time Ông asked who he was.", "Minh's mother buys a brown plastic radio with a cracked dial at a yard sale, and after two hours of work at the kitchen table it plays an old song.", "Ông's memory comes back while he fixes the radio, and he finally remembers Minh's name."],
          ["For two hours they worked side by side."],
          "A good summary includes Minh's hurt, the radio that brings them together, and his new acceptance at the end, with no judgment added.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Dolido porque su abuelo ya no lo reconoce, Minh descubre que todavía pueden conectar arreglando juntos un radio, y acepta a Ông como es ahora.",
          ["Minh es un nieto egoísta que debió tener mucha más paciencia con su abuelo desde la primera vez que Ông le preguntó quién era.", "La mamá de Minh compra en una venta de garaje un radio de plástico café con la perilla rajada, y después de dos horas de trabajo en la mesa de la cocina toca una canción vieja.", "Ông recupera la memoria mientras arregla el radio y por fin recuerda el nombre de Minh."],
          ["Durante dos horas trabajaron lado a lado."],
          "Un buen resumen incluye el dolor de Minh, el radio que los une y su nueva aceptación al final, sin agregar juicios.",
        ],
      ),
    ],
  },
  {
    id: "rumor-snowball",
    level: 2,
    genre: "story",
    en: [
      {
        title: "The Snowball",
        paras: [
          "It began with one sentence at lunch, and Daniela would later remember how small it had felt. Someone asked why Priscilla had skipped soccer tryouts, and Daniela shrugged. “Maybe she thinks she's too good for us now that she plays club,” she said. A few people laughed. Daniela laughed too, though she had no idea why Priscilla had stayed home.",
          "By Wednesday the sentence had grown. In the hallway, Daniela heard a sixth grader say that Priscilla had called the school team “a joke.” By Thursday, someone claimed she had said it to the coach's face. Each version arrived a little bigger and a little meaner, like a snowball rolling downhill, and none of them came back to Daniela with her name on it.",
          "On Friday, Daniela found Priscilla alone at the end of the bleachers. Her eyes were red. Her grandmother had been in the hospital the day of tryouts, she said, and she had spent the afternoon in a waiting room doing homework on her knees. Now half the team would not sit with her.",
          "Daniela could have said nothing. No one knew where the story had started. That was the strange part: the rumor had spread so far from her that it no longer seemed to belong to her at all. But she knew.",
          "“I started it,” she said, and the words came out smaller than she meant them to. “The part about you thinking you're too good. I made it up. I'm going to tell people.”",
          "Priscilla looked at her for a long time. “You can tell them,” she said finally. “I don't know if it'll matter.”",
          "Daniela told everyone she could find: her lunch table, the team captain, the sixth grader in the hallway. Some people believed her. Some had already moved on to other stories. The rumor never completely disappeared. But on Monday, when Priscilla sat down at the end of the bleachers, Daniela sat next to her, and after a minute, Priscilla let her stay.",
        ],
      },
    ],
    es: [
      {
        title: "La bola de nieve",
        paras: [
          "Empezó con una sola frase en el almuerzo, y Daniela recordaría después lo pequeña que le había parecido. Alguien preguntó por qué Priscilla había faltado a las pruebas de fútbol, y Daniela se encogió de hombros y dijo que a lo mejor ya se creía demasiado buena para ellas, ahora que jugaba en un club. Algunas se rieron. Daniela también se rio, aunque no tenía idea de por qué Priscilla se había quedado en casa.",
          "Para el miércoles, la frase había crecido. En el pasillo, Daniela oyó a una de sexto decir que Priscilla había llamado al equipo de la escuela “un chiste”. Para el jueves, alguien aseguraba que se lo había dicho en la cara a la entrenadora. Cada versión llegaba un poco más grande y un poco más cruel, como una bola de nieve que rueda cuesta abajo, y ninguna volvía a Daniela con su nombre.",
          "El viernes, Daniela encontró a Priscilla sola en la punta de las gradas. Tenía los ojos rojos. Le contó que su abuela había estado en el hospital el día de las pruebas y que ella había pasado la tarde en una sala de espera, haciendo la tarea sobre las rodillas. Ahora la mitad del equipo no se sentaba con ella.",
          "Daniela pudo no haber dicho nada. Nadie sabía dónde había empezado la historia. Eso era lo raro: el rumor se había alejado tanto de ella que ya ni parecía suyo. Pero ella lo sabía.",
          "—Yo lo empecé —dijo, y las palabras le salieron más bajito de lo que quería—. Lo de que te crees demasiado buena. Me lo inventé. Voy a decírselo a todas.",
          "Priscilla la miró un largo rato. —Puedes decírselo —dijo por fin—. No sé si vaya a servir de algo.",
          "Daniela se lo dijo a todas las que pudo encontrar: a su mesa del almuerzo, a la capitana del equipo, a la de sexto del pasillo. Algunas le creyeron. Otras ya andaban con otras historias. El rumor nunca desapareció del todo. Pero el lunes, cuando Priscilla se sentó en la punta de las gradas, Daniela se sentó a su lado, y después de un minuto, Priscilla la dejó quedarse.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "plot-not-theme", "contradicts-text"],
        [
          "Which statement best expresses a theme of the story?",
          "Careless words can spread beyond your control, but you are still responsible for them.",
          ["Gossip", "Daniela makes up a reason Priscilla skipped tryouts, and the story grows until half the team avoids her.", "People who start rumors are always found out in the end."],
          ["That was the strange part: the rumor had spread so far from her that it no longer seemed to belong to her at all."],
          "No one could trace the rumor back to Daniela, yet she chooses to own it and repair what she can. The story shows that responsibility does not depend on getting caught.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "Las palabras descuidadas pueden escaparse de tu control, pero sigues siendo responsable de ellas.",
          ["Los chismes", "Daniela inventa por qué Priscilla faltó a las pruebas, y la historia crece hasta que la mitad del equipo la evita.", "Quienes empiezan un rumor siempre terminan descubiertos."],
          ["Eso era lo raro: el rumor se había alejado tanto de ella que ya ni parecía suyo."],
          "Nadie podía saber que el rumor salió de Daniela, y aun así ella decide hacerse cargo y reparar lo que puede. El cuento muestra que la responsabilidad no depende de que te descubran.",
        ],
      ),
      q(
        "theme.develop",
        ["misses-the-change", "wrong-character", "off-point-evidence"],
        [
          "Which detail best shows that Daniela takes responsibility for what she said?",
          "She admits to Priscilla that she made up the claim and tells others the truth.",
          ["She laughs along with the others at lunch when people react to her comment about Priscilla.", "Priscilla's eyes are red when Daniela finds her at the end of the bleachers.", "A sixth grader says that Priscilla called the team “a joke.”"],
          ["Daniela told everyone she could find"],
          "No one could trace the story to Daniela, yet she confesses to Priscilla and then corrects it with everyone she can find. That is taking responsibility.",
        ],
        [
          "¿Qué detalle muestra mejor que Daniela se hace responsable de lo que dijo?",
          "Le confiesa a Priscilla que inventó lo que dijo y les cuenta la verdad a las demás.",
          ["Se ríe con las demás en el almuerzo cuando reaccionan a su comentario.", "Priscilla tiene los ojos rojos cuando Daniela la encuentra en la punta de las gradas.", "Una de sexto dice que Priscilla llamó al equipo “un chiste”."],
          ["Daniela se lo dijo a todas las que pudo encontrar"],
          "Nadie podía saber que la historia salió de Daniela, y aun así le confiesa la verdad a Priscilla y luego la corrige con todas las que encuentra. Eso es hacerse responsable.",
        ],
      ),
      q(
        "words.figurative",
        ["too-literal", "contradicts-text", "not-in-text"],
        [
          "In paragraph 2, the versions of the story arrive “like a snowball rolling downhill.” What does this simile suggest?",
          "The rumor grew bigger and harder to stop as it spread.",
          ["The rumor started during a winter snowstorm at school.", "The rumor got smaller and weaker each time it was told.", "The rumor reached Daniela's friends before anyone else."],
          ["Each version arrived a little bigger and a little meaner"],
          "A snowball rolling downhill picks up snow and speed. The simile shows the rumor growing larger and meaner as more people repeated it.",
        ],
        [
          "En el párrafo 2, las versiones de la historia llegan “como una bola de nieve que rueda cuesta abajo”. ¿Qué sugiere este símil?",
          "El rumor se hacía más grande y más difícil de detener al extenderse.",
          ["El rumor empezó durante una tormenta de nieve en la escuela.", "El rumor se hacía más pequeño y más débil cada vez que se contaba.", "El rumor llegó a las amigas de Daniela antes que a cualquier otra persona de la escuela."],
          ["Cada versión llegaba un poco más grande y un poco más cruel"],
          "Una bola de nieve que rueda cuesta abajo junta más nieve y más velocidad. El símil muestra que el rumor se hacía más grande y más cruel a medida que más gente lo repetía.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "Why does Priscilla say, “I don't know if it'll matter”?",
          "She doubts the truth can undo a story that has already spread so far.",
          ["She no longer cares what her teammates think of her.", "She plans to ask the coach to remove Daniela from the team as soon as practice starts.", "No one ever believes the truth once a rumor starts."],
          ["Some had already moved on to other stories."],
          "Priscilla has watched the story grow all week. Her doubt turns out to be partly right: some people believe Daniela, but the rumor never completely disappears.",
        ],
        [
          "¿Por qué Priscilla dice: “No sé si vaya a servir de algo”?",
          "Duda que la verdad pueda deshacer una historia que ya llegó tan lejos.",
          ["Ya no le importa lo que piensen sus compañeras de equipo.", "Piensa pedirle a la entrenadora que saque a Daniela del equipo en cuanto empiece la práctica.", "Nadie cree nunca la verdad una vez que empieza un rumor."],
          ["Otras ya andaban con otras historias."],
          "Priscilla vio crecer la historia toda la semana. Su duda resulta en parte cierta: algunas le creen a Daniela, pero el rumor nunca desaparece del todo.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Daniela invents a reason for Priscilla's absence, and the rumor grows until Priscilla is shunned. After learning the real reason, Daniela confesses and works to correct the story.",
          ["Daniela is a terrible friend, and Priscilla should never forgive her for starting such a cruel and careless rumor at lunch in front of everyone on the team, no matter how sorry she says she is.", "A sixth grader, a hallway, a coach, a waiting room, a grandmother in the hospital, and bleachers all appear in the story.", "Priscilla starts a rumor about Daniela, and the two girls stop speaking for the rest of the season."],
          ["Her grandmother had been in the hospital the day of tryouts"],
          "A good summary includes the invented claim, how it spread and hurt Priscilla, the real reason she missed tryouts, and what Daniela does about it, without judging anyone.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Daniela inventa una razón para la ausencia de Priscilla, y el rumor crece hasta que la apartan. Al saber la verdadera razón, Daniela confiesa e intenta corregir la historia.",
          ["Daniela es una pésima amiga, y Priscilla nunca debería perdonarla por empezar un rumor tan cruel y descuidado en el almuerzo delante de todo el equipo, por mucho que diga que lo siente.", "En el cuento aparecen una de sexto, un pasillo, una entrenadora, una sala de espera, una abuela en el hospital y unas gradas.", "Priscilla empieza un rumor sobre Daniela, y las dos dejan de hablarse el resto de la temporada."],
          ["su abuela había estado en el hospital el día de las pruebas"],
          "Un buen resumen incluye lo que Daniela inventó, cómo se extendió y lastimó a Priscilla, la verdadera razón de su ausencia y lo que Daniela hace al respecto, sin juzgar a nadie.",
        ],
      ),
    ],
  },
  {
    id: "ninety-first",
    level: 2,
    genre: "story",
    en: [
      {
        title: "Ninety-First",
        paras: [
          "There were ninety-four runners in the girls' race at the county championship, and Wren Castillo had never finished in the top half of anything. She was the slowest runner on the Eastside team. Everyone knew it, including Wren, who had stopped minding the way you stop noticing a scar.",
          "What no one else knew about was the notebook. Since August, Wren had written down every race time in pencil on the last page of her math notebook: 31:12, 30:48, 30:21, 29:58. Most of the numbers were worse than her teammates' slowest days. But the column was moving, slowly, in one direction.",
          "At the two-mile mark, a girl from Westfield passed her, breathing hard, and Wren felt the old urge to let her go. Instead she thought about the column. She did not try to catch the Westfield girl. She tried to beat 29:58.",
          "She crossed the line ninety-first. The clock beside the finish read 29:17.",
          "Near the team tent, her teammates were miserable. Jada had finished twelfth and missed a medal by two places. Sofia had fallen near the creek and cried the whole way back. Their coach was saying something about next year. Nobody asked Wren where she had placed, and she did not say.",
          "On the bus home, Jada noticed the notebook open on Wren's knees and leaned over. “Twenty-nine seventeen,” she read. “Is that good?”",
          "Wren thought about it. Ninety-first out of ninety-four was not good, not by any measure the county used. But it was forty-one seconds faster than her best race before today.",
          "“It's the best I've ever done,” she said, and wrote it down.",
        ],
      },
    ],
    es: [
      {
        title: "Lugar noventa y uno",
        paras: [
          "En la carrera femenil del campeonato del condado había noventa y cuatro corredoras, y Wren Castillo nunca había terminado en la mitad de arriba de nada. Era la corredora más lenta del equipo de Eastside. Todos lo sabían, incluida Wren, que había dejado de darle importancia como uno deja de fijarse en una cicatriz.",
          "Lo que nadie más sabía era lo del cuaderno. Desde agosto, Wren anotaba a lápiz cada tiempo de carrera en la última página de su cuaderno de matemáticas: 31:12, 30:48, 30:21, 29:58. Casi todos los números eran peores que los peores días de sus compañeras. Pero la columna se movía, despacio, en una sola dirección.",
          "En la marca de las dos millas, una chica de Westfield la rebasó, respirando fuerte, y Wren sintió las ganas de siempre de dejarla ir. En cambio, pensó en la columna. No intentó alcanzar a la chica de Westfield. Intentó ganarle a 29:58.",
          "Cruzó la meta en el lugar noventa y uno. El reloj junto a la meta marcaba 29:17.",
          "Cerca de la carpa del equipo, sus compañeras estaban deshechas. Jada había llegado en el lugar doce y se quedó sin medalla por dos lugares. Sofía se había caído cerca del arroyo y lloró todo el camino de regreso. La entrenadora decía algo sobre el año siguiente. Nadie le preguntó a Wren en qué lugar había llegado, y ella no lo dijo.",
          "En el autobús de regreso, Jada vio el cuaderno abierto sobre las rodillas de Wren y se asomó. —Veintinueve diecisiete —leyó—. ¿Eso es bueno?",
          "Wren lo pensó. El lugar noventa y uno de noventa y cuatro no era bueno, no según ninguna medida del condado. Pero eran cuarenta y un segundos menos que su mejor carrera hasta ese día.",
          "—Es lo mejor que he hecho —dijo, y lo anotó.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "plot-not-theme", "contradicts-text"],
        [
          "Which statement best expresses a theme of the story?",
          "Progress can be measured against your own past, not only against other people.",
          ["Running", "Wren finishes ninety-first in the county race and writes her time in a notebook on the bus home.", "Hard work always leads to winning a medal."],
          ["But it was forty-one seconds faster than her best race before today."],
          "Wren places near the bottom, yet she counts the race as her best because she beat her own time. The story values that kind of progress.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "El progreso se puede medir contra tu propio pasado, no solo contra los demás.",
          ["Correr", "Wren llega en el lugar noventa y uno en la carrera del condado y anota su tiempo en un cuaderno en el autobús.", "El esfuerzo siempre lleva a ganar una medalla."],
          ["Pero eran cuarenta y un segundos menos que su mejor carrera hasta ese día."],
          "Wren llega entre las últimas, pero cuenta la carrera como la mejor porque superó su propio tiempo. El cuento valora ese tipo de progreso.",
        ],
      ),
      q(
        "theme.develop",
        ["wrong-character", "misses-the-change", "off-point-evidence"],
        [
          "How does the contrast between Wren and her teammates after the race develop the theme?",
          "They are upset about their places, while Wren is content because she beat her own best time.",
          ["Jada missed a medal by only two places, which shows that she is the strongest runner on the whole team.", "Wren used to let faster runners pass her without a fight.", "There were ninety-four runners in the county championship."],
          ["Near the team tent, her teammates were miserable."],
          "Her teammates judge their races by place and feel miserable. Wren judges hers by her own past and feels satisfied, which sharpens the story's point about measuring progress.",
        ],
        [
          "¿Cómo desarrolla el mensaje el contraste entre Wren y sus compañeras después de la carrera?",
          "Ellas están tristes por su lugar, mientras que Wren está contenta porque superó su mejor tiempo.",
          ["Jada se quedó sin medalla por dos lugares, lo que muestra que es la corredora más fuerte del equipo.", "Wren antes dejaba que las corredoras más rápidas la rebasaran sin luchar.", "En el campeonato del condado había noventa y cuatro corredoras."],
          ["Cerca de la carpa del equipo, sus compañeras estaban deshechas."],
          "Sus compañeras juzgan su carrera por el lugar y se sienten deshechas. Wren juzga la suya por su propio pasado y se siente satisfecha, lo que hace más clara la idea del cuento sobre medir el progreso.",
        ],
      ),
      q(
        "infer.what",
        ["contradicts-text", "not-in-text", "overgeneralizes"],
        [
          "Why does Wren not tell anyone where she placed?",
          "Her place is not what matters to her, and others would not see her race as a success.",
          ["She is ashamed of her race and wants to quit the team.", "She wants to surprise her coach with the result at practice on Monday, in front of the whole team.", "Slow runners never talk about their races."],
          ["Ninety-first out of ninety-four was not good, not by any measure the county used."],
          "Wren knows her place sounds bad to everyone else. What matters to her is her time, which is a personal best, so telling her place would miss the point.",
        ],
        [
          "¿Por qué Wren no le dice a nadie en qué lugar llegó?",
          "Su lugar no es lo que le importa, y las demás no verían su carrera como un éxito.",
          ["Le da vergüenza su carrera y quiere dejar el equipo.", "Quiere sorprender a la entrenadora con el resultado en la práctica del lunes, delante de todo el equipo.", "Las corredoras lentas nunca hablan de sus carreras."],
          ["El lugar noventa y uno de noventa y cuatro no era bueno, no según ninguna medida del condado."],
          "Wren sabe que su lugar suena mal para todas las demás. Lo que le importa es su tiempo, que es su mejor marca, así que decir su lugar no tendría sentido.",
        ],
      ),
      q(
        "words.tone",
        ["opposite-tone", "ignores-connotation", "contradicts-text"],
        [
          "Which phrase best describes the tone of the final paragraph?",
          "Quietly satisfied",
          ["Bitter", "Boastful", "Coldly indifferent"],
          ["and wrote it down"],
          "Wren states a plain fact about her progress and records it. There is no bragging and no bitterness, only calm pride in getting better.",
        ],
        [
          "¿Qué frase describe mejor el tono del último párrafo?",
          "Sereno y satisfecho",
          ["Amargo", "Presumido", "Indiferente y distante"],
          ["y lo anotó"],
          "Wren dice un hecho sencillo sobre su progreso y lo anota. No hay presunción ni amargura, solo un orgullo tranquilo por mejorar.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Wren, the slowest runner on her team, focuses on beating her own best time and finishes forty-one seconds faster, content even though she places near the bottom.",
          ["Wren deserves a medal more than her teammates do, and the county should give awards for improvement instead of only for speed and places, because effort matters more than talent.", "A Westfield runner passes Wren at the two-mile mark, Sofia falls near a creek, and the team rides a bus home.", "Wren finally finishes in the top half of the race and wins a medal for her team."],
          ["She tried to beat 29:58."],
          "A good summary includes Wren's goal, her result, and why she is satisfied, without opinions about who deserves what.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Wren, la corredora más lenta de su equipo, se concentra en superar su mejor tiempo y lo baja cuarenta y un segundos, contenta aunque llega entre las últimas.",
          ["Wren merece una medalla más que sus compañeras, y el condado debería premiar la mejora en lugar de solo la velocidad y los lugares, porque el esfuerzo importa más que el talento.", "Una corredora de Westfield rebasa a Wren en la marca de las dos millas, Sofía se cae cerca de un arroyo y el equipo regresa en autobús.", "Wren por fin termina en la mitad de arriba de la carrera y gana una medalla para su equipo."],
          ["Intentó ganarle a 29:58."],
          "Un buen resumen incluye la meta de Wren, su resultado y por qué está satisfecha, sin opiniones sobre quién merece qué.",
        ],
      ),
    ],
  },
  {
    id: "perfect-picture",
    level: 2,
    genre: "story",
    en: [
      {
        title: "The Perfect Picture",
        paras: [
          "Nadia had planned the photograph for months. The total eclipse would pass over her grandparents' town in Texas for about four minutes, and she was going to capture all of it: the black disk of the moon, the pale ring of light around it, the strange twilight in the middle of the day. She had watched eleven videos about camera settings. She had a tripod, a special filter, and a checklist taped to her phone case.",
          "At 1:30 the light began to change. Shadows sharpened. The air grew cooler, and the birds in her grandfather's pecan trees went quiet one by one, as if someone were turning down a radio. Her little brother, Sami, lay down on the grass with his paper eclipse glasses and stopped talking, which Nadia had never seen him do.",
          "Then totality came, and Nadia's screen went black. The filter. She had forgotten to take off the filter. She pulled it off, and the picture came back far too bright, a white smear. She changed one setting, then another, her thumbs moving faster and faster, while somewhere above her the sky did something that made Sami gasp.",
          "“Nadia,” her grandmother said quietly. “Look up.”",
          "“One second,” Nadia said. “I almost have it.”",
          "By the time she got the settings right, the first bright bead of sunlight was already slipping out from behind the moon. Totality was over. Her photograph showed a perfect glowing ring, sharp enough to post. Three hundred people would like it by dinner.",
          "That night, Sami would not stop talking. He described the stars that had come out in the middle of the day, the orange glow all along the horizon, and the way the edge of the moon had looked like it was on fire. Nadia listened and scrolled through her pictures. Every one of them was sharp. None of them looked anything like what he was describing.",
        ],
      },
    ],
    es: [
      {
        title: "La foto perfecta",
        paras: [
          "Nadia llevaba meses planeando la foto. El eclipse total iba a pasar sobre el pueblo de sus abuelos en Texas durante unos cuatro minutos, y ella iba a captarlo todo: el disco negro de la luna, el anillo de luz pálida a su alrededor, el extraño anochecer a mitad del día. Había visto once videos sobre la configuración de la cámara. Tenía un tripié, un filtro especial y una lista pegada en la funda del teléfono.",
          "A la 1:30 la luz empezó a cambiar. Las sombras se volvieron más nítidas. El aire se enfrió, y los pájaros de los nogales de su abuelo se callaron uno por uno, como si alguien le bajara el volumen a un radio. Su hermanito, Sami, se acostó en el pasto con sus lentes de papel para eclipses y dejó de hablar, algo que Nadia nunca le había visto hacer.",
          "Entonces llegó la totalidad, y la pantalla de Nadia se puso negra. El filtro. Se le había olvidado quitar el filtro. Lo arrancó, y la imagen volvió demasiado brillante, una mancha blanca. Cambió un ajuste, luego otro, con los pulgares cada vez más rápidos, mientras en algún lugar sobre ella el cielo hacía algo que le sacó a Sami un grito ahogado.",
          "—Nadia —le dijo su abuela en voz baja—. Mira hacia arriba.",
          "—Un segundo —dijo Nadia—. Ya casi la tengo.",
          "Cuando por fin logró los ajustes correctos, la primera gota brillante de sol ya se asomaba por detrás de la luna. La totalidad había terminado. Su foto mostraba un anillo luminoso perfecto, lo bastante nítido para publicarlo. Trescientas personas le darían me gusta antes de la cena.",
          "Esa noche, Sami no dejaba de hablar. Describió las estrellas que habían salido a mitad del día, el resplandor naranja a lo largo de todo el horizonte y cómo el borde de la luna parecía estar en llamas. Nadia lo escuchaba mientras pasaba sus fotos. Todas eran nítidas. Ninguna se parecía en nada a lo que él describía.",
        ],
      },
    ],
    qs: [
      q(
        "theme.statement",
        ["topic-not-theme", "plot-not-theme", "not-in-text"],
        [
          "Which statement best expresses a theme of the story?",
          "Trying to record a moment perfectly can keep you from actually living it.",
          ["Eclipses", "Nadia photographs the eclipse at her grandparents' house while her brother watches it from the grass.", "Expensive cameras always take better pictures than phones."],
          ["None of them looked anything like what he was describing."],
          "Nadia gets a sharp photo but misses the eclipse itself, while Sami, who only watched, saw everything. The story's message comes from that contrast.",
        ],
        [
          "¿Qué oración expresa mejor un mensaje del cuento?",
          "Intentar grabar un momento a la perfección puede impedirte vivirlo de verdad.",
          ["Los eclipses", "Nadia fotografía el eclipse en casa de sus abuelos mientras su hermano lo mira desde el pasto.", "Las cámaras caras siempre toman mejores fotos que los teléfonos."],
          ["Ninguna se parecía en nada a lo que él describía."],
          "Nadia logra una foto nítida, pero se pierde el eclipse, mientras que Sami, que solo miró, lo vio todo. El mensaje del cuento sale de ese contraste.",
        ],
      ),
      q(
        "theme.develop",
        ["contradicts-text", "contradicts-text", "not-in-text"],
        [
          "How does the author use Sami to develop the theme?",
          "Sami simply watches, so he sees what Nadia misses while she works on her photo.",
          ["Sami forgets his eclipse glasses and cannot look at the sky at all.", "Sami helps Nadia fix her camera settings during totality so that she gets the shot.", "Sami posts his own photograph of the eclipse online that night."],
          ["He described the stars that had come out in the middle of the day"],
          "Sami lies on the grass and watches. His detailed description that night shows everything Nadia missed while she was fixing her settings.",
        ],
        [
          "¿Cómo usa el autor a Sami para desarrollar el mensaje?",
          "Sami solo mira, así que ve lo que Nadia se pierde mientras trabaja en su foto.",
          ["Sami olvida sus lentes para eclipses y no puede mirar el cielo.", "Sami ayuda a Nadia a corregir los ajustes de la cámara durante la totalidad para que logre la foto.", "Sami publica su propia foto del eclipse esa noche."],
          ["Describió las estrellas que habían salido a mitad del día"],
          "Sami se acuesta en el pasto y mira. Lo que describe con detalle esa noche muestra todo lo que Nadia se perdió mientras arreglaba los ajustes.",
        ],
      ),
      q(
        "infer.what",
        ["not-in-text", "contradicts-text", "overgeneralizes"],
        [
          "Why does Nadia answer “One second” when her grandmother tells her to look up?",
          "She is so focused on the shot that she does not realize totality is passing.",
          ["She is afraid to look up at the sky without her eclipse glasses, even during totality.", "She cannot hear her grandmother over the noise of a crowd.", "Teenagers never listen to their grandparents."],
          ["I almost have it."],
          "Nadia thinks she is about to get the picture, so she puts off looking. By the time she finishes, the four minutes are over.",
        ],
        [
          "¿Por qué Nadia contesta “Un segundo” cuando su abuela le dice que mire hacia arriba?",
          "Está tan concentrada en la foto que no se da cuenta de que la totalidad se le está pasando.",
          ["Le da miedo mirar hacia el cielo sin sus lentes para eclipses, aunque ya haya llegado la totalidad.", "No oye a su abuela por el ruido de una multitud.", "Los adolescentes nunca escuchan a sus abuelos."],
          ["Ya casi la tengo."],
          "Nadia cree que está a punto de lograr la foto, así que deja para después mirar. Cuando termina, los cuatro minutos ya pasaron.",
        ],
      ),
      q(
        "words.connotation",
        ["too-literal", "ignores-connotation", "contradicts-text"],
        [
          "In paragraph 6, the narrator says the photograph was “sharp enough to post.” What does this phrase suggest?",
          "The photo's value lies in being shared, not in what Nadia saw.",
          ["The photo is sharp enough to cut someone's finger.", "The photo is the most meaningful thing Nadia has ever made in her life.", "The photo is too blurry for anyone to recognize."],
          ["Three hundred people would like it by dinner."],
          "The narrator measures the photo by whether it can be posted and how many likes it will get. That night Nadia sees that the pictures miss what Sami saw, which shows how empty that measure is.",
        ],
        [
          "En el párrafo 6, el narrador dice que la foto mostraba un anillo “lo bastante nítido para publicarlo”. ¿Qué sugiere esta frase?",
          "El valor de la foto está en compartirla, no en lo que Nadia vio.",
          ["La foto es tan nítida que podría cortarle un dedo a alguien.", "La foto es lo más significativo que Nadia ha hecho en toda su vida hasta ahora.", "La foto está tan borrosa que nadie la reconocería."],
          ["Trescientas personas le darían me gusta antes de la cena."],
          "El narrador mide la foto por si se puede publicar y cuántos me gusta tendrá. Esa noche Nadia ve que las fotos no muestran lo que vio Sami, lo que deja ver lo vacía que es esa medida.",
        ],
      ),
      q(
        "central.summary",
        ["adds-opinion", "misses-key-point", "contradicts-text"],
        [
          "Which is the best objective summary of the story?",
          "Nadia spends the eclipse fixing her camera and gets a sharp photo only after totality ends. Hearing her brother describe it, she realizes she missed the real event.",
          ["Nadia should never have brought a camera, and families who stare at their phones during special events are ruining those once-in-a-lifetime moments for everyone else around them.", "Nadia watches eleven videos, buys a tripod, tapes a checklist to her phone case, and hears birds in pecan trees.", "Nadia takes a blurry photo of the eclipse, so she deletes every picture she took that day."],
          ["Totality was over."],
          "A good summary includes Nadia's plan, the mistake that costs her the eclipse, the photo she gets too late, and what she realizes, without opinions.",
        ],
        [
          "¿Cuál es el mejor resumen objetivo del cuento?",
          "Nadia pasa el eclipse arreglando la cámara y logra una foto nítida solo cuando termina la totalidad. Al oír a su hermano describirlo, se da cuenta de que se perdió lo que de verdad pasó.",
          ["Nadia nunca debió llevar una cámara, y las familias que se pasan mirando el teléfono durante los momentos especiales, como un eclipse que ocurre una vez en la vida, se los arruinan a todos los demás.", "Nadia ve once videos, compra un tripié, pega una lista en la funda del teléfono y oye pájaros en los nogales.", "Nadia toma una foto borrosa del eclipse, así que borra todas las fotos que tomó ese día."],
          ["La totalidad había terminado."],
          "Un buen resumen incluye el plan de Nadia, el error que le cuesta el eclipse, la foto que logra demasiado tarde y lo que comprende, sin opiniones.",
        ],
      ),
    ],
  },
];
